/* eslint-disable @stylistic/max-len */

import type {
	bool_string as docs_json_ts_common_types_bool_string,
	decimal_string as docs_json_ts_common_types_decimal_string,
	decimal_string_signed as docs_json_ts_common_types_decimal_string_signed,
	empty_object as docs_json_ts_common_types_empty_object,
	integer_string as docs_json_ts_common_types_integer_string,
	integer_string_signed as docs_json_ts_common_types_integer_string_signed,
	RGBA as docs_json_ts_common_types_RGBA,
	XYZ_decimal_string as docs_json_ts_common_types_XYZ_decimal_string,
	XYZW_decimal_string as docs_json_ts_common_types_XYZW_decimal_string,
} from './../common/types.ts';

import type {
	FalloffCurve_EditorCurveData as docs_json_ts_1_1_2_2_properties_FalloffCurve_EditorCurveData,
	FalloffCurve_EditorCurveData_with_ExternalCurve as docs_json_ts_1_1_2_2_properties_FalloffCurve_EditorCurveData_with_ExternalCurve,
	mHologramOverrides_item as docs_json_ts_1_1_2_2_properties_mHologramOverrides_item,
	Montages as docs_json_ts_1_1_2_2_properties_Montages,
	mPoleVariations_item as docs_json_ts_1_1_2_2_properties_mPoleVariations_item,
	mSoftAudioEvents as docs_json_ts_1_1_2_2_properties_mSoftAudioEvents,
	mStatisticGameplayTag as docs_json_ts_1_1_2_2_properties_mStatisticGameplayTag,
	WidgetClass as docs_json_ts_1_1_2_2_properties_WidgetClass,
} from './types/properties.ts';

import type {
	FGAmmoType_base as docs_json_ts_0_6_1_5_classes_base_FGAmmoType_base,
	FGAmmoType_version_specific as docs_json_ts_0_6_1_5_classes_base_FGAmmoType_version_specific,
	FGAmmoTypeInstantHit_Desc_CartridgeChaos_C_version_specific as docs_json_ts_0_6_1_5_classes_base_FGAmmoTypeInstantHit_Desc_CartridgeChaos_C_version_specific,
	FGAmmoTypeInstantHit_version_specific as docs_json_ts_0_6_1_5_classes_base_FGAmmoTypeInstantHit_version_specific,
	FGAmmoTypeProjectile_version_specific as docs_json_ts_0_6_1_5_classes_base_FGAmmoTypeProjectile_version_specific,
	FGAmmoTypeSpreadshot_version_specific as docs_json_ts_0_6_1_5_classes_base_FGAmmoTypeSpreadshot_version_specific,
	FGBuildable_base_version_specific as docs_json_ts_0_6_1_5_classes_base_FGBuildable_base_version_specific,
	FGBuildable_foundation_mDisableSnapOn as docs_json_ts_0_6_1_5_classes_base_FGBuildable_foundation_mDisableSnapOn,
	FGBuildable_with_depth as docs_json_ts_0_6_1_5_classes_base_FGBuildable_with_depth,
	FGBuildableFoundation_version_specific as docs_json_ts_0_6_1_5_classes_base_FGBuildableFoundation_version_specific,
	FGBuildableManufacturer_Build_SmelterMk1_C_base as docs_json_ts_0_6_1_5_classes_base_FGBuildableManufacturer_Build_SmelterMk1_C_base,
	FGBuildablePipeline_version_specific as docs_json_ts_0_6_1_5_classes_base_FGBuildablePipeline_version_specific,
	FGBuildableRadarTower_version_specific as docs_json_ts_0_6_1_5_classes_base_FGBuildableRadarTower_version_specific,
	FGBuildableResourceExtractor_base_version_specific_base as docs_json_ts_0_6_1_5_classes_base_FGBuildableResourceExtractor_base_version_specific_base,
	FGBuildableTrainPlatformCargo_version_specific as docs_json_ts_0_6_1_5_classes_base_FGBuildableTrainPlatformCargo_version_specific,
	FGChainsaw_version_specific as docs_json_ts_0_6_1_5_classes_base_FGChainsaw_version_specific,
	FGDescriptor as docs_json_ts_0_6_1_5_classes_base_FGDescriptor,
	FGEquipment_noisy_version_specific as docs_json_ts_0_6_1_5_classes_base_FGEquipment_noisy_version_specific,
	FGEquipment_version_specific as docs_json_ts_0_6_1_5_classes_base_FGEquipment_version_specific,
	FGEquipmentStunSpear_base_version_specific as docs_json_ts_0_6_1_5_classes_base_FGEquipmentStunSpear_base_version_specific,
	FGItemDescriptor_version_specific as docs_json_ts_0_6_1_5_classes_base_FGItemDescriptor_version_specific,
	FGJumpingStilts_version_specific as docs_json_ts_0_6_1_5_classes_base_FGJumpingStilts_version_specific,
	FGSchematic_version_specific as docs_json_ts_0_6_1_5_classes_base_FGSchematic_version_specific,
	FGSuitBase_version_specific as docs_json_ts_0_6_1_5_classes_base_FGSuitBase_version_specific,
	FGWeapon_base as docs_json_ts_0_6_1_5_classes_base_FGWeapon_base,
	has_mIsInverted as docs_json_ts_0_6_1_5_classes_base_has_mIsInverted,
} from './../0.6.1.5/classes/Base.ts';

import type {
	FGAmmoType_base as docs_json_ts_0_6_1_5_classes_base_overridable_FGAmmoType_base,
	FGAmmoType_version_specific as docs_json_ts_0_6_1_5_classes_base_overridable_FGAmmoType_version_specific,
	FGAmmoTypeProjectile_version_specific as docs_json_ts_0_6_1_5_classes_base_overridable_FGAmmoTypeProjectile_version_specific,
	FGBuildable_base_version_specific as docs_json_ts_0_6_1_5_classes_base_overridable_FGBuildable_base_version_specific,
	FGBuildableRadarTower_version_specific as docs_json_ts_0_6_1_5_classes_base_overridable_FGBuildableRadarTower_version_specific,
	FGItemDescriptor_version_specific as docs_json_ts_0_6_1_5_classes_base_overridable_FGItemDescriptor_version_specific,
} from './../0.6.1.5/classes/Base.1.1.2.2.ts';

import type {
	FGAmmoType_version_specific as docs_json_ts_0_8_3_3_classes_base_overridable_FGAmmoType_version_specific,
	FGBuildableRailroadTrack_version_specific as docs_json_ts_0_8_3_3_classes_base_overridable_FGBuildableRailroadTrack_version_specific,
	FGConsumableEquipment_version_specific as docs_json_ts_0_8_3_3_classes_base_overridable_FGConsumableEquipment_version_specific,
	FGEquipment_version_specific as docs_json_ts_0_8_3_3_classes_base_overridable_FGEquipment_version_specific,
	FGSchematic_has_mSchematicIcon as docs_json_ts_0_8_3_3_classes_base_overridable_FGSchematic_has_mSchematicIcon,
	FGSchematic_version_specific as docs_json_ts_0_8_3_3_classes_base_overridable_FGSchematic_version_specific,
} from './../0.8.3.3/classes/Base.1.1.2.2.ts';

import type {
	FGAmmoTypeProjectile_version_specific as docs_json_ts_1_0_1_4_classes_base_FGAmmoTypeProjectile_version_specific,
	FGBuildable_base as docs_json_ts_1_0_1_4_classes_base_FGBuildable_base,
	FGBuildable_powered as docs_json_ts_1_0_1_4_classes_base_FGBuildable_powered,
	FGBuildable_powered_version_specific as docs_json_ts_1_0_1_4_classes_base_FGBuildable_powered_version_specific,
	FGBuildable_version_specific as docs_json_ts_1_0_1_4_classes_base_FGBuildable_version_specific,
	FGBuildableBlueprintDesigner_version_specific as docs_json_ts_1_0_1_4_classes_base_FGBuildableBlueprintDesigner_version_specific,
	FGBuildableConveyorBelt_version_specific as docs_json_ts_1_0_1_4_classes_base_FGBuildableConveyorBelt_version_specific,
	FGBuildableConveyorLift_version_specific as docs_json_ts_1_0_1_4_classes_base_FGBuildableConveyorLift_version_specific,
	FGBuildableDroneStation_version_specific as docs_json_ts_1_0_1_4_classes_base_FGBuildableDroneStation_version_specific,
	FGBuildableGenerator as docs_json_ts_1_0_1_4_classes_base_FGBuildableGenerator,
	FGBuildableGenerator_no_fuel as docs_json_ts_1_0_1_4_classes_base_FGBuildableGenerator_no_fuel,
	FGBuildableGenerator_version_specific as docs_json_ts_1_0_1_4_classes_base_FGBuildableGenerator_version_specific,
	FGBuildableGeneratorFuel_biomass_version_specific as docs_json_ts_1_0_1_4_classes_base_FGBuildableGeneratorFuel_biomass_version_specific,
	FGBuildableGeneratorFuel_fuel_version_specific as docs_json_ts_1_0_1_4_classes_base_FGBuildableGeneratorFuel_fuel_version_specific,
	FGBuildableGeneratorNuclear_version_specific as docs_json_ts_1_0_1_4_classes_base_FGBuildableGeneratorNuclear_version_specific,
	FGBuildableMAM_version_specific as docs_json_ts_1_0_1_4_classes_base_FGBuildableMAM_version_specific,
	FGBuildableManufacturer_Build_ConstructorMk1_C_version_specific as docs_json_ts_1_0_1_4_classes_base_FGBuildableManufacturer_Build_ConstructorMk1_C_version_specific,
	FGBuildableManufacturer_Build_QuantumEncoder_C_version_specific as docs_json_ts_1_0_1_4_classes_base_FGBuildableManufacturer_Build_QuantumEncoder_C_version_specific,
	FGBuildablePipeline_version_specific as docs_json_ts_1_0_1_4_classes_base_FGBuildablePipeline_version_specific,
	FGBuildablePipelinePump_version_specific as docs_json_ts_1_0_1_4_classes_base_FGBuildablePipelinePump_version_specific,
	FGBuildablePortal_common as docs_json_ts_1_0_1_4_classes_base_FGBuildablePortal_common,
	FGBuildablePortal_version_specific as docs_json_ts_1_0_1_4_classes_base_FGBuildablePortal_version_specific,
	FGBuildablePortalSatellite_version_specific as docs_json_ts_1_0_1_4_classes_base_FGBuildablePortalSatellite_version_specific,
	FGBuildablePowerBooster_version_specific as docs_json_ts_1_0_1_4_classes_base_FGBuildablePowerBooster_version_specific,
	FGBuildablePowerStorage_version_specific as docs_json_ts_1_0_1_4_classes_base_FGBuildablePowerStorage_version_specific,
	FGBuildableResourceExtractor_miner_mk1_version_specific as docs_json_ts_1_0_1_4_classes_base_FGBuildableResourceExtractor_miner_mk1_version_specific,
	FGBuildableSnowCannon_version_specific as docs_json_ts_1_0_1_4_classes_base_FGBuildableSnowCannon_version_specific,
	FGBuildableSpaceElevator_version_specific as docs_json_ts_1_0_1_4_classes_base_FGBuildableSpaceElevator_version_specific,
	FGBuildableTradingPost_version_specific as docs_json_ts_1_0_1_4_classes_base_FGBuildableTradingPost_version_specific,
	FGBuildableTrainPlatform_version_specific as docs_json_ts_1_0_1_4_classes_base_FGBuildableTrainPlatform_version_specific,
	FGBuildableWidgetSign_version_specific as docs_json_ts_1_0_1_4_classes_base_FGBuildableWidgetSign_version_specific,
	FGCentralStorageContainer_version_specific as docs_json_ts_1_0_1_4_classes_base_FGCentralStorageContainer_version_specific,
	FGChainsaw_version_specific as docs_json_ts_1_0_1_4_classes_base_FGChainsaw_version_specific,
	FGConsumableEquipment_base_version_specific as docs_json_ts_1_0_1_4_classes_base_FGConsumableEquipment_base_version_specific,
	FGConsumableEquipment_medkit_version_specific as docs_json_ts_1_0_1_4_classes_base_FGConsumableEquipment_medkit_version_specific,
	FGEquipment as docs_json_ts_1_0_1_4_classes_base_FGEquipment,
	FGEquipment_version_specific as docs_json_ts_1_0_1_4_classes_base_FGEquipment_version_specific,
	FGEquipmentStunSpear_version_specific as docs_json_ts_1_0_1_4_classes_base_FGEquipmentStunSpear_version_specific,
	FGEquipmentZipline_version_specific as docs_json_ts_1_0_1_4_classes_base_FGEquipmentZipline_version_specific,
	FGGolfCartDispenser_version_specific as docs_json_ts_1_0_1_4_classes_base_FGGolfCartDispenser_version_specific,
	FGHoverPack_version_specific as docs_json_ts_1_0_1_4_classes_base_FGHoverPack_version_specific,
	FGItemDescriptor_version_specific as docs_json_ts_1_0_1_4_classes_base_FGItemDescriptor_version_specific,
	FGJetPack_version_specific as docs_json_ts_1_0_1_4_classes_base_FGJetPack_version_specific,
	FGNobeliskDetonator_version_specific as docs_json_ts_1_0_1_4_classes_base_FGNobeliskDetonator_version_specific,
	FGObjectScanner_version_specific as docs_json_ts_1_0_1_4_classes_base_FGObjectScanner_version_specific,
	FGParachute_version_specific as docs_json_ts_1_0_1_4_classes_base_FGParachute_version_specific,
	FGPortableMinerDispenser_version_specific as docs_json_ts_1_0_1_4_classes_base_FGPortableMinerDispenser_version_specific,
	FGSchematic_has_mTechTier as docs_json_ts_1_0_1_4_classes_base_FGSchematic_has_mTechTier,
	FGSchematic_version_specific as docs_json_ts_1_0_1_4_classes_base_FGSchematic_version_specific,
	FGSuitBase_version_specific as docs_json_ts_1_0_1_4_classes_base_FGSuitBase_version_specific,
	FGWeapon_version_specific as docs_json_ts_1_0_1_4_classes_base_FGWeapon_version_specific,
	has_SAMReference as docs_json_ts_1_0_1_4_classes_base_has_SAMReference,
} from './../1.0.1.4/Base.ts';

import type {
	has_mSubCategories as docs_json_ts_0_6_1_5_overridable_has_mSubCategories,
} from './../0.6.1.5/types/overridable--1.1.2.2.ts';

import type {
	FGAmmoTypeProjectile_version_specific as docs_json_ts_0_8_3_3_classes_base_FGAmmoTypeProjectile_version_specific,
	FGBuildable_has_mOnCircuitsChanged as docs_json_ts_0_8_3_3_classes_base_FGBuildable_has_mOnCircuitsChanged,
	FGBuildable_version_specific as docs_json_ts_0_8_3_3_classes_base_FGBuildable_version_specific,
	FGBuildable_with_mTickExponent as docs_json_ts_0_8_3_3_classes_base_FGBuildable_with_mTickExponent,
	FGBuildableBlueprintDesigner_version_specific as docs_json_ts_0_8_3_3_classes_base_FGBuildableBlueprintDesigner_version_specific,
	FGBuildableConveyorBelt_version_specific as docs_json_ts_0_8_3_3_classes_base_FGBuildableConveyorBelt_version_specific,
	FGBuildableJumppad_version_specific as docs_json_ts_0_8_3_3_classes_base_FGBuildableJumppad_version_specific,
	FGBuildablePassthrough_version_specific as docs_json_ts_0_8_3_3_classes_base_FGBuildablePassthrough_version_specific,
	FGBuildablePowerPole_version_specific as docs_json_ts_0_8_3_3_classes_base_FGBuildablePowerPole_version_specific,
	FGBuildablePriorityPowerSwitch_version_specific as docs_json_ts_0_8_3_3_classes_base_FGBuildablePriorityPowerSwitch_version_specific,
	FGBuildableRailroadSignal_version_specific as docs_json_ts_0_8_3_3_classes_base_FGBuildableRailroadSignal_version_specific,
	FGBuildableWidgetSign_version_specific as docs_json_ts_0_8_3_3_classes_base_FGBuildableWidgetSign_version_specific,
	FGBuildableWire_version_specific as docs_json_ts_0_8_3_3_classes_base_FGBuildableWire_version_specific,
	FGChainsaw_version_specific as docs_json_ts_0_8_3_3_classes_base_FGChainsaw_version_specific,
	FGEquipmentStunSpear_base_version_specific as docs_json_ts_0_8_3_3_classes_base_FGEquipmentStunSpear_base_version_specific,
	FGGasMask_version_specific as docs_json_ts_0_8_3_3_classes_base_FGGasMask_version_specific,
	FGJetPack_version_specific as docs_json_ts_0_8_3_3_classes_base_FGJetPack_version_specific,
	FGObjectScanner_version_specific as docs_json_ts_0_8_3_3_classes_base_FGObjectScanner_version_specific,
	FGParachute_version_specific as docs_json_ts_0_8_3_3_classes_base_FGParachute_version_specific,
} from './../0.8.3.3/classes/Base.ts';

import type {
	FGBuildable_base_version_specific as docs_json_ts_0_3_7_7_classes_base_FGBuildable_base_version_specific,
	FGBuildable_docking_station_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildable_docking_station_base_base_base,
	FGBuildable_docking_station_base_with_mMapText as docs_json_ts_0_3_7_7_classes_base_FGBuildable_docking_station_base_with_mMapText,
	FGBuildable_occupied_base as docs_json_ts_0_3_7_7_classes_base_FGBuildable_occupied_base,
	FGBuildable_powered_storage_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildable_powered_storage_base_base_base,
	FGBuildable_powered_version_specific as docs_json_ts_0_3_7_7_classes_base_FGBuildable_powered_version_specific,
	FGBuildable_tiered_base as docs_json_ts_0_3_7_7_classes_base_FGBuildable_tiered_base,
	FGBuildable_with_height_and_width_base as docs_json_ts_0_3_7_7_classes_base_FGBuildable_with_height_and_width_base,
	FGBuildable_with_height_base as docs_json_ts_0_3_7_7_classes_base_FGBuildable_with_height_base,
	FGBuildable_with_mLength as docs_json_ts_0_3_7_7_classes_base_FGBuildable_with_mLength,
	FGBuildable_with_size_and_elevation_base as docs_json_ts_0_3_7_7_classes_base_FGBuildable_with_size_and_elevation_base,
	FGBuildable_with_size_and_elevation_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildable_with_size_and_elevation_base_base,
	FGBuildable_with_size_base as docs_json_ts_0_3_7_7_classes_base_FGBuildable_with_size_base,
	FGBuildable_with_width_base as docs_json_ts_0_3_7_7_classes_base_FGBuildable_with_width_base,
	FGBuildableAttachment_has_mCurrentOutputIndex as docs_json_ts_0_3_7_7_classes_base_FGBuildableAttachment_has_mCurrentOutputIndex,
	FGBuildableAttachment_splitter_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableAttachment_splitter_base_base_base,
	FGBuildableAttachmentMerger_version_specific as docs_json_ts_0_3_7_7_classes_base_FGBuildableAttachmentMerger_version_specific,
	FGBuildableConveyorBelt_pre_1_0 as docs_json_ts_0_3_7_7_classes_base_FGBuildableConveyorBelt_pre_1_0,
	FGBuildableConveyorLift_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableConveyorLift_base,
	FGBuildableDockingStation_with_mFuelTransferSpeed_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableDockingStation_with_mFuelTransferSpeed_base,
	FGBuildableFactory_jump_pad_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableFactory_jump_pad_base_base_base,
	FGBuildableFactory_landing_pad_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableFactory_landing_pad_base_base_base,
	FGBuildableFactorySimpleProducer_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableFactorySimpleProducer_base_base,
	FGBuildableGenerator_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableGenerator_base_base_base,
	FGBuildableGenerator_no_fuel_base_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableGenerator_no_fuel_base_base_base_base,
	FGBuildableGeneratorFuel_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableGeneratorFuel_base_base_base,
	FGBuildableGeneratorFuel_coal_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableGeneratorFuel_coal_base_base,
	FGBuildableGeneratorGeoThermal_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableGeneratorGeoThermal_base_base_base,
	FGBuildableGeneratorNuclear_version_specific as docs_json_ts_0_3_7_7_classes_base_FGBuildableGeneratorNuclear_version_specific,
	FGBuildableJumppad_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableJumppad_base_base_base,
	FGBuildableLadder_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableLadder_base,
	FGBuildableManufacturer_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_base_base,
	FGBuildableManufacturer_base_IsPowered_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_IsPowered_base_base,
	FGBuildableManufacturer_base_mProductionEffectsRunning_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_mProductionEffectsRunning_base_base,
	FGBuildableManufacturer_base_packager_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_packager_base_base,
	FGBuildablePipeline_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildablePipeline_base_base,
	FGBuildablePipeline_base_no_indicator_base as docs_json_ts_0_3_7_7_classes_base_FGBuildablePipeline_base_no_indicator_base,
	FGBuildablePipeline_base_root as docs_json_ts_0_3_7_7_classes_base_FGBuildablePipeline_base_root,
	FGBuildablePipelinePump_powered_version_specific as docs_json_ts_0_3_7_7_classes_base_FGBuildablePipelinePump_powered_version_specific,
	FGBuildablePipelinePump_pump_version_specific as docs_json_ts_0_3_7_7_classes_base_FGBuildablePipelinePump_pump_version_specific,
	FGBuildablePipelineSupport_base as docs_json_ts_0_3_7_7_classes_base_FGBuildablePipelineSupport_base,
	FGBuildablePipeReservoir_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildablePipeReservoir_base_base_base,
	FGBuildableRailroadStation_version_specific as docs_json_ts_0_3_7_7_classes_base_FGBuildableRailroadStation_version_specific,
	FGBuildableRailroadTrack_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableRailroadTrack_base,
	FGBuildableResourceExtractor_miner_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_miner_base,
	FGBuildableResourceExtractor_miner_mk2_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_miner_mk2_base_base_base,
	FGBuildableResourceExtractor_miner_mk3_version_specific as docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_miner_mk3_version_specific,
	FGBuildableResourceExtractor_oil_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_oil_base_base_base,
	FGBuildableResourceExtractor_only_allow_certain_resources as docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_only_allow_certain_resources,
	FGBuildableResourceExtractor_piped as docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_piped,
	FGBuildableResourceExtractor_timed as docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_timed,
	FGBuildableResourceExtractor_water_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_water_base_base_base,
	FGBuildableResourceSinkShop_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceSinkShop_base_base_base,
	FGBuildableSplitterSmart_version_specific as docs_json_ts_0_3_7_7_classes_base_FGBuildableSplitterSmart_version_specific,
	FGBuildableStorage_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableStorage_base_base_base,
	FGBuildableTradingPost_version_specific as docs_json_ts_0_3_7_7_classes_base_FGBuildableTradingPost_version_specific,
	FGBuildableTrainPlatform_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableTrainPlatform_base_base_base,
	FGBuildableTrainPlatformCargo_version_specific as docs_json_ts_0_3_7_7_classes_base_FGBuildableTrainPlatformCargo_version_specific,
	FGBuildableWire_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableWire_base,
	FGChainsaw_version_specific as docs_json_ts_0_3_7_7_classes_base_FGChainsaw_version_specific,
	FGConsumableEquipment_version_specific as docs_json_ts_0_3_7_7_classes_base_FGConsumableEquipment_version_specific,
	FGEquipment_has_effect_timer as docs_json_ts_0_3_7_7_classes_base_FGEquipment_has_effect_timer,
	FGEquipment_has_mEquipmentSlot as docs_json_ts_0_3_7_7_classes_base_FGEquipment_has_mEquipmentSlot,
	FGEquipment_has_mFilterDuration as docs_json_ts_0_3_7_7_classes_base_FGEquipment_has_mFilterDuration,
	FGEquipment_negates_damage as docs_json_ts_0_3_7_7_classes_base_FGEquipment_negates_damage,
	FGEquipmentStunSpear_base_version_specific as docs_json_ts_0_3_7_7_classes_base_FGEquipmentStunSpear_base_version_specific,
	FGGasMask_base as docs_json_ts_0_3_7_7_classes_base_FGGasMask_base,
	FGGolfCartDispenser_has_mArmAnimation as docs_json_ts_0_3_7_7_classes_base_FGGolfCartDispenser_has_mArmAnimation,
	FGJetPack_version_specific as docs_json_ts_0_3_7_7_classes_base_FGJetPack_version_specific,
	FGJumpingStilts_base as docs_json_ts_0_3_7_7_classes_base_FGJumpingStilts_base,
	FGNobeliskDetonator_base as docs_json_ts_0_3_7_7_classes_base_FGNobeliskDetonator_base,
	FGObjectScanner_version_specific as docs_json_ts_0_3_7_7_classes_base_FGObjectScanner_version_specific,
	FGParachute_has_mIsDeployed as docs_json_ts_0_3_7_7_classes_base_FGParachute_has_mIsDeployed,
	FGPipeHyperStart_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGPipeHyperStart_base_base_base,
	FGPortableMinerDispenser_version_specific as docs_json_ts_0_3_7_7_classes_base_FGPortableMinerDispenser_version_specific,
	FGSuitBase_base as docs_json_ts_0_3_7_7_classes_base_FGSuitBase_base,
	FGWeaponInstantFire_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGWeaponInstantFire_base_base_base,
	FGWeaponProjectile_has_mAttachSocket as docs_json_ts_0_3_7_7_classes_base_FGWeaponProjectile_has_mAttachSocket,
	FGWeaponProjectile_thrown_base_pre_1_0 as docs_json_ts_0_3_7_7_classes_base_FGWeaponProjectile_thrown_base_pre_1_0,
	has_mMeshLength as docs_json_ts_0_3_7_7_classes_base_has_mMeshLength,
	has_mSplineData as docs_json_ts_0_3_7_7_classes_base_has_mSplineData,
	has_mStackHeight as docs_json_ts_0_3_7_7_classes_base_has_mStackHeight,
	instructive as docs_json_ts_0_3_7_7_classes_base_instructive,
	isDescribed as docs_json_ts_0_3_7_7_classes_base_isDescribed,
} from './../0.3.7.7/classes/Base.ts';

import type {
	FGBuildable_base_version_specific as docs_json_ts_0_4_2_11_classes_base_FGBuildable_base_version_specific,
	FGBuildable_has_mCachedSkeletalMeshes as docs_json_ts_0_4_2_11_classes_base_FGBuildable_has_mCachedSkeletalMeshes,
	FGBuildable_light_related_thing_base as docs_json_ts_0_4_2_11_classes_base_FGBuildable_light_related_thing_base,
	FGBuildable_mHasPower_base as docs_json_ts_0_4_2_11_classes_base_FGBuildable_mHasPower_base,
	FGBuildable_mStopped_audio_stuff_base as docs_json_ts_0_4_2_11_classes_base_FGBuildable_mStopped_audio_stuff_base,
	FGBuildableCircuitSwitch_base as docs_json_ts_0_4_2_11_classes_base_FGBuildableCircuitSwitch_base,
	FGBuildableDroneStation_version_specific as docs_json_ts_0_4_2_11_classes_base_FGBuildableDroneStation_version_specific,
	FGBuildableFloodlight_version_specific as docs_json_ts_0_4_2_11_classes_base_FGBuildableFloodlight_version_specific,
	FGBuildableFrackingActivator_version_specific as docs_json_ts_0_4_2_11_classes_base_FGBuildableFrackingActivator_version_specific,
	FGBuildableGeneratorFuel_base_base_base as docs_json_ts_0_4_2_11_classes_base_FGBuildableGeneratorFuel_base_base_base,
	FGBuildableGeneratorGeoThermal_base as docs_json_ts_0_4_2_11_classes_base_FGBuildableGeneratorGeoThermal_base,
	FGBuildableGeneratorNuclear_version_specific as docs_json_ts_0_4_2_11_classes_base_FGBuildableGeneratorNuclear_version_specific,
	FGBuildableLightsControlPanel_base as docs_json_ts_0_4_2_11_classes_base_FGBuildableLightsControlPanel_base,
	FGBuildableLightSource_version_specific as docs_json_ts_0_4_2_11_classes_base_FGBuildableLightSource_version_specific,
	FGBuildableMAM_version_specific as docs_json_ts_0_4_2_11_classes_base_FGBuildableMAM_version_specific,
	FGBuildableManufacturer_base_blender_base_base as docs_json_ts_0_4_2_11_classes_base_FGBuildableManufacturer_base_blender_base_base,
	FGBuildableManufacturer_Build_HadronCollider_C_base as docs_json_ts_0_4_2_11_classes_base_FGBuildableManufacturer_Build_HadronCollider_C_base,
	FGBuildableManufacturerVariablePower as docs_json_ts_0_4_2_11_classes_base_FGBuildableManufacturerVariablePower,
	FGBuildablePipelineJunction_base_base_base as docs_json_ts_0_4_2_11_classes_base_FGBuildablePipelineJunction_base_base_base,
	FGBuildablePowerStorage_base as docs_json_ts_0_4_2_11_classes_base_FGBuildablePowerStorage_base,
	FGBuildableResourceExtractor_miner_mk1_version_specific as docs_json_ts_0_4_2_11_classes_base_FGBuildableResourceExtractor_miner_mk1_version_specific,
	FGBuildableResourceExtractor_water_base as docs_json_ts_0_4_2_11_classes_base_FGBuildableResourceExtractor_water_base,
	FGBuildableResourceSink_base_base as docs_json_ts_0_4_2_11_classes_base_FGBuildableResourceSink_base_base,
	FGBuildableTradingPost_base_version_specific as docs_json_ts_0_4_2_11_classes_base_FGBuildableTradingPost_base_version_specific,
	FGConsumableEquipment_version_specific as docs_json_ts_0_4_2_11_classes_base_FGConsumableEquipment_version_specific,
	FGEquipmentZipline_version_specific as docs_json_ts_0_4_2_11_classes_base_FGEquipmentZipline_version_specific,
	FGHoverPack_version_specific as docs_json_ts_0_4_2_11_classes_base_FGHoverPack_version_specific,
	FGPortableMinerDispenser_version_specific as docs_json_ts_0_4_2_11_classes_base_FGPortableMinerDispenser_version_specific,
	FGWeaponProjectile_has_mBlockSprintWhenFiring as docs_json_ts_0_4_2_11_classes_base_FGWeaponProjectile_has_mBlockSprintWhenFiring,
	has_mInventorySize as docs_json_ts_0_4_2_11_classes_base_has_mInventorySize,
	has_mPowerConsumption as docs_json_ts_0_4_2_11_classes_base_has_mPowerConsumption,
} from './../0.4.2.11/classes/Base.ts';

import type {
	FGBuildable_base_version_specific as docs_json_ts_0_5_2_1_classes_base_FGBuildable_base_version_specific,
	FGBuildable_isFrame as docs_json_ts_0_5_2_1_classes_base_FGBuildable_isFrame,
	FGBuildable_mSnappedPassthroughs as docs_json_ts_0_5_2_1_classes_base_FGBuildable_mSnappedPassthroughs,
	FGBuildable_powered_base_base as docs_json_ts_0_5_2_1_classes_base_FGBuildable_powered_base_base,
	FGBuildable_with_elevation as docs_json_ts_0_5_2_1_classes_base_FGBuildable_with_elevation,
	FGBuildableBeam_base as docs_json_ts_0_5_2_1_classes_base_FGBuildableBeam_base,
	FGBuildableConveyorBelt_version_specific as docs_json_ts_0_5_2_1_classes_base_FGBuildableConveyorBelt_version_specific,
	FGBuildableDockingStation_base as docs_json_ts_0_5_2_1_classes_base_FGBuildableDockingStation_base,
	FGBuildableDoor_automated_version_specific as docs_json_ts_0_5_2_1_classes_base_FGBuildableDoor_automated_version_specific,
	FGBuildableDoor_base as docs_json_ts_0_5_2_1_classes_base_FGBuildableDoor_base,
	FGBuildableDoor_manual_version_specific as docs_json_ts_0_5_2_1_classes_base_FGBuildableDoor_manual_version_specific,
	FGBuildableLightsControlPanel_version_specific as docs_json_ts_0_5_2_1_classes_base_FGBuildableLightsControlPanel_version_specific,
	FGBuildableLightSource_base as docs_json_ts_0_5_2_1_classes_base_FGBuildableLightSource_base,
	FGBuildableLightSource_Build_StreetLight_C_version_specific as docs_json_ts_0_5_2_1_classes_base_FGBuildableLightSource_Build_StreetLight_C_version_specific,
	FGBuildableManufacturer_Build_FoundryMk1_C_base as docs_json_ts_0_5_2_1_classes_base_FGBuildableManufacturer_Build_FoundryMk1_C_base,
	FGBuildablePassthrough_base as docs_json_ts_0_5_2_1_classes_base_FGBuildablePassthrough_base,
	FGBuildableRailroadSignal_base_version_specific as docs_json_ts_0_5_2_1_classes_base_FGBuildableRailroadSignal_base_version_specific,
	FGBuildableRailroadSignal_block_version_specific as docs_json_ts_0_5_2_1_classes_base_FGBuildableRailroadSignal_block_version_specific,
	FGBuildableRailroadStation_base as docs_json_ts_0_5_2_1_classes_base_FGBuildableRailroadStation_base,
	FGBuildableRailroadTrack_base_version_specific as docs_json_ts_0_5_2_1_classes_base_FGBuildableRailroadTrack_base_version_specific,
	FGBuildableRamp_base as docs_json_ts_0_5_2_1_classes_base_FGBuildableRamp_base,
	FGBuildableTradingPost_base as docs_json_ts_0_5_2_1_classes_base_FGBuildableTradingPost_base,
	FGBuildableTrainPlatform_base_version_specific as docs_json_ts_0_5_2_1_classes_base_FGBuildableTrainPlatform_base_version_specific,
	FGBuildableTrainPlatform_non_empty_version_specific as docs_json_ts_0_5_2_1_classes_base_FGBuildableTrainPlatform_non_empty_version_specific,
	FGBuildableTrainPlatformCargo_version_specific as docs_json_ts_0_5_2_1_classes_base_FGBuildableTrainPlatformCargo_version_specific,
	FGBuildableWidgetSign_base as docs_json_ts_0_5_2_1_classes_base_FGBuildableWidgetSign_base,
	FGGolfCartDispenser_version_specific as docs_json_ts_0_5_2_1_classes_base_FGGolfCartDispenser_version_specific,
	FGNobeliskDetonator_version_specific as docs_json_ts_0_5_2_1_classes_base_FGNobeliskDetonator_version_specific,
	FGSchematic_with_described_unlocks_version_specific as docs_json_ts_0_5_2_1_classes_base_FGSchematic_with_described_unlocks_version_specific,
	FGWeapon_Equip_Rifle_C_base as docs_json_ts_0_5_2_1_classes_base_FGWeapon_Equip_Rifle_C_base,
	FGWeapon_pre_1_1 as docs_json_ts_0_5_2_1_classes_base_FGWeapon_pre_1_1,
	FGWeapon_version_specific as docs_json_ts_0_5_2_1_classes_base_FGWeapon_version_specific,
	has_mIsSupport as docs_json_ts_0_5_2_1_classes_base_has_mIsSupport,
	has_mSize_vector as docs_json_ts_0_5_2_1_classes_base_has_mSize_vector,
} from './../0.5.2.1/classes/Base.ts';

import type {
	FGBuildable_base_version_specific as docs_json_ts_0_7_1_1_classes_base_FGBuildable_base_version_specific,
	FGBuildable_powered_version_specific as docs_json_ts_0_7_1_1_classes_base_FGBuildable_powered_version_specific,
	FGBuildableBlueprintDesigner_version_specific as docs_json_ts_0_7_1_1_classes_base_FGBuildableBlueprintDesigner_version_specific,
	FGBuildableCircuitSwitch_version_specific as docs_json_ts_0_7_1_1_classes_base_FGBuildableCircuitSwitch_version_specific,
	FGBuildablePole_version_specific as docs_json_ts_0_7_1_1_classes_base_FGBuildablePole_version_specific,
} from './../0.7.1.1/classes/Base.ts';

import type {
	FGBuildableConveyorBelt as docs_json_ts_common_classes_FGBuildableConveyorBelt,
	FGSchematic as docs_json_ts_common_classes_FGSchematic,
} from './../common/classes.ts';

import type {
	FGBuildableResourceExtractor_miner_base as docs_json_ts_0_3_7_7_classes_base_overridable_FGBuildableResourceExtractor_miner_base,
	FGBuildableResourceExtractor_only_allow_certain_resources as docs_json_ts_0_3_7_7_classes_base_overridable_FGBuildableResourceExtractor_only_allow_certain_resources,
	FGEquipment_version_specific as docs_json_ts_0_3_7_7_classes_base_overridable_FGEquipment_version_specific,
	FGSchematic_version_specific as docs_json_ts_0_3_7_7_classes_base_overridable_FGSchematic_version_specific,
} from './../0.3.7.7/classes/Base.overridable--1.1.2.2.ts';

import type {
	FGBuildable_is_wallish as docs_json_ts_0_5_2_1_classes_base_overridable_FGBuildable_is_wallish,
	FGSchematic_version_specific as docs_json_ts_0_5_2_1_classes_base_overridable_FGSchematic_version_specific,
	FGWeapon_version_specific as docs_json_ts_0_5_2_1_classes_base_overridable_FGWeapon_version_specific,
} from './../0.5.2.1/classes/Base.overridable--1.1.2.2.ts';

import type {
	hasClassName as docs_json_ts_common_classes_base_hasClassName,
} from './../common/classes/Base.ts';

import type {
	FGJetPack_version_specific as docs_json_ts_0_7_1_1_classes_base_overridable_FGJetPack_version_specific,
} from './../0.7.1.1/classes/Base.1.1.2.2.ts';

import type {
	FGSchematic_has_mSchematicDependencies as docs_json_ts_1_0_1_4_properties_FGSchematic_has_mSchematicDependencies,
	Montages_item as docs_json_ts_1_0_1_4_properties_Montages_item,
} from './../1.0.1.4/types/properties.ts';

type has_bigOverlapList_0 = {
	bigOverlapList_0: null,
};

type has_mIsLeftHanded = {
	mIsLeftHanded: docs_json_ts_common_types_bool_string,
};

type has_mLastEditedBy = {
	mLastEditedBy: null,
};

type has_mOnLastEditedByChanged = {
	mOnLastEditedByChanged: docs_json_ts_common_types_empty_object,
};

type has_mPoleVariations = {
	mPoleVariations: [
		docs_json_ts_1_1_2_2_properties_mPoleVariations_item,
		...docs_json_ts_1_1_2_2_properties_mPoleVariations_item[],
	],
};

type FGAmmoType_version_specific = {
	mAudioEventsCache: docs_json_ts_common_types_empty_object | docs_json_ts_1_1_2_2_properties_mSoftAudioEvents,
};

type FGAmmoTypeInstantHit_Desc_CartridgeChaos_C = docs_json_ts_0_6_1_5_classes_base_FGAmmoType_base & docs_json_ts_0_6_1_5_classes_base_overridable_FGAmmoType_base & docs_json_ts_0_6_1_5_classes_base_FGAmmoType_version_specific & docs_json_ts_0_6_1_5_classes_base_overridable_FGAmmoType_version_specific & docs_json_ts_0_8_3_3_classes_base_overridable_FGAmmoType_version_specific & docs_json_ts_0_6_1_5_classes_base_FGAmmoTypeInstantHit_Desc_CartridgeChaos_C_version_specific & docs_json_ts_0_6_1_5_classes_base_FGAmmoTypeInstantHit_version_specific & docs_json_ts_1_0_1_4_classes_base_FGItemDescriptor_version_specific & FGAmmoType_version_specific & FGAmmoTypeInstantHit_version_specific;

type FGAmmoTypeInstantHit_Desc_CartridgeStandard_C = docs_json_ts_0_6_1_5_classes_base_FGAmmoType_base & docs_json_ts_0_6_1_5_classes_base_overridable_FGAmmoType_base & docs_json_ts_0_8_3_3_classes_base_overridable_FGAmmoType_version_specific & docs_json_ts_0_6_1_5_classes_base_FGAmmoType_version_specific & docs_json_ts_0_6_1_5_classes_base_overridable_FGAmmoType_version_specific & docs_json_ts_0_6_1_5_classes_base_FGAmmoTypeInstantHit_version_specific & docs_json_ts_1_0_1_4_classes_base_FGItemDescriptor_version_specific & FGAmmoType_version_specific & FGAmmoTypeInstantHit_version_specific;

type FGAmmoTypeInstantHit_version_specific = {
	mFiringSounds: null | [
        '/Game/WwiseAudio/Events/Equipment/Equipment_Weapons/Rifle/Play_Rifle_ChaosAmmo_Shot_3p.Play_Rifle_ChaosAmmo_Shot_3p' | '/Game/WwiseAudio/Events/Equipment/Rifle/Play_E_Rifle_GunShot_3P.Play_E_Rifle_GunShot_3P',
        ...('/Game/WwiseAudio/Events/Equipment/Equipment_Weapons/Rifle/Play_Rifle_ChaosAmmo_Shot_3p.Play_Rifle_ChaosAmmo_Shot_3p' | '/Game/WwiseAudio/Events/Equipment/Rifle/Play_E_Rifle_GunShot_3P.Play_E_Rifle_GunShot_3P')[],
	],
	mFiringSounds1P: null | [
        '/Game/WwiseAudio/Events/Equipment/Rifle/Play_Rifle_ChaosAmmo_Shot.Play_Rifle_ChaosAmmo_Shot' | '/Game/WwiseAudio/Events/Equipment/Rifle/Play_E_Rifle_GunShot.Play_E_Rifle_GunShot',
        ...('/Game/WwiseAudio/Events/Equipment/Rifle/Play_Rifle_ChaosAmmo_Shot.Play_Rifle_ChaosAmmo_Shot' | '/Game/WwiseAudio/Events/Equipment/Rifle/Play_E_Rifle_GunShot.Play_E_Rifle_GunShot')[],
	],
};

type FGAmmoTypeProjectile = docs_json_ts_0_6_1_5_classes_base_FGAmmoType_base & docs_json_ts_0_6_1_5_classes_base_overridable_FGAmmoTypeProjectile_version_specific & docs_json_ts_0_8_3_3_classes_base_overridable_FGAmmoType_version_specific & docs_json_ts_0_6_1_5_classes_base_FGAmmoTypeProjectile_version_specific & docs_json_ts_0_6_1_5_classes_base_FGDescriptor & docs_json_ts_0_6_1_5_classes_base_FGItemDescriptor_version_specific & docs_json_ts_0_6_1_5_classes_base_overridable_FGItemDescriptor_version_specific & docs_json_ts_0_6_1_5_overridable_has_mSubCategories & docs_json_ts_0_8_3_3_classes_base_FGAmmoTypeProjectile_version_specific & docs_json_ts_1_0_1_4_classes_base_FGAmmoTypeProjectile_version_specific & docs_json_ts_1_0_1_4_classes_base_FGItemDescriptor_version_specific & FGAmmoType_version_specific & FGAmmoTypeProjectile_version_specific;

type FGAmmoTypeProjectile_version_specific = {
	mAmmoDamageFalloff: docs_json_ts_1_1_2_2_properties_FalloffCurve_EditorCurveData | docs_json_ts_1_1_2_2_properties_FalloffCurve_EditorCurveData_with_ExternalCurve,
	mFiringSounds: null | [
        '/Game/WwiseAudio/Events/Equipment/RebarGun/Play_T_RebarGun_Fire.Play_T_RebarGun_Fire' | '/Game/WwiseAudio/Events/Equipment/Equipment_Weapons/RebarGun/3p/Play_RebarGun_StunFire_3p.Play_RebarGun_StunFire_3p' | '/Game/WwiseAudio/Events/Equipment/Equipment_Weapons/Rifle/Play_Rifle_HomingAmmo_Shot_3p.Play_Rifle_HomingAmmo_Shot_3p' | '/Game/WwiseAudio/Events/Equipment/Equipment_Weapons/Rifle/Play_Rifle_ChaosAmmo_Shot_3p.Play_Rifle_ChaosAmmo_Shot_3p',
        ...('/Game/WwiseAudio/Events/Equipment/RebarGun/Play_T_RebarGun_Fire.Play_T_RebarGun_Fire' | '/Game/WwiseAudio/Events/Equipment/Equipment_Weapons/RebarGun/3p/Play_RebarGun_StunFire_3p.Play_RebarGun_StunFire_3p' | '/Game/WwiseAudio/Events/Equipment/Equipment_Weapons/Rifle/Play_Rifle_HomingAmmo_Shot_3p.Play_Rifle_HomingAmmo_Shot_3p' | '/Game/WwiseAudio/Events/Equipment/Equipment_Weapons/Rifle/Play_Rifle_ChaosAmmo_Shot_3p.Play_Rifle_ChaosAmmo_Shot_3p')[],
	],
	mFiringSounds1P: null | [
        '/Game/WwiseAudio/Events/Equipment/Equipment_Weapons/RebarGun/3p/Play_T_RebarGun_Fire_3p.Play_T_RebarGun_Fire_3p' | '/Game/WwiseAudio/Events/Equipment/RebarGun/Play_RebarGun_StunFire.Play_RebarGun_StunFire' | '/Game/WwiseAudio/Events/Equipment/Rifle/Play_Rifle_HomingAmmo_Shot.Play_Rifle_HomingAmmo_Shot',
        ...('/Game/WwiseAudio/Events/Equipment/Equipment_Weapons/RebarGun/3p/Play_T_RebarGun_Fire_3p.Play_T_RebarGun_Fire_3p' | '/Game/WwiseAudio/Events/Equipment/RebarGun/Play_RebarGun_StunFire.Play_RebarGun_StunFire' | '/Game/WwiseAudio/Events/Equipment/Rifle/Play_Rifle_HomingAmmo_Shot.Play_Rifle_HomingAmmo_Shot')[],
	],
};

type FGAmmoTypeSpreadshot = docs_json_ts_0_6_1_5_classes_base_FGAmmoType_base & docs_json_ts_0_6_1_5_classes_base_overridable_FGAmmoType_base & docs_json_ts_0_8_3_3_classes_base_overridable_FGAmmoType_version_specific & docs_json_ts_0_6_1_5_classes_base_FGAmmoTypeSpreadshot_version_specific & docs_json_ts_1_0_1_4_classes_base_FGItemDescriptor_version_specific & FGAmmoType_version_specific & FGAmmoTypeSpreadshot_version_specific;

type FGAmmoTypeSpreadshot_version_specific = {
	mFiringSounds: null | [
		'/Game/WwiseAudio/Events/Equipment/Equipment_Weapons/RebarGun/3p/Play_RebarGun_Scatter_Fire_3p.Play_RebarGun_Scatter_Fire_3p',
		...'/Game/WwiseAudio/Events/Equipment/Equipment_Weapons/RebarGun/3p/Play_RebarGun_Scatter_Fire_3p.Play_RebarGun_Scatter_Fire_3p'[],
	],
	mFiringSounds1P: null | [
		'/Game/WwiseAudio/Events/Equipment/RebarGun/Play_RebarGun_Scatter_Fire.Play_RebarGun_Scatter_Fire',
		...'/Game/WwiseAudio/Events/Equipment/RebarGun/Play_RebarGun_Scatter_Fire.Play_RebarGun_Scatter_Fire'[],
	],
};

type FGBuildable_base = docs_json_ts_0_3_7_7_classes_base_FGBuildable_base_version_specific & docs_json_ts_0_4_2_11_classes_base_FGBuildable_base_version_specific & docs_json_ts_0_5_2_1_classes_base_FGBuildable_base_version_specific & docs_json_ts_0_6_1_5_classes_base_FGBuildable_base_version_specific & docs_json_ts_0_6_1_5_classes_base_overridable_FGBuildable_base_version_specific & docs_json_ts_0_7_1_1_classes_base_FGBuildable_base_version_specific & docs_json_ts_0_8_3_3_classes_base_FGBuildable_version_specific & docs_json_ts_1_0_1_4_classes_base_FGBuildable_version_specific & FGBuildable_version_specific;

type FGBuildable_occupied = docs_json_ts_0_3_7_7_classes_base_FGBuildable_occupied_base & FGBuildable_base;

type FGBuildable_powered = docs_json_ts_0_3_7_7_classes_base_FGBuildable_powered_version_specific & docs_json_ts_0_4_2_11_classes_base_FGBuildable_has_mCachedSkeletalMeshes & docs_json_ts_0_5_2_1_classes_base_FGBuildable_powered_base_base & docs_json_ts_0_7_1_1_classes_base_FGBuildable_powered_version_specific & docs_json_ts_0_8_3_3_classes_base_FGBuildable_with_mTickExponent & docs_json_ts_1_0_1_4_classes_base_FGBuildable_powered_version_specific & FGBuildable_base;

type FGBuildable_tiered = docs_json_ts_0_3_7_7_classes_base_FGBuildable_tiered_base & FGBuildable_base;

type FGBuildable_version_specific = {
	mOnBuildableReturnedToLightweightPool: docs_json_ts_common_types_empty_object,
	mInteractWidgetSoftClass: docs_json_ts_1_1_2_2_properties_WidgetClass,
};

type FGBuildableAttachmentMerger = docs_json_ts_0_3_7_7_classes_base_FGBuildableAttachmentMerger_version_specific & docs_json_ts_0_4_2_11_classes_base_has_mInventorySize & FGBuildable_base & FGBuildableConveyorAttachment_version_specific;

type FGBuildableAttachmentSplitter = docs_json_ts_0_3_7_7_classes_base_FGBuildableAttachment_has_mCurrentOutputIndex & docs_json_ts_0_4_2_11_classes_base_has_mInventorySize & FGBuildable_base & FGBuildableConveyorAttachment_version_specific;

type FGBuildableBarrierCorner = docs_json_ts_0_5_2_1_classes_base_has_mIsSupport & docs_json_ts_0_5_2_1_classes_base_has_mSize_vector & FGBuildable_base;

type FGBuildableBeam = docs_json_ts_0_5_2_1_classes_base_FGBuildableBeam_base & FGBuildable_base & FGBuildableBeam_version_specific;

type FGBuildableBeam_version_specific = {
	bTiledMesh: docs_json_ts_common_types_bool_string,
};

type FGBuildableBlueprintDesigner = docs_json_ts_0_7_1_1_classes_base_FGBuildableBlueprintDesigner_version_specific & docs_json_ts_0_8_3_3_classes_base_FGBuildableBlueprintDesigner_version_specific & docs_json_ts_1_0_1_4_classes_base_FGBuildableBlueprintDesigner_version_specific & FGBuildable_base;

type FGBuildableCircuitSwitch = docs_json_ts_0_4_2_11_classes_base_FGBuildableCircuitSwitch_base & docs_json_ts_0_7_1_1_classes_base_FGBuildableCircuitSwitch_version_specific & docs_json_ts_0_8_3_3_classes_base_FGBuildable_has_mOnCircuitsChanged & FGBuildable_base & FGBuildableCircuitSwitch_version_specific & has_mLastEditedBy & has_mOnLastEditedByChanged;

type FGBuildableCircuitSwitch_version_specific = {
	mFGTextRenderers: null,
};

type FGBuildableConveyorAttachment_version_specific = {
	mSavedDirections: null,
	mHologramOverrides: [
		docs_json_ts_1_1_2_2_properties_mHologramOverrides_item,
		...docs_json_ts_1_1_2_2_properties_mHologramOverrides_item[],
	],
};

type FGBuildableConveyorBelt = docs_json_ts_0_3_7_7_classes_base_FGBuildableConveyorBelt_pre_1_0 & docs_json_ts_0_3_7_7_classes_base_has_mMeshLength & docs_json_ts_0_3_7_7_classes_base_has_mSplineData & docs_json_ts_0_5_2_1_classes_base_FGBuildableConveyorBelt_version_specific & docs_json_ts_0_8_3_3_classes_base_FGBuildableConveyorBelt_version_specific & docs_json_ts_1_0_1_4_classes_base_FGBuildable_base & docs_json_ts_1_0_1_4_classes_base_FGBuildableConveyorBelt_version_specific & docs_json_ts_common_classes_FGBuildableConveyorBelt & FGBuildable_base & FGBuildableConveyorBelt_version_specific;

type FGBuildableConveyorBelt_version_specific = {
	mAttachedThroughputMonitors: null,
};

type FGBuildableConveyorLift = docs_json_ts_0_3_7_7_classes_base_FGBuildableConveyorBelt_pre_1_0 & docs_json_ts_0_3_7_7_classes_base_FGBuildableConveyorLift_base & docs_json_ts_0_5_2_1_classes_base_FGBuildable_mSnappedPassthroughs & docs_json_ts_0_8_3_3_classes_base_FGBuildableConveyorBelt_version_specific & docs_json_ts_1_0_1_4_classes_base_FGBuildableConveyorBelt_version_specific & docs_json_ts_1_0_1_4_classes_base_FGBuildableConveyorLift_version_specific & FGBuildable_base & FGBuildableConveyorBelt_version_specific & FGBuildableConveyorLift_version_specific;

type FGBuildableConveyorLift_version_specific = {
	mOutputMeshDisplayMode: 'MDM_Auto',
	mInputMeshDisplayMode: 'MDM_Auto',
	mIsBeltUsingInputRotation: docs_json_ts_common_types_bool_string,
};

type FGBuildableConveyorMonitor = FGBuildable_base & FGBuildableConveyorMonitor_version_specific;

type FGBuildableConveyorMonitor_version_specific = {
	WidgetClass: docs_json_ts_1_1_2_2_properties_WidgetClass,
	OnAverageDataUpdatedDelegate: docs_json_ts_common_types_empty_object,
	mIsSignificant: docs_json_ts_common_types_bool_string,
	mOffsetAlongConveyor: docs_json_ts_common_types_decimal_string_signed,
	mCalculatedItemsPerMinute: docs_json_ts_common_types_integer_string_signed,
	mTotalItems: docs_json_ts_common_types_integer_string,
	mTotalTime: docs_json_ts_common_types_decimal_string,
	mConfidence: docs_json_ts_common_types_decimal_string,
	mReplicatedCoreData: docs_json_ts_common_types_empty_object,
	mSignificanceRange: docs_json_ts_common_types_decimal_string,
};

type FGBuildableCornerWall = docs_json_ts_0_3_7_7_classes_base_FGBuildable_with_height_base & docs_json_ts_0_3_7_7_classes_base_FGBuildable_with_size_base & docs_json_ts_0_6_1_5_classes_base_has_mIsInverted & FGBuildable_base;

type FGBuildableDockingStation = docs_json_ts_0_3_7_7_classes_base_FGBuildable_docking_station_base_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableDockingStation_with_mFuelTransferSpeed_base & docs_json_ts_0_5_2_1_classes_base_FGBuildableDockingStation_base & FGBuildable_powered;

type FGBuildableDoor = FGBuildableDoor_manual | FGBuildableDoor_automated;

type FGBuildableDoor_automated = docs_json_ts_0_5_2_1_classes_base_FGBuildableDoor_automated_version_specific & docs_json_ts_0_5_2_1_classes_base_FGBuildableDoor_base & FGBuildableWall;

type FGBuildableDoor_big0 = docs_json_ts_0_5_2_1_classes_base_FGBuildableDoor_automated_version_specific & docs_json_ts_0_5_2_1_classes_base_FGBuildableDoor_base & FGBuildableWall & has_bigOverlapList_0;

type FGBuildableDoor_manual = docs_json_ts_0_5_2_1_classes_base_FGBuildableDoor_base & docs_json_ts_0_5_2_1_classes_base_FGBuildableDoor_manual_version_specific & FGBuildableWall;

type FGBuildableDroneStation = docs_json_ts_0_3_7_7_classes_base_FGBuildable_docking_station_base_with_mMapText & docs_json_ts_0_4_2_11_classes_base_FGBuildableDroneStation_version_specific & docs_json_ts_1_0_1_4_classes_base_FGBuildableDroneStation_version_specific & FGBuildable_powered;

type FGBuildableElevator = docs_json_ts_0_3_7_7_classes_base_FGBuildable_with_height_base & FGBuildable_base & FGBuildable_powered & FGBuildableElevator_version_specific;

type FGBuildableElevator_version_specific = {
	mStopAtFloorTimerHandle: docs_json_ts_common_types_empty_object,
	mPowerOutPauseTimerHandle: docs_json_ts_common_types_empty_object,
	mSpeed: docs_json_ts_common_types_decimal_string,
	mLockedMovementDirection: 'EED_Up',
	mFloorStopInfos: null,
	mQueuedStops: null,
	mQueuedStopIndexes: null,
	mCharactersInElevator: null,
	mOccupyingCharacters: null,
	mAllPawnsInElevator: null,
	mHeightOfCabin: docs_json_ts_common_types_decimal_string,
	mSongID: docs_json_ts_common_types_integer_string,
	mDurationToOpenDoors: docs_json_ts_common_types_decimal_string,
	mDurationToWaitAtStop: docs_json_ts_common_types_decimal_string,
	mDurationToCloseDoors: docs_json_ts_common_types_decimal_string,
	mDurationPauseBeforeMove: docs_json_ts_common_types_decimal_string,
	mDurationPausePowerOutage: docs_json_ts_common_types_decimal_string,
	mDurationPauseBeforeDoorOpen: docs_json_ts_common_types_decimal_string,
	mElevatorState: 'EES_NONE',
};

type FGBuildableElevatorFloorStop = FGBuildable_base & FGBuildableElevatorFloorStop_version_specific;

type FGBuildableElevatorFloorStop_version_specific = {
	Timeline_Offset_942DA00C47315AC741095991E04356D7: docs_json_ts_common_types_XYZ_decimal_string,
	Timeline__Direction_942DA00C47315AC741095991E04356D7: 'Forward',
	DoorStartTime: docs_json_ts_common_types_decimal_string,
	mElevatorDataStruct: {
		FloorColor_11_CD9C84CB45D5EE423EB254803463E6C9: docs_json_ts_common_types_RGBA,
	},
	bIsSignificant: docs_json_ts_common_types_bool_string,
	mSignificanceRange: docs_json_ts_common_types_decimal_string,
	mFloorRelevantElevatorState: 'EES_NONE',
	mCachedQueuedStatus: 'EEFSQS_None',
	mCachedFloorStopInfo: {
		IconId: docs_json_ts_common_types_integer_string_signed,
		IconColor: docs_json_ts_common_types_RGBA,
		Height?: docs_json_ts_common_types_integer_string_signed,
	},
};

type FGBuildableFactory_jump_pad = docs_json_ts_0_3_7_7_classes_base_FGBuildableFactory_jump_pad_base_base_base & FGBuildable_powered;

type FGBuildableFactory_landing_pad = docs_json_ts_0_3_7_7_classes_base_FGBuildableFactory_landing_pad_base_base_base & FGBuildable_powered;

type FGBuildableFactorySimpleProducer = docs_json_ts_0_3_7_7_classes_base_FGBuildableFactorySimpleProducer_base_base & FGBuildable_powered;

type FGBuildableFloodlight = docs_json_ts_0_4_2_11_classes_base_FGBuildableFloodlight_version_specific & FGBuildable_base & FGBuildableLightSource;

type FGBuildableFoundationLightweight = docs_json_ts_0_3_7_7_classes_base_FGBuildable_with_height_base & docs_json_ts_0_3_7_7_classes_base_FGBuildable_with_width_base & docs_json_ts_0_5_2_1_classes_base_FGBuildable_isFrame & docs_json_ts_0_5_2_1_classes_base_FGBuildable_with_elevation & docs_json_ts_0_6_1_5_classes_base_FGBuildable_foundation_mDisableSnapOn & docs_json_ts_0_6_1_5_classes_base_FGBuildable_with_depth & docs_json_ts_0_6_1_5_classes_base_FGBuildableFoundation_version_specific & FGBuildable_base;

type FGBuildableFrackingActivator = docs_json_ts_0_3_7_7_classes_base_overridable_FGBuildableResourceExtractor_only_allow_certain_resources & docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_only_allow_certain_resources & docs_json_ts_0_4_2_11_classes_base_FGBuildableFrackingActivator_version_specific & docs_json_ts_0_6_1_5_classes_base_FGBuildableResourceExtractor_base_version_specific_base & FGBuildable_powered;

type FGBuildableFrackingExtractor = docs_json_ts_0_3_7_7_classes_base_overridable_FGBuildableResourceExtractor_only_allow_certain_resources & docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_piped & docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_timed & docs_json_ts_0_6_1_5_classes_base_FGBuildableResourceExtractor_base_version_specific_base & FGBuildable_powered;

type FGBuildableGenerator = docs_json_ts_0_3_7_7_classes_base_FGBuildableGenerator_base_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableGenerator_no_fuel_base_base_base_base & docs_json_ts_1_0_1_4_classes_base_FGBuildableGenerator_no_fuel & docs_json_ts_1_0_1_4_classes_base_FGBuildableGenerator_version_specific & FGBuildable_base;

type FGBuildableGenerator_no_fuel = docs_json_ts_0_3_7_7_classes_base_FGBuildableGenerator_no_fuel_base_base_base_base & FGBuildable_powered;

type FGBuildableGeneratorFuel_biomass = docs_json_ts_0_4_2_11_classes_base_FGBuildableGeneratorFuel_base_base_base & docs_json_ts_1_0_1_4_classes_base_FGBuildableGeneratorFuel_biomass_version_specific & FGBuildableGenerator;

type FGBuildableGeneratorFuel_coal = docs_json_ts_0_3_7_7_classes_base_FGBuildableGeneratorFuel_coal_base_base & docs_json_ts_0_4_2_11_classes_base_FGBuildableGeneratorFuel_base_base_base & FGBuildableGenerator;

type FGBuildableGeneratorFuel_fuel = docs_json_ts_0_3_7_7_classes_base_FGBuildableGeneratorFuel_base_base_base & docs_json_ts_0_4_2_11_classes_base_FGBuildableGeneratorFuel_base_base_base & docs_json_ts_1_0_1_4_classes_base_FGBuildableGeneratorFuel_fuel_version_specific & FGBuildableGenerator;

type FGBuildableGeneratorGeoThermal = docs_json_ts_0_3_7_7_classes_base_FGBuildableGeneratorGeoThermal_base_base_base & docs_json_ts_0_4_2_11_classes_base_FGBuildableGeneratorGeoThermal_base & FGBuildableGenerator_no_fuel;

type FGBuildableGeneratorNuclear = docs_json_ts_0_3_7_7_classes_base_FGBuildableGeneratorNuclear_version_specific & docs_json_ts_0_4_2_11_classes_base_FGBuildableGeneratorFuel_base_base_base & docs_json_ts_0_4_2_11_classes_base_FGBuildableGeneratorNuclear_version_specific & docs_json_ts_1_0_1_4_classes_base_FGBuildableGenerator & docs_json_ts_1_0_1_4_classes_base_FGBuildableGeneratorNuclear_version_specific & FGBuildableGenerator;

type FGBuildableJumppad = docs_json_ts_0_3_7_7_classes_base_FGBuildableJumppad_base_base_base & docs_json_ts_0_8_3_3_classes_base_FGBuildableJumppad_version_specific & FGBuildable_powered;

type FGBuildableLadder = docs_json_ts_0_3_7_7_classes_base_FGBuildableLadder_base & FGBuildable_base;

type FGBuildableLightsControlPanel = docs_json_ts_0_4_2_11_classes_base_FGBuildable_light_related_thing_base & docs_json_ts_0_4_2_11_classes_base_FGBuildableLightsControlPanel_base & docs_json_ts_0_5_2_1_classes_base_FGBuildableLightsControlPanel_version_specific & docs_json_ts_0_8_3_3_classes_base_FGBuildable_has_mOnCircuitsChanged & FGBuildable_base;

type FGBuildableLightSource = docs_json_ts_0_4_2_11_classes_base_FGBuildable_light_related_thing_base & docs_json_ts_0_4_2_11_classes_base_FGBuildable_mHasPower_base & docs_json_ts_0_4_2_11_classes_base_FGBuildableLightSource_version_specific & docs_json_ts_0_4_2_11_classes_base_has_mPowerConsumption & docs_json_ts_0_5_2_1_classes_base_FGBuildableLightSource_base & FGBuildable_base;

type FGBuildableLightSource_Build_StreetLight_C = docs_json_ts_0_5_2_1_classes_base_FGBuildableLightSource_Build_StreetLight_C_version_specific & FGBuildableLightSource;

type FGBuildableMAM = docs_json_ts_0_4_2_11_classes_base_FGBuildableMAM_version_specific & docs_json_ts_1_0_1_4_classes_base_FGBuildableMAM_version_specific & FGBuildable_base & FGBuildable_occupied;

type FGBuildableManufacturer_Build_AssemblerMk1_C = docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_base_base & FGBuildable_powered;

type FGBuildableManufacturer_Build_Blender_C = docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_IsPowered_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_mProductionEffectsRunning_base_base & docs_json_ts_0_4_2_11_classes_base_FGBuildableManufacturer_base_blender_base_base & FGBuildable_powered;

type FGBuildableManufacturer_Build_ConstructorMk1_C = docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_base_base & docs_json_ts_1_0_1_4_classes_base_FGBuildableManufacturer_Build_ConstructorMk1_C_version_specific & FGBuildable_powered;

type FGBuildableManufacturer_Build_Converter_C = docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_base_base & docs_json_ts_0_4_2_11_classes_base_FGBuildableManufacturerVariablePower & FGBuildable_powered;

type FGBuildableManufacturer_Build_FoundryMk1_C = docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_mProductionEffectsRunning_base_base & docs_json_ts_0_5_2_1_classes_base_FGBuildableManufacturer_Build_FoundryMk1_C_base & FGBuildable_powered;

type FGBuildableManufacturer_Build_HadronCollider_C = docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_IsPowered_base_base & docs_json_ts_0_4_2_11_classes_base_FGBuildableManufacturer_Build_HadronCollider_C_base & docs_json_ts_0_4_2_11_classes_base_FGBuildableManufacturerVariablePower & FGBuildable_powered;

type FGBuildableManufacturer_Build_ManufacturerMk1_C = docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_base_base & docs_json_ts_0_4_2_11_classes_base_FGBuildable_mStopped_audio_stuff_base & FGBuildable_powered;

type FGBuildableManufacturer_Build_OilRefinery_C = docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_IsPowered_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_mProductionEffectsRunning_base_base & FGBuildable_powered;

type FGBuildableManufacturer_Build_Packager_C = docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_IsPowered_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_mProductionEffectsRunning_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_packager_base_base & FGBuildable_powered;

type FGBuildableManufacturer_Build_QuantumEncoder_C = docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_IsPowered_base_base & docs_json_ts_0_4_2_11_classes_base_FGBuildableManufacturerVariablePower & docs_json_ts_1_0_1_4_classes_base_FGBuildableManufacturer_Build_QuantumEncoder_C_version_specific & FGBuildable_powered;

type FGBuildableManufacturer_Build_SmelterMk1_C = docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_mProductionEffectsRunning_base_base & docs_json_ts_0_6_1_5_classes_base_FGBuildableManufacturer_Build_SmelterMk1_C_base & FGBuildable_powered;

type FGBuildableMergerPriority = docs_json_ts_0_4_2_11_classes_base_has_mInventorySize & FGBuildable_base & FGBuildableConveyorAttachment_version_specific & FGBuildableMergerPriority_version_specific;

type FGBuildableMergerPriority_version_specific = {
	mLocalCustomizationData: docs_json_ts_common_types_bool_string,
	OnInputPrioritiesChanged: docs_json_ts_common_types_empty_object,
	mInputPriorities: null,
	mCurrentInputIndices: null,
	mCurrentInputPriorityGroupIndex: docs_json_ts_common_types_integer_string,
};

type FGBuildablePassthrough = docs_json_ts_0_5_2_1_classes_base_FGBuildablePassthrough_base & docs_json_ts_0_8_3_3_classes_base_FGBuildablePassthrough_version_specific & FGBuildable_base;

type FGBuildablePillarLightweight = docs_json_ts_0_5_2_1_classes_base_has_mIsSupport & docs_json_ts_0_5_2_1_classes_base_has_mSize_vector & FGBuildable_base;

type FGBuildablePipeHyper = docs_json_ts_0_3_7_7_classes_base_has_mMeshLength & docs_json_ts_0_3_7_7_classes_base_has_mSplineData & docs_json_ts_0_5_2_1_classes_base_FGBuildable_mSnappedPassthroughs & FGBuildable_base;

type FGBuildablePipeHyperJunction = FGBuildable_powered & FGBuildablePipeHyperJunction_version_specific;

type FGBuildablePipeHyperJunction_version_specific = {
	JunctionPaths: null,
	DefaultPaths: null,
	mBuiltWithPipelineCostMultiplier: docs_json_ts_common_types_integer_string,
};

type FGBuildablePipeline = docs_json_ts_0_3_7_7_classes_base_FGBuildablePipeline_base_no_indicator_base & docs_json_ts_0_3_7_7_classes_base_FGBuildablePipeline_base_root & docs_json_ts_0_3_7_7_classes_base_has_mMeshLength & docs_json_ts_0_3_7_7_classes_base_has_mSplineData & docs_json_ts_0_5_2_1_classes_base_FGBuildable_mSnappedPassthroughs & docs_json_ts_0_6_1_5_classes_base_FGBuildablePipeline_version_specific & docs_json_ts_1_0_1_4_classes_base_FGBuildablePipeline_version_specific & FGBuildable_base;

type FGBuildablePipelineJunction = docs_json_ts_0_3_7_7_classes_base_FGBuildable_powered_version_specific & docs_json_ts_0_3_7_7_classes_base_FGBuildablePipeline_base_no_indicator_base & docs_json_ts_0_4_2_11_classes_base_FGBuildablePipelineJunction_base_base_base & FGBuildable_powered;

type FGBuildablePipelinePump_pump = docs_json_ts_0_3_7_7_classes_base_FGBuildablePipeline_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildablePipelinePump_powered_version_specific & docs_json_ts_0_3_7_7_classes_base_FGBuildablePipelinePump_pump_version_specific & docs_json_ts_1_0_1_4_classes_base_FGBuildablePipelinePump_version_specific & FGBuildable_powered;

type FGBuildablePipelinePump_valve = docs_json_ts_0_3_7_7_classes_base_FGBuildablePipeline_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildablePipelinePump_powered_version_specific & docs_json_ts_1_0_1_4_classes_base_FGBuildablePipelinePump_version_specific & FGBuildable_powered;

type FGBuildablePipeReservoir = docs_json_ts_0_3_7_7_classes_base_FGBuildablePipeReservoir_base_base_base & FGBuildable_powered;

type FGBuildablePoleConveyor = docs_json_ts_0_3_7_7_classes_base_FGBuildable_with_mLength & docs_json_ts_0_3_7_7_classes_base_FGBuildable_with_height_base & docs_json_ts_0_7_1_1_classes_base_FGBuildablePole_version_specific & FGBuildable_base & has_mPoleVariations;

type FGBuildablePolePipe = docs_json_ts_0_3_7_7_classes_base_FGBuildable_with_mLength & docs_json_ts_0_3_7_7_classes_base_FGBuildable_with_height_base & docs_json_ts_0_3_7_7_classes_base_FGBuildablePipelineSupport_base & docs_json_ts_0_7_1_1_classes_base_FGBuildablePole_version_specific & FGBuildable_base & FGBuildablePolePipe_version_specific & has_mPoleVariations;

type FGBuildablePolePipe_version_specific = {
	mSupportMeshInstanceData: {
		StaticMesh: `/Script/Engine.StaticMesh'/Game/FactoryGame${Exclude<string, ''>}${'\''}`,
		RelativeTransform: {
			Rotation: docs_json_ts_common_types_XYZW_decimal_string,
			Translation: docs_json_ts_common_types_XYZ_decimal_string,
			Scale3D: docs_json_ts_common_types_XYZ_decimal_string,
		},
		bUseBatchedCollision: docs_json_ts_common_types_bool_string,
		PositionOffset: docs_json_ts_common_types_XYZ_decimal_string,
		ScaleOffset: docs_json_ts_common_types_XYZ_decimal_string,
		NumCustomDataFloats: docs_json_ts_common_types_integer_string,
		CollisionProfileName: 'BuildingMeshExceptCamera',
		bCastShadows: docs_json_ts_common_types_bool_string,
		bCastDistanceFieldShadows: docs_json_ts_common_types_bool_string,
		MaxDrawDistance: docs_json_ts_common_types_decimal_string,
		MaxWPODistance: docs_json_ts_common_types_decimal_string,
		bAllowLazyInstance: docs_json_ts_common_types_bool_string,
		CollisionMeshSurfaceOverride: {
			OcclusionValue: docs_json_ts_common_types_decimal_string,
		},
	},
};

type FGBuildablePoleStackable = docs_json_ts_0_3_7_7_classes_base_has_mStackHeight & FGBuildable_base;

type FGBuildablePortal = docs_json_ts_1_0_1_4_classes_base_FGBuildablePortal_common & docs_json_ts_1_0_1_4_classes_base_FGBuildablePortal_version_specific & FGBuildable_base & FGBuildable_powered & has_mLastEditedBy;

type FGBuildablePortalSatellite = docs_json_ts_1_0_1_4_classes_base_FGBuildablePortal_common & docs_json_ts_1_0_1_4_classes_base_FGBuildablePortalSatellite_version_specific & FGBuildable_base & FGBuildable_powered & has_mLastEditedBy;

type FGBuildablePowerBooster = docs_json_ts_0_4_2_11_classes_base_has_mPowerConsumption & docs_json_ts_1_0_1_4_classes_base_FGBuildablePowerBooster_version_specific & FGBuildable_powered;

type FGBuildablePowerPole = docs_json_ts_0_4_2_11_classes_base_FGBuildable_mHasPower_base & docs_json_ts_0_5_2_1_classes_base_FGBuildable_base_version_specific & docs_json_ts_0_8_3_3_classes_base_FGBuildablePowerPole_version_specific & FGBuildable_base;

type FGBuildablePowerStorage = docs_json_ts_0_4_2_11_classes_base_FGBuildablePowerStorage_base & docs_json_ts_1_0_1_4_classes_base_FGBuildablePowerStorage_version_specific & FGBuildable_powered & FGBuildablePowerStorage_version_specific;

type FGBuildablePowerStorage_version_specific = {
	mNumExtraCustomizationData: docs_json_ts_common_types_integer_string,
	mMaxRealDataDriftTime: docs_json_ts_common_types_decimal_string,
};

type FGBuildablePriorityPowerSwitch = docs_json_ts_0_4_2_11_classes_base_FGBuildableCircuitSwitch_base & docs_json_ts_0_7_1_1_classes_base_FGBuildableCircuitSwitch_version_specific & docs_json_ts_0_8_3_3_classes_base_FGBuildable_has_mOnCircuitsChanged & docs_json_ts_0_8_3_3_classes_base_FGBuildablePriorityPowerSwitch_version_specific & FGBuildable_base & has_mLastEditedBy & has_mOnLastEditedByChanged;

type FGBuildableRadarTower = docs_json_ts_0_6_1_5_classes_base_FGBuildableRadarTower_version_specific & docs_json_ts_0_6_1_5_classes_base_overridable_FGBuildableRadarTower_version_specific & FGBuildable_powered & has_mLastEditedBy;

type FGBuildableRailroadAttachment = FGBuildable_base & FGBuildableRailroadAttachment_version_specific;

type FGBuildableRailroadAttachment_version_specific = {
	mIsEndStop: docs_json_ts_common_types_bool_string,
};

type FGBuildableRailroadSignal_base = docs_json_ts_0_5_2_1_classes_base_FGBuildableRailroadSignal_base_version_specific & docs_json_ts_0_8_3_3_classes_base_FGBuildableRailroadSignal_version_specific & FGBuildable_base & has_mIsLeftHanded;

type FGBuildableRailroadSignal_block = docs_json_ts_0_5_2_1_classes_base_FGBuildableRailroadSignal_block_version_specific & FGBuildableRailroadSignal_base & has_mIsLeftHanded;

type FGBuildableRailroadStation = docs_json_ts_0_3_7_7_classes_base_FGBuildableRailroadStation_version_specific & docs_json_ts_0_3_7_7_classes_base_FGBuildableTrainPlatform_base_base_base & docs_json_ts_0_5_2_1_classes_base_FGBuildableRailroadStation_base & docs_json_ts_0_5_2_1_classes_base_FGBuildableTrainPlatform_base_version_specific & docs_json_ts_0_5_2_1_classes_base_FGBuildableTrainPlatform_non_empty_version_specific & docs_json_ts_1_0_1_4_classes_base_FGBuildableTrainPlatform_version_specific & FGBuildable_powered & FGBuildableRailroadStation_version_specific;

type FGBuildableRailroadStation_version_specific = {
	mStationName: string,
};

type FGBuildableRailroadTrack = docs_json_ts_0_8_3_3_classes_base_overridable_FGBuildableRailroadTrack_version_specific & docs_json_ts_0_3_7_7_classes_base_FGBuildableRailroadTrack_base & docs_json_ts_0_5_2_1_classes_base_FGBuildableRailroadTrack_base_version_specific & FGBuildable_base;

type FGBuildableRampLightweight = docs_json_ts_0_5_2_1_classes_base_FGBuildableRamp_base & docs_json_ts_0_6_1_5_classes_base_has_mIsInverted & FGBuildableFoundationLightweight;

type FGBuildableResourceExtractor_base = docs_json_ts_0_3_7_7_classes_base_overridable_FGBuildableResourceExtractor_only_allow_certain_resources & docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_piped & docs_json_ts_0_6_1_5_classes_base_FGBuildableResourceExtractor_base_version_specific_base & FGBuildable_powered;

type FGBuildableResourceExtractor_miner_mk1 = docs_json_ts_0_3_7_7_classes_base_overridable_FGBuildableResourceExtractor_miner_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_miner_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_timed & docs_json_ts_0_4_2_11_classes_base_FGBuildableResourceExtractor_miner_mk1_version_specific & docs_json_ts_1_0_1_4_classes_base_FGBuildableResourceExtractor_miner_mk1_version_specific & docs_json_ts_1_0_1_4_classes_base_has_SAMReference & FGBuildableResourceExtractor_base;

type FGBuildableResourceExtractor_miner_mk2 = docs_json_ts_0_3_7_7_classes_base_overridable_FGBuildableResourceExtractor_miner_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_miner_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_miner_mk2_base_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_timed & docs_json_ts_1_0_1_4_classes_base_has_SAMReference & FGBuildableResourceExtractor_base;

type FGBuildableResourceExtractor_miner_mk3 = docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_miner_base & docs_json_ts_0_3_7_7_classes_base_overridable_FGBuildableResourceExtractor_miner_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_miner_mk3_version_specific & docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_timed & docs_json_ts_1_0_1_4_classes_base_has_SAMReference & FGBuildableResourceExtractor_base;

type FGBuildableResourceExtractor_oil = docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_oil_base_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_timed & FGBuildableResourceExtractor_base;

type FGBuildableResourceExtractor_water = docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_timed & docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_water_base_base_base & docs_json_ts_0_4_2_11_classes_base_FGBuildableResourceExtractor_water_base & FGBuildableResourceExtractor_base;

type FGBuildableResourceSink = docs_json_ts_0_4_2_11_classes_base_FGBuildableResourceSink_base_base & FGBuildable_powered;

type FGBuildableResourceSinkShop = docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceSinkShop_base_base_base & FGBuildable_powered;

type FGBuildableSnowCannon = docs_json_ts_1_0_1_4_classes_base_FGBuildableSnowCannon_version_specific & FGBuildable_base;

type FGBuildableSpaceElevator = docs_json_ts_1_0_1_4_classes_base_FGBuildableSpaceElevator_version_specific & FGBuildable_powered;

type FGBuildableSplitterSmart = docs_json_ts_0_3_7_7_classes_base_FGBuildableAttachment_splitter_base_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableSplitterSmart_version_specific & docs_json_ts_0_4_2_11_classes_base_has_mInventorySize & FGBuildable_base & FGBuildableConveyorAttachment_version_specific;

type FGBuildableStackableShelf = docs_json_ts_0_5_2_1_classes_base_has_mSize_vector & FGBuildable_base;

type FGBuildableStorage = docs_json_ts_0_3_7_7_classes_base_FGBuildableStorage_base_base_base & FGBuildable_powered;

type FGBuildableTradingPost = docs_json_ts_0_3_7_7_classes_base_FGBuildableTradingPost_version_specific & docs_json_ts_0_4_2_11_classes_base_FGBuildableTradingPost_base_version_specific & docs_json_ts_0_5_2_1_classes_base_FGBuildableTradingPost_base & docs_json_ts_1_0_1_4_classes_base_FGBuildable_powered & docs_json_ts_1_0_1_4_classes_base_FGBuildableTradingPost_version_specific & FGBuildable_version_specific & FGBuildableTradingPost_version_specific;

type FGBuildableTradingPost_version_specific = {
	Timeline_1_Circle_Time_0FCB760D4456675480E5668A43BA28E4: docs_json_ts_common_types_decimal_string,
	Timeline_1_Circle_Visibility_0FCB760D4456675480E5668A43BA28E4: docs_json_ts_common_types_decimal_string,
	Timeline_1__Direction_0FCB760D4456675480E5668A43BA28E4: 'Forward',
	Timeline_0_NewTrack_0_682BE0A145186C364CDC23A2A7B837A9: docs_json_ts_common_types_decimal_string,
	Timeline_0__Direction_682BE0A145186C364CDC23A2A7B837A9: 'Forward',
	Timeline_NewTrack_0_DB12CB5E4B31F8645E6A5F99ED2B1409: docs_json_ts_common_types_decimal_string,
	Timeline__Direction_DB12CB5E4B31F8645E6A5F99ED2B1409: 'Forward',
	CueName: '',
	SpawnedEventActors: '',
	bDidSpawnSeasonalEventProps: docs_json_ts_common_types_bool_string,
};

type FGBuildableTrainPlatformCargo = docs_json_ts_0_3_7_7_classes_base_FGBuildable_powered_storage_base_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableTrainPlatform_base_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableTrainPlatformCargo_version_specific & docs_json_ts_0_5_2_1_classes_base_FGBuildableTrainPlatform_base_version_specific & docs_json_ts_0_5_2_1_classes_base_FGBuildableTrainPlatform_non_empty_version_specific & docs_json_ts_0_5_2_1_classes_base_FGBuildableTrainPlatformCargo_version_specific & docs_json_ts_0_6_1_5_classes_base_FGBuildableTrainPlatformCargo_version_specific & docs_json_ts_1_0_1_4_classes_base_FGBuildableTrainPlatform_version_specific & FGBuildable_powered;

type FGBuildableTrainPlatformEmpty = docs_json_ts_0_3_7_7_classes_base_FGBuildableTrainPlatform_base_base_base & docs_json_ts_0_5_2_1_classes_base_FGBuildableTrainPlatform_base_version_specific & docs_json_ts_1_0_1_4_classes_base_FGBuildableTrainPlatform_version_specific & FGBuildable_powered;

type FGBuildableWalkway = docs_json_ts_0_3_7_7_classes_base_FGBuildable_with_size_and_elevation_base & docs_json_ts_0_3_7_7_classes_base_FGBuildable_with_size_and_elevation_base_base & FGBuildable_base;

type FGBuildableWall = docs_json_ts_0_5_2_1_classes_base_overridable_FGBuildable_is_wallish & docs_json_ts_0_3_7_7_classes_base_FGBuildable_with_height_and_width_base & docs_json_ts_0_5_2_1_classes_base_FGBuildable_with_elevation & docs_json_ts_1_0_1_4_classes_base_FGBuildable_base & FGBuildable_base;

type FGBuildableWidgetSign = docs_json_ts_0_5_2_1_classes_base_FGBuildableWidgetSign_base & docs_json_ts_0_8_3_3_classes_base_FGBuildableWidgetSign_version_specific & docs_json_ts_1_0_1_4_classes_base_FGBuildableWidgetSign_version_specific & FGBuildable_base & has_mLastEditedBy;

type FGBuildableWire = docs_json_ts_0_3_7_7_classes_base_FGBuildableWire_base & docs_json_ts_0_8_3_3_classes_base_FGBuildableWire_version_specific & FGBuildable_base;

type FGCentralStorageContainer = docs_json_ts_1_0_1_4_classes_base_FGCentralStorageContainer_version_specific & FGBuildable_base & FGBuildableStorage;

type FGChainsaw = docs_json_ts_0_3_7_7_classes_base_FGChainsaw_version_specific & docs_json_ts_0_6_1_5_classes_base_FGChainsaw_version_specific & docs_json_ts_0_8_3_3_classes_base_FGChainsaw_version_specific & docs_json_ts_1_0_1_4_classes_base_FGChainsaw_version_specific & docs_json_ts_1_0_1_4_classes_base_FGEquipment & FGChainsaw_version_specific & FGEquipment_version_specific;

type FGChainsaw_version_specific = {
	CurrentState: 'None',
	StateChanged: docs_json_ts_common_types_bool_string,
};

type FGConsumableEquipment_base = docs_json_ts_0_8_3_3_classes_base_overridable_FGConsumableEquipment_version_specific & docs_json_ts_0_3_7_7_classes_base_FGConsumableEquipment_version_specific & docs_json_ts_0_4_2_11_classes_base_FGConsumableEquipment_version_specific & docs_json_ts_1_0_1_4_classes_base_FGConsumableEquipment_base_version_specific & docs_json_ts_1_0_1_4_classes_base_FGEquipment & FGEquipment_version_specific;

type FGConsumableEquipment_medkit = docs_json_ts_0_8_3_3_classes_base_overridable_FGConsumableEquipment_version_specific & docs_json_ts_0_3_7_7_classes_base_FGConsumableEquipment_version_specific & docs_json_ts_0_4_2_11_classes_base_FGConsumableEquipment_version_specific & docs_json_ts_1_0_1_4_classes_base_FGConsumableEquipment_medkit_version_specific & docs_json_ts_1_0_1_4_classes_base_FGEquipment & FGEquipment_version_specific;

type FGEquipment_version_specific = {
	mEquipMontage: docs_json_ts_1_1_2_2_properties_Montages,
	mMagnetismStrength: docs_json_ts_common_types_decimal_string,
	mMagnetismZeroInputStrength: docs_json_ts_common_types_decimal_string,
	bMagnetismActive: docs_json_ts_common_types_bool_string,
};

type FGEquipmentStunSpear_xenobasher = docs_json_ts_0_3_7_7_classes_base_overridable_FGEquipment_version_specific & docs_json_ts_0_8_3_3_classes_base_overridable_FGEquipment_version_specific & docs_json_ts_0_3_7_7_classes_base_FGEquipmentStunSpear_base_version_specific & docs_json_ts_0_6_1_5_classes_base_FGEquipment_version_specific & docs_json_ts_0_6_1_5_classes_base_FGEquipmentStunSpear_base_version_specific & docs_json_ts_0_8_3_3_classes_base_FGEquipmentStunSpear_base_version_specific & docs_json_ts_1_0_1_4_classes_base_FGEquipment_version_specific & docs_json_ts_1_0_1_4_classes_base_FGEquipmentStunSpear_version_specific & docs_json_ts_common_classes_base_hasClassName & FGEquipment_version_specific;

type FGEquipmentStunSpear_xenozapper = docs_json_ts_0_3_7_7_classes_base_overridable_FGEquipment_version_specific & docs_json_ts_0_8_3_3_classes_base_overridable_FGEquipment_version_specific & docs_json_ts_0_3_7_7_classes_base_FGEquipmentStunSpear_base_version_specific & docs_json_ts_0_6_1_5_classes_base_FGEquipment_version_specific & docs_json_ts_0_6_1_5_classes_base_FGEquipmentStunSpear_base_version_specific & docs_json_ts_0_8_3_3_classes_base_FGEquipmentStunSpear_base_version_specific & docs_json_ts_1_0_1_4_classes_base_FGEquipment_version_specific & docs_json_ts_1_0_1_4_classes_base_FGEquipmentStunSpear_version_specific & docs_json_ts_common_classes_base_hasClassName & FGEquipment_version_specific;

type FGEquipmentZipline = docs_json_ts_0_4_2_11_classes_base_FGEquipmentZipline_version_specific & docs_json_ts_0_6_1_5_classes_base_FGEquipment_noisy_version_specific & docs_json_ts_1_0_1_4_classes_base_FGEquipment & docs_json_ts_1_0_1_4_classes_base_FGEquipmentZipline_version_specific & FGEquipment_version_specific;

type FGGasMask = docs_json_ts_0_3_7_7_classes_base_FGEquipment_has_mFilterDuration & docs_json_ts_0_3_7_7_classes_base_FGGasMask_base & docs_json_ts_0_8_3_3_classes_base_FGGasMask_version_specific & docs_json_ts_1_0_1_4_classes_base_FGEquipment & FGEquipment_version_specific;

type FGGolfCartDispenser = docs_json_ts_0_3_7_7_classes_base_FGGolfCartDispenser_has_mArmAnimation & docs_json_ts_0_5_2_1_classes_base_FGGolfCartDispenser_version_specific & docs_json_ts_1_0_1_4_classes_base_FGEquipment & docs_json_ts_1_0_1_4_classes_base_FGGolfCartDispenser_version_specific & FGEquipment_version_specific;

type FGHoverPack = docs_json_ts_0_4_2_11_classes_base_FGHoverPack_version_specific & docs_json_ts_0_6_1_5_classes_base_FGEquipment_noisy_version_specific & docs_json_ts_1_0_1_4_classes_base_FGEquipment & docs_json_ts_1_0_1_4_classes_base_FGHoverPack_version_specific & FGEquipment_version_specific;

type FGItemDescriptor_base = docs_json_ts_0_6_1_5_classes_base_FGDescriptor & docs_json_ts_0_6_1_5_classes_base_FGItemDescriptor_version_specific & docs_json_ts_0_6_1_5_classes_base_overridable_FGItemDescriptor_version_specific & docs_json_ts_0_6_1_5_overridable_has_mSubCategories & docs_json_ts_1_0_1_4_classes_base_FGItemDescriptor_version_specific & FGItemDescriptor_version_specific;

type FGItemDescriptor_version_specific = {
	mUsesDistanceForZooping: docs_json_ts_common_types_bool_string,
};

type FGJetPack = docs_json_ts_0_7_1_1_classes_base_overridable_FGJetPack_version_specific & docs_json_ts_0_3_7_7_classes_base_FGJetPack_version_specific & docs_json_ts_0_6_1_5_classes_base_FGEquipment_noisy_version_specific & docs_json_ts_0_8_3_3_classes_base_FGJetPack_version_specific & docs_json_ts_1_0_1_4_classes_base_FGEquipment & docs_json_ts_1_0_1_4_classes_base_FGJetPack_version_specific & FGEquipment_version_specific;

type FGJumpingStilts = docs_json_ts_0_3_7_7_classes_base_FGJumpingStilts_base & docs_json_ts_0_6_1_5_classes_base_FGJumpingStilts_version_specific & docs_json_ts_1_0_1_4_classes_base_FGEquipment & FGEquipment_version_specific;

type FGNobeliskDetonator = docs_json_ts_0_5_2_1_classes_base_overridable_FGWeapon_version_specific & docs_json_ts_0_3_7_7_classes_base_FGNobeliskDetonator_base & docs_json_ts_0_3_7_7_classes_base_FGWeaponProjectile_thrown_base_pre_1_0 & docs_json_ts_0_4_2_11_classes_base_FGWeaponProjectile_has_mBlockSprintWhenFiring & docs_json_ts_0_5_2_1_classes_base_FGNobeliskDetonator_version_specific & docs_json_ts_0_5_2_1_classes_base_FGWeapon_pre_1_1 & docs_json_ts_0_5_2_1_classes_base_FGWeapon_version_specific & docs_json_ts_0_6_1_5_classes_base_FGWeapon_base & docs_json_ts_1_0_1_4_classes_base_FGEquipment & docs_json_ts_1_0_1_4_classes_base_FGNobeliskDetonator_version_specific & FGEquipment_version_specific & FGNobeliskDetonator_version_specific;

type FGNobeliskDetonator_version_specific = {
	bHasDispensedProjectiles: docs_json_ts_common_types_bool_string,
};

type FGObjectScanner = docs_json_ts_0_3_7_7_classes_base_FGObjectScanner_version_specific & docs_json_ts_0_8_3_3_classes_base_FGObjectScanner_version_specific & docs_json_ts_1_0_1_4_classes_base_FGEquipment & docs_json_ts_1_0_1_4_classes_base_FGObjectScanner_version_specific & FGEquipment_version_specific;

type FGParachute = docs_json_ts_0_3_7_7_classes_base_FGParachute_has_mIsDeployed & docs_json_ts_0_8_3_3_classes_base_FGParachute_version_specific & docs_json_ts_1_0_1_4_classes_base_FGEquipment & docs_json_ts_1_0_1_4_classes_base_FGParachute_version_specific & FGEquipment_version_specific;

type FGPipeHyperStart = docs_json_ts_0_3_7_7_classes_base_FGPipeHyperStart_base_base_base & FGBuildable_powered;

type FGPortableMinerDispenser = docs_json_ts_0_3_7_7_classes_base_FGPortableMinerDispenser_version_specific & docs_json_ts_0_4_2_11_classes_base_FGPortableMinerDispenser_version_specific & docs_json_ts_1_0_1_4_classes_base_FGEquipment & docs_json_ts_1_0_1_4_classes_base_FGPortableMinerDispenser_version_specific & FGEquipment_version_specific;

type FGSchematic_version_specific = {
	mStatisticGameplayTag: docs_json_ts_common_types_empty_object | docs_json_ts_1_1_2_2_properties_mStatisticGameplayTag,
};

type FGSchematic_with_described_unlocks = docs_json_ts_0_3_7_7_classes_base_overridable_FGSchematic_version_specific & docs_json_ts_0_5_2_1_classes_base_overridable_FGSchematic_version_specific & docs_json_ts_0_8_3_3_classes_base_overridable_FGSchematic_has_mSchematicIcon & docs_json_ts_0_8_3_3_classes_base_overridable_FGSchematic_version_specific & docs_json_ts_0_3_7_7_classes_base_instructive & docs_json_ts_0_3_7_7_classes_base_isDescribed & docs_json_ts_0_5_2_1_classes_base_FGSchematic_with_described_unlocks_version_specific & docs_json_ts_0_6_1_5_classes_base_FGSchematic_version_specific & docs_json_ts_1_0_1_4_classes_base_FGSchematic_has_mTechTier & docs_json_ts_1_0_1_4_classes_base_FGSchematic_version_specific & docs_json_ts_1_0_1_4_properties_FGSchematic_has_mSchematicDependencies & docs_json_ts_common_classes_FGSchematic & FGSchematic_version_specific;

type FGSchematic_without_described_unlocks = docs_json_ts_0_3_7_7_classes_base_overridable_FGSchematic_version_specific & docs_json_ts_0_5_2_1_classes_base_overridable_FGSchematic_version_specific & docs_json_ts_0_8_3_3_classes_base_overridable_FGSchematic_has_mSchematicIcon & docs_json_ts_0_8_3_3_classes_base_overridable_FGSchematic_version_specific & docs_json_ts_0_3_7_7_classes_base_instructive & docs_json_ts_0_3_7_7_classes_base_isDescribed & docs_json_ts_0_6_1_5_classes_base_FGSchematic_version_specific & docs_json_ts_1_0_1_4_classes_base_FGSchematic_has_mTechTier & docs_json_ts_1_0_1_4_classes_base_FGSchematic_version_specific & docs_json_ts_1_0_1_4_properties_FGSchematic_has_mSchematicDependencies & docs_json_ts_common_classes_FGSchematic & FGSchematic_version_specific;

type FGSuitBase = docs_json_ts_0_3_7_7_classes_base_FGEquipment_has_mFilterDuration & docs_json_ts_0_3_7_7_classes_base_FGEquipment_has_effect_timer & docs_json_ts_0_3_7_7_classes_base_FGEquipment_negates_damage & docs_json_ts_0_3_7_7_classes_base_overridable_FGEquipment_version_specific & docs_json_ts_0_8_3_3_classes_base_overridable_FGEquipment_version_specific & docs_json_ts_0_3_7_7_classes_base_FGSuitBase_base & docs_json_ts_0_6_1_5_classes_base_FGEquipment_version_specific & docs_json_ts_0_6_1_5_classes_base_FGSuitBase_version_specific & docs_json_ts_1_0_1_4_classes_base_FGEquipment_version_specific & docs_json_ts_1_0_1_4_classes_base_FGSuitBase_version_specific & docs_json_ts_common_classes_base_hasClassName & FGEquipment_version_specific;

type FGWeapon_Equip_RebarGun_Projectile_C = docs_json_ts_0_5_2_1_classes_base_overridable_FGWeapon_version_specific & docs_json_ts_0_3_7_7_classes_base_FGEquipment_has_mEquipmentSlot & docs_json_ts_0_3_7_7_classes_base_FGWeaponProjectile_has_mAttachSocket & docs_json_ts_0_4_2_11_classes_base_FGWeaponProjectile_has_mBlockSprintWhenFiring & docs_json_ts_0_5_2_1_classes_base_FGWeapon_version_specific & docs_json_ts_0_6_1_5_classes_base_FGWeapon_base & docs_json_ts_1_0_1_4_classes_base_FGEquipment & docs_json_ts_1_0_1_4_classes_base_FGWeapon_version_specific & FGEquipment_version_specific & FGWeapon_version_specific;

type FGWeapon_Equip_Rifle_C = docs_json_ts_0_5_2_1_classes_base_overridable_FGWeapon_version_specific & docs_json_ts_0_3_7_7_classes_base_FGEquipment_has_mEquipmentSlot & docs_json_ts_0_3_7_7_classes_base_FGWeaponInstantFire_base_base_base & docs_json_ts_0_3_7_7_classes_base_FGWeaponProjectile_has_mAttachSocket & docs_json_ts_0_4_2_11_classes_base_FGWeaponProjectile_has_mBlockSprintWhenFiring & docs_json_ts_0_5_2_1_classes_base_FGWeapon_Equip_Rifle_C_base & docs_json_ts_0_5_2_1_classes_base_FGWeapon_version_specific & docs_json_ts_0_6_1_5_classes_base_FGWeapon_base & docs_json_ts_1_0_1_4_classes_base_FGEquipment & docs_json_ts_1_0_1_4_classes_base_FGWeapon_version_specific & FGEquipment_version_specific & FGWeapon_version_specific;

type FGWeapon_version_specific = {
	mFireMontage: docs_json_ts_1_0_1_4_properties_Montages_item,
};

export type {
	has_bigOverlapList_0,
	has_mIsLeftHanded,
	has_mLastEditedBy,
	has_mOnLastEditedByChanged,
	has_mPoleVariations,
	FGAmmoType_version_specific,
	FGAmmoTypeInstantHit_Desc_CartridgeChaos_C,
	FGAmmoTypeInstantHit_Desc_CartridgeStandard_C,
	FGAmmoTypeInstantHit_version_specific,
	FGAmmoTypeProjectile,
	FGAmmoTypeProjectile_version_specific,
	FGAmmoTypeSpreadshot,
	FGAmmoTypeSpreadshot_version_specific,
	FGBuildable_base,
	FGBuildable_occupied,
	FGBuildable_powered,
	FGBuildable_tiered,
	FGBuildable_version_specific,
	FGBuildableAttachmentMerger,
	FGBuildableAttachmentSplitter,
	FGBuildableBarrierCorner,
	FGBuildableBeam,
	FGBuildableBeam_version_specific,
	FGBuildableBlueprintDesigner,
	FGBuildableCircuitSwitch,
	FGBuildableCircuitSwitch_version_specific,
	FGBuildableConveyorAttachment_version_specific,
	FGBuildableConveyorBelt,
	FGBuildableConveyorBelt_version_specific,
	FGBuildableConveyorLift,
	FGBuildableConveyorLift_version_specific,
	FGBuildableConveyorMonitor,
	FGBuildableConveyorMonitor_version_specific,
	FGBuildableCornerWall,
	FGBuildableDockingStation,
	FGBuildableDoor,
	FGBuildableDoor_automated,
	FGBuildableDoor_big0,
	FGBuildableDoor_manual,
	FGBuildableDroneStation,
	FGBuildableElevator,
	FGBuildableElevator_version_specific,
	FGBuildableElevatorFloorStop,
	FGBuildableElevatorFloorStop_version_specific,
	FGBuildableFactory_jump_pad,
	FGBuildableFactory_landing_pad,
	FGBuildableFactorySimpleProducer,
	FGBuildableFloodlight,
	FGBuildableFoundationLightweight,
	FGBuildableFrackingActivator,
	FGBuildableFrackingExtractor,
	FGBuildableGenerator,
	FGBuildableGenerator_no_fuel,
	FGBuildableGeneratorFuel_biomass,
	FGBuildableGeneratorFuel_coal,
	FGBuildableGeneratorFuel_fuel,
	FGBuildableGeneratorGeoThermal,
	FGBuildableGeneratorNuclear,
	FGBuildableJumppad,
	FGBuildableLadder,
	FGBuildableLightsControlPanel,
	FGBuildableLightSource,
	FGBuildableLightSource_Build_StreetLight_C,
	FGBuildableMAM,
	FGBuildableManufacturer_Build_AssemblerMk1_C,
	FGBuildableManufacturer_Build_Blender_C,
	FGBuildableManufacturer_Build_ConstructorMk1_C,
	FGBuildableManufacturer_Build_Converter_C,
	FGBuildableManufacturer_Build_FoundryMk1_C,
	FGBuildableManufacturer_Build_HadronCollider_C,
	FGBuildableManufacturer_Build_ManufacturerMk1_C,
	FGBuildableManufacturer_Build_OilRefinery_C,
	FGBuildableManufacturer_Build_Packager_C,
	FGBuildableManufacturer_Build_QuantumEncoder_C,
	FGBuildableManufacturer_Build_SmelterMk1_C,
	FGBuildableMergerPriority,
	FGBuildableMergerPriority_version_specific,
	FGBuildablePassthrough,
	FGBuildablePillarLightweight,
	FGBuildablePipeHyper,
	FGBuildablePipeHyperJunction,
	FGBuildablePipeHyperJunction_version_specific,
	FGBuildablePipeline,
	FGBuildablePipelineJunction,
	FGBuildablePipelinePump_pump,
	FGBuildablePipelinePump_valve,
	FGBuildablePipeReservoir,
	FGBuildablePoleConveyor,
	FGBuildablePolePipe,
	FGBuildablePolePipe_version_specific,
	FGBuildablePoleStackable,
	FGBuildablePortal,
	FGBuildablePortalSatellite,
	FGBuildablePowerBooster,
	FGBuildablePowerPole,
	FGBuildablePowerStorage,
	FGBuildablePowerStorage_version_specific,
	FGBuildablePriorityPowerSwitch,
	FGBuildableRadarTower,
	FGBuildableRailroadAttachment,
	FGBuildableRailroadAttachment_version_specific,
	FGBuildableRailroadSignal_base,
	FGBuildableRailroadSignal_block,
	FGBuildableRailroadStation,
	FGBuildableRailroadStation_version_specific,
	FGBuildableRailroadTrack,
	FGBuildableRampLightweight,
	FGBuildableResourceExtractor_base,
	FGBuildableResourceExtractor_miner_mk1,
	FGBuildableResourceExtractor_miner_mk2,
	FGBuildableResourceExtractor_miner_mk3,
	FGBuildableResourceExtractor_oil,
	FGBuildableResourceExtractor_water,
	FGBuildableResourceSink,
	FGBuildableResourceSinkShop,
	FGBuildableSnowCannon,
	FGBuildableSpaceElevator,
	FGBuildableSplitterSmart,
	FGBuildableStackableShelf,
	FGBuildableStorage,
	FGBuildableTradingPost,
	FGBuildableTradingPost_version_specific,
	FGBuildableTrainPlatformCargo,
	FGBuildableTrainPlatformEmpty,
	FGBuildableWalkway,
	FGBuildableWall,
	FGBuildableWidgetSign,
	FGBuildableWire,
	FGCentralStorageContainer,
	FGChainsaw,
	FGChainsaw_version_specific,
	FGConsumableEquipment_base,
	FGConsumableEquipment_medkit,
	FGEquipment_version_specific,
	FGEquipmentStunSpear_xenobasher,
	FGEquipmentStunSpear_xenozapper,
	FGEquipmentZipline,
	FGGasMask,
	FGGolfCartDispenser,
	FGHoverPack,
	FGItemDescriptor_base,
	FGItemDescriptor_version_specific,
	FGJetPack,
	FGJumpingStilts,
	FGNobeliskDetonator,
	FGNobeliskDetonator_version_specific,
	FGObjectScanner,
	FGParachute,
	FGPipeHyperStart,
	FGPortableMinerDispenser,
	FGSchematic_version_specific,
	FGSchematic_with_described_unlocks,
	FGSchematic_without_described_unlocks,
	FGSuitBase,
	FGWeapon_Equip_RebarGun_Projectile_C,
	FGWeapon_Equip_Rifle_C,
	FGWeapon_version_specific,
};
