/* eslint-disable @stylistic/max-len */

import type {
	FGAmmoTypeInstantHit_Desc_CartridgeChaos_C as docs_json_ts_1_2_2_0_classes_base_FGAmmoTypeInstantHit_Desc_CartridgeChaos_C,
	FGAmmoTypeInstantHit_Desc_CartridgeStandard_C as docs_json_ts_1_2_2_0_classes_base_FGAmmoTypeInstantHit_Desc_CartridgeStandard_C,
	FGAmmoTypeProjectile as docs_json_ts_1_2_2_0_classes_base_FGAmmoTypeProjectile,
	FGAmmoTypeSpreadshot as docs_json_ts_1_2_2_0_classes_base_FGAmmoTypeSpreadshot,
	FGBuildableCircuitSwitch as docs_json_ts_1_2_2_0_classes_base_FGBuildableCircuitSwitch,
	FGBuildablePriorityPowerSwitch as docs_json_ts_1_2_2_0_classes_base_FGBuildablePriorityPowerSwitch,
	FGBuildingDescriptor as docs_json_ts_1_2_2_0_classes_base_FGBuildingDescriptor,
	FGConsumableDescriptor as docs_json_ts_1_2_2_0_classes_base_FGConsumableDescriptor,
	FGEquipmentDescriptor as docs_json_ts_1_2_2_0_classes_base_FGEquipmentDescriptor,
	FGItemDescriptor_non_sinkable as docs_json_ts_1_2_2_0_classes_base_FGItemDescriptor_non_sinkable,
	FGItemDescriptor_sinkable as docs_json_ts_1_2_2_0_classes_base_FGItemDescriptor_sinkable,
	FGItemDescriptorBiomass as docs_json_ts_1_2_2_0_classes_base_FGItemDescriptorBiomass,
	FGItemDescriptorNuclearFuel as docs_json_ts_1_2_2_0_classes_base_FGItemDescriptorNuclearFuel,
	FGItemDescriptorPowerBoosterFuel as docs_json_ts_1_2_2_0_classes_base_FGItemDescriptorPowerBoosterFuel,
	FGPowerShardDescriptor as docs_json_ts_1_2_2_0_classes_base_FGPowerShardDescriptor,
	FGResourceDescriptor as docs_json_ts_1_2_2_0_classes_base_FGResourceDescriptor,
	FGVehicleDescriptor_Desc_CyberWagon_C as docs_json_ts_1_2_2_0_classes_base_FGVehicleDescriptor_Desc_CyberWagon_C,
	FGVehicleDescriptor_Desc_DroneTransport_C as docs_json_ts_1_2_2_0_classes_base_FGVehicleDescriptor_Desc_DroneTransport_C,
	FGVehicleDescriptor_Desc_Explorer_C as docs_json_ts_1_2_2_0_classes_base_FGVehicleDescriptor_Desc_Explorer_C,
	FGVehicleDescriptor_Desc_FluidTruck_C as docs_json_ts_1_2_2_0_classes_base_FGVehicleDescriptor_Desc_FluidTruck_C,
	FGVehicleDescriptor_Desc_FreightWagon_C as docs_json_ts_1_2_2_0_classes_base_FGVehicleDescriptor_Desc_FreightWagon_C,
	FGVehicleDescriptor_Desc_Locomotive_C as docs_json_ts_1_2_2_0_classes_base_FGVehicleDescriptor_Desc_Locomotive_C,
	FGVehicleDescriptor_Desc_Tractor_C as docs_json_ts_1_2_2_0_classes_base_FGVehicleDescriptor_Desc_Tractor_C,
	FGVehicleDescriptor_Desc_Truck_C as docs_json_ts_1_2_2_0_classes_base_FGVehicleDescriptor_Desc_Truck_C,
} from './Base.ts';

type FGAmmoTypeInstantHit_Desc_CartridgeChaos_C = docs_json_ts_1_2_2_0_classes_base_FGAmmoTypeInstantHit_Desc_CartridgeChaos_C;

type FGAmmoTypeInstantHit_Desc_CartridgeStandard_C = docs_json_ts_1_2_2_0_classes_base_FGAmmoTypeInstantHit_Desc_CartridgeStandard_C;

type FGAmmoTypeProjectile = docs_json_ts_1_2_2_0_classes_base_FGAmmoTypeProjectile;

type FGAmmoTypeSpreadshot = docs_json_ts_1_2_2_0_classes_base_FGAmmoTypeSpreadshot;

type FGBuildableCircuitSwitch = docs_json_ts_1_2_2_0_classes_base_FGBuildableCircuitSwitch;

type FGBuildablePriorityPowerSwitch = docs_json_ts_1_2_2_0_classes_base_FGBuildablePriorityPowerSwitch;

type FGBuildingDescriptor = docs_json_ts_1_2_2_0_classes_base_FGBuildingDescriptor;

type FGConsumableDescriptor = docs_json_ts_1_2_2_0_classes_base_FGConsumableDescriptor;

type FGEquipmentDescriptor = docs_json_ts_1_2_2_0_classes_base_FGEquipmentDescriptor;

type FGItemDescriptor_non_sinkable = docs_json_ts_1_2_2_0_classes_base_FGItemDescriptor_non_sinkable;

type FGItemDescriptor_sinkable = docs_json_ts_1_2_2_0_classes_base_FGItemDescriptor_sinkable;

type FGItemDescriptorBiomass = docs_json_ts_1_2_2_0_classes_base_FGItemDescriptorBiomass;

type FGItemDescriptorNuclearFuel = docs_json_ts_1_2_2_0_classes_base_FGItemDescriptorNuclearFuel;

type FGItemDescriptorPowerBoosterFuel = docs_json_ts_1_2_2_0_classes_base_FGItemDescriptorPowerBoosterFuel;

type FGPowerShardDescriptor = docs_json_ts_1_2_2_0_classes_base_FGPowerShardDescriptor;

type FGResourceDescriptor = docs_json_ts_1_2_2_0_classes_base_FGResourceDescriptor;

type FGVehicleDescriptor_Desc_CyberWagon_C = docs_json_ts_1_2_2_0_classes_base_FGVehicleDescriptor_Desc_CyberWagon_C;

type FGVehicleDescriptor_Desc_DroneTransport_C = docs_json_ts_1_2_2_0_classes_base_FGVehicleDescriptor_Desc_DroneTransport_C;

type FGVehicleDescriptor_Desc_Explorer_C = docs_json_ts_1_2_2_0_classes_base_FGVehicleDescriptor_Desc_Explorer_C;

type FGVehicleDescriptor_Desc_FluidTruck_C = docs_json_ts_1_2_2_0_classes_base_FGVehicleDescriptor_Desc_FluidTruck_C;

type FGVehicleDescriptor_Desc_FreightWagon_C = docs_json_ts_1_2_2_0_classes_base_FGVehicleDescriptor_Desc_FreightWagon_C;

type FGVehicleDescriptor_Desc_Locomotive_C = docs_json_ts_1_2_2_0_classes_base_FGVehicleDescriptor_Desc_Locomotive_C;

type FGVehicleDescriptor_Desc_Tractor_C = docs_json_ts_1_2_2_0_classes_base_FGVehicleDescriptor_Desc_Tractor_C;

type FGVehicleDescriptor_Desc_Truck_C = docs_json_ts_1_2_2_0_classes_base_FGVehicleDescriptor_Desc_Truck_C;

export type {
	FGAmmoTypeInstantHit_Desc_CartridgeChaos_C,
	FGAmmoTypeInstantHit_Desc_CartridgeStandard_C,
	FGAmmoTypeProjectile,
	FGAmmoTypeSpreadshot,
	FGBuildableCircuitSwitch,
	FGBuildablePriorityPowerSwitch,
	FGBuildingDescriptor,
	FGConsumableDescriptor,
	FGEquipmentDescriptor,
	FGItemDescriptor_non_sinkable,
	FGItemDescriptor_sinkable,
	FGItemDescriptorBiomass,
	FGItemDescriptorNuclearFuel,
	FGItemDescriptorPowerBoosterFuel,
	FGPowerShardDescriptor,
	FGResourceDescriptor,
	FGVehicleDescriptor_Desc_CyberWagon_C,
	FGVehicleDescriptor_Desc_DroneTransport_C,
	FGVehicleDescriptor_Desc_Explorer_C,
	FGVehicleDescriptor_Desc_FluidTruck_C,
	FGVehicleDescriptor_Desc_FreightWagon_C,
	FGVehicleDescriptor_Desc_Locomotive_C,
	FGVehicleDescriptor_Desc_Tractor_C,
	FGVehicleDescriptor_Desc_Truck_C,
};
