/* eslint-disable @stylistic/max-len */

import type {
	FGBuildable as docs_json_ts_1_2_0_0_FGBuildable,
	FGBuildableAttachmentMerger as docs_json_ts_1_2_0_0_FGBuildableAttachmentMerger,
	FGBuildableAttachmentSplitter as docs_json_ts_1_2_0_0_FGBuildableAttachmentSplitter,
	FGBuildableBarrierCorner as docs_json_ts_1_2_0_0_FGBuildableBarrierCorner,
	FGBuildableBeam as docs_json_ts_1_2_0_0_FGBuildableBeam,
	FGBuildableBlueprintDesigner as docs_json_ts_1_2_0_0_FGBuildableBlueprintDesigner,
	FGBuildableConveyorBelt as docs_json_ts_1_2_0_0_FGBuildableConveyorBelt,
	FGBuildableConveyorLift as docs_json_ts_1_2_0_0_FGBuildableConveyorLift,
	FGBuildableConveyorMonitor as docs_json_ts_1_2_0_0_FGBuildableConveyorMonitor,
	FGBuildableCornerWall as docs_json_ts_1_2_0_0_FGBuildableCornerWall,
	FGBuildableCornerWallLightweight as docs_json_ts_1_2_0_0_FGBuildableCornerWallLightweight,
	FGBuildableDockingStation as docs_json_ts_1_2_0_0_FGBuildableDockingStation,
	FGBuildableDoor as docs_json_ts_1_2_0_0_FGBuildableDoor,
	FGBuildableDroneStation as docs_json_ts_1_2_0_0_FGBuildableDroneStation,
	FGBuildableElevator as docs_json_ts_1_2_0_0_FGBuildableElevator,
	FGBuildableElevatorFloorStop as docs_json_ts_1_2_0_0_FGBuildableElevatorFloorStop,
	FGBuildableFactory as docs_json_ts_1_2_0_0_FGBuildableFactory,
	FGBuildableFactoryBuilding as docs_json_ts_1_2_0_0_FGBuildableFactoryBuilding,
	FGBuildableFactorySimpleProducer as docs_json_ts_1_2_0_0_FGBuildableFactorySimpleProducer,
	FGBuildableFloodlight as docs_json_ts_1_2_0_0_FGBuildableFloodlight,
	FGBuildableFoundationLightweight as docs_json_ts_1_2_0_0_FGBuildableFoundationLightweight,
	FGBuildableFrackingActivator as docs_json_ts_1_2_0_0_FGBuildableFrackingActivator,
	FGBuildableFrackingExtractor as docs_json_ts_1_2_0_0_FGBuildableFrackingExtractor,
	FGBuildableGeneratorFuel as docs_json_ts_1_2_0_0_FGBuildableGeneratorFuel,
	FGBuildableGeneratorGeoThermal as docs_json_ts_1_2_0_0_FGBuildableGeneratorGeoThermal,
	FGBuildableGeneratorNuclear as docs_json_ts_1_2_0_0_FGBuildableGeneratorNuclear,
	FGBuildableJumppad as docs_json_ts_1_2_0_0_FGBuildableJumppad,
	FGBuildableLadder as docs_json_ts_1_2_0_0_FGBuildableLadder,
	FGBuildableLightsControlPanel as docs_json_ts_1_2_0_0_FGBuildableLightsControlPanel,
	FGBuildableLightSource as docs_json_ts_1_2_0_0_FGBuildableLightSource,
	FGBuildableMAM as docs_json_ts_1_2_0_0_FGBuildableMAM,
	FGBuildableManufacturer as docs_json_ts_1_2_0_0_FGBuildableManufacturer,
	FGBuildableManufacturerVariablePower as docs_json_ts_1_2_0_0_FGBuildableManufacturerVariablePower,
	FGBuildableMergerPriority as docs_json_ts_1_2_0_0_FGBuildableMergerPriority,
	FGBuildablePassthrough as docs_json_ts_1_2_0_0_FGBuildablePassthrough,
	FGBuildablePassthroughPipeHyper as docs_json_ts_1_2_0_0_FGBuildablePassthroughPipeHyper,
	FGBuildablePillarLightweight as docs_json_ts_1_2_0_0_FGBuildablePillarLightweight,
	FGBuildablePipeHyper as docs_json_ts_1_2_0_0_FGBuildablePipeHyper,
	FGBuildablePipeHyperJunction as docs_json_ts_1_2_0_0_FGBuildablePipeHyperJunction,
	FGBuildablePipeline as docs_json_ts_1_2_0_0_FGBuildablePipeline,
	FGBuildablePipelineJunction as docs_json_ts_1_2_0_0_FGBuildablePipelineJunction,
	FGBuildablePipelinePump as docs_json_ts_1_2_0_0_FGBuildablePipelinePump,
	FGBuildablePipeReservoir as docs_json_ts_1_2_0_0_FGBuildablePipeReservoir,
	FGBuildablePoleBase as docs_json_ts_1_2_0_0_FGBuildablePoleBase,
	FGBuildablePoleConveyor as docs_json_ts_1_2_0_0_FGBuildablePoleConveyor,
	FGBuildablePolePipe as docs_json_ts_1_2_0_0_FGBuildablePolePipe,
	FGBuildablePoleStackable as docs_json_ts_1_2_0_0_FGBuildablePoleStackable,
	FGBuildablePortal as docs_json_ts_1_2_0_0_FGBuildablePortal,
	FGBuildablePortalSatellite as docs_json_ts_1_2_0_0_FGBuildablePortalSatellite,
	FGBuildablePowerBooster as docs_json_ts_1_2_0_0_FGBuildablePowerBooster,
	FGBuildablePowerPole as docs_json_ts_1_2_0_0_FGBuildablePowerPole,
	FGBuildablePowerStorage as docs_json_ts_1_2_0_0_FGBuildablePowerStorage,
	FGBuildableRadarTower as docs_json_ts_1_2_0_0_FGBuildableRadarTower,
	FGBuildableRailroadAttachment as docs_json_ts_1_2_0_0_FGBuildableRailroadAttachment,
	FGBuildableRailroadSignal as docs_json_ts_1_2_0_0_FGBuildableRailroadSignal,
	FGBuildableRailroadStation as docs_json_ts_1_2_0_0_FGBuildableRailroadStation,
	FGBuildableRailroadTrack as docs_json_ts_1_2_0_0_FGBuildableRailroadTrack,
	FGBuildableRampLightweight as docs_json_ts_1_2_0_0_FGBuildableRampLightweight,
	FGBuildableResourceExtractor as docs_json_ts_1_2_0_0_FGBuildableResourceExtractor,
	FGBuildableResourceSink as docs_json_ts_1_2_0_0_FGBuildableResourceSink,
	FGBuildableResourceSinkShop as docs_json_ts_1_2_0_0_FGBuildableResourceSinkShop,
	FGBuildableSnowCannon as docs_json_ts_1_2_0_0_FGBuildableSnowCannon,
	FGBuildableSnowDispenser as docs_json_ts_1_2_0_0_FGBuildableSnowDispenser,
	FGBuildableSpaceElevator as docs_json_ts_1_2_0_0_FGBuildableSpaceElevator,
	FGBuildableSplitterSmart as docs_json_ts_1_2_0_0_FGBuildableSplitterSmart,
	FGBuildableStackableShelf as docs_json_ts_1_2_0_0_FGBuildableStackableShelf,
	FGBuildableStair as docs_json_ts_1_2_0_0_FGBuildableStair,
	FGBuildableStorage as docs_json_ts_1_2_0_0_FGBuildableStorage,
	FGBuildableTradingPost as docs_json_ts_1_2_0_0_FGBuildableTradingPost,
	FGBuildableTrainPlatformCargo as docs_json_ts_1_2_0_0_FGBuildableTrainPlatformCargo,
	FGBuildableTrainPlatformEmpty as docs_json_ts_1_2_0_0_FGBuildableTrainPlatformEmpty,
	FGBuildableWalkway as docs_json_ts_1_2_0_0_FGBuildableWalkway,
	FGBuildableWalkwayLightweight as docs_json_ts_1_2_0_0_FGBuildableWalkwayLightweight,
	FGBuildableWall as docs_json_ts_1_2_0_0_FGBuildableWall,
	FGBuildableWallLightweight as docs_json_ts_1_2_0_0_FGBuildableWallLightweight,
	FGBuildableWaterPump as docs_json_ts_1_2_0_0_FGBuildableWaterPump,
	FGBuildableWidgetSign as docs_json_ts_1_2_0_0_FGBuildableWidgetSign,
	FGBuildableWire as docs_json_ts_1_2_0_0_FGBuildableWire,
	FGCentralStorageContainer as docs_json_ts_1_2_0_0_FGCentralStorageContainer,
	FGChargedWeapon as docs_json_ts_1_2_0_0_FGChargedWeapon,
	FGConsumableEquipment as docs_json_ts_1_2_0_0_FGConsumableEquipment,
	FGCustomizationRecipe as docs_json_ts_1_2_0_0_FGCustomizationRecipe,
	FGEquipmentStunSpear as docs_json_ts_1_2_0_0_FGEquipmentStunSpear,
	FGHoverPack as docs_json_ts_1_2_0_0_FGHoverPack,
	FGObjectScanner as docs_json_ts_1_2_0_0_FGObjectScanner,
	FGParachute as docs_json_ts_1_2_0_0_FGParachute,
	FGPipeHyperStart as docs_json_ts_1_2_0_0_FGPipeHyperStart,
	FGRecipe as docs_json_ts_1_2_0_0_FGRecipe,
	FGSchematic as docs_json_ts_1_2_0_0_FGSchematic,
	FGVehiclePathSegment as docs_json_ts_1_2_0_0_FGVehiclePathSegment,
	FGWeapon as docs_json_ts_1_2_0_0_FGWeapon,
} from './../1.2.0.0/types.ts';

import type {
	FGChainsaw as docs_json_ts_1_1_2_2_FGChainsaw,
	FGEquipmentZipline as docs_json_ts_1_1_2_2_FGEquipmentZipline,
	FGGasMask as docs_json_ts_1_1_2_2_FGGasMask,
	FGGolfCartDispenser as docs_json_ts_1_1_2_2_FGGolfCartDispenser,
	FGJetPack as docs_json_ts_1_1_2_2_FGJetPack,
	FGJumpingStilts as docs_json_ts_1_1_2_2_FGJumpingStilts,
	FGPortableMinerDispenser as docs_json_ts_1_1_2_2_FGPortableMinerDispenser,
	FGSuitBase as docs_json_ts_1_1_2_2_FGSuitBase,
} from './../1.1.2.2/types.ts';

import type {
	FGAmmoTypeInstantHit_Desc_CartridgeChaos_C as docs_json_ts_1_2_2_0_classes_FGAmmoTypeInstantHit_Desc_CartridgeChaos_C,
	FGAmmoTypeInstantHit_Desc_CartridgeStandard_C as docs_json_ts_1_2_2_0_classes_FGAmmoTypeInstantHit_Desc_CartridgeStandard_C,
	FGAmmoTypeProjectile as docs_json_ts_1_2_2_0_classes_FGAmmoTypeProjectile,
	FGAmmoTypeSpreadshot as docs_json_ts_1_2_2_0_classes_FGAmmoTypeSpreadshot,
	FGBuildableCircuitSwitch as docs_json_ts_1_2_2_0_classes_FGBuildableCircuitSwitch,
	FGBuildablePriorityPowerSwitch as docs_json_ts_1_2_2_0_classes_FGBuildablePriorityPowerSwitch,
	FGBuildingDescriptor as docs_json_ts_1_2_2_0_classes_FGBuildingDescriptor,
	FGConsumableDescriptor as docs_json_ts_1_2_2_0_classes_FGConsumableDescriptor,
	FGEquipmentDescriptor as docs_json_ts_1_2_2_0_classes_FGEquipmentDescriptor,
	FGItemDescriptor_non_sinkable as docs_json_ts_1_2_2_0_classes_FGItemDescriptor_non_sinkable,
	FGItemDescriptor_sinkable as docs_json_ts_1_2_2_0_classes_FGItemDescriptor_sinkable,
	FGItemDescriptorBiomass as docs_json_ts_1_2_2_0_classes_FGItemDescriptorBiomass,
	FGItemDescriptorNuclearFuel as docs_json_ts_1_2_2_0_classes_FGItemDescriptorNuclearFuel,
	FGItemDescriptorPowerBoosterFuel as docs_json_ts_1_2_2_0_classes_FGItemDescriptorPowerBoosterFuel,
	FGPowerShardDescriptor as docs_json_ts_1_2_2_0_classes_FGPowerShardDescriptor,
	FGResourceDescriptor as docs_json_ts_1_2_2_0_classes_FGResourceDescriptor,
	FGVehicleDescriptor_Desc_CyberWagon_C as docs_json_ts_1_2_2_0_classes_FGVehicleDescriptor_Desc_CyberWagon_C,
	FGVehicleDescriptor_Desc_DroneTransport_C as docs_json_ts_1_2_2_0_classes_FGVehicleDescriptor_Desc_DroneTransport_C,
	FGVehicleDescriptor_Desc_Explorer_C as docs_json_ts_1_2_2_0_classes_FGVehicleDescriptor_Desc_Explorer_C,
	FGVehicleDescriptor_Desc_FluidTruck_C as docs_json_ts_1_2_2_0_classes_FGVehicleDescriptor_Desc_FluidTruck_C,
	FGVehicleDescriptor_Desc_FreightWagon_C as docs_json_ts_1_2_2_0_classes_FGVehicleDescriptor_Desc_FreightWagon_C,
	FGVehicleDescriptor_Desc_Locomotive_C as docs_json_ts_1_2_2_0_classes_FGVehicleDescriptor_Desc_Locomotive_C,
	FGVehicleDescriptor_Desc_Tractor_C as docs_json_ts_1_2_2_0_classes_FGVehicleDescriptor_Desc_Tractor_C,
	FGVehicleDescriptor_Desc_Truck_C as docs_json_ts_1_2_2_0_classes_FGVehicleDescriptor_Desc_Truck_C,
} from './classes.ts';

type FGAmmoTypeInstantHit = {
	NativeClass: `/Script/CoreUObject.Class'/Script/${'FactoryGame.FGAmmoTypeInstantHit'}${'\''}`,
	Classes: [
		docs_json_ts_1_2_2_0_classes_FGAmmoTypeInstantHit_Desc_CartridgeChaos_C,
		docs_json_ts_1_2_2_0_classes_FGAmmoTypeInstantHit_Desc_CartridgeStandard_C,
	],
};

type FGAmmoTypeProjectile = {
	NativeClass: `/Script/CoreUObject.Class'/Script/${'FactoryGame.FGAmmoTypeProjectile'}${'\''}`,
	Classes: [
		docs_json_ts_1_2_2_0_classes_FGAmmoTypeProjectile,
		docs_json_ts_1_2_2_0_classes_FGAmmoTypeProjectile,
		docs_json_ts_1_2_2_0_classes_FGAmmoTypeProjectile,
		docs_json_ts_1_2_2_0_classes_FGAmmoTypeProjectile,
		docs_json_ts_1_2_2_0_classes_FGAmmoTypeProjectile,
		docs_json_ts_1_2_2_0_classes_FGAmmoTypeProjectile,
		docs_json_ts_1_2_2_0_classes_FGAmmoTypeProjectile,
		docs_json_ts_1_2_2_0_classes_FGAmmoTypeProjectile,
		docs_json_ts_1_2_2_0_classes_FGAmmoTypeProjectile,
		docs_json_ts_1_2_2_0_classes_FGAmmoTypeProjectile,
		docs_json_ts_1_2_2_0_classes_FGAmmoTypeProjectile,
		docs_json_ts_1_2_2_0_classes_FGAmmoTypeProjectile,
		docs_json_ts_1_2_2_0_classes_FGAmmoTypeProjectile,
		...docs_json_ts_1_2_2_0_classes_FGAmmoTypeProjectile[],
	],
};

type FGAmmoTypeSpreadshot = {
	NativeClass: `/Script/CoreUObject.Class'/Script/${'FactoryGame.FGAmmoTypeSpreadshot'}${'\''}`,
	Classes: [
		docs_json_ts_1_2_2_0_classes_FGAmmoTypeSpreadshot,
		...docs_json_ts_1_2_2_0_classes_FGAmmoTypeSpreadshot[],
	],
};

type FGBuildableCircuitSwitch = {
	NativeClass: `/Script/CoreUObject.Class'/Script/${'FactoryGame.FGBuildableCircuitSwitch'}${'\''}`,
	Classes: [
		docs_json_ts_1_2_2_0_classes_FGBuildableCircuitSwitch,
		...docs_json_ts_1_2_2_0_classes_FGBuildableCircuitSwitch[],
	],
};

type FGBuildablePriorityPowerSwitch = {
	NativeClass: `/Script/CoreUObject.Class'/Script/${'FactoryGame.FGBuildablePriorityPowerSwitch'}${'\''}`,
	Classes: [
		docs_json_ts_1_2_2_0_classes_FGBuildablePriorityPowerSwitch,
		...docs_json_ts_1_2_2_0_classes_FGBuildablePriorityPowerSwitch[],
	],
};

type FGBuildingDescriptor = {
	NativeClass: `/Script/CoreUObject.Class'/Script/${'FactoryGame.FGBuildingDescriptor'}${'\''}`,
	Classes: [
		docs_json_ts_1_2_2_0_classes_FGBuildingDescriptor,
		...docs_json_ts_1_2_2_0_classes_FGBuildingDescriptor[],
	],
};

type FGConsumableDescriptor = {
	NativeClass: `/Script/CoreUObject.Class'/Script/${'FactoryGame.FGConsumableDescriptor'}${'\''}`,
	Classes: [
		docs_json_ts_1_2_2_0_classes_FGConsumableDescriptor,
		...docs_json_ts_1_2_2_0_classes_FGConsumableDescriptor[],
	],
};

type FGEquipmentDescriptor = {
	NativeClass: `/Script/CoreUObject.Class'/Script/${'FactoryGame.FGEquipmentDescriptor'}${'\''}`,
	Classes: [
		docs_json_ts_1_2_2_0_classes_FGEquipmentDescriptor,
		...docs_json_ts_1_2_2_0_classes_FGEquipmentDescriptor[],
	],
};

type FGItemDescriptor = {
	NativeClass: `/Script/CoreUObject.Class'/Script/${'FactoryGame.FGItemDescriptor'}${'\''}`,
	Classes: [
		FGItemDescriptor_item,
		...FGItemDescriptor_item[],
	],
};

type FGItemDescriptor_item = docs_json_ts_1_2_2_0_classes_FGItemDescriptor_non_sinkable | docs_json_ts_1_2_2_0_classes_FGItemDescriptor_sinkable;

type FGItemDescriptorBiomass = {
	NativeClass: `/Script/CoreUObject.Class'/Script/${'FactoryGame.FGItemDescriptorBiomass'}${'\''}`,
	Classes: [
		docs_json_ts_1_2_2_0_classes_FGItemDescriptorBiomass,
		...docs_json_ts_1_2_2_0_classes_FGItemDescriptorBiomass[],
	],
};

type FGItemDescriptorNuclearFuel = {
	NativeClass: `/Script/CoreUObject.Class'/Script/${'FactoryGame.FGItemDescriptorNuclearFuel'}${'\''}`,
	Classes: [
		docs_json_ts_1_2_2_0_classes_FGItemDescriptorNuclearFuel,
		...docs_json_ts_1_2_2_0_classes_FGItemDescriptorNuclearFuel[],
	],
};

type FGItemDescriptorPowerBoosterFuel = {
	NativeClass: `/Script/CoreUObject.Class'/Script/${'FactoryGame.FGItemDescriptorPowerBoosterFuel'}${'\''}`,
	Classes: [
		docs_json_ts_1_2_2_0_classes_FGItemDescriptorPowerBoosterFuel,
		...docs_json_ts_1_2_2_0_classes_FGItemDescriptorPowerBoosterFuel[],
	],
};

type FGPowerShardDescriptor = {
	NativeClass: `/Script/CoreUObject.Class'/Script/${'FactoryGame.FGPowerShardDescriptor'}${'\''}`,
	Classes: [
		docs_json_ts_1_2_2_0_classes_FGPowerShardDescriptor,
		...docs_json_ts_1_2_2_0_classes_FGPowerShardDescriptor[],
	],
};

type FGResourceDescriptor = {
	NativeClass: `/Script/CoreUObject.Class'/Script/${'FactoryGame.FGResourceDescriptor'}${'\''}`,
	Classes: [
		docs_json_ts_1_2_2_0_classes_FGResourceDescriptor,
		...docs_json_ts_1_2_2_0_classes_FGResourceDescriptor[],
	],
};

type FGVehicleDescriptor = {
	NativeClass: `/Script/CoreUObject.Class'/Script/${'FactoryGame.FGVehicleDescriptor'}${'\''}`,
	Classes: [
		docs_json_ts_1_2_2_0_classes_FGVehicleDescriptor_Desc_CyberWagon_C,
		docs_json_ts_1_2_2_0_classes_FGVehicleDescriptor_Desc_DroneTransport_C,
		docs_json_ts_1_2_2_0_classes_FGVehicleDescriptor_Desc_Explorer_C,
		docs_json_ts_1_2_2_0_classes_FGVehicleDescriptor_Desc_FreightWagon_C,
		docs_json_ts_1_2_2_0_classes_FGVehicleDescriptor_Desc_Locomotive_C,
		docs_json_ts_1_2_2_0_classes_FGVehicleDescriptor_Desc_FluidTruck_C,
		docs_json_ts_1_2_2_0_classes_FGVehicleDescriptor_Desc_Truck_C,
		docs_json_ts_1_2_2_0_classes_FGVehicleDescriptor_Desc_Tractor_C,
	],
};

export type release_1_2_2_0_docs = [
	FGItemDescriptor,
	FGResourceDescriptor,
	docs_json_ts_1_2_0_0_FGBuildableWallLightweight,
	docs_json_ts_1_2_0_0_FGRecipe,
	docs_json_ts_1_2_0_0_FGConsumableEquipment,
	docs_json_ts_1_2_0_0_FGEquipmentStunSpear,
	FGEquipmentDescriptor,
	docs_json_ts_1_2_0_0_FGCustomizationRecipe,
	docs_json_ts_1_2_0_0_FGObjectScanner,
	FGItemDescriptorBiomass,
	FGConsumableDescriptor,
	docs_json_ts_1_2_0_0_FGBuildable,
	FGBuildingDescriptor,
	docs_json_ts_1_2_0_0_FGVehiclePathSegment,
	FGAmmoTypeProjectile,
	docs_json_ts_1_2_0_0_FGBuildableRailroadTrack,
	docs_json_ts_1_2_0_0_FGBuildableBeam,
	docs_json_ts_1_2_0_0_FGWeapon,
	FGAmmoTypeSpreadshot,
	FGAmmoTypeInstantHit,
	docs_json_ts_1_1_2_2_FGGasMask,
	docs_json_ts_1_1_2_2_FGSuitBase,
	docs_json_ts_1_1_2_2_FGJetPack,
	docs_json_ts_1_2_0_0_FGChargedWeapon,
	docs_json_ts_1_2_0_0_FGBuildableTradingPost,
	docs_json_ts_1_2_0_0_FGBuildablePoleConveyor,
	docs_json_ts_1_2_0_0_FGBuildablePoleBase,
	docs_json_ts_1_2_0_0_FGBuildableConveyorBelt,
	docs_json_ts_1_2_0_0_FGBuildablePowerPole,
	docs_json_ts_1_2_0_0_FGBuildableWire,
	docs_json_ts_1_2_0_0_FGSchematic,
	docs_json_ts_1_2_0_0_FGBuildableStair,
	docs_json_ts_1_2_0_0_FGBuildableWalkwayLightweight,
	docs_json_ts_1_2_0_0_FGBuildableWalkway,
	docs_json_ts_1_2_0_0_FGBuildableWall,
	docs_json_ts_1_2_0_0_FGBuildablePillarLightweight,
	docs_json_ts_1_2_0_0_FGBuildableFactory,
	docs_json_ts_1_2_0_0_FGBuildableGeneratorFuel,
	docs_json_ts_1_2_0_0_FGBuildableStorage,
	docs_json_ts_1_2_0_0_FGBuildableResourceExtractor,
	docs_json_ts_1_1_2_2_FGPortableMinerDispenser,
	docs_json_ts_1_2_0_0_FGBuildableManufacturer,
	docs_json_ts_1_2_0_0_FGBuildableSpaceElevator,
	docs_json_ts_1_2_0_0_FGBuildableCornerWall,
	docs_json_ts_1_2_0_0_FGBuildableDoor,
	docs_json_ts_1_2_0_0_FGBuildableFoundationLightweight,
	docs_json_ts_1_2_0_0_FGBuildableRampLightweight,
	docs_json_ts_1_2_0_0_FGBuildableLadder,
	docs_json_ts_1_2_0_0_FGBuildablePipeReservoir,
	docs_json_ts_1_2_0_0_FGBuildablePipelinePump,
	docs_json_ts_1_2_0_0_FGBuildablePoleStackable,
	docs_json_ts_1_2_0_0_FGBuildablePolePipe,
	docs_json_ts_1_2_0_0_FGBuildablePassthrough,
	docs_json_ts_1_2_0_0_FGPipeHyperStart,
	docs_json_ts_1_2_0_0_FGBuildablePipeHyperJunction,
	docs_json_ts_1_2_0_0_FGBuildablePipeHyper,
	docs_json_ts_1_2_0_0_FGBuildablePipelineJunction,
	docs_json_ts_1_2_0_0_FGBuildableWaterPump,
	docs_json_ts_1_2_0_0_FGBuildableResourceSink,
	docs_json_ts_1_2_0_0_FGBuildableResourceSinkShop,
	docs_json_ts_1_2_0_0_FGBuildablePipeline,
	FGItemDescriptorNuclearFuel,
	docs_json_ts_1_2_0_0_FGBuildableDroneStation,
	docs_json_ts_1_1_2_2_FGGolfCartDispenser,
	FGVehicleDescriptor,
	docs_json_ts_1_2_0_0_FGBuildableLightSource,
	docs_json_ts_1_2_0_0_FGBuildableFloodlight,
	docs_json_ts_1_2_0_0_FGBuildableStackableShelf,
	docs_json_ts_1_2_0_0_FGBuildableCornerWallLightweight,
	docs_json_ts_1_2_0_0_FGBuildableElevatorFloorStop,
	docs_json_ts_1_2_0_0_FGBuildableElevator,
	docs_json_ts_1_2_0_0_FGBuildableLightsControlPanel,
	docs_json_ts_1_2_0_0_FGBuildableWidgetSign,
	docs_json_ts_1_2_0_0_FGBuildablePassthroughPipeHyper,
	docs_json_ts_1_2_0_0_FGBuildableBarrierCorner,
	docs_json_ts_1_2_0_0_FGBuildableConveyorMonitor,
	docs_json_ts_1_2_0_0_FGBuildableFactoryBuilding,
	docs_json_ts_1_2_0_0_FGBuildableManufacturerVariablePower,
	docs_json_ts_1_2_0_0_FGBuildableConveyorLift,
	FGPowerShardDescriptor,
	docs_json_ts_1_2_0_0_FGBuildableFrackingExtractor,
	docs_json_ts_1_2_0_0_FGBuildableFrackingActivator,
	docs_json_ts_1_2_0_0_FGBuildableGeneratorNuclear,
	docs_json_ts_1_1_2_2_FGChainsaw,
	docs_json_ts_1_2_0_0_FGBuildableSnowDispenser,
	docs_json_ts_1_2_0_0_FGBuildableSnowCannon,
	docs_json_ts_1_2_0_0_FGBuildableFactorySimpleProducer,
	docs_json_ts_1_2_0_0_FGBuildableMergerPriority,
	docs_json_ts_1_2_0_0_FGBuildableRadarTower,
	docs_json_ts_1_2_0_0_FGParachute,
	docs_json_ts_1_2_0_0_FGBuildableGeneratorGeoThermal,
	docs_json_ts_1_2_0_0_FGBuildableSplitterSmart,
	FGBuildablePriorityPowerSwitch,
	docs_json_ts_1_1_2_2_FGJumpingStilts,
	FGBuildableCircuitSwitch,
	docs_json_ts_1_1_2_2_FGEquipmentZipline,
	docs_json_ts_1_2_0_0_FGBuildablePowerBooster,
	docs_json_ts_1_2_0_0_FGCentralStorageContainer,
	FGItemDescriptorPowerBoosterFuel,
	docs_json_ts_1_2_0_0_FGBuildablePortal,
	docs_json_ts_1_2_0_0_FGBuildablePortalSatellite,
	docs_json_ts_1_2_0_0_FGBuildableBlueprintDesigner,
	docs_json_ts_1_2_0_0_FGHoverPack,
	docs_json_ts_1_2_0_0_FGBuildableRailroadSignal,
	docs_json_ts_1_2_0_0_FGBuildableRailroadAttachment,
	docs_json_ts_1_2_0_0_FGBuildableRailroadStation,
	docs_json_ts_1_2_0_0_FGBuildableTrainPlatformCargo,
	docs_json_ts_1_2_0_0_FGBuildableTrainPlatformEmpty,
	docs_json_ts_1_2_0_0_FGBuildableDockingStation,
	docs_json_ts_1_2_0_0_FGBuildablePowerStorage,
	docs_json_ts_1_2_0_0_FGBuildableJumppad,
	docs_json_ts_1_2_0_0_FGBuildableMAM,
	docs_json_ts_1_2_0_0_FGBuildableAttachmentMerger,
	docs_json_ts_1_2_0_0_FGBuildableAttachmentSplitter,
];

export type {
	FGAmmoTypeInstantHit,
	FGAmmoTypeProjectile,
	FGAmmoTypeSpreadshot,
	FGBuildableCircuitSwitch,
	FGBuildablePriorityPowerSwitch,
	FGBuildingDescriptor,
	FGConsumableDescriptor,
	FGEquipmentDescriptor,
	FGItemDescriptor,
	FGItemDescriptor_item,
	FGItemDescriptorBiomass,
	FGItemDescriptorNuclearFuel,
	FGItemDescriptorPowerBoosterFuel,
	FGPowerShardDescriptor,
	FGResourceDescriptor,
	FGVehicleDescriptor,
};
