/* eslint-disable @stylistic/max-len */

import type {
	bool_string as docs_json_ts_common_types_bool_string,
	decimal_string as docs_json_ts_common_types_decimal_string,
	decimal_string_signed as docs_json_ts_common_types_decimal_string_signed,
	empty_object as docs_json_ts_common_types_empty_object,
	integer_string as docs_json_ts_common_types_integer_string,
	integer_string_signed as docs_json_ts_common_types_integer_string_signed,
	XY_decimal_string as docs_json_ts_common_types_XY_decimal_string,
	XY_integer_string as docs_json_ts_common_types_XY_integer_string,
	XYZ_decimal_string as docs_json_ts_common_types_XYZ_decimal_string,
	XYZW_decimal_string as docs_json_ts_common_types_XYZW_decimal_string,
} from './../../common/types.ts';

import type {
	CameraAnimationSequence_quoted as docs_json_ts_0_8_3_3_properties_CameraAnimationSequence_quoted,
	DocsDotJson_AkAudioEvent_quoted_list as docs_json_ts_0_8_3_3_properties_DocsDotJson_AkAudioEvent_quoted_list,
	FGRailroadTrackConnectionComponent_quoted as docs_json_ts_0_8_3_3_properties_FGRailroadTrackConnectionComponent_quoted,
	FGTrainPlatformConnection_quoted as docs_json_ts_0_8_3_3_properties_FGTrainPlatformConnection_quoted,
	mComponentNameToFirstPersonMaterials_item as docs_json_ts_0_8_3_3_properties_mComponentNameToFirstPersonMaterials_item,
	mDamageTypes as docs_json_ts_0_8_3_3_properties_mDamageTypes,
	mUnlocks_item as docs_json_ts_0_8_3_3_properties_mUnlocks_item,
} from './../types/properties.ts';

import type {
	AnimMontage_quoted as docs_json_ts_0_3_7_7_properties_AnimMontage_quoted,
	MaterialInstanceConstant_quoted as docs_json_ts_0_3_7_7_properties_MaterialInstanceConstant_quoted,
} from './../../0.3.7.7/types/properties.ts';

import type {
	FGAmmoType_base as docs_json_ts_0_6_1_5_classes_base_FGAmmoType_base,
	FGAmmoType_version_specific as docs_json_ts_0_6_1_5_classes_base_FGAmmoType_version_specific,
	FGAmmoTypeInstantHit_Desc_CartridgeChaos_C_version_specific as docs_json_ts_0_6_1_5_classes_base_FGAmmoTypeInstantHit_Desc_CartridgeChaos_C_version_specific,
	FGAmmoTypeInstantHit_version_specific as docs_json_ts_0_6_1_5_classes_base_FGAmmoTypeInstantHit_version_specific,
	FGAmmoTypeProjectile_version_specific as docs_json_ts_0_6_1_5_classes_base_FGAmmoTypeProjectile_version_specific,
	FGAmmoTypeSpreadshot_version_specific as docs_json_ts_0_6_1_5_classes_base_FGAmmoTypeSpreadshot_version_specific,
	FGBuildable_base_pre_update8 as docs_json_ts_0_6_1_5_classes_base_FGBuildable_base_pre_update8,
	FGBuildable_foundation_mDisableSnapOn as docs_json_ts_0_6_1_5_classes_base_FGBuildable_foundation_mDisableSnapOn,
	FGBuildable_with_depth as docs_json_ts_0_6_1_5_classes_base_FGBuildable_with_depth,
	FGBuildableCornerWall_version_specific as docs_json_ts_0_6_1_5_classes_base_FGBuildableCornerWall_version_specific,
	FGBuildableFoundation_version_specific as docs_json_ts_0_6_1_5_classes_base_FGBuildableFoundation_version_specific,
	FGBuildableManufacturer_Build_SmelterMk1_C_base as docs_json_ts_0_6_1_5_classes_base_FGBuildableManufacturer_Build_SmelterMk1_C_base,
	FGBuildablePipeline_version_specific as docs_json_ts_0_6_1_5_classes_base_FGBuildablePipeline_version_specific,
	FGBuildableRadarTower_base as docs_json_ts_0_6_1_5_classes_base_FGBuildableRadarTower_base,
	FGBuildableResourceExtractor_base_version_specific_base as docs_json_ts_0_6_1_5_classes_base_FGBuildableResourceExtractor_base_version_specific_base,
	FGBuildableTrainPlatformCargo_version_specific as docs_json_ts_0_6_1_5_classes_base_FGBuildableTrainPlatformCargo_version_specific,
	FGChainsaw_version_specific as docs_json_ts_0_6_1_5_classes_base_FGChainsaw_version_specific,
	FGEquipment_noisy_version_specific as docs_json_ts_0_6_1_5_classes_base_FGEquipment_noisy_version_specific,
	FGEquipment_version_specific as docs_json_ts_0_6_1_5_classes_base_FGEquipment_version_specific,
	FGEquipmentStunSpear_base_version_specific as docs_json_ts_0_6_1_5_classes_base_FGEquipmentStunSpear_base_version_specific,
	FGJumpingStilts_version_specific as docs_json_ts_0_6_1_5_classes_base_FGJumpingStilts_version_specific,
	FGSchematic_version_specific_base as docs_json_ts_0_6_1_5_classes_base_FGSchematic_version_specific_base,
	FGSuitBase_version_specific as docs_json_ts_0_6_1_5_classes_base_FGSuitBase_version_specific,
	FGWeapon_base as docs_json_ts_0_6_1_5_classes_base_FGWeapon_base,
	FGWeapon_Equip_RebarGun_Projectile_C_version_specific as docs_json_ts_0_6_1_5_classes_base_FGWeapon_Equip_RebarGun_Projectile_C_version_specific,
} from './../../0.6.1.5/classes/Base.ts';

import type {
	FGBuildable_base_pre_update8 as docs_json_ts_0_7_1_1_classes_base_FGBuildable_base_pre_update8,
	FGBuildable_powered_pre_update8 as docs_json_ts_0_7_1_1_classes_base_FGBuildable_powered_pre_update8,
	FGBuildableBlueprintDesigner_pre_update8 as docs_json_ts_0_7_1_1_classes_base_FGBuildableBlueprintDesigner_pre_update8,
	FGBuildableCircuitSwitch_version_specific as docs_json_ts_0_7_1_1_classes_base_FGBuildableCircuitSwitch_version_specific,
	FGBuildablePole_version_specific as docs_json_ts_0_7_1_1_classes_base_FGBuildablePole_version_specific,
	FGJetPack_version_specific as docs_json_ts_0_7_1_1_classes_base_FGJetPack_version_specific,
} from './../../0.7.1.1/classes/Base.ts';

import type {
	FGBuildable_base_pre_update8 as docs_json_ts_0_5_2_1_classes_base_FGBuildable_base_pre_update8,
	FGBuildable_is_wallish as docs_json_ts_0_5_2_1_classes_base_FGBuildable_is_wallish,
	FGBuildable_isFrame as docs_json_ts_0_5_2_1_classes_base_FGBuildable_isFrame,
	FGBuildable_mHasPower as docs_json_ts_0_5_2_1_classes_base_FGBuildable_mHasPower,
	FGBuildable_mSnappedPassthroughs as docs_json_ts_0_5_2_1_classes_base_FGBuildable_mSnappedPassthroughs,
	FGBuildable_powered_base_base as docs_json_ts_0_5_2_1_classes_base_FGBuildable_powered_base_base,
	FGBuildable_with_elevation as docs_json_ts_0_5_2_1_classes_base_FGBuildable_with_elevation,
	FGBuildableBeam_base as docs_json_ts_0_5_2_1_classes_base_FGBuildableBeam_base,
	FGBuildableConveyorBelt_spline as docs_json_ts_0_5_2_1_classes_base_FGBuildableConveyorBelt_spline,
	FGBuildableDockingStation_base as docs_json_ts_0_5_2_1_classes_base_FGBuildableDockingStation_base,
	FGBuildableDoor_automated_version_specific as docs_json_ts_0_5_2_1_classes_base_FGBuildableDoor_automated_version_specific,
	FGBuildableDoor_base as docs_json_ts_0_5_2_1_classes_base_FGBuildableDoor_base,
	FGBuildableDoor_manual_version_specific as docs_json_ts_0_5_2_1_classes_base_FGBuildableDoor_manual_version_specific,
	FGBuildableLightsControlPanel_version_specific as docs_json_ts_0_5_2_1_classes_base_FGBuildableLightsControlPanel_version_specific,
	FGBuildableLightSource_base as docs_json_ts_0_5_2_1_classes_base_FGBuildableLightSource_base,
	FGBuildableLightSource_Build_StreetLight_C_version_specific as docs_json_ts_0_5_2_1_classes_base_FGBuildableLightSource_Build_StreetLight_C_version_specific,
	FGBuildableManufacturer_Build_ConstructorMk1_C_base as docs_json_ts_0_5_2_1_classes_base_FGBuildableManufacturer_Build_ConstructorMk1_C_base,
	FGBuildableManufacturer_Build_FoundryMk1_C_base as docs_json_ts_0_5_2_1_classes_base_FGBuildableManufacturer_Build_FoundryMk1_C_base,
	FGBuildablePassthrough_base as docs_json_ts_0_5_2_1_classes_base_FGBuildablePassthrough_base,
	FGBuildablePillar_base as docs_json_ts_0_5_2_1_classes_base_FGBuildablePillar_base,
	FGBuildablePipeline_base_spline as docs_json_ts_0_5_2_1_classes_base_FGBuildablePipeline_base_spline,
	FGBuildableRailroadSignal_base_version_specific as docs_json_ts_0_5_2_1_classes_base_FGBuildableRailroadSignal_base_version_specific,
	FGBuildableRailroadSignal_block_version_specific as docs_json_ts_0_5_2_1_classes_base_FGBuildableRailroadSignal_block_version_specific,
	FGBuildableRailroadStation_base as docs_json_ts_0_5_2_1_classes_base_FGBuildableRailroadStation_base,
	FGBuildableRailroadTrack_base_version_specific as docs_json_ts_0_5_2_1_classes_base_FGBuildableRailroadTrack_base_version_specific,
	FGBuildableRamp_base as docs_json_ts_0_5_2_1_classes_base_FGBuildableRamp_base,
	FGBuildableStair_has_mStairDirection as docs_json_ts_0_5_2_1_classes_base_FGBuildableStair_has_mStairDirection,
	FGBuildableTradingPost_base as docs_json_ts_0_5_2_1_classes_base_FGBuildableTradingPost_base,
	FGBuildableTrainPlatform_base_version_specific as docs_json_ts_0_5_2_1_classes_base_FGBuildableTrainPlatform_base_version_specific,
	FGBuildableTrainPlatform_non_empty_version_specific as docs_json_ts_0_5_2_1_classes_base_FGBuildableTrainPlatform_non_empty_version_specific,
	FGBuildableTrainPlatformCargo_version_specific as docs_json_ts_0_5_2_1_classes_base_FGBuildableTrainPlatformCargo_version_specific,
	FGBuildableWidgetSign_base as docs_json_ts_0_5_2_1_classes_base_FGBuildableWidgetSign_base,
	FGGolfCartDispenser_version_specific as docs_json_ts_0_5_2_1_classes_base_FGGolfCartDispenser_version_specific,
	FGNobeliskDetonator_base as docs_json_ts_0_5_2_1_classes_base_FGNobeliskDetonator_base,
	FGSchematic_base_base_base as docs_json_ts_0_5_2_1_classes_base_FGSchematic_base_base_base,
	FGSchematic_with_described_unlocks_base_base as docs_json_ts_0_5_2_1_classes_base_FGSchematic_with_described_unlocks_base_base,
	FGWeapon_base_base as docs_json_ts_0_5_2_1_classes_base_FGWeapon_base_base,
	FGWeapon_Equip_Rifle_C_base as docs_json_ts_0_5_2_1_classes_base_FGWeapon_Equip_Rifle_C_base,
} from './../../0.5.2.1/classes/Base.ts';

import type {
	FGBuildable_base_pre_update8 as docs_json_ts_0_4_2_11_classes_base_FGBuildable_base_pre_update8,
	FGBuildable_light_related_thing_base as docs_json_ts_0_4_2_11_classes_base_FGBuildable_light_related_thing_base,
	FGBuildable_mHasPower_base as docs_json_ts_0_4_2_11_classes_base_FGBuildable_mHasPower_base,
	FGBuildable_mStopped_audio_stuff_base as docs_json_ts_0_4_2_11_classes_base_FGBuildable_mStopped_audio_stuff_base,
	FGBuildable_powered_base_base as docs_json_ts_0_4_2_11_classes_base_FGBuildable_powered_base_base,
	FGBuildableCircuitSwitch_base as docs_json_ts_0_4_2_11_classes_base_FGBuildableCircuitSwitch_base,
	FGBuildableDroneStation_base_base_base as docs_json_ts_0_4_2_11_classes_base_FGBuildableDroneStation_base_base_base,
	FGBuildableFloodlight_base as docs_json_ts_0_4_2_11_classes_base_FGBuildableFloodlight_base,
	FGBuildableFrackingActivator_base_base as docs_json_ts_0_4_2_11_classes_base_FGBuildableFrackingActivator_base_base,
	FGBuildableGeneratorFuel_base_base_base as docs_json_ts_0_4_2_11_classes_base_FGBuildableGeneratorFuel_base_base_base,
	FGBuildableGeneratorGeoThermal_base as docs_json_ts_0_4_2_11_classes_base_FGBuildableGeneratorGeoThermal_base,
	FGBuildableGeneratorNuclear_base as docs_json_ts_0_4_2_11_classes_base_FGBuildableGeneratorNuclear_base,
	FGBuildableLightsControlPanel_base as docs_json_ts_0_4_2_11_classes_base_FGBuildableLightsControlPanel_base,
	FGBuildableLightSource_base as docs_json_ts_0_4_2_11_classes_base_FGBuildableLightSource_base,
	FGBuildableMAM_version_specific as docs_json_ts_0_4_2_11_classes_base_FGBuildableMAM_version_specific,
	FGBuildableManufacturer_base_blender_base_base as docs_json_ts_0_4_2_11_classes_base_FGBuildableManufacturer_base_blender_base_base,
	FGBuildableManufacturer_base_constructor_base_base as docs_json_ts_0_4_2_11_classes_base_FGBuildableManufacturer_base_constructor_base_base,
	FGBuildableManufacturer_Build_HadronCollider_C_base as docs_json_ts_0_4_2_11_classes_base_FGBuildableManufacturer_Build_HadronCollider_C_base,
	FGBuildablePipelineJunction_base_base_base as docs_json_ts_0_4_2_11_classes_base_FGBuildablePipelineJunction_base_base_base,
	FGBuildablePowerStorage_base as docs_json_ts_0_4_2_11_classes_base_FGBuildablePowerStorage_base,
	FGBuildableResourceExtractor_miner_mk1_base_base_base as docs_json_ts_0_4_2_11_classes_base_FGBuildableResourceExtractor_miner_mk1_base_base_base,
	FGBuildableResourceExtractor_water_base as docs_json_ts_0_4_2_11_classes_base_FGBuildableResourceExtractor_water_base,
	FGBuildableResourceSink_base_base as docs_json_ts_0_4_2_11_classes_base_FGBuildableResourceSink_base_base,
	FGConsumableEquipment_version_specific as docs_json_ts_0_4_2_11_classes_base_FGConsumableEquipment_version_specific,
	FGEquipment_version_specific as docs_json_ts_0_4_2_11_classes_base_FGEquipment_version_specific,
	FGEquipmentZipline_base as docs_json_ts_0_4_2_11_classes_base_FGEquipmentZipline_base,
	FGHoverPack_version_specific as docs_json_ts_0_4_2_11_classes_base_FGHoverPack_version_specific,
	FGPortableMinerDispenser_version_specific as docs_json_ts_0_4_2_11_classes_base_FGPortableMinerDispenser_version_specific,
	FGSchematic_base_base_props_sans_mSchematicIcon_mMenuPriority as docs_json_ts_0_4_2_11_classes_base_FGSchematic_base_base_props_sans_mSchematicIcon_mMenuPriority,
	FGWeaponProjectile_has_mBlockSprintWhenFiring as docs_json_ts_0_4_2_11_classes_base_FGWeaponProjectile_has_mBlockSprintWhenFiring,
	FGWeaponProjectileFire_has_mMuteDryFire as docs_json_ts_0_4_2_11_classes_base_FGWeaponProjectileFire_has_mMuteDryFire,
} from './../../0.4.2.11/classes/Base.ts';

import type {
	FGBuildable_base_pre_update8 as docs_json_ts_0_3_7_7_classes_base_FGBuildable_base_pre_update8,
	FGBuildable_docking_station_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildable_docking_station_base_base_base,
	FGBuildable_docking_station_base_with_mMapText as docs_json_ts_0_3_7_7_classes_base_FGBuildable_docking_station_base_with_mMapText,
	FGBuildable_occupied_base as docs_json_ts_0_3_7_7_classes_base_FGBuildable_occupied_base,
	FGBuildable_pole_with_length_and_power_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildable_pole_with_length_and_power_base_base,
	FGBuildable_powered_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildable_powered_base_base_base,
	FGBuildable_powered_base_resources_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildable_powered_base_resources_base_base,
	FGBuildable_powered_storage_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildable_powered_storage_base_base_base,
	FGBuildable_spline as docs_json_ts_0_3_7_7_classes_base_FGBuildable_spline,
	FGBuildable_tiered_base as docs_json_ts_0_3_7_7_classes_base_FGBuildable_tiered_base,
	FGBuildable_with_height_and_width_base as docs_json_ts_0_3_7_7_classes_base_FGBuildable_with_height_and_width_base,
	FGBuildable_with_height_base as docs_json_ts_0_3_7_7_classes_base_FGBuildable_with_height_base,
	FGBuildable_with_mLength as docs_json_ts_0_3_7_7_classes_base_FGBuildable_with_mLength,
	FGBuildable_with_size_and_elevation_base as docs_json_ts_0_3_7_7_classes_base_FGBuildable_with_size_and_elevation_base,
	FGBuildable_with_size_and_elevation_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildable_with_size_and_elevation_base_base,
	FGBuildable_with_size_base as docs_json_ts_0_3_7_7_classes_base_FGBuildable_with_size_base,
	FGBuildable_with_width_base as docs_json_ts_0_3_7_7_classes_base_FGBuildable_with_width_base,
	FGBuildableAttachment_has_mCurrentOutputIndex as docs_json_ts_0_3_7_7_classes_base_FGBuildableAttachment_has_mCurrentOutputIndex,
	FGBuildableAttachment_splitter_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableAttachment_splitter_base_base_base,
	FGBuildableAttachmentMerger_pre_update7 as docs_json_ts_0_3_7_7_classes_base_FGBuildableAttachmentMerger_pre_update7,
	FGBuildableConveyorLift_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableConveyorLift_base,
	FGBuildableDockingStation_with_mFuelTransferSpeed_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableDockingStation_with_mFuelTransferSpeed_base,
	FGBuildableFactory_jump_pad_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableFactory_jump_pad_base_base_base,
	FGBuildableFactory_landing_pad_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableFactory_landing_pad_base_base_base,
	FGBuildableFactorySimpleProducer_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableFactorySimpleProducer_base_base,
	FGBuildableGenerator_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableGenerator_base_base_base,
	FGBuildableGenerator_no_fuel_base_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableGenerator_no_fuel_base_base_base_base,
	FGBuildableGeneratorFuel_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableGeneratorFuel_base_base_base,
	FGBuildableGeneratorFuel_biomass_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableGeneratorFuel_biomass_base_base,
	FGBuildableGeneratorFuel_coal_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableGeneratorFuel_coal_base_base,
	FGBuildableGeneratorFuel_fuel_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableGeneratorFuel_fuel_base_base,
	FGBuildableGeneratorGeoThermal_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableGeneratorGeoThermal_base_base_base,
	FGBuildableGeneratorNuclear_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableGeneratorNuclear_base_base_base,
	FGBuildableJumppad_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableJumppad_base_base_base,
	FGBuildableLadder_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableLadder_base,
	FGBuildableManufacturer_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_base_base,
	FGBuildableManufacturer_base_IsPowered_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_IsPowered_base_base,
	FGBuildableManufacturer_base_mProductionEffectsRunning_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_mProductionEffectsRunning_base_base,
	FGBuildableManufacturer_base_packager_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_packager_base_base,
	FGBuildablePipeline_base_root as docs_json_ts_0_3_7_7_classes_base_FGBuildablePipeline_base_root,
	FGBuildablePipeline_base_spline_base as docs_json_ts_0_3_7_7_classes_base_FGBuildablePipeline_base_spline_base,
	FGBuildablePipelinePump_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildablePipelinePump_base_base_base,
	FGBuildablePipelinePump_powered_base_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildablePipelinePump_powered_base_base_base_base,
	FGBuildablePipelinePump_pump_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildablePipelinePump_pump_base_base_base,
	FGBuildablePipelineSupport_base as docs_json_ts_0_3_7_7_classes_base_FGBuildablePipelineSupport_base,
	FGBuildablePipeReservoir_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildablePipeReservoir_base_base_base,
	FGBuildablePole_base as docs_json_ts_0_3_7_7_classes_base_FGBuildablePole_base,
	FGBuildableRailroadStation_version_specific as docs_json_ts_0_3_7_7_classes_base_FGBuildableRailroadStation_version_specific,
	FGBuildableRailroadTrack_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableRailroadTrack_base,
	FGBuildableResourceExtractor_base_base_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_base_base_base_base_base,
	FGBuildableResourceExtractor_base_base_base_piped_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_base_base_base_piped_base,
	FGBuildableResourceExtractor_base_base_timed_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_base_base_timed_base,
	FGBuildableResourceExtractor_miner_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_miner_base_base_base,
	FGBuildableResourceExtractor_miner_mk2_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_miner_mk2_base_base_base,
	FGBuildableResourceExtractor_miner_mk3_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_miner_mk3_base_base_base,
	FGBuildableResourceExtractor_oil_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_oil_base_base_base,
	FGBuildableResourceExtractor_water_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_water_base_base_base,
	FGBuildableResourceSinkShop_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceSinkShop_base_base_base,
	FGBuildableSplitterSmart_version_specific as docs_json_ts_0_3_7_7_classes_base_FGBuildableSplitterSmart_version_specific,
	FGBuildableStorage_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableStorage_base_base_base,
	FGBuildableTradingPost_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableTradingPost_base_base_base,
	FGBuildableTrainPlatform_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableTrainPlatform_base_base_base,
	FGBuildableTrainPlatformCargo_pre_update8 as docs_json_ts_0_3_7_7_classes_base_FGBuildableTrainPlatformCargo_pre_update8,
	FGBuildableWire_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableWire_base,
	FGChainsaw_version_specific as docs_json_ts_0_3_7_7_classes_base_FGChainsaw_version_specific,
	FGConsumableEquipment_version_specific_pre_update8 as docs_json_ts_0_3_7_7_classes_base_FGConsumableEquipment_version_specific_pre_update8,
	FGEquipment_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGEquipment_base_base_base,
	FGEquipment_dispenser_version_specific as docs_json_ts_0_3_7_7_classes_base_FGEquipment_dispenser_version_specific,
	FGEquipment_filtered as docs_json_ts_0_3_7_7_classes_base_FGEquipment_filtered,
	FGEquipment_has_effect_timer as docs_json_ts_0_3_7_7_classes_base_FGEquipment_has_effect_timer,
	FGEquipment_has_mEquipmentSlot as docs_json_ts_0_3_7_7_classes_base_FGEquipment_has_mEquipmentSlot,
	FGEquipment_has_mPlayingSound as docs_json_ts_0_3_7_7_classes_base_FGEquipment_has_mPlayingSound,
	FGEquipment_has_mRandomStingerAnim as docs_json_ts_0_3_7_7_classes_base_FGEquipment_has_mRandomStingerAnim,
	FGEquipment_negates_damage as docs_json_ts_0_3_7_7_classes_base_FGEquipment_negates_damage,
	FGEquipmentStunSpear_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGEquipmentStunSpear_base_base_base,
	FGEquipmentStunSpear_base_version_specific as docs_json_ts_0_3_7_7_classes_base_FGEquipmentStunSpear_base_version_specific,
	FGEquipmentStunSpear_xenobasher_version_specific as docs_json_ts_0_3_7_7_classes_base_FGEquipmentStunSpear_xenobasher_version_specific,
	FGGasMask_base as docs_json_ts_0_3_7_7_classes_base_FGGasMask_base,
	FGGolfCartDispenser_has_mArmAnimation as docs_json_ts_0_3_7_7_classes_base_FGGolfCartDispenser_has_mArmAnimation,
	FGJetPack_version_specific as docs_json_ts_0_3_7_7_classes_base_FGJetPack_version_specific,
	FGJumpingStilts_base as docs_json_ts_0_3_7_7_classes_base_FGJumpingStilts_base,
	FGNobeliskDetonator_base as docs_json_ts_0_3_7_7_classes_base_FGNobeliskDetonator_base,
	FGObjectScanner_version_specific as docs_json_ts_0_3_7_7_classes_base_FGObjectScanner_version_specific,
	FGParachute_has_mIsDeployed as docs_json_ts_0_3_7_7_classes_base_FGParachute_has_mIsDeployed,
	FGPipeHyperStart_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGPipeHyperStart_base_base_base,
	FGPortableMinerDispenser_version_specific as docs_json_ts_0_3_7_7_classes_base_FGPortableMinerDispenser_version_specific,
	FGSuitBase_base as docs_json_ts_0_3_7_7_classes_base_FGSuitBase_base,
	FGWeaponInstantFire_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGWeaponInstantFire_base_base_base,
	FGWeaponProjectile_has_mAttachSocket as docs_json_ts_0_3_7_7_classes_base_FGWeaponProjectile_has_mAttachSocket,
	FGWeaponProjectileFire_has_mRandomReloadAnim as docs_json_ts_0_3_7_7_classes_base_FGWeaponProjectileFire_has_mRandomReloadAnim,
} from './../../0.3.7.7/classes/Base.ts';

import type {
	Texture2D_quoted as docs_json_ts_0_4_2_11_properties_Texture2D_quoted,
	TintColor as docs_json_ts_0_4_2_11_properties_TintColor,
} from './../../0.4.2.11/types/properties.ts';

type has_mFuelInventoryHandlerData = {
	mFuelInventoryHandlerData: docs_json_ts_common_types_empty_object,
};

type has_mInventoryHandlerData = {
	mInventoryHandlerData: docs_json_ts_common_types_empty_object,
};

type FGAmmoType_version_specific = {
	mAmmoTickFunction: {
		bAllowTickOnDedicatedServer: docs_json_ts_common_types_bool_string,
	},
	mDamageTypesOnImpact: null | docs_json_ts_0_8_3_3_properties_mDamageTypes,
	mFiringSounds: null | docs_json_ts_0_8_3_3_properties_DocsDotJson_AkAudioEvent_quoted_list,
	mFiringSounds1P: '',
	mMagazineMeshMaterials1p: [
		docs_json_ts_0_3_7_7_properties_MaterialInstanceConstant_quoted,
		...docs_json_ts_0_3_7_7_properties_MaterialInstanceConstant_quoted[],
	],
};

type FGAmmoTypeInstantHit_Desc_CartridgeChaos_C = docs_json_ts_0_6_1_5_classes_base_FGAmmoType_base & docs_json_ts_0_6_1_5_classes_base_FGAmmoType_version_specific & docs_json_ts_0_6_1_5_classes_base_FGAmmoTypeInstantHit_version_specific & docs_json_ts_0_6_1_5_classes_base_FGAmmoTypeInstantHit_Desc_CartridgeChaos_C_version_specific & FGAmmoType_version_specific;

type FGAmmoTypeInstantHit_Desc_CartridgeStandard_C = docs_json_ts_0_6_1_5_classes_base_FGAmmoType_base & docs_json_ts_0_6_1_5_classes_base_FGAmmoType_version_specific & docs_json_ts_0_6_1_5_classes_base_FGAmmoTypeInstantHit_version_specific & FGAmmoType_version_specific;

type FGAmmoTypeProjectile = docs_json_ts_0_6_1_5_classes_base_FGAmmoType_base & docs_json_ts_0_6_1_5_classes_base_FGAmmoTypeProjectile_version_specific & FGAmmoType_version_specific & FGAmmoTypeProjectile_version_specific;

type FGAmmoTypeProjectile_version_specific = {
	mDamageTypesAtEndOfLife: null | docs_json_ts_0_8_3_3_properties_mDamageTypes,
};

type FGAmmoTypeSpreadshot = docs_json_ts_0_6_1_5_classes_base_FGAmmoType_base & docs_json_ts_0_6_1_5_classes_base_FGAmmoTypeSpreadshot_version_specific & FGAmmoType_version_specific;

type FGBuildable_base = docs_json_ts_0_7_1_1_classes_base_FGBuildable_base_pre_update8 & docs_json_ts_0_6_1_5_classes_base_FGBuildable_base_pre_update8 & docs_json_ts_0_5_2_1_classes_base_FGBuildable_base_pre_update8 & docs_json_ts_0_4_2_11_classes_base_FGBuildable_base_pre_update8 & docs_json_ts_0_3_7_7_classes_base_FGBuildable_base_pre_update8 & FGBuildable_version_specific;

type FGBuildable_has_mInputInventoryHandlerData = {
	mInputInventoryHandlerData: docs_json_ts_common_types_empty_object,
};

type FGBuildable_has_mOnCircuitsChanged = {
	mOnCircuitsChanged: docs_json_ts_common_types_empty_object,
};

type FGBuildable_has_mOutputInventoryHandlerData = {
	mOutputInventoryHandlerData: docs_json_ts_common_types_empty_object,
};

type FGBuildable_occupied = docs_json_ts_0_3_7_7_classes_base_FGBuildable_occupied_base & FGBuildable_base;

type FGBuildable_powered = docs_json_ts_0_7_1_1_classes_base_FGBuildable_powered_pre_update8 & FGBuildable_with_mInventoryPotentialHandlerData & FGBuildable_powered_base;

type FGBuildable_powered_base = docs_json_ts_0_3_7_7_classes_base_FGBuildable_powered_base_base_base & docs_json_ts_0_5_2_1_classes_base_FGBuildable_powered_base_base & docs_json_ts_0_4_2_11_classes_base_FGBuildable_powered_base_base & FGBuildable_base;

type FGBuildable_tiered = docs_json_ts_0_3_7_7_classes_base_FGBuildable_tiered_base & FGBuildable_base;

type FGBuildable_version_specific = {
	mIsConsideredForBaseWeightValue: docs_json_ts_common_types_decimal_string,
	mOcclusionBoxInfo: null | [
		{
			Min: docs_json_ts_common_types_XYZ_decimal_string,
			Max: docs_json_ts_common_types_XYZ_decimal_string,
			IsValid: docs_json_ts_common_types_bool_string,
		},
		...{
			Min: docs_json_ts_common_types_XYZ_decimal_string,
			Max: docs_json_ts_common_types_XYZ_decimal_string,
			IsValid: docs_json_ts_common_types_bool_string,
		}[],
	],
};

type FGBuildable_with_mInventoryPotentialHandlerData = {
	mInventoryPotentialHandlerData: docs_json_ts_common_types_empty_object,
	mTickExponent: docs_json_ts_common_types_decimal_string,
};

type FGBuildableAttachmentMerger = docs_json_ts_0_3_7_7_classes_base_FGBuildableAttachmentMerger_pre_update7 & FGBuildable_base;

type FGBuildableAttachmentSplitter = docs_json_ts_0_3_7_7_classes_base_FGBuildableAttachment_has_mCurrentOutputIndex & FGBuildable_base;

type FGBuildableBeamLightweight = docs_json_ts_0_5_2_1_classes_base_FGBuildableBeam_base & FGBuildable_base;

type FGBuildableBlueprintDesigner = docs_json_ts_0_7_1_1_classes_base_FGBuildableBlueprintDesigner_pre_update8 & FGBuildable_base & FGBuildableBlueprintDesigner_version_specific;

type FGBuildableBlueprintDesigner_version_specific = {
	mIsDismantlingAll: docs_json_ts_common_types_bool_string,
};

type FGBuildableCircuitSwitch = docs_json_ts_0_4_2_11_classes_base_FGBuildableCircuitSwitch_base & docs_json_ts_0_7_1_1_classes_base_FGBuildableCircuitSwitch_version_specific & FGBuildable_base & FGBuildable_has_mOnCircuitsChanged;

type FGBuildableConveyorBelt = docs_json_ts_0_5_2_1_classes_base_FGBuildableConveyorBelt_spline & FGBuildable_base & FGBuildableConveyorBelt_version_specific;

type FGBuildableConveyorBelt_version_specific = {
	mConveyorChainFlags: docs_json_ts_common_types_integer_string,
};

type FGBuildableConveyorLift = docs_json_ts_0_3_7_7_classes_base_FGBuildableConveyorLift_base & docs_json_ts_0_5_2_1_classes_base_FGBuildable_mSnappedPassthroughs & FGBuildable_base & FGBuildableConveyorBelt_version_specific;

type FGBuildableCornerWall = docs_json_ts_0_6_1_5_classes_base_FGBuildableCornerWall_version_specific & docs_json_ts_0_3_7_7_classes_base_FGBuildable_with_size_base & docs_json_ts_0_3_7_7_classes_base_FGBuildable_with_height_base & FGBuildable_base;

type FGBuildableDockingStation = docs_json_ts_0_5_2_1_classes_base_FGBuildableDockingStation_base & docs_json_ts_0_3_7_7_classes_base_FGBuildable_docking_station_base_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableDockingStation_with_mFuelTransferSpeed_base & FGBuildable_powered & has_mFuelInventoryHandlerData & has_mInventoryHandlerData;

type FGBuildableDoor = FGBuildableDoor_manual | FGBuildableDoor_automated;

type FGBuildableDoor_automated = docs_json_ts_0_5_2_1_classes_base_FGBuildableDoor_automated_version_specific & docs_json_ts_0_5_2_1_classes_base_FGBuildableDoor_base & FGBuildableWall;

type FGBuildableDoor_manual = docs_json_ts_0_5_2_1_classes_base_FGBuildableDoor_manual_version_specific & docs_json_ts_0_5_2_1_classes_base_FGBuildableDoor_base & FGBuildableWall;

type FGBuildableDroneStation = docs_json_ts_0_4_2_11_classes_base_FGBuildableDroneStation_base_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildable_docking_station_base_with_mMapText & FGBuildable_powered & FGBuildableDroneStation_version_specific;

type FGBuildableDroneStation_version_specific = {
	mInputInventoryHandler: docs_json_ts_common_types_empty_object,
	mOutputInventoryHandler: docs_json_ts_common_types_empty_object,
	mBatteryInventoryHandler: docs_json_ts_common_types_empty_object,
};

type FGBuildableFactory_jump_pad = FGBuildable_powered & docs_json_ts_0_3_7_7_classes_base_FGBuildableFactory_jump_pad_base_base_base;

type FGBuildableFactory_landing_pad = FGBuildable_powered & docs_json_ts_0_3_7_7_classes_base_FGBuildableFactory_landing_pad_base_base_base;

type FGBuildableFactorySimpleProducer = FGBuildable_powered & docs_json_ts_0_3_7_7_classes_base_FGBuildableFactorySimpleProducer_base_base;

type FGBuildableFloodlight = docs_json_ts_0_4_2_11_classes_base_FGBuildableFloodlight_base & FGBuildableLightSource & FGBuildable_base;

type FGBuildableFoundation = docs_json_ts_0_3_7_7_classes_base_FGBuildable_with_height_base & docs_json_ts_0_5_2_1_classes_base_FGBuildable_isFrame & docs_json_ts_0_6_1_5_classes_base_FGBuildable_foundation_mDisableSnapOn & docs_json_ts_0_5_2_1_classes_base_FGBuildable_with_elevation & docs_json_ts_0_3_7_7_classes_base_FGBuildable_with_width_base & docs_json_ts_0_6_1_5_classes_base_FGBuildable_with_depth & docs_json_ts_0_6_1_5_classes_base_FGBuildableFoundation_version_specific & FGBuildable_base;

type FGBuildableFrackingActivator = docs_json_ts_0_4_2_11_classes_base_FGBuildableFrackingActivator_base_base & docs_json_ts_0_6_1_5_classes_base_FGBuildableResourceExtractor_base_version_specific_base & FGBuildable_powered;

type FGBuildableFrackingExtractor = docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_base_base_timed_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_base_base_base_piped_base & docs_json_ts_0_6_1_5_classes_base_FGBuildableResourceExtractor_base_version_specific_base & FGBuildable_powered;

type FGBuildableGenerator = FGBuildableGenerator_no_fuel & docs_json_ts_0_3_7_7_classes_base_FGBuildableGenerator_base_base_base & has_mFuelInventoryHandlerData;

type FGBuildableGenerator_no_fuel = docs_json_ts_0_3_7_7_classes_base_FGBuildableGenerator_no_fuel_base_base_base_base & FGBuildable_powered;

type FGBuildableGeneratorFuel_biomass = FGBuildableGenerator & docs_json_ts_0_4_2_11_classes_base_FGBuildableGeneratorFuel_base_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableGeneratorFuel_biomass_base_base;

type FGBuildableGeneratorFuel_coal = FGBuildableGenerator & docs_json_ts_0_4_2_11_classes_base_FGBuildableGeneratorFuel_base_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableGeneratorFuel_coal_base_base;

type FGBuildableGeneratorFuel_fuel = FGBuildableGenerator & docs_json_ts_0_4_2_11_classes_base_FGBuildableGeneratorFuel_base_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableGeneratorFuel_base_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableGeneratorFuel_fuel_base_base;

type FGBuildableGeneratorGeoThermal = FGBuildableGenerator_no_fuel & docs_json_ts_0_3_7_7_classes_base_FGBuildableGeneratorGeoThermal_base_base_base & docs_json_ts_0_4_2_11_classes_base_FGBuildableGeneratorGeoThermal_base;

type FGBuildableGeneratorNuclear = FGBuildableGenerator & docs_json_ts_0_4_2_11_classes_base_FGBuildableGeneratorFuel_base_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableGeneratorNuclear_base_base_base & docs_json_ts_0_4_2_11_classes_base_FGBuildableGeneratorNuclear_base & FGBuildable_has_mOutputInventoryHandlerData;

type FGBuildableJumppad = docs_json_ts_0_3_7_7_classes_base_FGBuildableJumppad_base_base_base & FGBuildable_powered & FGBuildableJumppad_version_specific;

type FGBuildableJumppad_version_specific = {
	mTrajectorySplineMeshNumPrimitiveDataFloats: docs_json_ts_common_types_integer_string,
	mTrajectorySplineMeshSplineDataSettings: {
		StartTangentPrimitiveDataStartIndex: docs_json_ts_common_types_integer_string,
		EndPositionPrimitiveDataStartIndex: docs_json_ts_common_types_integer_string,
		EndTangentPrimitiveDataStartIndex: docs_json_ts_common_types_integer_string,
		InstanceScaleIndex: docs_json_ts_common_types_integer_string_signed,
	},
};

type FGBuildableLadder = docs_json_ts_0_3_7_7_classes_base_FGBuildableLadder_base & FGBuildable_base;

type FGBuildableLightsControlPanel = docs_json_ts_0_4_2_11_classes_base_FGBuildableLightsControlPanel_base & docs_json_ts_0_4_2_11_classes_base_FGBuildable_light_related_thing_base & FGBuildable_base & docs_json_ts_0_5_2_1_classes_base_FGBuildableLightsControlPanel_version_specific & FGBuildable_has_mOnCircuitsChanged;

type FGBuildableLightSource = docs_json_ts_0_4_2_11_classes_base_FGBuildable_mHasPower_base & docs_json_ts_0_4_2_11_classes_base_FGBuildable_light_related_thing_base & docs_json_ts_0_4_2_11_classes_base_FGBuildableLightSource_base & docs_json_ts_0_5_2_1_classes_base_FGBuildableLightSource_base & FGBuildable_base;

type FGBuildableLightSource_Build_StreetLight_C = FGBuildableLightSource & docs_json_ts_0_5_2_1_classes_base_FGBuildableLightSource_Build_StreetLight_C_version_specific;

type FGBuildableMAM = FGBuildable_occupied & docs_json_ts_0_4_2_11_classes_base_FGBuildableMAM_version_specific & FGBuildable_base;

type FGBuildableManufacturer_Build_AssemblerMk1_C = docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_IsPowered_base_base & FGBuildable_powered & FGBuildableManufacturer_version_specific;

type FGBuildableManufacturer_Build_Blender_C = docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_base_base & docs_json_ts_0_4_2_11_classes_base_FGBuildableManufacturer_base_blender_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_IsPowered_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_mProductionEffectsRunning_base_base & FGBuildable_powered & FGBuildableManufacturer_version_specific;

type FGBuildableManufacturer_Build_ConstructorMk1_C = docs_json_ts_0_4_2_11_classes_base_FGBuildableManufacturer_base_constructor_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_IsPowered_base_base & FGBuildable_powered & docs_json_ts_0_5_2_1_classes_base_FGBuildableManufacturer_Build_ConstructorMk1_C_base & FGBuildableManufacturer_version_specific;

type FGBuildableManufacturer_Build_FoundryMk1_C = docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_mProductionEffectsRunning_base_base & FGBuildable_powered & docs_json_ts_0_5_2_1_classes_base_FGBuildableManufacturer_Build_FoundryMk1_C_base & FGBuildableManufacturer_version_specific;

type FGBuildableManufacturer_Build_HadronCollider_C = docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_IsPowered_base_base & FGBuildable_powered & docs_json_ts_0_4_2_11_classes_base_FGBuildableManufacturer_Build_HadronCollider_C_base & FGBuildableManufacturer_version_specific;

type FGBuildableManufacturer_Build_ManufacturerMk1_C = docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_base_base & docs_json_ts_0_4_2_11_classes_base_FGBuildable_mStopped_audio_stuff_base & FGBuildable_powered & FGBuildableManufacturer_version_specific;

type FGBuildableManufacturer_Build_OilRefinery_C = docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_IsPowered_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_mProductionEffectsRunning_base_base & FGBuildable_powered & FGBuildableManufacturer_version_specific;

type FGBuildableManufacturer_Build_Packager_C = docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_IsPowered_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_mProductionEffectsRunning_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_packager_base_base & FGBuildable_powered & FGBuildableManufacturer_version_specific;

type FGBuildableManufacturer_Build_SmelterMk1_C = docs_json_ts_0_6_1_5_classes_base_FGBuildableManufacturer_Build_SmelterMk1_C_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_mProductionEffectsRunning_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_base_base & FGBuildable_powered & FGBuildableManufacturer_version_specific;

type FGBuildableManufacturer_version_specific = FGBuildable_has_mInputInventoryHandlerData & FGBuildable_has_mOutputInventoryHandlerData;

type FGBuildablePassthrough = docs_json_ts_0_5_2_1_classes_base_FGBuildablePassthrough_base & FGBuildable_base & FGBuildablePassthrough_version_specific;

type FGBuildablePassthrough_version_specific = {
	mCostSegmentLength: docs_json_ts_common_types_decimal_string,
	mGeneratedMeshComponents: '',
};

type FGBuildablePillarLightweight = docs_json_ts_0_5_2_1_classes_base_FGBuildablePillar_base & FGBuildable_base;

type FGBuildablePipeHyper = docs_json_ts_0_5_2_1_classes_base_FGBuildable_mSnappedPassthroughs & docs_json_ts_0_3_7_7_classes_base_FGBuildable_spline & FGBuildable_base;

type FGBuildablePipeline = docs_json_ts_0_6_1_5_classes_base_FGBuildablePipeline_version_specific & docs_json_ts_0_3_7_7_classes_base_FGBuildablePipeline_base_root & docs_json_ts_0_3_7_7_classes_base_FGBuildablePipeline_base_spline_base & docs_json_ts_0_5_2_1_classes_base_FGBuildablePipeline_base_spline & FGBuildable_base;

type FGBuildablePipelineJunction = docs_json_ts_0_4_2_11_classes_base_FGBuildablePipelineJunction_base_base_base & FGBuildable_powered;

type FGBuildablePipelinePump_pump = docs_json_ts_0_3_7_7_classes_base_FGBuildablePipelinePump_pump_base_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildablePipelinePump_powered_base_base_base_base & FGBuildable_powered;

type FGBuildablePipelinePump_valve = docs_json_ts_0_3_7_7_classes_base_FGBuildablePipelinePump_base_base_base & FGBuildable_powered;

type FGBuildablePipelineSupport = docs_json_ts_0_3_7_7_classes_base_FGBuildablePipelineSupport_base & docs_json_ts_0_3_7_7_classes_base_FGBuildable_with_mLength & FGBuildable_base;

type FGBuildablePipeReservoir = FGBuildable_powered & docs_json_ts_0_3_7_7_classes_base_FGBuildablePipeReservoir_base_base_base;

type FGBuildablePole = docs_json_ts_0_7_1_1_classes_base_FGBuildablePole_version_specific & docs_json_ts_0_3_7_7_classes_base_FGBuildablePole_base & FGBuildable_base;

type FGBuildablePoleLightweight = docs_json_ts_0_7_1_1_classes_base_FGBuildablePole_version_specific & docs_json_ts_0_3_7_7_classes_base_FGBuildablePole_base & FGBuildable_base;

type FGBuildablePowerPole = docs_json_ts_0_5_2_1_classes_base_FGBuildable_mHasPower & FGBuildablePowerPole_version_specific & FGBuildable_base;

type FGBuildablePowerPole_version_specific = {
	mPowerConnections?: '',
	mPowerPoleType?: 'PPT_POLE' | 'PPT_WALL' | 'PPT_WALL_DOUBLE' | 'PPT_TOWER',
	mPowerTowerWireMaxLength: docs_json_ts_common_types_decimal_string,
};

type FGBuildablePowerStorage = FGBuildable_powered & docs_json_ts_0_4_2_11_classes_base_FGBuildablePowerStorage_base;

type FGBuildablePriorityPowerSwitch = FGBuildableCircuitSwitch & FGBuildablePriorityPowerSwitch_version_specific;

type FGBuildablePriorityPowerSwitch_version_specific = {
	mOnPriorityChanged: docs_json_ts_common_types_empty_object,
	mPriority: docs_json_ts_common_types_integer_string,
};

type FGBuildableRadarTower = FGBuildable_powered & docs_json_ts_0_6_1_5_classes_base_FGBuildableRadarTower_base;

type FGBuildableRailroadSignal_base = docs_json_ts_0_5_2_1_classes_base_FGBuildableRailroadSignal_base_version_specific & FGBuildable_base & FGBuildableRailroadSignal_version_specific;

type FGBuildableRailroadSignal_block = docs_json_ts_0_5_2_1_classes_base_FGBuildableRailroadSignal_block_version_specific & FGBuildableRailroadSignal_base;

type FGBuildableRailroadSignal_version_specific = {
	mDrawDebugVisualState: docs_json_ts_common_types_bool_string,
};

type FGBuildableRailroadStation = docs_json_ts_0_5_2_1_classes_base_FGBuildableRailroadStation_base & docs_json_ts_0_5_2_1_classes_base_FGBuildableTrainPlatform_base_version_specific & docs_json_ts_0_5_2_1_classes_base_FGBuildableTrainPlatform_non_empty_version_specific & docs_json_ts_0_3_7_7_classes_base_FGBuildableRailroadStation_version_specific & docs_json_ts_0_3_7_7_classes_base_FGBuildableTrainPlatform_base_base_base & FGBuildable_powered & FGBuildableTrainPlatform_version_specific;

type FGBuildableRailroadTrack = docs_json_ts_0_5_2_1_classes_base_FGBuildableRailroadTrack_base_version_specific & docs_json_ts_0_3_7_7_classes_base_FGBuildableRailroadTrack_base & FGBuildable_base & FGBuildableRailroadTrack_version_specific;

type FGBuildableRailroadTrack_version_specific = {
	mBlockVisualizationMeshLength: docs_json_ts_common_types_decimal_string,
	mBlockVisualizationNumPrimitiveDataFloats: docs_json_ts_common_types_integer_string,
	mBlockVisualizationNumPerInstancePrimitiveDataCountOffset: docs_json_ts_common_types_integer_string,
	mBlockVisualizationSplineDataSettings: {
		StartTangentPrimitiveDataStartIndex: docs_json_ts_common_types_integer_string,
		EndPositionPrimitiveDataStartIndex: docs_json_ts_common_types_integer_string,
		EndTangentPrimitiveDataStartIndex: docs_json_ts_common_types_integer_string,
		InstanceScaleIndex: docs_json_ts_common_types_integer_string_signed,
	},
	mBlockVisualizationColorDataStartIndex: docs_json_ts_common_types_integer_string,
	mConnections: [
		docs_json_ts_0_8_3_3_properties_FGRailroadTrackConnectionComponent_quoted,
		...docs_json_ts_0_8_3_3_properties_FGRailroadTrackConnectionComponent_quoted[],
	],
};

type FGBuildableRamp = FGBuildableFoundation & docs_json_ts_0_5_2_1_classes_base_FGBuildableRamp_base;

type FGBuildableResourceExtractor_base = docs_json_ts_0_6_1_5_classes_base_FGBuildableResourceExtractor_base_version_specific_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_base_base_base_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_base_base_base_piped_base & docs_json_ts_0_3_7_7_classes_base_FGBuildable_powered_base_resources_base_base & FGBuildable_powered;

type FGBuildableResourceExtractor_miner_mk1 = docs_json_ts_0_4_2_11_classes_base_FGBuildableResourceExtractor_miner_mk1_base_base_base & FGBuildableResourceExtractor_base;

type FGBuildableResourceExtractor_miner_mk2 = docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_miner_mk2_base_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_miner_base_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_base_base_timed_base & FGBuildableResourceExtractor_base;

type FGBuildableResourceExtractor_miner_mk3 = docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_miner_mk3_base_base_base & FGBuildableResourceExtractor_base;

type FGBuildableResourceExtractor_oil = docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_oil_base_base_base & FGBuildableResourceExtractor_base;

type FGBuildableResourceExtractor_water = docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_water_base_base_base & docs_json_ts_0_4_2_11_classes_base_FGBuildableResourceExtractor_water_base & FGBuildableResourceExtractor_base;

type FGBuildableResourceSink = FGBuildable_powered & docs_json_ts_0_4_2_11_classes_base_FGBuildableResourceSink_base_base & FGBuildableResourceSink_version_specific;

type FGBuildableResourceSink_version_specific = {
	mCouponInventoryHandler: docs_json_ts_common_types_empty_object,
};

type FGBuildableResourceSinkShop = FGBuildable_powered & docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceSinkShop_base_base_base;

type FGBuildableSplitterSmart = docs_json_ts_0_3_7_7_classes_base_FGBuildableAttachment_splitter_base_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableSplitterSmart_version_specific & FGBuildable_base;

type FGBuildableStair = docs_json_ts_0_3_7_7_classes_base_FGBuildable_with_size_base & docs_json_ts_0_3_7_7_classes_base_FGBuildable_with_height_base & FGBuildable_base & docs_json_ts_0_5_2_1_classes_base_FGBuildableStair_has_mStairDirection;

type FGBuildableStorage = docs_json_ts_0_3_7_7_classes_base_FGBuildableStorage_base_base_base & FGBuildable_powered;

type FGBuildableTradingPost = docs_json_ts_0_3_7_7_classes_base_FGBuildableTradingPost_base_base_base & docs_json_ts_0_5_2_1_classes_base_FGBuildableTradingPost_base & FGBuildableTradingPost_version_specific & FGBuildable_powered;

type FGBuildableTradingPost_version_specific = {
	Meshes: [
        '/Script/Engine.StaticMesh\'"/Game/FactoryGame/Buildable/Factory/TradingPost/Mesh/Tradingpost_Stage_1.Tradingpost_Stage_1"\'' | '/Script/Engine.StaticMesh\'"/Game/FactoryGame/Buildable/Factory/TradingPost/Mesh/Tradingpost_Stage_2.Tradingpost_Stage_2"\'' | '/Script/Engine.StaticMesh\'"/Game/FactoryGame/Buildable/Factory/TradingPost/Mesh/Tradingpost_Stage_3.Tradingpost_Stage_3"\'' | '/Script/Engine.StaticMesh\'"/Game/FactoryGame/Buildable/Factory/TradingPost/Mesh/Tradingpost_Stage_4.Tradingpost_Stage_4"\'' | '/Script/Engine.StaticMesh\'"/Game/FactoryGame/Buildable/Factory/TradingPost/Mesh/Tradingpost_Stage_5.Tradingpost_Stage_5"\'' | '/Script/Engine.StaticMesh\'"/Game/FactoryGame/Buildable/Factory/TradingPost/Mesh/Tradingpost_Stage_6.Tradingpost_Stage_6"\'',
        ...('/Script/Engine.StaticMesh\'"/Game/FactoryGame/Buildable/Factory/TradingPost/Mesh/Tradingpost_Stage_1.Tradingpost_Stage_1"\'' | '/Script/Engine.StaticMesh\'"/Game/FactoryGame/Buildable/Factory/TradingPost/Mesh/Tradingpost_Stage_2.Tradingpost_Stage_2"\'' | '/Script/Engine.StaticMesh\'"/Game/FactoryGame/Buildable/Factory/TradingPost/Mesh/Tradingpost_Stage_3.Tradingpost_Stage_3"\'' | '/Script/Engine.StaticMesh\'"/Game/FactoryGame/Buildable/Factory/TradingPost/Mesh/Tradingpost_Stage_4.Tradingpost_Stage_4"\'' | '/Script/Engine.StaticMesh\'"/Game/FactoryGame/Buildable/Factory/TradingPost/Mesh/Tradingpost_Stage_5.Tradingpost_Stage_5"\'' | '/Script/Engine.StaticMesh\'"/Game/FactoryGame/Buildable/Factory/TradingPost/Mesh/Tradingpost_Stage_6.Tradingpost_Stage_6"\'')[],
	],
};

type FGBuildableTrainPlatform_version_specific = {
	mPlatformConnections: [
		docs_json_ts_0_8_3_3_properties_FGTrainPlatformConnection_quoted,
		...docs_json_ts_0_8_3_3_properties_FGTrainPlatformConnection_quoted[],
	],
};

type FGBuildableTrainPlatformCargo = docs_json_ts_0_6_1_5_classes_base_FGBuildableTrainPlatformCargo_version_specific & docs_json_ts_0_5_2_1_classes_base_FGBuildableTrainPlatformCargo_version_specific & docs_json_ts_0_5_2_1_classes_base_FGBuildableTrainPlatform_base_version_specific & FGBuildable_powered & docs_json_ts_0_5_2_1_classes_base_FGBuildableTrainPlatform_non_empty_version_specific & docs_json_ts_0_3_7_7_classes_base_FGBuildableTrainPlatform_base_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableTrainPlatformCargo_pre_update8 & docs_json_ts_0_3_7_7_classes_base_FGBuildable_powered_storage_base_base_base & FGBuildableTrainPlatform_version_specific;

type FGBuildableTrainPlatformEmpty = docs_json_ts_0_5_2_1_classes_base_FGBuildableTrainPlatform_base_version_specific & docs_json_ts_0_3_7_7_classes_base_FGBuildableTrainPlatform_base_base_base & FGBuildable_powered & FGBuildableTrainPlatform_version_specific;

type FGBuildableWalkway = docs_json_ts_0_3_7_7_classes_base_FGBuildable_with_size_and_elevation_base & docs_json_ts_0_3_7_7_classes_base_FGBuildable_with_size_and_elevation_base_base & FGBuildable_base;

type FGBuildableWall = docs_json_ts_0_3_7_7_classes_base_FGBuildable_with_height_and_width_base & docs_json_ts_0_5_2_1_classes_base_FGBuildable_with_elevation & docs_json_ts_0_5_2_1_classes_base_FGBuildable_is_wallish & FGBuildable_base;

type FGBuildableWidgetSign = docs_json_ts_0_5_2_1_classes_base_FGBuildableWidgetSign_base & FGBuildable_base & FGBuildableWidgetSign_version_specific;

type FGBuildableWidgetSign_version_specific = {
	mSignDrawSize: docs_json_ts_common_types_XY_integer_string,
};

type FGBuildableWire = docs_json_ts_0_3_7_7_classes_base_FGBuildableWire_base & FGBuildable_base & FGBuildableWire_version_specific;

type FGBuildableWire_version_specific = {
	mMaxPowerTowerLength: docs_json_ts_common_types_decimal_string,
	mConnectionLocations: docs_json_ts_common_types_XYZ_decimal_string,
	mWireInstances: '',
	mCachedLength: docs_json_ts_common_types_decimal_string,
};

type FGChainsaw = docs_json_ts_0_3_7_7_classes_base_FGChainsaw_version_specific & docs_json_ts_0_6_1_5_classes_base_FGChainsaw_version_specific & FGChainsaw_version_specific & FGEquipment;

type FGChainsaw_version_specific = {
	mSawingMontageLength: docs_json_ts_common_types_decimal_string,
	mCurrentHasFuel: docs_json_ts_common_types_bool_string,
	mPreviousState: 'None',
	mSawingProgress: docs_json_ts_common_types_decimal_string,
	mChainsawState: 'None',
};

type FGConsumableEquipment = docs_json_ts_0_4_2_11_classes_base_FGConsumableEquipment_version_specific & docs_json_ts_0_3_7_7_classes_base_FGConsumableEquipment_version_specific_pre_update8 & FGEquipment & FGConsumableEquipment_version_specific;

type FGConsumableEquipment_version_specific = {
	mAnimData?: [
		{
			Montage_7_2E66F6A948A8606E71185682EA2AC4EC: docs_json_ts_0_3_7_7_properties_AnimMontage_quoted,
			CameraAnimationSequence_11_920C446448786C507704569A05006500: docs_json_ts_0_8_3_3_properties_CameraAnimationSequence_quoted,
		},
		...{
			Montage_7_2E66F6A948A8606E71185682EA2AC4EC: docs_json_ts_0_3_7_7_properties_AnimMontage_quoted,
			CameraAnimationSequence_11_920C446448786C507704569A05006500: docs_json_ts_0_8_3_3_properties_CameraAnimationSequence_quoted,
		}[],
	],
};

type FGEquipment = docs_json_ts_0_3_7_7_classes_base_FGEquipment_base_base_base & docs_json_ts_0_4_2_11_classes_base_FGEquipment_version_specific & docs_json_ts_0_6_1_5_classes_base_FGEquipment_version_specific & FGEquipment_version_specific;

type FGEquipment_dispenser = docs_json_ts_0_3_7_7_classes_base_FGEquipment_dispenser_version_specific & FGEquipment;

type FGEquipment_noisy = FGEquipment & docs_json_ts_0_6_1_5_classes_base_FGEquipment_noisy_version_specific;

type FGEquipment_version_specific = {
	mComponentNameToFirstPersonMaterials: docs_json_ts_common_types_empty_object | [
		docs_json_ts_0_8_3_3_properties_mComponentNameToFirstPersonMaterials_item,
		...docs_json_ts_0_8_3_3_properties_mComponentNameToFirstPersonMaterials_item[],
	],
	mNeedsDefaultEquipmentMappingContext: docs_json_ts_common_types_bool_string,
	mDefaultEquipmentActions: docs_json_ts_common_types_integer_string,
	mSwappedOutThirdPersonMaterials: docs_json_ts_common_types_empty_object,
};

type FGEquipmentStunSpear_base = FGEquipment & docs_json_ts_0_6_1_5_classes_base_FGEquipmentStunSpear_base_version_specific & docs_json_ts_0_3_7_7_classes_base_FGEquipmentStunSpear_base_version_specific & FGEquipmentStunSpear_base_version_specific;

type FGEquipmentStunSpear_base_version_specific = {
	mDamageTypes: docs_json_ts_0_8_3_3_properties_mDamageTypes,
};

type FGEquipmentStunSpear_xenobasher = docs_json_ts_0_3_7_7_classes_base_FGEquipmentStunSpear_xenobasher_version_specific & docs_json_ts_0_3_7_7_classes_base_FGEquipmentStunSpear_base_base_base & FGEquipmentStunSpear_base;

type FGEquipmentStunSpear_xenozapper = FGEquipmentStunSpear_base & FGEquipmentStunSpear_xenozapper_version_specific;

type FGEquipmentStunSpear_xenozapper_version_specific = {
	mPunchAnimationWeight: docs_json_ts_common_types_decimal_string,
};

type FGEquipmentZipline = docs_json_ts_0_4_2_11_classes_base_FGEquipmentZipline_base & FGEquipment_noisy;

type FGGasMask = docs_json_ts_0_3_7_7_classes_base_FGGasMask_base & docs_json_ts_0_3_7_7_classes_base_FGEquipment_filtered & FGEquipment & FGGasMask_version_specific;

type FGGasMask_version_specific = {
	mDamageTypesToProtectAgainst: docs_json_ts_0_8_3_3_properties_mDamageTypes,
	mFilterCountdown: docs_json_ts_common_types_decimal_string,
	mIsInPoisonGas: docs_json_ts_common_types_bool_string,
};

type FGGolfCartDispenser = docs_json_ts_0_5_2_1_classes_base_FGGolfCartDispenser_version_specific & docs_json_ts_0_3_7_7_classes_base_FGGolfCartDispenser_has_mArmAnimation & docs_json_ts_0_3_7_7_classes_base_FGEquipment_dispenser_version_specific & FGEquipment;

type FGHoverPack = docs_json_ts_0_4_2_11_classes_base_FGHoverPack_version_specific & FGEquipment_noisy;

type FGJetPack = docs_json_ts_0_3_7_7_classes_base_FGJetPack_version_specific & docs_json_ts_0_6_1_5_classes_base_FGEquipment_noisy_version_specific & docs_json_ts_0_7_1_1_classes_base_FGJetPack_version_specific & FGEquipment & FGJetPack_version_specific;

type FGJetPack_version_specific = {
	FuelTypeDescriptos: '',
	mOnFuelAmountChanged: docs_json_ts_common_types_empty_object,
	mOnBurnPercentChanged: docs_json_ts_common_types_empty_object,
	mOnFuelTypeChanged: docs_json_ts_common_types_empty_object,
};

type FGJumpingStilts = docs_json_ts_0_3_7_7_classes_base_FGJumpingStilts_base & FGEquipment & docs_json_ts_0_6_1_5_classes_base_FGJumpingStilts_version_specific;

type FGNobeliskDetonator = docs_json_ts_0_5_2_1_classes_base_FGNobeliskDetonator_base & docs_json_ts_0_4_2_11_classes_base_FGWeaponProjectile_has_mBlockSprintWhenFiring & docs_json_ts_0_3_7_7_classes_base_FGNobeliskDetonator_base & docs_json_ts_0_5_2_1_classes_base_FGWeapon_base_base & docs_json_ts_0_6_1_5_classes_base_FGWeapon_base & FGEquipment;

type FGObjectScanner = docs_json_ts_0_3_7_7_classes_base_FGObjectScanner_version_specific & docs_json_ts_0_3_7_7_classes_base_FGEquipment_has_mPlayingSound & FGObjectScanner_version_specific & FGEquipment;

type FGObjectScanner_version_specific = {
	mIsPlayingStaticSound: docs_json_ts_common_types_bool_string,
	mClosestObjectInScanRange: docs_json_ts_common_types_bool_string,
	mNormalizedDistanceToClosestObject: docs_json_ts_common_types_decimal_string,
	mAngleToClosestObject: docs_json_ts_common_types_decimal_string,
};

type FGParachute = docs_json_ts_0_3_7_7_classes_base_FGParachute_has_mIsDeployed & FGEquipment & FGParachute_version_specific;

type FGParachute_version_specific = {
	ArmEquipmentsToSkipAnim: [
		'AE_ChainSaw',
		'AE_PortableMiner',
		'AE_Generic2Hand',
		'AE_Nobelisk',
		'AE_Rifle',
	],
	DeployedVFXComponents: '',
	mUseDistanceOverride: docs_json_ts_common_types_decimal_string,
};

type FGPipeHyperStart = docs_json_ts_0_3_7_7_classes_base_FGPipeHyperStart_base_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildable_pole_with_length_and_power_base_base & FGBuildable_powered;

type FGPortableMinerDispenser = docs_json_ts_0_4_2_11_classes_base_FGPortableMinerDispenser_version_specific & docs_json_ts_0_3_7_7_classes_base_FGPortableMinerDispenser_version_specific & FGEquipment_dispenser;

type FGSchematic_base = docs_json_ts_0_4_2_11_classes_base_FGSchematic_base_base_props_sans_mSchematicIcon_mMenuPriority & docs_json_ts_0_5_2_1_classes_base_FGSchematic_base_base_base & FGSchematic_base_base_props_with_mSchematicIcon & docs_json_ts_0_6_1_5_classes_base_FGSchematic_version_specific_base & FGSchematic_version_specific;

type FGSchematic_base_base_props_with_mSchematicIcon = {
	mSchematicIcon: {
		DrawAs: 'Image',
		ImageSize: docs_json_ts_common_types_XY_decimal_string,
		Margin: docs_json_ts_common_types_empty_object,
		TintColor: docs_json_ts_0_4_2_11_properties_TintColor,
		OutlineSettings: {
			CornerRadii: docs_json_ts_common_types_XYZW_decimal_string,
			Color: docs_json_ts_0_4_2_11_properties_TintColor,
			RoundingType: 'HalfHeightRadius',
		},
		ResourceObject?: docs_json_ts_0_4_2_11_properties_Texture2D_quoted,
		UVRegion: {
			Min: docs_json_ts_common_types_XY_decimal_string,
			Max: docs_json_ts_common_types_XY_decimal_string,
			bIsValid: docs_json_ts_common_types_bool_string,
		},
	},
};

type FGSchematic_version_specific = {
	mIsPlayerSpecific: docs_json_ts_common_types_bool_string,
	mMenuPriority: docs_json_ts_common_types_decimal_string_signed,
	mUnlocks: [
		...docs_json_ts_0_8_3_3_properties_mUnlocks_item[],
	],
};

type FGSchematic_with_described_unlocks = docs_json_ts_0_5_2_1_classes_base_FGSchematic_with_described_unlocks_base_base & FGSchematic_base;

type FGSuitBase = docs_json_ts_0_6_1_5_classes_base_FGSuitBase_version_specific & docs_json_ts_0_3_7_7_classes_base_FGSuitBase_base & docs_json_ts_0_3_7_7_classes_base_FGEquipment_filtered & docs_json_ts_0_3_7_7_classes_base_FGEquipment_has_effect_timer & docs_json_ts_0_3_7_7_classes_base_FGEquipment_negates_damage & FGEquipment;

type FGWeapon_Equip_RebarGun_Projectile_C = docs_json_ts_0_3_7_7_classes_base_FGWeaponProjectile_has_mAttachSocket & docs_json_ts_0_3_7_7_classes_base_FGWeaponProjectileFire_has_mRandomReloadAnim & docs_json_ts_0_3_7_7_classes_base_FGEquipment_has_mRandomStingerAnim & docs_json_ts_0_4_2_11_classes_base_FGWeaponProjectile_has_mBlockSprintWhenFiring & docs_json_ts_0_3_7_7_classes_base_FGEquipment_has_mEquipmentSlot & docs_json_ts_0_4_2_11_classes_base_FGWeaponProjectileFire_has_mMuteDryFire & docs_json_ts_0_5_2_1_classes_base_FGWeapon_base_base & docs_json_ts_0_6_1_5_classes_base_FGWeapon_base & FGEquipment & docs_json_ts_0_6_1_5_classes_base_FGWeapon_Equip_RebarGun_Projectile_C_version_specific;

type FGWeapon_Equip_Rifle_C = docs_json_ts_0_3_7_7_classes_base_FGWeaponProjectile_has_mAttachSocket & docs_json_ts_0_3_7_7_classes_base_FGWeaponInstantFire_base_base_base & docs_json_ts_0_4_2_11_classes_base_FGWeaponProjectile_has_mBlockSprintWhenFiring & docs_json_ts_0_3_7_7_classes_base_FGEquipment_has_mEquipmentSlot & docs_json_ts_0_5_2_1_classes_base_FGWeapon_Equip_Rifle_C_base & docs_json_ts_0_5_2_1_classes_base_FGWeapon_base_base & docs_json_ts_0_6_1_5_classes_base_FGWeapon_base & FGEquipment;

export type {
	has_mFuelInventoryHandlerData,
	has_mInventoryHandlerData,
	FGAmmoType_version_specific,
	FGAmmoTypeInstantHit_Desc_CartridgeChaos_C,
	FGAmmoTypeInstantHit_Desc_CartridgeStandard_C,
	FGAmmoTypeProjectile,
	FGAmmoTypeProjectile_version_specific,
	FGAmmoTypeSpreadshot,
	FGBuildable_base,
	FGBuildable_has_mInputInventoryHandlerData,
	FGBuildable_has_mOnCircuitsChanged,
	FGBuildable_has_mOutputInventoryHandlerData,
	FGBuildable_occupied,
	FGBuildable_powered,
	FGBuildable_powered_base,
	FGBuildable_tiered,
	FGBuildable_version_specific,
	FGBuildable_with_mInventoryPotentialHandlerData,
	FGBuildableAttachmentMerger,
	FGBuildableAttachmentSplitter,
	FGBuildableBeamLightweight,
	FGBuildableBlueprintDesigner,
	FGBuildableBlueprintDesigner_version_specific,
	FGBuildableCircuitSwitch,
	FGBuildableConveyorBelt,
	FGBuildableConveyorBelt_version_specific,
	FGBuildableConveyorLift,
	FGBuildableCornerWall,
	FGBuildableDockingStation,
	FGBuildableDoor,
	FGBuildableDoor_automated,
	FGBuildableDoor_manual,
	FGBuildableDroneStation,
	FGBuildableDroneStation_version_specific,
	FGBuildableFactory_jump_pad,
	FGBuildableFactory_landing_pad,
	FGBuildableFactorySimpleProducer,
	FGBuildableFloodlight,
	FGBuildableFoundation,
	FGBuildableFrackingActivator,
	FGBuildableFrackingExtractor,
	FGBuildableGenerator,
	FGBuildableGenerator_no_fuel,
	FGBuildableGeneratorFuel_biomass,
	FGBuildableGeneratorFuel_coal,
	FGBuildableGeneratorFuel_fuel,
	FGBuildableGeneratorGeoThermal,
	FGBuildableGeneratorNuclear,
	FGBuildableJumppad,
	FGBuildableJumppad_version_specific,
	FGBuildableLadder,
	FGBuildableLightsControlPanel,
	FGBuildableLightSource,
	FGBuildableLightSource_Build_StreetLight_C,
	FGBuildableMAM,
	FGBuildableManufacturer_Build_AssemblerMk1_C,
	FGBuildableManufacturer_Build_Blender_C,
	FGBuildableManufacturer_Build_ConstructorMk1_C,
	FGBuildableManufacturer_Build_FoundryMk1_C,
	FGBuildableManufacturer_Build_HadronCollider_C,
	FGBuildableManufacturer_Build_ManufacturerMk1_C,
	FGBuildableManufacturer_Build_OilRefinery_C,
	FGBuildableManufacturer_Build_Packager_C,
	FGBuildableManufacturer_Build_SmelterMk1_C,
	FGBuildableManufacturer_version_specific,
	FGBuildablePassthrough,
	FGBuildablePassthrough_version_specific,
	FGBuildablePillarLightweight,
	FGBuildablePipeHyper,
	FGBuildablePipeline,
	FGBuildablePipelineJunction,
	FGBuildablePipelinePump_pump,
	FGBuildablePipelinePump_valve,
	FGBuildablePipelineSupport,
	FGBuildablePipeReservoir,
	FGBuildablePole,
	FGBuildablePoleLightweight,
	FGBuildablePowerPole,
	FGBuildablePowerPole_version_specific,
	FGBuildablePowerStorage,
	FGBuildablePriorityPowerSwitch,
	FGBuildablePriorityPowerSwitch_version_specific,
	FGBuildableRadarTower,
	FGBuildableRailroadSignal_base,
	FGBuildableRailroadSignal_block,
	FGBuildableRailroadSignal_version_specific,
	FGBuildableRailroadStation,
	FGBuildableRailroadTrack,
	FGBuildableRailroadTrack_version_specific,
	FGBuildableRamp,
	FGBuildableResourceExtractor_base,
	FGBuildableResourceExtractor_miner_mk1,
	FGBuildableResourceExtractor_miner_mk2,
	FGBuildableResourceExtractor_miner_mk3,
	FGBuildableResourceExtractor_oil,
	FGBuildableResourceExtractor_water,
	FGBuildableResourceSink,
	FGBuildableResourceSink_version_specific,
	FGBuildableResourceSinkShop,
	FGBuildableSplitterSmart,
	FGBuildableStair,
	FGBuildableStorage,
	FGBuildableTradingPost,
	FGBuildableTradingPost_version_specific,
	FGBuildableTrainPlatform_version_specific,
	FGBuildableTrainPlatformCargo,
	FGBuildableTrainPlatformEmpty,
	FGBuildableWalkway,
	FGBuildableWall,
	FGBuildableWidgetSign,
	FGBuildableWidgetSign_version_specific,
	FGBuildableWire,
	FGBuildableWire_version_specific,
	FGChainsaw,
	FGChainsaw_version_specific,
	FGConsumableEquipment,
	FGConsumableEquipment_version_specific,
	FGEquipment,
	FGEquipment_dispenser,
	FGEquipment_noisy,
	FGEquipment_version_specific,
	FGEquipmentStunSpear_base,
	FGEquipmentStunSpear_base_version_specific,
	FGEquipmentStunSpear_xenobasher,
	FGEquipmentStunSpear_xenozapper,
	FGEquipmentStunSpear_xenozapper_version_specific,
	FGEquipmentZipline,
	FGGasMask,
	FGGasMask_version_specific,
	FGGolfCartDispenser,
	FGHoverPack,
	FGJetPack,
	FGJetPack_version_specific,
	FGJumpingStilts,
	FGNobeliskDetonator,
	FGObjectScanner,
	FGObjectScanner_version_specific,
	FGParachute,
	FGParachute_version_specific,
	FGPipeHyperStart,
	FGPortableMinerDispenser,
	FGSchematic_base,
	FGSchematic_base_base_props_with_mSchematicIcon,
	FGSchematic_version_specific,
	FGSchematic_with_described_unlocks,
	FGSuitBase,
	FGWeapon_Equip_RebarGun_Projectile_C,
	FGWeapon_Equip_Rifle_C,
};
