/* eslint-disable @stylistic/max-len */

import type {
	FGBuildable_base as docs_json_ts_0_4_2_11_classes_base_FGBuildable_base,
	FGBuildable_docking_station_base as docs_json_ts_0_4_2_11_classes_base_FGBuildable_docking_station_base,
	FGBuildable_has_mCachedSkeletalMeshes as docs_json_ts_0_4_2_11_classes_base_FGBuildable_has_mCachedSkeletalMeshes,
	FGBuildable_light_related_thing_base as docs_json_ts_0_4_2_11_classes_base_FGBuildable_light_related_thing_base,
	FGBuildable_mHasPower_base as docs_json_ts_0_4_2_11_classes_base_FGBuildable_mHasPower_base,
	FGBuildable_mStopped_audio_stuff_base as docs_json_ts_0_4_2_11_classes_base_FGBuildable_mStopped_audio_stuff_base,
	FGBuildable_powered_has_mAllowedResourceForms_base as docs_json_ts_0_4_2_11_classes_base_FGBuildable_powered_has_mAllowedResourceForms_base,
	FGBuildable_powered_has_mAllowedResourceForms_with_resources_base as docs_json_ts_0_4_2_11_classes_base_FGBuildable_powered_has_mAllowedResourceForms_with_resources_base,
	FGBuildable_powered_storage_base as docs_json_ts_0_4_2_11_classes_base_FGBuildable_powered_storage_base,
	FGBuildable_with_height_and_width_base as docs_json_ts_0_4_2_11_classes_base_FGBuildable_with_height_and_width_base,
	FGBuildableCircuitSwitch_base as docs_json_ts_0_4_2_11_classes_base_FGBuildableCircuitSwitch_base,
	FGBuildableDroneStation_base as docs_json_ts_0_4_2_11_classes_base_FGBuildableDroneStation_base,
	FGBuildableFloodlight_base as docs_json_ts_0_4_2_11_classes_base_FGBuildableFloodlight_base,
	FGBuildableFrackingActivator_base as docs_json_ts_0_4_2_11_classes_base_FGBuildableFrackingActivator_base,
	FGBuildableGeneratorFuel_base_base as docs_json_ts_0_4_2_11_classes_base_FGBuildableGeneratorFuel_base_base,
	FGBuildableGeneratorGeoThermal_base as docs_json_ts_0_4_2_11_classes_base_FGBuildableGeneratorGeoThermal_base,
	FGBuildableGeneratorNuclear_base as docs_json_ts_0_4_2_11_classes_base_FGBuildableGeneratorNuclear_base,
	FGBuildableLightsControlPanel_base as docs_json_ts_0_4_2_11_classes_base_FGBuildableLightsControlPanel_base,
	FGBuildableLightSource_base as docs_json_ts_0_4_2_11_classes_base_FGBuildableLightSource_base,
	FGBuildableMAM_version_specific as docs_json_ts_0_4_2_11_classes_base_FGBuildableMAM_version_specific,
	FGBuildableManufacturer_base_blender_base as docs_json_ts_0_4_2_11_classes_base_FGBuildableManufacturer_base_blender_base,
	FGBuildableManufacturer_base_constructor_base as docs_json_ts_0_4_2_11_classes_base_FGBuildableManufacturer_base_constructor_base,
	FGBuildableManufacturer_Build_HadronCollider_C_base as docs_json_ts_0_4_2_11_classes_base_FGBuildableManufacturer_Build_HadronCollider_C_base,
	FGBuildablePipelineJunction_base_base as docs_json_ts_0_4_2_11_classes_base_FGBuildablePipelineJunction_base_base,
	FGBuildablePowerStorage_base as docs_json_ts_0_4_2_11_classes_base_FGBuildablePowerStorage_base,
	FGBuildableRailroadTrack_base_base as docs_json_ts_0_4_2_11_classes_base_FGBuildableRailroadTrack_base_base,
	FGBuildableResourceExtractor_miner_mk1_base_base as docs_json_ts_0_4_2_11_classes_base_FGBuildableResourceExtractor_miner_mk1_base_base,
	FGBuildableResourceExtractor_water_base as docs_json_ts_0_4_2_11_classes_base_FGBuildableResourceExtractor_water_base,
	FGBuildableResourceSink_base as docs_json_ts_0_4_2_11_classes_base_FGBuildableResourceSink_base,
	FGBuildableTradingPost_base as docs_json_ts_0_4_2_11_classes_base_FGBuildableTradingPost_base,
	FGDescriptor_base as docs_json_ts_0_4_2_11_classes_base_FGDescriptor_base,
	FGDescriptor_BuildMenu_base as docs_json_ts_0_4_2_11_classes_base_FGDescriptor_BuildMenu_base,
	FGDescriptor_sinkable as docs_json_ts_0_4_2_11_classes_base_FGDescriptor_sinkable,
	FGDescriptor_sinkable_base as docs_json_ts_0_4_2_11_classes_base_FGDescriptor_sinkable_base,
	FGVehicleDescriptor_fueled_with_inventory as docs_json_ts_0_4_2_11_classes_base_FGVehicleDescriptor_fueled_with_inventory,
	FGVehicleDescriptor_powered as docs_json_ts_0_4_2_11_classes_base_FGVehicleDescriptor_powered,
	FGVehicleDescriptor_with_inventory as docs_json_ts_0_4_2_11_classes_base_FGVehicleDescriptor_with_inventory,
	FGWeaponProjectile_base as docs_json_ts_0_4_2_11_classes_base_FGWeaponProjectile_base,
	FGWeaponProjectileFire_has_mMuteDryFire as docs_json_ts_0_4_2_11_classes_base_FGWeaponProjectileFire_has_mMuteDryFire,
} from './../../0.4.2.11/classes/Base.ts';

import type {
	bool_string as docs_json_ts_common_types_bool_string,
	decimal_string as docs_json_ts_common_types_decimal_string,
	decimal_string_signed as docs_json_ts_common_types_decimal_string_signed,
	empty_object as docs_json_ts_common_types_empty_object,
	integer_string as docs_json_ts_common_types_integer_string,
	integer_string_signed as docs_json_ts_common_types_integer_string_signed,
	PitchYawRoll_decimal_string_signed as docs_json_ts_common_types_PitchYawRoll_decimal_string_signed,
	RGBA as docs_json_ts_common_types_RGBA,
	XY_decimal_string as docs_json_ts_common_types_XY_decimal_string,
	XYZ_decimal_string as docs_json_ts_common_types_XYZ_decimal_string,
} from './../../common/types.ts';

import type {
	FalloffCurve_EditorCurveData_only as docs_json_ts_0_5_2_1_properties_FalloffCurve_EditorCurveData_only,
	FGBuildableManufacturer_Build_ConstructorMk1_C_CurrentPotentialConvert_item as docs_json_ts_0_5_2_1_properties_FGBuildableManufacturer_Build_ConstructorMk1_C_CurrentPotentialConvert_item,
	mDisableSnapOn_bottom as docs_json_ts_0_5_2_1_properties_mDisableSnapOn_bottom,
	mDisableSnapOn_top as docs_json_ts_0_5_2_1_properties_mDisableSnapOn_top,
	mDockingRuleSet as docs_json_ts_0_5_2_1_properties_mDockingRuleSet,
} from './../types/properties.ts';

import type {
	Class_quoted as docs_json_ts_0_3_7_7_properties_Class_quoted,
	mDisableSnapOn_front_bottom as docs_json_ts_0_3_7_7_properties_mDisableSnapOn_front_bottom,
	mDisableSnapOn_top_bottom as docs_json_ts_0_3_7_7_properties_mDisableSnapOn_top_bottom,
	transform_Rotation_Translation_Scale3D as docs_json_ts_0_3_7_7_properties_transform_Rotation_Translation_Scale3D,
} from './../../0.3.7.7/types/properties.ts';

import type {
	FGBuildable_docking_station_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildable_docking_station_base_base_base,
	FGBuildable_occupied_base as docs_json_ts_0_3_7_7_classes_base_FGBuildable_occupied_base,
	FGBuildable_pole_with_length_and_power_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildable_pole_with_length_and_power_base_base,
	FGBuildable_powered_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildable_powered_base_base,
	FGBuildable_powered_base_resources_base as docs_json_ts_0_3_7_7_classes_base_FGBuildable_powered_base_resources_base,
	FGBuildable_spline as docs_json_ts_0_3_7_7_classes_base_FGBuildable_spline,
	FGBuildable_tiered_base as docs_json_ts_0_3_7_7_classes_base_FGBuildable_tiered_base,
	FGBuildable_with_height_base as docs_json_ts_0_3_7_7_classes_base_FGBuildable_with_height_base,
	FGBuildable_with_mLength as docs_json_ts_0_3_7_7_classes_base_FGBuildable_with_mLength,
	FGBuildable_with_size_and_elevation_base as docs_json_ts_0_3_7_7_classes_base_FGBuildable_with_size_and_elevation_base,
	FGBuildable_with_size_and_elevation_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildable_with_size_and_elevation_base_base,
	FGBuildable_with_size_base as docs_json_ts_0_3_7_7_classes_base_FGBuildable_with_size_base,
	FGBuildableAttachment_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableAttachment_base_base,
	FGBuildableAttachment_splitter_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableAttachment_splitter_base_base_base,
	FGBuildableAttachmentMerger_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableAttachmentMerger_base_base,
	FGBuildableConveyorBelt_spline_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableConveyorBelt_spline_base,
	FGBuildableConveyorLift_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableConveyorLift_base,
	FGBuildableDockingStation_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableDockingStation_base_base,
	FGBuildableFactory_jump_pad_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableFactory_jump_pad_base_base,
	FGBuildableFactory_landing_pad_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableFactory_landing_pad_base_base,
	FGBuildableFactorySimpleProducer_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableFactorySimpleProducer_base_base,
	FGBuildableGenerator_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableGenerator_base_base,
	FGBuildableGenerator_no_fuel_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableGenerator_no_fuel_base_base,
	FGBuildableGeneratorFuel_biomass_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableGeneratorFuel_biomass_base_base,
	FGBuildableGeneratorFuel_coal_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableGeneratorFuel_coal_base_base,
	FGBuildableGeneratorFuel_fuel_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableGeneratorFuel_fuel_base_base,
	FGBuildableGeneratorGeoThermal_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableGeneratorGeoThermal_base_base,
	FGBuildableGeneratorNuclear_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableGeneratorNuclear_base_base,
	FGBuildableJumppad_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableJumppad_base_base,
	FGBuildableLadder_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableLadder_base,
	FGBuildableManufacturer_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_base,
	FGBuildableManufacturer_base_IsPowered_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_IsPowered_base,
	FGBuildableManufacturer_base_mProductionEffectsRunning_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_mProductionEffectsRunning_base,
	FGBuildableManufacturer_base_packager_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_packager_base,
	FGBuildableManufacturer_Build_SmelterMk1_C_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_Build_SmelterMk1_C_base,
	FGBuildablePipeline_base_root_quantized as docs_json_ts_0_3_7_7_classes_base_FGBuildablePipeline_base_root_quantized,
	FGBuildablePipeline_base_spline_base as docs_json_ts_0_3_7_7_classes_base_FGBuildablePipeline_base_spline_base,
	FGBuildablePipelinePump_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildablePipelinePump_base_base,
	FGBuildablePipelinePump_powered_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildablePipelinePump_powered_base_base_base,
	FGBuildablePipelinePump_pump_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildablePipelinePump_pump_base_base,
	FGBuildablePipelineSupport_base as docs_json_ts_0_3_7_7_classes_base_FGBuildablePipelineSupport_base,
	FGBuildablePipeReservoir_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildablePipeReservoir_base_base,
	FGBuildablePole_base as docs_json_ts_0_3_7_7_classes_base_FGBuildablePole_base,
	FGBuildablePowerPole_base as docs_json_ts_0_3_7_7_classes_base_FGBuildablePowerPole_base,
	FGBuildableRadarTower_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableRadarTower_base_base,
	FGBuildableRailroadStation_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableRailroadStation_base_base,
	FGBuildableResourceExtractor_miner_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_miner_base,
	FGBuildableResourceExtractor_miner_mk2_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_miner_mk2_base_base,
	FGBuildableResourceExtractor_miner_mk3_version_specific as docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_miner_mk3_version_specific,
	FGBuildableResourceExtractor_oil_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_oil_base_base,
	FGBuildableResourceExtractor_piped as docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_piped,
	FGBuildableResourceExtractor_timed as docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_timed,
	FGBuildableResourceExtractor_water_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_water_base_base,
	FGBuildableResourceSinkShop_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceSinkShop_base_base,
	FGBuildableSplitterSmart_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableSplitterSmart_base_base,
	FGBuildableStorage_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableStorage_base_base,
	FGBuildableTradingPost_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableTradingPost_base,
	FGBuildableTrainPlatform_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableTrainPlatform_base_base,
	FGBuildableTrainPlatform_with_storage_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableTrainPlatform_with_storage_base_base_base,
	FGBuildableTrainPlatformCargo_pre_update8 as docs_json_ts_0_3_7_7_classes_base_FGBuildableTrainPlatformCargo_pre_update8,
	FGBuildableTrainPlatformCargo_version_specific as docs_json_ts_0_3_7_7_classes_base_FGBuildableTrainPlatformCargo_version_specific,
	FGBuildableWire_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableWire_base,
	FGColorGun_base_base as docs_json_ts_0_3_7_7_classes_base_FGColorGun_base_base,
	FGConsumableDescriptor_base as docs_json_ts_0_3_7_7_classes_base_FGConsumableDescriptor_base,
	FGDescriptor_sinkable_base as docs_json_ts_0_3_7_7_classes_base_FGDescriptor_sinkable_base,
	FGEquipment_base as docs_json_ts_0_3_7_7_classes_base_FGEquipment_base,
	FGGolfCartDispenser as docs_json_ts_0_3_7_7_classes_base_FGGolfCartDispenser,
	FGNobeliskDetonator_base as docs_json_ts_0_3_7_7_classes_base_FGNobeliskDetonator_base,
	FGPipeHyperStart_base_base as docs_json_ts_0_3_7_7_classes_base_FGPipeHyperStart_base_base,
	FGResourceDescriptor_base as docs_json_ts_0_3_7_7_classes_base_FGResourceDescriptor_base,
	FGSchematic_pre_1_0 as docs_json_ts_0_3_7_7_classes_base_FGSchematic_pre_1_0,
	FGWeaponInstantFire_base as docs_json_ts_0_3_7_7_classes_base_FGWeaponInstantFire_base,
	FGWeaponProjectile_base as docs_json_ts_0_3_7_7_classes_base_FGWeaponProjectile_base,
	FGWeaponProjectile_has_mAttachSocket as docs_json_ts_0_3_7_7_classes_base_FGWeaponProjectile_has_mAttachSocket,
	FGWeaponProjectileFire_base_random as docs_json_ts_0_3_7_7_classes_base_FGWeaponProjectileFire_base_random,
	instructive as docs_json_ts_0_3_7_7_classes_base_instructive,
	isDescribed as docs_json_ts_0_3_7_7_classes_base_isDescribed,
} from './../../0.3.7.7/classes/Base.ts';

import type {
	has_mBatteryClasses as docs_json_ts_0_4_2_11_overridable_has_mBatteryClasses,
} from './../../0.4.2.11/types/overridable.ts';

import type {
	FGBuildableResourceExtractor_miner_base as docs_json_ts_0_3_7_7_classes_base_overridable_FGBuildableResourceExtractor_miner_base,
	FGBuildableResourceExtractor_only_allow_certain_resources as docs_json_ts_0_3_7_7_classes_base_overridable_FGBuildableResourceExtractor_only_allow_certain_resources,
	FGSchematic_version_specific as docs_json_ts_0_3_7_7_classes_base_overridable_FGSchematic_version_specific,
} from './../../0.3.7.7/classes/Base.overridable.ts';

import type {
	FGBuildable_is_wallish as docs_json_ts_0_5_2_1_classes_base_overridable_FGBuildable_is_wallish,
	FGSchematic_version_specific as docs_json_ts_0_5_2_1_classes_base_overridable_FGSchematic_version_specific,
	FGWeapon_version_specific as docs_json_ts_0_5_2_1_classes_base_overridable_FGWeapon_version_specific,
} from './Base.overridable.ts';

import type {
	Texture2D as docs_json_ts_0_4_2_11_properties_Texture2D,
} from './../../0.4.2.11/types/properties.ts';

import type {
	FalloffCurve_EditorCurveData_with_ExternalCurve as docs_json_ts_0_5_2_1_overridable_FalloffCurve_EditorCurveData_with_ExternalCurve,
	mUnlocks_item as docs_json_ts_0_5_2_1_overridable_mUnlocks_item,
} from './../types/overridable.ts';

import type {
	BlueprintGeneratedClass_quoted as docs_json_ts_0_3_7_7_overridable_BlueprintGeneratedClass_quoted,
} from './../../0.3.7.7/types/overridable.ts';

import type {
	FGSchematic_base as docs_json_ts_0_4_2_11_classes_base_overridable_FGSchematic_base,
	FGSchematic_has_mSchematicIcon as docs_json_ts_0_4_2_11_classes_base_overridable_FGSchematic_has_mSchematicIcon,
} from './../../0.4.2.11/classes/Base.overridable.ts';

type FGBuildable_base = docs_json_ts_0_4_2_11_classes_base_FGBuildable_base & FGBuildable_base_version_specific;

type FGBuildable_base_version_specific = {
	mAllowColoring: docs_json_ts_common_types_bool_string,
	mShouldShowAttachmentPointVisuals: docs_json_ts_common_types_bool_string,
	mCreateClearanceMeshRepresentation: docs_json_ts_common_types_bool_string,
	mAttachmentPoints: '',
};

type FGBuildable_docking_station = docs_json_ts_0_4_2_11_classes_base_FGBuildable_docking_station_base & FGBuildable_powered_storage;

type FGBuildable_foundation_DisableAttachmentSnapOn = FGBuildable_base & {
	mDisableAttachmentSnapOn: docs_json_ts_common_types_empty_object | docs_json_ts_0_5_2_1_properties_mDisableSnapOn_top | docs_json_ts_0_5_2_1_properties_mDisableSnapOn_bottom,
};

type FGBuildable_foundation_mDisableSnapOn = FGBuildable_base & {
	mDisableSnapOn: docs_json_ts_common_types_empty_object | docs_json_ts_0_3_7_7_properties_mDisableSnapOn_front_bottom | docs_json_ts_0_5_2_1_properties_mDisableSnapOn_top | docs_json_ts_0_5_2_1_properties_mDisableSnapOn_bottom,
};

type FGBuildable_isFrame = {
	mIsFrame: docs_json_ts_common_types_bool_string,
};

type FGBuildable_mHasPower = docs_json_ts_0_4_2_11_classes_base_FGBuildable_mHasPower_base & FGBuildable_base_version_specific;

type FGBuildable_mSnappedPassthroughs = FGBuildable_base_version_specific & {
	mSnappedPassthroughs: '',
};

type FGBuildable_occupied = docs_json_ts_0_3_7_7_classes_base_FGBuildable_occupied_base & FGBuildable_base;

type FGBuildable_pole_with_length_and_power = docs_json_ts_0_3_7_7_classes_base_FGBuildable_pole_with_length_and_power_base_base & FGBuildable_powered;

type FGBuildable_powered = docs_json_ts_0_3_7_7_classes_base_FGBuildable_powered_base_base & FGBuildable_base & FGBuildable_powered_base;

type FGBuildable_powered_base = docs_json_ts_0_4_2_11_classes_base_FGBuildable_has_mCachedSkeletalMeshes & FGBuildable_powered_base_base;

type FGBuildable_powered_base_base = {
	mDoesHaveShutdownAnimation: docs_json_ts_common_types_bool_string,
};

type FGBuildable_powered_storage = docs_json_ts_0_4_2_11_classes_base_FGBuildable_powered_storage_base & FGBuildable_powered;

type FGBuildable_ramp_DisableAttachmentSnapOn = FGBuildable_base & {
	mDisableAttachmentSnapOn: docs_json_ts_common_types_empty_object | docs_json_ts_0_3_7_7_properties_mDisableSnapOn_top_bottom | docs_json_ts_0_5_2_1_properties_mDisableSnapOn_top | docs_json_ts_0_5_2_1_properties_mDisableSnapOn_bottom,
};

type FGBuildable_ramp_mDisableSnapOn = FGBuildable_base & {
	mDisableSnapOn: docs_json_ts_0_3_7_7_properties_mDisableSnapOn_top_bottom | docs_json_ts_0_3_7_7_properties_mDisableSnapOn_front_bottom | docs_json_ts_0_5_2_1_properties_mDisableSnapOn_top | docs_json_ts_0_5_2_1_properties_mDisableSnapOn_bottom,
};

type FGBuildable_spline = docs_json_ts_0_3_7_7_classes_base_FGBuildable_spline & FGBuildable_base & FGBuildable_mSnappedPassthroughs;

type FGBuildable_tiered = docs_json_ts_0_3_7_7_classes_base_FGBuildable_tiered_base & FGBuildable_base;

type FGBuildable_with_elevation = {
	mElevation: docs_json_ts_common_types_decimal_string,
};

type FGBuildable_with_height = docs_json_ts_0_3_7_7_classes_base_FGBuildable_with_height_base & FGBuildable_base;

type FGBuildable_with_height_and_width = docs_json_ts_0_4_2_11_classes_base_FGBuildable_with_height_and_width_base & FGBuildable_base;

type FGBuildable_with_size_and_elevation = docs_json_ts_0_3_7_7_classes_base_FGBuildable_with_size_and_elevation_base & FGBuildable_with_size_and_elevation_base;

type FGBuildable_with_size_and_elevation_base = docs_json_ts_0_3_7_7_classes_base_FGBuildable_with_size_and_elevation_base_base & FGBuildable_base;

type FGBuildableAttachment = docs_json_ts_0_3_7_7_classes_base_FGBuildableAttachment_base_base & FGBuildable_powered;

type FGBuildableAttachment_splitter = docs_json_ts_0_3_7_7_classes_base_FGBuildableAttachment_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableAttachment_splitter_base_base_base & FGBuildableAttachment;

type FGBuildableAttachmentMerger = docs_json_ts_0_3_7_7_classes_base_FGBuildableAttachmentMerger_base_base & FGBuildableAttachment;

type FGBuildableBeam = FGBuildable_base & FGBuildableBeam_base;

type FGBuildableBeam_base = docs_json_ts_0_3_7_7_classes_base_FGBuildable_with_size_base & {
	mDefaultLength: docs_json_ts_common_types_decimal_string,
	mMaxLength: docs_json_ts_common_types_decimal_string,
	mLength: docs_json_ts_common_types_decimal_string,
};

type FGBuildableCircuitSwitch = docs_json_ts_0_4_2_11_classes_base_FGBuildableCircuitSwitch_base & FGBuildable_base;

type FGBuildableConveyorBelt = FGBuildable_base & FGBuildableConveyorBelt_spline;

type FGBuildableConveyorBelt_spline = docs_json_ts_0_3_7_7_classes_base_FGBuildableConveyorBelt_spline_base & FGBuildableConveyorBelt_spline_base;

type FGBuildableConveyorBelt_spline_base = FGBuildable_base_version_specific & {
	mCustomSkins: [
		'/Game/FactoryGame/Buildable/-Shared/Customization/Skins/SkinDesc_Test1.SkinDesc_Test1_C',
	],
};

type FGBuildableConveyorLift = docs_json_ts_0_3_7_7_classes_base_FGBuildableConveyorLift_base & FGBuildable_base & FGBuildable_mSnappedPassthroughs;

type FGBuildableCornerWall = docs_json_ts_0_3_7_7_classes_base_FGBuildable_with_size_base & FGBuildable_with_height;

type FGBuildableDockingStation = FGBuildableDockingStation_base & FGBuildableDockingStation_base_base;

type FGBuildableDockingStation_base = docs_json_ts_0_3_7_7_classes_base_FGBuildable_docking_station_base_base_base & {
	VehicleFuelConsumptionRateChangedDelegate: docs_json_ts_common_types_empty_object,
	ItemTransferRateChangedDelegate: docs_json_ts_common_types_empty_object,
	MaximumStackTransferRateChangedDelegate: docs_json_ts_common_types_empty_object,
	mDockPosition: docs_json_ts_common_types_XY_decimal_string,
	mMinimumDockingTime: docs_json_ts_common_types_decimal_string,
	mFuelInventorySizeX: docs_json_ts_common_types_integer_string,
	mFuelInventorySizeY: docs_json_ts_common_types_integer_string,
	mForceSignificance: docs_json_ts_common_types_bool_string,
	mVehicleFuelConsumptionRate: docs_json_ts_common_types_decimal_string,
	mItemTransferRate: docs_json_ts_common_types_decimal_string,
	mMaximumStackTransferRate: docs_json_ts_common_types_decimal_string,
	mDockingVehicleStatistics: docs_json_ts_common_types_empty_object,
};

type FGBuildableDockingStation_base_base = docs_json_ts_0_3_7_7_classes_base_FGBuildableDockingStation_base_base & FGBuildable_docking_station;

type FGBuildableDoor = FGBuildableDoor_manual | FGBuildableDoor_automated;

type FGBuildableDoor_automated = FGBuildableDoor_automated_version_specific & FGBuildableDoor_base & FGBuildableWall;

type FGBuildableDoor_automated_version_specific = {
	bigOverlapList: '',
};

type FGBuildableDoor_base = {
	mCanBeLocked: docs_json_ts_common_types_bool_string,
	mAnimationRate: docs_json_ts_common_types_decimal_string,
	mMovementRate: docs_json_ts_common_types_decimal_string,
	EasingFunction: 'ExpoInOut' | 'Linear',
	BlendExp: docs_json_ts_common_types_decimal_string,
	Steps: docs_json_ts_common_types_integer_string,
};

type FGBuildableDoor_manual = FGBuildableDoor_base & FGBuildableDoor_manual_version_specific & FGBuildableWall;

type FGBuildableDoor_manual_version_specific = {
	IsDoorOpen: docs_json_ts_common_types_bool_string,
};

type FGBuildableDroneStation = docs_json_ts_0_4_2_11_classes_base_FGBuildable_docking_station_base & docs_json_ts_0_4_2_11_classes_base_FGBuildableDroneStation_base & docs_json_ts_0_4_2_11_overridable_has_mBatteryClasses & FGBuildable_docking_station;

type FGBuildableFactory_jump_pad = docs_json_ts_0_3_7_7_classes_base_FGBuildableFactory_jump_pad_base_base & FGBuildable_powered;

type FGBuildableFactory_landing_pad = docs_json_ts_0_3_7_7_classes_base_FGBuildableFactory_landing_pad_base_base & FGBuildable_powered;

type FGBuildableFactorySimpleProducer = docs_json_ts_0_3_7_7_classes_base_FGBuildableFactorySimpleProducer_base_base & FGBuildable_powered;

type FGBuildableFloodlight = docs_json_ts_0_4_2_11_classes_base_FGBuildableFloodlight_base & FGBuildableLightSource;

type FGBuildableFoundation = FGBuildable_with_size_and_elevation_base & FGBuildableFoundation_base;

type FGBuildableFoundation_base = FGBuildableFoundation_base_base & {
	mDisableSnapOn: docs_json_ts_common_types_empty_object | docs_json_ts_0_3_7_7_properties_mDisableSnapOn_front_bottom | docs_json_ts_0_5_2_1_properties_mDisableSnapOn_top | docs_json_ts_0_5_2_1_properties_mDisableSnapOn_bottom,
};

type FGBuildableFoundation_base_base = docs_json_ts_0_3_7_7_classes_base_FGBuildable_with_height_base & FGBuildable_base & FGBuildable_foundation_DisableAttachmentSnapOn & FGBuildable_foundation_mDisableSnapOn & FGBuildable_isFrame;

type FGBuildableFrackingActivator = docs_json_ts_0_4_2_11_classes_base_FGBuildable_powered_has_mAllowedResourceForms_with_resources_base & docs_json_ts_0_4_2_11_classes_base_FGBuildableFrackingActivator_base & FGBuildable_base & FGBuildable_powered_base;

type FGBuildableFrackingExtractor = FGBuildable_powered & FGBuildableResourceExtractor_base;

type FGBuildableGenerator = docs_json_ts_0_3_7_7_classes_base_FGBuildableGenerator_base_base & FGBuildableGenerator_no_fuel;

type FGBuildableGenerator_no_fuel = docs_json_ts_0_3_7_7_classes_base_FGBuildableGenerator_no_fuel_base_base & FGBuildable_powered;

type FGBuildableGeneratorFuel_biomass = docs_json_ts_0_3_7_7_classes_base_FGBuildableGeneratorFuel_biomass_base_base & docs_json_ts_0_4_2_11_classes_base_FGBuildableGeneratorFuel_base_base & FGBuildableGenerator;

type FGBuildableGeneratorFuel_coal = docs_json_ts_0_3_7_7_classes_base_FGBuildableGeneratorFuel_coal_base_base & docs_json_ts_0_4_2_11_classes_base_FGBuildableGeneratorFuel_base_base & FGBuildableGenerator;

type FGBuildableGeneratorFuel_fuel = docs_json_ts_0_3_7_7_classes_base_FGBuildableGeneratorFuel_fuel_base_base & docs_json_ts_0_4_2_11_classes_base_FGBuildableGeneratorFuel_base_base & FGBuildableGenerator;

type FGBuildableGeneratorGeoThermal = docs_json_ts_0_3_7_7_classes_base_FGBuildableGeneratorGeoThermal_base_base & docs_json_ts_0_4_2_11_classes_base_FGBuildableGeneratorGeoThermal_base & FGBuildableGenerator_no_fuel;

type FGBuildableGeneratorNuclear = docs_json_ts_0_3_7_7_classes_base_FGBuildableGeneratorNuclear_base_base & docs_json_ts_0_4_2_11_classes_base_FGBuildableGeneratorFuel_base_base & docs_json_ts_0_4_2_11_classes_base_FGBuildableGeneratorNuclear_base & FGBuildableGenerator;

type FGBuildableJumppad = docs_json_ts_0_3_7_7_classes_base_FGBuildableJumppad_base_base & FGBuildable_powered;

type FGBuildableLadder = docs_json_ts_0_3_7_7_classes_base_FGBuildableLadder_base & FGBuildable_base;

type FGBuildableLightsControlPanel = docs_json_ts_0_4_2_11_classes_base_FGBuildable_light_related_thing_base & docs_json_ts_0_4_2_11_classes_base_FGBuildableLightsControlPanel_base & FGBuildable_base & FGBuildableLightsControlPanel_version_specific;

type FGBuildableLightsControlPanel_version_specific = {
	OnLightControlPanelStateChanged: docs_json_ts_common_types_empty_object,
};

type FGBuildableLightSource = docs_json_ts_0_4_2_11_classes_base_FGBuildable_light_related_thing_base & docs_json_ts_0_4_2_11_classes_base_FGBuildableLightSource_base & FGBuildable_base & FGBuildable_mHasPower & FGBuildableLightSource_base;

type FGBuildableLightSource_base = {
	OnBuildableLightSourceStateChanged: docs_json_ts_common_types_empty_object,
};

type FGBuildableLightSource_Build_StreetLight_C = FGBuildableLightSource & FGBuildableLightSource_Build_StreetLight_C_version_specific;

type FGBuildableLightSource_Build_StreetLight_C_version_specific = {
	newCustomizationData: {
		OverrideColorData: {
			PrimaryColor: docs_json_ts_common_types_RGBA,
			SecondaryColor: docs_json_ts_common_types_RGBA,
		},
	},
};

type FGBuildableMAM = docs_json_ts_0_4_2_11_classes_base_FGBuildableMAM_version_specific & FGBuildable_occupied;

type FGBuildableManufacturer_Build_AssemblerMk1_C = docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_IsPowered_base & FGBuildable_powered;

type FGBuildableManufacturer_Build_Blender_C = docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_IsPowered_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_mProductionEffectsRunning_base & docs_json_ts_0_4_2_11_classes_base_FGBuildableManufacturer_base_blender_base & FGBuildable_powered;

type FGBuildableManufacturer_Build_ConstructorMk1_C = docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_IsPowered_base & docs_json_ts_0_4_2_11_classes_base_FGBuildableManufacturer_base_constructor_base & FGBuildable_powered & FGBuildableManufacturer_Build_ConstructorMk1_C_base;

type FGBuildableManufacturer_Build_ConstructorMk1_C_base = {
	CurrentPotentialConvert: docs_json_ts_0_5_2_1_properties_FGBuildableManufacturer_Build_ConstructorMk1_C_CurrentPotentialConvert_item,
};

type FGBuildableManufacturer_Build_FoundryMk1_C = docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_mProductionEffectsRunning_base & FGBuildable_powered & FGBuildableManufacturer_Build_FoundryMk1_C_base;

type FGBuildableManufacturer_Build_FoundryMk1_C_base = {
	bIsPendingToKillVfx: docs_json_ts_common_types_bool_string,
};

type FGBuildableManufacturer_Build_HadronCollider_C = docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_IsPowered_base & docs_json_ts_0_4_2_11_classes_base_FGBuildableManufacturer_Build_HadronCollider_C_base & FGBuildable_powered;

type FGBuildableManufacturer_Build_ManufacturerMk1_C = docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_base & docs_json_ts_0_4_2_11_classes_base_FGBuildable_mStopped_audio_stuff_base & FGBuildable_powered;

type FGBuildableManufacturer_Build_OilRefinery_C = docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_IsPowered_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_mProductionEffectsRunning_base & FGBuildable_powered;

type FGBuildableManufacturer_Build_Packager_C = docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_IsPowered_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_mProductionEffectsRunning_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_packager_base & FGBuildable_powered;

type FGBuildableManufacturer_Build_SmelterMk1_C = docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_Build_SmelterMk1_C_base & FGBuildable_powered & FGBuildableManufacturer_Build_SmelterMk1_C_base;

type FGBuildableManufacturer_Build_SmelterMk1_C_base = {
	mIsPendingToKillVFX: docs_json_ts_common_types_bool_string,
};

type FGBuildablePassthrough = FGBuildable_base & FGBuildablePassthrough_base & FGBuildablePassthrough_pre_update8;

type FGBuildablePassthrough_base = {
	mSnappedBuildingThickness: docs_json_ts_common_types_decimal_string,
	mMidMeshLength: docs_json_ts_common_types_decimal_string,
	mGenerateTunnelCollision: docs_json_ts_common_types_bool_string,
	mEndCapRotation: docs_json_ts_common_types_PitchYawRoll_decimal_string_signed,
	mMidMeshRotation: docs_json_ts_common_types_PitchYawRoll_decimal_string_signed,
	mEndCapTranslation: docs_json_ts_common_types_XYZ_decimal_string,
	mClearanceHeightMin: docs_json_ts_common_types_decimal_string,
	mClearanceThickness: docs_json_ts_common_types_decimal_string,
};

type FGBuildablePassthrough_pre_update8 = {
	mUseSoftClearance: docs_json_ts_common_types_bool_string,
};

type FGBuildablePillar = FGBuildable_base & FGBuildablePillar_base;

type FGBuildablePillar_base = {
	mSize: docs_json_ts_common_types_XYZ_decimal_string,
	mIsSupport: docs_json_ts_common_types_bool_string,
};

type FGBuildablePipeHyper = FGBuildable_spline & FGBuildablePipeHyper_version_specific;

type FGBuildablePipeHyper_version_specific = {
	mExitOffset: docs_json_ts_common_types_XYZ_decimal_string,
};

type FGBuildablePipeline = docs_json_ts_0_3_7_7_classes_base_FGBuildablePipeline_base_root_quantized & FGBuildable_base & FGBuildablePipeline_base_spline;

type FGBuildablePipeline_base_spline = docs_json_ts_0_3_7_7_classes_base_FGBuildablePipeline_base_spline_base & FGBuildable_mSnappedPassthroughs;

type FGBuildablePipelineJunction = docs_json_ts_0_4_2_11_classes_base_FGBuildablePipelineJunction_base_base & FGBuildable_powered;

type FGBuildablePipelinePump_pump = docs_json_ts_0_3_7_7_classes_base_FGBuildablePipelinePump_powered_base_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildablePipelinePump_pump_base_base & FGBuildable_powered;

type FGBuildablePipelinePump_valve = docs_json_ts_0_3_7_7_classes_base_FGBuildablePipelinePump_base_base & FGBuildable_powered;

type FGBuildablePipelineSupport = docs_json_ts_0_3_7_7_classes_base_FGBuildable_with_mLength & docs_json_ts_0_3_7_7_classes_base_FGBuildablePipelineSupport_base & FGBuildable_base;

type FGBuildablePipeReservoir = docs_json_ts_0_3_7_7_classes_base_FGBuildablePipeReservoir_base_base & FGBuildable_powered;

type FGBuildablePole = docs_json_ts_0_3_7_7_classes_base_FGBuildablePole_base & FGBuildable_base;

type FGBuildablePowerPole = docs_json_ts_0_3_7_7_classes_base_FGBuildablePowerPole_base & FGBuildable_base & FGBuildable_mHasPower;

type FGBuildablePowerStorage = docs_json_ts_0_4_2_11_classes_base_FGBuildablePowerStorage_base & FGBuildable_powered;

type FGBuildableRadarTower = docs_json_ts_0_3_7_7_classes_base_FGBuildableRadarTower_base_base & FGBuildable_powered;

type FGBuildableRailroadSignal_base = FGBuildable_base & FGBuildableRailroadSignal_base_version_specific;

type FGBuildableRailroadSignal_base_version_specific = {
	mOnAspectChangedDelegate: docs_json_ts_common_types_empty_object,
	mOnBlockValidationChangedDelegate: docs_json_ts_common_types_empty_object,
	mGuardedConnections: '',
	mObservedConnections: '',
	mAspect: 'RSA_None',
	mBlockValidation: 'RBV_Unvalidated',
	mIsPathSignal: docs_json_ts_common_types_bool_string,
	mIsBiDirectional: docs_json_ts_common_types_bool_string,
	mVisualState: docs_json_ts_common_types_integer_string,
	mSignificanceRange: docs_json_ts_common_types_decimal_string,
};

type FGBuildableRailroadSignal_block = FGBuildableRailroadSignal_base & FGBuildableRailroadSignal_block_version_specific;

type FGBuildableRailroadSignal_block_version_specific = {
	mPreviousAspect: 'RSA_None',
};

type FGBuildableRailroadStation = docs_json_ts_0_3_7_7_classes_base_FGBuildableRailroadStation_base_base & FGBuildableRailroadStation_base & FGBuildableTrainPlatform & FGBuildableTrainPlatform_non_empty;

type FGBuildableRailroadStation_base = {
	mShouldTeleportHere: docs_json_ts_common_types_bool_string,
	mCurrentDockedWithRuleSet: docs_json_ts_0_5_2_1_properties_mDockingRuleSet,
};

type FGBuildableRailroadTrack = FGBuildable_base & FGBuildableRailroadTrack_base & FGBuildableRailroadTrack_base_version_specific;

type FGBuildableRailroadTrack_base = docs_json_ts_0_4_2_11_classes_base_FGBuildableRailroadTrack_base_base & FGBuildable_base_version_specific;

type FGBuildableRailroadTrack_base_version_specific = {
	mTrackGraphID: docs_json_ts_common_types_integer_string_signed,
	mOverlappingTracks: '',
	mVehicles: docs_json_ts_common_types_empty_object,
	mSignalBlockID: docs_json_ts_common_types_integer_string,
};

type FGBuildableRamp = FGBuildableRamp_base & FGBuildableRamp_base_base;

type FGBuildableRamp_base = {
	mIsDoubleRamp: docs_json_ts_common_types_bool_string,
	mIsRoof: docs_json_ts_common_types_bool_string,
};

type FGBuildableRamp_base_base = docs_json_ts_0_3_7_7_classes_base_FGBuildable_with_height_base & docs_json_ts_0_3_7_7_classes_base_FGBuildable_with_size_and_elevation_base_base & FGBuildable_isFrame & FGBuildable_ramp_DisableAttachmentSnapOn & FGBuildable_ramp_mDisableSnapOn;

type FGBuildableResourceExtractor_base = docs_json_ts_0_3_7_7_classes_base_overridable_FGBuildableResourceExtractor_only_allow_certain_resources & docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_piped & docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_timed & docs_json_ts_0_4_2_11_classes_base_FGBuildable_powered_has_mAllowedResourceForms_base & FGBuildable_base & FGBuildable_powered_base;

type FGBuildableResourceExtractor_miner_mk1 = docs_json_ts_0_4_2_11_classes_base_FGBuildableResourceExtractor_miner_mk1_base_base & FGBuildable_powered & FGBuildableResourceExtractor_base;

type FGBuildableResourceExtractor_miner_mk2 = docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_miner_mk2_base_base & FGBuildable_powered;

type FGBuildableResourceExtractor_miner_mk3 = docs_json_ts_0_3_7_7_classes_base_FGBuildable_powered_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildable_powered_base_resources_base & docs_json_ts_0_3_7_7_classes_base_overridable_FGBuildableResourceExtractor_miner_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_miner_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_miner_mk3_version_specific & docs_json_ts_0_3_7_7_classes_base_overridable_FGBuildableResourceExtractor_only_allow_certain_resources & docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_piped & docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_timed & FGBuildable_powered;

type FGBuildableResourceExtractor_oil = docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_oil_base_base & FGBuildable_powered;

type FGBuildableResourceExtractor_water = docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_water_base_base & docs_json_ts_0_4_2_11_classes_base_FGBuildableResourceExtractor_water_base & FGBuildable_powered;

type FGBuildableResourceSink = docs_json_ts_0_4_2_11_classes_base_FGBuildableResourceSink_base & FGBuildable_powered;

type FGBuildableResourceSinkShop = docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceSinkShop_base_base & FGBuildable_powered;

type FGBuildableSplitterSmart = docs_json_ts_0_3_7_7_classes_base_FGBuildableSplitterSmart_base_base & FGBuildable_powered;

type FGBuildableStair = docs_json_ts_0_3_7_7_classes_base_FGBuildable_with_height_base & docs_json_ts_0_3_7_7_classes_base_FGBuildable_with_size_base & FGBuildable_base & FGBuildableStair_has_mStairDirection;

type FGBuildableStair_has_mStairDirection = {
	mStairDirection: 'EBSD_Left' | 'EBSD_Right',
};

type FGBuildableStorage = docs_json_ts_0_3_7_7_classes_base_FGBuildableStorage_base_base & FGBuildable_powered;

type FGBuildableTradingPost = docs_json_ts_0_3_7_7_classes_base_FGBuildableTradingPost_base & FGBuildable_powered & FGBuildableTradingPost_base;

type FGBuildableTradingPost_base = docs_json_ts_0_4_2_11_classes_base_FGBuildableTradingPost_base & {
	mRepresentationText: 'The HUB',
};

type FGBuildableTrainPlatform = FGBuildable_powered & FGBuildableTrainPlatform_base;

type FGBuildableTrainPlatform_base = docs_json_ts_0_3_7_7_classes_base_FGBuildableTrainPlatform_base_base & FGBuildableTrainPlatform_base_version_specific;

type FGBuildableTrainPlatform_base_version_specific = {
	mIdleUpdateTimerHandle: docs_json_ts_common_types_empty_object,
	mDockWasCancelled: docs_json_ts_common_types_bool_string,
};

type FGBuildableTrainPlatform_non_empty = FGBuildableTrainPlatform_base & FGBuildableTrainPlatform_non_empty_version_specific;

type FGBuildableTrainPlatform_non_empty_version_specific = {
	mCurrentDockForDuration: docs_json_ts_common_types_decimal_string,
};

type FGBuildableTrainPlatform_with_storage = FGBuildable_powered_storage & FGBuildableTrainPlatform_non_empty;

type FGBuildableTrainPlatformCargo = docs_json_ts_0_3_7_7_classes_base_FGBuildableTrainPlatform_with_storage_base_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableTrainPlatformCargo_pre_update8 & docs_json_ts_0_3_7_7_classes_base_FGBuildableTrainPlatformCargo_version_specific & FGBuildable_base & FGBuildableTrainPlatform_with_storage & FGBuildableTrainPlatformCargo_version_specific;

type FGBuildableTrainPlatformCargo_version_specific = {
	mOnTransferRateUpdated: docs_json_ts_common_types_empty_object,
	mWaitForConditionUpdatePeriod: docs_json_ts_common_types_decimal_string,
	mDockingRuleSet: docs_json_ts_0_5_2_1_properties_mDockingRuleSet,
	mLoadItemFilter: '',
	mUnloadItemFilter: '',
	mHasFullyLoadUnloadRule: docs_json_ts_common_types_bool_string,
	mDockForDuration: docs_json_ts_common_types_decimal_string,
	mMustDockForDuration: docs_json_ts_common_types_bool_string,
	mRanCompleteBeforeNone: docs_json_ts_common_types_bool_string,
	mTimeSinceLastLoadTransferUpdate: docs_json_ts_common_types_decimal_string,
	mTimeSinceLastUnloadTransferUpdate: docs_json_ts_common_types_decimal_string,
	mSmoothedLoadRate: docs_json_ts_common_types_decimal_string,
	mSmoothedUnloadRate: docs_json_ts_common_types_decimal_string,
};

type FGBuildableWall = docs_json_ts_0_5_2_1_classes_base_overridable_FGBuildable_is_wallish & FGBuildable_with_elevation & FGBuildable_with_height_and_width;

type FGBuildableWidgetSign = FGBuildable_base & FGBuildableWidgetSign_base;

type FGBuildableWidgetSign_base = {
	mGainSignificanceDistance: docs_json_ts_common_types_decimal_string,
	mTextElementToDataMap: docs_json_ts_common_types_empty_object,
	mIconElementToDataMap: docs_json_ts_common_types_empty_object,
	mPrefabTextElementSaveData: '',
	mPrefabIconElementSaveData: '',
	mForegroundColor: docs_json_ts_common_types_RGBA,
	mBackgroundColor: docs_json_ts_common_types_RGBA,
	mAuxilaryColor: docs_json_ts_common_types_RGBA,
	mEmissive: docs_json_ts_common_types_decimal_string,
	mGlossiness: docs_json_ts_common_types_decimal_string,
	mDataVersion: docs_json_ts_common_types_integer_string,
	mSignPoles: '',
	mWorldDimensions: docs_json_ts_common_types_XY_decimal_string,
	mPoleOffset: docs_json_ts_common_types_XYZ_decimal_string,
	mPoleScale: docs_json_ts_common_types_XY_decimal_string,
	mSignToSignOffset: docs_json_ts_common_types_decimal_string,
};

type FGBuildableWire = docs_json_ts_0_3_7_7_classes_base_FGBuildableWire_base & FGBuildable_base;

type FGConsumableDescriptor = docs_json_ts_0_3_7_7_classes_base_FGConsumableDescriptor_base & FGDescriptor_sinkable & FGItemDescriptor_base;

type FGDescriptor = docs_json_ts_0_4_2_11_classes_base_FGDescriptor_base & {
	mPersistentBigIcon: docs_json_ts_0_4_2_11_properties_Texture2D | 'None',
	mSmallIcon: docs_json_ts_0_4_2_11_properties_Texture2D | 'None',
};

type FGDescriptor_BuildMenu = FGDescriptor & FGDescriptor_BuildMenu_base;

type FGDescriptor_BuildMenu_base = docs_json_ts_0_4_2_11_classes_base_FGDescriptor_BuildMenu_base & {
	mMenuPriority: docs_json_ts_common_types_decimal_string,
	mBuildMenuPriority: docs_json_ts_common_types_decimal_string,
};

type FGDescriptor_sinkable = docs_json_ts_0_3_7_7_classes_base_FGDescriptor_sinkable_base & FGDescriptor;

type FGGolfCartDispenser = docs_json_ts_0_3_7_7_classes_base_FGGolfCartDispenser & FGGolfCartDispenser_version_specific;

type FGGolfCartDispenser_version_specific = {
	mMaxSpawnDistance: docs_json_ts_common_types_decimal_string,
	mSpawningClearance: docs_json_ts_common_types_decimal_string,
	mBuildDisqualifierText: 'Vehicles cannot be built or deployed on top of existing vehicles.',
	canDisplayDisqualifier: docs_json_ts_common_types_bool_string,
};

type FGItemDescAmmoTypeColorCartridge = docs_json_ts_0_3_7_7_classes_base_FGColorGun_base_base & FGItemDescAmmoTypeColorCartridge_base;

type FGItemDescAmmoTypeColorCartridge_base = FGItemDescAmmoTypeInstantHit & {
	ToggleColorPickerUI: docs_json_ts_common_types_empty_object,
};

type FGItemDescAmmoTypeInstantHit = FGItemDescAmmoTypeInstantHit_base & FGItemDescAmmoTypeProjectile_base_sinkable;

type FGItemDescAmmoTypeInstantHit_base = FGItemDescAmmoTypeProjectile_base & {
	mHitDamage: docs_json_ts_common_types_decimal_string,
};

type FGItemDescAmmoTypeProjectile_base = FGItemDescAmmoTypeProjectile_base_base & FGItemDescAmmoTypeProjectile_base_version_specific & FGItemDescriptor_base;

type FGItemDescAmmoTypeProjectile_base_base = FGItemDescriptor_base_base & {
	AmmoFiredDelegate: docs_json_ts_common_types_empty_object,
	mFiringTransform: docs_json_ts_0_3_7_7_properties_transform_Rotation_Translation_Scale3D,
	mHasBeenInitialized: docs_json_ts_common_types_bool_string,
	mWeaponDamageMultiplier: docs_json_ts_common_types_decimal_string,
	mMagazineSize: docs_json_ts_common_types_integer_string,
	mMaxAmmoEffectiveRange: docs_json_ts_common_types_decimal_string,
};

type FGItemDescAmmoTypeProjectile_base_sinkable = FGItemDescAmmoTypeProjectile_base & {
	mResourceSinkPoints: docs_json_ts_common_types_integer_string,
};

type FGItemDescAmmoTypeProjectile_base_version_specific = FGItemDescriptor_base_base & {
	mReloadTimeModifier: docs_json_ts_common_types_decimal_string,
	mFireRateModifier: docs_json_ts_common_types_decimal_string,
	mDispersionPerShotChangeModifier: docs_json_ts_common_types_decimal_string,
	mMinWeaponDispersionModifier: docs_json_ts_common_types_decimal_string,
	mMaxWeaponDispersionModifier: docs_json_ts_common_types_decimal_string,
	mWeaponAimTimeModifier: docs_json_ts_common_types_decimal_string,
	mAmmoDamageFalloff: docs_json_ts_0_5_2_1_overridable_FalloffCurve_EditorCurveData_with_ExternalCurve,
};

type FGItemDescAmmoTypeProjectile_Desc_NobeliskExplosive_C = FGItemDescAmmoTypeProjectile_Desc_NobeliskExplosive_C_base & {
	mProjectileData: {
		ProjectileClass: docs_json_ts_0_3_7_7_overridable_BlueprintGeneratedClass_quoted,
		ProjectileLifeSpan: docs_json_ts_common_types_decimal_string_signed,
		ProjectileStickSpan: docs_json_ts_common_types_decimal_string_signed,
		ExplosionDamage: docs_json_ts_common_types_integer_string,
		ExplosionRadius: docs_json_ts_common_types_decimal_string,
		ImpactDamage: docs_json_ts_common_types_integer_string,
		ExplodeAtEndOfLife: docs_json_ts_common_types_bool_string,
		DamageType: docs_json_ts_0_3_7_7_overridable_BlueprintGeneratedClass_quoted,
		DamageTypeExplode: docs_json_ts_0_3_7_7_overridable_BlueprintGeneratedClass_quoted,
		DamageFalloffCurve: docs_json_ts_0_5_2_1_properties_FalloffCurve_EditorCurveData_only,
		WeaponDamageMultiplier: docs_json_ts_common_types_decimal_string,
	},
};

type FGItemDescAmmoTypeProjectile_Desc_NobeliskExplosive_C_base = FGItemDescAmmoTypeProjectile_base & FGItemDescAmmoTypeProjectile_base_sinkable;

type FGItemDescAmmoTypeProjectile_Desc_SnowballProjectile_C = FGItemDescAmmoTypeProjectile_Desc_SnowballProjectile_C_base & {
	mProjectileData: {
		ProjectileClass: docs_json_ts_0_3_7_7_overridable_BlueprintGeneratedClass_quoted,
		ProjectileLifeSpan: docs_json_ts_common_types_decimal_string_signed,
		ProjectileStickSpan: docs_json_ts_common_types_decimal_string_signed,
		ExplosionDamage: docs_json_ts_common_types_integer_string,
		ExplosionRadius: docs_json_ts_common_types_decimal_string,
		ImpactDamage: docs_json_ts_common_types_integer_string,
		ExplodeAtEndOfLife: docs_json_ts_common_types_bool_string,
		DamageType: docs_json_ts_0_3_7_7_overridable_BlueprintGeneratedClass_quoted,
		DamageTypeExplode: docs_json_ts_0_3_7_7_overridable_BlueprintGeneratedClass_quoted,
		DamageFalloffCurve: docs_json_ts_0_5_2_1_properties_FalloffCurve_EditorCurveData_only,
		WeaponDamageMultiplier: docs_json_ts_common_types_decimal_string,
	},
};

type FGItemDescAmmoTypeProjectile_Desc_SnowballProjectile_C_base = FGItemDescAmmoTypeProjectile_base & FGItemDescAmmoTypeProjectile_base_sinkable;

type FGItemDescAmmoTypeProjectile_Desc_SpikedRebar_C = FGItemDescAmmoTypeProjectile_Desc_SpikedRebar_C_base & {
	mProjectileData: {
		ProjectileClass: docs_json_ts_0_3_7_7_overridable_BlueprintGeneratedClass_quoted,
		ProjectileLifeSpan: docs_json_ts_common_types_decimal_string_signed,
		ProjectileStickSpan: docs_json_ts_common_types_decimal_string_signed,
		ImpactDamage: docs_json_ts_common_types_integer_string,
		CanTriggerExplodeBySameClass: docs_json_ts_common_types_bool_string,
		DamageType: docs_json_ts_0_3_7_7_overridable_BlueprintGeneratedClass_quoted,
		DamageTypeExplode: docs_json_ts_0_3_7_7_properties_Class_quoted,
		DamageFalloffCurve: docs_json_ts_0_5_2_1_properties_FalloffCurve_EditorCurveData_only,
		WeaponDamageMultiplier: docs_json_ts_common_types_decimal_string,
	},
};

type FGItemDescAmmoTypeProjectile_Desc_SpikedRebar_C_base = FGItemDescAmmoTypeProjectile_base & FGItemDescAmmoTypeProjectile_base_sinkable;

type FGItemDescAmmoTypeProjectile_explosive_firework = FGItemDescAmmoTypeProjectile_base & {
	mProjectileData: {
		ProjectileClass: docs_json_ts_0_3_7_7_overridable_BlueprintGeneratedClass_quoted,
		ProjectileLifeSpan: docs_json_ts_common_types_decimal_string_signed,
		ProjectileStickSpan: docs_json_ts_common_types_decimal_string_signed,
		ExplosionDamage: docs_json_ts_common_types_integer_string,
		ExplosionRadius: docs_json_ts_common_types_decimal_string,
		ImpactDamage: docs_json_ts_common_types_integer_string,
		CanTriggerExplodeBySameClass: docs_json_ts_common_types_bool_string,
		ExplodeAtEndOfLife: docs_json_ts_common_types_bool_string,
		DamageType: docs_json_ts_0_3_7_7_overridable_BlueprintGeneratedClass_quoted,
		DamageTypeExplode: docs_json_ts_0_3_7_7_overridable_BlueprintGeneratedClass_quoted,
		DamageFalloffCurve: docs_json_ts_0_5_2_1_properties_FalloffCurve_EditorCurveData_only,
		WeaponDamageMultiplier: docs_json_ts_common_types_decimal_string,
	},
};

type FGItemDescriptor = docs_json_ts_0_4_2_11_classes_base_FGDescriptor_sinkable_base & FGItemDescriptor_base;

type FGItemDescriptor_base = FGItemDescriptor_base_base & {
	mBuildMenuPriority: docs_json_ts_common_types_decimal_string,
};

type FGItemDescriptor_base_base = FGDescriptor & {
	mMenuPriority: docs_json_ts_common_types_decimal_string,
	mSubCategories: null,
};

type FGNobeliskDetonator = FGNobeliskDetonator_pre_update6 & FGNobeliskDetonator_version_specific;

type FGNobeliskDetonator_pre_update6 = docs_json_ts_0_5_2_1_classes_base_overridable_FGWeapon_version_specific & docs_json_ts_0_3_7_7_classes_base_FGEquipment_base & docs_json_ts_0_3_7_7_classes_base_FGNobeliskDetonator_base & docs_json_ts_0_4_2_11_classes_base_FGWeaponProjectile_base & FGWeapon_pre_update6 & FGWeapon_version_specific;

type FGNobeliskDetonator_version_specific = {
	mRadialMenuShowUpTime: docs_json_ts_common_types_decimal_string,
	mDispensedProjectiles: '',
	mDelayBetweenSecondaryTriggers: docs_json_ts_common_types_decimal_string,
};

type FGPipeHyperStart = docs_json_ts_0_3_7_7_classes_base_FGPipeHyperStart_base_base & FGBuildable_pole_with_length_and_power;

type FGResourceDescriptor = docs_json_ts_0_3_7_7_classes_base_FGResourceDescriptor_base & docs_json_ts_0_4_2_11_classes_base_FGDescriptor_sinkable & FGItemDescriptor_base;

type FGSchematic_base = docs_json_ts_0_4_2_11_classes_base_overridable_FGSchematic_base & docs_json_ts_0_5_2_1_classes_base_overridable_FGSchematic_version_specific & docs_json_ts_0_3_7_7_classes_base_FGSchematic_pre_1_0 & docs_json_ts_0_3_7_7_classes_base_overridable_FGSchematic_version_specific & docs_json_ts_0_4_2_11_classes_base_overridable_FGSchematic_has_mSchematicIcon & docs_json_ts_0_3_7_7_classes_base_instructive & docs_json_ts_0_3_7_7_classes_base_isDescribed & FGSchematic_pre_update6;

type FGSchematic_pre_update6 = {
	mUnlocks: [
		...docs_json_ts_0_5_2_1_overridable_mUnlocks_item[],
	],
};

type FGSchematic_with_described_unlocks = FGSchematic_base & FGSchematic_with_described_unlocks_base;

type FGSchematic_with_described_unlocks_base = FGSchematic_with_described_unlocks_base_base & {
	mUnlockDescription: Exclude<string, ''>,
};

type FGSchematic_with_described_unlocks_base_base = {
	mUnlockName: Exclude<string, ''>,
	mUnlockDescription: string,
	mUnlockIconBig: 'Unsupported texture. Contact developer for support',
	mUnlockIconSmall: 'Unsupported texture. Contact developer for support',
	mUnlockIconCategory: 'Unsupported texture. Contact developer for support',
};

type FGVehicleDescriptor_fueled_with_inventory = docs_json_ts_0_4_2_11_classes_base_FGVehicleDescriptor_fueled_with_inventory & FGDescriptor_BuildMenu_base;

type FGVehicleDescriptor_powered = docs_json_ts_0_4_2_11_classes_base_FGVehicleDescriptor_powered & FGDescriptor_BuildMenu_base;

type FGVehicleDescriptor_with_inventory = docs_json_ts_0_4_2_11_classes_base_FGVehicleDescriptor_with_inventory & FGDescriptor_BuildMenu_base;

type FGWeapon_Equip_RebarGun_Projectile_C = docs_json_ts_0_5_2_1_classes_base_overridable_FGWeapon_version_specific & docs_json_ts_0_3_7_7_classes_base_FGWeaponProjectile_base & docs_json_ts_0_3_7_7_classes_base_FGWeaponProjectile_has_mAttachSocket & docs_json_ts_0_3_7_7_classes_base_FGWeaponProjectileFire_base_random & docs_json_ts_0_4_2_11_classes_base_FGWeaponProjectile_base & docs_json_ts_0_4_2_11_classes_base_FGWeaponProjectileFire_has_mMuteDryFire & FGWeapon_pre_update6 & FGWeapon_version_specific;

type FGWeapon_Equip_Rifle_C = docs_json_ts_0_5_2_1_classes_base_overridable_FGWeapon_version_specific & docs_json_ts_0_3_7_7_classes_base_FGWeaponInstantFire_base & docs_json_ts_0_3_7_7_classes_base_FGWeaponProjectile_base & docs_json_ts_0_3_7_7_classes_base_FGWeaponProjectile_has_mAttachSocket & docs_json_ts_0_4_2_11_classes_base_FGWeaponProjectile_base & FGWeapon_Equip_Rifle_C_base & FGWeapon_pre_update6 & FGWeapon_version_specific;

type FGWeapon_Equip_Rifle_C_base = {
	mArmAnimation: 'AE_Rifle',
};

type FGWeapon_pre_update6 = {
	mOldState: [
		'EWS_Unequipped',
	],
	mBaseRestingDispersion: docs_json_ts_common_types_decimal_string,
	mBaseFiringDispersion: docs_json_ts_common_types_decimal_string,
	mBaseAimTime: docs_json_ts_common_types_decimal_string,
	mRestingDispersion: docs_json_ts_common_types_decimal_string,
	mFiringDispersion: docs_json_ts_common_types_decimal_string,
	mDispersionChangePerShot: docs_json_ts_common_types_decimal_string,
	mAimTime: docs_json_ts_common_types_decimal_string,
	mAmmoCycleMode: 'IE_Released',
};

type FGWeapon_version_specific = {
	mShowCycleAmmoRadialMenuTimer: docs_json_ts_common_types_empty_object,
	mWeaponState: 'EWS_Unequipped',
	mAutomaticallyReload: docs_json_ts_common_types_bool_string,
	mAutoReloadDelay: docs_json_ts_common_types_decimal_string,
	mAutoReloadTimerHandle: docs_json_ts_common_types_empty_object,
	mCurrentAmmoCount: docs_json_ts_common_types_integer_string,
	mWeaponDamageMultiplier: docs_json_ts_common_types_decimal_string,
	mFiringBlocksDispersionReduction: docs_json_ts_common_types_bool_string,
	mCurrentDispersion: docs_json_ts_common_types_decimal_string,
	mAmmoSwitchUsedRadialMenu: docs_json_ts_common_types_bool_string,
	mOnAmmoCyclingPressed: docs_json_ts_common_types_empty_object,
	mOnAmmoCyclingReleased: docs_json_ts_common_types_empty_object,
	mOnWeaponStateChanged: docs_json_ts_common_types_empty_object,
};

export type {
	FGBuildable_base,
	FGBuildable_base_version_specific,
	FGBuildable_docking_station,
	FGBuildable_foundation_DisableAttachmentSnapOn,
	FGBuildable_foundation_mDisableSnapOn,
	FGBuildable_isFrame,
	FGBuildable_mHasPower,
	FGBuildable_mSnappedPassthroughs,
	FGBuildable_occupied,
	FGBuildable_pole_with_length_and_power,
	FGBuildable_powered,
	FGBuildable_powered_base,
	FGBuildable_powered_base_base,
	FGBuildable_powered_storage,
	FGBuildable_ramp_DisableAttachmentSnapOn,
	FGBuildable_ramp_mDisableSnapOn,
	FGBuildable_spline,
	FGBuildable_tiered,
	FGBuildable_with_elevation,
	FGBuildable_with_height,
	FGBuildable_with_height_and_width,
	FGBuildable_with_size_and_elevation,
	FGBuildable_with_size_and_elevation_base,
	FGBuildableAttachment,
	FGBuildableAttachment_splitter,
	FGBuildableAttachmentMerger,
	FGBuildableBeam,
	FGBuildableBeam_base,
	FGBuildableCircuitSwitch,
	FGBuildableConveyorBelt,
	FGBuildableConveyorBelt_spline,
	FGBuildableConveyorBelt_spline_base,
	FGBuildableConveyorLift,
	FGBuildableCornerWall,
	FGBuildableDockingStation,
	FGBuildableDockingStation_base,
	FGBuildableDockingStation_base_base,
	FGBuildableDoor,
	FGBuildableDoor_automated,
	FGBuildableDoor_automated_version_specific,
	FGBuildableDoor_base,
	FGBuildableDoor_manual,
	FGBuildableDoor_manual_version_specific,
	FGBuildableDroneStation,
	FGBuildableFactory_jump_pad,
	FGBuildableFactory_landing_pad,
	FGBuildableFactorySimpleProducer,
	FGBuildableFloodlight,
	FGBuildableFoundation,
	FGBuildableFoundation_base,
	FGBuildableFoundation_base_base,
	FGBuildableFrackingActivator,
	FGBuildableFrackingExtractor,
	FGBuildableGenerator,
	FGBuildableGenerator_no_fuel,
	FGBuildableGeneratorFuel_biomass,
	FGBuildableGeneratorFuel_coal,
	FGBuildableGeneratorFuel_fuel,
	FGBuildableGeneratorGeoThermal,
	FGBuildableGeneratorNuclear,
	FGBuildableJumppad,
	FGBuildableLadder,
	FGBuildableLightsControlPanel,
	FGBuildableLightsControlPanel_version_specific,
	FGBuildableLightSource,
	FGBuildableLightSource_base,
	FGBuildableLightSource_Build_StreetLight_C,
	FGBuildableLightSource_Build_StreetLight_C_version_specific,
	FGBuildableMAM,
	FGBuildableManufacturer_Build_AssemblerMk1_C,
	FGBuildableManufacturer_Build_Blender_C,
	FGBuildableManufacturer_Build_ConstructorMk1_C,
	FGBuildableManufacturer_Build_ConstructorMk1_C_base,
	FGBuildableManufacturer_Build_FoundryMk1_C,
	FGBuildableManufacturer_Build_FoundryMk1_C_base,
	FGBuildableManufacturer_Build_HadronCollider_C,
	FGBuildableManufacturer_Build_ManufacturerMk1_C,
	FGBuildableManufacturer_Build_OilRefinery_C,
	FGBuildableManufacturer_Build_Packager_C,
	FGBuildableManufacturer_Build_SmelterMk1_C,
	FGBuildableManufacturer_Build_SmelterMk1_C_base,
	FGBuildablePassthrough,
	FGBuildablePassthrough_base,
	FGBuildablePassthrough_pre_update8,
	FGBuildablePillar,
	FGBuildablePillar_base,
	FGBuildablePipeHyper,
	FGBuildablePipeHyper_version_specific,
	FGBuildablePipeline,
	FGBuildablePipeline_base_spline,
	FGBuildablePipelineJunction,
	FGBuildablePipelinePump_pump,
	FGBuildablePipelinePump_valve,
	FGBuildablePipelineSupport,
	FGBuildablePipeReservoir,
	FGBuildablePole,
	FGBuildablePowerPole,
	FGBuildablePowerStorage,
	FGBuildableRadarTower,
	FGBuildableRailroadSignal_base,
	FGBuildableRailroadSignal_base_version_specific,
	FGBuildableRailroadSignal_block,
	FGBuildableRailroadSignal_block_version_specific,
	FGBuildableRailroadStation,
	FGBuildableRailroadStation_base,
	FGBuildableRailroadTrack,
	FGBuildableRailroadTrack_base,
	FGBuildableRailroadTrack_base_version_specific,
	FGBuildableRamp,
	FGBuildableRamp_base,
	FGBuildableRamp_base_base,
	FGBuildableResourceExtractor_base,
	FGBuildableResourceExtractor_miner_mk1,
	FGBuildableResourceExtractor_miner_mk2,
	FGBuildableResourceExtractor_miner_mk3,
	FGBuildableResourceExtractor_oil,
	FGBuildableResourceExtractor_water,
	FGBuildableResourceSink,
	FGBuildableResourceSinkShop,
	FGBuildableSplitterSmart,
	FGBuildableStair,
	FGBuildableStair_has_mStairDirection,
	FGBuildableStorage,
	FGBuildableTradingPost,
	FGBuildableTradingPost_base,
	FGBuildableTrainPlatform,
	FGBuildableTrainPlatform_base,
	FGBuildableTrainPlatform_base_version_specific,
	FGBuildableTrainPlatform_non_empty,
	FGBuildableTrainPlatform_non_empty_version_specific,
	FGBuildableTrainPlatform_with_storage,
	FGBuildableTrainPlatformCargo,
	FGBuildableTrainPlatformCargo_version_specific,
	FGBuildableWall,
	FGBuildableWidgetSign,
	FGBuildableWidgetSign_base,
	FGBuildableWire,
	FGConsumableDescriptor,
	FGDescriptor,
	FGDescriptor_BuildMenu,
	FGDescriptor_BuildMenu_base,
	FGDescriptor_sinkable,
	FGGolfCartDispenser,
	FGGolfCartDispenser_version_specific,
	FGItemDescAmmoTypeColorCartridge,
	FGItemDescAmmoTypeColorCartridge_base,
	FGItemDescAmmoTypeInstantHit,
	FGItemDescAmmoTypeInstantHit_base,
	FGItemDescAmmoTypeProjectile_base,
	FGItemDescAmmoTypeProjectile_base_base,
	FGItemDescAmmoTypeProjectile_base_sinkable,
	FGItemDescAmmoTypeProjectile_base_version_specific,
	FGItemDescAmmoTypeProjectile_Desc_NobeliskExplosive_C,
	FGItemDescAmmoTypeProjectile_Desc_NobeliskExplosive_C_base,
	FGItemDescAmmoTypeProjectile_Desc_SnowballProjectile_C,
	FGItemDescAmmoTypeProjectile_Desc_SnowballProjectile_C_base,
	FGItemDescAmmoTypeProjectile_Desc_SpikedRebar_C,
	FGItemDescAmmoTypeProjectile_Desc_SpikedRebar_C_base,
	FGItemDescAmmoTypeProjectile_explosive_firework,
	FGItemDescriptor,
	FGItemDescriptor_base,
	FGItemDescriptor_base_base,
	FGNobeliskDetonator,
	FGNobeliskDetonator_pre_update6,
	FGNobeliskDetonator_version_specific,
	FGPipeHyperStart,
	FGResourceDescriptor,
	FGSchematic_base,
	FGSchematic_pre_update6,
	FGSchematic_with_described_unlocks,
	FGSchematic_with_described_unlocks_base,
	FGSchematic_with_described_unlocks_base_base,
	FGVehicleDescriptor_fueled_with_inventory,
	FGVehicleDescriptor_powered,
	FGVehicleDescriptor_with_inventory,
	FGWeapon_Equip_RebarGun_Projectile_C,
	FGWeapon_Equip_Rifle_C,
	FGWeapon_Equip_Rifle_C_base,
	FGWeapon_pre_update6,
	FGWeapon_version_specific,
};
