/* eslint-disable @stylistic/max-len */

import type {
	bool_string as docs_json_ts_common_types_bool_string,
	decimal_string as docs_json_ts_common_types_decimal_string,
	decimal_string_signed as docs_json_ts_common_types_decimal_string_signed,
	empty_object as docs_json_ts_common_types_empty_object,
	integer_string as docs_json_ts_common_types_integer_string,
	integer_string_signed as docs_json_ts_common_types_integer_string_signed,
	PitchYawRoll_decimal_string_signed as docs_json_ts_common_types_PitchYawRoll_decimal_string_signed,
	RGBA as docs_json_ts_common_types_RGBA,
	XY_decimal_string as docs_json_ts_common_types_XY_decimal_string,
	XYZ_decimal_string as docs_json_ts_common_types_XYZ_decimal_string,
} from './../../common/types.ts';

import type {
	FGBuildable_base_pre_1_0 as docs_json_ts_0_3_7_7_classes_base_FGBuildable_base_pre_1_0,
	FGBuildable_base_version_specific as docs_json_ts_0_3_7_7_classes_base_FGBuildable_base_version_specific,
	FGBuildable_docking_station_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildable_docking_station_base_base_base,
	FGBuildable_occupied_base as docs_json_ts_0_3_7_7_classes_base_FGBuildable_occupied_base,
	FGBuildable_powered_base_resources_base as docs_json_ts_0_3_7_7_classes_base_FGBuildable_powered_base_resources_base,
	FGBuildable_powered_pre_1_0 as docs_json_ts_0_3_7_7_classes_base_FGBuildable_powered_pre_1_0,
	FGBuildable_powered_version_specific as docs_json_ts_0_3_7_7_classes_base_FGBuildable_powered_version_specific,
	FGBuildable_tiered_base as docs_json_ts_0_3_7_7_classes_base_FGBuildable_tiered_base,
	FGBuildable_with_mLength as docs_json_ts_0_3_7_7_classes_base_FGBuildable_with_mLength,
	FGBuildableAttachment_has_mCurrentInventoryIndex as docs_json_ts_0_3_7_7_classes_base_FGBuildableAttachment_has_mCurrentInventoryIndex,
	FGBuildableAttachment_splitter_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableAttachment_splitter_base_base_base,
	FGBuildableAttachmentMerger_version_specific as docs_json_ts_0_3_7_7_classes_base_FGBuildableAttachmentMerger_version_specific,
	FGBuildableConveyorBelt_pre_1_0 as docs_json_ts_0_3_7_7_classes_base_FGBuildableConveyorBelt_pre_1_0,
	FGBuildableConveyorBelt_pre_update8 as docs_json_ts_0_3_7_7_classes_base_FGBuildableConveyorBelt_pre_update8,
	FGBuildableConveyorLift_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableConveyorLift_base,
	FGBuildableDockingStation_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableDockingStation_base_base,
	FGBuildableFactory_jump_pad_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableFactory_jump_pad_base_base,
	FGBuildableFactory_landing_pad_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableFactory_landing_pad_base_base,
	FGBuildableFactorySimpleProducer_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableFactorySimpleProducer_base_base,
	FGBuildableGenerator_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableGenerator_base_base_base,
	FGBuildableGenerator_base_base_pre_1_0 as docs_json_ts_0_3_7_7_classes_base_FGBuildableGenerator_base_base_pre_1_0,
	FGBuildableGenerator_no_fuel_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableGenerator_no_fuel_base_base,
	FGBuildableGenerator_no_fuel_base_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableGenerator_no_fuel_base_base_base_base,
	FGBuildableGeneratorFuel_biomass_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableGeneratorFuel_biomass_base_base,
	FGBuildableGeneratorFuel_coal_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableGeneratorFuel_coal_base_base,
	FGBuildableGeneratorFuel_fuel_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableGeneratorFuel_fuel_base_base,
	FGBuildableGeneratorGeoThermal_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableGeneratorGeoThermal_base_base,
	FGBuildableGeneratorNuclear_version_specific as docs_json_ts_0_3_7_7_classes_base_FGBuildableGeneratorNuclear_version_specific,
	FGBuildableJumppad_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableJumppad_base_base,
	FGBuildableLadder_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableLadder_base,
	FGBuildableManufacturer_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_base,
	FGBuildableManufacturer_base_IsPowered_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_IsPowered_base,
	FGBuildableManufacturer_base_mProductionEffectsRunning_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_mProductionEffectsRunning_base,
	FGBuildableManufacturer_base_packager_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_packager_base,
	FGBuildableManufacturer_Build_SmelterMk1_C_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_Build_SmelterMk1_C_base,
	FGBuildablePipeline_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildablePipeline_base_base,
	FGBuildablePipeline_base_root_quantized as docs_json_ts_0_3_7_7_classes_base_FGBuildablePipeline_base_root_quantized,
	FGBuildablePipeline_base_spline_base as docs_json_ts_0_3_7_7_classes_base_FGBuildablePipeline_base_spline_base,
	FGBuildablePipelinePump_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildablePipelinePump_base_base,
	FGBuildablePipelinePump_powered_version_specific as docs_json_ts_0_3_7_7_classes_base_FGBuildablePipelinePump_powered_version_specific,
	FGBuildablePipelinePump_pump_version_specific as docs_json_ts_0_3_7_7_classes_base_FGBuildablePipelinePump_pump_version_specific,
	FGBuildablePipelineSupport_base as docs_json_ts_0_3_7_7_classes_base_FGBuildablePipelineSupport_base,
	FGBuildablePipeReservoir_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildablePipeReservoir_base_base,
	FGBuildablePowerPole_base as docs_json_ts_0_3_7_7_classes_base_FGBuildablePowerPole_base,
	FGBuildableRadarTower_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableRadarTower_base_base,
	FGBuildableRailroadStation_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableRailroadStation_base_base,
	FGBuildableResourceExtractor_miner_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_miner_base,
	FGBuildableResourceExtractor_miner_mk2_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_miner_mk2_base_base,
	FGBuildableResourceExtractor_miner_mk3_version_specific as docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_miner_mk3_version_specific,
	FGBuildableResourceExtractor_oil_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_oil_base_base,
	FGBuildableResourceExtractor_piped as docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_piped,
	FGBuildableResourceExtractor_piped_pre_1_0 as docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_piped_pre_1_0,
	FGBuildableResourceExtractor_timed as docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_timed,
	FGBuildableResourceExtractor_water_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_water_base_base,
	FGBuildableResourceSinkShop_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceSinkShop_base_base,
	FGBuildableSplitterSmart_version_specific as docs_json_ts_0_3_7_7_classes_base_FGBuildableSplitterSmart_version_specific,
	FGBuildableStorage_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableStorage_base_base,
	FGBuildableTradingPost_pre_1_0 as docs_json_ts_0_3_7_7_classes_base_FGBuildableTradingPost_pre_1_0,
	FGBuildableTradingPost_pre_update8 as docs_json_ts_0_3_7_7_classes_base_FGBuildableTradingPost_pre_update8,
	FGBuildableTradingPost_version_specific as docs_json_ts_0_3_7_7_classes_base_FGBuildableTradingPost_version_specific,
	FGBuildableTrainPlatform_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableTrainPlatform_base_base,
	FGBuildableTrainPlatform_with_storage_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableTrainPlatform_with_storage_base_base_base,
	FGBuildableTrainPlatformCargo_pre_update8 as docs_json_ts_0_3_7_7_classes_base_FGBuildableTrainPlatformCargo_pre_update8,
	FGBuildableTrainPlatformCargo_version_specific as docs_json_ts_0_3_7_7_classes_base_FGBuildableTrainPlatformCargo_version_specific,
	FGBuildableWire_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableWire_base,
	FGColorGun_base_base as docs_json_ts_0_3_7_7_classes_base_FGColorGun_base_base,
	FGConsumableDescriptor_base as docs_json_ts_0_3_7_7_classes_base_FGConsumableDescriptor_base,
	FGDescriptor_base as docs_json_ts_0_3_7_7_classes_base_FGDescriptor_base,
	FGEquipment_base as docs_json_ts_0_3_7_7_classes_base_FGEquipment_base,
	FGGolfCartDispenser as docs_json_ts_0_3_7_7_classes_base_FGGolfCartDispenser,
	FGNobeliskDetonator_base as docs_json_ts_0_3_7_7_classes_base_FGNobeliskDetonator_base,
	FGPipeHyperStart_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGPipeHyperStart_base_base_base,
	FGPipeHyperStart_pre_update8 as docs_json_ts_0_3_7_7_classes_base_FGPipeHyperStart_pre_update8,
	FGResourceDescriptor_base as docs_json_ts_0_3_7_7_classes_base_FGResourceDescriptor_base,
	FGSchematic_pre_1_0 as docs_json_ts_0_3_7_7_classes_base_FGSchematic_pre_1_0,
	FGWeaponInstantFire_base as docs_json_ts_0_3_7_7_classes_base_FGWeaponInstantFire_base,
	FGWeaponProjectile_base as docs_json_ts_0_3_7_7_classes_base_FGWeaponProjectile_base,
	FGWeaponProjectile_has_mAttachSocket as docs_json_ts_0_3_7_7_classes_base_FGWeaponProjectile_has_mAttachSocket,
	FGWeaponProjectile_thrown_base_base as docs_json_ts_0_3_7_7_classes_base_FGWeaponProjectile_thrown_base_base,
	FGWeaponProjectileFire_base_random as docs_json_ts_0_3_7_7_classes_base_FGWeaponProjectileFire_base_random,
	has_mCanStack as docs_json_ts_0_3_7_7_classes_base_has_mCanStack,
	has_mDisableSnapOn as docs_json_ts_0_3_7_7_classes_base_has_mDisableSnapOn,
	has_mElevation as docs_json_ts_0_3_7_7_classes_base_has_mElevation,
	has_mHeight as docs_json_ts_0_3_7_7_classes_base_has_mHeight,
	has_mMeshLength as docs_json_ts_0_3_7_7_classes_base_has_mMeshLength,
	has_mNumCyclesForProductivity as docs_json_ts_0_3_7_7_classes_base_has_mNumCyclesForProductivity,
	has_mResourceSinkPoints as docs_json_ts_0_3_7_7_classes_base_has_mResourceSinkPoints,
	has_mSize as docs_json_ts_0_3_7_7_classes_base_has_mSize,
	has_mSplineData as docs_json_ts_0_3_7_7_classes_base_has_mSplineData,
	has_mStackHeight as docs_json_ts_0_3_7_7_classes_base_has_mStackHeight,
	has_mUseStaticHeight as docs_json_ts_0_3_7_7_classes_base_has_mUseStaticHeight,
	has_mWidth as docs_json_ts_0_3_7_7_classes_base_has_mWidth,
} from './../../0.3.7.7/classes/Base.ts';

import type {
	FGBuildable_base_version_specific as docs_json_ts_0_4_2_11_classes_base_FGBuildable_base_version_specific,
	FGBuildable_docking_station_base as docs_json_ts_0_4_2_11_classes_base_FGBuildable_docking_station_base,
	FGBuildable_has_mCachedSkeletalMeshes as docs_json_ts_0_4_2_11_classes_base_FGBuildable_has_mCachedSkeletalMeshes,
	FGBuildable_light_related_thing_base as docs_json_ts_0_4_2_11_classes_base_FGBuildable_light_related_thing_base,
	FGBuildable_mStopped_audio_stuff as docs_json_ts_0_4_2_11_classes_base_FGBuildable_mStopped_audio_stuff,
	FGBuildable_powered_has_mAllowedResourceForms_base as docs_json_ts_0_4_2_11_classes_base_FGBuildable_powered_has_mAllowedResourceForms_base,
	FGBuildable_powered_has_mAllowedResourceForms_with_resources_base as docs_json_ts_0_4_2_11_classes_base_FGBuildable_powered_has_mAllowedResourceForms_with_resources_base,
	FGBuildable_powered_storage_base as docs_json_ts_0_4_2_11_classes_base_FGBuildable_powered_storage_base,
	FGBuildableCircuitSwitch_base as docs_json_ts_0_4_2_11_classes_base_FGBuildableCircuitSwitch_base,
	FGBuildableDroneStation_pre_1_0 as docs_json_ts_0_4_2_11_classes_base_FGBuildableDroneStation_pre_1_0,
	FGBuildableDroneStation_version_specific as docs_json_ts_0_4_2_11_classes_base_FGBuildableDroneStation_version_specific,
	FGBuildableFloodlight_version_specific as docs_json_ts_0_4_2_11_classes_base_FGBuildableFloodlight_version_specific,
	FGBuildableFrackingActivator_base as docs_json_ts_0_4_2_11_classes_base_FGBuildableFrackingActivator_base,
	FGBuildableGeneratorFuel_base_base as docs_json_ts_0_4_2_11_classes_base_FGBuildableGeneratorFuel_base_base,
	FGBuildableGeneratorGeoThermal_base as docs_json_ts_0_4_2_11_classes_base_FGBuildableGeneratorGeoThermal_base,
	FGBuildableGeneratorNuclear_pre_1_0 as docs_json_ts_0_4_2_11_classes_base_FGBuildableGeneratorNuclear_pre_1_0,
	FGBuildableGeneratorNuclear_version_specific as docs_json_ts_0_4_2_11_classes_base_FGBuildableGeneratorNuclear_version_specific,
	FGBuildableLightsControlPanel_version_specific as docs_json_ts_0_4_2_11_classes_base_FGBuildableLightsControlPanel_version_specific,
	FGBuildableLightSource_version_specific as docs_json_ts_0_4_2_11_classes_base_FGBuildableLightSource_version_specific,
	FGBuildableMAM_version_specific as docs_json_ts_0_4_2_11_classes_base_FGBuildableMAM_version_specific,
	FGBuildableManufacturer_base_blender_base as docs_json_ts_0_4_2_11_classes_base_FGBuildableManufacturer_base_blender_base,
	FGBuildableManufacturer_base_constructor_base as docs_json_ts_0_4_2_11_classes_base_FGBuildableManufacturer_base_constructor_base,
	FGBuildableManufacturer_Build_HadronCollider_C_base as docs_json_ts_0_4_2_11_classes_base_FGBuildableManufacturer_Build_HadronCollider_C_base,
	FGBuildableManufacturerVariablePower as docs_json_ts_0_4_2_11_classes_base_FGBuildableManufacturerVariablePower,
	FGBuildablePipelineJunction_base_base as docs_json_ts_0_4_2_11_classes_base_FGBuildablePipelineJunction_base_base,
	FGBuildablePowerStorage_base as docs_json_ts_0_4_2_11_classes_base_FGBuildablePowerStorage_base,
	FGBuildableRailroadTrack_base_base as docs_json_ts_0_4_2_11_classes_base_FGBuildableRailroadTrack_base_base,
	FGBuildableResourceExtractor_miner_mk1_base_base as docs_json_ts_0_4_2_11_classes_base_FGBuildableResourceExtractor_miner_mk1_base_base,
	FGBuildableResourceExtractor_water_base as docs_json_ts_0_4_2_11_classes_base_FGBuildableResourceExtractor_water_base,
	FGBuildableResourceSink_base as docs_json_ts_0_4_2_11_classes_base_FGBuildableResourceSink_base,
	FGBuildableTradingPost_base as docs_json_ts_0_4_2_11_classes_base_FGBuildableTradingPost_base,
	FGBuildableTradingPost_base_pre_1_0 as docs_json_ts_0_4_2_11_classes_base_FGBuildableTradingPost_base_pre_1_0,
	FGBuildableTradingPost_base_version_specific as docs_json_ts_0_4_2_11_classes_base_FGBuildableTradingPost_base_version_specific,
	FGDescriptor_base as docs_json_ts_0_4_2_11_classes_base_FGDescriptor_base,
	FGDescriptor_BuildMenu_base as docs_json_ts_0_4_2_11_classes_base_FGDescriptor_BuildMenu_base,
	FGDescriptor_sinkable as docs_json_ts_0_4_2_11_classes_base_FGDescriptor_sinkable,
	FGSchematic_has_mMenuPriority as docs_json_ts_0_4_2_11_classes_base_FGSchematic_has_mMenuPriority,
	FGSchematic_has_mTechTier as docs_json_ts_0_4_2_11_classes_base_FGSchematic_has_mTechTier,
	FGVehicleDescriptor_fueled_with_inventory as docs_json_ts_0_4_2_11_classes_base_FGVehicleDescriptor_fueled_with_inventory,
	FGVehicleDescriptor_powered as docs_json_ts_0_4_2_11_classes_base_FGVehicleDescriptor_powered,
	FGVehicleDescriptor_with_inventory as docs_json_ts_0_4_2_11_classes_base_FGVehicleDescriptor_with_inventory,
	FGWeaponProjectile_base as docs_json_ts_0_4_2_11_classes_base_FGWeaponProjectile_base,
	FGWeaponProjectileFire_has_mMuteDryFire as docs_json_ts_0_4_2_11_classes_base_FGWeaponProjectileFire_has_mMuteDryFire,
	has_mHasPower as docs_json_ts_0_4_2_11_classes_base_has_mHasPower,
	has_mPowerConsumption as docs_json_ts_0_4_2_11_classes_base_has_mPowerConsumption,
} from './../../0.4.2.11/classes/Base.ts';

import type {
	FalloffCurve_EditorCurveData_only as docs_json_ts_0_5_2_1_properties_FalloffCurve_EditorCurveData_only,
	FGBuildableManufacturer_Build_ConstructorMk1_C_CurrentPotentialConvert_item as docs_json_ts_0_5_2_1_properties_FGBuildableManufacturer_Build_ConstructorMk1_C_CurrentPotentialConvert_item,
	mDisableSnapOn_bottom as docs_json_ts_0_5_2_1_properties_mDisableSnapOn_bottom,
	mDisableSnapOn_top as docs_json_ts_0_5_2_1_properties_mDisableSnapOn_top,
	mDockingRuleSet as docs_json_ts_0_5_2_1_properties_mDockingRuleSet,
} from './../types/properties.ts';

import type {
	Class_quoted as docs_json_ts_0_3_7_7_properties_Class_quoted,
	mDisableSnapOn_front_bottom as docs_json_ts_0_3_7_7_properties_mDisableSnapOn_front_bottom,
	mDisableSnapOn_top_bottom as docs_json_ts_0_3_7_7_properties_mDisableSnapOn_top_bottom,
	transform_Rotation_Translation_Scale3D as docs_json_ts_0_3_7_7_properties_transform_Rotation_Translation_Scale3D,
} from './../../0.3.7.7/types/properties.ts';

import type {
	FGBuildable_occupied as docs_json_ts_common_classes_FGBuildable_occupied,
	FGBuildable_tiered as docs_json_ts_common_classes_FGBuildable_tiered,
	FGBuildable_unoccupied_and_untiered as docs_json_ts_common_classes_FGBuildable_unoccupied_and_untiered,
	FGBuildableAttachmentMerger as docs_json_ts_common_classes_FGBuildableAttachmentMerger,
	FGBuildableAttachmentSplitter as docs_json_ts_common_classes_FGBuildableAttachmentSplitter,
	FGBuildableBeam as docs_json_ts_common_classes_FGBuildableBeam,
	FGBuildableCircuitSwitch as docs_json_ts_common_classes_FGBuildableCircuitSwitch,
	FGBuildableConveyorBelt as docs_json_ts_common_classes_FGBuildableConveyorBelt,
	FGBuildableConveyorLift as docs_json_ts_common_classes_FGBuildableConveyorLift,
	FGBuildableCornerWall as docs_json_ts_common_classes_FGBuildableCornerWall,
	FGBuildableDockingStation as docs_json_ts_common_classes_FGBuildableDockingStation,
	FGBuildableDoor as docs_json_ts_common_classes_FGBuildableDoor,
	FGBuildableDroneStation as docs_json_ts_common_classes_FGBuildableDroneStation,
	FGBuildableFactory as docs_json_ts_common_classes_FGBuildableFactory,
	FGBuildableFactoryBuilding as docs_json_ts_common_classes_FGBuildableFactoryBuilding,
	FGBuildableFactorySimpleProducer as docs_json_ts_common_classes_FGBuildableFactorySimpleProducer,
	FGBuildableFloodlight as docs_json_ts_common_classes_FGBuildableFloodlight,
	FGBuildableFoundation as docs_json_ts_common_classes_FGBuildableFoundation,
	FGBuildableFrackingActivator as docs_json_ts_common_classes_FGBuildableFrackingActivator,
	FGBuildableFrackingExtractor as docs_json_ts_common_classes_FGBuildableFrackingExtractor,
	FGBuildableGeneratorFuel as docs_json_ts_common_classes_FGBuildableGeneratorFuel,
	FGBuildableGeneratorGeoThermal as docs_json_ts_common_classes_FGBuildableGeneratorGeoThermal,
	FGBuildableGeneratorNuclear as docs_json_ts_common_classes_FGBuildableGeneratorNuclear,
	FGBuildableJumppad as docs_json_ts_common_classes_FGBuildableJumppad,
	FGBuildableLadder as docs_json_ts_common_classes_FGBuildableLadder,
	FGBuildableLightsControlPanel as docs_json_ts_common_classes_FGBuildableLightsControlPanel,
	FGBuildableLightSource as docs_json_ts_common_classes_FGBuildableLightSource,
	FGBuildableMAM as docs_json_ts_common_classes_FGBuildableMAM,
	FGBuildableManufacturer as docs_json_ts_common_classes_FGBuildableManufacturer,
	FGBuildableManufacturerVariablePower as docs_json_ts_common_classes_FGBuildableManufacturerVariablePower,
	FGBuildablePassthrough as docs_json_ts_common_classes_FGBuildablePassthrough,
	FGBuildablePillar as docs_json_ts_common_classes_FGBuildablePillar,
	FGBuildablePipeHyper as docs_json_ts_common_classes_FGBuildablePipeHyper,
	FGBuildablePipeline as docs_json_ts_common_classes_FGBuildablePipeline,
	FGBuildablePipelineJunction as docs_json_ts_common_classes_FGBuildablePipelineJunction,
	FGBuildablePipelinePump as docs_json_ts_common_classes_FGBuildablePipelinePump,
	FGBuildablePipelineSupport as docs_json_ts_common_classes_FGBuildablePipelineSupport,
	FGBuildablePipeReservoir as docs_json_ts_common_classes_FGBuildablePipeReservoir,
	FGBuildablePole as docs_json_ts_common_classes_FGBuildablePole,
	FGBuildablePowerPole as docs_json_ts_common_classes_FGBuildablePowerPole,
	FGBuildablePowerStorage as docs_json_ts_common_classes_FGBuildablePowerStorage,
	FGBuildableRadarTower as docs_json_ts_common_classes_FGBuildableRadarTower,
	FGBuildableRailroadSignal_block as docs_json_ts_common_classes_FGBuildableRailroadSignal_block,
	FGBuildableRailroadSignal_path as docs_json_ts_common_classes_FGBuildableRailroadSignal_path,
	FGBuildableRailroadStation as docs_json_ts_common_classes_FGBuildableRailroadStation,
	FGBuildableRailroadTrack as docs_json_ts_common_classes_FGBuildableRailroadTrack,
	FGBuildableRamp as docs_json_ts_common_classes_FGBuildableRamp,
	FGBuildableResourceExtractor as docs_json_ts_common_classes_FGBuildableResourceExtractor,
	FGBuildableResourceSink as docs_json_ts_common_classes_FGBuildableResourceSink,
	FGBuildableResourceSinkShop as docs_json_ts_common_classes_FGBuildableResourceSinkShop,
	FGBuildableSnowDispenser as docs_json_ts_common_classes_FGBuildableSnowDispenser,
	FGBuildableSpaceElevator as docs_json_ts_common_classes_FGBuildableSpaceElevator,
	FGBuildableSplitterSmart as docs_json_ts_common_classes_FGBuildableSplitterSmart,
	FGBuildableStair as docs_json_ts_common_classes_FGBuildableStair,
	FGBuildableStorage as docs_json_ts_common_classes_FGBuildableStorage,
	FGBuildableTradingPost as docs_json_ts_common_classes_FGBuildableTradingPost,
	FGBuildableTrainPlatformCargo as docs_json_ts_common_classes_FGBuildableTrainPlatformCargo,
	FGBuildableTrainPlatformEmpty as docs_json_ts_common_classes_FGBuildableTrainPlatformEmpty,
	FGBuildableWalkway as docs_json_ts_common_classes_FGBuildableWalkway,
	FGBuildableWall as docs_json_ts_common_classes_FGBuildableWall,
	FGBuildableWidgetSign as docs_json_ts_common_classes_FGBuildableWidgetSign,
	FGBuildableWire as docs_json_ts_common_classes_FGBuildableWire,
	FGBuildingDescriptor as docs_json_ts_common_classes_FGBuildingDescriptor,
	FGConsumableDescriptor as docs_json_ts_common_classes_FGConsumableDescriptor,
	FGConveyorPoleStackable as docs_json_ts_common_classes_FGConveyorPoleStackable,
	FGEquipmentDescriptor as docs_json_ts_common_classes_FGEquipmentDescriptor,
	FGGolfCartDispenser as docs_json_ts_common_classes_FGGolfCartDispenser,
	FGItemDescAmmoTypeColorCartridge as docs_json_ts_common_classes_FGItemDescAmmoTypeColorCartridge,
	FGItemDescAmmoTypeInstantHit as docs_json_ts_common_classes_FGItemDescAmmoTypeInstantHit,
	FGItemDescAmmoTypeProjectile as docs_json_ts_common_classes_FGItemDescAmmoTypeProjectile,
	FGItemDescriptor as docs_json_ts_common_classes_FGItemDescriptor,
	FGItemDescriptorBiomass as docs_json_ts_common_classes_FGItemDescriptorBiomass,
	FGNobeliskDetonator as docs_json_ts_common_classes_FGNobeliskDetonator,
	FGPipeHyperStart as docs_json_ts_common_classes_FGPipeHyperStart,
	FGPoleDescriptor as docs_json_ts_common_classes_FGPoleDescriptor,
	FGResourceDescriptor as docs_json_ts_common_classes_FGResourceDescriptor,
	FGSchematic as docs_json_ts_common_classes_FGSchematic,
	FGVehicleDescriptor as docs_json_ts_common_classes_FGVehicleDescriptor,
	FGWeapon_Equip_RebarGun_Projectile_C as docs_json_ts_common_classes_FGWeapon_Equip_RebarGun_Projectile_C,
	FGWeapon_Equip_Rifle_C as docs_json_ts_common_classes_FGWeapon_Equip_Rifle_C,
} from './../../common/classes.ts';

import type {
	FGBuildable_is_wallish as docs_json_ts_0_5_2_1_classes_base_overridable_FGBuildable_is_wallish,
	FGSchematic_version_specific as docs_json_ts_0_5_2_1_classes_base_overridable_FGSchematic_version_specific,
	FGWeapon_version_specific as docs_json_ts_0_5_2_1_classes_base_overridable_FGWeapon_version_specific,
} from './Base.overridable.ts';

import type {
	has_mBatteryClasses as docs_json_ts_0_4_2_11_overridable_has_mBatteryClasses,
} from './../../0.4.2.11/types/overridable.ts';

import type {
	FGBuildableResourceExtractor_miner_base as docs_json_ts_0_3_7_7_classes_base_overridable_FGBuildableResourceExtractor_miner_base,
	FGBuildableResourceExtractor_only_allow_certain_resources as docs_json_ts_0_3_7_7_classes_base_overridable_FGBuildableResourceExtractor_only_allow_certain_resources,
	FGSchematic_version_specific as docs_json_ts_0_3_7_7_classes_base_overridable_FGSchematic_version_specific,
} from './../../0.3.7.7/classes/Base.overridable.ts';

import type {
	Texture2D as docs_json_ts_0_4_2_11_properties_Texture2D,
} from './../../0.4.2.11/types/properties.ts';

import type {
	FalloffCurve_EditorCurveData_with_ExternalCurve as docs_json_ts_0_5_2_1_overridable_FalloffCurve_EditorCurveData_with_ExternalCurve,
	mUnlocks_item as docs_json_ts_0_5_2_1_overridable_mUnlocks_item,
} from './../types/overridable.ts';

import type {
	BlueprintGeneratedClass_quoted as docs_json_ts_0_3_7_7_overridable_BlueprintGeneratedClass_quoted,
} from './../../0.3.7.7/types/overridable.ts';

import type {
	FGSchematic_base as docs_json_ts_0_4_2_11_classes_base_overridable_FGSchematic_base,
	FGSchematic_has_mSchematicIcon as docs_json_ts_0_4_2_11_classes_base_overridable_FGSchematic_has_mSchematicIcon,
} from './../../0.4.2.11/classes/Base.overridable.ts';

import type {
	isDescribed as docs_json_ts_common_classes_base_isDescribed,
} from './../../common/classes/Base.ts';

type has_mIsSupport = {
	mIsSupport: docs_json_ts_common_types_bool_string,
};

type has_mSize_vector = {
	mSize: docs_json_ts_common_types_XYZ_decimal_string,
};

type has_mSplineData = docs_json_ts_0_3_7_7_classes_base_has_mMeshLength & docs_json_ts_0_3_7_7_classes_base_has_mSplineData & FGBuildable_base & FGBuildable_mSnappedPassthroughs;

type FGBuildable_base = docs_json_ts_0_3_7_7_classes_base_FGBuildable_base_pre_1_0 & docs_json_ts_0_3_7_7_classes_base_FGBuildable_base_version_specific & docs_json_ts_0_4_2_11_classes_base_FGBuildable_base_version_specific & FGBuildable_base_pre_1_0 & FGBuildable_base_version_specific;

type FGBuildable_base_pre_1_0 = {
	mCreateClearanceMeshRepresentation: docs_json_ts_common_types_bool_string,
};

type FGBuildable_base_version_specific = {
	mAllowColoring: docs_json_ts_common_types_bool_string,
	mShouldShowAttachmentPointVisuals: docs_json_ts_common_types_bool_string,
	mAttachmentPoints: '',
};

type FGBuildable_docking_station = docs_json_ts_0_4_2_11_classes_base_FGBuildable_docking_station_base & FGBuildable_powered_storage;

type FGBuildable_foundation_DisableAttachmentSnapOn = FGBuildable_base & {
	mDisableAttachmentSnapOn: docs_json_ts_common_types_empty_object | docs_json_ts_0_5_2_1_properties_mDisableSnapOn_top | docs_json_ts_0_5_2_1_properties_mDisableSnapOn_bottom,
};

type FGBuildable_foundation_mDisableSnapOn = FGBuildable_base & {
	mDisableSnapOn: docs_json_ts_common_types_empty_object | docs_json_ts_0_3_7_7_properties_mDisableSnapOn_front_bottom | docs_json_ts_0_5_2_1_properties_mDisableSnapOn_top | docs_json_ts_0_5_2_1_properties_mDisableSnapOn_bottom,
};

type FGBuildable_isFrame = {
	mIsFrame: docs_json_ts_common_types_bool_string,
};

type FGBuildable_mSnappedPassthroughs = {
	mSnappedPassthroughs: '',
};

type FGBuildable_occupied = docs_json_ts_0_3_7_7_classes_base_FGBuildable_occupied_base & docs_json_ts_common_classes_FGBuildable_occupied & FGBuildable_base;

type FGBuildable_powered = docs_json_ts_0_3_7_7_classes_base_FGBuildable_powered_pre_1_0 & docs_json_ts_0_3_7_7_classes_base_FGBuildable_powered_version_specific & docs_json_ts_0_3_7_7_classes_base_has_mNumCyclesForProductivity & docs_json_ts_0_4_2_11_classes_base_FGBuildable_has_mCachedSkeletalMeshes & FGBuildable_base & FGBuildable_powered_base_base;

type FGBuildable_powered_base_base = {
	mDoesHaveShutdownAnimation: docs_json_ts_common_types_bool_string,
};

type FGBuildable_powered_storage = docs_json_ts_0_4_2_11_classes_base_FGBuildable_powered_storage_base & FGBuildable_powered;

type FGBuildable_ramp_DisableAttachmentSnapOn = FGBuildable_base & {
	mDisableAttachmentSnapOn: docs_json_ts_common_types_empty_object | docs_json_ts_0_3_7_7_properties_mDisableSnapOn_top_bottom | docs_json_ts_0_5_2_1_properties_mDisableSnapOn_top | docs_json_ts_0_5_2_1_properties_mDisableSnapOn_bottom,
};

type FGBuildable_ramp_mDisableSnapOn = {
	mDisableSnapOn: docs_json_ts_0_3_7_7_properties_mDisableSnapOn_top_bottom | docs_json_ts_0_3_7_7_properties_mDisableSnapOn_front_bottom | docs_json_ts_0_5_2_1_properties_mDisableSnapOn_top | docs_json_ts_0_5_2_1_properties_mDisableSnapOn_bottom,
};

type FGBuildable_tiered = docs_json_ts_0_3_7_7_classes_base_FGBuildable_tiered_base & docs_json_ts_common_classes_FGBuildable_tiered & FGBuildable_base;

type FGBuildable_unoccupied_and_untiered = docs_json_ts_common_classes_FGBuildable_unoccupied_and_untiered & FGBuildable_base;

type FGBuildable_with_height = docs_json_ts_0_3_7_7_classes_base_has_mHeight & FGBuildable_base;

type FGBuildableAttachment = docs_json_ts_0_3_7_7_classes_base_FGBuildable_powered_pre_1_0 & docs_json_ts_0_3_7_7_classes_base_FGBuildable_powered_version_specific & docs_json_ts_0_3_7_7_classes_base_FGBuildableAttachment_has_mCurrentInventoryIndex & docs_json_ts_0_3_7_7_classes_base_has_mNumCyclesForProductivity & FGBuildable_powered;

type FGBuildableAttachment_splitter = docs_json_ts_0_3_7_7_classes_base_FGBuildable_powered_pre_1_0 & docs_json_ts_0_3_7_7_classes_base_FGBuildable_powered_version_specific & docs_json_ts_0_3_7_7_classes_base_FGBuildableAttachment_has_mCurrentInventoryIndex & docs_json_ts_0_3_7_7_classes_base_FGBuildableAttachment_splitter_base_base_base & docs_json_ts_0_3_7_7_classes_base_has_mNumCyclesForProductivity & FGBuildableAttachment;

type FGBuildableAttachmentMerger = docs_json_ts_0_3_7_7_classes_base_FGBuildable_powered_pre_1_0 & docs_json_ts_0_3_7_7_classes_base_FGBuildable_powered_version_specific & docs_json_ts_0_3_7_7_classes_base_FGBuildableAttachment_has_mCurrentInventoryIndex & docs_json_ts_0_3_7_7_classes_base_FGBuildableAttachmentMerger_version_specific & docs_json_ts_0_3_7_7_classes_base_has_mNumCyclesForProductivity & docs_json_ts_common_classes_FGBuildableAttachmentMerger & FGBuildableAttachment;

type FGBuildableAttachmentSplitter = docs_json_ts_common_classes_FGBuildableAttachmentSplitter & FGBuildableAttachment_splitter;

type FGBuildableBeam = docs_json_ts_0_3_7_7_classes_base_has_mSize & docs_json_ts_common_classes_FGBuildableBeam & FGBuildable_base & FGBuildableBeam_version_specific;

type FGBuildableBeam_version_specific = {
	mDefaultLength: docs_json_ts_common_types_decimal_string,
	mMaxLength: docs_json_ts_common_types_decimal_string,
	mLength: docs_json_ts_common_types_decimal_string,
};

type FGBuildableCircuitSwitch = docs_json_ts_0_4_2_11_classes_base_FGBuildableCircuitSwitch_base & docs_json_ts_common_classes_FGBuildableCircuitSwitch & FGBuildable_base;

type FGBuildableConveyorBelt = docs_json_ts_0_3_7_7_classes_base_FGBuildableConveyorBelt_pre_1_0 & docs_json_ts_0_3_7_7_classes_base_FGBuildableConveyorBelt_pre_update8 & docs_json_ts_0_3_7_7_classes_base_has_mMeshLength & docs_json_ts_0_3_7_7_classes_base_has_mSplineData & docs_json_ts_common_classes_FGBuildableConveyorBelt & FGBuildable_base & FGBuildableConveyorBelt_version_specific;

type FGBuildableConveyorBelt_version_specific = {
	mCustomSkins: [
		'/Game/FactoryGame/Buildable/-Shared/Customization/Skins/SkinDesc_Test1.SkinDesc_Test1_C',
	],
};

type FGBuildableConveyorLift = docs_json_ts_0_3_7_7_classes_base_FGBuildableConveyorBelt_pre_1_0 & docs_json_ts_0_3_7_7_classes_base_FGBuildableConveyorBelt_pre_update8 & docs_json_ts_0_3_7_7_classes_base_FGBuildableConveyorLift_base & docs_json_ts_common_classes_FGBuildableConveyorLift & FGBuildable_base & FGBuildable_mSnappedPassthroughs;

type FGBuildableCornerWall = docs_json_ts_0_3_7_7_classes_base_has_mSize & docs_json_ts_common_classes_FGBuildableCornerWall & FGBuildable_with_height;

type FGBuildableDockingStation = docs_json_ts_common_classes_FGBuildableDockingStation & FGBuildableDockingStation_base & FGBuildableDockingStation_base_base;

type FGBuildableDockingStation_base = docs_json_ts_0_3_7_7_classes_base_FGBuildable_docking_station_base_base_base & {
	VehicleFuelConsumptionRateChangedDelegate: docs_json_ts_common_types_empty_object,
	ItemTransferRateChangedDelegate: docs_json_ts_common_types_empty_object,
	MaximumStackTransferRateChangedDelegate: docs_json_ts_common_types_empty_object,
	mDockPosition: docs_json_ts_common_types_XY_decimal_string,
	mMinimumDockingTime: docs_json_ts_common_types_decimal_string,
	mFuelInventorySizeX: docs_json_ts_common_types_integer_string,
	mFuelInventorySizeY: docs_json_ts_common_types_integer_string,
	mForceSignificance: docs_json_ts_common_types_bool_string,
	mVehicleFuelConsumptionRate: docs_json_ts_common_types_decimal_string,
	mItemTransferRate: docs_json_ts_common_types_decimal_string,
	mMaximumStackTransferRate: docs_json_ts_common_types_decimal_string,
	mDockingVehicleStatistics: docs_json_ts_common_types_empty_object,
};

type FGBuildableDockingStation_base_base = docs_json_ts_0_3_7_7_classes_base_FGBuildableDockingStation_base_base & FGBuildable_docking_station;

type FGBuildableDoor = FGBuildableDoor_manual | FGBuildableDoor_automated;

type FGBuildableDoor_automated = docs_json_ts_0_5_2_1_classes_base_overridable_FGBuildable_is_wallish & docs_json_ts_0_3_7_7_classes_base_has_mElevation & docs_json_ts_0_3_7_7_classes_base_has_mHeight & docs_json_ts_0_3_7_7_classes_base_has_mWidth & docs_json_ts_common_classes_FGBuildableDoor & FGBuildable_base & FGBuildableDoor_automated_version_specific & FGBuildableDoor_base;

type FGBuildableDoor_automated_version_specific = {
	bigOverlapList: '',
};

type FGBuildableDoor_base = {
	mCanBeLocked: docs_json_ts_common_types_bool_string,
	mAnimationRate: docs_json_ts_common_types_decimal_string,
	mMovementRate: docs_json_ts_common_types_decimal_string,
	EasingFunction: 'ExpoInOut' | 'Linear',
	BlendExp: docs_json_ts_common_types_decimal_string,
	Steps: docs_json_ts_common_types_integer_string,
};

type FGBuildableDoor_manual = docs_json_ts_0_5_2_1_classes_base_overridable_FGBuildable_is_wallish & docs_json_ts_0_3_7_7_classes_base_has_mElevation & docs_json_ts_0_3_7_7_classes_base_has_mHeight & docs_json_ts_0_3_7_7_classes_base_has_mWidth & docs_json_ts_common_classes_FGBuildableDoor & FGBuildable_base & FGBuildableDoor_base & FGBuildableDoor_manual_version_specific;

type FGBuildableDoor_manual_version_specific = {
	IsDoorOpen: docs_json_ts_common_types_bool_string,
};

type FGBuildableDroneStation = docs_json_ts_0_4_2_11_classes_base_FGBuildable_docking_station_base & docs_json_ts_0_4_2_11_classes_base_FGBuildableDroneStation_pre_1_0 & docs_json_ts_0_4_2_11_classes_base_FGBuildableDroneStation_version_specific & docs_json_ts_0_4_2_11_overridable_has_mBatteryClasses & docs_json_ts_common_classes_FGBuildableDroneStation & FGBuildable_docking_station;

type FGBuildableFactory_jump_pad = docs_json_ts_0_3_7_7_classes_base_FGBuildableFactory_jump_pad_base_base & docs_json_ts_common_classes_FGBuildableFactory & FGBuildable_powered;

type FGBuildableFactory_landing_pad = docs_json_ts_0_3_7_7_classes_base_FGBuildableFactory_landing_pad_base_base & docs_json_ts_common_classes_FGBuildableFactory & FGBuildable_powered;

type FGBuildableFactory_not_pad = docs_json_ts_common_classes_FGBuildableFactory & FGBuildable_powered;

type FGBuildableFactoryBuilding = docs_json_ts_common_classes_FGBuildableFactoryBuilding & FGBuildable_base;

type FGBuildableFactorySimpleProducer = docs_json_ts_0_3_7_7_classes_base_FGBuildableFactorySimpleProducer_base_base & docs_json_ts_common_classes_FGBuildableFactorySimpleProducer & FGBuildable_powered;

type FGBuildableFloodlight = docs_json_ts_0_4_2_11_classes_base_FGBuildable_light_related_thing_base & docs_json_ts_0_4_2_11_classes_base_FGBuildableFloodlight_version_specific & docs_json_ts_0_4_2_11_classes_base_FGBuildableLightSource_version_specific & docs_json_ts_0_4_2_11_classes_base_has_mHasPower & docs_json_ts_0_4_2_11_classes_base_has_mPowerConsumption & docs_json_ts_common_classes_FGBuildableFloodlight & FGBuildable_base & FGBuildableLightSource_base;

type FGBuildableFoundation = docs_json_ts_0_3_7_7_classes_base_has_mElevation & docs_json_ts_0_3_7_7_classes_base_has_mSize & docs_json_ts_common_classes_FGBuildableFoundation & FGBuildable_base & FGBuildableFoundation_base;

type FGBuildableFoundation_base = FGBuildableFoundation_base_base & {
	mDisableSnapOn: docs_json_ts_common_types_empty_object | docs_json_ts_0_3_7_7_properties_mDisableSnapOn_front_bottom | docs_json_ts_0_5_2_1_properties_mDisableSnapOn_top | docs_json_ts_0_5_2_1_properties_mDisableSnapOn_bottom,
};

type FGBuildableFoundation_base_base = docs_json_ts_0_3_7_7_classes_base_has_mHeight & FGBuildable_base & FGBuildable_foundation_DisableAttachmentSnapOn & FGBuildable_foundation_mDisableSnapOn & FGBuildable_isFrame;

type FGBuildableFrackingActivator = docs_json_ts_0_4_2_11_classes_base_FGBuildable_powered_has_mAllowedResourceForms_with_resources_base & docs_json_ts_0_4_2_11_classes_base_FGBuildableFrackingActivator_base & docs_json_ts_common_classes_FGBuildableFrackingActivator & FGBuildable_powered;

type FGBuildableFrackingExtractor = docs_json_ts_common_classes_FGBuildableFrackingExtractor & FGBuildable_powered & FGBuildableResourceExtractor_base;

type FGBuildableGenerator = docs_json_ts_0_3_7_7_classes_base_FGBuildableGenerator_base_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableGenerator_base_base_pre_1_0 & docs_json_ts_0_3_7_7_classes_base_FGBuildableGenerator_no_fuel_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableGenerator_no_fuel_base_base_base_base & FGBuildableGenerator_no_fuel;

type FGBuildableGenerator_no_fuel = docs_json_ts_0_3_7_7_classes_base_FGBuildableGenerator_no_fuel_base_base & FGBuildable_powered;

type FGBuildableGeneratorFuel_biomass = docs_json_ts_0_3_7_7_classes_base_FGBuildableGeneratorFuel_biomass_base_base & docs_json_ts_0_4_2_11_classes_base_FGBuildableGeneratorFuel_base_base & docs_json_ts_common_classes_FGBuildableGeneratorFuel & FGBuildableGenerator;

type FGBuildableGeneratorFuel_coal = docs_json_ts_0_3_7_7_classes_base_FGBuildableGeneratorFuel_coal_base_base & docs_json_ts_0_4_2_11_classes_base_FGBuildableGeneratorFuel_base_base & docs_json_ts_common_classes_FGBuildableGeneratorFuel & FGBuildableGenerator;

type FGBuildableGeneratorFuel_fuel = docs_json_ts_0_3_7_7_classes_base_FGBuildableGeneratorFuel_fuel_base_base & docs_json_ts_0_4_2_11_classes_base_FGBuildableGeneratorFuel_base_base & docs_json_ts_common_classes_FGBuildableGeneratorFuel & FGBuildableGenerator;

type FGBuildableGeneratorGeoThermal = docs_json_ts_0_3_7_7_classes_base_FGBuildableGeneratorGeoThermal_base_base & docs_json_ts_0_4_2_11_classes_base_FGBuildableGeneratorGeoThermal_base & docs_json_ts_common_classes_FGBuildableGeneratorGeoThermal & FGBuildableGenerator_no_fuel;

type FGBuildableGeneratorNuclear = docs_json_ts_0_3_7_7_classes_base_FGBuildableGenerator_no_fuel_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableGenerator_no_fuel_base_base_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableGeneratorNuclear_version_specific & docs_json_ts_0_4_2_11_classes_base_FGBuildableGeneratorFuel_base_base & docs_json_ts_0_4_2_11_classes_base_FGBuildableGeneratorNuclear_pre_1_0 & docs_json_ts_0_4_2_11_classes_base_FGBuildableGeneratorNuclear_version_specific & docs_json_ts_common_classes_FGBuildableGeneratorNuclear & FGBuildableGenerator;

type FGBuildableJumppad = docs_json_ts_0_3_7_7_classes_base_FGBuildableJumppad_base_base & docs_json_ts_common_classes_FGBuildableJumppad & FGBuildable_powered;

type FGBuildableLadder = docs_json_ts_0_3_7_7_classes_base_FGBuildableLadder_base & docs_json_ts_0_3_7_7_classes_base_has_mWidth & docs_json_ts_common_classes_FGBuildableLadder & FGBuildable_base;

type FGBuildableLightsControlPanel = docs_json_ts_0_4_2_11_classes_base_FGBuildable_light_related_thing_base & docs_json_ts_0_4_2_11_classes_base_FGBuildableLightsControlPanel_version_specific & docs_json_ts_common_classes_FGBuildableLightsControlPanel & FGBuildable_base & FGBuildableLightsControlPanel_version_specific;

type FGBuildableLightsControlPanel_version_specific = {
	OnLightControlPanelStateChanged: docs_json_ts_common_types_empty_object,
};

type FGBuildableLightSource_base = {
	OnBuildableLightSourceStateChanged: docs_json_ts_common_types_empty_object,
};

type FGBuildableLightSource_Build_CeilingLight_C = docs_json_ts_0_4_2_11_classes_base_FGBuildable_light_related_thing_base & docs_json_ts_0_4_2_11_classes_base_FGBuildableLightSource_version_specific & docs_json_ts_0_4_2_11_classes_base_has_mHasPower & docs_json_ts_0_4_2_11_classes_base_has_mPowerConsumption & docs_json_ts_common_classes_FGBuildableLightSource & FGBuildable_base & FGBuildableLightSource_base;

type FGBuildableLightSource_Build_StreetLight_C = docs_json_ts_0_4_2_11_classes_base_FGBuildable_light_related_thing_base & docs_json_ts_0_4_2_11_classes_base_FGBuildableLightSource_version_specific & docs_json_ts_0_4_2_11_classes_base_has_mHasPower & docs_json_ts_0_4_2_11_classes_base_has_mPowerConsumption & docs_json_ts_common_classes_FGBuildableLightSource & FGBuildable_base & FGBuildableLightSource_base & FGBuildableLightSource_Build_StreetLight_C_version_specific;

type FGBuildableLightSource_Build_StreetLight_C_version_specific = {
	newCustomizationData: {
		OverrideColorData: {
			PrimaryColor: docs_json_ts_common_types_RGBA,
			SecondaryColor: docs_json_ts_common_types_RGBA,
		},
	},
};

type FGBuildableMAM = docs_json_ts_0_4_2_11_classes_base_FGBuildableMAM_version_specific & docs_json_ts_common_classes_FGBuildableMAM & FGBuildable_occupied;

type FGBuildableManufacturer_Build_AssemblerMk1_C = docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_IsPowered_base & docs_json_ts_common_classes_FGBuildableManufacturer & FGBuildable_powered;

type FGBuildableManufacturer_Build_Blender_C = docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_IsPowered_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_mProductionEffectsRunning_base & docs_json_ts_0_4_2_11_classes_base_FGBuildableManufacturer_base_blender_base & docs_json_ts_common_classes_FGBuildableManufacturer & FGBuildable_powered;

type FGBuildableManufacturer_Build_ConstructorMk1_C = docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_IsPowered_base & docs_json_ts_0_4_2_11_classes_base_FGBuildableManufacturer_base_constructor_base & docs_json_ts_common_classes_FGBuildableManufacturer & FGBuildable_powered & FGBuildableManufacturer_Build_ConstructorMk1_C_base;

type FGBuildableManufacturer_Build_ConstructorMk1_C_base = {
	CurrentPotentialConvert: docs_json_ts_0_5_2_1_properties_FGBuildableManufacturer_Build_ConstructorMk1_C_CurrentPotentialConvert_item,
};

type FGBuildableManufacturer_Build_FoundryMk1_C = docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_mProductionEffectsRunning_base & docs_json_ts_common_classes_FGBuildableManufacturer & FGBuildable_powered & FGBuildableManufacturer_Build_FoundryMk1_C_base;

type FGBuildableManufacturer_Build_FoundryMk1_C_base = {
	bIsPendingToKillVfx: docs_json_ts_common_types_bool_string,
};

type FGBuildableManufacturer_Build_HadronCollider_C = docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_IsPowered_base & docs_json_ts_0_4_2_11_classes_base_FGBuildableManufacturer_Build_HadronCollider_C_base & docs_json_ts_0_4_2_11_classes_base_FGBuildableManufacturerVariablePower & docs_json_ts_common_classes_FGBuildableManufacturerVariablePower & FGBuildable_powered;

type FGBuildableManufacturer_Build_ManufacturerMk1_C = docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_base & docs_json_ts_0_4_2_11_classes_base_FGBuildable_mStopped_audio_stuff & docs_json_ts_common_classes_FGBuildableManufacturer & FGBuildable_powered;

type FGBuildableManufacturer_Build_OilRefinery_C = docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_IsPowered_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_mProductionEffectsRunning_base & docs_json_ts_common_classes_FGBuildableManufacturer & FGBuildable_powered;

type FGBuildableManufacturer_Build_Packager_C = docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_IsPowered_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_mProductionEffectsRunning_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_packager_base & docs_json_ts_common_classes_FGBuildableManufacturer & FGBuildable_powered;

type FGBuildableManufacturer_Build_SmelterMk1_C = docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_Build_SmelterMk1_C_base & docs_json_ts_common_classes_FGBuildableManufacturer & FGBuildable_powered & FGBuildableManufacturer_Build_SmelterMk1_C_base;

type FGBuildableManufacturer_Build_SmelterMk1_C_base = {
	mIsPendingToKillVFX: docs_json_ts_common_types_bool_string,
};

type FGBuildablePassthrough = docs_json_ts_common_classes_FGBuildablePassthrough & FGBuildable_base & FGBuildablePassthrough_base & FGBuildablePassthrough_pre_update8;

type FGBuildablePassthrough_base = {
	mSnappedBuildingThickness: docs_json_ts_common_types_decimal_string,
	mMidMeshLength: docs_json_ts_common_types_decimal_string,
	mGenerateTunnelCollision: docs_json_ts_common_types_bool_string,
	mEndCapRotation: docs_json_ts_common_types_PitchYawRoll_decimal_string_signed,
	mMidMeshRotation: docs_json_ts_common_types_PitchYawRoll_decimal_string_signed,
	mEndCapTranslation: docs_json_ts_common_types_XYZ_decimal_string,
	mClearanceHeightMin: docs_json_ts_common_types_decimal_string,
	mClearanceThickness: docs_json_ts_common_types_decimal_string,
};

type FGBuildablePassthrough_pre_update8 = {
	mUseSoftClearance: docs_json_ts_common_types_bool_string,
};

type FGBuildablePillar = docs_json_ts_common_classes_FGBuildablePillar & FGBuildable_base & has_mIsSupport & has_mSize_vector;

type FGBuildablePipeHyper = docs_json_ts_common_classes_FGBuildablePipeHyper & FGBuildablePipeHyper_version_specific & has_mSplineData;

type FGBuildablePipeHyper_version_specific = {
	mExitOffset: docs_json_ts_common_types_XYZ_decimal_string,
};

type FGBuildablePipeline = docs_json_ts_0_3_7_7_classes_base_FGBuildablePipeline_base_root_quantized & docs_json_ts_common_classes_FGBuildablePipeline & FGBuildable_base & FGBuildablePipeline_base_spline;

type FGBuildablePipeline_base_spline = docs_json_ts_0_3_7_7_classes_base_FGBuildablePipeline_base_spline_base & FGBuildable_mSnappedPassthroughs;

type FGBuildablePipelineJunction = docs_json_ts_0_4_2_11_classes_base_FGBuildablePipelineJunction_base_base & docs_json_ts_common_classes_FGBuildablePipelineJunction & FGBuildable_powered;

type FGBuildablePipelinePump_pump = docs_json_ts_0_3_7_7_classes_base_FGBuildable_powered_pre_1_0 & docs_json_ts_0_3_7_7_classes_base_FGBuildable_powered_version_specific & docs_json_ts_0_3_7_7_classes_base_FGBuildablePipeline_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildablePipelinePump_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildablePipelinePump_powered_version_specific & docs_json_ts_0_3_7_7_classes_base_FGBuildablePipelinePump_pump_version_specific & docs_json_ts_0_3_7_7_classes_base_has_mNumCyclesForProductivity & docs_json_ts_common_classes_FGBuildablePipelinePump & FGBuildable_powered;

type FGBuildablePipelinePump_valve = docs_json_ts_0_3_7_7_classes_base_FGBuildablePipelinePump_base_base & docs_json_ts_common_classes_FGBuildablePipelinePump & FGBuildable_powered;

type FGBuildablePipelineSupport = docs_json_ts_0_3_7_7_classes_base_FGBuildable_with_mLength & docs_json_ts_0_3_7_7_classes_base_FGBuildablePipelineSupport_base & docs_json_ts_0_3_7_7_classes_base_has_mCanStack & docs_json_ts_0_3_7_7_classes_base_has_mStackHeight & docs_json_ts_0_3_7_7_classes_base_has_mUseStaticHeight & docs_json_ts_common_classes_FGBuildablePipelineSupport & FGBuildable_base;

type FGBuildablePipeReservoir = docs_json_ts_0_3_7_7_classes_base_FGBuildablePipeReservoir_base_base & docs_json_ts_common_classes_FGBuildablePipeReservoir & FGBuildable_powered;

type FGBuildablePole = docs_json_ts_0_3_7_7_classes_base_has_mCanStack & docs_json_ts_0_3_7_7_classes_base_has_mHeight & docs_json_ts_0_3_7_7_classes_base_has_mStackHeight & docs_json_ts_0_3_7_7_classes_base_has_mUseStaticHeight & docs_json_ts_common_classes_FGBuildablePole & FGBuildable_base;

type FGBuildablePowerPole = docs_json_ts_0_3_7_7_classes_base_FGBuildablePowerPole_base & docs_json_ts_0_4_2_11_classes_base_has_mHasPower & docs_json_ts_common_classes_FGBuildablePowerPole & FGBuildable_base;

type FGBuildablePowerStorage = docs_json_ts_0_4_2_11_classes_base_FGBuildablePowerStorage_base & docs_json_ts_common_classes_FGBuildablePowerStorage & FGBuildable_powered;

type FGBuildableRadarTower = docs_json_ts_0_3_7_7_classes_base_FGBuildableRadarTower_base_base & docs_json_ts_common_classes_FGBuildableRadarTower & FGBuildable_powered;

type FGBuildableRailroadSignal_base = FGBuildable_base & FGBuildableRailroadSignal_base_version_specific;

type FGBuildableRailroadSignal_base_version_specific = {
	mOnAspectChangedDelegate: docs_json_ts_common_types_empty_object,
	mOnBlockValidationChangedDelegate: docs_json_ts_common_types_empty_object,
	mGuardedConnections: '',
	mObservedConnections: '',
	mAspect: 'RSA_None',
	mBlockValidation: 'RBV_Unvalidated',
	mIsPathSignal: docs_json_ts_common_types_bool_string,
	mIsBiDirectional: docs_json_ts_common_types_bool_string,
	mVisualState: docs_json_ts_common_types_integer_string,
	mSignificanceRange: docs_json_ts_common_types_decimal_string,
};

type FGBuildableRailroadSignal_block = docs_json_ts_common_classes_FGBuildableRailroadSignal_block & FGBuildableRailroadSignal_base & FGBuildableRailroadSignal_block_version_specific;

type FGBuildableRailroadSignal_block_version_specific = {
	mPreviousAspect: 'RSA_None',
};

type FGBuildableRailroadSignal_path = docs_json_ts_common_classes_FGBuildableRailroadSignal_path & FGBuildableRailroadSignal_base;

type FGBuildableRailroadStation = docs_json_ts_0_3_7_7_classes_base_FGBuildableRailroadStation_base_base & docs_json_ts_common_classes_FGBuildableRailroadStation & FGBuildable_powered & FGBuildableRailroadStation_base & FGBuildableTrainPlatform_base & FGBuildableTrainPlatform_non_empty;

type FGBuildableRailroadStation_base = {
	mShouldTeleportHere: docs_json_ts_common_types_bool_string,
	mCurrentDockedWithRuleSet: docs_json_ts_0_5_2_1_properties_mDockingRuleSet,
};

type FGBuildableRailroadTrack = docs_json_ts_0_3_7_7_classes_base_has_mMeshLength & docs_json_ts_common_classes_FGBuildableRailroadTrack & FGBuildable_base & FGBuildableRailroadTrack_base & FGBuildableRailroadTrack_base_version_specific;

type FGBuildableRailroadTrack_base = docs_json_ts_0_4_2_11_classes_base_FGBuildableRailroadTrack_base_base & FGBuildable_base_pre_1_0 & FGBuildable_base_version_specific;

type FGBuildableRailroadTrack_base_version_specific = {
	mTrackGraphID: docs_json_ts_common_types_integer_string_signed,
	mOverlappingTracks: '',
	mVehicles: docs_json_ts_common_types_empty_object,
	mSignalBlockID: docs_json_ts_common_types_integer_string,
};

type FGBuildableRamp = docs_json_ts_common_classes_FGBuildableRamp & FGBuildableRamp_base & FGBuildableRamp_base_base;

type FGBuildableRamp_base = {
	mIsDoubleRamp: docs_json_ts_common_types_bool_string,
	mIsRoof: docs_json_ts_common_types_bool_string,
};

type FGBuildableRamp_base_base = docs_json_ts_0_3_7_7_classes_base_has_mElevation & docs_json_ts_0_3_7_7_classes_base_has_mHeight & docs_json_ts_0_3_7_7_classes_base_has_mSize & FGBuildable_isFrame & FGBuildable_ramp_DisableAttachmentSnapOn & FGBuildable_ramp_mDisableSnapOn;

type FGBuildableResourceExtractor_base = docs_json_ts_0_3_7_7_classes_base_overridable_FGBuildableResourceExtractor_only_allow_certain_resources & docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_piped & docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_piped_pre_1_0 & docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_timed & docs_json_ts_0_4_2_11_classes_base_FGBuildable_powered_has_mAllowedResourceForms_base & FGBuildable_powered;

type FGBuildableResourceExtractor_miner_mk1 = docs_json_ts_0_4_2_11_classes_base_FGBuildableResourceExtractor_miner_mk1_base_base & docs_json_ts_common_classes_FGBuildableResourceExtractor & FGBuildable_powered & FGBuildableResourceExtractor_base;

type FGBuildableResourceExtractor_miner_mk2 = docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_miner_mk2_base_base & docs_json_ts_common_classes_FGBuildableResourceExtractor & FGBuildable_powered;

type FGBuildableResourceExtractor_miner_mk3 = docs_json_ts_0_3_7_7_classes_base_FGBuildable_powered_base_resources_base & docs_json_ts_0_3_7_7_classes_base_FGBuildable_powered_pre_1_0 & docs_json_ts_0_3_7_7_classes_base_FGBuildable_powered_version_specific & docs_json_ts_0_3_7_7_classes_base_overridable_FGBuildableResourceExtractor_miner_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_miner_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_miner_mk3_version_specific & docs_json_ts_0_3_7_7_classes_base_overridable_FGBuildableResourceExtractor_only_allow_certain_resources & docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_piped & docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_piped_pre_1_0 & docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_timed & docs_json_ts_0_3_7_7_classes_base_has_mNumCyclesForProductivity & docs_json_ts_common_classes_FGBuildableResourceExtractor & FGBuildable_powered;

type FGBuildableResourceExtractor_oil = docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_oil_base_base & docs_json_ts_common_classes_FGBuildableResourceExtractor & FGBuildable_powered;

type FGBuildableResourceExtractor_water = docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_water_base_base & docs_json_ts_0_4_2_11_classes_base_FGBuildableResourceExtractor_water_base & docs_json_ts_common_classes_FGBuildableResourceExtractor & FGBuildable_powered;

type FGBuildableResourceSink = docs_json_ts_0_4_2_11_classes_base_FGBuildableResourceSink_base & docs_json_ts_common_classes_FGBuildableResourceSink & FGBuildable_powered;

type FGBuildableResourceSinkShop = docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceSinkShop_base_base & docs_json_ts_common_classes_FGBuildableResourceSinkShop & FGBuildable_powered;

type FGBuildableSnowDispenser = docs_json_ts_common_classes_FGBuildableSnowDispenser & FGBuildable_base;

type FGBuildableSpaceElevator = docs_json_ts_common_classes_FGBuildableSpaceElevator & FGBuildable_powered;

type FGBuildableSplitterSmart = docs_json_ts_0_3_7_7_classes_base_FGBuildable_powered_pre_1_0 & docs_json_ts_0_3_7_7_classes_base_FGBuildable_powered_version_specific & docs_json_ts_0_3_7_7_classes_base_FGBuildableAttachment_has_mCurrentInventoryIndex & docs_json_ts_0_3_7_7_classes_base_FGBuildableAttachment_splitter_base_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableSplitterSmart_version_specific & docs_json_ts_0_3_7_7_classes_base_has_mNumCyclesForProductivity & docs_json_ts_common_classes_FGBuildableSplitterSmart & FGBuildable_powered;

type FGBuildableStair = docs_json_ts_0_3_7_7_classes_base_has_mHeight & docs_json_ts_0_3_7_7_classes_base_has_mSize & docs_json_ts_common_classes_FGBuildableStair & FGBuildable_base & FGBuildableStair_has_mStairDirection;

type FGBuildableStair_has_mStairDirection = {
	mStairDirection: 'EBSD_Left' | 'EBSD_Right',
};

type FGBuildableStorage = docs_json_ts_0_3_7_7_classes_base_FGBuildableStorage_base_base & docs_json_ts_common_classes_FGBuildableStorage & FGBuildable_powered;

type FGBuildableTradingPost = docs_json_ts_0_3_7_7_classes_base_FGBuildable_powered_pre_1_0 & docs_json_ts_0_3_7_7_classes_base_FGBuildable_powered_version_specific & docs_json_ts_0_3_7_7_classes_base_FGBuildableTradingPost_pre_1_0 & docs_json_ts_0_3_7_7_classes_base_FGBuildableTradingPost_pre_update8 & docs_json_ts_0_3_7_7_classes_base_FGBuildableTradingPost_version_specific & docs_json_ts_0_3_7_7_classes_base_has_mNumCyclesForProductivity & docs_json_ts_0_4_2_11_classes_base_FGBuildableTradingPost_base & docs_json_ts_0_4_2_11_classes_base_FGBuildableTradingPost_base_pre_1_0 & docs_json_ts_0_4_2_11_classes_base_FGBuildableTradingPost_base_version_specific & docs_json_ts_common_classes_FGBuildableTradingPost & FGBuildable_powered & FGBuildableTradingPost_version_specific;

type FGBuildableTradingPost_version_specific = {
	mRepresentationText: Exclude<string, ''>,
};

type FGBuildableTrainPlatform_base = docs_json_ts_0_3_7_7_classes_base_FGBuildableTrainPlatform_base_base & FGBuildableTrainPlatform_base_version_specific;

type FGBuildableTrainPlatform_base_version_specific = {
	mIdleUpdateTimerHandle: docs_json_ts_common_types_empty_object,
	mDockWasCancelled: docs_json_ts_common_types_bool_string,
};

type FGBuildableTrainPlatform_non_empty = FGBuildableTrainPlatform_base & FGBuildableTrainPlatform_non_empty_version_specific;

type FGBuildableTrainPlatform_non_empty_version_specific = {
	mCurrentDockForDuration: docs_json_ts_common_types_decimal_string,
};

type FGBuildableTrainPlatform_with_storage = FGBuildable_powered_storage & FGBuildableTrainPlatform_non_empty;

type FGBuildableTrainPlatformCargo = docs_json_ts_0_3_7_7_classes_base_FGBuildableTrainPlatform_with_storage_base_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableTrainPlatformCargo_pre_update8 & docs_json_ts_0_3_7_7_classes_base_FGBuildableTrainPlatformCargo_version_specific & docs_json_ts_common_classes_FGBuildableTrainPlatformCargo & FGBuildable_base & FGBuildableTrainPlatform_with_storage & FGBuildableTrainPlatformCargo_version_specific;

type FGBuildableTrainPlatformCargo_version_specific = {
	mOnTransferRateUpdated: docs_json_ts_common_types_empty_object,
	mWaitForConditionUpdatePeriod: docs_json_ts_common_types_decimal_string,
	mDockingRuleSet: docs_json_ts_0_5_2_1_properties_mDockingRuleSet,
	mLoadItemFilter: '',
	mUnloadItemFilter: '',
	mHasFullyLoadUnloadRule: docs_json_ts_common_types_bool_string,
	mDockForDuration: docs_json_ts_common_types_decimal_string,
	mMustDockForDuration: docs_json_ts_common_types_bool_string,
	mRanCompleteBeforeNone: docs_json_ts_common_types_bool_string,
	mTimeSinceLastLoadTransferUpdate: docs_json_ts_common_types_decimal_string,
	mTimeSinceLastUnloadTransferUpdate: docs_json_ts_common_types_decimal_string,
	mSmoothedLoadRate: docs_json_ts_common_types_decimal_string,
	mSmoothedUnloadRate: docs_json_ts_common_types_decimal_string,
};

type FGBuildableTrainPlatformEmpty = docs_json_ts_common_classes_FGBuildableTrainPlatformEmpty & FGBuildable_powered & FGBuildableTrainPlatform_base;

type FGBuildableWalkway = docs_json_ts_0_3_7_7_classes_base_has_mDisableSnapOn & docs_json_ts_0_3_7_7_classes_base_has_mElevation & docs_json_ts_0_3_7_7_classes_base_has_mSize & docs_json_ts_common_classes_FGBuildableWalkway & FGBuildable_base;

type FGBuildableWall = docs_json_ts_0_5_2_1_classes_base_overridable_FGBuildable_is_wallish & docs_json_ts_0_3_7_7_classes_base_has_mElevation & docs_json_ts_0_3_7_7_classes_base_has_mHeight & docs_json_ts_0_3_7_7_classes_base_has_mWidth & docs_json_ts_common_classes_FGBuildableWall & FGBuildable_base;

type FGBuildableWidgetSign = docs_json_ts_common_classes_FGBuildableWidgetSign & FGBuildable_base & FGBuildableWidgetSign_base;

type FGBuildableWidgetSign_base = {
	mGainSignificanceDistance: docs_json_ts_common_types_decimal_string,
	mTextElementToDataMap: docs_json_ts_common_types_empty_object,
	mIconElementToDataMap: docs_json_ts_common_types_empty_object,
	mPrefabTextElementSaveData: '',
	mPrefabIconElementSaveData: '',
	mForegroundColor: docs_json_ts_common_types_RGBA,
	mBackgroundColor: docs_json_ts_common_types_RGBA,
	mAuxilaryColor: docs_json_ts_common_types_RGBA,
	mEmissive: docs_json_ts_common_types_decimal_string,
	mGlossiness: docs_json_ts_common_types_decimal_string,
	mDataVersion: docs_json_ts_common_types_integer_string,
	mSignPoles: '',
	mWorldDimensions: docs_json_ts_common_types_XY_decimal_string,
	mPoleOffset: docs_json_ts_common_types_XYZ_decimal_string,
	mPoleScale: docs_json_ts_common_types_XY_decimal_string,
	mSignToSignOffset: docs_json_ts_common_types_decimal_string,
};

type FGBuildableWire = docs_json_ts_0_3_7_7_classes_base_FGBuildableWire_base & docs_json_ts_common_classes_FGBuildableWire & FGBuildable_base;

type FGBuildingDescriptor = docs_json_ts_common_classes_FGBuildingDescriptor & FGDescriptor_BuildMenu;

type FGConsumableDescriptor = docs_json_ts_0_3_7_7_classes_base_FGConsumableDescriptor_base & docs_json_ts_common_classes_FGConsumableDescriptor & FGDescriptor_sinkable & FGItemDescriptor_base & FGItemDescriptor_base_base;

type FGConveyorPoleStackable = docs_json_ts_0_3_7_7_classes_base_has_mCanStack & docs_json_ts_0_3_7_7_classes_base_has_mHeight & docs_json_ts_0_3_7_7_classes_base_has_mStackHeight & docs_json_ts_0_3_7_7_classes_base_has_mUseStaticHeight & docs_json_ts_common_classes_FGBuildablePole & docs_json_ts_common_classes_FGConveyorPoleStackable & FGBuildable_base;

type FGDescriptor = docs_json_ts_0_4_2_11_classes_base_FGDescriptor_base & {
	mPersistentBigIcon: docs_json_ts_0_4_2_11_properties_Texture2D | 'None',
	mSmallIcon: docs_json_ts_0_4_2_11_properties_Texture2D | 'None',
};

type FGDescriptor_BuildMenu = FGDescriptor & FGDescriptor_BuildMenu_base;

type FGDescriptor_BuildMenu_base = docs_json_ts_0_4_2_11_classes_base_FGDescriptor_BuildMenu_base & {
	mMenuPriority: docs_json_ts_common_types_decimal_string,
	mBuildMenuPriority: docs_json_ts_common_types_decimal_string,
};

type FGDescriptor_sinkable = docs_json_ts_0_3_7_7_classes_base_FGDescriptor_base & docs_json_ts_0_3_7_7_classes_base_has_mResourceSinkPoints & FGDescriptor;

type FGEquipmentDescriptor = docs_json_ts_0_3_7_7_classes_base_has_mResourceSinkPoints & docs_json_ts_common_classes_FGEquipmentDescriptor & FGItemDescriptor_base & FGItemDescriptor_base_base;

type FGEquipmentDescriptor_Desc_GolfCartGold_C = docs_json_ts_common_classes_FGEquipmentDescriptor & FGItemDescriptor_base & FGItemDescriptor_base_base;

type FGGolfCartDispenser = docs_json_ts_0_3_7_7_classes_base_FGGolfCartDispenser & docs_json_ts_common_classes_FGGolfCartDispenser & FGGolfCartDispenser_pre_1_0 & FGGolfCartDispenser_version_specific;

type FGGolfCartDispenser_pre_1_0 = {
	mMaxSpawnDistance: docs_json_ts_common_types_decimal_string,
	mSpawningClearance: docs_json_ts_common_types_decimal_string,
	mBuildDisqualifierText: 'Vehicles cannot be built or deployed on top of existing vehicles.',
};

type FGGolfCartDispenser_version_specific = {
	mBuildDisqualifierText: Exclude<string, ''>,
	canDisplayDisqualifier: docs_json_ts_common_types_bool_string,
};

type FGItemDescAmmoTypeColorCartridge = docs_json_ts_0_3_7_7_classes_base_FGColorGun_base_base & docs_json_ts_0_3_7_7_classes_base_has_mResourceSinkPoints & docs_json_ts_common_classes_FGItemDescAmmoTypeColorCartridge & FGItemDescAmmoTypeColorCartridge_version_specific & FGItemDescAmmoTypeInstantHit_base & FGItemDescAmmoTypeProjectile_base;

type FGItemDescAmmoTypeColorCartridge_version_specific = {
	ToggleColorPickerUI: docs_json_ts_common_types_empty_object,
};

type FGItemDescAmmoTypeInstantHit = docs_json_ts_0_3_7_7_classes_base_has_mResourceSinkPoints & docs_json_ts_common_classes_FGItemDescAmmoTypeInstantHit & FGItemDescAmmoTypeInstantHit_base & FGItemDescAmmoTypeProjectile_base;

type FGItemDescAmmoTypeInstantHit_base = FGItemDescAmmoTypeProjectile_base & {
	mHitDamage: docs_json_ts_common_types_decimal_string,
};

type FGItemDescAmmoTypeProjectile_base = FGItemDescAmmoTypeProjectile_base_base & FGItemDescAmmoTypeProjectile_base_version_specific & FGItemDescriptor_base & FGItemDescriptor_base_base;

type FGItemDescAmmoTypeProjectile_base_base = {
	AmmoFiredDelegate: docs_json_ts_common_types_empty_object,
	mFiringTransform: docs_json_ts_0_3_7_7_properties_transform_Rotation_Translation_Scale3D,
	mHasBeenInitialized: docs_json_ts_common_types_bool_string,
	mWeaponDamageMultiplier: docs_json_ts_common_types_decimal_string,
	mMagazineSize: docs_json_ts_common_types_integer_string,
	mMaxAmmoEffectiveRange: docs_json_ts_common_types_decimal_string,
};

type FGItemDescAmmoTypeProjectile_base_version_specific = {
	mReloadTimeModifier: docs_json_ts_common_types_decimal_string,
	mFireRateModifier: docs_json_ts_common_types_decimal_string,
	mDispersionPerShotChangeModifier: docs_json_ts_common_types_decimal_string,
	mMinWeaponDispersionModifier: docs_json_ts_common_types_decimal_string,
	mMaxWeaponDispersionModifier: docs_json_ts_common_types_decimal_string,
	mWeaponAimTimeModifier: docs_json_ts_common_types_decimal_string,
	mAmmoDamageFalloff: docs_json_ts_0_5_2_1_overridable_FalloffCurve_EditorCurveData_with_ExternalCurve,
};

type FGItemDescAmmoTypeProjectile_Desc_NobeliskExplosive_C = docs_json_ts_0_3_7_7_classes_base_has_mResourceSinkPoints & docs_json_ts_common_classes_FGItemDescAmmoTypeProjectile & FGItemDescAmmoTypeProjectile_base & FGItemDescAmmoTypeProjectile_Desc_NobeliskExplosive_C_version_specific;

type FGItemDescAmmoTypeProjectile_Desc_NobeliskExplosive_C_version_specific = {
	mProjectileData: {
		ProjectileClass: docs_json_ts_0_3_7_7_overridable_BlueprintGeneratedClass_quoted,
		ProjectileLifeSpan: docs_json_ts_common_types_decimal_string_signed,
		ProjectileStickSpan: docs_json_ts_common_types_decimal_string_signed,
		ExplosionDamage: docs_json_ts_common_types_integer_string,
		ExplosionRadius: docs_json_ts_common_types_decimal_string,
		ImpactDamage: docs_json_ts_common_types_integer_string,
		ExplodeAtEndOfLife: docs_json_ts_common_types_bool_string,
		DamageType: docs_json_ts_0_3_7_7_overridable_BlueprintGeneratedClass_quoted,
		DamageTypeExplode: docs_json_ts_0_3_7_7_overridable_BlueprintGeneratedClass_quoted,
		DamageFalloffCurve: docs_json_ts_0_5_2_1_properties_FalloffCurve_EditorCurveData_only,
		WeaponDamageMultiplier: docs_json_ts_common_types_decimal_string,
	},
};

type FGItemDescAmmoTypeProjectile_Desc_SnowballProjectile_C = docs_json_ts_0_3_7_7_classes_base_has_mResourceSinkPoints & docs_json_ts_common_classes_FGItemDescAmmoTypeProjectile & FGItemDescAmmoTypeProjectile_base & FGItemDescAmmoTypeProjectile_Desc_SnowballProjectile_C_version_specific;

type FGItemDescAmmoTypeProjectile_Desc_SnowballProjectile_C_version_specific = {
	mProjectileData: {
		ProjectileClass: docs_json_ts_0_3_7_7_overridable_BlueprintGeneratedClass_quoted,
		ProjectileLifeSpan: docs_json_ts_common_types_decimal_string_signed,
		ProjectileStickSpan: docs_json_ts_common_types_decimal_string_signed,
		ExplosionDamage: docs_json_ts_common_types_integer_string,
		ExplosionRadius: docs_json_ts_common_types_decimal_string,
		ImpactDamage: docs_json_ts_common_types_integer_string,
		ExplodeAtEndOfLife: docs_json_ts_common_types_bool_string,
		DamageType: docs_json_ts_0_3_7_7_overridable_BlueprintGeneratedClass_quoted,
		DamageTypeExplode: docs_json_ts_0_3_7_7_overridable_BlueprintGeneratedClass_quoted,
		DamageFalloffCurve: docs_json_ts_0_5_2_1_properties_FalloffCurve_EditorCurveData_only,
		WeaponDamageMultiplier: docs_json_ts_common_types_decimal_string,
	},
};

type FGItemDescAmmoTypeProjectile_Desc_SpikedRebar_C = docs_json_ts_0_3_7_7_classes_base_has_mResourceSinkPoints & docs_json_ts_common_classes_FGItemDescAmmoTypeProjectile & FGItemDescAmmoTypeProjectile_base & FGItemDescAmmoTypeProjectile_Desc_SpikedRebar_C_version_specific;

type FGItemDescAmmoTypeProjectile_Desc_SpikedRebar_C_version_specific = {
	mProjectileData: {
		ProjectileClass: docs_json_ts_0_3_7_7_overridable_BlueprintGeneratedClass_quoted,
		ProjectileLifeSpan: docs_json_ts_common_types_decimal_string_signed,
		ProjectileStickSpan: docs_json_ts_common_types_decimal_string_signed,
		ImpactDamage: docs_json_ts_common_types_integer_string,
		CanTriggerExplodeBySameClass: docs_json_ts_common_types_bool_string,
		DamageType: docs_json_ts_0_3_7_7_overridable_BlueprintGeneratedClass_quoted,
		DamageTypeExplode: docs_json_ts_0_3_7_7_properties_Class_quoted,
		DamageFalloffCurve: docs_json_ts_0_5_2_1_properties_FalloffCurve_EditorCurveData_only,
		WeaponDamageMultiplier: docs_json_ts_common_types_decimal_string,
	},
};

type FGItemDescAmmoTypeProjectile_explosive_firework = docs_json_ts_common_classes_FGItemDescAmmoTypeProjectile & FGItemDescAmmoTypeProjectile_base & FGItemDescAmmoTypeProjectile_explosive_firework_version_specific;

type FGItemDescAmmoTypeProjectile_explosive_firework_version_specific = {
	mProjectileData: {
		ProjectileClass: docs_json_ts_0_3_7_7_overridable_BlueprintGeneratedClass_quoted,
		ProjectileLifeSpan: docs_json_ts_common_types_decimal_string_signed,
		ProjectileStickSpan: docs_json_ts_common_types_decimal_string_signed,
		ExplosionDamage: docs_json_ts_common_types_integer_string,
		ExplosionRadius: docs_json_ts_common_types_decimal_string,
		ImpactDamage: docs_json_ts_common_types_integer_string,
		CanTriggerExplodeBySameClass: docs_json_ts_common_types_bool_string,
		ExplodeAtEndOfLife: docs_json_ts_common_types_bool_string,
		DamageType: docs_json_ts_0_3_7_7_overridable_BlueprintGeneratedClass_quoted,
		DamageTypeExplode: docs_json_ts_0_3_7_7_overridable_BlueprintGeneratedClass_quoted,
		DamageFalloffCurve: docs_json_ts_0_5_2_1_properties_FalloffCurve_EditorCurveData_only,
		WeaponDamageMultiplier: docs_json_ts_common_types_decimal_string,
	},
};

type FGItemDescriptor = docs_json_ts_0_4_2_11_classes_base_FGDescriptor_sinkable & docs_json_ts_common_classes_FGItemDescriptor & FGItemDescriptor_base & FGItemDescriptor_base_base;

type FGItemDescriptor_base = {
	mBuildMenuPriority: docs_json_ts_common_types_decimal_string,
};

type FGItemDescriptor_base_base = FGDescriptor & {
	mMenuPriority: docs_json_ts_common_types_decimal_string,
	mSubCategories: null,
};

type FGItemDescriptorBiomass = docs_json_ts_0_4_2_11_classes_base_FGDescriptor_sinkable & docs_json_ts_common_classes_FGItemDescriptorBiomass & FGItemDescriptor_base & FGItemDescriptor_base_base;

type FGNobeliskDetonator = docs_json_ts_common_classes_FGNobeliskDetonator & FGNobeliskDetonator_pre_update6 & FGNobeliskDetonator_version_specific;

type FGNobeliskDetonator_pre_update6 = docs_json_ts_0_5_2_1_classes_base_overridable_FGWeapon_version_specific & docs_json_ts_0_3_7_7_classes_base_FGEquipment_base & docs_json_ts_0_3_7_7_classes_base_FGNobeliskDetonator_base & docs_json_ts_0_3_7_7_classes_base_FGWeaponProjectile_thrown_base_base & docs_json_ts_0_4_2_11_classes_base_FGWeaponProjectile_base & FGWeapon_pre_1_1 & FGWeapon_pre_update6 & FGWeapon_version_specific;

type FGNobeliskDetonator_version_specific = {
	mRadialMenuShowUpTime: docs_json_ts_common_types_decimal_string,
	mDispensedProjectiles: '',
	mDelayBetweenSecondaryTriggers: docs_json_ts_common_types_decimal_string,
};

type FGPipeHyperStart = docs_json_ts_0_3_7_7_classes_base_FGBuildable_powered_pre_1_0 & docs_json_ts_0_3_7_7_classes_base_FGBuildable_powered_version_specific & docs_json_ts_0_3_7_7_classes_base_FGBuildable_with_mLength & docs_json_ts_0_3_7_7_classes_base_FGPipeHyperStart_base_base_base & docs_json_ts_0_3_7_7_classes_base_FGPipeHyperStart_pre_update8 & docs_json_ts_0_3_7_7_classes_base_has_mCanStack & docs_json_ts_0_3_7_7_classes_base_has_mNumCyclesForProductivity & docs_json_ts_0_3_7_7_classes_base_has_mStackHeight & docs_json_ts_0_3_7_7_classes_base_has_mUseStaticHeight & docs_json_ts_common_classes_FGPipeHyperStart & FGBuildable_powered;

type FGPoleDescriptor = docs_json_ts_common_classes_FGPoleDescriptor & FGDescriptor_BuildMenu;

type FGResourceDescriptor = docs_json_ts_0_3_7_7_classes_base_FGResourceDescriptor_base & docs_json_ts_0_4_2_11_classes_base_FGDescriptor_sinkable & docs_json_ts_common_classes_FGResourceDescriptor & FGItemDescriptor_base & FGItemDescriptor_base_base;

type FGSchematic = docs_json_ts_0_4_2_11_classes_base_overridable_FGSchematic_base & docs_json_ts_0_5_2_1_classes_base_overridable_FGSchematic_version_specific & docs_json_ts_0_3_7_7_classes_base_FGSchematic_pre_1_0 & docs_json_ts_0_3_7_7_classes_base_overridable_FGSchematic_version_specific & docs_json_ts_0_4_2_11_classes_base_FGSchematic_has_mMenuPriority & docs_json_ts_0_4_2_11_classes_base_overridable_FGSchematic_has_mSchematicIcon & docs_json_ts_0_4_2_11_classes_base_FGSchematic_has_mTechTier & docs_json_ts_common_classes_FGSchematic & docs_json_ts_common_classes_base_isDescribed & FGSchematic_pre_update6;

type FGSchematic_pre_update6 = {
	mUnlocks: [
		...docs_json_ts_0_5_2_1_overridable_mUnlocks_item[],
	],
};

type FGSchematic_with_described_unlocks = docs_json_ts_0_4_2_11_classes_base_overridable_FGSchematic_base & docs_json_ts_0_5_2_1_classes_base_overridable_FGSchematic_version_specific & docs_json_ts_0_3_7_7_classes_base_FGSchematic_pre_1_0 & docs_json_ts_0_3_7_7_classes_base_overridable_FGSchematic_version_specific & docs_json_ts_0_4_2_11_classes_base_FGSchematic_has_mMenuPriority & docs_json_ts_0_4_2_11_classes_base_overridable_FGSchematic_has_mSchematicIcon & docs_json_ts_0_4_2_11_classes_base_FGSchematic_has_mTechTier & docs_json_ts_common_classes_FGSchematic & docs_json_ts_common_classes_base_isDescribed & FGSchematic_pre_update6 & FGSchematic_with_described_unlocks_pre_update6 & FGSchematic_with_described_unlocks_version_specific;

type FGSchematic_with_described_unlocks_pre_update6 = {
	mUnlockDescription: Exclude<string, ''>,
};

type FGSchematic_with_described_unlocks_version_specific = {
	mUnlockName: Exclude<string, ''>,
	mUnlockDescription: string,
	mUnlockIconBig: 'Unsupported texture. Contact developer for support',
	mUnlockIconSmall: 'Unsupported texture. Contact developer for support',
	mUnlockIconCategory: 'Unsupported texture. Contact developer for support',
};

type FGVehicleDescriptor_Desc_CyberWagon_C = docs_json_ts_common_classes_FGVehicleDescriptor & FGVehicleDescriptor_fueled_with_inventory;

type FGVehicleDescriptor_Desc_DroneTransport_C = docs_json_ts_common_classes_FGVehicleDescriptor & FGVehicleDescriptor_with_inventory;

type FGVehicleDescriptor_Desc_Explorer_C = docs_json_ts_common_classes_FGVehicleDescriptor & FGVehicleDescriptor_fueled_with_inventory;

type FGVehicleDescriptor_Desc_FreightWagon_C = docs_json_ts_common_classes_FGVehicleDescriptor & FGVehicleDescriptor_with_inventory;

type FGVehicleDescriptor_Desc_Locomotive_C = docs_json_ts_common_classes_FGVehicleDescriptor & FGVehicleDescriptor_powered;

type FGVehicleDescriptor_Desc_Tractor_C = docs_json_ts_common_classes_FGVehicleDescriptor & FGVehicleDescriptor_fueled_with_inventory;

type FGVehicleDescriptor_Desc_Truck_C = docs_json_ts_common_classes_FGVehicleDescriptor & FGVehicleDescriptor_fueled_with_inventory;

type FGVehicleDescriptor_fueled_with_inventory = docs_json_ts_0_4_2_11_classes_base_FGVehicleDescriptor_fueled_with_inventory & FGDescriptor_BuildMenu_base;

type FGVehicleDescriptor_powered = docs_json_ts_0_4_2_11_classes_base_FGVehicleDescriptor_powered & FGDescriptor_BuildMenu_base;

type FGVehicleDescriptor_with_inventory = docs_json_ts_0_4_2_11_classes_base_FGVehicleDescriptor_with_inventory & FGDescriptor_BuildMenu_base;

type FGWeapon_Equip_RebarGun_Projectile_C = docs_json_ts_0_5_2_1_classes_base_overridable_FGWeapon_version_specific & docs_json_ts_0_3_7_7_classes_base_FGWeaponProjectile_base & docs_json_ts_0_3_7_7_classes_base_FGWeaponProjectile_has_mAttachSocket & docs_json_ts_0_3_7_7_classes_base_FGWeaponProjectileFire_base_random & docs_json_ts_0_4_2_11_classes_base_FGWeaponProjectile_base & docs_json_ts_0_4_2_11_classes_base_FGWeaponProjectileFire_has_mMuteDryFire & docs_json_ts_common_classes_FGWeapon_Equip_RebarGun_Projectile_C & FGWeapon_pre_1_1 & FGWeapon_pre_update6 & FGWeapon_version_specific;

type FGWeapon_Equip_Rifle_C = docs_json_ts_0_5_2_1_classes_base_overridable_FGWeapon_version_specific & docs_json_ts_0_3_7_7_classes_base_FGWeaponInstantFire_base & docs_json_ts_0_3_7_7_classes_base_FGWeaponProjectile_base & docs_json_ts_0_3_7_7_classes_base_FGWeaponProjectile_has_mAttachSocket & docs_json_ts_0_4_2_11_classes_base_FGWeaponProjectile_base & docs_json_ts_common_classes_FGWeapon_Equip_Rifle_C & FGWeapon_Equip_Rifle_C_base & FGWeapon_pre_1_1 & FGWeapon_pre_update6 & FGWeapon_version_specific;

type FGWeapon_Equip_Rifle_C_base = {
	mArmAnimation: 'AE_Rifle',
};

type FGWeapon_pre_1_1 = {
	mShowCycleAmmoRadialMenuTimer: docs_json_ts_common_types_empty_object,
};

type FGWeapon_pre_update6 = {
	mOldState: [
		'EWS_Unequipped',
	],
	mBaseRestingDispersion: docs_json_ts_common_types_decimal_string,
	mBaseFiringDispersion: docs_json_ts_common_types_decimal_string,
	mBaseAimTime: docs_json_ts_common_types_decimal_string,
	mRestingDispersion: docs_json_ts_common_types_decimal_string,
	mFiringDispersion: docs_json_ts_common_types_decimal_string,
	mDispersionChangePerShot: docs_json_ts_common_types_decimal_string,
	mAimTime: docs_json_ts_common_types_decimal_string,
	mAmmoCycleMode: 'IE_Released',
};

type FGWeapon_version_specific = {
	mWeaponState: 'EWS_Unequipped',
	mAutomaticallyReload: docs_json_ts_common_types_bool_string,
	mAutoReloadDelay: docs_json_ts_common_types_decimal_string,
	mAutoReloadTimerHandle: docs_json_ts_common_types_empty_object,
	mCurrentAmmoCount: docs_json_ts_common_types_integer_string,
	mWeaponDamageMultiplier: docs_json_ts_common_types_decimal_string,
	mFiringBlocksDispersionReduction: docs_json_ts_common_types_bool_string,
	mCurrentDispersion: docs_json_ts_common_types_decimal_string,
	mAmmoSwitchUsedRadialMenu: docs_json_ts_common_types_bool_string,
	mOnAmmoCyclingPressed: docs_json_ts_common_types_empty_object,
	mOnAmmoCyclingReleased: docs_json_ts_common_types_empty_object,
	mOnWeaponStateChanged: docs_json_ts_common_types_empty_object,
};

export type {
	has_mIsSupport,
	has_mSize_vector,
	has_mSplineData,
	FGBuildable_base,
	FGBuildable_base_pre_1_0,
	FGBuildable_base_version_specific,
	FGBuildable_docking_station,
	FGBuildable_foundation_DisableAttachmentSnapOn,
	FGBuildable_foundation_mDisableSnapOn,
	FGBuildable_isFrame,
	FGBuildable_mSnappedPassthroughs,
	FGBuildable_occupied,
	FGBuildable_powered,
	FGBuildable_powered_base_base,
	FGBuildable_powered_storage,
	FGBuildable_ramp_DisableAttachmentSnapOn,
	FGBuildable_ramp_mDisableSnapOn,
	FGBuildable_tiered,
	FGBuildable_unoccupied_and_untiered,
	FGBuildable_with_height,
	FGBuildableAttachment,
	FGBuildableAttachment_splitter,
	FGBuildableAttachmentMerger,
	FGBuildableAttachmentSplitter,
	FGBuildableBeam,
	FGBuildableBeam_version_specific,
	FGBuildableCircuitSwitch,
	FGBuildableConveyorBelt,
	FGBuildableConveyorBelt_version_specific,
	FGBuildableConveyorLift,
	FGBuildableCornerWall,
	FGBuildableDockingStation,
	FGBuildableDockingStation_base,
	FGBuildableDockingStation_base_base,
	FGBuildableDoor,
	FGBuildableDoor_automated,
	FGBuildableDoor_automated_version_specific,
	FGBuildableDoor_base,
	FGBuildableDoor_manual,
	FGBuildableDoor_manual_version_specific,
	FGBuildableDroneStation,
	FGBuildableFactory_jump_pad,
	FGBuildableFactory_landing_pad,
	FGBuildableFactory_not_pad,
	FGBuildableFactoryBuilding,
	FGBuildableFactorySimpleProducer,
	FGBuildableFloodlight,
	FGBuildableFoundation,
	FGBuildableFoundation_base,
	FGBuildableFoundation_base_base,
	FGBuildableFrackingActivator,
	FGBuildableFrackingExtractor,
	FGBuildableGenerator,
	FGBuildableGenerator_no_fuel,
	FGBuildableGeneratorFuel_biomass,
	FGBuildableGeneratorFuel_coal,
	FGBuildableGeneratorFuel_fuel,
	FGBuildableGeneratorGeoThermal,
	FGBuildableGeneratorNuclear,
	FGBuildableJumppad,
	FGBuildableLadder,
	FGBuildableLightsControlPanel,
	FGBuildableLightsControlPanel_version_specific,
	FGBuildableLightSource_base,
	FGBuildableLightSource_Build_CeilingLight_C,
	FGBuildableLightSource_Build_StreetLight_C,
	FGBuildableLightSource_Build_StreetLight_C_version_specific,
	FGBuildableMAM,
	FGBuildableManufacturer_Build_AssemblerMk1_C,
	FGBuildableManufacturer_Build_Blender_C,
	FGBuildableManufacturer_Build_ConstructorMk1_C,
	FGBuildableManufacturer_Build_ConstructorMk1_C_base,
	FGBuildableManufacturer_Build_FoundryMk1_C,
	FGBuildableManufacturer_Build_FoundryMk1_C_base,
	FGBuildableManufacturer_Build_HadronCollider_C,
	FGBuildableManufacturer_Build_ManufacturerMk1_C,
	FGBuildableManufacturer_Build_OilRefinery_C,
	FGBuildableManufacturer_Build_Packager_C,
	FGBuildableManufacturer_Build_SmelterMk1_C,
	FGBuildableManufacturer_Build_SmelterMk1_C_base,
	FGBuildablePassthrough,
	FGBuildablePassthrough_base,
	FGBuildablePassthrough_pre_update8,
	FGBuildablePillar,
	FGBuildablePipeHyper,
	FGBuildablePipeHyper_version_specific,
	FGBuildablePipeline,
	FGBuildablePipeline_base_spline,
	FGBuildablePipelineJunction,
	FGBuildablePipelinePump_pump,
	FGBuildablePipelinePump_valve,
	FGBuildablePipelineSupport,
	FGBuildablePipeReservoir,
	FGBuildablePole,
	FGBuildablePowerPole,
	FGBuildablePowerStorage,
	FGBuildableRadarTower,
	FGBuildableRailroadSignal_base,
	FGBuildableRailroadSignal_base_version_specific,
	FGBuildableRailroadSignal_block,
	FGBuildableRailroadSignal_block_version_specific,
	FGBuildableRailroadSignal_path,
	FGBuildableRailroadStation,
	FGBuildableRailroadStation_base,
	FGBuildableRailroadTrack,
	FGBuildableRailroadTrack_base,
	FGBuildableRailroadTrack_base_version_specific,
	FGBuildableRamp,
	FGBuildableRamp_base,
	FGBuildableRamp_base_base,
	FGBuildableResourceExtractor_base,
	FGBuildableResourceExtractor_miner_mk1,
	FGBuildableResourceExtractor_miner_mk2,
	FGBuildableResourceExtractor_miner_mk3,
	FGBuildableResourceExtractor_oil,
	FGBuildableResourceExtractor_water,
	FGBuildableResourceSink,
	FGBuildableResourceSinkShop,
	FGBuildableSnowDispenser,
	FGBuildableSpaceElevator,
	FGBuildableSplitterSmart,
	FGBuildableStair,
	FGBuildableStair_has_mStairDirection,
	FGBuildableStorage,
	FGBuildableTradingPost,
	FGBuildableTradingPost_version_specific,
	FGBuildableTrainPlatform_base,
	FGBuildableTrainPlatform_base_version_specific,
	FGBuildableTrainPlatform_non_empty,
	FGBuildableTrainPlatform_non_empty_version_specific,
	FGBuildableTrainPlatform_with_storage,
	FGBuildableTrainPlatformCargo,
	FGBuildableTrainPlatformCargo_version_specific,
	FGBuildableTrainPlatformEmpty,
	FGBuildableWalkway,
	FGBuildableWall,
	FGBuildableWidgetSign,
	FGBuildableWidgetSign_base,
	FGBuildableWire,
	FGBuildingDescriptor,
	FGConsumableDescriptor,
	FGConveyorPoleStackable,
	FGDescriptor,
	FGDescriptor_BuildMenu,
	FGDescriptor_BuildMenu_base,
	FGDescriptor_sinkable,
	FGEquipmentDescriptor,
	FGEquipmentDescriptor_Desc_GolfCartGold_C,
	FGGolfCartDispenser,
	FGGolfCartDispenser_pre_1_0,
	FGGolfCartDispenser_version_specific,
	FGItemDescAmmoTypeColorCartridge,
	FGItemDescAmmoTypeColorCartridge_version_specific,
	FGItemDescAmmoTypeInstantHit,
	FGItemDescAmmoTypeInstantHit_base,
	FGItemDescAmmoTypeProjectile_base,
	FGItemDescAmmoTypeProjectile_base_base,
	FGItemDescAmmoTypeProjectile_base_version_specific,
	FGItemDescAmmoTypeProjectile_Desc_NobeliskExplosive_C,
	FGItemDescAmmoTypeProjectile_Desc_NobeliskExplosive_C_version_specific,
	FGItemDescAmmoTypeProjectile_Desc_SnowballProjectile_C,
	FGItemDescAmmoTypeProjectile_Desc_SnowballProjectile_C_version_specific,
	FGItemDescAmmoTypeProjectile_Desc_SpikedRebar_C,
	FGItemDescAmmoTypeProjectile_Desc_SpikedRebar_C_version_specific,
	FGItemDescAmmoTypeProjectile_explosive_firework,
	FGItemDescAmmoTypeProjectile_explosive_firework_version_specific,
	FGItemDescriptor,
	FGItemDescriptor_base,
	FGItemDescriptor_base_base,
	FGItemDescriptorBiomass,
	FGNobeliskDetonator,
	FGNobeliskDetonator_pre_update6,
	FGNobeliskDetonator_version_specific,
	FGPipeHyperStart,
	FGPoleDescriptor,
	FGResourceDescriptor,
	FGSchematic,
	FGSchematic_pre_update6,
	FGSchematic_with_described_unlocks,
	FGSchematic_with_described_unlocks_pre_update6,
	FGSchematic_with_described_unlocks_version_specific,
	FGVehicleDescriptor_Desc_CyberWagon_C,
	FGVehicleDescriptor_Desc_DroneTransport_C,
	FGVehicleDescriptor_Desc_Explorer_C,
	FGVehicleDescriptor_Desc_FreightWagon_C,
	FGVehicleDescriptor_Desc_Locomotive_C,
	FGVehicleDescriptor_Desc_Tractor_C,
	FGVehicleDescriptor_Desc_Truck_C,
	FGVehicleDescriptor_fueled_with_inventory,
	FGVehicleDescriptor_powered,
	FGVehicleDescriptor_with_inventory,
	FGWeapon_Equip_RebarGun_Projectile_C,
	FGWeapon_Equip_Rifle_C,
	FGWeapon_Equip_Rifle_C_base,
	FGWeapon_pre_1_1,
	FGWeapon_pre_update6,
	FGWeapon_version_specific,
};
