/* eslint-disable @stylistic/max-len */

import type {
	FGBuildable_occupied as docs_json_ts_0_4_2_11_classes_base_FGBuildable_occupied,
	FGBuildable_powered as docs_json_ts_0_4_2_11_classes_base_FGBuildable_powered,
	FGBuildable_tiered as docs_json_ts_0_4_2_11_classes_base_FGBuildable_tiered,
	FGBuildable_unoccupied_and_untiered as docs_json_ts_0_4_2_11_classes_base_FGBuildable_unoccupied_and_untiered,
	FGBuildableAttachmentMerger as docs_json_ts_0_4_2_11_classes_base_FGBuildableAttachmentMerger,
	FGBuildableAttachmentSplitter as docs_json_ts_0_4_2_11_classes_base_FGBuildableAttachmentSplitter,
	FGBuildableCircuitSwitch as docs_json_ts_0_4_2_11_classes_base_FGBuildableCircuitSwitch,
	FGBuildableConveyorBelt_spline as docs_json_ts_0_4_2_11_classes_base_FGBuildableConveyorBelt_spline,
	FGBuildableConveyorLift as docs_json_ts_0_4_2_11_classes_base_FGBuildableConveyorLift,
	FGBuildableDockingStation as docs_json_ts_0_4_2_11_classes_base_FGBuildableDockingStation,
	FGBuildableDroneStation as docs_json_ts_0_4_2_11_classes_base_FGBuildableDroneStation,
	FGBuildableFactory_jump_pad as docs_json_ts_0_4_2_11_classes_base_FGBuildableFactory_jump_pad,
	FGBuildableFactory_landing_pad as docs_json_ts_0_4_2_11_classes_base_FGBuildableFactory_landing_pad,
	FGBuildableFactory_not_a_pad as docs_json_ts_0_4_2_11_classes_base_FGBuildableFactory_not_a_pad,
	FGBuildableFactorySimpleProducer as docs_json_ts_0_4_2_11_classes_base_FGBuildableFactorySimpleProducer,
	FGBuildableFloodlight as docs_json_ts_0_4_2_11_classes_base_FGBuildableFloodlight,
	FGBuildableFoundation as docs_json_ts_0_4_2_11_classes_base_FGBuildableFoundation,
	FGBuildableFrackingActivator as docs_json_ts_0_4_2_11_classes_base_FGBuildableFrackingActivator,
	FGBuildableFrackingExtractor as docs_json_ts_0_4_2_11_classes_base_FGBuildableFrackingExtractor,
	FGBuildableGeneratorFuel_biomass as docs_json_ts_0_4_2_11_classes_base_FGBuildableGeneratorFuel_biomass,
	FGBuildableGeneratorFuel_coal as docs_json_ts_0_4_2_11_classes_base_FGBuildableGeneratorFuel_coal,
	FGBuildableGeneratorFuel_fuel as docs_json_ts_0_4_2_11_classes_base_FGBuildableGeneratorFuel_fuel,
	FGBuildableGeneratorGeoThermal as docs_json_ts_0_4_2_11_classes_base_FGBuildableGeneratorGeoThermal,
	FGBuildableGeneratorNuclear as docs_json_ts_0_4_2_11_classes_base_FGBuildableGeneratorNuclear,
	FGBuildableJumppad as docs_json_ts_0_4_2_11_classes_base_FGBuildableJumppad,
	FGBuildableLadder as docs_json_ts_0_4_2_11_classes_base_FGBuildableLadder,
	FGBuildableLightsControlPanel as docs_json_ts_0_4_2_11_classes_base_FGBuildableLightsControlPanel,
	FGBuildableLightSource as docs_json_ts_0_4_2_11_classes_base_FGBuildableLightSource,
	FGBuildableMAM as docs_json_ts_0_4_2_11_classes_base_FGBuildableMAM,
	FGBuildableManufacturer_Build_AssemblerMk1_C as docs_json_ts_0_4_2_11_classes_base_FGBuildableManufacturer_Build_AssemblerMk1_C,
	FGBuildableManufacturer_Build_Blender_C as docs_json_ts_0_4_2_11_classes_base_FGBuildableManufacturer_Build_Blender_C,
	FGBuildableManufacturer_Build_ConstructorMk1_C as docs_json_ts_0_4_2_11_classes_base_FGBuildableManufacturer_Build_ConstructorMk1_C,
	FGBuildableManufacturer_Build_FoundryMk1_C as docs_json_ts_0_4_2_11_classes_base_FGBuildableManufacturer_Build_FoundryMk1_C,
	FGBuildableManufacturer_Build_HadronCollider_C as docs_json_ts_0_4_2_11_classes_base_FGBuildableManufacturer_Build_HadronCollider_C,
	FGBuildableManufacturer_Build_ManufacturerMk1_C as docs_json_ts_0_4_2_11_classes_base_FGBuildableManufacturer_Build_ManufacturerMk1_C,
	FGBuildableManufacturer_Build_OilRefinery_C as docs_json_ts_0_4_2_11_classes_base_FGBuildableManufacturer_Build_OilRefinery_C,
	FGBuildableManufacturer_Build_Packager_C as docs_json_ts_0_4_2_11_classes_base_FGBuildableManufacturer_Build_Packager_C,
	FGBuildableManufacturer_Build_SmelterMk1_C as docs_json_ts_0_4_2_11_classes_base_FGBuildableManufacturer_Build_SmelterMk1_C,
	FGBuildablePipeHyper as docs_json_ts_0_4_2_11_classes_base_FGBuildablePipeHyper,
	FGBuildablePipeline as docs_json_ts_0_4_2_11_classes_base_FGBuildablePipeline,
	FGBuildablePipelineJunction as docs_json_ts_0_4_2_11_classes_base_FGBuildablePipelineJunction,
	FGBuildablePipelinePump_pump as docs_json_ts_0_4_2_11_classes_base_FGBuildablePipelinePump_pump,
	FGBuildablePipelinePump_valve as docs_json_ts_0_4_2_11_classes_base_FGBuildablePipelinePump_valve,
	FGBuildablePipelineSupport as docs_json_ts_0_4_2_11_classes_base_FGBuildablePipelineSupport,
	FGBuildablePipeReservoir as docs_json_ts_0_4_2_11_classes_base_FGBuildablePipeReservoir,
	FGBuildablePole as docs_json_ts_0_4_2_11_classes_base_FGBuildablePole,
	FGBuildablePowerPole as docs_json_ts_0_4_2_11_classes_base_FGBuildablePowerPole,
	FGBuildablePowerStorage as docs_json_ts_0_4_2_11_classes_base_FGBuildablePowerStorage,
	FGBuildableRadarTower as docs_json_ts_0_4_2_11_classes_base_FGBuildableRadarTower,
	FGBuildableRailroadStation as docs_json_ts_0_4_2_11_classes_base_FGBuildableRailroadStation,
	FGBuildableRailroadTrack as docs_json_ts_0_4_2_11_classes_base_FGBuildableRailroadTrack,
	FGBuildableResourceExtractor_miner_mk1 as docs_json_ts_0_4_2_11_classes_base_FGBuildableResourceExtractor_miner_mk1,
	FGBuildableResourceExtractor_miner_mk2 as docs_json_ts_0_4_2_11_classes_base_FGBuildableResourceExtractor_miner_mk2,
	FGBuildableResourceExtractor_miner_mk3 as docs_json_ts_0_4_2_11_classes_base_FGBuildableResourceExtractor_miner_mk3,
	FGBuildableResourceExtractor_oil as docs_json_ts_0_4_2_11_classes_base_FGBuildableResourceExtractor_oil,
	FGBuildableResourceExtractor_water as docs_json_ts_0_4_2_11_classes_base_FGBuildableResourceExtractor_water,
	FGBuildableResourceSink as docs_json_ts_0_4_2_11_classes_base_FGBuildableResourceSink,
	FGBuildableResourceSinkShop as docs_json_ts_0_4_2_11_classes_base_FGBuildableResourceSinkShop,
	FGBuildableSnowDispenser as docs_json_ts_0_4_2_11_classes_base_FGBuildableSnowDispenser,
	FGBuildableSpaceElevator as docs_json_ts_0_4_2_11_classes_base_FGBuildableSpaceElevator,
	FGBuildableSplitterSmart as docs_json_ts_0_4_2_11_classes_base_FGBuildableSplitterSmart,
	FGBuildableStair as docs_json_ts_0_4_2_11_classes_base_FGBuildableStair,
	FGBuildableStorage as docs_json_ts_0_4_2_11_classes_base_FGBuildableStorage,
	FGBuildableTradingPost as docs_json_ts_0_4_2_11_classes_base_FGBuildableTradingPost,
	FGBuildableTrainPlatformCargo as docs_json_ts_0_4_2_11_classes_base_FGBuildableTrainPlatformCargo,
	FGBuildableTrainPlatformEmpty as docs_json_ts_0_4_2_11_classes_base_FGBuildableTrainPlatformEmpty,
	FGBuildableWalkway as docs_json_ts_0_4_2_11_classes_base_FGBuildableWalkway,
	FGBuildableWall as docs_json_ts_0_4_2_11_classes_base_FGBuildableWall,
	FGBuildableWire as docs_json_ts_0_4_2_11_classes_base_FGBuildableWire,
	FGBuildingDescriptor as docs_json_ts_0_4_2_11_classes_base_FGBuildingDescriptor,
	FGColorGun as docs_json_ts_0_4_2_11_classes_base_FGColorGun,
	FGConsumableDescriptor as docs_json_ts_0_4_2_11_classes_base_FGConsumableDescriptor,
	FGConsumableEquipment as docs_json_ts_0_4_2_11_classes_base_FGConsumableEquipment,
	FGConveyorPoleStackable as docs_json_ts_0_4_2_11_classes_base_FGConveyorPoleStackable,
	FGEquipmentDescriptor as docs_json_ts_0_4_2_11_classes_base_FGEquipmentDescriptor,
	FGEquipmentZipline as docs_json_ts_0_4_2_11_classes_base_FGEquipmentZipline,
	FGHoverPack as docs_json_ts_0_4_2_11_classes_base_FGHoverPack,
	FGItemDescriptor as docs_json_ts_0_4_2_11_classes_base_FGItemDescriptor,
	FGItemDescriptorBiomass as docs_json_ts_0_4_2_11_classes_base_FGItemDescriptorBiomass,
	FGNobeliskDetonator as docs_json_ts_0_4_2_11_classes_base_FGNobeliskDetonator,
	FGParachute as docs_json_ts_0_4_2_11_classes_base_FGParachute,
	FGPipeHyperStart as docs_json_ts_0_4_2_11_classes_base_FGPipeHyperStart,
	FGPoleDescriptor as docs_json_ts_0_4_2_11_classes_base_FGPoleDescriptor,
	FGPortableMinerDispenser as docs_json_ts_0_4_2_11_classes_base_FGPortableMinerDispenser,
	FGRecipe as docs_json_ts_0_4_2_11_classes_base_FGRecipe,
	FGResourceDescriptor as docs_json_ts_0_4_2_11_classes_base_FGResourceDescriptor,
	FGSchematic as docs_json_ts_0_4_2_11_classes_base_FGSchematic,
	FGSnowballWeapon as docs_json_ts_0_4_2_11_classes_base_FGSnowballWeapon,
	FGVehicleDescriptor_Desc_CyberWagon_C as docs_json_ts_0_4_2_11_classes_base_FGVehicleDescriptor_Desc_CyberWagon_C,
	FGVehicleDescriptor_Desc_DroneTransport_C as docs_json_ts_0_4_2_11_classes_base_FGVehicleDescriptor_Desc_DroneTransport_C,
	FGVehicleDescriptor_Desc_Explorer_C as docs_json_ts_0_4_2_11_classes_base_FGVehicleDescriptor_Desc_Explorer_C,
	FGVehicleDescriptor_Desc_FreightWagon_C as docs_json_ts_0_4_2_11_classes_base_FGVehicleDescriptor_Desc_FreightWagon_C,
	FGVehicleDescriptor_Desc_Locomotive_C as docs_json_ts_0_4_2_11_classes_base_FGVehicleDescriptor_Desc_Locomotive_C,
	FGVehicleDescriptor_Desc_Tractor_C as docs_json_ts_0_4_2_11_classes_base_FGVehicleDescriptor_Desc_Tractor_C,
	FGVehicleDescriptor_Desc_Truck_C as docs_json_ts_0_4_2_11_classes_base_FGVehicleDescriptor_Desc_Truck_C,
	FGWeapon_Equip_RebarGun_Projectile_C as docs_json_ts_0_4_2_11_classes_base_FGWeapon_Equip_RebarGun_Projectile_C,
	FGWeapon_Equip_Rifle_C as docs_json_ts_0_4_2_11_classes_base_FGWeapon_Equip_Rifle_C,
} from './classes/Base.ts';

import type {
	FGItemDescriptorNuclearFuel as docs_json_ts_0_4_2_11_classes_base_overridable_FGItemDescriptorNuclearFuel,
} from './classes/Base.overridable.ts';

type FGBuildable_occupied = docs_json_ts_0_4_2_11_classes_base_FGBuildable_occupied;

type FGBuildable_powered_base = docs_json_ts_0_4_2_11_classes_base_FGBuildable_powered;

type FGBuildable_tiered = docs_json_ts_0_4_2_11_classes_base_FGBuildable_tiered;

type FGBuildable_unoccupied_and_untiered = docs_json_ts_0_4_2_11_classes_base_FGBuildable_unoccupied_and_untiered;

type FGBuildableAttachmentMerger = docs_json_ts_0_4_2_11_classes_base_FGBuildableAttachmentMerger;

type FGBuildableAttachmentSplitter = docs_json_ts_0_4_2_11_classes_base_FGBuildableAttachmentSplitter;

type FGBuildableCircuitSwitch = docs_json_ts_0_4_2_11_classes_base_FGBuildableCircuitSwitch;

type FGBuildableConveyorBelt = docs_json_ts_0_4_2_11_classes_base_FGBuildableConveyorBelt_spline;

type FGBuildableConveyorLift = docs_json_ts_0_4_2_11_classes_base_FGBuildableConveyorLift;

type FGBuildableDockingStation = docs_json_ts_0_4_2_11_classes_base_FGBuildableDockingStation;

type FGBuildableDroneStation = docs_json_ts_0_4_2_11_classes_base_FGBuildableDroneStation;

type FGBuildableFactory_jump_pad = docs_json_ts_0_4_2_11_classes_base_FGBuildableFactory_jump_pad;

type FGBuildableFactory_landing_pad = docs_json_ts_0_4_2_11_classes_base_FGBuildableFactory_landing_pad;

type FGBuildableFactory_not_a_pad = docs_json_ts_0_4_2_11_classes_base_FGBuildableFactory_not_a_pad;

type FGBuildableFactorySimpleProducer = docs_json_ts_0_4_2_11_classes_base_FGBuildableFactorySimpleProducer;

type FGBuildableFloodlight = docs_json_ts_0_4_2_11_classes_base_FGBuildableFloodlight;

type FGBuildableFoundation = docs_json_ts_0_4_2_11_classes_base_FGBuildableFoundation;

type FGBuildableFrackingActivator = docs_json_ts_0_4_2_11_classes_base_FGBuildableFrackingActivator;

type FGBuildableFrackingExtractor = docs_json_ts_0_4_2_11_classes_base_FGBuildableFrackingExtractor;

type FGBuildableGeneratorFuel_biomass = docs_json_ts_0_4_2_11_classes_base_FGBuildableGeneratorFuel_biomass;

type FGBuildableGeneratorFuel_coal = docs_json_ts_0_4_2_11_classes_base_FGBuildableGeneratorFuel_coal;

type FGBuildableGeneratorFuel_fuel = docs_json_ts_0_4_2_11_classes_base_FGBuildableGeneratorFuel_fuel;

type FGBuildableGeneratorGeoThermal = docs_json_ts_0_4_2_11_classes_base_FGBuildableGeneratorGeoThermal;

type FGBuildableGeneratorNuclear = docs_json_ts_0_4_2_11_classes_base_FGBuildableGeneratorNuclear;

type FGBuildableJumppad = docs_json_ts_0_4_2_11_classes_base_FGBuildableJumppad;

type FGBuildableLadder = docs_json_ts_0_4_2_11_classes_base_FGBuildableLadder;

type FGBuildableLightsControlPanel = docs_json_ts_0_4_2_11_classes_base_FGBuildableLightsControlPanel;

type FGBuildableLightSource = docs_json_ts_0_4_2_11_classes_base_FGBuildableLightSource;

type FGBuildableMAM = docs_json_ts_0_4_2_11_classes_base_FGBuildableMAM;

type FGBuildableManufacturer_Build_AssemblerMk1_C = docs_json_ts_0_4_2_11_classes_base_FGBuildableManufacturer_Build_AssemblerMk1_C;

type FGBuildableManufacturer_Build_Blender_C = docs_json_ts_0_4_2_11_classes_base_FGBuildableManufacturer_Build_Blender_C;

type FGBuildableManufacturer_Build_ConstructorMk1_C = docs_json_ts_0_4_2_11_classes_base_FGBuildableManufacturer_Build_ConstructorMk1_C;

type FGBuildableManufacturer_Build_FoundryMk1_C = docs_json_ts_0_4_2_11_classes_base_FGBuildableManufacturer_Build_FoundryMk1_C;

type FGBuildableManufacturer_Build_ManufacturerMk1_C = docs_json_ts_0_4_2_11_classes_base_FGBuildableManufacturer_Build_ManufacturerMk1_C;

type FGBuildableManufacturer_Build_OilRefinery_C = docs_json_ts_0_4_2_11_classes_base_FGBuildableManufacturer_Build_OilRefinery_C;

type FGBuildableManufacturer_Build_Packager_C = docs_json_ts_0_4_2_11_classes_base_FGBuildableManufacturer_Build_Packager_C;

type FGBuildableManufacturer_Build_SmelterMk1_C = docs_json_ts_0_4_2_11_classes_base_FGBuildableManufacturer_Build_SmelterMk1_C;

type FGBuildableManufacturerVariablePower = docs_json_ts_0_4_2_11_classes_base_FGBuildableManufacturer_Build_HadronCollider_C;

type FGBuildablePipeHyper = docs_json_ts_0_4_2_11_classes_base_FGBuildablePipeHyper;

type FGBuildablePipeline = docs_json_ts_0_4_2_11_classes_base_FGBuildablePipeline;

type FGBuildablePipelineJunction = docs_json_ts_0_4_2_11_classes_base_FGBuildablePipelineJunction;

type FGBuildablePipelinePump_pump = docs_json_ts_0_4_2_11_classes_base_FGBuildablePipelinePump_pump;

type FGBuildablePipelinePump_valve = docs_json_ts_0_4_2_11_classes_base_FGBuildablePipelinePump_valve;

type FGBuildablePipelineSupport = docs_json_ts_0_4_2_11_classes_base_FGBuildablePipelineSupport;

type FGBuildablePipeReservoir = docs_json_ts_0_4_2_11_classes_base_FGBuildablePipeReservoir;

type FGBuildablePole = docs_json_ts_0_4_2_11_classes_base_FGBuildablePole;

type FGBuildablePowerPole = docs_json_ts_0_4_2_11_classes_base_FGBuildablePowerPole;

type FGBuildablePowerStorage = docs_json_ts_0_4_2_11_classes_base_FGBuildablePowerStorage;

type FGBuildableRadarTower = docs_json_ts_0_4_2_11_classes_base_FGBuildableRadarTower;

type FGBuildableRailroadStation = docs_json_ts_0_4_2_11_classes_base_FGBuildableRailroadStation;

type FGBuildableRailroadTrack = docs_json_ts_0_4_2_11_classes_base_FGBuildableRailroadTrack;

type FGBuildableResourceExtractor_miner_mk1 = docs_json_ts_0_4_2_11_classes_base_FGBuildableResourceExtractor_miner_mk1;

type FGBuildableResourceExtractor_miner_mk2 = docs_json_ts_0_4_2_11_classes_base_FGBuildableResourceExtractor_miner_mk2;

type FGBuildableResourceExtractor_miner_mk3 = docs_json_ts_0_4_2_11_classes_base_FGBuildableResourceExtractor_miner_mk3;

type FGBuildableResourceExtractor_oil = docs_json_ts_0_4_2_11_classes_base_FGBuildableResourceExtractor_oil;

type FGBuildableResourceExtractor_water = docs_json_ts_0_4_2_11_classes_base_FGBuildableResourceExtractor_water;

type FGBuildableResourceSink = docs_json_ts_0_4_2_11_classes_base_FGBuildableResourceSink;

type FGBuildableResourceSinkShop = docs_json_ts_0_4_2_11_classes_base_FGBuildableResourceSinkShop;

type FGBuildableSnowDispenser = docs_json_ts_0_4_2_11_classes_base_FGBuildableSnowDispenser;

type FGBuildableSpaceElevator = docs_json_ts_0_4_2_11_classes_base_FGBuildableSpaceElevator;

type FGBuildableSplitterSmart = docs_json_ts_0_4_2_11_classes_base_FGBuildableSplitterSmart;

type FGBuildableStair = docs_json_ts_0_4_2_11_classes_base_FGBuildableStair;

type FGBuildableStorage = docs_json_ts_0_4_2_11_classes_base_FGBuildableStorage;

type FGBuildableTradingPost = docs_json_ts_0_4_2_11_classes_base_FGBuildableTradingPost;

type FGBuildableTrainPlatformCargo = docs_json_ts_0_4_2_11_classes_base_FGBuildableTrainPlatformCargo;

type FGBuildableTrainPlatformEmpty = docs_json_ts_0_4_2_11_classes_base_FGBuildableTrainPlatformEmpty;

type FGBuildableWalkway = docs_json_ts_0_4_2_11_classes_base_FGBuildableWalkway;

type FGBuildableWall = docs_json_ts_0_4_2_11_classes_base_FGBuildableWall;

type FGBuildableWaterPump = docs_json_ts_0_4_2_11_classes_base_FGBuildableResourceExtractor_water;

type FGBuildableWire = docs_json_ts_0_4_2_11_classes_base_FGBuildableWire;

type FGBuildingDescriptor = docs_json_ts_0_4_2_11_classes_base_FGBuildingDescriptor;

type FGColorGun = docs_json_ts_0_4_2_11_classes_base_FGColorGun;

type FGConsumableDescriptor = docs_json_ts_0_4_2_11_classes_base_FGConsumableDescriptor;

type FGConsumableEquipment = docs_json_ts_0_4_2_11_classes_base_FGConsumableEquipment;

type FGConveyorPoleStackable = docs_json_ts_0_4_2_11_classes_base_FGConveyorPoleStackable;

type FGEquipmentDescriptor = docs_json_ts_0_4_2_11_classes_base_FGEquipmentDescriptor;

type FGEquipmentZipline = docs_json_ts_0_4_2_11_classes_base_FGEquipmentZipline;

type FGHoverPack = docs_json_ts_0_4_2_11_classes_base_FGHoverPack;

type FGItemDescriptor = docs_json_ts_0_4_2_11_classes_base_FGItemDescriptor;

type FGItemDescriptorBiomass = docs_json_ts_0_4_2_11_classes_base_FGItemDescriptorBiomass;

type FGItemDescriptorNuclearFuel = docs_json_ts_0_4_2_11_classes_base_overridable_FGItemDescriptorNuclearFuel;

type FGNobeliskDetonator = docs_json_ts_0_4_2_11_classes_base_FGNobeliskDetonator;

type FGParachute = docs_json_ts_0_4_2_11_classes_base_FGParachute;

type FGPipeHyperStart = docs_json_ts_0_4_2_11_classes_base_FGPipeHyperStart;

type FGPoleDescriptor = docs_json_ts_0_4_2_11_classes_base_FGPoleDescriptor;

type FGPortableMinerDispenser = docs_json_ts_0_4_2_11_classes_base_FGPortableMinerDispenser;

type FGRecipe = docs_json_ts_0_4_2_11_classes_base_FGRecipe;

type FGResourceDescriptor = docs_json_ts_0_4_2_11_classes_base_FGResourceDescriptor;

type FGSchematic = docs_json_ts_0_4_2_11_classes_base_FGSchematic;

type FGSnowballWeapon = docs_json_ts_0_4_2_11_classes_base_FGSnowballWeapon;

type FGVehicleDescriptor_Desc_CyberWagon_C = docs_json_ts_0_4_2_11_classes_base_FGVehicleDescriptor_Desc_CyberWagon_C;

type FGVehicleDescriptor_Desc_DroneTransport_C = docs_json_ts_0_4_2_11_classes_base_FGVehicleDescriptor_Desc_DroneTransport_C;

type FGVehicleDescriptor_Desc_Explorer_C = docs_json_ts_0_4_2_11_classes_base_FGVehicleDescriptor_Desc_Explorer_C;

type FGVehicleDescriptor_Desc_FreightWagon_C = docs_json_ts_0_4_2_11_classes_base_FGVehicleDescriptor_Desc_FreightWagon_C;

type FGVehicleDescriptor_Desc_Locomotive_C = docs_json_ts_0_4_2_11_classes_base_FGVehicleDescriptor_Desc_Locomotive_C;

type FGVehicleDescriptor_Desc_Tractor_C = docs_json_ts_0_4_2_11_classes_base_FGVehicleDescriptor_Desc_Tractor_C;

type FGVehicleDescriptor_Desc_Truck_C = docs_json_ts_0_4_2_11_classes_base_FGVehicleDescriptor_Desc_Truck_C;

type FGWeapon_Equip_RebarGun_Projectile_C = docs_json_ts_0_4_2_11_classes_base_FGWeapon_Equip_RebarGun_Projectile_C;

type FGWeapon_Equip_Rifle_C = docs_json_ts_0_4_2_11_classes_base_FGWeapon_Equip_Rifle_C;

export type {
	FGBuildable_occupied,
	FGBuildable_powered_base,
	FGBuildable_tiered,
	FGBuildable_unoccupied_and_untiered,
	FGBuildableAttachmentMerger,
	FGBuildableAttachmentSplitter,
	FGBuildableCircuitSwitch,
	FGBuildableConveyorBelt,
	FGBuildableConveyorLift,
	FGBuildableDockingStation,
	FGBuildableDroneStation,
	FGBuildableFactory_jump_pad,
	FGBuildableFactory_landing_pad,
	FGBuildableFactory_not_a_pad,
	FGBuildableFactorySimpleProducer,
	FGBuildableFloodlight,
	FGBuildableFoundation,
	FGBuildableFrackingActivator,
	FGBuildableFrackingExtractor,
	FGBuildableGeneratorFuel_biomass,
	FGBuildableGeneratorFuel_coal,
	FGBuildableGeneratorFuel_fuel,
	FGBuildableGeneratorGeoThermal,
	FGBuildableGeneratorNuclear,
	FGBuildableJumppad,
	FGBuildableLadder,
	FGBuildableLightsControlPanel,
	FGBuildableLightSource,
	FGBuildableMAM,
	FGBuildableManufacturer_Build_AssemblerMk1_C,
	FGBuildableManufacturer_Build_Blender_C,
	FGBuildableManufacturer_Build_ConstructorMk1_C,
	FGBuildableManufacturer_Build_FoundryMk1_C,
	FGBuildableManufacturer_Build_ManufacturerMk1_C,
	FGBuildableManufacturer_Build_OilRefinery_C,
	FGBuildableManufacturer_Build_Packager_C,
	FGBuildableManufacturer_Build_SmelterMk1_C,
	FGBuildableManufacturerVariablePower,
	FGBuildablePipeHyper,
	FGBuildablePipeline,
	FGBuildablePipelineJunction,
	FGBuildablePipelinePump_pump,
	FGBuildablePipelinePump_valve,
	FGBuildablePipelineSupport,
	FGBuildablePipeReservoir,
	FGBuildablePole,
	FGBuildablePowerPole,
	FGBuildablePowerStorage,
	FGBuildableRadarTower,
	FGBuildableRailroadStation,
	FGBuildableRailroadTrack,
	FGBuildableResourceExtractor_miner_mk1,
	FGBuildableResourceExtractor_miner_mk2,
	FGBuildableResourceExtractor_miner_mk3,
	FGBuildableResourceExtractor_oil,
	FGBuildableResourceExtractor_water,
	FGBuildableResourceSink,
	FGBuildableResourceSinkShop,
	FGBuildableSnowDispenser,
	FGBuildableSpaceElevator,
	FGBuildableSplitterSmart,
	FGBuildableStair,
	FGBuildableStorage,
	FGBuildableTradingPost,
	FGBuildableTrainPlatformCargo,
	FGBuildableTrainPlatformEmpty,
	FGBuildableWalkway,
	FGBuildableWall,
	FGBuildableWaterPump,
	FGBuildableWire,
	FGBuildingDescriptor,
	FGColorGun,
	FGConsumableDescriptor,
	FGConsumableEquipment,
	FGConveyorPoleStackable,
	FGEquipmentDescriptor,
	FGEquipmentZipline,
	FGHoverPack,
	FGItemDescriptor,
	FGItemDescriptorBiomass,
	FGItemDescriptorNuclearFuel,
	FGNobeliskDetonator,
	FGParachute,
	FGPipeHyperStart,
	FGPoleDescriptor,
	FGPortableMinerDispenser,
	FGRecipe,
	FGResourceDescriptor,
	FGSchematic,
	FGSnowballWeapon,
	FGVehicleDescriptor_Desc_CyberWagon_C,
	FGVehicleDescriptor_Desc_DroneTransport_C,
	FGVehicleDescriptor_Desc_Explorer_C,
	FGVehicleDescriptor_Desc_FreightWagon_C,
	FGVehicleDescriptor_Desc_Locomotive_C,
	FGVehicleDescriptor_Desc_Tractor_C,
	FGVehicleDescriptor_Desc_Truck_C,
	FGWeapon_Equip_RebarGun_Projectile_C,
	FGWeapon_Equip_Rifle_C,
};
