/* eslint-disable @stylistic/max-len */

import type {
	FGBuildable_occupied as docs_json_ts_0_7_1_1_classes_base_FGBuildable_occupied,
	FGBuildable_tiered as docs_json_ts_0_7_1_1_classes_base_FGBuildable_tiered,
	FGBuildable_unoccupied_and_untiered as docs_json_ts_0_7_1_1_classes_base_FGBuildable_unoccupied_and_untiered,
	FGBuildableAttachmentMerger as docs_json_ts_0_7_1_1_classes_base_FGBuildableAttachmentMerger,
	FGBuildableAttachmentSplitter as docs_json_ts_0_7_1_1_classes_base_FGBuildableAttachmentSplitter,
	FGBuildableBeamLightweight as docs_json_ts_0_7_1_1_classes_base_FGBuildableBeamLightweight,
	FGBuildableBlueprintDesigner as docs_json_ts_0_7_1_1_classes_base_FGBuildableBlueprintDesigner,
	FGBuildableCircuitSwitch as docs_json_ts_0_7_1_1_classes_base_FGBuildableCircuitSwitch,
	FGBuildableConveyorBelt as docs_json_ts_0_7_1_1_classes_base_FGBuildableConveyorBelt,
	FGBuildableConveyorLift as docs_json_ts_0_7_1_1_classes_base_FGBuildableConveyorLift,
	FGBuildableCornerWall as docs_json_ts_0_7_1_1_classes_base_FGBuildableCornerWall,
	FGBuildableDockingStation as docs_json_ts_0_7_1_1_classes_base_FGBuildableDockingStation,
	FGBuildableDoor as docs_json_ts_0_7_1_1_classes_base_FGBuildableDoor,
	FGBuildableDroneStation as docs_json_ts_0_7_1_1_classes_base_FGBuildableDroneStation,
	FGBuildableFactory_jump_pad as docs_json_ts_0_7_1_1_classes_base_FGBuildableFactory_jump_pad,
	FGBuildableFactory_landing_pad as docs_json_ts_0_7_1_1_classes_base_FGBuildableFactory_landing_pad,
	FGBuildableFactory_not_pad as docs_json_ts_0_7_1_1_classes_base_FGBuildableFactory_not_pad,
	FGBuildableFactoryBuilding as docs_json_ts_0_7_1_1_classes_base_FGBuildableFactoryBuilding,
	FGBuildableFactorySimpleProducer as docs_json_ts_0_7_1_1_classes_base_FGBuildableFactorySimpleProducer,
	FGBuildableFloodlight as docs_json_ts_0_7_1_1_classes_base_FGBuildableFloodlight,
	FGBuildableFoundation as docs_json_ts_0_7_1_1_classes_base_FGBuildableFoundation,
	FGBuildableFoundationLightweight as docs_json_ts_0_7_1_1_classes_base_FGBuildableFoundationLightweight,
	FGBuildableFrackingActivator as docs_json_ts_0_7_1_1_classes_base_FGBuildableFrackingActivator,
	FGBuildableFrackingExtractor as docs_json_ts_0_7_1_1_classes_base_FGBuildableFrackingExtractor,
	FGBuildableGeneratorFuel_biomass as docs_json_ts_0_7_1_1_classes_base_FGBuildableGeneratorFuel_biomass,
	FGBuildableGeneratorFuel_coal as docs_json_ts_0_7_1_1_classes_base_FGBuildableGeneratorFuel_coal,
	FGBuildableGeneratorFuel_fuel as docs_json_ts_0_7_1_1_classes_base_FGBuildableGeneratorFuel_fuel,
	FGBuildableGeneratorGeoThermal as docs_json_ts_0_7_1_1_classes_base_FGBuildableGeneratorGeoThermal,
	FGBuildableGeneratorNuclear as docs_json_ts_0_7_1_1_classes_base_FGBuildableGeneratorNuclear,
	FGBuildableJumppad as docs_json_ts_0_7_1_1_classes_base_FGBuildableJumppad,
	FGBuildableLadder as docs_json_ts_0_7_1_1_classes_base_FGBuildableLadder,
	FGBuildableLightsControlPanel as docs_json_ts_0_7_1_1_classes_base_FGBuildableLightsControlPanel,
	FGBuildableLightSource_Build_CeilingLight_C as docs_json_ts_0_7_1_1_classes_base_FGBuildableLightSource_Build_CeilingLight_C,
	FGBuildableLightSource_Build_StreetLight_C as docs_json_ts_0_7_1_1_classes_base_FGBuildableLightSource_Build_StreetLight_C,
	FGBuildableMAM as docs_json_ts_0_7_1_1_classes_base_FGBuildableMAM,
	FGBuildableManufacturer_Build_AssemblerMk1_C as docs_json_ts_0_7_1_1_classes_base_FGBuildableManufacturer_Build_AssemblerMk1_C,
	FGBuildableManufacturer_Build_Blender_C as docs_json_ts_0_7_1_1_classes_base_FGBuildableManufacturer_Build_Blender_C,
	FGBuildableManufacturer_Build_ConstructorMk1_C as docs_json_ts_0_7_1_1_classes_base_FGBuildableManufacturer_Build_ConstructorMk1_C,
	FGBuildableManufacturer_Build_FoundryMk1_C as docs_json_ts_0_7_1_1_classes_base_FGBuildableManufacturer_Build_FoundryMk1_C,
	FGBuildableManufacturer_Build_HadronCollider_C as docs_json_ts_0_7_1_1_classes_base_FGBuildableManufacturer_Build_HadronCollider_C,
	FGBuildableManufacturer_Build_ManufacturerMk1_C as docs_json_ts_0_7_1_1_classes_base_FGBuildableManufacturer_Build_ManufacturerMk1_C,
	FGBuildableManufacturer_Build_OilRefinery_C as docs_json_ts_0_7_1_1_classes_base_FGBuildableManufacturer_Build_OilRefinery_C,
	FGBuildableManufacturer_Build_Packager_C as docs_json_ts_0_7_1_1_classes_base_FGBuildableManufacturer_Build_Packager_C,
	FGBuildableManufacturer_Build_SmelterMk1_C as docs_json_ts_0_7_1_1_classes_base_FGBuildableManufacturer_Build_SmelterMk1_C,
	FGBuildablePassthrough as docs_json_ts_0_7_1_1_classes_base_FGBuildablePassthrough,
	FGBuildablePillarLightweight as docs_json_ts_0_7_1_1_classes_base_FGBuildablePillarLightweight,
	FGBuildablePipeHyper as docs_json_ts_0_7_1_1_classes_base_FGBuildablePipeHyper,
	FGBuildablePipeline as docs_json_ts_0_7_1_1_classes_base_FGBuildablePipeline,
	FGBuildablePipelineJunction as docs_json_ts_0_7_1_1_classes_base_FGBuildablePipelineJunction,
	FGBuildablePipelinePump_pump as docs_json_ts_0_7_1_1_classes_base_FGBuildablePipelinePump_pump,
	FGBuildablePipelinePump_valve as docs_json_ts_0_7_1_1_classes_base_FGBuildablePipelinePump_valve,
	FGBuildablePipelineSupport as docs_json_ts_0_7_1_1_classes_base_FGBuildablePipelineSupport,
	FGBuildablePipeReservoir as docs_json_ts_0_7_1_1_classes_base_FGBuildablePipeReservoir,
	FGBuildablePole as docs_json_ts_0_7_1_1_classes_base_FGBuildablePole,
	FGBuildablePoleLightweight as docs_json_ts_0_7_1_1_classes_base_FGBuildablePoleLightweight,
	FGBuildablePowerPole as docs_json_ts_0_7_1_1_classes_base_FGBuildablePowerPole,
	FGBuildablePowerStorage as docs_json_ts_0_7_1_1_classes_base_FGBuildablePowerStorage,
	FGBuildableRadarTower as docs_json_ts_0_7_1_1_classes_base_FGBuildableRadarTower,
	FGBuildableRailroadSignal_block as docs_json_ts_0_7_1_1_classes_base_FGBuildableRailroadSignal_block,
	FGBuildableRailroadSignal_path as docs_json_ts_0_7_1_1_classes_base_FGBuildableRailroadSignal_path,
	FGBuildableRailroadStation as docs_json_ts_0_7_1_1_classes_base_FGBuildableRailroadStation,
	FGBuildableRailroadTrack as docs_json_ts_0_7_1_1_classes_base_FGBuildableRailroadTrack,
	FGBuildableRamp as docs_json_ts_0_7_1_1_classes_base_FGBuildableRamp,
	FGBuildableResourceExtractor_miner_mk1 as docs_json_ts_0_7_1_1_classes_base_FGBuildableResourceExtractor_miner_mk1,
	FGBuildableResourceExtractor_miner_mk2 as docs_json_ts_0_7_1_1_classes_base_FGBuildableResourceExtractor_miner_mk2,
	FGBuildableResourceExtractor_miner_mk3 as docs_json_ts_0_7_1_1_classes_base_FGBuildableResourceExtractor_miner_mk3,
	FGBuildableResourceExtractor_oil as docs_json_ts_0_7_1_1_classes_base_FGBuildableResourceExtractor_oil,
	FGBuildableResourceExtractor_water as docs_json_ts_0_7_1_1_classes_base_FGBuildableResourceExtractor_water,
	FGBuildableResourceSink as docs_json_ts_0_7_1_1_classes_base_FGBuildableResourceSink,
	FGBuildableResourceSinkShop as docs_json_ts_0_7_1_1_classes_base_FGBuildableResourceSinkShop,
	FGBuildableSnowDispenser as docs_json_ts_0_7_1_1_classes_base_FGBuildableSnowDispenser,
	FGBuildableSpaceElevator as docs_json_ts_0_7_1_1_classes_base_FGBuildableSpaceElevator,
	FGBuildableSplitterSmart as docs_json_ts_0_7_1_1_classes_base_FGBuildableSplitterSmart,
	FGBuildableStair as docs_json_ts_0_7_1_1_classes_base_FGBuildableStair,
	FGBuildableStorage as docs_json_ts_0_7_1_1_classes_base_FGBuildableStorage,
	FGBuildableTradingPost as docs_json_ts_0_7_1_1_classes_base_FGBuildableTradingPost,
	FGBuildableTrainPlatformCargo as docs_json_ts_0_7_1_1_classes_base_FGBuildableTrainPlatformCargo,
	FGBuildableTrainPlatformEmpty as docs_json_ts_0_7_1_1_classes_base_FGBuildableTrainPlatformEmpty,
	FGBuildableWalkway as docs_json_ts_0_7_1_1_classes_base_FGBuildableWalkway,
	FGBuildableWalkwayLightweight as docs_json_ts_0_7_1_1_classes_base_FGBuildableWalkwayLightweight,
	FGBuildableWall as docs_json_ts_0_7_1_1_classes_base_FGBuildableWall,
	FGBuildableWallLightweight as docs_json_ts_0_7_1_1_classes_base_FGBuildableWallLightweight,
	FGBuildableWidgetSign as docs_json_ts_0_7_1_1_classes_base_FGBuildableWidgetSign,
	FGBuildableWire as docs_json_ts_0_7_1_1_classes_base_FGBuildableWire,
	FGConveyorPoleStackable as docs_json_ts_0_7_1_1_classes_base_FGConveyorPoleStackable,
	FGJetPack as docs_json_ts_0_7_1_1_classes_base_FGJetPack,
	FGPipeHyperStart as docs_json_ts_0_7_1_1_classes_base_FGPipeHyperStart,
} from './classes/Base.ts';

type FGBuildable_occupied = docs_json_ts_0_7_1_1_classes_base_FGBuildable_occupied;

type FGBuildable_tiered = docs_json_ts_0_7_1_1_classes_base_FGBuildable_tiered;

type FGBuildable_unoccupied_and_untiered = docs_json_ts_0_7_1_1_classes_base_FGBuildable_unoccupied_and_untiered;

type FGBuildableAttachmentMerger = docs_json_ts_0_7_1_1_classes_base_FGBuildableAttachmentMerger;

type FGBuildableAttachmentSplitter = docs_json_ts_0_7_1_1_classes_base_FGBuildableAttachmentSplitter;

type FGBuildableBeamLightweight = docs_json_ts_0_7_1_1_classes_base_FGBuildableBeamLightweight;

type FGBuildableBlueprintDesigner = docs_json_ts_0_7_1_1_classes_base_FGBuildableBlueprintDesigner;

type FGBuildableCircuitSwitch = docs_json_ts_0_7_1_1_classes_base_FGBuildableCircuitSwitch;

type FGBuildableConveyorBelt = docs_json_ts_0_7_1_1_classes_base_FGBuildableConveyorBelt;

type FGBuildableConveyorLift = docs_json_ts_0_7_1_1_classes_base_FGBuildableConveyorLift;

type FGBuildableCornerWall = docs_json_ts_0_7_1_1_classes_base_FGBuildableCornerWall;

type FGBuildableDockingStation = docs_json_ts_0_7_1_1_classes_base_FGBuildableDockingStation;

type FGBuildableDoor = docs_json_ts_0_7_1_1_classes_base_FGBuildableDoor;

type FGBuildableDroneStation = docs_json_ts_0_7_1_1_classes_base_FGBuildableDroneStation;

type FGBuildableFactory_jump_pad = docs_json_ts_0_7_1_1_classes_base_FGBuildableFactory_jump_pad;

type FGBuildableFactory_landing_pad = docs_json_ts_0_7_1_1_classes_base_FGBuildableFactory_landing_pad;

type FGBuildableFactory_not_pad = docs_json_ts_0_7_1_1_classes_base_FGBuildableFactory_not_pad;

type FGBuildableFactoryBuilding = docs_json_ts_0_7_1_1_classes_base_FGBuildableFactoryBuilding;

type FGBuildableFactorySimpleProducer = docs_json_ts_0_7_1_1_classes_base_FGBuildableFactorySimpleProducer;

type FGBuildableFloodlight = docs_json_ts_0_7_1_1_classes_base_FGBuildableFloodlight;

type FGBuildableFoundation = docs_json_ts_0_7_1_1_classes_base_FGBuildableFoundation;

type FGBuildableFoundationLightweight = docs_json_ts_0_7_1_1_classes_base_FGBuildableFoundationLightweight;

type FGBuildableFrackingActivator = docs_json_ts_0_7_1_1_classes_base_FGBuildableFrackingActivator;

type FGBuildableFrackingExtractor = docs_json_ts_0_7_1_1_classes_base_FGBuildableFrackingExtractor;

type FGBuildableGeneratorFuel_biomass = docs_json_ts_0_7_1_1_classes_base_FGBuildableGeneratorFuel_biomass;

type FGBuildableGeneratorFuel_coal = docs_json_ts_0_7_1_1_classes_base_FGBuildableGeneratorFuel_coal;

type FGBuildableGeneratorFuel_fuel = docs_json_ts_0_7_1_1_classes_base_FGBuildableGeneratorFuel_fuel;

type FGBuildableGeneratorGeoThermal = docs_json_ts_0_7_1_1_classes_base_FGBuildableGeneratorGeoThermal;

type FGBuildableGeneratorNuclear = docs_json_ts_0_7_1_1_classes_base_FGBuildableGeneratorNuclear;

type FGBuildableJumppad = docs_json_ts_0_7_1_1_classes_base_FGBuildableJumppad;

type FGBuildableLadder = docs_json_ts_0_7_1_1_classes_base_FGBuildableLadder;

type FGBuildableLightsControlPanel = docs_json_ts_0_7_1_1_classes_base_FGBuildableLightsControlPanel;

type FGBuildableLightSource_Build_CeilingLight_C = docs_json_ts_0_7_1_1_classes_base_FGBuildableLightSource_Build_CeilingLight_C;

type FGBuildableLightSource_Build_StreetLight_C = docs_json_ts_0_7_1_1_classes_base_FGBuildableLightSource_Build_StreetLight_C;

type FGBuildableMAM = docs_json_ts_0_7_1_1_classes_base_FGBuildableMAM;

type FGBuildableManufacturer_Build_AssemblerMk1_C = docs_json_ts_0_7_1_1_classes_base_FGBuildableManufacturer_Build_AssemblerMk1_C;

type FGBuildableManufacturer_Build_Blender_C = docs_json_ts_0_7_1_1_classes_base_FGBuildableManufacturer_Build_Blender_C;

type FGBuildableManufacturer_Build_ConstructorMk1_C = docs_json_ts_0_7_1_1_classes_base_FGBuildableManufacturer_Build_ConstructorMk1_C;

type FGBuildableManufacturer_Build_FoundryMk1_C = docs_json_ts_0_7_1_1_classes_base_FGBuildableManufacturer_Build_FoundryMk1_C;

type FGBuildableManufacturer_Build_HadronCollider_C = docs_json_ts_0_7_1_1_classes_base_FGBuildableManufacturer_Build_HadronCollider_C;

type FGBuildableManufacturer_Build_ManufacturerMk1_C = docs_json_ts_0_7_1_1_classes_base_FGBuildableManufacturer_Build_ManufacturerMk1_C;

type FGBuildableManufacturer_Build_OilRefinery_C = docs_json_ts_0_7_1_1_classes_base_FGBuildableManufacturer_Build_OilRefinery_C;

type FGBuildableManufacturer_Build_Packager_C = docs_json_ts_0_7_1_1_classes_base_FGBuildableManufacturer_Build_Packager_C;

type FGBuildableManufacturer_Build_SmelterMk1_C = docs_json_ts_0_7_1_1_classes_base_FGBuildableManufacturer_Build_SmelterMk1_C;

type FGBuildablePassthrough = docs_json_ts_0_7_1_1_classes_base_FGBuildablePassthrough;

type FGBuildablePillarLightweight = docs_json_ts_0_7_1_1_classes_base_FGBuildablePillarLightweight;

type FGBuildablePipeHyper = docs_json_ts_0_7_1_1_classes_base_FGBuildablePipeHyper;

type FGBuildablePipeline = docs_json_ts_0_7_1_1_classes_base_FGBuildablePipeline;

type FGBuildablePipelineJunction = docs_json_ts_0_7_1_1_classes_base_FGBuildablePipelineJunction;

type FGBuildablePipelinePump_pump = docs_json_ts_0_7_1_1_classes_base_FGBuildablePipelinePump_pump;

type FGBuildablePipelinePump_valve = docs_json_ts_0_7_1_1_classes_base_FGBuildablePipelinePump_valve;

type FGBuildablePipelineSupport = docs_json_ts_0_7_1_1_classes_base_FGBuildablePipelineSupport;

type FGBuildablePipeReservoir = docs_json_ts_0_7_1_1_classes_base_FGBuildablePipeReservoir;

type FGBuildablePole = docs_json_ts_0_7_1_1_classes_base_FGBuildablePole;

type FGBuildablePoleLightweight = docs_json_ts_0_7_1_1_classes_base_FGBuildablePoleLightweight;

type FGBuildablePowerPole = docs_json_ts_0_7_1_1_classes_base_FGBuildablePowerPole;

type FGBuildablePowerStorage = docs_json_ts_0_7_1_1_classes_base_FGBuildablePowerStorage;

type FGBuildableRadarTower = docs_json_ts_0_7_1_1_classes_base_FGBuildableRadarTower;

type FGBuildableRailroadSignal_block = docs_json_ts_0_7_1_1_classes_base_FGBuildableRailroadSignal_block;

type FGBuildableRailroadSignal_path = docs_json_ts_0_7_1_1_classes_base_FGBuildableRailroadSignal_path;

type FGBuildableRailroadStation = docs_json_ts_0_7_1_1_classes_base_FGBuildableRailroadStation;

type FGBuildableRailroadTrack = docs_json_ts_0_7_1_1_classes_base_FGBuildableRailroadTrack;

type FGBuildableRamp = docs_json_ts_0_7_1_1_classes_base_FGBuildableRamp;

type FGBuildableResourceExtractor_miner_mk1 = docs_json_ts_0_7_1_1_classes_base_FGBuildableResourceExtractor_miner_mk1;

type FGBuildableResourceExtractor_miner_mk2 = docs_json_ts_0_7_1_1_classes_base_FGBuildableResourceExtractor_miner_mk2;

type FGBuildableResourceExtractor_miner_mk3 = docs_json_ts_0_7_1_1_classes_base_FGBuildableResourceExtractor_miner_mk3;

type FGBuildableResourceExtractor_oil = docs_json_ts_0_7_1_1_classes_base_FGBuildableResourceExtractor_oil;

type FGBuildableResourceSink = docs_json_ts_0_7_1_1_classes_base_FGBuildableResourceSink;

type FGBuildableResourceSinkShop = docs_json_ts_0_7_1_1_classes_base_FGBuildableResourceSinkShop;

type FGBuildableSnowDispenser = docs_json_ts_0_7_1_1_classes_base_FGBuildableSnowDispenser;

type FGBuildableSpaceElevator = docs_json_ts_0_7_1_1_classes_base_FGBuildableSpaceElevator;

type FGBuildableSplitterSmart = docs_json_ts_0_7_1_1_classes_base_FGBuildableSplitterSmart;

type FGBuildableStair = docs_json_ts_0_7_1_1_classes_base_FGBuildableStair;

type FGBuildableStorage = docs_json_ts_0_7_1_1_classes_base_FGBuildableStorage;

type FGBuildableTradingPost = docs_json_ts_0_7_1_1_classes_base_FGBuildableTradingPost;

type FGBuildableTrainPlatformCargo = docs_json_ts_0_7_1_1_classes_base_FGBuildableTrainPlatformCargo;

type FGBuildableTrainPlatformEmpty = docs_json_ts_0_7_1_1_classes_base_FGBuildableTrainPlatformEmpty;

type FGBuildableWalkway = docs_json_ts_0_7_1_1_classes_base_FGBuildableWalkway;

type FGBuildableWalkwayLightweight = docs_json_ts_0_7_1_1_classes_base_FGBuildableWalkwayLightweight;

type FGBuildableWall = docs_json_ts_0_7_1_1_classes_base_FGBuildableWall;

type FGBuildableWallLightweight = docs_json_ts_0_7_1_1_classes_base_FGBuildableWallLightweight;

type FGBuildableWaterPump = docs_json_ts_0_7_1_1_classes_base_FGBuildableResourceExtractor_water;

type FGBuildableWidgetSign = docs_json_ts_0_7_1_1_classes_base_FGBuildableWidgetSign;

type FGBuildableWire = docs_json_ts_0_7_1_1_classes_base_FGBuildableWire;

type FGConveyorPoleStackable = docs_json_ts_0_7_1_1_classes_base_FGConveyorPoleStackable;

type FGJetPack = docs_json_ts_0_7_1_1_classes_base_FGJetPack;

type FGPipeHyperStart = docs_json_ts_0_7_1_1_classes_base_FGPipeHyperStart;

export type {
	FGBuildable_occupied,
	FGBuildable_tiered,
	FGBuildable_unoccupied_and_untiered,
	FGBuildableAttachmentMerger,
	FGBuildableAttachmentSplitter,
	FGBuildableBeamLightweight,
	FGBuildableBlueprintDesigner,
	FGBuildableCircuitSwitch,
	FGBuildableConveyorBelt,
	FGBuildableConveyorLift,
	FGBuildableCornerWall,
	FGBuildableDockingStation,
	FGBuildableDoor,
	FGBuildableDroneStation,
	FGBuildableFactory_jump_pad,
	FGBuildableFactory_landing_pad,
	FGBuildableFactory_not_pad,
	FGBuildableFactoryBuilding,
	FGBuildableFactorySimpleProducer,
	FGBuildableFloodlight,
	FGBuildableFoundation,
	FGBuildableFoundationLightweight,
	FGBuildableFrackingActivator,
	FGBuildableFrackingExtractor,
	FGBuildableGeneratorFuel_biomass,
	FGBuildableGeneratorFuel_coal,
	FGBuildableGeneratorFuel_fuel,
	FGBuildableGeneratorGeoThermal,
	FGBuildableGeneratorNuclear,
	FGBuildableJumppad,
	FGBuildableLadder,
	FGBuildableLightsControlPanel,
	FGBuildableLightSource_Build_CeilingLight_C,
	FGBuildableLightSource_Build_StreetLight_C,
	FGBuildableMAM,
	FGBuildableManufacturer_Build_AssemblerMk1_C,
	FGBuildableManufacturer_Build_Blender_C,
	FGBuildableManufacturer_Build_ConstructorMk1_C,
	FGBuildableManufacturer_Build_FoundryMk1_C,
	FGBuildableManufacturer_Build_HadronCollider_C,
	FGBuildableManufacturer_Build_ManufacturerMk1_C,
	FGBuildableManufacturer_Build_OilRefinery_C,
	FGBuildableManufacturer_Build_Packager_C,
	FGBuildableManufacturer_Build_SmelterMk1_C,
	FGBuildablePassthrough,
	FGBuildablePillarLightweight,
	FGBuildablePipeHyper,
	FGBuildablePipeline,
	FGBuildablePipelineJunction,
	FGBuildablePipelinePump_pump,
	FGBuildablePipelinePump_valve,
	FGBuildablePipelineSupport,
	FGBuildablePipeReservoir,
	FGBuildablePole,
	FGBuildablePoleLightweight,
	FGBuildablePowerPole,
	FGBuildablePowerStorage,
	FGBuildableRadarTower,
	FGBuildableRailroadSignal_block,
	FGBuildableRailroadSignal_path,
	FGBuildableRailroadStation,
	FGBuildableRailroadTrack,
	FGBuildableRamp,
	FGBuildableResourceExtractor_miner_mk1,
	FGBuildableResourceExtractor_miner_mk2,
	FGBuildableResourceExtractor_miner_mk3,
	FGBuildableResourceExtractor_oil,
	FGBuildableResourceSink,
	FGBuildableResourceSinkShop,
	FGBuildableSnowDispenser,
	FGBuildableSpaceElevator,
	FGBuildableSplitterSmart,
	FGBuildableStair,
	FGBuildableStorage,
	FGBuildableTradingPost,
	FGBuildableTrainPlatformCargo,
	FGBuildableTrainPlatformEmpty,
	FGBuildableWalkway,
	FGBuildableWalkwayLightweight,
	FGBuildableWall,
	FGBuildableWallLightweight,
	FGBuildableWaterPump,
	FGBuildableWidgetSign,
	FGBuildableWire,
	FGConveyorPoleStackable,
	FGJetPack,
	FGPipeHyperStart,
};
