/* eslint-disable @stylistic/max-len */

import type {
	FGAmmoType_base as docs_json_ts_0_6_1_5_classes_base_FGAmmoType_base,
	FGAmmoType_version_specific as docs_json_ts_0_6_1_5_classes_base_FGAmmoType_version_specific,
	FGAmmoTypeInstantHit_Desc_CartridgeChaos_C_version_specific as docs_json_ts_0_6_1_5_classes_base_FGAmmoTypeInstantHit_Desc_CartridgeChaos_C_version_specific,
	FGAmmoTypeInstantHit_version_specific as docs_json_ts_0_6_1_5_classes_base_FGAmmoTypeInstantHit_version_specific,
	FGAmmoTypeProjectile_version_specific as docs_json_ts_0_6_1_5_classes_base_FGAmmoTypeProjectile_version_specific,
	FGAmmoTypeSpreadshot_version_specific as docs_json_ts_0_6_1_5_classes_base_FGAmmoTypeSpreadshot_version_specific,
	FGBuildable_base_version_specific as docs_json_ts_0_6_1_5_classes_base_FGBuildable_base_version_specific,
	FGBuildable_foundation_mDisableSnapOn as docs_json_ts_0_6_1_5_classes_base_FGBuildable_foundation_mDisableSnapOn,
	FGBuildable_with_depth as docs_json_ts_0_6_1_5_classes_base_FGBuildable_with_depth,
	FGBuildableFoundation_version_specific as docs_json_ts_0_6_1_5_classes_base_FGBuildableFoundation_version_specific,
	FGBuildableManufacturer_Build_SmelterMk1_C_base as docs_json_ts_0_6_1_5_classes_base_FGBuildableManufacturer_Build_SmelterMk1_C_base,
	FGBuildablePipeline_version_specific as docs_json_ts_0_6_1_5_classes_base_FGBuildablePipeline_version_specific,
	FGBuildableRadarTower_version_specific as docs_json_ts_0_6_1_5_classes_base_FGBuildableRadarTower_version_specific,
	FGBuildableResourceExtractor_base_version_specific_base as docs_json_ts_0_6_1_5_classes_base_FGBuildableResourceExtractor_base_version_specific_base,
	FGBuildableTrainPlatformCargo_version_specific as docs_json_ts_0_6_1_5_classes_base_FGBuildableTrainPlatformCargo_version_specific,
	FGChainsaw_version_specific as docs_json_ts_0_6_1_5_classes_base_FGChainsaw_version_specific,
	FGDescriptor as docs_json_ts_0_6_1_5_classes_base_FGDescriptor,
	FGEquipment_noisy_version_specific as docs_json_ts_0_6_1_5_classes_base_FGEquipment_noisy_version_specific,
	FGEquipment_version_specific as docs_json_ts_0_6_1_5_classes_base_FGEquipment_version_specific,
	FGEquipmentStunSpear_base_version_specific as docs_json_ts_0_6_1_5_classes_base_FGEquipmentStunSpear_base_version_specific,
	FGItemDescriptor_version_specific as docs_json_ts_0_6_1_5_classes_base_FGItemDescriptor_version_specific,
	FGJumpingStilts_version_specific as docs_json_ts_0_6_1_5_classes_base_FGJumpingStilts_version_specific,
	FGSchematic_version_specific as docs_json_ts_0_6_1_5_classes_base_FGSchematic_version_specific,
	FGSuitBase_version_specific as docs_json_ts_0_6_1_5_classes_base_FGSuitBase_version_specific,
	FGVehicleDescriptor_Desc_CyberWagon_C as docs_json_ts_0_6_1_5_classes_base_FGVehicleDescriptor_Desc_CyberWagon_C,
	FGVehicleDescriptor_Desc_DroneTransport_C as docs_json_ts_0_6_1_5_classes_base_FGVehicleDescriptor_Desc_DroneTransport_C,
	FGVehicleDescriptor_Desc_Explorer_C as docs_json_ts_0_6_1_5_classes_base_FGVehicleDescriptor_Desc_Explorer_C,
	FGVehicleDescriptor_Desc_FreightWagon_C as docs_json_ts_0_6_1_5_classes_base_FGVehicleDescriptor_Desc_FreightWagon_C,
	FGVehicleDescriptor_Desc_Locomotive_C as docs_json_ts_0_6_1_5_classes_base_FGVehicleDescriptor_Desc_Locomotive_C,
	FGVehicleDescriptor_Desc_Tractor_C as docs_json_ts_0_6_1_5_classes_base_FGVehicleDescriptor_Desc_Tractor_C,
	FGVehicleDescriptor_Desc_Truck_C as docs_json_ts_0_6_1_5_classes_base_FGVehicleDescriptor_Desc_Truck_C,
	FGWeapon_base as docs_json_ts_0_6_1_5_classes_base_FGWeapon_base,
	has_mIsInverted as docs_json_ts_0_6_1_5_classes_base_has_mIsInverted,
} from './../0.6.1.5/classes/Base.ts';

import type {
	FGAmmoType_base as docs_json_ts_0_6_1_5_classes_base_overridable_FGAmmoType_base,
	FGAmmoType_version_specific as docs_json_ts_0_6_1_5_classes_base_overridable_FGAmmoType_version_specific,
	FGAmmoTypeProjectile_version_specific as docs_json_ts_0_6_1_5_classes_base_overridable_FGAmmoTypeProjectile_version_specific,
	FGBuildable_base_version_specific as docs_json_ts_0_6_1_5_classes_base_overridable_FGBuildable_base_version_specific,
	FGBuildableRadarTower_version_specific as docs_json_ts_0_6_1_5_classes_base_overridable_FGBuildableRadarTower_version_specific,
	FGItemDescriptor_base as docs_json_ts_0_6_1_5_classes_base_overridable_FGItemDescriptor_base,
	FGItemDescriptor_version_specific as docs_json_ts_0_6_1_5_classes_base_overridable_FGItemDescriptor_version_specific,
} from './../0.6.1.5/classes/Base.1.0.1.4.ts';

import type {
	FGAmmoType_pre_1_1 as docs_json_ts_0_8_3_3_classes_base_overridable_FGAmmoType_pre_1_1,
	FGAmmoType_version_specific as docs_json_ts_0_8_3_3_classes_base_overridable_FGAmmoType_version_specific,
	FGBuildableRailroadTrack_version_specific as docs_json_ts_0_8_3_3_classes_base_overridable_FGBuildableRailroadTrack_version_specific,
	FGConsumableEquipment_version_specific as docs_json_ts_0_8_3_3_classes_base_overridable_FGConsumableEquipment_version_specific,
	FGEquipment_version_specific as docs_json_ts_0_8_3_3_classes_base_overridable_FGEquipment_version_specific,
	FGSchematic_has_mSchematicIcon as docs_json_ts_0_8_3_3_classes_base_overridable_FGSchematic_has_mSchematicIcon,
	FGSchematic_version_specific as docs_json_ts_0_8_3_3_classes_base_overridable_FGSchematic_version_specific,
} from './../0.8.3.3/classes/Base.1.0.1.4.ts';

import type {
	has_mSubCategories as docs_json_ts_0_6_1_5_overridable_has_mSubCategories,
} from './../0.6.1.5/types/overridable--1.0.1.4.ts';

import type {
	FGAmmoTypeProjectile_version_specific as docs_json_ts_0_8_3_3_classes_base_FGAmmoTypeProjectile_version_specific,
	FGBuildable_has_mOnCircuitsChanged as docs_json_ts_0_8_3_3_classes_base_FGBuildable_has_mOnCircuitsChanged,
	FGBuildable_version_specific as docs_json_ts_0_8_3_3_classes_base_FGBuildable_version_specific,
	FGBuildable_with_mTickExponent as docs_json_ts_0_8_3_3_classes_base_FGBuildable_with_mTickExponent,
	FGBuildableBlueprintDesigner_version_specific as docs_json_ts_0_8_3_3_classes_base_FGBuildableBlueprintDesigner_version_specific,
	FGBuildableConveyorBelt_version_specific as docs_json_ts_0_8_3_3_classes_base_FGBuildableConveyorBelt_version_specific,
	FGBuildableJumppad_version_specific as docs_json_ts_0_8_3_3_classes_base_FGBuildableJumppad_version_specific,
	FGBuildablePassthrough_version_specific as docs_json_ts_0_8_3_3_classes_base_FGBuildablePassthrough_version_specific,
	FGBuildablePowerPole_version_specific as docs_json_ts_0_8_3_3_classes_base_FGBuildablePowerPole_version_specific,
	FGBuildablePriorityPowerSwitch_version_specific as docs_json_ts_0_8_3_3_classes_base_FGBuildablePriorityPowerSwitch_version_specific,
	FGBuildableRailroadSignal_version_specific as docs_json_ts_0_8_3_3_classes_base_FGBuildableRailroadSignal_version_specific,
	FGBuildableWidgetSign_version_specific as docs_json_ts_0_8_3_3_classes_base_FGBuildableWidgetSign_version_specific,
	FGBuildableWire_version_specific as docs_json_ts_0_8_3_3_classes_base_FGBuildableWire_version_specific,
	FGChainsaw_version_specific as docs_json_ts_0_8_3_3_classes_base_FGChainsaw_version_specific,
	FGEquipmentStunSpear_base_version_specific as docs_json_ts_0_8_3_3_classes_base_FGEquipmentStunSpear_base_version_specific,
	FGGasMask_version_specific as docs_json_ts_0_8_3_3_classes_base_FGGasMask_version_specific,
	FGJetPack_version_specific as docs_json_ts_0_8_3_3_classes_base_FGJetPack_version_specific,
	FGObjectScanner_version_specific as docs_json_ts_0_8_3_3_classes_base_FGObjectScanner_version_specific,
	FGParachute_version_specific as docs_json_ts_0_8_3_3_classes_base_FGParachute_version_specific,
} from './../0.8.3.3/classes/Base.ts';

import type {
	FGItemDescriptor_version_specific_mDescriptorStatBars_item as docs_json_ts_1_0_1_4_properties_FGItemDescriptor_version_specific_mDescriptorStatBars_item,
	FGJetPackFuelParameters_quoted as docs_json_ts_1_0_1_4_properties_FGJetPackFuelParameters_quoted,
	FGSchematic_has_mSchematicDependencies as docs_json_ts_1_0_1_4_properties_FGSchematic_has_mSchematicDependencies,
	FGTrainPlatformConnection_quoted as docs_json_ts_1_0_1_4_properties_FGTrainPlatformConnection_quoted,
	IconID as docs_json_ts_1_0_1_4_properties_IconID,
	mClearanceData_item as docs_json_ts_1_0_1_4_properties_mClearanceData_item,
	mMagazineMeshMaterials_item as docs_json_ts_1_0_1_4_properties_mMagazineMeshMaterials_item,
	Montages as docs_json_ts_1_0_1_4_properties_Montages,
	Montages_item as docs_json_ts_1_0_1_4_properties_Montages_item,
	mProducedIn as docs_json_ts_1_0_1_4_properties_mProducedIn,
	mStatisticGameplayTag as docs_json_ts_1_0_1_4_properties_mStatisticGameplayTag,
	mUnlocks_item as docs_json_ts_1_0_1_4_properties_mUnlocks_item,
	Tier as docs_json_ts_1_0_1_4_properties_Tier,
} from './types/properties.ts';

import type {
	FGBuildable_base_version_specific as docs_json_ts_0_3_7_7_classes_base_FGBuildable_base_version_specific,
	FGBuildable_docking_station_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildable_docking_station_base_base_base,
	FGBuildable_docking_station_base_with_mMapText as docs_json_ts_0_3_7_7_classes_base_FGBuildable_docking_station_base_with_mMapText,
	FGBuildable_occupied_base as docs_json_ts_0_3_7_7_classes_base_FGBuildable_occupied_base,
	FGBuildable_pole_base as docs_json_ts_0_3_7_7_classes_base_FGBuildable_pole_base,
	FGBuildable_powered_storage_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildable_powered_storage_base_base_base,
	FGBuildable_powered_version_specific as docs_json_ts_0_3_7_7_classes_base_FGBuildable_powered_version_specific,
	FGBuildable_spline as docs_json_ts_0_3_7_7_classes_base_FGBuildable_spline,
	FGBuildable_tiered_base as docs_json_ts_0_3_7_7_classes_base_FGBuildable_tiered_base,
	FGBuildable_with_height_and_width_base as docs_json_ts_0_3_7_7_classes_base_FGBuildable_with_height_and_width_base,
	FGBuildable_with_height_base as docs_json_ts_0_3_7_7_classes_base_FGBuildable_with_height_base,
	FGBuildable_with_mLength as docs_json_ts_0_3_7_7_classes_base_FGBuildable_with_mLength,
	FGBuildable_with_size_and_elevation_base as docs_json_ts_0_3_7_7_classes_base_FGBuildable_with_size_and_elevation_base,
	FGBuildable_with_size_and_elevation_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildable_with_size_and_elevation_base_base,
	FGBuildable_with_size_base as docs_json_ts_0_3_7_7_classes_base_FGBuildable_with_size_base,
	FGBuildable_with_width_base as docs_json_ts_0_3_7_7_classes_base_FGBuildable_with_width_base,
	FGBuildableAttachment_has_mCurrentOutputIndex as docs_json_ts_0_3_7_7_classes_base_FGBuildableAttachment_has_mCurrentOutputIndex,
	FGBuildableAttachment_splitter_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableAttachment_splitter_base_base_base,
	FGBuildableAttachmentMerger_version_specific as docs_json_ts_0_3_7_7_classes_base_FGBuildableAttachmentMerger_version_specific,
	FGBuildableConveyorBelt_base_base_pre_1_0 as docs_json_ts_0_3_7_7_classes_base_FGBuildableConveyorBelt_base_base_pre_1_0,
	FGBuildableConveyorLift_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableConveyorLift_base,
	FGBuildableDockingStation_with_mFuelTransferSpeed_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableDockingStation_with_mFuelTransferSpeed_base,
	FGBuildableFactory_jump_pad_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableFactory_jump_pad_base_base_base,
	FGBuildableFactory_landing_pad_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableFactory_landing_pad_base_base_base,
	FGBuildableFactorySimpleProducer_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableFactorySimpleProducer_base_base,
	FGBuildableGenerator_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableGenerator_base_base_base,
	FGBuildableGenerator_no_fuel_base_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableGenerator_no_fuel_base_base_base_base,
	FGBuildableGeneratorFuel_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableGeneratorFuel_base_base_base,
	FGBuildableGeneratorFuel_coal_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableGeneratorFuel_coal_base_base,
	FGBuildableGeneratorGeoThermal_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableGeneratorGeoThermal_base_base_base,
	FGBuildableGeneratorNuclear_version_specific as docs_json_ts_0_3_7_7_classes_base_FGBuildableGeneratorNuclear_version_specific,
	FGBuildableJumppad_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableJumppad_base_base_base,
	FGBuildableLadder_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableLadder_base,
	FGBuildableManufacturer_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_base_base,
	FGBuildableManufacturer_base_IsPowered_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_IsPowered_base_base,
	FGBuildableManufacturer_base_mProductionEffectsRunning_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_mProductionEffectsRunning_base_base,
	FGBuildableManufacturer_base_packager_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_packager_base_base,
	FGBuildablePipeline_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildablePipeline_base_base,
	FGBuildablePipeline_base_no_indicator_base as docs_json_ts_0_3_7_7_classes_base_FGBuildablePipeline_base_no_indicator_base,
	FGBuildablePipeline_base_root as docs_json_ts_0_3_7_7_classes_base_FGBuildablePipeline_base_root,
	FGBuildablePipeline_base_spline_base as docs_json_ts_0_3_7_7_classes_base_FGBuildablePipeline_base_spline_base,
	FGBuildablePipelinePump_powered_version_specific as docs_json_ts_0_3_7_7_classes_base_FGBuildablePipelinePump_powered_version_specific,
	FGBuildablePipelinePump_pump_version_specific as docs_json_ts_0_3_7_7_classes_base_FGBuildablePipelinePump_pump_version_specific,
	FGBuildablePipelineSupport_base as docs_json_ts_0_3_7_7_classes_base_FGBuildablePipelineSupport_base,
	FGBuildablePipeReservoir_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildablePipeReservoir_base_base_base,
	FGBuildableRailroadStation_version_specific as docs_json_ts_0_3_7_7_classes_base_FGBuildableRailroadStation_version_specific,
	FGBuildableRailroadTrack_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableRailroadTrack_base,
	FGBuildableResourceExtractor_miner_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_miner_base,
	FGBuildableResourceExtractor_miner_mk2_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_miner_mk2_base_base_base,
	FGBuildableResourceExtractor_miner_mk3_version_specific as docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_miner_mk3_version_specific,
	FGBuildableResourceExtractor_oil_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_oil_base_base_base,
	FGBuildableResourceExtractor_only_allow_certain_resources as docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_only_allow_certain_resources,
	FGBuildableResourceExtractor_piped as docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_piped,
	FGBuildableResourceExtractor_timed as docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_timed,
	FGBuildableResourceExtractor_water_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_water_base_base_base,
	FGBuildableResourceSinkShop_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceSinkShop_base_base_base,
	FGBuildableSplitterSmart_version_specific as docs_json_ts_0_3_7_7_classes_base_FGBuildableSplitterSmart_version_specific,
	FGBuildableStorage_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableStorage_base_base_base,
	FGBuildableTradingPost_version_specific as docs_json_ts_0_3_7_7_classes_base_FGBuildableTradingPost_version_specific,
	FGBuildableTrainPlatform_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableTrainPlatform_base_base_base,
	FGBuildableTrainPlatformCargo_version_specific as docs_json_ts_0_3_7_7_classes_base_FGBuildableTrainPlatformCargo_version_specific,
	FGBuildableWire_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableWire_base,
	FGChainsaw_version_specific as docs_json_ts_0_3_7_7_classes_base_FGChainsaw_version_specific,
	FGConsumableDescriptor_base as docs_json_ts_0_3_7_7_classes_base_FGConsumableDescriptor_base,
	FGConsumableEquipment_version_specific as docs_json_ts_0_3_7_7_classes_base_FGConsumableEquipment_version_specific,
	FGDescriptor_sinkable_base as docs_json_ts_0_3_7_7_classes_base_FGDescriptor_sinkable_base,
	FGEquipment_has_effect_timer as docs_json_ts_0_3_7_7_classes_base_FGEquipment_has_effect_timer,
	FGEquipment_has_mEquipmentSlot as docs_json_ts_0_3_7_7_classes_base_FGEquipment_has_mEquipmentSlot,
	FGEquipment_has_mFilterDuration as docs_json_ts_0_3_7_7_classes_base_FGEquipment_has_mFilterDuration,
	FGEquipment_negates_damage as docs_json_ts_0_3_7_7_classes_base_FGEquipment_negates_damage,
	FGEquipmentStunSpear_base_version_specific as docs_json_ts_0_3_7_7_classes_base_FGEquipmentStunSpear_base_version_specific,
	FGGasMask_base as docs_json_ts_0_3_7_7_classes_base_FGGasMask_base,
	FGGolfCartDispenser_has_mArmAnimation as docs_json_ts_0_3_7_7_classes_base_FGGolfCartDispenser_has_mArmAnimation,
	FGItemDescriptorNuclearFuel_version_specific as docs_json_ts_0_3_7_7_classes_base_FGItemDescriptorNuclearFuel_version_specific,
	FGJetPack_version_specific as docs_json_ts_0_3_7_7_classes_base_FGJetPack_version_specific,
	FGJumpingStilts_base as docs_json_ts_0_3_7_7_classes_base_FGJumpingStilts_base,
	FGNobeliskDetonator_base as docs_json_ts_0_3_7_7_classes_base_FGNobeliskDetonator_base,
	FGObjectScanner_version_specific as docs_json_ts_0_3_7_7_classes_base_FGObjectScanner_version_specific,
	FGParachute_has_mIsDeployed as docs_json_ts_0_3_7_7_classes_base_FGParachute_has_mIsDeployed,
	FGPipeHyperStart_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGPipeHyperStart_base_base_base,
	FGPortableMinerDispenser_version_specific as docs_json_ts_0_3_7_7_classes_base_FGPortableMinerDispenser_version_specific,
	FGRecipe_version_specific as docs_json_ts_0_3_7_7_classes_base_FGRecipe_version_specific,
	FGResourceDescriptor_base as docs_json_ts_0_3_7_7_classes_base_FGResourceDescriptor_base,
	FGSuitBase_base as docs_json_ts_0_3_7_7_classes_base_FGSuitBase_base,
	FGWeaponInstantFire_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGWeaponInstantFire_base_base_base,
	FGWeaponProjectile_has_mAttachSocket as docs_json_ts_0_3_7_7_classes_base_FGWeaponProjectile_has_mAttachSocket,
	FGWeaponProjectile_thrown_base_pre_1_0 as docs_json_ts_0_3_7_7_classes_base_FGWeaponProjectile_thrown_base_pre_1_0,
	has_mCanStack as docs_json_ts_0_3_7_7_classes_base_has_mCanStack,
	has_mStackHeight as docs_json_ts_0_3_7_7_classes_base_has_mStackHeight,
	instructive as docs_json_ts_0_3_7_7_classes_base_instructive,
	isDescribed as docs_json_ts_0_3_7_7_classes_base_isDescribed,
} from './../0.3.7.7/classes/Base.ts';

import type {
	FGBuildable_base_version_specific as docs_json_ts_0_4_2_11_classes_base_FGBuildable_base_version_specific,
	FGBuildable_has_mCachedSkeletalMeshes as docs_json_ts_0_4_2_11_classes_base_FGBuildable_has_mCachedSkeletalMeshes,
	FGBuildable_light_related_thing_base as docs_json_ts_0_4_2_11_classes_base_FGBuildable_light_related_thing_base,
	FGBuildable_mHasPower_base as docs_json_ts_0_4_2_11_classes_base_FGBuildable_mHasPower_base,
	FGBuildable_mStopped_audio_stuff_base as docs_json_ts_0_4_2_11_classes_base_FGBuildable_mStopped_audio_stuff_base,
	FGBuildableCircuitSwitch_base as docs_json_ts_0_4_2_11_classes_base_FGBuildableCircuitSwitch_base,
	FGBuildableDroneStation_version_specific as docs_json_ts_0_4_2_11_classes_base_FGBuildableDroneStation_version_specific,
	FGBuildableFloodlight_version_specific as docs_json_ts_0_4_2_11_classes_base_FGBuildableFloodlight_version_specific,
	FGBuildableFrackingActivator_version_specific as docs_json_ts_0_4_2_11_classes_base_FGBuildableFrackingActivator_version_specific,
	FGBuildableGeneratorFuel_base_base_base as docs_json_ts_0_4_2_11_classes_base_FGBuildableGeneratorFuel_base_base_base,
	FGBuildableGeneratorGeoThermal_base as docs_json_ts_0_4_2_11_classes_base_FGBuildableGeneratorGeoThermal_base,
	FGBuildableGeneratorNuclear_version_specific as docs_json_ts_0_4_2_11_classes_base_FGBuildableGeneratorNuclear_version_specific,
	FGBuildableLightsControlPanel_base as docs_json_ts_0_4_2_11_classes_base_FGBuildableLightsControlPanel_base,
	FGBuildableLightSource_version_specific as docs_json_ts_0_4_2_11_classes_base_FGBuildableLightSource_version_specific,
	FGBuildableMAM_version_specific as docs_json_ts_0_4_2_11_classes_base_FGBuildableMAM_version_specific,
	FGBuildableManufacturer_base_blender_base_base as docs_json_ts_0_4_2_11_classes_base_FGBuildableManufacturer_base_blender_base_base,
	FGBuildableManufacturer_Build_HadronCollider_C_base as docs_json_ts_0_4_2_11_classes_base_FGBuildableManufacturer_Build_HadronCollider_C_base,
	FGBuildableManufacturerVariablePower as docs_json_ts_0_4_2_11_classes_base_FGBuildableManufacturerVariablePower,
	FGBuildablePipelineJunction_base_base_base as docs_json_ts_0_4_2_11_classes_base_FGBuildablePipelineJunction_base_base_base,
	FGBuildablePowerStorage_base as docs_json_ts_0_4_2_11_classes_base_FGBuildablePowerStorage_base,
	FGBuildableResourceExtractor_miner_mk1_version_specific as docs_json_ts_0_4_2_11_classes_base_FGBuildableResourceExtractor_miner_mk1_version_specific,
	FGBuildableResourceExtractor_water_base as docs_json_ts_0_4_2_11_classes_base_FGBuildableResourceExtractor_water_base,
	FGBuildableResourceSink_base_base as docs_json_ts_0_4_2_11_classes_base_FGBuildableResourceSink_base_base,
	FGBuildableTradingPost_base_version_specific as docs_json_ts_0_4_2_11_classes_base_FGBuildableTradingPost_base_version_specific,
	FGConsumableEquipment_version_specific as docs_json_ts_0_4_2_11_classes_base_FGConsumableEquipment_version_specific,
	FGDescriptor_sinkable as docs_json_ts_0_4_2_11_classes_base_FGDescriptor_sinkable,
	FGEquipmentZipline_version_specific as docs_json_ts_0_4_2_11_classes_base_FGEquipmentZipline_version_specific,
	FGHoverPack_version_specific as docs_json_ts_0_4_2_11_classes_base_FGHoverPack_version_specific,
	FGPortableMinerDispenser_version_specific as docs_json_ts_0_4_2_11_classes_base_FGPortableMinerDispenser_version_specific,
	FGRecipe_version_specific as docs_json_ts_0_4_2_11_classes_base_FGRecipe_version_specific,
	FGWeaponProjectile_has_mBlockSprintWhenFiring as docs_json_ts_0_4_2_11_classes_base_FGWeaponProjectile_has_mBlockSprintWhenFiring,
	has_mInventorySize as docs_json_ts_0_4_2_11_classes_base_has_mInventorySize,
	has_mPowerConsumption as docs_json_ts_0_4_2_11_classes_base_has_mPowerConsumption,
} from './../0.4.2.11/classes/Base.ts';

import type {
	FGBuildable_base_version_specific as docs_json_ts_0_5_2_1_classes_base_FGBuildable_base_version_specific,
	FGBuildable_isFrame as docs_json_ts_0_5_2_1_classes_base_FGBuildable_isFrame,
	FGBuildable_mSnappedPassthroughs as docs_json_ts_0_5_2_1_classes_base_FGBuildable_mSnappedPassthroughs,
	FGBuildable_powered_base_base as docs_json_ts_0_5_2_1_classes_base_FGBuildable_powered_base_base,
	FGBuildable_with_elevation as docs_json_ts_0_5_2_1_classes_base_FGBuildable_with_elevation,
	FGBuildableBeam_base as docs_json_ts_0_5_2_1_classes_base_FGBuildableBeam_base,
	FGBuildableConveyorBelt_spline_base as docs_json_ts_0_5_2_1_classes_base_FGBuildableConveyorBelt_spline_base,
	FGBuildableDockingStation_base as docs_json_ts_0_5_2_1_classes_base_FGBuildableDockingStation_base,
	FGBuildableDoor_automated_version_specific as docs_json_ts_0_5_2_1_classes_base_FGBuildableDoor_automated_version_specific,
	FGBuildableDoor_base as docs_json_ts_0_5_2_1_classes_base_FGBuildableDoor_base,
	FGBuildableDoor_manual_version_specific as docs_json_ts_0_5_2_1_classes_base_FGBuildableDoor_manual_version_specific,
	FGBuildableLightsControlPanel_version_specific as docs_json_ts_0_5_2_1_classes_base_FGBuildableLightsControlPanel_version_specific,
	FGBuildableLightSource_base as docs_json_ts_0_5_2_1_classes_base_FGBuildableLightSource_base,
	FGBuildableLightSource_Build_StreetLight_C_version_specific as docs_json_ts_0_5_2_1_classes_base_FGBuildableLightSource_Build_StreetLight_C_version_specific,
	FGBuildableManufacturer_Build_FoundryMk1_C_base as docs_json_ts_0_5_2_1_classes_base_FGBuildableManufacturer_Build_FoundryMk1_C_base,
	FGBuildablePassthrough_base as docs_json_ts_0_5_2_1_classes_base_FGBuildablePassthrough_base,
	FGBuildablePipeline_base_spline as docs_json_ts_0_5_2_1_classes_base_FGBuildablePipeline_base_spline,
	FGBuildableRailroadSignal_base_version_specific as docs_json_ts_0_5_2_1_classes_base_FGBuildableRailroadSignal_base_version_specific,
	FGBuildableRailroadSignal_block_version_specific as docs_json_ts_0_5_2_1_classes_base_FGBuildableRailroadSignal_block_version_specific,
	FGBuildableRailroadStation_base as docs_json_ts_0_5_2_1_classes_base_FGBuildableRailroadStation_base,
	FGBuildableRailroadTrack_base_version_specific as docs_json_ts_0_5_2_1_classes_base_FGBuildableRailroadTrack_base_version_specific,
	FGBuildableRamp_base as docs_json_ts_0_5_2_1_classes_base_FGBuildableRamp_base,
	FGBuildableTradingPost_base as docs_json_ts_0_5_2_1_classes_base_FGBuildableTradingPost_base,
	FGBuildableTrainPlatform_base_version_specific as docs_json_ts_0_5_2_1_classes_base_FGBuildableTrainPlatform_base_version_specific,
	FGBuildableTrainPlatform_non_empty_version_specific as docs_json_ts_0_5_2_1_classes_base_FGBuildableTrainPlatform_non_empty_version_specific,
	FGBuildableTrainPlatformCargo_version_specific as docs_json_ts_0_5_2_1_classes_base_FGBuildableTrainPlatformCargo_version_specific,
	FGBuildableWidgetSign_base as docs_json_ts_0_5_2_1_classes_base_FGBuildableWidgetSign_base,
	FGGolfCartDispenser_version_specific as docs_json_ts_0_5_2_1_classes_base_FGGolfCartDispenser_version_specific,
	FGNobeliskDetonator_version_specific as docs_json_ts_0_5_2_1_classes_base_FGNobeliskDetonator_version_specific,
	FGSchematic_with_described_unlocks_version_specific as docs_json_ts_0_5_2_1_classes_base_FGSchematic_with_described_unlocks_version_specific,
	FGWeapon_Equip_Rifle_C_base as docs_json_ts_0_5_2_1_classes_base_FGWeapon_Equip_Rifle_C_base,
	FGWeapon_pre_1_1 as docs_json_ts_0_5_2_1_classes_base_FGWeapon_pre_1_1,
	FGWeapon_version_specific as docs_json_ts_0_5_2_1_classes_base_FGWeapon_version_specific,
	has_mIsSupport as docs_json_ts_0_5_2_1_classes_base_has_mIsSupport,
	has_mResourceSinkPoints as docs_json_ts_0_5_2_1_classes_base_has_mResourceSinkPoints,
	has_mSize_vector as docs_json_ts_0_5_2_1_classes_base_has_mSize_vector,
} from './../0.5.2.1/classes/Base.ts';

import type {
	FGBuildable_base_version_specific as docs_json_ts_0_7_1_1_classes_base_FGBuildable_base_version_specific,
	FGBuildable_powered_version_specific as docs_json_ts_0_7_1_1_classes_base_FGBuildable_powered_version_specific,
	FGBuildableBlueprintDesigner_version_specific as docs_json_ts_0_7_1_1_classes_base_FGBuildableBlueprintDesigner_version_specific,
	FGBuildableCircuitSwitch_version_specific as docs_json_ts_0_7_1_1_classes_base_FGBuildableCircuitSwitch_version_specific,
	FGBuildablePole_version_specific as docs_json_ts_0_7_1_1_classes_base_FGBuildablePole_version_specific,
} from './../0.7.1.1/classes/Base.ts';

import type {
	bool_string as docs_json_ts_common_types_bool_string,
	decimal_string as docs_json_ts_common_types_decimal_string,
	empty_object as docs_json_ts_common_types_empty_object,
	integer_string as docs_json_ts_common_types_integer_string,
	integer_string_signed as docs_json_ts_common_types_integer_string_signed,
	RGBA as docs_json_ts_common_types_RGBA,
	XYZ_decimal_string as docs_json_ts_common_types_XYZ_decimal_string,
	XYZ_decimal_string_list as docs_json_ts_common_types_XYZ_decimal_string_list,
} from './../common/types.ts';

import type {
	FGBuildableResourceExtractor_miner_base as docs_json_ts_0_3_7_7_classes_base_overridable_FGBuildableResourceExtractor_miner_base,
	FGBuildableResourceExtractor_only_allow_certain_resources as docs_json_ts_0_3_7_7_classes_base_overridable_FGBuildableResourceExtractor_only_allow_certain_resources,
	FGEquipment_version_specific as docs_json_ts_0_3_7_7_classes_base_overridable_FGEquipment_version_specific,
	FGSchematic_version_specific as docs_json_ts_0_3_7_7_classes_base_overridable_FGSchematic_version_specific,
} from './../0.3.7.7/classes/Base.overridable--1.0.1.4.ts';

import type {
	FGBuildable_is_wallish as docs_json_ts_0_5_2_1_classes_base_overridable_FGBuildable_is_wallish,
	FGRecipe_version_specific as docs_json_ts_0_5_2_1_classes_base_overridable_FGRecipe_version_specific,
	FGSchematic_version_specific as docs_json_ts_0_5_2_1_classes_base_overridable_FGSchematic_version_specific,
	FGWeapon_version_specific as docs_json_ts_0_5_2_1_classes_base_overridable_FGWeapon_version_specific,
} from './../0.5.2.1/classes/Base.overridable--1.0.1.4.ts';

import type {
	hasClassName as docs_json_ts_common_classes_base_hasClassName,
} from './../common/classes/Base.ts';

import type {
	FGItemDescriptor as docs_json_ts_common_classes_FGItemDescriptor,
	FGPoleDescriptor as docs_json_ts_common_classes_FGPoleDescriptor,
	FGRecipe as docs_json_ts_common_classes_FGRecipe,
	FGSchematic as docs_json_ts_common_classes_FGSchematic,
} from './../common/classes.ts';

import type {
	BlueprintGeneratedClass_single_quoted as docs_json_ts_0_4_2_11_overridable_BlueprintGeneratedClass_single_quoted,
} from './../0.4.2.11/types/overridable--1.0.1.4.ts';

import type {
	FGJetPack_version_specific as docs_json_ts_0_7_1_1_classes_base_overridable_FGJetPack_version_specific,
} from './../0.7.1.1/classes/Base.1.0.1.4.ts';

import type {
	AnimMontage_quoted as docs_json_ts_0_3_7_7_overridable_AnimMontage_quoted,
	MaterialInstanceConstant_quoted as docs_json_ts_0_3_7_7_overridable_MaterialInstanceConstant_quoted,
} from './../0.3.7.7/types/overridable--1.0.1.4.ts';

import type {
	CameraAnimationSequence_quoted as docs_json_ts_0_8_3_3_properties_overridable_CameraAnimationSequence_quoted,
	DocsDotJson_AkAudioEvent_quoted_list_item as docs_json_ts_0_8_3_3_properties_overridable_DocsDotJson_AkAudioEvent_quoted_list_item,
} from './../0.8.3.3/types/properties.1.0.1.4.ts';

type has_SAMReference = {
	SAMReference: '/Game/FactoryGame/Resource/RawResources/SAM/Desc_SAM.Desc_SAM_C',
};

type FGAmmoTypeInstantHit_Desc_CartridgeChaos_C = docs_json_ts_0_6_1_5_classes_base_FGAmmoType_base & docs_json_ts_0_6_1_5_classes_base_overridable_FGAmmoType_base & docs_json_ts_0_6_1_5_classes_base_FGAmmoType_version_specific & docs_json_ts_0_6_1_5_classes_base_overridable_FGAmmoType_version_specific & docs_json_ts_0_8_3_3_classes_base_overridable_FGAmmoType_pre_1_1 & docs_json_ts_0_8_3_3_classes_base_overridable_FGAmmoType_version_specific & docs_json_ts_0_6_1_5_classes_base_FGAmmoTypeInstantHit_Desc_CartridgeChaos_C_version_specific & docs_json_ts_0_6_1_5_classes_base_FGAmmoTypeInstantHit_version_specific & FGItemDescriptor_version_specific;

type FGAmmoTypeInstantHit_Desc_CartridgeStandard_C = docs_json_ts_0_6_1_5_classes_base_FGAmmoType_base & docs_json_ts_0_6_1_5_classes_base_overridable_FGAmmoType_base & docs_json_ts_0_8_3_3_classes_base_overridable_FGAmmoType_pre_1_1 & docs_json_ts_0_8_3_3_classes_base_overridable_FGAmmoType_version_specific & docs_json_ts_0_6_1_5_classes_base_FGAmmoType_version_specific & docs_json_ts_0_6_1_5_classes_base_overridable_FGAmmoType_version_specific & docs_json_ts_0_6_1_5_classes_base_FGAmmoTypeInstantHit_version_specific & FGItemDescriptor_version_specific;

type FGAmmoTypeProjectile = docs_json_ts_0_6_1_5_classes_base_FGAmmoType_base & docs_json_ts_0_6_1_5_classes_base_overridable_FGAmmoType_version_specific & docs_json_ts_0_6_1_5_classes_base_overridable_FGAmmoTypeProjectile_version_specific & docs_json_ts_0_8_3_3_classes_base_overridable_FGAmmoType_pre_1_1 & docs_json_ts_0_8_3_3_classes_base_overridable_FGAmmoType_version_specific & docs_json_ts_0_6_1_5_classes_base_FGAmmoTypeProjectile_version_specific & docs_json_ts_0_6_1_5_classes_base_FGDescriptor & docs_json_ts_0_6_1_5_classes_base_FGItemDescriptor_version_specific & docs_json_ts_0_6_1_5_classes_base_overridable_FGItemDescriptor_version_specific & docs_json_ts_0_6_1_5_overridable_has_mSubCategories & docs_json_ts_0_8_3_3_classes_base_FGAmmoTypeProjectile_version_specific & FGAmmoTypeProjectile_version_specific & FGItemDescriptor_version_specific;

type FGAmmoTypeProjectile_version_specific = {
	mMagazineMeshMaterials: null | [
		docs_json_ts_1_0_1_4_properties_mMagazineMeshMaterials_item,
		...docs_json_ts_1_0_1_4_properties_mMagazineMeshMaterials_item[],
	],
};

type FGAmmoTypeSpreadshot = docs_json_ts_0_6_1_5_classes_base_FGAmmoType_base & docs_json_ts_0_6_1_5_classes_base_overridable_FGAmmoType_base & docs_json_ts_0_8_3_3_classes_base_overridable_FGAmmoType_pre_1_1 & docs_json_ts_0_8_3_3_classes_base_overridable_FGAmmoType_version_specific & docs_json_ts_0_6_1_5_classes_base_FGAmmoTypeSpreadshot_version_specific & FGItemDescriptor_version_specific;

type FGBuildable_base = docs_json_ts_0_3_7_7_classes_base_FGBuildable_base_version_specific & docs_json_ts_0_4_2_11_classes_base_FGBuildable_base_version_specific & docs_json_ts_0_5_2_1_classes_base_FGBuildable_base_version_specific & docs_json_ts_0_6_1_5_classes_base_FGBuildable_base_version_specific & docs_json_ts_0_6_1_5_classes_base_overridable_FGBuildable_base_version_specific & docs_json_ts_0_7_1_1_classes_base_FGBuildable_base_version_specific & docs_json_ts_0_8_3_3_classes_base_FGBuildable_version_specific & FGBuildable_version_specific;

type FGBuildable_occupied = docs_json_ts_0_3_7_7_classes_base_FGBuildable_occupied_base & FGBuildable_base;

type FGBuildable_powered = docs_json_ts_0_3_7_7_classes_base_FGBuildable_powered_version_specific & docs_json_ts_0_4_2_11_classes_base_FGBuildable_has_mCachedSkeletalMeshes & docs_json_ts_0_5_2_1_classes_base_FGBuildable_powered_base_base & docs_json_ts_0_7_1_1_classes_base_FGBuildable_powered_version_specific & docs_json_ts_0_8_3_3_classes_base_FGBuildable_with_mTickExponent & FGBuildable_base & FGBuildable_powered_version_specific;

type FGBuildable_powered_version_specific = {
	mProductionBoostPowerConsumptionExponent: docs_json_ts_common_types_decimal_string,
	mOnPendingPotentialChanged: docs_json_ts_common_types_empty_object,
	mOnPendingProductionBoostChanged: docs_json_ts_common_types_empty_object,
	mOnCurrentProductivityChanged: docs_json_ts_common_types_empty_object,
	mCanChangeProductionBoost: docs_json_ts_common_types_bool_string,
	mBaseProductionBoost: docs_json_ts_common_types_decimal_string,
	mPotentialShardSlots: docs_json_ts_common_types_integer_string,
	mProductionShardSlotSize: docs_json_ts_common_types_integer_string,
	mProductionShardBoostMultiplier: docs_json_ts_common_types_decimal_string,
	mHasInventoryPotential: docs_json_ts_common_types_bool_string,
	mIsTickRateManaged: docs_json_ts_common_types_bool_string,
	mOverridePotentialShardSlots: docs_json_ts_common_types_bool_string,
	mOverrideProductionShardSlotSize: docs_json_ts_common_types_bool_string,
	mAlienOverClockingParticleEffects: '',
};

type FGBuildable_tiered = docs_json_ts_0_3_7_7_classes_base_FGBuildable_tiered_base & FGBuildable_base;

type FGBuildable_version_specific = {
	bForceLegacyBuildEffect: docs_json_ts_common_types_bool_string,
	bForceBuildEffectSolo: docs_json_ts_common_types_bool_string,
	mInteractionRegisterPlayerWithCircuit: docs_json_ts_common_types_bool_string,
	mManagedByLightweightBuildableSubsystem: docs_json_ts_common_types_bool_string,
	mRemoveBuildableFromSubsystemOnDismantle: docs_json_ts_common_types_bool_string,
	mHasBeenRemovedFromSubsystem: docs_json_ts_common_types_bool_string,
	mReplicatedBuiltInsideBlueprintDesigner: docs_json_ts_common_types_bool_string,
	mClearanceData: null | [
		docs_json_ts_1_0_1_4_properties_mClearanceData_item,
		...docs_json_ts_1_0_1_4_properties_mClearanceData_item[],
	],
	mTimelapseBucketId: docs_json_ts_common_types_integer_string,
	mTimelapseDelay: docs_json_ts_common_types_decimal_string,
	mAlienOverClockingZOffset: docs_json_ts_common_types_decimal_string,
	mAlienOverClockingAttenuationScalingFactor: docs_json_ts_common_types_decimal_string,
	mAlienOverClockingVolumeDB_RTPC: docs_json_ts_common_types_decimal_string,
	mAlienOverClockingHighpass_RTPC: docs_json_ts_common_types_decimal_string,
	mAlienOverClockingPitch_RTPC: docs_json_ts_common_types_decimal_string,
};

type FGBuildableAttachmentMerger = docs_json_ts_0_3_7_7_classes_base_FGBuildableAttachmentMerger_version_specific & docs_json_ts_0_4_2_11_classes_base_has_mInventorySize & FGBuildable_base;

type FGBuildableAttachmentSplitter = docs_json_ts_0_3_7_7_classes_base_FGBuildableAttachment_has_mCurrentOutputIndex & docs_json_ts_0_4_2_11_classes_base_has_mInventorySize & FGBuildable_base;

type FGBuildableBeamLightweight = docs_json_ts_0_5_2_1_classes_base_FGBuildableBeam_base & FGBuildable_base;

type FGBuildableBlueprintDesigner = docs_json_ts_0_7_1_1_classes_base_FGBuildableBlueprintDesigner_version_specific & docs_json_ts_0_8_3_3_classes_base_FGBuildableBlueprintDesigner_version_specific & FGBuildable_base & FGBuildableBlueprintDesigner_version_specific;

type FGBuildableBlueprintDesigner_version_specific = {
	mCurrentRecordData: {
		IconID: docs_json_ts_1_0_1_4_properties_IconID,
		Color: docs_json_ts_common_types_RGBA,
	},
};

type FGBuildableCircuitSwitch = docs_json_ts_0_4_2_11_classes_base_FGBuildableCircuitSwitch_base & docs_json_ts_0_7_1_1_classes_base_FGBuildableCircuitSwitch_version_specific & docs_json_ts_0_8_3_3_classes_base_FGBuildable_has_mOnCircuitsChanged & FGBuildable_base;

type FGBuildableConveyorBelt = docs_json_ts_0_3_7_7_classes_base_FGBuildable_spline & docs_json_ts_0_3_7_7_classes_base_FGBuildableConveyorBelt_base_base_pre_1_0 & docs_json_ts_0_5_2_1_classes_base_FGBuildableConveyorBelt_spline_base & docs_json_ts_0_8_3_3_classes_base_FGBuildableConveyorBelt_version_specific & FGBuildable_base & FGBuildableConveyorBelt_version_specific;

type FGBuildableConveyorBelt_version_specific = {
	mItems: {
		ArrayReplicationKey?: docs_json_ts_common_types_integer_string_signed,
	},
	mChainSegmentIndex: docs_json_ts_common_types_integer_string_signed,
};

type FGBuildableConveyorLift = docs_json_ts_0_3_7_7_classes_base_FGBuildableConveyorBelt_base_base_pre_1_0 & docs_json_ts_0_3_7_7_classes_base_FGBuildableConveyorLift_base & docs_json_ts_0_5_2_1_classes_base_FGBuildable_mSnappedPassthroughs & docs_json_ts_0_8_3_3_classes_base_FGBuildableConveyorBelt_version_specific & FGBuildable_base & FGBuildableConveyorBelt_version_specific & FGBuildableConveyorLift_version_specific;

type FGBuildableConveyorLift_version_specific = {
	mFlipMeshOnReverse: docs_json_ts_common_types_bool_string,
	mOpposingConnectionClearance: docs_json_ts_common_types_decimal_string,
};

type FGBuildableCornerWall = docs_json_ts_0_3_7_7_classes_base_FGBuildable_with_height_base & docs_json_ts_0_3_7_7_classes_base_FGBuildable_with_size_base & docs_json_ts_0_6_1_5_classes_base_has_mIsInverted & FGBuildable_base;

type FGBuildableDockingStation = docs_json_ts_0_3_7_7_classes_base_FGBuildable_docking_station_base_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableDockingStation_with_mFuelTransferSpeed_base & docs_json_ts_0_5_2_1_classes_base_FGBuildableDockingStation_base & FGBuildable_powered;

type FGBuildableDoor = FGBuildableDoor_manual | FGBuildableDoor_automated;

type FGBuildableDoor_automated = docs_json_ts_0_5_2_1_classes_base_FGBuildableDoor_automated_version_specific & docs_json_ts_0_5_2_1_classes_base_FGBuildableDoor_base & FGBuildableWall;

type FGBuildableDoor_manual = docs_json_ts_0_5_2_1_classes_base_FGBuildableDoor_base & docs_json_ts_0_5_2_1_classes_base_FGBuildableDoor_manual_version_specific & FGBuildableWall;

type FGBuildableDroneStation = docs_json_ts_0_3_7_7_classes_base_FGBuildable_docking_station_base_with_mMapText & docs_json_ts_0_4_2_11_classes_base_FGBuildableDroneStation_version_specific & FGBuildable_powered & FGBuildableDroneStation_version_specific;

type FGBuildableDroneStation_version_specific = {
	mFuelStorageSizeX: docs_json_ts_common_types_integer_string,
	mFuelStorageSizeY: docs_json_ts_common_types_integer_string,
};

type FGBuildableFactory_jump_pad = docs_json_ts_0_3_7_7_classes_base_FGBuildableFactory_jump_pad_base_base_base & FGBuildable_powered;

type FGBuildableFactory_landing_pad = docs_json_ts_0_3_7_7_classes_base_FGBuildableFactory_landing_pad_base_base_base & FGBuildable_powered;

type FGBuildableFactorySimpleProducer = docs_json_ts_0_3_7_7_classes_base_FGBuildableFactorySimpleProducer_base_base & FGBuildable_powered;

type FGBuildableFloodlight = docs_json_ts_0_4_2_11_classes_base_FGBuildableFloodlight_version_specific & FGBuildable_base & FGBuildableLightSource;

type FGBuildableFoundation = docs_json_ts_0_3_7_7_classes_base_FGBuildable_with_height_base & docs_json_ts_0_3_7_7_classes_base_FGBuildable_with_width_base & docs_json_ts_0_5_2_1_classes_base_FGBuildable_isFrame & docs_json_ts_0_5_2_1_classes_base_FGBuildable_with_elevation & docs_json_ts_0_6_1_5_classes_base_FGBuildable_foundation_mDisableSnapOn & docs_json_ts_0_6_1_5_classes_base_FGBuildable_with_depth & docs_json_ts_0_6_1_5_classes_base_FGBuildableFoundation_version_specific & FGBuildable_base;

type FGBuildableFrackingActivator = docs_json_ts_0_3_7_7_classes_base_overridable_FGBuildableResourceExtractor_only_allow_certain_resources & docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_only_allow_certain_resources & docs_json_ts_0_4_2_11_classes_base_FGBuildableFrackingActivator_version_specific & docs_json_ts_0_6_1_5_classes_base_FGBuildableResourceExtractor_base_version_specific_base & FGBuildable_powered;

type FGBuildableFrackingExtractor = docs_json_ts_0_3_7_7_classes_base_overridable_FGBuildableResourceExtractor_only_allow_certain_resources & docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_piped & docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_timed & docs_json_ts_0_6_1_5_classes_base_FGBuildableResourceExtractor_base_version_specific_base & FGBuildable_powered;

type FGBuildableGenerator = docs_json_ts_0_3_7_7_classes_base_FGBuildableGenerator_base_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableGenerator_no_fuel_base_base_base_base & FGBuildableGenerator_no_fuel & FGBuildableGenerator_version_specific;

type FGBuildableGenerator_no_fuel = docs_json_ts_0_3_7_7_classes_base_FGBuildableGenerator_no_fuel_base_base_base_base & FGBuildable_powered;

type FGBuildableGenerator_version_specific = {
	mFuelClassesInInventory: null,
};

type FGBuildableGeneratorFuel_biomass = docs_json_ts_0_4_2_11_classes_base_FGBuildableGeneratorFuel_base_base_base & FGBuildableGenerator & FGBuildableGeneratorFuel_biomass_version_specific;

type FGBuildableGeneratorFuel_biomass_version_specific = {
	mDefaultFuelClasses: [
		'/Game/FactoryGame/Resource/Parts/GenericBiomass/Desc_Leaves.Desc_Leaves_C',
		'/Game/FactoryGame/Resource/Parts/GenericBiomass/Desc_Wood.Desc_Wood_C',
		'/Game/FactoryGame/Resource/Parts/GenericBiomass/Desc_Mycelia.Desc_Mycelia_C',
		'/Game/FactoryGame/Resource/Parts/GenericBiomass/Desc_GenericBiomass.Desc_GenericBiomass_C',
		'/Game/FactoryGame/Resource/Parts/BioFuel/Desc_Biofuel.Desc_Biofuel_C',
		'/Game/FactoryGame/Resource/Parts/BioFuel/Desc_PackagedBiofuel.Desc_PackagedBiofuel_C',
	],
};

type FGBuildableGeneratorFuel_coal = docs_json_ts_0_3_7_7_classes_base_FGBuildableGeneratorFuel_coal_base_base & docs_json_ts_0_4_2_11_classes_base_FGBuildableGeneratorFuel_base_base_base & FGBuildableGenerator;

type FGBuildableGeneratorFuel_fuel = docs_json_ts_0_3_7_7_classes_base_FGBuildableGeneratorFuel_base_base_base & docs_json_ts_0_4_2_11_classes_base_FGBuildableGeneratorFuel_base_base_base & FGBuildableGenerator & FGBuildableGeneratorFuel_fuel_version_specific;

type FGBuildableGeneratorFuel_fuel_version_specific = {
	mDefaultFuelClasses: [
		'/Game/FactoryGame/Resource/Parts/Fuel/Desc_LiquidFuel.Desc_LiquidFuel_C',
		'/Game/FactoryGame/Resource/Parts/Turbofuel/Desc_LiquidTurboFuel.Desc_LiquidTurboFuel_C',
		'/Game/FactoryGame/Resource/Parts/BioFuel/Desc_LiquidBiofuel.Desc_LiquidBiofuel_C',
		'/Game/FactoryGame/Resource/Parts/RocketFuel/Desc_RocketFuel.Desc_RocketFuel_C',
		'/Game/FactoryGame/Resource/Parts/IonizedFuel/Desc_IonizedFuel.Desc_IonizedFuel_C',
	],
};

type FGBuildableGeneratorGeoThermal = docs_json_ts_0_3_7_7_classes_base_FGBuildableGeneratorGeoThermal_base_base_base & docs_json_ts_0_4_2_11_classes_base_FGBuildableGeneratorGeoThermal_base & FGBuildableGenerator_no_fuel;

type FGBuildableGeneratorNuclear = docs_json_ts_0_3_7_7_classes_base_FGBuildableGeneratorNuclear_version_specific & docs_json_ts_0_4_2_11_classes_base_FGBuildableGeneratorFuel_base_base_base & docs_json_ts_0_4_2_11_classes_base_FGBuildableGeneratorNuclear_version_specific & FGBuildableGenerator & FGBuildableGeneratorNuclear_version_specific;

type FGBuildableGeneratorNuclear_version_specific = {
	mDefaultFuelClasses: [
		'/Game/FactoryGame/Resource/Parts/NuclearFuelRod/Desc_NuclearFuelRod.Desc_NuclearFuelRod_C',
		'/Game/FactoryGame/Resource/Parts/PlutoniumFuelRods/Desc_PlutoniumFuelRod.Desc_PlutoniumFuelRod_C',
		'/Game/FactoryGame/Resource/Parts/FicsoniumFuelRod/Desc_FicsoniumFuelRod.Desc_FicsoniumFuelRod_C',
	],
};

type FGBuildableJumppad = docs_json_ts_0_3_7_7_classes_base_FGBuildableJumppad_base_base_base & docs_json_ts_0_8_3_3_classes_base_FGBuildableJumppad_version_specific & FGBuildable_powered;

type FGBuildableLadder = docs_json_ts_0_3_7_7_classes_base_FGBuildableLadder_base & FGBuildable_base;

type FGBuildableLightsControlPanel = docs_json_ts_0_4_2_11_classes_base_FGBuildable_light_related_thing_base & docs_json_ts_0_4_2_11_classes_base_FGBuildableLightsControlPanel_base & docs_json_ts_0_5_2_1_classes_base_FGBuildableLightsControlPanel_version_specific & docs_json_ts_0_8_3_3_classes_base_FGBuildable_has_mOnCircuitsChanged & FGBuildable_base;

type FGBuildableLightSource = docs_json_ts_0_4_2_11_classes_base_FGBuildable_light_related_thing_base & docs_json_ts_0_4_2_11_classes_base_FGBuildable_mHasPower_base & docs_json_ts_0_4_2_11_classes_base_FGBuildableLightSource_version_specific & docs_json_ts_0_4_2_11_classes_base_has_mPowerConsumption & docs_json_ts_0_5_2_1_classes_base_FGBuildableLightSource_base & FGBuildable_base;

type FGBuildableLightSource_Build_StreetLight_C = docs_json_ts_0_5_2_1_classes_base_FGBuildableLightSource_Build_StreetLight_C_version_specific & FGBuildableLightSource;

type FGBuildableMAM = docs_json_ts_0_4_2_11_classes_base_FGBuildableMAM_version_specific & FGBuildable_base & FGBuildable_occupied & FGBuildableMAM_version_specific;

type FGBuildableMAM_version_specific = {
	Centrifuge_NewTrack_1_BB49BD99478F0FC67F8D7E9A54C7E849: docs_json_ts_common_types_decimal_string,
	Centrifuge_NewTrack_0_BB49BD99478F0FC67F8D7E9A54C7E849: docs_json_ts_common_types_decimal_string,
	Centrifuge__Direction_BB49BD99478F0FC67F8D7E9A54C7E849: 'Forward',
	['Centrifuge Duration']: docs_json_ts_common_types_decimal_string,
};

type FGBuildableManufacturer_Build_AssemblerMk1_C = docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_base_base & FGBuildable_powered;

type FGBuildableManufacturer_Build_Blender_C = docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_IsPowered_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_mProductionEffectsRunning_base_base & docs_json_ts_0_4_2_11_classes_base_FGBuildableManufacturer_base_blender_base_base & FGBuildable_powered;

type FGBuildableManufacturer_Build_ConstructorMk1_C = docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_base_base & FGBuildable_powered & FGBuildableManufacturer_Build_ConstructorMk1_C_version_specific;

type FGBuildableManufacturer_Build_ConstructorMk1_C_version_specific = {
	mAOAttenuationScalingFactor: docs_json_ts_common_types_decimal_string,
	mAOLayerZOffset: docs_json_ts_common_types_decimal_string,
	RTPC_AO_VolumeDB: docs_json_ts_common_types_decimal_string,
	RTPC_AO_HighpassValue: docs_json_ts_common_types_decimal_string,
	RTPC_AO_Pitch: docs_json_ts_common_types_decimal_string,
};

type FGBuildableManufacturer_Build_Converter_C = docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_base_base & docs_json_ts_0_4_2_11_classes_base_FGBuildableManufacturerVariablePower & FGBuildable_powered;

type FGBuildableManufacturer_Build_FoundryMk1_C = docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_mProductionEffectsRunning_base_base & docs_json_ts_0_5_2_1_classes_base_FGBuildableManufacturer_Build_FoundryMk1_C_base & FGBuildable_powered;

type FGBuildableManufacturer_Build_HadronCollider_C = docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_IsPowered_base_base & docs_json_ts_0_4_2_11_classes_base_FGBuildableManufacturer_Build_HadronCollider_C_base & docs_json_ts_0_4_2_11_classes_base_FGBuildableManufacturerVariablePower & FGBuildable_powered;

type FGBuildableManufacturer_Build_ManufacturerMk1_C = docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_base_base & docs_json_ts_0_4_2_11_classes_base_FGBuildable_mStopped_audio_stuff_base & FGBuildable_powered;

type FGBuildableManufacturer_Build_OilRefinery_C = docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_IsPowered_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_mProductionEffectsRunning_base_base & FGBuildable_powered;

type FGBuildableManufacturer_Build_Packager_C = docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_IsPowered_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_mProductionEffectsRunning_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_packager_base_base & FGBuildable_powered;

type FGBuildableManufacturer_Build_QuantumEncoder_C = docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_IsPowered_base_base & docs_json_ts_0_4_2_11_classes_base_FGBuildableManufacturerVariablePower & FGBuildable_powered & FGBuildableManufacturer_Build_QuantumEncoder_C_version_specific;

type FGBuildableManufacturer_Build_QuantumEncoder_C_version_specific = {
	IsAnimProducing: docs_json_ts_common_types_bool_string,
};

type FGBuildableManufacturer_Build_SmelterMk1_C = docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_mProductionEffectsRunning_base_base & docs_json_ts_0_6_1_5_classes_base_FGBuildableManufacturer_Build_SmelterMk1_C_base & FGBuildable_powered;

type FGBuildablePassthrough = docs_json_ts_0_5_2_1_classes_base_FGBuildablePassthrough_base & docs_json_ts_0_8_3_3_classes_base_FGBuildablePassthrough_version_specific & FGBuildable_base;

type FGBuildablePillarLightweight = docs_json_ts_0_5_2_1_classes_base_has_mIsSupport & docs_json_ts_0_5_2_1_classes_base_has_mSize_vector & FGBuildable_base;

type FGBuildablePipeHyper = docs_json_ts_0_3_7_7_classes_base_FGBuildable_spline & docs_json_ts_0_5_2_1_classes_base_FGBuildable_mSnappedPassthroughs & FGBuildable_base;

type FGBuildablePipeline = docs_json_ts_0_3_7_7_classes_base_FGBuildablePipeline_base_root & docs_json_ts_0_3_7_7_classes_base_FGBuildablePipeline_base_spline_base & docs_json_ts_0_5_2_1_classes_base_FGBuildablePipeline_base_spline & docs_json_ts_0_6_1_5_classes_base_FGBuildablePipeline_version_specific & FGBuildable_base & FGBuildablePipeline_version_specific;

type FGBuildablePipeline_version_specific = {
	mSoundSplineComponentEmitterInterval: docs_json_ts_common_types_decimal_string,
	mLastElapsedTime: docs_json_ts_common_types_decimal_string,
	mLastFlowForSoundUpdateThreshold: docs_json_ts_common_types_decimal_string,
	mUpdateSoundsTimerInterval: docs_json_ts_common_types_decimal_string,
};

type FGBuildablePipelineJunction = docs_json_ts_0_3_7_7_classes_base_FGBuildable_powered_version_specific & docs_json_ts_0_3_7_7_classes_base_FGBuildablePipeline_base_no_indicator_base & docs_json_ts_0_4_2_11_classes_base_FGBuildablePipelineJunction_base_base_base & FGBuildable_powered;

type FGBuildablePipelinePump_pump = docs_json_ts_0_3_7_7_classes_base_FGBuildablePipeline_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildablePipelinePump_powered_version_specific & docs_json_ts_0_3_7_7_classes_base_FGBuildablePipelinePump_pump_version_specific & FGBuildable_powered & FGBuildablePipelinePump_version_specific;

type FGBuildablePipelinePump_valve = docs_json_ts_0_3_7_7_classes_base_FGBuildablePipeline_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildablePipelinePump_powered_version_specific & FGBuildable_powered & FGBuildablePipelinePump_version_specific;

type FGBuildablePipelinePump_version_specific = {
	mUpdateAudioFlowTime: docs_json_ts_common_types_decimal_string,
};

type FGBuildablePipelineSupport = docs_json_ts_0_3_7_7_classes_base_FGBuildable_pole_base & docs_json_ts_0_3_7_7_classes_base_FGBuildable_with_mLength & docs_json_ts_0_3_7_7_classes_base_FGBuildablePipelineSupport_base & docs_json_ts_0_3_7_7_classes_base_has_mCanStack & docs_json_ts_0_3_7_7_classes_base_has_mStackHeight & FGBuildable_base;

type FGBuildablePipeReservoir = docs_json_ts_0_3_7_7_classes_base_FGBuildablePipeReservoir_base_base_base & FGBuildable_powered;

type FGBuildablePoleBase = docs_json_ts_0_3_7_7_classes_base_FGBuildable_base_version_specific & docs_json_ts_0_3_7_7_classes_base_has_mCanStack & docs_json_ts_0_3_7_7_classes_base_has_mStackHeight & FGBuildable_base;

type FGBuildablePoleLightweight = docs_json_ts_0_3_7_7_classes_base_FGBuildable_pole_base & docs_json_ts_0_3_7_7_classes_base_FGBuildable_with_height_base & docs_json_ts_0_3_7_7_classes_base_has_mCanStack & docs_json_ts_0_3_7_7_classes_base_has_mStackHeight & docs_json_ts_0_7_1_1_classes_base_FGBuildablePole_version_specific & FGBuildable_base;

type FGBuildablePortal = FGBuildable_base & FGBuildable_powered & FGBuildablePortal_common & FGBuildablePortal_version_specific;

type FGBuildablePortal_common = {
	['HeatingUpPlaying ID']: docs_json_ts_common_types_integer_string,
	LightningEndLoc: docs_json_ts_common_types_XYZ_decimal_string,
	LightningStartLoc: docs_json_ts_common_types_XYZ_decimal_string,
	LightningStartSocket: [
		'LightningStartLocSocket',
		'LightningStartLocSocketL',
		'LightningStartLocSocketR',
		'LightningStartLocSocketA',
		'LightningStartLocSocketB',
	],
	LightningEndSocket: [
		'LightningEndLocSocket',
		'LightningEndLocSocketL',
		'LightningEndLocSocketR',
		'LightningEndLocSocketA',
		'LightningEndLocSocketB',
	],
	mTeleportationCompleteRepNotify: docs_json_ts_common_types_integer_string,
	mTeleportationBeginRepNotify: docs_json_ts_common_types_integer_string,
	PortalActive: docs_json_ts_common_types_decimal_string,
	PortalFluctuation: docs_json_ts_common_types_decimal_string,
	mOnLinkedPortalChanged: docs_json_ts_common_types_empty_object,
	mOnPortalTraversableChanged: docs_json_ts_common_types_empty_object,
	mOnHeatUpStateChanged: docs_json_ts_common_types_empty_object,
	mMaxPortalTravelTime: docs_json_ts_common_types_decimal_string,
	mIsPortalTraversable: docs_json_ts_common_types_bool_string,
	mActorRepresentationColor: docs_json_ts_common_types_RGBA,
	mActorRepresentationViewDistance: 'CVD_Far',
	mActorRepresentationFogOfWarRevealRadius: docs_json_ts_common_types_decimal_string,
	mTeleportPowerConsumptionTimeLeft: docs_json_ts_common_types_decimal_string,
	mTeleportPowerConsumption: docs_json_ts_common_types_decimal_string,
	mCachedFactoryTickData: docs_json_ts_common_types_empty_object,
};

type FGBuildablePortal_version_specific = {
	OffsetFromPortalSurface: docs_json_ts_common_types_decimal_string,
	LightningStartVector: docs_json_ts_common_types_XYZ_decimal_string_list,
	LightningEndVector: docs_json_ts_common_types_XYZ_decimal_string_list,
	['In Value']: docs_json_ts_common_types_decimal_string,
	mFuelSlotSize: docs_json_ts_common_types_integer_string,
	mMinFuelToStartProducing: docs_json_ts_common_types_integer_string,
	mMinFuelToStartProducingAfterAbruptStop: docs_json_ts_common_types_integer_string,
	mPortalDisconnectedCooldownTime: docs_json_ts_common_types_decimal_string,
	mCachedInputConnections: '',
	mHeatUpComplete: docs_json_ts_common_types_bool_string,
	mHeatUpCycleTime: docs_json_ts_common_types_decimal_string,
	mCurrentHeatUpProgress: docs_json_ts_common_types_decimal_string,
	mCurrentProductionProgress: docs_json_ts_common_types_decimal_string,
	mLinkedPortalDisconnectCooldownTimeLeft: docs_json_ts_common_types_decimal_string,
	mCurrentProductionCycleTime: docs_json_ts_common_types_decimal_string,
	mTrippedProductionStop: docs_json_ts_common_types_bool_string,
	mCachedHasEnoughFuelForProduce: docs_json_ts_common_types_bool_string,
	mPortalName: Exclude<string, ''>,
};

type FGBuildablePortalSatellite = FGBuildable_base & FGBuildable_powered & FGBuildablePortal_common & FGBuildablePortalSatellite_version_specific;

type FGBuildablePortalSatellite_version_specific = {
	['Lightning End Socket']: null,
	['Lightning Start Socket']: null,
	mWasHeatingUpLastTick: docs_json_ts_common_types_bool_string,
	mPortalName: Exclude<string, ''>,
};

type FGBuildablePowerBooster = docs_json_ts_0_4_2_11_classes_base_has_mPowerConsumption & FGBuildable_powered & FGBuildablePowerBooster_version_specific;

type FGBuildablePowerBooster_version_specific = {
	IsInProducingAnimState: docs_json_ts_common_types_bool_string,
	LaserSocketNames: [
		'LeftArmLaser01_Vfx_Socket',
		'LeftArmLaser02_Vfx_Socket',
		'RightArmLaser01_Vfx_Socket',
		'RightArmLaser02_Vfx_Socket',
	],
	mVFX_LaserSubtract: docs_json_ts_common_types_decimal_string,
	mVFX_SummerSloop_Loc_Offset: docs_json_ts_common_types_XYZ_decimal_string,
	mVFX_SubVector: docs_json_ts_common_types_XYZ_decimal_string,
	m_Beam_TargetLoc: docs_json_ts_common_types_XYZ_decimal_string,
	mShrine_location: docs_json_ts_common_types_XYZ_decimal_string,
	bFirstRun: docs_json_ts_common_types_bool_string,
	mBasePowerProduction: docs_json_ts_common_types_decimal_string,
	mBaseBoostPercentage: docs_json_ts_common_types_decimal_string,
	mCurrentFuelBoostPercentage: docs_json_ts_common_types_decimal_string,
	mDefaultFuelClasses: [
		'/Game/FactoryGame/Resource/Parts/AlienPowerFuel/Desc_AlienPowerFuel.Desc_AlienPowerFuel_C',
	],
	mAvailableFuelClasses: '',
	mCachedInputConnections: '',
	mCurrentFuelDuration: docs_json_ts_common_types_decimal_string,
	mCurrentFuelDurationLeft: docs_json_ts_common_types_decimal_string,
};

type FGBuildablePowerPole = docs_json_ts_0_4_2_11_classes_base_FGBuildable_mHasPower_base & docs_json_ts_0_5_2_1_classes_base_FGBuildable_base_version_specific & docs_json_ts_0_8_3_3_classes_base_FGBuildablePowerPole_version_specific & FGBuildable_base;

type FGBuildablePowerStorage = docs_json_ts_0_4_2_11_classes_base_FGBuildablePowerStorage_base & FGBuildable_powered & FGBuildablePowerStorage_version_specific;

type FGBuildablePowerStorage_version_specific = {
	mStatusPrimitiveID: docs_json_ts_common_types_integer_string,
	mChargePrimitiveID: docs_json_ts_common_types_integer_string,
	mPowerInput: docs_json_ts_common_types_decimal_string,
};

type FGBuildablePriorityPowerSwitch = docs_json_ts_0_4_2_11_classes_base_FGBuildableCircuitSwitch_base & docs_json_ts_0_7_1_1_classes_base_FGBuildableCircuitSwitch_version_specific & docs_json_ts_0_8_3_3_classes_base_FGBuildable_has_mOnCircuitsChanged & docs_json_ts_0_8_3_3_classes_base_FGBuildablePriorityPowerSwitch_version_specific & FGBuildable_base;

type FGBuildableRadarTower = docs_json_ts_0_6_1_5_classes_base_FGBuildableRadarTower_version_specific & docs_json_ts_0_6_1_5_classes_base_overridable_FGBuildableRadarTower_version_specific & FGBuildable_powered;

type FGBuildableRailroadSignal_base = docs_json_ts_0_5_2_1_classes_base_FGBuildableRailroadSignal_base_version_specific & docs_json_ts_0_8_3_3_classes_base_FGBuildableRailroadSignal_version_specific & FGBuildable_base;

type FGBuildableRailroadSignal_block = docs_json_ts_0_5_2_1_classes_base_FGBuildableRailroadSignal_block_version_specific & FGBuildableRailroadSignal_base;

type FGBuildableRailroadStation = docs_json_ts_0_3_7_7_classes_base_FGBuildableRailroadStation_version_specific & docs_json_ts_0_3_7_7_classes_base_FGBuildableTrainPlatform_base_base_base & docs_json_ts_0_5_2_1_classes_base_FGBuildableRailroadStation_base & docs_json_ts_0_5_2_1_classes_base_FGBuildableTrainPlatform_base_version_specific & docs_json_ts_0_5_2_1_classes_base_FGBuildableTrainPlatform_non_empty_version_specific & FGBuildable_powered & FGBuildableTrainPlatform_version_specific;

type FGBuildableRailroadTrack = docs_json_ts_0_8_3_3_classes_base_overridable_FGBuildableRailroadTrack_version_specific & docs_json_ts_0_3_7_7_classes_base_FGBuildableRailroadTrack_base & docs_json_ts_0_5_2_1_classes_base_FGBuildableRailroadTrack_base_version_specific & FGBuildable_base;

type FGBuildableRampLightweight = docs_json_ts_0_5_2_1_classes_base_FGBuildableRamp_base & docs_json_ts_0_6_1_5_classes_base_has_mIsInverted & FGBuildableFoundation;

type FGBuildableResourceExtractor_base = docs_json_ts_0_3_7_7_classes_base_overridable_FGBuildableResourceExtractor_only_allow_certain_resources & docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_piped & docs_json_ts_0_6_1_5_classes_base_FGBuildableResourceExtractor_base_version_specific_base & FGBuildable_powered;

type FGBuildableResourceExtractor_miner_mk1 = docs_json_ts_0_3_7_7_classes_base_overridable_FGBuildableResourceExtractor_miner_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_miner_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_timed & docs_json_ts_0_4_2_11_classes_base_FGBuildableResourceExtractor_miner_mk1_version_specific & FGBuildableResourceExtractor_base & FGBuildableResourceExtractor_miner_mk1_version_specific & has_SAMReference;

type FGBuildableResourceExtractor_miner_mk1_version_specific = {
	InternalStartUpTimer: docs_json_ts_common_types_decimal_string,
};

type FGBuildableResourceExtractor_miner_mk2 = docs_json_ts_0_3_7_7_classes_base_overridable_FGBuildableResourceExtractor_miner_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_miner_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_miner_mk2_base_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_timed & FGBuildableResourceExtractor_base & has_SAMReference;

type FGBuildableResourceExtractor_miner_mk3 = docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_miner_base & docs_json_ts_0_3_7_7_classes_base_overridable_FGBuildableResourceExtractor_miner_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_miner_mk3_version_specific & docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_timed & FGBuildableResourceExtractor_base & has_SAMReference;

type FGBuildableResourceExtractor_oil = docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_oil_base_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_timed & FGBuildableResourceExtractor_base;

type FGBuildableResourceExtractor_water = docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_timed & docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_water_base_base_base & docs_json_ts_0_4_2_11_classes_base_FGBuildableResourceExtractor_water_base & FGBuildableResourceExtractor_base;

type FGBuildableResourceSink = docs_json_ts_0_4_2_11_classes_base_FGBuildableResourceSink_base_base & FGBuildable_powered;

type FGBuildableResourceSinkShop = docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceSinkShop_base_base_base & FGBuildable_powered;

type FGBuildableSnowCannon = FGBuildable_base & FGBuildableSnowCannon_version_specific;

type FGBuildableSnowCannon_version_specific = {
	SFXLocation: docs_json_ts_common_types_XYZ_decimal_string,
	mSignificanceRange: docs_json_ts_common_types_decimal_string,
	mAngleLimit: {
		Min: docs_json_ts_common_types_integer_string_signed,
		Max: docs_json_ts_common_types_integer_string,
	},
	mAngleOffset: docs_json_ts_common_types_integer_string_signed,
	mCannonAngle: docs_json_ts_common_types_integer_string,
};

type FGBuildableSpaceElevator = FGBuildable_powered & FGBuildableSpaceElevator_version_specific;

type FGBuildableSpaceElevator_version_specific = {
	mOnSpaceElevatorStateUpdated: docs_json_ts_common_types_empty_object,
	mSpaceElevatorState: 'ESES_Load',
};

type FGBuildableSplitterSmart = docs_json_ts_0_3_7_7_classes_base_FGBuildableAttachment_splitter_base_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableSplitterSmart_version_specific & docs_json_ts_0_4_2_11_classes_base_has_mInventorySize & FGBuildable_base;

type FGBuildableStorage = docs_json_ts_0_3_7_7_classes_base_FGBuildableStorage_base_base_base & FGBuildable_powered;

type FGBuildableTradingPost = docs_json_ts_0_3_7_7_classes_base_FGBuildableTradingPost_version_specific & docs_json_ts_0_4_2_11_classes_base_FGBuildableTradingPost_base_version_specific & docs_json_ts_0_5_2_1_classes_base_FGBuildableTradingPost_base & FGBuildable_powered & FGBuildableTradingPost_version_specific;

type FGBuildableTradingPost_version_specific = {
	mWorkBenchOccupied: Exclude<string, ''>,
	mWorkBenchFree: Exclude<string, ''>,
	mMamFreeText: Exclude<string, ''>,
	mMamOccupiedText: Exclude<string, ''>,
	Meshes: [
		'/Script/Engine.StaticMesh\'/Game/Geometry/Meshes/1M_Cube_Chamfer.1M_Cube_Chamfer\'',
		'/Script/Engine.StaticMesh\'/Game/Geometry/Meshes/1M_Cube_Chamfer.1M_Cube_Chamfer\'',
		'/Script/Engine.StaticMesh\'/Game/Geometry/Meshes/1M_Cube_Chamfer.1M_Cube_Chamfer\'',
		'/Script/Engine.StaticMesh\'/Game/Geometry/Meshes/1M_Cube_Chamfer.1M_Cube_Chamfer\'',
		'/Script/Engine.StaticMesh\'/Game/Geometry/Meshes/1M_Cube_Chamfer.1M_Cube_Chamfer\'',
		'/Script/Engine.StaticMesh\'/Game/Geometry/Meshes/1M_Cube_Chamfer.1M_Cube_Chamfer\'',
	],
	mMeshes: [
		'/Game/Geometry/Meshes/1M_Cube_Chamfer.1M_Cube_Chamfer',
		'/Game/Geometry/Meshes/1M_Cube_Chamfer.1M_Cube_Chamfer',
		'/Game/Geometry/Meshes/1M_Cube_Chamfer.1M_Cube_Chamfer',
		'/Game/Geometry/Meshes/1M_Cube_Chamfer.1M_Cube_Chamfer',
		'/Game/Geometry/Meshes/1M_Cube_Chamfer.1M_Cube_Chamfer',
		'/Game/Geometry/Meshes/1M_Cube_Chamfer.1M_Cube_Chamfer',
	],
	mStages: [
		'/Game/FactoryGame/Buildable/Factory/TradingPost/Mesh/SM_Hub_Stg_01.SM_Hub_Stg_01',
		'/Game/FactoryGame/Buildable/Factory/TradingPost/Mesh/SM_Hub_Stg_02.SM_Hub_Stg_02',
		'/Game/FactoryGame/Buildable/Factory/TradingPost/Mesh/SM_Hub_Stg_03.SM_Hub_Stg_03',
		'/Game/FactoryGame/Buildable/Factory/TradingPost/Mesh/SM_Hub_Stg_04.SM_Hub_Stg_04',
		'/Game/FactoryGame/Buildable/Factory/TradingPost/Mesh/SM_Hub_Stg_05.SM_Hub_Stg_05',
		'/Game/FactoryGame/Buildable/Factory/TradingPost/Mesh/SM_Hub_Stg_05.SM_Hub_Stg_05',
		'/Game/FactoryGame/Buildable/Factory/TradingPost/Mesh/SM_Hub_Stg_06.SM_Hub_Stg_06',
	],
	mLadderVisibilityLevel: docs_json_ts_common_types_integer_string,
	mLockerVisibilityLevel: docs_json_ts_common_types_integer_string,
	mMiniGameAndCalendarVisibilityLevel: docs_json_ts_common_types_integer_string,
};

type FGBuildableTrainPlatform_version_specific = {
	mPlatformConnections: [
		docs_json_ts_1_0_1_4_properties_FGTrainPlatformConnection_quoted,
		...docs_json_ts_1_0_1_4_properties_FGTrainPlatformConnection_quoted[],
	],
};

type FGBuildableTrainPlatformCargo = docs_json_ts_0_3_7_7_classes_base_FGBuildable_powered_storage_base_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableTrainPlatform_base_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableTrainPlatformCargo_version_specific & docs_json_ts_0_5_2_1_classes_base_FGBuildableTrainPlatform_base_version_specific & docs_json_ts_0_5_2_1_classes_base_FGBuildableTrainPlatform_non_empty_version_specific & docs_json_ts_0_5_2_1_classes_base_FGBuildableTrainPlatformCargo_version_specific & docs_json_ts_0_6_1_5_classes_base_FGBuildableTrainPlatformCargo_version_specific & FGBuildable_powered & FGBuildableTrainPlatform_version_specific;

type FGBuildableTrainPlatformEmpty = docs_json_ts_0_3_7_7_classes_base_FGBuildableTrainPlatform_base_base_base & docs_json_ts_0_5_2_1_classes_base_FGBuildableTrainPlatform_base_version_specific & FGBuildable_powered & FGBuildableTrainPlatform_version_specific;

type FGBuildableWalkway = docs_json_ts_0_3_7_7_classes_base_FGBuildable_with_size_and_elevation_base & docs_json_ts_0_3_7_7_classes_base_FGBuildable_with_size_and_elevation_base_base & FGBuildable_base;

type FGBuildableWall = docs_json_ts_0_5_2_1_classes_base_overridable_FGBuildable_is_wallish & docs_json_ts_0_3_7_7_classes_base_FGBuildable_with_height_and_width_base & docs_json_ts_0_5_2_1_classes_base_FGBuildable_with_elevation & FGBuildable_base;

type FGBuildableWidgetSign = docs_json_ts_0_5_2_1_classes_base_FGBuildableWidgetSign_base & docs_json_ts_0_8_3_3_classes_base_FGBuildableWidgetSign_version_specific & FGBuildable_base & FGBuildableWidgetSign_version_specific;

type FGBuildableWidgetSign_version_specific = {
	mTextElementToLocDataMap: docs_json_ts_common_types_empty_object,
	mSoftActivePrefabLayout: 'None',
	mActivePrefabLayout: docs_json_ts_common_types_empty_object,
	mGlobalPrefabIconElementSaveData: null,
};

type FGBuildableWire = docs_json_ts_0_3_7_7_classes_base_FGBuildableWire_base & docs_json_ts_0_8_3_3_classes_base_FGBuildableWire_version_specific & FGBuildable_base;

type FGCentralStorageContainer = FGBuildable_base & FGBuildableStorage & FGCentralStorageContainer_version_specific;

type FGCentralStorageContainer_version_specific = {
	TimeToExecuteCheckAfterItemAdded: docs_json_ts_common_types_decimal_string,
	mUploadTimer: docs_json_ts_common_types_decimal_string,
	mTimeToUpload: docs_json_ts_common_types_decimal_string,
};

type FGChainsaw = docs_json_ts_0_3_7_7_classes_base_FGChainsaw_version_specific & docs_json_ts_0_6_1_5_classes_base_FGChainsaw_version_specific & docs_json_ts_0_8_3_3_classes_base_FGChainsaw_version_specific & FGChainsaw_version_specific & FGEquipment;

type FGChainsaw_version_specific = {
	StartUpToIdleID: docs_json_ts_common_types_integer_string,
	mChainsawEngageMontage: docs_json_ts_1_0_1_4_properties_Montages_item,
	mChainsawSawingMontage: docs_json_ts_1_0_1_4_properties_Montages_item,
	mChainsawEquipFuelMontage: docs_json_ts_1_0_1_4_properties_Montages_item,
	mChainsawEquipNoFuelMontage: docs_json_ts_1_0_1_4_properties_Montages_item,
	mChainsawEquipStingerMontage: docs_json_ts_1_0_1_4_properties_Montages_item,
	mShowAOESelectorUITimer: docs_json_ts_common_types_empty_object,
	EngagePlayingID: docs_json_ts_common_types_integer_string,
	['IdlePlaying ID']: docs_json_ts_common_types_integer_string,
	['Playing ID']: docs_json_ts_common_types_integer_string,
	SawingPlayingID: docs_json_ts_common_types_integer_string,
	mIsAOEOn: docs_json_ts_common_types_bool_string,
};

type FGConsumableDescriptor = docs_json_ts_0_3_7_7_classes_base_FGConsumableDescriptor_base & docs_json_ts_0_4_2_11_classes_base_FGDescriptor_sinkable & FGItemDescriptor_base;

type FGConsumableEquipment_base = docs_json_ts_0_8_3_3_classes_base_overridable_FGConsumableEquipment_version_specific & docs_json_ts_0_3_7_7_classes_base_FGConsumableEquipment_version_specific & docs_json_ts_0_4_2_11_classes_base_FGConsumableEquipment_version_specific & FGConsumableEquipment_base_version_specific & FGEquipment;

type FGConsumableEquipment_base_version_specific = {
	mEatMontage: docs_json_ts_1_0_1_4_properties_Montages_item,
	mReEquipAfterEatMontage: docs_json_ts_1_0_1_4_properties_Montages_item,
};

type FGConsumableEquipment_medkit = docs_json_ts_0_8_3_3_classes_base_overridable_FGConsumableEquipment_version_specific & docs_json_ts_0_3_7_7_classes_base_FGConsumableEquipment_version_specific & docs_json_ts_0_4_2_11_classes_base_FGConsumableEquipment_version_specific & FGConsumableEquipment_medkit_version_specific & FGEquipment;

type FGConsumableEquipment_medkit_version_specific = {
	mMedkitUseMontages: docs_json_ts_1_0_1_4_properties_Montages,
	mCurrentMedkitUseMontage: {
		Weight: docs_json_ts_common_types_decimal_string,
	},
};

type FGEquipment = docs_json_ts_0_3_7_7_classes_base_overridable_FGEquipment_version_specific & docs_json_ts_0_8_3_3_classes_base_overridable_FGEquipment_version_specific & docs_json_ts_0_6_1_5_classes_base_FGEquipment_version_specific & docs_json_ts_common_classes_base_hasClassName & FGEquipment_pre_1_1 & FGEquipment_version_specific;

type FGEquipment_pre_1_1 = {
	mEquipMontage: docs_json_ts_1_0_1_4_properties_Montages,
};

type FGEquipment_version_specific = {
	mHasStingerMontage: docs_json_ts_common_types_bool_string,
	mStingerMontage?: docs_json_ts_1_0_1_4_properties_Montages,
	mUnEquipMontage?: docs_json_ts_common_types_empty_object | docs_json_ts_1_0_1_4_properties_Montages_item,
	mMontageBlendOutTime: docs_json_ts_common_types_decimal_string,
	mEquipmentLookAtDescOverride: string,
	mAttachSocket: 'None' | 'hand_rSocket' | 'hand_lSocket' | 'jumpingStilt_lSocket' | 'helmetSocket' | 'root' | 'backpack',
};

type FGEquipmentStunSpear_base = docs_json_ts_0_3_7_7_classes_base_FGEquipmentStunSpear_base_version_specific & docs_json_ts_0_6_1_5_classes_base_FGEquipmentStunSpear_base_version_specific & docs_json_ts_0_8_3_3_classes_base_FGEquipmentStunSpear_base_version_specific & FGEquipment;

type FGEquipmentStunSpear_version_specific = {
	mFirstSwingMontageList: docs_json_ts_1_0_1_4_properties_Montages,
	mSecondSwingMontageList: docs_json_ts_1_0_1_4_properties_Montages,
	mSecondSwingMinDelay: docs_json_ts_common_types_decimal_string,
	mSecondSwingMaxDelay: docs_json_ts_common_types_decimal_string,
	mSecondSwingUseCoolDown: docs_json_ts_common_types_decimal_string,
};

type FGEquipmentStunSpear_xenobasher = docs_json_ts_0_3_7_7_classes_base_FGEquipmentStunSpear_base_version_specific & FGEquipmentStunSpear_base & FGEquipmentStunSpear_version_specific;

type FGEquipmentStunSpear_xenozapper = FGEquipmentStunSpear_base & FGEquipmentStunSpear_version_specific;

type FGEquipmentZipline = docs_json_ts_0_4_2_11_classes_base_FGEquipmentZipline_version_specific & docs_json_ts_0_6_1_5_classes_base_FGEquipment_noisy_version_specific & FGEquipment & FGEquipmentZipline_version_specific;

type FGEquipmentZipline_version_specific = {
	mZiplineAttachMontage: docs_json_ts_1_0_1_4_properties_Montages_item,
	mZiplineDetachMontage: docs_json_ts_1_0_1_4_properties_Montages_item,
	mZiplineTryAttachMontage: docs_json_ts_1_0_1_4_properties_Montages_item,
	mWantToGrab: docs_json_ts_common_types_bool_string,
};

type FGGasMask = docs_json_ts_0_3_7_7_classes_base_FGEquipment_has_mFilterDuration & docs_json_ts_0_3_7_7_classes_base_FGGasMask_base & docs_json_ts_0_8_3_3_classes_base_FGGasMask_version_specific & FGEquipment;

type FGGolfCartDispenser = docs_json_ts_0_3_7_7_classes_base_FGGolfCartDispenser_has_mArmAnimation & docs_json_ts_0_5_2_1_classes_base_FGGolfCartDispenser_version_specific & FGEquipment & FGGolfCartDispenser_version_specific;

type FGGolfCartDispenser_version_specific = {
	mBuildDisqualifierText: Exclude<string, ''>,
	mChristmasMaterial: 'None' | '/Game/FactoryGame/Buildable/Vehicle/Golfcart/Material/MI_ChrismasCart_Inst.MI_ChrismasCart_Inst',
	mChristmasMaterial1P: 'None' | '/Game/FactoryGame/Buildable/Vehicle/Golfcart/Material/MI_ChrismasCart_Inst_1p.MI_ChrismasCart_Inst_1p',
	mCartPlacementClearance: docs_json_ts_common_types_XYZ_decimal_string,
	mCartPlacementDistance: docs_json_ts_common_types_decimal_string,
};

type FGHoverPack = docs_json_ts_0_4_2_11_classes_base_FGHoverPack_version_specific & docs_json_ts_0_6_1_5_classes_base_FGEquipment_noisy_version_specific & FGEquipment & FGHoverPack_version_specific;

type FGHoverPack_version_specific = {
	mCurrentPlayerVelocity_SFX: docs_json_ts_common_types_decimal_string,
	mCurrentMouseDelta_SFX: docs_json_ts_common_types_decimal_string,
	mLowBatteryWarningActive_SFX: docs_json_ts_common_types_bool_string,
	mPropellerVFX: null,
	mDisplayRangeWarning: docs_json_ts_common_types_bool_string,
};

type FGItemDescriptor = docs_json_ts_0_4_2_11_classes_base_FGDescriptor_sinkable & docs_json_ts_common_classes_FGItemDescriptor & FGItemDescriptor_base;

type FGItemDescriptor_base = docs_json_ts_0_6_1_5_classes_base_FGDescriptor & docs_json_ts_0_6_1_5_classes_base_FGItemDescriptor_version_specific & docs_json_ts_0_6_1_5_classes_base_overridable_FGItemDescriptor_version_specific & docs_json_ts_0_6_1_5_overridable_has_mSubCategories & FGItemDescriptor_version_specific;

type FGItemDescriptor_version_specific = {
	mGasType: 'GT_NORMAL' | 'GT_ENERGY',
	mIsAlienItem: docs_json_ts_common_types_bool_string,
	mNeedsPickUpMarker: docs_json_ts_common_types_bool_string,
	mClassToScanFor: 'None' | `/Game/FactoryGame/${'Resource/Environment/' | 'World/Benefit/' | 'Prototype/WAT'}${string}${'/BP_'}${Exclude<string, ''>}${'.BP_'}${Exclude<string, ''>}`,
	mDescriptorStatBars: null | [
		docs_json_ts_1_0_1_4_properties_FGItemDescriptor_version_specific_mDescriptorStatBars_item,
		...docs_json_ts_1_0_1_4_properties_FGItemDescriptor_version_specific_mDescriptorStatBars_item[],
	],
};

type FGItemDescriptorNuclearFuel = docs_json_ts_0_3_7_7_classes_base_FGItemDescriptorNuclearFuel_version_specific & FGItemDescriptor_base & FGItemDescriptorNuclearFuel_version_specific;

type FGItemDescriptorNuclearFuel_version_specific = {
	mSpentFuelClass: 'None' | docs_json_ts_0_4_2_11_overridable_BlueprintGeneratedClass_single_quoted,
};

type FGItemDescriptorPowerBoosterFuel = docs_json_ts_0_5_2_1_classes_base_has_mResourceSinkPoints & FGItemDescriptor_base & FGItemDescriptorPowerBoosterFuel_version_specific;

type FGItemDescriptorPowerBoosterFuel_version_specific = {
	mBoostPercentage: docs_json_ts_common_types_decimal_string,
	mBoostDuration: docs_json_ts_common_types_decimal_string,
};

type FGJetPack = docs_json_ts_0_7_1_1_classes_base_overridable_FGJetPack_version_specific & docs_json_ts_0_3_7_7_classes_base_FGJetPack_version_specific & docs_json_ts_0_6_1_5_classes_base_FGEquipment_noisy_version_specific & docs_json_ts_0_8_3_3_classes_base_FGJetPack_version_specific & FGEquipment & FGJetPack_version_specific;

type FGJetPack_version_specific = {
	mAttachSocket: 'backpack',
	mAllowedFuelTypes: [
		docs_json_ts_1_0_1_4_properties_FGJetPackFuelParameters_quoted,
		...docs_json_ts_1_0_1_4_properties_FGJetPackFuelParameters_quoted[],
	],
	mUnlockedFuelTypes: null,
	mAvailableFuelTypes: null,
};

type FGJumpingStilts = docs_json_ts_0_3_7_7_classes_base_FGJumpingStilts_base & docs_json_ts_0_6_1_5_classes_base_FGJumpingStilts_version_specific & FGEquipment;

type FGNobeliskDetonator = docs_json_ts_0_5_2_1_classes_base_overridable_FGWeapon_version_specific & docs_json_ts_0_3_7_7_classes_base_FGNobeliskDetonator_base & docs_json_ts_0_3_7_7_classes_base_FGWeaponProjectile_thrown_base_pre_1_0 & docs_json_ts_0_4_2_11_classes_base_FGWeaponProjectile_has_mBlockSprintWhenFiring & docs_json_ts_0_5_2_1_classes_base_FGNobeliskDetonator_version_specific & docs_json_ts_0_5_2_1_classes_base_FGWeapon_pre_1_1 & docs_json_ts_0_5_2_1_classes_base_FGWeapon_version_specific & docs_json_ts_0_6_1_5_classes_base_FGWeapon_base & FGEquipment & FGNobeliskDetonator_version_specific;

type FGNobeliskDetonator_version_specific = {
	AmmoTypeToAkEvent: [
		[
            `/Script/Engine.BlueprintGeneratedClass'/Game/FactoryGame${Exclude<string, ''>}${'\''}`,
            `/Script/AkAudio.AkAudioEvent'/Game/WwiseAudio${Exclude<string, ''>}${'\''}`,
		],
		...[
            `/Script/Engine.BlueprintGeneratedClass'/Game/FactoryGame${Exclude<string, ''>}${'\''}`,
            `/Script/AkAudio.AkAudioEvent'/Game/WwiseAudio${Exclude<string, ''>}${'\''}`,
		][],
	],
	mPrimaryFireStartMontageList: docs_json_ts_1_0_1_4_properties_Montages,
	mReloadMontageList: docs_json_ts_1_0_1_4_properties_Montages,
	mSecondaryFireMontageList: docs_json_ts_1_0_1_4_properties_Montages,
	mPrimaryFireEndMontageList: docs_json_ts_1_0_1_4_properties_Montages,
	mReleaseCooldown: docs_json_ts_common_types_decimal_string,
};

type FGObjectScanner = docs_json_ts_0_3_7_7_classes_base_FGObjectScanner_version_specific & docs_json_ts_0_8_3_3_classes_base_FGObjectScanner_version_specific & FGEquipment & FGObjectScanner_version_specific;

type FGObjectScanner_version_specific = {
	mScannerCycleLeftMontage: docs_json_ts_1_0_1_4_properties_Montages_item,
	mScannerCycleRightMontage: docs_json_ts_1_0_1_4_properties_Montages_item,
	mClosestObject: {
		ActorLocation: docs_json_ts_common_types_XYZ_decimal_string,
	},
};

type FGParachute = docs_json_ts_0_3_7_7_classes_base_FGParachute_has_mIsDeployed & docs_json_ts_0_8_3_3_classes_base_FGParachute_version_specific & FGEquipment & FGParachute_version_specific;

type FGParachute_version_specific = {
	mParachuteDeployMontageList: docs_json_ts_1_0_1_4_properties_Montages,
	mParachuteDetachMontageList: docs_json_ts_1_0_1_4_properties_Montages,
};

type FGPipeHyperStart = docs_json_ts_0_3_7_7_classes_base_FGBuildable_pole_base & docs_json_ts_0_3_7_7_classes_base_FGBuildable_with_mLength & docs_json_ts_0_3_7_7_classes_base_FGPipeHyperStart_base_base_base & docs_json_ts_0_3_7_7_classes_base_has_mCanStack & docs_json_ts_0_3_7_7_classes_base_has_mStackHeight & FGBuildable_powered;

type FGPoleDescriptor = docs_json_ts_0_6_1_5_classes_base_overridable_FGItemDescriptor_base & docs_json_ts_common_classes_FGPoleDescriptor & FGItemDescriptor_version_specific;

type FGPortableMinerDispenser = docs_json_ts_0_3_7_7_classes_base_FGPortableMinerDispenser_version_specific & docs_json_ts_0_4_2_11_classes_base_FGPortableMinerDispenser_version_specific & FGEquipment & FGPortableMinerDispenser_version_specific;

type FGPortableMinerDispenser_version_specific = {
	mEquipmentLookAtDescOverride: `${Exclude<string, ''>}${'[{PlayerActions_PrimaryFire}]'}${Exclude<string, ''>}${'{Ore}'}${Exclude<string, ''>}${'{Purity}'}` | `${Exclude<string, ''>}${'[{PlayerActions_PrimaryFire}]'}${Exclude<string, ''>}${'{Ore}'}${Exclude<string, ''>}${'{Purity}'}${Exclude<string, ''>}` | `${Exclude<string, ''>}${'[{PlayerActions_PrimaryFire}]'}${Exclude<string, ''>}${'{Purity}'}${Exclude<string, ''>}${'{Ore}'}` | `${Exclude<string, ''>}${'[{PlayerActions_PrimaryFire}]'}${Exclude<string, ''>}${'{Purity}'}${Exclude<string, ''>}${'{Ore}'}${Exclude<string, ''>}` | `${Exclude<string, ''>}${'{Ore}'}${Exclude<string, ''>}${'{Purity}'}${Exclude<string, ''>}${'[{PlayerActions_PrimaryFire}]'}${Exclude<string, ''>}` | `[{PlayerActions_PrimaryFire}]${Exclude<string, ''>}${'{Ore}'}${Exclude<string, ''>}${'{Purity}'}${Exclude<string, ''>}` | `${Exclude<string, ''>}${'{Ore}'}${'{Purity}'}${Exclude<string, ''>}${'{PlayerActions_PrimaryFire}'}${Exclude<string, ''>}` | `{Ore}${Exclude<string, ''>}${'{Purity}'}${Exclude<string, ''>}${'[{PlayerActions_PrimaryFire}]'}${Exclude<string, ''>}` | `${Exclude<string, ''>}${'{PlayerActions_PrimaryFire}'}${Exclude<string, ''>}${'{Ore}'}${'{Purity}'}${Exclude<string, ''>}` | `${Exclude<string, ''>}${'<{PlayerActions_PrimaryFire}>'}${Exclude<string, ''>}${'<{Ore}>'}${Exclude<string, ''>}${'<{Purity}>'}`,
};

type FGPowerShardDescriptor = docs_json_ts_0_3_7_7_classes_base_FGDescriptor_sinkable_base & FGItemDescriptor_base & FGItemDescriptor_version_specific & FGPowerShardDescriptor_version_specific;

type FGPowerShardDescriptor_version_specific = {
	mPowerShardType: 'PST_Overclock' | 'PST_ProductionBoost',
	mExtraPotential: docs_json_ts_common_types_decimal_string,
	mExtraProductionBoost: docs_json_ts_common_types_decimal_string,
};

type FGRecipe = docs_json_ts_0_5_2_1_classes_base_overridable_FGRecipe_version_specific & docs_json_ts_0_3_7_7_classes_base_FGRecipe_version_specific & docs_json_ts_0_3_7_7_classes_base_instructive & docs_json_ts_0_4_2_11_classes_base_FGRecipe_version_specific & docs_json_ts_common_classes_FGRecipe & FGRecipe_version_specific;

type FGRecipe_version_specific = {
	mProducedIn: docs_json_ts_1_0_1_4_properties_mProducedIn,
};

type FGResourceDescriptor = docs_json_ts_0_6_1_5_classes_base_overridable_FGItemDescriptor_base & docs_json_ts_0_3_7_7_classes_base_FGResourceDescriptor_base & docs_json_ts_0_4_2_11_classes_base_FGDescriptor_sinkable & FGItemDescriptor_version_specific & FGResourceDescriptor_version_specific;

type FGResourceDescriptor_version_specific = {
	mManualMiningAudioName: 'Metal' | 'Sam',
};

type FGSchematic = docs_json_ts_0_3_7_7_classes_base_overridable_FGSchematic_version_specific & docs_json_ts_0_5_2_1_classes_base_overridable_FGSchematic_version_specific & docs_json_ts_0_8_3_3_classes_base_overridable_FGSchematic_has_mSchematicIcon & docs_json_ts_0_8_3_3_classes_base_overridable_FGSchematic_version_specific & docs_json_ts_0_3_7_7_classes_base_instructive & docs_json_ts_0_3_7_7_classes_base_isDescribed & docs_json_ts_0_6_1_5_classes_base_FGSchematic_version_specific & docs_json_ts_1_0_1_4_properties_FGSchematic_has_mSchematicDependencies & docs_json_ts_common_classes_FGSchematic & FGSchematic_has_mTechTier & FGSchematic_pre_1_1 & FGSchematic_version_specific;

type FGSchematic_has_mTechTier = {
	mTechTier: docs_json_ts_1_0_1_4_properties_Tier,
};

type FGSchematic_pre_1_1 = {
	mStatisticGameplayTag: docs_json_ts_common_types_empty_object | docs_json_ts_1_0_1_4_properties_mStatisticGameplayTag,
};

type FGSchematic_version_specific = {
	mSchematicUnlockTag: docs_json_ts_common_types_empty_object | {
		TagName: 'Stats.Gameplay.UnlockedGoldenNut',
	},
	mUnlocks: [
		...docs_json_ts_1_0_1_4_properties_mUnlocks_item[],
	],
	mType?: 'EST_Custom' | 'EST_Customization' | 'EST_Tutorial' | 'EST_MAM' | 'EST_HardDrive' | 'EST_Milestone' | 'EST_Alternate' | 'EST_ResourceSink',
};

type FGSchematic_with_described_unlocks = docs_json_ts_0_5_2_1_classes_base_FGSchematic_with_described_unlocks_version_specific & FGSchematic;

type FGSuitBase = docs_json_ts_0_3_7_7_classes_base_FGEquipment_has_mFilterDuration & docs_json_ts_0_3_7_7_classes_base_FGEquipment_has_effect_timer & docs_json_ts_0_3_7_7_classes_base_FGEquipment_negates_damage & docs_json_ts_0_3_7_7_classes_base_FGSuitBase_base & docs_json_ts_0_6_1_5_classes_base_FGSuitBase_version_specific & FGEquipment & FGSuitBase_version_specific;

type FGSuitBase_version_specific = {
	mSuitMeshMaterials: [
		{
			SlotName: 'Pioneer_torso',
			Material: docs_json_ts_0_3_7_7_overridable_MaterialInstanceConstant_quoted,
			Material3P: docs_json_ts_0_3_7_7_overridable_MaterialInstanceConstant_quoted,
		},
		{
			SlotName: 'Pioneer_Legs',
			Material: docs_json_ts_0_3_7_7_overridable_MaterialInstanceConstant_quoted,
			Material3P: docs_json_ts_0_3_7_7_overridable_MaterialInstanceConstant_quoted,
		},
	],
};

type FGVehicleDescriptor_Desc_CyberWagon_C = docs_json_ts_0_6_1_5_classes_base_FGVehicleDescriptor_Desc_CyberWagon_C & FGItemDescriptor_base;

type FGVehicleDescriptor_Desc_DroneTransport_C = docs_json_ts_0_6_1_5_classes_base_FGVehicleDescriptor_Desc_DroneTransport_C & FGItemDescriptor_base;

type FGVehicleDescriptor_Desc_Explorer_C = docs_json_ts_0_6_1_5_classes_base_FGVehicleDescriptor_Desc_Explorer_C & FGItemDescriptor_base;

type FGVehicleDescriptor_Desc_FreightWagon_C = docs_json_ts_0_6_1_5_classes_base_FGVehicleDescriptor_Desc_FreightWagon_C & FGItemDescriptor_base;

type FGVehicleDescriptor_Desc_Locomotive_C = docs_json_ts_0_6_1_5_classes_base_FGVehicleDescriptor_Desc_Locomotive_C & FGItemDescriptor_base;

type FGVehicleDescriptor_Desc_Tractor_C = docs_json_ts_0_6_1_5_classes_base_FGVehicleDescriptor_Desc_Tractor_C & FGItemDescriptor_base;

type FGVehicleDescriptor_Desc_Truck_C = docs_json_ts_0_6_1_5_classes_base_FGVehicleDescriptor_Desc_Truck_C & FGItemDescriptor_base;

type FGWeapon_Equip_RebarGun_Projectile_C = docs_json_ts_0_5_2_1_classes_base_overridable_FGWeapon_version_specific & docs_json_ts_0_3_7_7_classes_base_FGEquipment_has_mEquipmentSlot & docs_json_ts_0_3_7_7_classes_base_FGWeaponProjectile_has_mAttachSocket & docs_json_ts_0_4_2_11_classes_base_FGWeaponProjectile_has_mBlockSprintWhenFiring & docs_json_ts_0_5_2_1_classes_base_FGWeapon_pre_1_1 & docs_json_ts_0_5_2_1_classes_base_FGWeapon_version_specific & docs_json_ts_0_6_1_5_classes_base_FGWeapon_base & FGEquipment & FGWeapon_pre_1_1 & FGWeapon_version_specific;

type FGWeapon_Equip_Rifle_C = docs_json_ts_0_5_2_1_classes_base_overridable_FGWeapon_version_specific & docs_json_ts_0_3_7_7_classes_base_FGEquipment_has_mEquipmentSlot & docs_json_ts_0_3_7_7_classes_base_FGWeaponInstantFire_base_base_base & docs_json_ts_0_3_7_7_classes_base_FGWeaponProjectile_has_mAttachSocket & docs_json_ts_0_4_2_11_classes_base_FGWeaponProjectile_has_mBlockSprintWhenFiring & docs_json_ts_0_5_2_1_classes_base_FGWeapon_Equip_Rifle_C_base & docs_json_ts_0_5_2_1_classes_base_FGWeapon_pre_1_1 & docs_json_ts_0_5_2_1_classes_base_FGWeapon_version_specific & docs_json_ts_0_6_1_5_classes_base_FGWeapon_base & FGEquipment & FGWeapon_pre_1_1 & FGWeapon_version_specific;

type FGWeapon_pre_1_1 = {
	mFireMontage: {
		Montage_1P: docs_json_ts_0_3_7_7_overridable_AnimMontage_quoted,
		Montage_3P: docs_json_ts_0_3_7_7_overridable_AnimMontage_quoted,
		Montage_Equipment: docs_json_ts_0_3_7_7_overridable_AnimMontage_quoted,
		AudioEvent: docs_json_ts_0_8_3_3_properties_overridable_DocsDotJson_AkAudioEvent_quoted_list_item,
		CameraAnim: docs_json_ts_0_8_3_3_properties_overridable_CameraAnimationSequence_quoted,
	},
};

type FGWeapon_version_specific = {
	mReloadMontageList: docs_json_ts_1_0_1_4_properties_Montages,
	mAmmoSwapMontageList: docs_json_ts_1_0_1_4_properties_Montages,
	mFailedToFireMontageList: docs_json_ts_1_0_1_4_properties_Montages,
	mSupressDryFireMontage: docs_json_ts_common_types_bool_string,
};

export type {
	has_SAMReference,
	FGAmmoTypeInstantHit_Desc_CartridgeChaos_C,
	FGAmmoTypeInstantHit_Desc_CartridgeStandard_C,
	FGAmmoTypeProjectile,
	FGAmmoTypeProjectile_version_specific,
	FGAmmoTypeSpreadshot,
	FGBuildable_base,
	FGBuildable_occupied,
	FGBuildable_powered,
	FGBuildable_powered_version_specific,
	FGBuildable_tiered,
	FGBuildable_version_specific,
	FGBuildableAttachmentMerger,
	FGBuildableAttachmentSplitter,
	FGBuildableBeamLightweight,
	FGBuildableBlueprintDesigner,
	FGBuildableBlueprintDesigner_version_specific,
	FGBuildableCircuitSwitch,
	FGBuildableConveyorBelt,
	FGBuildableConveyorBelt_version_specific,
	FGBuildableConveyorLift,
	FGBuildableConveyorLift_version_specific,
	FGBuildableCornerWall,
	FGBuildableDockingStation,
	FGBuildableDoor,
	FGBuildableDoor_automated,
	FGBuildableDoor_manual,
	FGBuildableDroneStation,
	FGBuildableDroneStation_version_specific,
	FGBuildableFactory_jump_pad,
	FGBuildableFactory_landing_pad,
	FGBuildableFactorySimpleProducer,
	FGBuildableFloodlight,
	FGBuildableFoundation,
	FGBuildableFrackingActivator,
	FGBuildableFrackingExtractor,
	FGBuildableGenerator,
	FGBuildableGenerator_no_fuel,
	FGBuildableGenerator_version_specific,
	FGBuildableGeneratorFuel_biomass,
	FGBuildableGeneratorFuel_biomass_version_specific,
	FGBuildableGeneratorFuel_coal,
	FGBuildableGeneratorFuel_fuel,
	FGBuildableGeneratorFuel_fuel_version_specific,
	FGBuildableGeneratorGeoThermal,
	FGBuildableGeneratorNuclear,
	FGBuildableGeneratorNuclear_version_specific,
	FGBuildableJumppad,
	FGBuildableLadder,
	FGBuildableLightsControlPanel,
	FGBuildableLightSource,
	FGBuildableLightSource_Build_StreetLight_C,
	FGBuildableMAM,
	FGBuildableMAM_version_specific,
	FGBuildableManufacturer_Build_AssemblerMk1_C,
	FGBuildableManufacturer_Build_Blender_C,
	FGBuildableManufacturer_Build_ConstructorMk1_C,
	FGBuildableManufacturer_Build_ConstructorMk1_C_version_specific,
	FGBuildableManufacturer_Build_Converter_C,
	FGBuildableManufacturer_Build_FoundryMk1_C,
	FGBuildableManufacturer_Build_HadronCollider_C,
	FGBuildableManufacturer_Build_ManufacturerMk1_C,
	FGBuildableManufacturer_Build_OilRefinery_C,
	FGBuildableManufacturer_Build_Packager_C,
	FGBuildableManufacturer_Build_QuantumEncoder_C,
	FGBuildableManufacturer_Build_QuantumEncoder_C_version_specific,
	FGBuildableManufacturer_Build_SmelterMk1_C,
	FGBuildablePassthrough,
	FGBuildablePillarLightweight,
	FGBuildablePipeHyper,
	FGBuildablePipeline,
	FGBuildablePipeline_version_specific,
	FGBuildablePipelineJunction,
	FGBuildablePipelinePump_pump,
	FGBuildablePipelinePump_valve,
	FGBuildablePipelinePump_version_specific,
	FGBuildablePipelineSupport,
	FGBuildablePipeReservoir,
	FGBuildablePoleBase,
	FGBuildablePoleLightweight,
	FGBuildablePortal,
	FGBuildablePortal_common,
	FGBuildablePortal_version_specific,
	FGBuildablePortalSatellite,
	FGBuildablePortalSatellite_version_specific,
	FGBuildablePowerBooster,
	FGBuildablePowerBooster_version_specific,
	FGBuildablePowerPole,
	FGBuildablePowerStorage,
	FGBuildablePowerStorage_version_specific,
	FGBuildablePriorityPowerSwitch,
	FGBuildableRadarTower,
	FGBuildableRailroadSignal_base,
	FGBuildableRailroadSignal_block,
	FGBuildableRailroadStation,
	FGBuildableRailroadTrack,
	FGBuildableRampLightweight,
	FGBuildableResourceExtractor_base,
	FGBuildableResourceExtractor_miner_mk1,
	FGBuildableResourceExtractor_miner_mk1_version_specific,
	FGBuildableResourceExtractor_miner_mk2,
	FGBuildableResourceExtractor_miner_mk3,
	FGBuildableResourceExtractor_oil,
	FGBuildableResourceExtractor_water,
	FGBuildableResourceSink,
	FGBuildableResourceSinkShop,
	FGBuildableSnowCannon,
	FGBuildableSnowCannon_version_specific,
	FGBuildableSpaceElevator,
	FGBuildableSpaceElevator_version_specific,
	FGBuildableSplitterSmart,
	FGBuildableStorage,
	FGBuildableTradingPost,
	FGBuildableTradingPost_version_specific,
	FGBuildableTrainPlatform_version_specific,
	FGBuildableTrainPlatformCargo,
	FGBuildableTrainPlatformEmpty,
	FGBuildableWalkway,
	FGBuildableWall,
	FGBuildableWidgetSign,
	FGBuildableWidgetSign_version_specific,
	FGBuildableWire,
	FGCentralStorageContainer,
	FGCentralStorageContainer_version_specific,
	FGChainsaw,
	FGChainsaw_version_specific,
	FGConsumableDescriptor,
	FGConsumableEquipment_base,
	FGConsumableEquipment_base_version_specific,
	FGConsumableEquipment_medkit,
	FGConsumableEquipment_medkit_version_specific,
	FGEquipment,
	FGEquipment_pre_1_1,
	FGEquipment_version_specific,
	FGEquipmentStunSpear_base,
	FGEquipmentStunSpear_version_specific,
	FGEquipmentStunSpear_xenobasher,
	FGEquipmentStunSpear_xenozapper,
	FGEquipmentZipline,
	FGEquipmentZipline_version_specific,
	FGGasMask,
	FGGolfCartDispenser,
	FGGolfCartDispenser_version_specific,
	FGHoverPack,
	FGHoverPack_version_specific,
	FGItemDescriptor,
	FGItemDescriptor_base,
	FGItemDescriptor_version_specific,
	FGItemDescriptorNuclearFuel,
	FGItemDescriptorNuclearFuel_version_specific,
	FGItemDescriptorPowerBoosterFuel,
	FGItemDescriptorPowerBoosterFuel_version_specific,
	FGJetPack,
	FGJetPack_version_specific,
	FGJumpingStilts,
	FGNobeliskDetonator,
	FGNobeliskDetonator_version_specific,
	FGObjectScanner,
	FGObjectScanner_version_specific,
	FGParachute,
	FGParachute_version_specific,
	FGPipeHyperStart,
	FGPoleDescriptor,
	FGPortableMinerDispenser,
	FGPortableMinerDispenser_version_specific,
	FGPowerShardDescriptor,
	FGPowerShardDescriptor_version_specific,
	FGRecipe,
	FGRecipe_version_specific,
	FGResourceDescriptor,
	FGResourceDescriptor_version_specific,
	FGSchematic,
	FGSchematic_has_mTechTier,
	FGSchematic_pre_1_1,
	FGSchematic_version_specific,
	FGSchematic_with_described_unlocks,
	FGSuitBase,
	FGSuitBase_version_specific,
	FGVehicleDescriptor_Desc_CyberWagon_C,
	FGVehicleDescriptor_Desc_DroneTransport_C,
	FGVehicleDescriptor_Desc_Explorer_C,
	FGVehicleDescriptor_Desc_FreightWagon_C,
	FGVehicleDescriptor_Desc_Locomotive_C,
	FGVehicleDescriptor_Desc_Tractor_C,
	FGVehicleDescriptor_Desc_Truck_C,
	FGWeapon_Equip_RebarGun_Projectile_C,
	FGWeapon_Equip_Rifle_C,
	FGWeapon_pre_1_1,
	FGWeapon_version_specific,
};
