/* eslint-disable @stylistic/max-len */

import type {
	BGRA as docs_json_ts_common_types_BGRA,
	bool_string as docs_json_ts_common_types_bool_string,
	decimal_string as docs_json_ts_common_types_decimal_string,
	decimal_string_signed as docs_json_ts_common_types_decimal_string_signed,
	empty_object as docs_json_ts_common_types_empty_object,
	integer_string as docs_json_ts_common_types_integer_string,
	RGBA as docs_json_ts_common_types_RGBA,
	XYZ_decimal_string as docs_json_ts_common_types_XYZ_decimal_string,
} from './../../common/types.ts';

import type {
	FGBuildable_base_version_specific as docs_json_ts_0_4_2_11_classes_base_FGBuildable_base_version_specific,
	FGBuildable_has_mCachedSkeletalMeshes as docs_json_ts_0_4_2_11_classes_base_FGBuildable_has_mCachedSkeletalMeshes,
	FGBuildable_light_related_thing_base as docs_json_ts_0_4_2_11_classes_base_FGBuildable_light_related_thing_base,
	FGBuildable_mStopped_audio_stuff as docs_json_ts_0_4_2_11_classes_base_FGBuildable_mStopped_audio_stuff,
	FGBuildable_powered_storage_base as docs_json_ts_0_4_2_11_classes_base_FGBuildable_powered_storage_base,
	FGBuildableCircuitSwitch_base as docs_json_ts_0_4_2_11_classes_base_FGBuildableCircuitSwitch_base,
	FGBuildableDroneStation_pre_1_0 as docs_json_ts_0_4_2_11_classes_base_FGBuildableDroneStation_pre_1_0,
	FGBuildableDroneStation_version_specific as docs_json_ts_0_4_2_11_classes_base_FGBuildableDroneStation_version_specific,
	FGBuildableFloodlight_version_specific as docs_json_ts_0_4_2_11_classes_base_FGBuildableFloodlight_version_specific,
	FGBuildableFrackingActivator_base as docs_json_ts_0_4_2_11_classes_base_FGBuildableFrackingActivator_base,
	FGBuildableGeneratorFuel_base_base as docs_json_ts_0_4_2_11_classes_base_FGBuildableGeneratorFuel_base_base,
	FGBuildableGeneratorGeoThermal_base as docs_json_ts_0_4_2_11_classes_base_FGBuildableGeneratorGeoThermal_base,
	FGBuildableGeneratorNuclear_pre_1_0 as docs_json_ts_0_4_2_11_classes_base_FGBuildableGeneratorNuclear_pre_1_0,
	FGBuildableGeneratorNuclear_version_specific as docs_json_ts_0_4_2_11_classes_base_FGBuildableGeneratorNuclear_version_specific,
	FGBuildableLightsControlPanel_version_specific as docs_json_ts_0_4_2_11_classes_base_FGBuildableLightsControlPanel_version_specific,
	FGBuildableLightSource_version_specific as docs_json_ts_0_4_2_11_classes_base_FGBuildableLightSource_version_specific,
	FGBuildableMAM_version_specific as docs_json_ts_0_4_2_11_classes_base_FGBuildableMAM_version_specific,
	FGBuildableManufacturer_base_blender_base as docs_json_ts_0_4_2_11_classes_base_FGBuildableManufacturer_base_blender_base,
	FGBuildableManufacturer_base_constructor_base as docs_json_ts_0_4_2_11_classes_base_FGBuildableManufacturer_base_constructor_base,
	FGBuildableManufacturer_Build_HadronCollider_C_base as docs_json_ts_0_4_2_11_classes_base_FGBuildableManufacturer_Build_HadronCollider_C_base,
	FGBuildableManufacturerVariablePower as docs_json_ts_0_4_2_11_classes_base_FGBuildableManufacturerVariablePower,
	FGBuildablePipelineJunction_base_base as docs_json_ts_0_4_2_11_classes_base_FGBuildablePipelineJunction_base_base,
	FGBuildablePowerStorage_base as docs_json_ts_0_4_2_11_classes_base_FGBuildablePowerStorage_base,
	FGBuildableResourceExtractor_miner_mk1_base_base as docs_json_ts_0_4_2_11_classes_base_FGBuildableResourceExtractor_miner_mk1_base_base,
	FGBuildableResourceExtractor_water_base as docs_json_ts_0_4_2_11_classes_base_FGBuildableResourceExtractor_water_base,
	FGBuildableResourceSink_base as docs_json_ts_0_4_2_11_classes_base_FGBuildableResourceSink_base,
	FGBuildableTradingPost_base as docs_json_ts_0_4_2_11_classes_base_FGBuildableTradingPost_base,
	FGBuildableTradingPost_base_pre_1_0 as docs_json_ts_0_4_2_11_classes_base_FGBuildableTradingPost_base_pre_1_0,
	FGBuildableTradingPost_base_version_specific as docs_json_ts_0_4_2_11_classes_base_FGBuildableTradingPost_base_version_specific,
	FGConsumableEquipment_version_specific as docs_json_ts_0_4_2_11_classes_base_FGConsumableEquipment_version_specific,
	FGDescriptor as docs_json_ts_0_4_2_11_classes_base_FGDescriptor,
	FGDescriptor_base as docs_json_ts_0_4_2_11_classes_base_FGDescriptor_base,
	FGDescriptor_sinkable as docs_json_ts_0_4_2_11_classes_base_FGDescriptor_sinkable,
	FGEquipment_base as docs_json_ts_0_4_2_11_classes_base_FGEquipment_base,
	FGEquipmentZipline_pre_1_0 as docs_json_ts_0_4_2_11_classes_base_FGEquipmentZipline_pre_1_0,
	FGEquipmentZipline_version_specific as docs_json_ts_0_4_2_11_classes_base_FGEquipmentZipline_version_specific,
	FGHoverPack_pre_1_0 as docs_json_ts_0_4_2_11_classes_base_FGHoverPack_pre_1_0,
	FGHoverPack_version_specific as docs_json_ts_0_4_2_11_classes_base_FGHoverPack_version_specific,
	FGSchematic_has_mMenuPriority as docs_json_ts_0_4_2_11_classes_base_FGSchematic_has_mMenuPriority,
	FGSchematic_has_mTechTier as docs_json_ts_0_4_2_11_classes_base_FGSchematic_has_mTechTier,
	FGVehicleDescriptor_fueled_with_inventory_base as docs_json_ts_0_4_2_11_classes_base_FGVehicleDescriptor_fueled_with_inventory_base,
	FGVehicleDescriptor_powered_base as docs_json_ts_0_4_2_11_classes_base_FGVehicleDescriptor_powered_base,
	FGWeaponProjectile_has_mBlockSprintWhenFiring as docs_json_ts_0_4_2_11_classes_base_FGWeaponProjectile_has_mBlockSprintWhenFiring,
	FGWeaponProjectileFire_has_mMuteDryFire as docs_json_ts_0_4_2_11_classes_base_FGWeaponProjectileFire_has_mMuteDryFire,
	has_mHasPower as docs_json_ts_0_4_2_11_classes_base_has_mHasPower,
	has_mInventorySize as docs_json_ts_0_4_2_11_classes_base_has_mInventorySize,
	has_mPowerConsumption as docs_json_ts_0_4_2_11_classes_base_has_mPowerConsumption,
} from './../../0.4.2.11/classes/Base.ts';

import type {
	FGBuildable_base_pre_1_0 as docs_json_ts_0_5_2_1_classes_base_FGBuildable_base_pre_1_0,
	FGBuildable_base_version_specific as docs_json_ts_0_5_2_1_classes_base_FGBuildable_base_version_specific,
	FGBuildable_docking_station as docs_json_ts_0_5_2_1_classes_base_FGBuildable_docking_station,
	FGBuildable_isFrame as docs_json_ts_0_5_2_1_classes_base_FGBuildable_isFrame,
	FGBuildable_mSnappedPassthroughs as docs_json_ts_0_5_2_1_classes_base_FGBuildable_mSnappedPassthroughs,
	FGBuildable_powered_version_specific as docs_json_ts_0_5_2_1_classes_base_FGBuildable_powered_version_specific,
	FGBuildableAttachment_splitter as docs_json_ts_0_5_2_1_classes_base_FGBuildableAttachment_splitter,
	FGBuildableBeam_version_specific as docs_json_ts_0_5_2_1_classes_base_FGBuildableBeam_version_specific,
	FGBuildableConveyorBelt_version_specific as docs_json_ts_0_5_2_1_classes_base_FGBuildableConveyorBelt_version_specific,
	FGBuildableCornerWall as docs_json_ts_0_5_2_1_classes_base_FGBuildableCornerWall,
	FGBuildableDockingStation_base as docs_json_ts_0_5_2_1_classes_base_FGBuildableDockingStation_base,
	FGBuildableDoor_automated_version_specific as docs_json_ts_0_5_2_1_classes_base_FGBuildableDoor_automated_version_specific,
	FGBuildableDoor_base as docs_json_ts_0_5_2_1_classes_base_FGBuildableDoor_base,
	FGBuildableDoor_manual_version_specific as docs_json_ts_0_5_2_1_classes_base_FGBuildableDoor_manual_version_specific,
	FGBuildableGenerator as docs_json_ts_0_5_2_1_classes_base_FGBuildableGenerator,
	FGBuildableGenerator_no_fuel as docs_json_ts_0_5_2_1_classes_base_FGBuildableGenerator_no_fuel,
	FGBuildableLightsControlPanel_version_specific as docs_json_ts_0_5_2_1_classes_base_FGBuildableLightsControlPanel_version_specific,
	FGBuildableLightSource_base as docs_json_ts_0_5_2_1_classes_base_FGBuildableLightSource_base,
	FGBuildableLightSource_Build_StreetLight_C_version_specific as docs_json_ts_0_5_2_1_classes_base_FGBuildableLightSource_Build_StreetLight_C_version_specific,
	FGBuildableManufacturer_Build_ConstructorMk1_C_base as docs_json_ts_0_5_2_1_classes_base_FGBuildableManufacturer_Build_ConstructorMk1_C_base,
	FGBuildableManufacturer_Build_FoundryMk1_C_base as docs_json_ts_0_5_2_1_classes_base_FGBuildableManufacturer_Build_FoundryMk1_C_base,
	FGBuildableManufacturer_Build_SmelterMk1_C_base as docs_json_ts_0_5_2_1_classes_base_FGBuildableManufacturer_Build_SmelterMk1_C_base,
	FGBuildablePassthrough_base as docs_json_ts_0_5_2_1_classes_base_FGBuildablePassthrough_base,
	FGBuildablePassthrough_pre_update8 as docs_json_ts_0_5_2_1_classes_base_FGBuildablePassthrough_pre_update8,
	FGBuildablePipeHyper_version_specific as docs_json_ts_0_5_2_1_classes_base_FGBuildablePipeHyper_version_specific,
	FGBuildablePipeline_base_spline as docs_json_ts_0_5_2_1_classes_base_FGBuildablePipeline_base_spline,
	FGBuildableRailroadSignal_base as docs_json_ts_0_5_2_1_classes_base_FGBuildableRailroadSignal_base,
	FGBuildableRailroadSignal_block_version_specific as docs_json_ts_0_5_2_1_classes_base_FGBuildableRailroadSignal_block_version_specific,
	FGBuildableRailroadStation_base as docs_json_ts_0_5_2_1_classes_base_FGBuildableRailroadStation_base,
	FGBuildableRailroadTrack_base as docs_json_ts_0_5_2_1_classes_base_FGBuildableRailroadTrack_base,
	FGBuildableRailroadTrack_base_version_specific as docs_json_ts_0_5_2_1_classes_base_FGBuildableRailroadTrack_base_version_specific,
	FGBuildableRamp_base as docs_json_ts_0_5_2_1_classes_base_FGBuildableRamp_base,
	FGBuildableStair_has_mStairDirection as docs_json_ts_0_5_2_1_classes_base_FGBuildableStair_has_mStairDirection,
	FGBuildableTradingPost_version_specific as docs_json_ts_0_5_2_1_classes_base_FGBuildableTradingPost_version_specific,
	FGBuildableTrainPlatform_base as docs_json_ts_0_5_2_1_classes_base_FGBuildableTrainPlatform_base,
	FGBuildableTrainPlatform_non_empty as docs_json_ts_0_5_2_1_classes_base_FGBuildableTrainPlatform_non_empty,
	FGBuildableTrainPlatform_with_storage as docs_json_ts_0_5_2_1_classes_base_FGBuildableTrainPlatform_with_storage,
	FGBuildableTrainPlatformCargo_version_specific as docs_json_ts_0_5_2_1_classes_base_FGBuildableTrainPlatformCargo_version_specific,
	FGBuildableWidgetSign_base as docs_json_ts_0_5_2_1_classes_base_FGBuildableWidgetSign_base,
	FGDescriptor as docs_json_ts_0_5_2_1_classes_base_FGDescriptor,
	FGGolfCartDispenser as docs_json_ts_0_5_2_1_classes_base_FGGolfCartDispenser,
	FGItemDescAmmoTypeProjectile_base_base as docs_json_ts_0_5_2_1_classes_base_FGItemDescAmmoTypeProjectile_base_base,
	FGItemDescriptor_base_base as docs_json_ts_0_5_2_1_classes_base_FGItemDescriptor_base_base,
	FGNobeliskDetonator_version_specific as docs_json_ts_0_5_2_1_classes_base_FGNobeliskDetonator_version_specific,
	FGSchematic_with_described_unlocks_version_specific as docs_json_ts_0_5_2_1_classes_base_FGSchematic_with_described_unlocks_version_specific,
	FGWeapon_Equip_Rifle_C_base as docs_json_ts_0_5_2_1_classes_base_FGWeapon_Equip_Rifle_C_base,
	FGWeapon_pre_1_1 as docs_json_ts_0_5_2_1_classes_base_FGWeapon_pre_1_1,
	FGWeapon_version_specific as docs_json_ts_0_5_2_1_classes_base_FGWeapon_version_specific,
	has_mIsSupport as docs_json_ts_0_5_2_1_classes_base_has_mIsSupport,
	has_mSize_vector as docs_json_ts_0_5_2_1_classes_base_has_mSize_vector,
	has_mSplineData as docs_json_ts_0_5_2_1_classes_base_has_mSplineData,
} from './../../0.5.2.1/classes/Base.ts';

import type {
	BP_RadialDamageType_Explosive_C_quoted as docs_json_ts_0_6_1_5_properties_BP_RadialDamageType_Explosive_C_quoted,
	BP_RadialDamageType_Gas_C_quoted as docs_json_ts_0_6_1_5_properties_BP_RadialDamageType_Gas_C_quoted,
	DamageTypes as docs_json_ts_0_6_1_5_properties_DamageTypes,
	DocsDotJson_AkAudioEvent_quoted_list as docs_json_ts_0_6_1_5_properties_DocsDotJson_AkAudioEvent_quoted_list,
	FGBuildable_mOcclusionBoxInfo_item as docs_json_ts_0_6_1_5_properties_FGBuildable_mOcclusionBoxInfo_item,
	FGItemDescriptor_version_specific_mDescriptorStatBars_item as docs_json_ts_0_6_1_5_properties_FGItemDescriptor_version_specific_mDescriptorStatBars_item,
	FGObjectScanner_mObjectDetails_item as docs_json_ts_0_6_1_5_properties_FGObjectScanner_mObjectDetails_item,
	mAllowedResourceForms as docs_json_ts_0_6_1_5_properties_mAllowedResourceForms,
	mDisableSnapOn_front_right as docs_json_ts_0_6_1_5_properties_mDisableSnapOn_front_right,
	mProducedIn as docs_json_ts_0_6_1_5_properties_mProducedIn,
} from './../types/properties.ts';

import type {
	FGAmmoType_base as docs_json_ts_0_6_1_5_classes_base_overridable_FGAmmoType_base,
	FGAmmoType_version_specific as docs_json_ts_0_6_1_5_classes_base_overridable_FGAmmoType_version_specific,
	FGAmmoTypeProjectile_version_specific as docs_json_ts_0_6_1_5_classes_base_overridable_FGAmmoTypeProjectile_version_specific,
	FGBuildable_base_version_specific as docs_json_ts_0_6_1_5_classes_base_overridable_FGBuildable_base_version_specific,
	FGBuildableRadarTower_version_specific as docs_json_ts_0_6_1_5_classes_base_overridable_FGBuildableRadarTower_version_specific,
	FGItemDescriptor_base as docs_json_ts_0_6_1_5_classes_base_overridable_FGItemDescriptor_base,
	FGObjectScanner_version_specific as docs_json_ts_0_6_1_5_classes_base_overridable_FGObjectScanner_version_specific,
	FGSchematic_version_specific_mUnlocks as docs_json_ts_0_6_1_5_classes_base_overridable_FGSchematic_version_specific_mUnlocks,
} from './Base.overridable.ts';

import type {
	FGAmmoTypeInstantHit as docs_json_ts_common_classes_FGAmmoTypeInstantHit,
	FGAmmoTypeProjectile as docs_json_ts_common_classes_FGAmmoTypeProjectile,
	FGAmmoTypeSpreadshot as docs_json_ts_common_classes_FGAmmoTypeSpreadshot,
	FGBuildable_occupied as docs_json_ts_common_classes_FGBuildable_occupied,
	FGBuildable_tiered as docs_json_ts_common_classes_FGBuildable_tiered,
	FGBuildable_unoccupied_and_untiered as docs_json_ts_common_classes_FGBuildable_unoccupied_and_untiered,
	FGBuildableAttachmentMerger as docs_json_ts_common_classes_FGBuildableAttachmentMerger,
	FGBuildableAttachmentSplitter as docs_json_ts_common_classes_FGBuildableAttachmentSplitter,
	FGBuildableBeam as docs_json_ts_common_classes_FGBuildableBeam,
	FGBuildableCircuitSwitch as docs_json_ts_common_classes_FGBuildableCircuitSwitch,
	FGBuildableConveyorBelt as docs_json_ts_common_classes_FGBuildableConveyorBelt,
	FGBuildableConveyorLift as docs_json_ts_common_classes_FGBuildableConveyorLift,
	FGBuildableCornerWall as docs_json_ts_common_classes_FGBuildableCornerWall,
	FGBuildableDockingStation as docs_json_ts_common_classes_FGBuildableDockingStation,
	FGBuildableDoor as docs_json_ts_common_classes_FGBuildableDoor,
	FGBuildableDroneStation as docs_json_ts_common_classes_FGBuildableDroneStation,
	FGBuildableFactory as docs_json_ts_common_classes_FGBuildableFactory,
	FGBuildableFactoryBuilding as docs_json_ts_common_classes_FGBuildableFactoryBuilding,
	FGBuildableFactorySimpleProducer as docs_json_ts_common_classes_FGBuildableFactorySimpleProducer,
	FGBuildableFloodlight as docs_json_ts_common_classes_FGBuildableFloodlight,
	FGBuildableFoundation as docs_json_ts_common_classes_FGBuildableFoundation,
	FGBuildableFrackingActivator as docs_json_ts_common_classes_FGBuildableFrackingActivator,
	FGBuildableFrackingExtractor as docs_json_ts_common_classes_FGBuildableFrackingExtractor,
	FGBuildableGeneratorFuel as docs_json_ts_common_classes_FGBuildableGeneratorFuel,
	FGBuildableGeneratorGeoThermal as docs_json_ts_common_classes_FGBuildableGeneratorGeoThermal,
	FGBuildableGeneratorNuclear as docs_json_ts_common_classes_FGBuildableGeneratorNuclear,
	FGBuildableJumppad as docs_json_ts_common_classes_FGBuildableJumppad,
	FGBuildableLadder as docs_json_ts_common_classes_FGBuildableLadder,
	FGBuildableLightsControlPanel as docs_json_ts_common_classes_FGBuildableLightsControlPanel,
	FGBuildableLightSource as docs_json_ts_common_classes_FGBuildableLightSource,
	FGBuildableMAM as docs_json_ts_common_classes_FGBuildableMAM,
	FGBuildableManufacturer as docs_json_ts_common_classes_FGBuildableManufacturer,
	FGBuildableManufacturerVariablePower as docs_json_ts_common_classes_FGBuildableManufacturerVariablePower,
	FGBuildablePassthrough as docs_json_ts_common_classes_FGBuildablePassthrough,
	FGBuildablePillar as docs_json_ts_common_classes_FGBuildablePillar,
	FGBuildablePipeHyper as docs_json_ts_common_classes_FGBuildablePipeHyper,
	FGBuildablePipeline as docs_json_ts_common_classes_FGBuildablePipeline,
	FGBuildablePipelineJunction as docs_json_ts_common_classes_FGBuildablePipelineJunction,
	FGBuildablePipelinePump as docs_json_ts_common_classes_FGBuildablePipelinePump,
	FGBuildablePipelineSupport as docs_json_ts_common_classes_FGBuildablePipelineSupport,
	FGBuildablePipeReservoir as docs_json_ts_common_classes_FGBuildablePipeReservoir,
	FGBuildablePole as docs_json_ts_common_classes_FGBuildablePole,
	FGBuildablePowerPole as docs_json_ts_common_classes_FGBuildablePowerPole,
	FGBuildablePowerStorage as docs_json_ts_common_classes_FGBuildablePowerStorage,
	FGBuildableRadarTower as docs_json_ts_common_classes_FGBuildableRadarTower,
	FGBuildableRailroadSignal_block as docs_json_ts_common_classes_FGBuildableRailroadSignal_block,
	FGBuildableRailroadSignal_path as docs_json_ts_common_classes_FGBuildableRailroadSignal_path,
	FGBuildableRailroadStation as docs_json_ts_common_classes_FGBuildableRailroadStation,
	FGBuildableRailroadTrack as docs_json_ts_common_classes_FGBuildableRailroadTrack,
	FGBuildableRamp as docs_json_ts_common_classes_FGBuildableRamp,
	FGBuildableResourceExtractor as docs_json_ts_common_classes_FGBuildableResourceExtractor,
	FGBuildableResourceSink as docs_json_ts_common_classes_FGBuildableResourceSink,
	FGBuildableResourceSinkShop as docs_json_ts_common_classes_FGBuildableResourceSinkShop,
	FGBuildableSnowDispenser as docs_json_ts_common_classes_FGBuildableSnowDispenser,
	FGBuildableSpaceElevator as docs_json_ts_common_classes_FGBuildableSpaceElevator,
	FGBuildableSplitterSmart as docs_json_ts_common_classes_FGBuildableSplitterSmart,
	FGBuildableStair as docs_json_ts_common_classes_FGBuildableStair,
	FGBuildableStorage as docs_json_ts_common_classes_FGBuildableStorage,
	FGBuildableTradingPost as docs_json_ts_common_classes_FGBuildableTradingPost,
	FGBuildableTrainPlatformCargo as docs_json_ts_common_classes_FGBuildableTrainPlatformCargo,
	FGBuildableTrainPlatformEmpty as docs_json_ts_common_classes_FGBuildableTrainPlatformEmpty,
	FGBuildableWalkway as docs_json_ts_common_classes_FGBuildableWalkway,
	FGBuildableWall as docs_json_ts_common_classes_FGBuildableWall,
	FGBuildableWidgetSign as docs_json_ts_common_classes_FGBuildableWidgetSign,
	FGBuildableWire as docs_json_ts_common_classes_FGBuildableWire,
	FGChainsaw as docs_json_ts_common_classes_FGChainsaw,
	FGConsumableEquipment as docs_json_ts_common_classes_FGConsumableEquipment,
	FGConveyorPoleStackable as docs_json_ts_common_classes_FGConveyorPoleStackable,
	FGEquipmentDescriptor as docs_json_ts_common_classes_FGEquipmentDescriptor,
	FGEquipmentStunSpear as docs_json_ts_common_classes_FGEquipmentStunSpear,
	FGEquipmentZipline as docs_json_ts_common_classes_FGEquipmentZipline,
	FGGasMask as docs_json_ts_common_classes_FGGasMask,
	FGGolfCartDispenser as docs_json_ts_common_classes_FGGolfCartDispenser,
	FGHoverPack as docs_json_ts_common_classes_FGHoverPack,
	FGItemDescriptor as docs_json_ts_common_classes_FGItemDescriptor,
	FGItemDescriptorBiomass as docs_json_ts_common_classes_FGItemDescriptorBiomass,
	FGJetPack as docs_json_ts_common_classes_FGJetPack,
	FGJumpingStilts as docs_json_ts_common_classes_FGJumpingStilts,
	FGNobeliskDetonator as docs_json_ts_common_classes_FGNobeliskDetonator,
	FGObjectScanner as docs_json_ts_common_classes_FGObjectScanner,
	FGParachute as docs_json_ts_common_classes_FGParachute,
	FGPipeHyperStart as docs_json_ts_common_classes_FGPipeHyperStart,
	FGPortableMinerDispenser as docs_json_ts_common_classes_FGPortableMinerDispenser,
	FGResourceDescriptor as docs_json_ts_common_classes_FGResourceDescriptor,
	FGSchematic as docs_json_ts_common_classes_FGSchematic,
	FGSuitBase as docs_json_ts_common_classes_FGSuitBase,
	FGVehicleDescriptor as docs_json_ts_common_classes_FGVehicleDescriptor,
	FGWeapon_Equip_RebarGun_Projectile_C as docs_json_ts_common_classes_FGWeapon_Equip_RebarGun_Projectile_C,
	FGWeapon_Equip_Rifle_C as docs_json_ts_common_classes_FGWeapon_Equip_Rifle_C,
} from './../../common/classes.ts';

import type {
	FalloffCurve_EditorCurveData_only as docs_json_ts_0_5_2_1_properties_FalloffCurve_EditorCurveData_only,
	mDisableSnapOn_bottom as docs_json_ts_0_5_2_1_properties_mDisableSnapOn_bottom,
	mDisableSnapOn_top as docs_json_ts_0_5_2_1_properties_mDisableSnapOn_top,
} from './../../0.5.2.1/types/properties.ts';

import type {
	FGBuildable_base_pre_1_0 as docs_json_ts_0_3_7_7_classes_base_FGBuildable_base_pre_1_0,
	FGBuildable_base_version_specific as docs_json_ts_0_3_7_7_classes_base_FGBuildable_base_version_specific,
	FGBuildable_docking_station_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildable_docking_station_base_base_base,
	FGBuildable_docking_station_base_with_mMapText as docs_json_ts_0_3_7_7_classes_base_FGBuildable_docking_station_base_with_mMapText,
	FGBuildable_occupied_base as docs_json_ts_0_3_7_7_classes_base_FGBuildable_occupied_base,
	FGBuildable_powered_base_resources_base as docs_json_ts_0_3_7_7_classes_base_FGBuildable_powered_base_resources_base,
	FGBuildable_powered_pre_1_0 as docs_json_ts_0_3_7_7_classes_base_FGBuildable_powered_pre_1_0,
	FGBuildable_powered_storage_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildable_powered_storage_base_base,
	FGBuildable_powered_version_specific as docs_json_ts_0_3_7_7_classes_base_FGBuildable_powered_version_specific,
	FGBuildable_tiered_base as docs_json_ts_0_3_7_7_classes_base_FGBuildable_tiered_base,
	FGBuildable_with_mLength as docs_json_ts_0_3_7_7_classes_base_FGBuildable_with_mLength,
	FGBuildableAttachment_has_mCurrentInventoryIndex as docs_json_ts_0_3_7_7_classes_base_FGBuildableAttachment_has_mCurrentInventoryIndex,
	FGBuildableAttachment_splitter_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableAttachment_splitter_base_base_base,
	FGBuildableAttachmentMerger_version_specific as docs_json_ts_0_3_7_7_classes_base_FGBuildableAttachmentMerger_version_specific,
	FGBuildableConveyorBelt_pre_1_0 as docs_json_ts_0_3_7_7_classes_base_FGBuildableConveyorBelt_pre_1_0,
	FGBuildableConveyorBelt_pre_update8 as docs_json_ts_0_3_7_7_classes_base_FGBuildableConveyorBelt_pre_update8,
	FGBuildableConveyorLift_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableConveyorLift_base,
	FGBuildableDockingStation_with_mFuelTransferSpeed as docs_json_ts_0_3_7_7_classes_base_FGBuildableDockingStation_with_mFuelTransferSpeed,
	FGBuildableFactory_jump_pad_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableFactory_jump_pad_base_base,
	FGBuildableFactory_landing_pad_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableFactory_landing_pad_base_base,
	FGBuildableFactorySimpleProducer_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableFactorySimpleProducer_base_base,
	FGBuildableGenerator_no_fuel_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableGenerator_no_fuel_base_base,
	FGBuildableGenerator_no_fuel_base_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableGenerator_no_fuel_base_base_base_base,
	FGBuildableGeneratorFuel_biomass_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableGeneratorFuel_biomass_base_base,
	FGBuildableGeneratorFuel_coal_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableGeneratorFuel_coal_base_base,
	FGBuildableGeneratorFuel_fuel_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableGeneratorFuel_fuel_base_base,
	FGBuildableGeneratorGeoThermal_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableGeneratorGeoThermal_base_base,
	FGBuildableGeneratorNuclear_version_specific as docs_json_ts_0_3_7_7_classes_base_FGBuildableGeneratorNuclear_version_specific,
	FGBuildableJumppad_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableJumppad_base_base,
	FGBuildableLadder_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableLadder_base,
	FGBuildableManufacturer_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_base,
	FGBuildableManufacturer_base_IsPowered_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_IsPowered_base,
	FGBuildableManufacturer_base_mProductionEffectsRunning_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_mProductionEffectsRunning_base,
	FGBuildableManufacturer_base_packager_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_packager_base,
	FGBuildableManufacturer_Build_SmelterMk1_C_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_Build_SmelterMk1_C_base,
	FGBuildablePipeline_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildablePipeline_base_base,
	FGBuildablePipeline_base_no_indicator_base as docs_json_ts_0_3_7_7_classes_base_FGBuildablePipeline_base_no_indicator_base,
	FGBuildablePipeline_base_root as docs_json_ts_0_3_7_7_classes_base_FGBuildablePipeline_base_root,
	FGBuildablePipelinePump_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildablePipelinePump_base_base,
	FGBuildablePipelinePump_powered_version_specific as docs_json_ts_0_3_7_7_classes_base_FGBuildablePipelinePump_powered_version_specific,
	FGBuildablePipelinePump_pump_version_specific as docs_json_ts_0_3_7_7_classes_base_FGBuildablePipelinePump_pump_version_specific,
	FGBuildablePipelineSupport_base as docs_json_ts_0_3_7_7_classes_base_FGBuildablePipelineSupport_base,
	FGBuildablePipeReservoir_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildablePipeReservoir_base_base,
	FGBuildablePowerPole_base as docs_json_ts_0_3_7_7_classes_base_FGBuildablePowerPole_base,
	FGBuildableRailroadStation_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableRailroadStation_base_base,
	FGBuildableResourceExtractor_miner_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_miner_base,
	FGBuildableResourceExtractor_miner_mk2_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_miner_mk2_base_base,
	FGBuildableResourceExtractor_miner_mk3_version_specific as docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_miner_mk3_version_specific,
	FGBuildableResourceExtractor_oil_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_oil_base_base,
	FGBuildableResourceExtractor_piped as docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_piped,
	FGBuildableResourceExtractor_piped_pre_1_0 as docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_piped_pre_1_0,
	FGBuildableResourceExtractor_timed as docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_timed,
	FGBuildableResourceExtractor_water_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_water_base_base,
	FGBuildableResourceSinkShop_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceSinkShop_base_base,
	FGBuildableSplitterSmart_version_specific as docs_json_ts_0_3_7_7_classes_base_FGBuildableSplitterSmart_version_specific,
	FGBuildableStorage_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableStorage_base_base,
	FGBuildableTradingPost_pre_1_0 as docs_json_ts_0_3_7_7_classes_base_FGBuildableTradingPost_pre_1_0,
	FGBuildableTradingPost_pre_update8 as docs_json_ts_0_3_7_7_classes_base_FGBuildableTradingPost_pre_update8,
	FGBuildableTradingPost_version_specific as docs_json_ts_0_3_7_7_classes_base_FGBuildableTradingPost_version_specific,
	FGBuildableTrainPlatform_with_storage_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableTrainPlatform_with_storage_base_base_base,
	FGBuildableTrainPlatformCargo_pre_update8 as docs_json_ts_0_3_7_7_classes_base_FGBuildableTrainPlatformCargo_pre_update8,
	FGBuildableTrainPlatformCargo_version_specific as docs_json_ts_0_3_7_7_classes_base_FGBuildableTrainPlatformCargo_version_specific,
	FGBuildableWire_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableWire_base,
	FGChainsaw_pre_1_0 as docs_json_ts_0_3_7_7_classes_base_FGChainsaw_pre_1_0,
	FGChainsaw_pre_update8 as docs_json_ts_0_3_7_7_classes_base_FGChainsaw_pre_update8,
	FGChainsaw_version_specific as docs_json_ts_0_3_7_7_classes_base_FGChainsaw_version_specific,
	FGConsumableEquipment_pre_update8 as docs_json_ts_0_3_7_7_classes_base_FGConsumableEquipment_pre_update8,
	FGConsumableEquipment_version_specific as docs_json_ts_0_3_7_7_classes_base_FGConsumableEquipment_version_specific,
	FGEquipment as docs_json_ts_0_3_7_7_classes_base_FGEquipment,
	FGEquipment_base as docs_json_ts_0_3_7_7_classes_base_FGEquipment_base,
	FGEquipment_dispenser as docs_json_ts_0_3_7_7_classes_base_FGEquipment_dispenser,
	FGEquipment_has_effect_timer as docs_json_ts_0_3_7_7_classes_base_FGEquipment_has_effect_timer,
	FGEquipment_has_mFilterDuration as docs_json_ts_0_3_7_7_classes_base_FGEquipment_has_mFilterDuration,
	FGEquipment_has_mPlayingSound as docs_json_ts_0_3_7_7_classes_base_FGEquipment_has_mPlayingSound,
	FGEquipment_has_mRandomStingerAnim as docs_json_ts_0_3_7_7_classes_base_FGEquipment_has_mRandomStingerAnim,
	FGEquipment_negates_damage as docs_json_ts_0_3_7_7_classes_base_FGEquipment_negates_damage,
	FGEquipmentStunSpear_xenobasher_base as docs_json_ts_0_3_7_7_classes_base_FGEquipmentStunSpear_xenobasher_base,
	FGEquipmentStunSpear_xenozapper_base as docs_json_ts_0_3_7_7_classes_base_FGEquipmentStunSpear_xenozapper_base,
	FGGasMask_base as docs_json_ts_0_3_7_7_classes_base_FGGasMask_base,
	FGJetPack_pre_1_0 as docs_json_ts_0_3_7_7_classes_base_FGJetPack_pre_1_0,
	FGJetPack_pre_update7 as docs_json_ts_0_3_7_7_classes_base_FGJetPack_pre_update7,
	FGJetPack_version_specific as docs_json_ts_0_3_7_7_classes_base_FGJetPack_version_specific,
	FGJumpingStilts_base as docs_json_ts_0_3_7_7_classes_base_FGJumpingStilts_base,
	FGNobeliskDetonator_base as docs_json_ts_0_3_7_7_classes_base_FGNobeliskDetonator_base,
	FGObjectScanner_pre_1_0 as docs_json_ts_0_3_7_7_classes_base_FGObjectScanner_pre_1_0,
	FGObjectScanner_pre_update8 as docs_json_ts_0_3_7_7_classes_base_FGObjectScanner_pre_update8,
	FGObjectScanner_version_specific as docs_json_ts_0_3_7_7_classes_base_FGObjectScanner_version_specific,
	FGParachute_has_mIsDeployed as docs_json_ts_0_3_7_7_classes_base_FGParachute_has_mIsDeployed,
	FGParachute_has_mTerminalVelocityZ as docs_json_ts_0_3_7_7_classes_base_FGParachute_has_mTerminalVelocityZ,
	FGPipeHyperStart_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGPipeHyperStart_base_base_base,
	FGPipeHyperStart_pre_update8 as docs_json_ts_0_3_7_7_classes_base_FGPipeHyperStart_pre_update8,
	FGPortableMinerDispenser_version_specific as docs_json_ts_0_3_7_7_classes_base_FGPortableMinerDispenser_version_specific,
	FGResourceDescriptor_base as docs_json_ts_0_3_7_7_classes_base_FGResourceDescriptor_base,
	FGSchematic_pre_1_0 as docs_json_ts_0_3_7_7_classes_base_FGSchematic_pre_1_0,
	FGSuitBase_base as docs_json_ts_0_3_7_7_classes_base_FGSuitBase_base,
	FGWeaponInstantFire_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGWeaponInstantFire_base_base_base,
	FGWeaponProjectile_has_mAttachSocket as docs_json_ts_0_3_7_7_classes_base_FGWeaponProjectile_has_mAttachSocket,
	FGWeaponProjectile_thrown_base_base as docs_json_ts_0_3_7_7_classes_base_FGWeaponProjectile_thrown_base_base,
	FGWeaponProjectile_thrown_base_pre_1_0 as docs_json_ts_0_3_7_7_classes_base_FGWeaponProjectile_thrown_base_pre_1_0,
	FGWeaponProjectileFire_has_mRandomReloadAnim as docs_json_ts_0_3_7_7_classes_base_FGWeaponProjectileFire_has_mRandomReloadAnim,
	has_mCanStack as docs_json_ts_0_3_7_7_classes_base_has_mCanStack,
	has_mDisableSnapOn as docs_json_ts_0_3_7_7_classes_base_has_mDisableSnapOn,
	has_mElevation as docs_json_ts_0_3_7_7_classes_base_has_mElevation,
	has_mHeight as docs_json_ts_0_3_7_7_classes_base_has_mHeight,
	has_mMeshLength as docs_json_ts_0_3_7_7_classes_base_has_mMeshLength,
	has_mNumCyclesForProductivity as docs_json_ts_0_3_7_7_classes_base_has_mNumCyclesForProductivity,
	has_mRTPCInterval as docs_json_ts_0_3_7_7_classes_base_has_mRTPCInterval,
	has_mSize as docs_json_ts_0_3_7_7_classes_base_has_mSize,
	has_mSplineData as docs_json_ts_0_3_7_7_classes_base_has_mSplineData,
	has_mStackHeight as docs_json_ts_0_3_7_7_classes_base_has_mStackHeight,
	has_mUseStaticHeight as docs_json_ts_0_3_7_7_classes_base_has_mUseStaticHeight,
	has_mWidth as docs_json_ts_0_3_7_7_classes_base_has_mWidth,
} from './../../0.3.7.7/classes/Base.ts';

import type {
	mDisableSnapOn_front_bottom as docs_json_ts_0_3_7_7_properties_mDisableSnapOn_front_bottom,
	mDisableSnapOn_top_bottom as docs_json_ts_0_3_7_7_properties_mDisableSnapOn_top_bottom,
} from './../../0.3.7.7/types/properties.ts';

import type {
	FGBuildable_is_wallish as docs_json_ts_0_5_2_1_classes_base_overridable_FGBuildable_is_wallish,
	FGSchematic_version_specific as docs_json_ts_0_5_2_1_classes_base_overridable_FGSchematic_version_specific,
	FGWeapon_version_specific as docs_json_ts_0_5_2_1_classes_base_overridable_FGWeapon_version_specific,
} from './../../0.5.2.1/classes/Base.overridable.ts';

import type {
	has_mBatteryClasses as docs_json_ts_0_4_2_11_overridable_has_mBatteryClasses,
} from './../../0.4.2.11/types/overridable.ts';

import type {
	FGBuildableResourceExtractor_miner_base as docs_json_ts_0_3_7_7_classes_base_overridable_FGBuildableResourceExtractor_miner_base,
	FGBuildableResourceExtractor_only_allow_certain_resources as docs_json_ts_0_3_7_7_classes_base_overridable_FGBuildableResourceExtractor_only_allow_certain_resources,
	FGSchematic_version_specific as docs_json_ts_0_3_7_7_classes_base_overridable_FGSchematic_version_specific,
	FGSuitBase_pre_1_0 as docs_json_ts_0_3_7_7_classes_base_overridable_FGSuitBase_pre_1_0,
} from './../../0.3.7.7/classes/Base.overridable.ts';

import type {
	Texture2D as docs_json_ts_0_4_2_11_properties_Texture2D,
} from './../../0.4.2.11/types/properties.ts';

import type {
	FGSchematic_has_mSchematicDependencies as docs_json_ts_0_4_2_11_classes_base_overridable_FGSchematic_has_mSchematicDependencies,
	FGSchematic_has_mSchematicIcon as docs_json_ts_0_4_2_11_classes_base_overridable_FGSchematic_has_mSchematicIcon,
} from './../../0.4.2.11/classes/Base.overridable.ts';

import type {
	isDescribed as docs_json_ts_common_classes_base_isDescribed,
} from './../../common/classes/Base.ts';

import type {
	ItemClass_Amount_list as docs_json_ts_0_3_7_7_overridable_ItemClass_Amount_list,
} from './../../0.3.7.7/types/overridable.ts';

import type {
	ItemClass_list as docs_json_ts_0_6_1_5_overridable_ItemClass_list,
} from './../types/overridable.ts';

type has_mIsInverted = {
	mIsInverted: docs_json_ts_common_types_bool_string,
};

type FGAmmoType_base = docs_json_ts_0_4_2_11_classes_base_FGDescriptor_sinkable & docs_json_ts_0_5_2_1_classes_base_FGDescriptor & docs_json_ts_0_5_2_1_classes_base_FGItemDescAmmoTypeProjectile_base_base & docs_json_ts_0_5_2_1_classes_base_FGItemDescriptor_base_base & FGAmmoType_version_specific;

type FGAmmoType_pre_update8 = {
	mDamageTypesOnImpact: null | docs_json_ts_0_6_1_5_properties_DamageTypes,
	mFiringSounds: null | docs_json_ts_0_6_1_5_properties_DocsDotJson_AkAudioEvent_quoted_list,
	mAmmoTickFunction: {
		bCanEverTick: docs_json_ts_common_types_bool_string,
		bStartWithTickEnabled: docs_json_ts_common_types_bool_string,
		bAllowTickOnDedicatedServer: docs_json_ts_common_types_bool_string,
	},
};

type FGAmmoType_version_specific = {
	mFiringDirection: docs_json_ts_common_types_XYZ_decimal_string,
	mReloadTimeMultiplier: docs_json_ts_common_types_decimal_string,
	mFireRate: docs_json_ts_common_types_decimal_string,
	mFiringTransformIgnoresDispersion: docs_json_ts_common_types_bool_string,
	mDispersionFireRateMultiplier: docs_json_ts_common_types_decimal_string,
	mDispersionPerShot: docs_json_ts_common_types_decimal_string,
	mRestingDispersion: docs_json_ts_common_types_decimal_string,
	mFiringDispersion: docs_json_ts_common_types_decimal_string,
	mDispersionRecoveryTime?: docs_json_ts_common_types_decimal_string,
	mMuzzleFlashScale: docs_json_ts_common_types_XYZ_decimal_string,
	mAmmoColor: docs_json_ts_common_types_RGBA,
	mAmmoScale: docs_json_ts_common_types_decimal_string,
};

type FGAmmoTypeInstantHit_Desc_CartridgeChaos_C = docs_json_ts_0_6_1_5_classes_base_overridable_FGAmmoType_base & docs_json_ts_0_6_1_5_classes_base_overridable_FGAmmoType_version_specific & docs_json_ts_common_classes_FGAmmoTypeInstantHit & FGAmmoType_base & FGAmmoType_pre_update8 & FGAmmoType_version_specific & FGAmmoTypeInstantHit_Desc_CartridgeChaos_C_version_specific & FGAmmoTypeInstantHit_version_specific;

type FGAmmoTypeInstantHit_Desc_CartridgeChaos_C_version_specific = {
	Location: docs_json_ts_common_types_XYZ_decimal_string,
	Trail_Velocity: docs_json_ts_common_types_decimal_string,
};

type FGAmmoTypeInstantHit_Desc_CartridgeStandard_C = docs_json_ts_0_6_1_5_classes_base_overridable_FGAmmoType_base & docs_json_ts_0_6_1_5_classes_base_overridable_FGAmmoType_version_specific & docs_json_ts_common_classes_FGAmmoTypeInstantHit & FGAmmoType_base & FGAmmoType_pre_update8 & FGAmmoType_version_specific & FGAmmoTypeInstantHit_version_specific;

type FGAmmoTypeInstantHit_version_specific = {
	mPlayFireEffects: docs_json_ts_common_types_bool_string,
};

type FGAmmoTypeProjectile = docs_json_ts_0_6_1_5_classes_base_overridable_FGAmmoType_base & docs_json_ts_0_6_1_5_classes_base_overridable_FGAmmoTypeProjectile_version_specific & docs_json_ts_common_classes_FGAmmoTypeProjectile & FGAmmoType_base & FGAmmoType_pre_update8 & FGAmmoTypeProjectile_pre_update8 & FGAmmoTypeProjectile_version_specific;

type FGAmmoTypeProjectile_pre_update8 = {
	mDamageTypesAtEndOfLife: null | [
		docs_json_ts_0_6_1_5_properties_BP_RadialDamageType_Explosive_C_quoted,
		...docs_json_ts_0_6_1_5_properties_BP_RadialDamageType_Explosive_C_quoted[],
	] | [
		docs_json_ts_0_6_1_5_properties_BP_RadialDamageType_Gas_C_quoted,
		...docs_json_ts_0_6_1_5_properties_BP_RadialDamageType_Gas_C_quoted[],
	],
};

type FGAmmoTypeProjectile_version_specific = {
	mInitialProjectileSpeedOverride: docs_json_ts_common_types_decimal_string_signed,
	mProjectileMaxSpeedOverride: docs_json_ts_common_types_decimal_string_signed,
	mProjectileHealthOverride: docs_json_ts_common_types_decimal_string_signed,
	mProjectileLifespan: docs_json_ts_common_types_decimal_string_signed,
	mProjectileStickspan: docs_json_ts_common_types_decimal_string_signed,
	mCanTakeDamageBySameProjectileOrChild: docs_json_ts_common_types_bool_string,
	mGravityScaleOverLifespan: docs_json_ts_0_5_2_1_properties_FalloffCurve_EditorCurveData_only,
	mHomingProjectile: docs_json_ts_common_types_bool_string,
	mHomingNeedsValidTarget: docs_json_ts_common_types_bool_string,
	mMaxHomingAccelerationMagnitudeOverride: docs_json_ts_common_types_decimal_string_signed,
	mHomingMagnitudeMultiplierOverLifespan: docs_json_ts_0_5_2_1_properties_FalloffCurve_EditorCurveData_only,
	mHomingMagnitudeMultiplierOverDistanceToTarget: docs_json_ts_0_5_2_1_properties_FalloffCurve_EditorCurveData_only,
	mHomingOverlapSize: docs_json_ts_common_types_decimal_string,
	mHomingAngleLimit: docs_json_ts_common_types_decimal_string,
};

type FGAmmoTypeSpreadshot = docs_json_ts_0_6_1_5_classes_base_overridable_FGAmmoType_base & docs_json_ts_common_classes_FGAmmoTypeSpreadshot & FGAmmoType_base & FGAmmoType_pre_update8 & FGAmmoTypeSpreadshot_version_specific;

type FGAmmoTypeSpreadshot_version_specific = {
	SpreadTrail_Velocity: docs_json_ts_common_types_decimal_string,
	mNumShots: {
		Min: docs_json_ts_common_types_integer_string,
		Max: docs_json_ts_common_types_integer_string,
	},
	mSpreadAngleDegrees: docs_json_ts_common_types_decimal_string,
};

type FGBuildable_base = docs_json_ts_0_6_1_5_classes_base_overridable_FGBuildable_base_version_specific & docs_json_ts_0_3_7_7_classes_base_FGBuildable_base_pre_1_0 & docs_json_ts_0_3_7_7_classes_base_FGBuildable_base_version_specific & docs_json_ts_0_4_2_11_classes_base_FGBuildable_base_version_specific & docs_json_ts_0_5_2_1_classes_base_FGBuildable_base_pre_1_0 & docs_json_ts_0_5_2_1_classes_base_FGBuildable_base_version_specific & FGBuildable_pre_1_2 & FGBuildable_pre_update8 & FGBuildable_version_specific;

type FGBuildable_foundation_mDisableSnapOn = {
	mDisableSnapOn: docs_json_ts_common_types_empty_object | docs_json_ts_0_3_7_7_properties_mDisableSnapOn_front_bottom | docs_json_ts_0_5_2_1_properties_mDisableSnapOn_top | docs_json_ts_0_5_2_1_properties_mDisableSnapOn_bottom | docs_json_ts_0_3_7_7_properties_mDisableSnapOn_top_bottom,
};

type FGBuildable_occupied = docs_json_ts_0_3_7_7_classes_base_FGBuildable_occupied_base & docs_json_ts_common_classes_FGBuildable_occupied & FGBuildable_base;

type FGBuildable_powered = docs_json_ts_0_3_7_7_classes_base_FGBuildable_powered_pre_1_0 & docs_json_ts_0_3_7_7_classes_base_FGBuildable_powered_version_specific & docs_json_ts_0_3_7_7_classes_base_has_mNumCyclesForProductivity & docs_json_ts_0_4_2_11_classes_base_FGBuildable_has_mCachedSkeletalMeshes & docs_json_ts_0_5_2_1_classes_base_FGBuildable_powered_version_specific & FGBuildable_base;

type FGBuildable_powered_base = docs_json_ts_0_4_2_11_classes_base_FGBuildable_has_mCachedSkeletalMeshes & docs_json_ts_0_5_2_1_classes_base_FGBuildable_powered_version_specific & FGBuildable_base;

type FGBuildable_pre_1_2 = {
	mScaleCustomOffset: docs_json_ts_common_types_decimal_string,
	mCustomScaleType: 'ROCSS_Center' | 'ROCSS_Top' | 'ROCSS_Bot',
	mOcclusionShape: 'ROCS_Box' | 'ROCS_Ramp' | 'ROCS_Box_Special' | 'ROCS_CornerRamp',
};

type FGBuildable_pre_update8 = {
	mOcclusionBoxInfo: null | [
		docs_json_ts_0_6_1_5_properties_FGBuildable_mOcclusionBoxInfo_item,
		...docs_json_ts_0_6_1_5_properties_FGBuildable_mOcclusionBoxInfo_item[],
	],
};

type FGBuildable_tiered = docs_json_ts_0_3_7_7_classes_base_FGBuildable_tiered_base & docs_json_ts_common_classes_FGBuildable_tiered & FGBuildable_base;

type FGBuildable_unoccupied_and_untiered = docs_json_ts_common_classes_FGBuildable_unoccupied_and_untiered & FGBuildable_base;

type FGBuildable_version_specific = {
	mAllowPatterning: docs_json_ts_common_types_bool_string,
	mAffectsOcclusion: docs_json_ts_common_types_bool_string,
};

type FGBuildable_with_depth = {
	mDepth: docs_json_ts_common_types_decimal_string,
};

type FGBuildableAttachmentMerger = docs_json_ts_0_3_7_7_classes_base_FGBuildable_powered_pre_1_0 & docs_json_ts_0_3_7_7_classes_base_FGBuildable_powered_version_specific & docs_json_ts_0_3_7_7_classes_base_FGBuildableAttachment_has_mCurrentInventoryIndex & docs_json_ts_0_3_7_7_classes_base_FGBuildableAttachmentMerger_version_specific & docs_json_ts_0_3_7_7_classes_base_has_mNumCyclesForProductivity & docs_json_ts_common_classes_FGBuildableAttachmentMerger & FGBuildable_powered;

type FGBuildableAttachmentSplitter = docs_json_ts_0_5_2_1_classes_base_FGBuildableAttachment_splitter & docs_json_ts_common_classes_FGBuildableAttachmentSplitter & FGBuildable_base;

type FGBuildableBeam = docs_json_ts_0_3_7_7_classes_base_has_mSize & docs_json_ts_0_5_2_1_classes_base_FGBuildableBeam_version_specific & docs_json_ts_common_classes_FGBuildableBeam & FGBuildable_base;

type FGBuildableCircuitSwitch = docs_json_ts_0_4_2_11_classes_base_FGBuildableCircuitSwitch_base & docs_json_ts_common_classes_FGBuildableCircuitSwitch & FGBuildable_base;

type FGBuildableConveyorBelt = docs_json_ts_0_3_7_7_classes_base_FGBuildableConveyorBelt_pre_1_0 & docs_json_ts_0_3_7_7_classes_base_FGBuildableConveyorBelt_pre_update8 & docs_json_ts_0_3_7_7_classes_base_has_mMeshLength & docs_json_ts_0_3_7_7_classes_base_has_mSplineData & docs_json_ts_0_5_2_1_classes_base_FGBuildableConveyorBelt_version_specific & docs_json_ts_common_classes_FGBuildableConveyorBelt & FGBuildable_base;

type FGBuildableConveyorLift = docs_json_ts_0_3_7_7_classes_base_FGBuildableConveyorBelt_pre_1_0 & docs_json_ts_0_3_7_7_classes_base_FGBuildableConveyorBelt_pre_update8 & docs_json_ts_0_3_7_7_classes_base_FGBuildableConveyorLift_base & docs_json_ts_0_5_2_1_classes_base_FGBuildable_mSnappedPassthroughs & docs_json_ts_common_classes_FGBuildableConveyorLift & FGBuildable_base;

type FGBuildableCornerWall = docs_json_ts_common_classes_FGBuildableCornerWall & FGBuildableCornerWall_base & has_mIsInverted;

type FGBuildableCornerWall_base = docs_json_ts_0_5_2_1_classes_base_FGBuildableCornerWall & FGBuildable_base;

type FGBuildableDockingStation = docs_json_ts_0_3_7_7_classes_base_FGBuildable_docking_station_base_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildable_powered_storage_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableDockingStation_with_mFuelTransferSpeed & docs_json_ts_0_5_2_1_classes_base_FGBuildableDockingStation_base & docs_json_ts_common_classes_FGBuildableDockingStation & FGBuildable_powered;

type FGBuildableDoor = FGBuildableDoor_manual | FGBuildableDoor_automated;

type FGBuildableDoor_automated = docs_json_ts_0_5_2_1_classes_base_overridable_FGBuildable_is_wallish & docs_json_ts_0_3_7_7_classes_base_has_mElevation & docs_json_ts_0_3_7_7_classes_base_has_mHeight & docs_json_ts_0_3_7_7_classes_base_has_mWidth & docs_json_ts_0_5_2_1_classes_base_FGBuildableDoor_automated_version_specific & docs_json_ts_0_5_2_1_classes_base_FGBuildableDoor_base & docs_json_ts_common_classes_FGBuildableDoor & FGBuildable_base;

type FGBuildableDoor_manual = docs_json_ts_0_5_2_1_classes_base_overridable_FGBuildable_is_wallish & docs_json_ts_0_3_7_7_classes_base_has_mElevation & docs_json_ts_0_3_7_7_classes_base_has_mHeight & docs_json_ts_0_3_7_7_classes_base_has_mWidth & docs_json_ts_0_5_2_1_classes_base_FGBuildableDoor_base & docs_json_ts_0_5_2_1_classes_base_FGBuildableDoor_manual_version_specific & docs_json_ts_common_classes_FGBuildableDoor & FGBuildable_base;

type FGBuildableDroneStation = docs_json_ts_0_3_7_7_classes_base_FGBuildable_docking_station_base_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildable_docking_station_base_with_mMapText & docs_json_ts_0_3_7_7_classes_base_FGBuildable_powered_storage_base_base & docs_json_ts_0_4_2_11_classes_base_FGBuildable_powered_storage_base & docs_json_ts_0_4_2_11_classes_base_FGBuildableDroneStation_pre_1_0 & docs_json_ts_0_4_2_11_classes_base_FGBuildableDroneStation_version_specific & docs_json_ts_0_4_2_11_overridable_has_mBatteryClasses & docs_json_ts_0_5_2_1_classes_base_FGBuildable_docking_station & docs_json_ts_common_classes_FGBuildableDroneStation & FGBuildable_base;

type FGBuildableFactory_jump_pad = docs_json_ts_0_3_7_7_classes_base_FGBuildableFactory_jump_pad_base_base & docs_json_ts_common_classes_FGBuildableFactory & FGBuildable_powered;

type FGBuildableFactory_landing_pad = docs_json_ts_0_3_7_7_classes_base_FGBuildableFactory_landing_pad_base_base & docs_json_ts_common_classes_FGBuildableFactory & FGBuildable_powered;

type FGBuildableFactory_not_pad = docs_json_ts_common_classes_FGBuildableFactory & FGBuildable_powered;

type FGBuildableFactoryBuilding = docs_json_ts_common_classes_FGBuildableFactoryBuilding & FGBuildable_base;

type FGBuildableFactorySimpleProducer = docs_json_ts_0_3_7_7_classes_base_FGBuildableFactorySimpleProducer_base_base & docs_json_ts_common_classes_FGBuildableFactorySimpleProducer & FGBuildable_powered;

type FGBuildableFloodlight = docs_json_ts_0_4_2_11_classes_base_FGBuildable_light_related_thing_base & docs_json_ts_0_4_2_11_classes_base_FGBuildableFloodlight_version_specific & docs_json_ts_0_4_2_11_classes_base_FGBuildableLightSource_version_specific & docs_json_ts_0_4_2_11_classes_base_has_mHasPower & docs_json_ts_0_4_2_11_classes_base_has_mPowerConsumption & docs_json_ts_0_5_2_1_classes_base_FGBuildableLightSource_base & docs_json_ts_common_classes_FGBuildableFloodlight & FGBuildable_base;

type FGBuildableFoundation = docs_json_ts_0_3_7_7_classes_base_has_mElevation & docs_json_ts_0_3_7_7_classes_base_has_mHeight & docs_json_ts_0_3_7_7_classes_base_has_mWidth & docs_json_ts_0_5_2_1_classes_base_FGBuildable_isFrame & docs_json_ts_common_classes_FGBuildableFoundation & FGBuildable_base & FGBuildable_foundation_mDisableSnapOn & FGBuildable_with_depth & FGBuildableFoundation_version_specific;

type FGBuildableFoundation_version_specific = {
	mDisableAttachmentSnapOn: docs_json_ts_common_types_empty_object | docs_json_ts_0_3_7_7_properties_mDisableSnapOn_top_bottom | docs_json_ts_0_6_1_5_properties_mDisableSnapOn_front_right | docs_json_ts_0_5_2_1_properties_mDisableSnapOn_top | docs_json_ts_0_5_2_1_properties_mDisableSnapOn_bottom,
};

type FGBuildableFrackingActivator = docs_json_ts_0_4_2_11_classes_base_FGBuildableFrackingActivator_base & docs_json_ts_common_classes_FGBuildableFrackingActivator & FGBuildableResourceExtractor_base_version_specific;

type FGBuildableFrackingExtractor = docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_piped & docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_piped_pre_1_0 & docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_timed & docs_json_ts_common_classes_FGBuildableFrackingExtractor & FGBuildableResourceExtractor_base_version_specific;

type FGBuildableGeneratorFuel_biomass = docs_json_ts_0_3_7_7_classes_base_FGBuildableGeneratorFuel_biomass_base_base & docs_json_ts_0_4_2_11_classes_base_FGBuildableGeneratorFuel_base_base & docs_json_ts_0_5_2_1_classes_base_FGBuildableGenerator & docs_json_ts_common_classes_FGBuildableGeneratorFuel & FGBuildable_base;

type FGBuildableGeneratorFuel_coal = docs_json_ts_0_3_7_7_classes_base_FGBuildableGeneratorFuel_coal_base_base & docs_json_ts_0_4_2_11_classes_base_FGBuildableGeneratorFuel_base_base & docs_json_ts_0_5_2_1_classes_base_FGBuildableGenerator & docs_json_ts_common_classes_FGBuildableGeneratorFuel & FGBuildable_base;

type FGBuildableGeneratorFuel_fuel = docs_json_ts_0_3_7_7_classes_base_FGBuildableGeneratorFuel_fuel_base_base & docs_json_ts_0_3_7_7_classes_base_has_mRTPCInterval & docs_json_ts_0_4_2_11_classes_base_FGBuildableGeneratorFuel_base_base & docs_json_ts_0_5_2_1_classes_base_FGBuildableGenerator & docs_json_ts_common_classes_FGBuildableGeneratorFuel & FGBuildable_base;

type FGBuildableGeneratorGeoThermal = docs_json_ts_0_3_7_7_classes_base_FGBuildableGeneratorGeoThermal_base_base & docs_json_ts_0_4_2_11_classes_base_FGBuildableGeneratorGeoThermal_base & docs_json_ts_0_5_2_1_classes_base_FGBuildableGenerator_no_fuel & docs_json_ts_common_classes_FGBuildableGeneratorGeoThermal & FGBuildable_base;

type FGBuildableGeneratorNuclear = docs_json_ts_0_3_7_7_classes_base_FGBuildable_powered_version_specific & docs_json_ts_0_3_7_7_classes_base_FGBuildableGenerator_no_fuel_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableGenerator_no_fuel_base_base_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableGeneratorNuclear_version_specific & docs_json_ts_0_4_2_11_classes_base_FGBuildableGeneratorFuel_base_base & docs_json_ts_0_4_2_11_classes_base_FGBuildableGeneratorNuclear_pre_1_0 & docs_json_ts_0_4_2_11_classes_base_FGBuildableGeneratorNuclear_version_specific & docs_json_ts_0_5_2_1_classes_base_FGBuildableGenerator & docs_json_ts_common_classes_FGBuildableGeneratorNuclear & FGBuildable_base;

type FGBuildableJumppad = docs_json_ts_0_3_7_7_classes_base_FGBuildableJumppad_base_base & docs_json_ts_common_classes_FGBuildableJumppad & FGBuildable_powered;

type FGBuildableLadder = docs_json_ts_0_3_7_7_classes_base_FGBuildableLadder_base & docs_json_ts_0_3_7_7_classes_base_has_mWidth & docs_json_ts_common_classes_FGBuildableLadder & FGBuildable_base;

type FGBuildableLightsControlPanel = docs_json_ts_0_4_2_11_classes_base_FGBuildable_light_related_thing_base & docs_json_ts_0_4_2_11_classes_base_FGBuildableLightsControlPanel_version_specific & docs_json_ts_0_5_2_1_classes_base_FGBuildableLightsControlPanel_version_specific & docs_json_ts_common_classes_FGBuildableLightsControlPanel & FGBuildable_base;

type FGBuildableLightSource_Build_CeilingLight_C = docs_json_ts_0_4_2_11_classes_base_FGBuildable_light_related_thing_base & docs_json_ts_0_4_2_11_classes_base_FGBuildableLightSource_version_specific & docs_json_ts_0_4_2_11_classes_base_has_mHasPower & docs_json_ts_0_4_2_11_classes_base_has_mPowerConsumption & docs_json_ts_0_5_2_1_classes_base_FGBuildableLightSource_base & docs_json_ts_common_classes_FGBuildableLightSource & FGBuildable_base;

type FGBuildableLightSource_Build_StreetLight_C = docs_json_ts_0_4_2_11_classes_base_FGBuildable_light_related_thing_base & docs_json_ts_0_4_2_11_classes_base_FGBuildableLightSource_version_specific & docs_json_ts_0_4_2_11_classes_base_has_mHasPower & docs_json_ts_0_4_2_11_classes_base_has_mPowerConsumption & docs_json_ts_0_5_2_1_classes_base_FGBuildableLightSource_base & docs_json_ts_0_5_2_1_classes_base_FGBuildableLightSource_Build_StreetLight_C_version_specific & docs_json_ts_common_classes_FGBuildableLightSource & FGBuildable_base;

type FGBuildableMAM = docs_json_ts_0_4_2_11_classes_base_FGBuildableMAM_version_specific & docs_json_ts_common_classes_FGBuildableMAM & FGBuildable_base & FGBuildable_occupied;

type FGBuildableManufacturer_Build_AssemblerMk1_C = docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_IsPowered_base & docs_json_ts_common_classes_FGBuildableManufacturer & FGBuildable_powered;

type FGBuildableManufacturer_Build_Blender_C = docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_IsPowered_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_mProductionEffectsRunning_base & docs_json_ts_0_4_2_11_classes_base_FGBuildableManufacturer_base_blender_base & docs_json_ts_common_classes_FGBuildableManufacturer & FGBuildable_powered;

type FGBuildableManufacturer_Build_ConstructorMk1_C = docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_IsPowered_base & docs_json_ts_0_4_2_11_classes_base_FGBuildableManufacturer_base_constructor_base & docs_json_ts_0_5_2_1_classes_base_FGBuildableManufacturer_Build_ConstructorMk1_C_base & docs_json_ts_common_classes_FGBuildableManufacturer & FGBuildable_powered;

type FGBuildableManufacturer_Build_FoundryMk1_C = docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_mProductionEffectsRunning_base & docs_json_ts_0_5_2_1_classes_base_FGBuildableManufacturer_Build_FoundryMk1_C_base & docs_json_ts_common_classes_FGBuildableManufacturer & FGBuildable_powered;

type FGBuildableManufacturer_Build_HadronCollider_C = docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_IsPowered_base & docs_json_ts_0_4_2_11_classes_base_FGBuildableManufacturer_Build_HadronCollider_C_base & docs_json_ts_0_4_2_11_classes_base_FGBuildableManufacturerVariablePower & docs_json_ts_common_classes_FGBuildableManufacturerVariablePower & FGBuildable_powered;

type FGBuildableManufacturer_Build_ManufacturerMk1_C = docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_base & docs_json_ts_0_4_2_11_classes_base_FGBuildable_mStopped_audio_stuff & docs_json_ts_common_classes_FGBuildableManufacturer & FGBuildable_powered;

type FGBuildableManufacturer_Build_OilRefinery_C = docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_IsPowered_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_mProductionEffectsRunning_base & docs_json_ts_common_classes_FGBuildableManufacturer & FGBuildable_powered;

type FGBuildableManufacturer_Build_Packager_C = docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_IsPowered_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_mProductionEffectsRunning_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_packager_base & docs_json_ts_common_classes_FGBuildableManufacturer & FGBuildable_powered;

type FGBuildableManufacturer_Build_SmelterMk1_C = docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_Build_SmelterMk1_C_base & docs_json_ts_0_5_2_1_classes_base_FGBuildableManufacturer_Build_SmelterMk1_C_base & docs_json_ts_common_classes_FGBuildableManufacturer & FGBuildable_powered & FGBuildableManufacturer_Build_SmelterMk1_C_base;

type FGBuildableManufacturer_Build_SmelterMk1_C_base = docs_json_ts_0_5_2_1_classes_base_FGBuildableManufacturer_Build_SmelterMk1_C_base & {
	mCachedCurrentPotential: docs_json_ts_common_types_integer_string,
};

type FGBuildablePassthrough = docs_json_ts_0_5_2_1_classes_base_FGBuildablePassthrough_base & docs_json_ts_0_5_2_1_classes_base_FGBuildablePassthrough_pre_update8 & docs_json_ts_common_classes_FGBuildablePassthrough & FGBuildable_base;

type FGBuildablePillar = docs_json_ts_0_5_2_1_classes_base_has_mIsSupport & docs_json_ts_0_5_2_1_classes_base_has_mSize_vector & docs_json_ts_common_classes_FGBuildablePillar & FGBuildable_base;

type FGBuildablePipeHyper = docs_json_ts_0_5_2_1_classes_base_FGBuildablePipeHyper_version_specific & docs_json_ts_0_5_2_1_classes_base_has_mSplineData & docs_json_ts_common_classes_FGBuildablePipeHyper & FGBuildable_base;

type FGBuildablePipeline = docs_json_ts_0_3_7_7_classes_base_FGBuildablePipeline_base_root & docs_json_ts_0_5_2_1_classes_base_FGBuildablePipeline_base_spline & docs_json_ts_common_classes_FGBuildablePipeline & FGBuildable_base & FGBuildablePipeline_version_specific;

type FGBuildablePipeline_version_specific = {
	mLastContentForSound: docs_json_ts_common_types_decimal_string,
	mLastFlowForSound: docs_json_ts_common_types_decimal_string,
	mUpdateSoundsHandle: docs_json_ts_common_types_empty_object,
};

type FGBuildablePipelineJunction = docs_json_ts_0_4_2_11_classes_base_FGBuildablePipelineJunction_base_base & docs_json_ts_common_classes_FGBuildablePipelineJunction & FGBuildable_powered;

type FGBuildablePipelinePump_pump = docs_json_ts_0_3_7_7_classes_base_FGBuildable_powered_pre_1_0 & docs_json_ts_0_3_7_7_classes_base_FGBuildable_powered_version_specific & docs_json_ts_0_3_7_7_classes_base_FGBuildablePipeline_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildablePipeline_base_no_indicator_base & docs_json_ts_0_3_7_7_classes_base_FGBuildablePipelinePump_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildablePipelinePump_powered_version_specific & docs_json_ts_0_3_7_7_classes_base_FGBuildablePipelinePump_pump_version_specific & docs_json_ts_0_3_7_7_classes_base_has_mNumCyclesForProductivity & docs_json_ts_common_classes_FGBuildablePipelinePump & FGBuildable_powered;

type FGBuildablePipelinePump_valve = docs_json_ts_0_3_7_7_classes_base_FGBuildablePipelinePump_base_base & docs_json_ts_common_classes_FGBuildablePipelinePump & FGBuildable_powered;

type FGBuildablePipelineSupport = docs_json_ts_0_3_7_7_classes_base_FGBuildable_with_mLength & docs_json_ts_0_3_7_7_classes_base_FGBuildablePipelineSupport_base & docs_json_ts_0_3_7_7_classes_base_has_mCanStack & docs_json_ts_0_3_7_7_classes_base_has_mStackHeight & docs_json_ts_0_3_7_7_classes_base_has_mUseStaticHeight & docs_json_ts_common_classes_FGBuildablePipelineSupport & FGBuildable_base;

type FGBuildablePipeReservoir = docs_json_ts_0_3_7_7_classes_base_FGBuildablePipeReservoir_base_base & docs_json_ts_common_classes_FGBuildablePipeReservoir & FGBuildable_powered;

type FGBuildablePole = docs_json_ts_0_3_7_7_classes_base_has_mCanStack & docs_json_ts_0_3_7_7_classes_base_has_mHeight & docs_json_ts_0_3_7_7_classes_base_has_mStackHeight & docs_json_ts_0_3_7_7_classes_base_has_mUseStaticHeight & docs_json_ts_common_classes_FGBuildablePole & FGBuildable_base;

type FGBuildablePowerPole = docs_json_ts_0_3_7_7_classes_base_FGBuildablePowerPole_base & docs_json_ts_0_4_2_11_classes_base_has_mHasPower & docs_json_ts_common_classes_FGBuildablePowerPole & FGBuildable_base;

type FGBuildablePowerStorage = docs_json_ts_0_4_2_11_classes_base_FGBuildablePowerStorage_base & docs_json_ts_common_classes_FGBuildablePowerStorage & FGBuildable_powered;

type FGBuildableRadarTower = docs_json_ts_0_6_1_5_classes_base_overridable_FGBuildableRadarTower_version_specific & docs_json_ts_common_classes_FGBuildableRadarTower & FGBuildable_powered & FGBuildableRadarTower_version_specific;

type FGBuildableRadarTower_version_specific = {
	mMapText: Exclude<string, ''>,
	mRevealRadius: docs_json_ts_common_types_decimal_string,
};

type FGBuildableRailroadSignal_base = docs_json_ts_0_5_2_1_classes_base_FGBuildableRailroadSignal_base & FGBuildable_base;

type FGBuildableRailroadSignal_block = docs_json_ts_0_5_2_1_classes_base_FGBuildableRailroadSignal_block_version_specific & docs_json_ts_common_classes_FGBuildableRailroadSignal_block & FGBuildable_base & FGBuildableRailroadSignal_base;

type FGBuildableRailroadSignal_path = docs_json_ts_common_classes_FGBuildableRailroadSignal_path & FGBuildableRailroadSignal_base;

type FGBuildableRailroadStation = docs_json_ts_0_3_7_7_classes_base_FGBuildableRailroadStation_base_base & docs_json_ts_0_5_2_1_classes_base_FGBuildableRailroadStation_base & docs_json_ts_0_5_2_1_classes_base_FGBuildableTrainPlatform_base & docs_json_ts_0_5_2_1_classes_base_FGBuildableTrainPlatform_non_empty & docs_json_ts_common_classes_FGBuildableRailroadStation & FGBuildable_powered;

type FGBuildableRailroadTrack = docs_json_ts_0_3_7_7_classes_base_has_mMeshLength & docs_json_ts_0_5_2_1_classes_base_FGBuildableRailroadTrack_base & docs_json_ts_0_5_2_1_classes_base_FGBuildableRailroadTrack_base_version_specific & docs_json_ts_common_classes_FGBuildableRailroadTrack & FGBuildable_base;

type FGBuildableRamp = docs_json_ts_0_3_7_7_classes_base_has_mElevation & docs_json_ts_0_3_7_7_classes_base_has_mHeight & docs_json_ts_0_3_7_7_classes_base_has_mWidth & docs_json_ts_0_5_2_1_classes_base_FGBuildable_isFrame & docs_json_ts_0_5_2_1_classes_base_FGBuildableRamp_base & docs_json_ts_common_classes_FGBuildableRamp & FGBuildable_base & FGBuildable_foundation_mDisableSnapOn & FGBuildable_with_depth & FGBuildableFoundation_version_specific;

type FGBuildableRamp_version_specific = {
	mDisableAttachmentSnapOn: docs_json_ts_common_types_empty_object | docs_json_ts_0_5_2_1_properties_mDisableSnapOn_top | docs_json_ts_0_3_7_7_properties_mDisableSnapOn_top_bottom | docs_json_ts_0_5_2_1_properties_mDisableSnapOn_bottom,
};

type FGBuildableResourceExtractor_base = FGBuildableResourceExtractor_base_base & FGBuildableResourceExtractor_base_version_specific;

type FGBuildableResourceExtractor_base_base = docs_json_ts_0_3_7_7_classes_base_FGBuildable_powered_base_resources_base & docs_json_ts_0_3_7_7_classes_base_overridable_FGBuildableResourceExtractor_only_allow_certain_resources & docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_piped & docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_piped_pre_1_0 & FGBuildable_powered;

type FGBuildableResourceExtractor_base_untimed = docs_json_ts_0_3_7_7_classes_base_overridable_FGBuildableResourceExtractor_only_allow_certain_resources & FGBuildable_powered;

type FGBuildableResourceExtractor_base_version_specific = FGBuildableResourceExtractor_base_untimed & FGBuildableResourceExtractor_base_version_specific_base;

type FGBuildableResourceExtractor_base_version_specific_base = {
	mTryFindMissingResource: docs_json_ts_common_types_bool_string,
	mAllowedResourceForms: docs_json_ts_0_6_1_5_properties_mAllowedResourceForms,
};

type FGBuildableResourceExtractor_miner_mk1 = docs_json_ts_0_4_2_11_classes_base_FGBuildableResourceExtractor_miner_mk1_base_base & docs_json_ts_common_classes_FGBuildableResourceExtractor & FGBuildableResourceExtractor_base;

type FGBuildableResourceExtractor_miner_mk2 = docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_miner_mk2_base_base & docs_json_ts_common_classes_FGBuildableResourceExtractor & FGBuildable_powered & FGBuildableResourceExtractor_base;

type FGBuildableResourceExtractor_miner_mk3 = docs_json_ts_0_3_7_7_classes_base_FGBuildable_powered_base_resources_base & docs_json_ts_0_3_7_7_classes_base_FGBuildable_powered_pre_1_0 & docs_json_ts_0_3_7_7_classes_base_FGBuildable_powered_version_specific & docs_json_ts_0_3_7_7_classes_base_overridable_FGBuildableResourceExtractor_miner_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_miner_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_miner_mk3_version_specific & docs_json_ts_0_3_7_7_classes_base_overridable_FGBuildableResourceExtractor_only_allow_certain_resources & docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_piped & docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_piped_pre_1_0 & docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_timed & docs_json_ts_0_3_7_7_classes_base_has_mNumCyclesForProductivity & docs_json_ts_common_classes_FGBuildableResourceExtractor & FGBuildable_powered & FGBuildableResourceExtractor_base;

type FGBuildableResourceExtractor_oil = docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_oil_base_base & docs_json_ts_common_classes_FGBuildableResourceExtractor & FGBuildable_powered & FGBuildableResourceExtractor_base;

type FGBuildableResourceExtractor_water = docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_water_base_base & docs_json_ts_0_4_2_11_classes_base_FGBuildableResourceExtractor_water_base & docs_json_ts_common_classes_FGBuildableResourceExtractor & FGBuildable_powered & FGBuildableResourceExtractor_base;

type FGBuildableResourceSink = docs_json_ts_0_4_2_11_classes_base_FGBuildableResourceSink_base & docs_json_ts_common_classes_FGBuildableResourceSink & FGBuildable_powered;

type FGBuildableResourceSinkShop = docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceSinkShop_base_base & docs_json_ts_common_classes_FGBuildableResourceSinkShop & FGBuildable_powered;

type FGBuildableSnowDispenser = docs_json_ts_common_classes_FGBuildableSnowDispenser & FGBuildable_base;

type FGBuildableSpaceElevator = docs_json_ts_common_classes_FGBuildableSpaceElevator & FGBuildable_powered;

type FGBuildableSplitterSmart = docs_json_ts_0_3_7_7_classes_base_FGBuildable_powered_pre_1_0 & docs_json_ts_0_3_7_7_classes_base_FGBuildable_powered_version_specific & docs_json_ts_0_3_7_7_classes_base_FGBuildableAttachment_has_mCurrentInventoryIndex & docs_json_ts_0_3_7_7_classes_base_FGBuildableAttachment_splitter_base_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableSplitterSmart_version_specific & docs_json_ts_0_3_7_7_classes_base_has_mNumCyclesForProductivity & docs_json_ts_common_classes_FGBuildableSplitterSmart & FGBuildable_powered;

type FGBuildableStair = docs_json_ts_0_3_7_7_classes_base_has_mHeight & docs_json_ts_0_3_7_7_classes_base_has_mSize & docs_json_ts_0_5_2_1_classes_base_FGBuildableStair_has_mStairDirection & docs_json_ts_common_classes_FGBuildableStair & FGBuildable_base;

type FGBuildableStorage = docs_json_ts_0_3_7_7_classes_base_FGBuildableStorage_base_base & docs_json_ts_common_classes_FGBuildableStorage & FGBuildable_powered;

type FGBuildableTradingPost = docs_json_ts_0_3_7_7_classes_base_FGBuildable_powered_pre_1_0 & docs_json_ts_0_3_7_7_classes_base_FGBuildable_powered_version_specific & docs_json_ts_0_3_7_7_classes_base_FGBuildableTradingPost_pre_1_0 & docs_json_ts_0_3_7_7_classes_base_FGBuildableTradingPost_pre_update8 & docs_json_ts_0_3_7_7_classes_base_FGBuildableTradingPost_version_specific & docs_json_ts_0_3_7_7_classes_base_has_mNumCyclesForProductivity & docs_json_ts_0_4_2_11_classes_base_FGBuildableTradingPost_base & docs_json_ts_0_4_2_11_classes_base_FGBuildableTradingPost_base_pre_1_0 & docs_json_ts_0_4_2_11_classes_base_FGBuildableTradingPost_base_version_specific & docs_json_ts_0_5_2_1_classes_base_FGBuildableTradingPost_version_specific & docs_json_ts_common_classes_FGBuildableTradingPost & FGBuildable_powered;

type FGBuildableTrainPlatformCargo = docs_json_ts_0_3_7_7_classes_base_FGBuildableTrainPlatform_with_storage_base_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableTrainPlatformCargo_pre_update8 & docs_json_ts_0_3_7_7_classes_base_FGBuildableTrainPlatformCargo_version_specific & docs_json_ts_0_5_2_1_classes_base_FGBuildableTrainPlatform_with_storage & docs_json_ts_0_5_2_1_classes_base_FGBuildableTrainPlatformCargo_version_specific & docs_json_ts_common_classes_FGBuildableTrainPlatformCargo & FGBuildable_base & FGBuildableTrainPlatformCargo_version_specific;

type FGBuildableTrainPlatformCargo_version_specific = {
	mHasAnyRelevantStacksToMove: docs_json_ts_common_types_bool_string,
	mAllowDepartureNoValidItemsToTransfer: docs_json_ts_common_types_bool_string,
};

type FGBuildableTrainPlatformEmpty = docs_json_ts_0_5_2_1_classes_base_FGBuildableTrainPlatform_base & docs_json_ts_common_classes_FGBuildableTrainPlatformEmpty & FGBuildable_powered;

type FGBuildableWalkway = docs_json_ts_0_3_7_7_classes_base_has_mDisableSnapOn & docs_json_ts_0_3_7_7_classes_base_has_mElevation & docs_json_ts_0_3_7_7_classes_base_has_mSize & docs_json_ts_common_classes_FGBuildableWalkway & FGBuildable_base;

type FGBuildableWall = docs_json_ts_0_5_2_1_classes_base_overridable_FGBuildable_is_wallish & docs_json_ts_0_3_7_7_classes_base_has_mElevation & docs_json_ts_0_3_7_7_classes_base_has_mHeight & docs_json_ts_0_3_7_7_classes_base_has_mWidth & docs_json_ts_common_classes_FGBuildableWall & FGBuildable_base;

type FGBuildableWidgetSign = docs_json_ts_0_5_2_1_classes_base_FGBuildableWidgetSign_base & docs_json_ts_common_classes_FGBuildableWidgetSign & FGBuildable_base;

type FGBuildableWire = docs_json_ts_0_3_7_7_classes_base_FGBuildableWire_base & docs_json_ts_common_classes_FGBuildableWire & FGBuildable_base;

type FGChainsaw = docs_json_ts_0_3_7_7_classes_base_FGChainsaw_pre_1_0 & docs_json_ts_0_3_7_7_classes_base_FGChainsaw_pre_update8 & docs_json_ts_0_3_7_7_classes_base_FGChainsaw_version_specific & docs_json_ts_0_3_7_7_classes_base_FGEquipment & docs_json_ts_0_3_7_7_classes_base_FGEquipment_has_mPlayingSound & docs_json_ts_common_classes_FGChainsaw & FGChainsaw_pre_1_0 & FGChainsaw_pre_update8 & FGChainsaw_version_specific & FGEquipment;

type FGChainsaw_pre_1_0 = {
	mCurrentAkID: docs_json_ts_common_types_integer_string,
};

type FGChainsaw_pre_update8 = {
	mAkEventsArray: docs_json_ts_0_6_1_5_properties_DocsDotJson_AkAudioEvent_quoted_list,
	mEventIndexSFX: docs_json_ts_common_types_integer_string,
};

type FGChainsaw_version_specific = {
	mCurrentOutputDataSFX: docs_json_ts_common_types_decimal_string,
};

type FGConsumableEquipment = docs_json_ts_0_3_7_7_classes_base_FGConsumableEquipment_pre_update8 & docs_json_ts_0_3_7_7_classes_base_FGConsumableEquipment_version_specific & docs_json_ts_0_3_7_7_classes_base_FGEquipment & docs_json_ts_0_3_7_7_classes_base_FGEquipment_base & docs_json_ts_0_4_2_11_classes_base_FGConsumableEquipment_version_specific & docs_json_ts_common_classes_FGConsumableEquipment & FGEquipment;

type FGConveyorPoleStackable = docs_json_ts_0_3_7_7_classes_base_has_mCanStack & docs_json_ts_0_3_7_7_classes_base_has_mHeight & docs_json_ts_0_3_7_7_classes_base_has_mStackHeight & docs_json_ts_0_3_7_7_classes_base_has_mUseStaticHeight & docs_json_ts_common_classes_FGBuildablePole & docs_json_ts_common_classes_FGConveyorPoleStackable & FGBuildable_base;

type FGDescriptor = docs_json_ts_0_4_2_11_classes_base_FGDescriptor_base & {
	mPersistentBigIcon: docs_json_ts_0_4_2_11_properties_Texture2D | 'None',
	mSmallIcon: docs_json_ts_0_4_2_11_properties_Texture2D | 'None',
};

type FGEquipment = docs_json_ts_0_4_2_11_classes_base_FGEquipment_base & FGEquipment_pre_1_0 & FGEquipment_version_specific;

type FGEquipment_noisy = FGEquipment & FGEquipment_noisy_version_specific;

type FGEquipment_noisy_version_specific = {
	mActiveNoiseFrequency: docs_json_ts_common_types_decimal_string,
};

type FGEquipment_pre_1_0 = {
	mOnlyVisibleToOwner: docs_json_ts_common_types_bool_string,
};

type FGEquipment_version_specific = {
	mReceivedDamageModifiers: '',
	mEquipmentSlot: 'ES_ARMS' | 'ES_HEAD' | 'ES_BACK' | 'ES_BODY' | 'ES_LEGS',
};

type FGEquipmentDescriptor = docs_json_ts_0_6_1_5_classes_base_overridable_FGItemDescriptor_base & docs_json_ts_0_4_2_11_classes_base_FGDescriptor_sinkable & docs_json_ts_common_classes_FGEquipmentDescriptor;

type FGEquipmentStunSpear_base = FGEquipment & FGEquipmentStunSpear_base_mDamageTypes & FGEquipmentStunSpear_base_version_specific;

type FGEquipmentStunSpear_base_mDamageTypes = {
	mDamageTypes: docs_json_ts_0_6_1_5_properties_DamageTypes,
};

type FGEquipmentStunSpear_base_version_specific = {
	mAttackSweepRadius: docs_json_ts_common_types_decimal_string,
};

type FGEquipmentStunSpear_xenobasher = docs_json_ts_0_3_7_7_classes_base_FGEquipmentStunSpear_xenobasher_base & docs_json_ts_common_classes_FGEquipmentStunSpear & FGEquipmentStunSpear_base;

type FGEquipmentStunSpear_xenozapper = docs_json_ts_0_3_7_7_classes_base_FGEquipmentStunSpear_xenozapper_base & docs_json_ts_common_classes_FGEquipmentStunSpear & FGEquipmentStunSpear_base;

type FGEquipmentZipline = docs_json_ts_0_4_2_11_classes_base_FGEquipmentZipline_pre_1_0 & docs_json_ts_0_4_2_11_classes_base_FGEquipmentZipline_version_specific & docs_json_ts_common_classes_FGEquipmentZipline & FGEquipment_noisy;

type FGGasMask = docs_json_ts_0_3_7_7_classes_base_FGEquipment_has_mFilterDuration & docs_json_ts_0_3_7_7_classes_base_FGEquipment_has_effect_timer & docs_json_ts_0_3_7_7_classes_base_FGEquipment_negates_damage & docs_json_ts_0_3_7_7_classes_base_FGGasMask_base & docs_json_ts_common_classes_FGGasMask & FGEquipment & FGGasMask_version_specific;

type FGGasMask_version_specific = {
	mIsInPoisonArea: docs_json_ts_common_types_bool_string,
};

type FGGolfCartDispenser = docs_json_ts_0_5_2_1_classes_base_FGGolfCartDispenser & docs_json_ts_common_classes_FGGolfCartDispenser & FGEquipment;

type FGHoverPack = docs_json_ts_0_4_2_11_classes_base_FGHoverPack_pre_1_0 & docs_json_ts_0_4_2_11_classes_base_FGHoverPack_version_specific & docs_json_ts_common_classes_FGHoverPack & FGEquipment_noisy;

type FGItemDescriptor = docs_json_ts_0_6_1_5_classes_base_overridable_FGItemDescriptor_base & docs_json_ts_0_4_2_11_classes_base_FGDescriptor_sinkable & docs_json_ts_common_classes_FGItemDescriptor;

type FGItemDescriptor_pre_1_0 = {
	mClassToScanFor: 'None' | `/Game/FactoryGame/${'Resource/Environment/' | 'World/Benefit/'}${string}${'/BP_'}${Exclude<string, ''>}${'.BP_'}${Exclude<string, ''>}`,
	mDescriptorStatBars: null | [
		docs_json_ts_0_6_1_5_properties_FGItemDescriptor_version_specific_mDescriptorStatBars_item,
		...docs_json_ts_0_6_1_5_properties_FGItemDescriptor_version_specific_mDescriptorStatBars_item[],
	],
};

type FGItemDescriptor_version_specific = {
	mCrosshairMaterial: 'None' | `/Game/FactoryGame/Interface/UI/Material/Crosshairs/MI_UI_Crosshair_${Exclude<string, ''>}${'.MI_UI_Crosshair_'}${Exclude<string, ''>}`,
	mScannableType: 'RTWOT_Default' | 'RTWOT_WeakSignal' | 'RTWOT_Flora',
	mShouldOverrideScannerDisplayText: docs_json_ts_common_types_bool_string,
	mScannerDisplayText: string,
	mScannerLightColor: docs_json_ts_common_types_BGRA,
	mMenuPriority: docs_json_ts_common_types_decimal_string,
};

type FGItemDescriptorBiomass = docs_json_ts_0_6_1_5_classes_base_overridable_FGItemDescriptor_base & docs_json_ts_0_4_2_11_classes_base_FGDescriptor_sinkable & docs_json_ts_common_classes_FGItemDescriptorBiomass;

type FGJetPack = docs_json_ts_0_3_7_7_classes_base_FGJetPack_pre_1_0 & docs_json_ts_0_3_7_7_classes_base_FGJetPack_pre_update7 & docs_json_ts_0_3_7_7_classes_base_FGJetPack_version_specific & docs_json_ts_0_3_7_7_classes_base_has_mRTPCInterval & docs_json_ts_common_classes_FGJetPack & FGEquipment_noisy & FGJetPack_version_specific;

type FGJetPack_version_specific = {
	mJumpTimeStamp: docs_json_ts_common_types_decimal_string_signed,
};

type FGJumpingStilts = docs_json_ts_0_3_7_7_classes_base_FGJumpingStilts_base & docs_json_ts_common_classes_FGJumpingStilts & FGEquipment & FGJumpingStilts_version_specific;

type FGJumpingStilts_version_specific = {
	mEquipmentSlot: 'ES_LEGS',
};

type FGNobeliskDetonator = docs_json_ts_0_5_2_1_classes_base_overridable_FGWeapon_version_specific & docs_json_ts_0_3_7_7_classes_base_FGEquipment_base & docs_json_ts_0_3_7_7_classes_base_FGNobeliskDetonator_base & docs_json_ts_0_3_7_7_classes_base_FGWeaponProjectile_thrown_base_base & docs_json_ts_0_3_7_7_classes_base_FGWeaponProjectile_thrown_base_pre_1_0 & docs_json_ts_0_4_2_11_classes_base_FGWeaponProjectile_has_mBlockSprintWhenFiring & docs_json_ts_0_5_2_1_classes_base_FGNobeliskDetonator_version_specific & docs_json_ts_0_5_2_1_classes_base_FGWeapon_pre_1_1 & docs_json_ts_0_5_2_1_classes_base_FGWeapon_version_specific & docs_json_ts_common_classes_FGNobeliskDetonator & FGEquipment & FGWeapon_base;

type FGObjectScanner = docs_json_ts_0_6_1_5_classes_base_overridable_FGObjectScanner_version_specific & docs_json_ts_0_3_7_7_classes_base_FGEquipment_has_mPlayingSound & docs_json_ts_0_3_7_7_classes_base_FGObjectScanner_pre_1_0 & docs_json_ts_0_3_7_7_classes_base_FGObjectScanner_pre_update8 & docs_json_ts_0_3_7_7_classes_base_FGObjectScanner_version_specific & docs_json_ts_common_classes_FGObjectScanner & FGEquipment & FGObjectScanner_version_specific;

type FGObjectScanner_version_specific = {
	mObjectDetails: [
		docs_json_ts_0_6_1_5_properties_FGObjectScanner_mObjectDetails_item,
		...docs_json_ts_0_6_1_5_properties_FGObjectScanner_mObjectDetails_item[],
	],
};

type FGParachute = docs_json_ts_0_3_7_7_classes_base_FGParachute_has_mIsDeployed & docs_json_ts_0_3_7_7_classes_base_FGParachute_has_mTerminalVelocityZ & docs_json_ts_common_classes_FGParachute & FGEquipment;

type FGPipeHyperStart = docs_json_ts_0_3_7_7_classes_base_FGBuildable_powered_pre_1_0 & docs_json_ts_0_3_7_7_classes_base_FGBuildable_powered_version_specific & docs_json_ts_0_3_7_7_classes_base_FGBuildable_with_mLength & docs_json_ts_0_3_7_7_classes_base_FGPipeHyperStart_base_base_base & docs_json_ts_0_3_7_7_classes_base_FGPipeHyperStart_pre_update8 & docs_json_ts_0_3_7_7_classes_base_has_mCanStack & docs_json_ts_0_3_7_7_classes_base_has_mNumCyclesForProductivity & docs_json_ts_0_3_7_7_classes_base_has_mStackHeight & docs_json_ts_0_3_7_7_classes_base_has_mUseStaticHeight & docs_json_ts_common_classes_FGPipeHyperStart & FGBuildable_base & FGBuildable_powered;

type FGPortableMinerDispenser = docs_json_ts_0_3_7_7_classes_base_FGEquipment_dispenser & docs_json_ts_0_3_7_7_classes_base_FGPortableMinerDispenser_version_specific & docs_json_ts_common_classes_FGPortableMinerDispenser & FGEquipment;

type FGRecipe_version_specific = {
	mProducedIn: docs_json_ts_0_6_1_5_properties_mProducedIn,
};

type FGResourceDescriptor = docs_json_ts_0_6_1_5_classes_base_overridable_FGItemDescriptor_base & docs_json_ts_0_3_7_7_classes_base_FGResourceDescriptor_base & docs_json_ts_0_4_2_11_classes_base_FGDescriptor_sinkable & docs_json_ts_common_classes_FGResourceDescriptor;

type FGSchematic = docs_json_ts_0_3_7_7_classes_base_overridable_FGSchematic_version_specific & docs_json_ts_0_4_2_11_classes_base_overridable_FGSchematic_has_mSchematicDependencies & docs_json_ts_0_4_2_11_classes_base_overridable_FGSchematic_has_mSchematicIcon & docs_json_ts_0_5_2_1_classes_base_overridable_FGSchematic_version_specific & docs_json_ts_0_6_1_5_classes_base_overridable_FGSchematic_version_specific_mUnlocks & docs_json_ts_0_3_7_7_classes_base_FGSchematic_pre_1_0 & docs_json_ts_0_4_2_11_classes_base_FGSchematic_has_mMenuPriority & docs_json_ts_0_4_2_11_classes_base_FGSchematic_has_mTechTier & docs_json_ts_common_classes_FGSchematic & docs_json_ts_common_classes_base_isDescribed & FGSchematic_pre_update8 & FGSchematic_version_specific;

type FGSchematic_pre_update8 = {
	mCost: null | docs_json_ts_0_3_7_7_overridable_ItemClass_Amount_list | docs_json_ts_0_6_1_5_overridable_ItemClass_list,
};

type FGSchematic_version_specific = {
	mHiddenUntilDependenciesMet: docs_json_ts_common_types_bool_string,
};

type FGSchematic_with_described_unlocks = docs_json_ts_0_3_7_7_classes_base_overridable_FGSchematic_version_specific & docs_json_ts_0_4_2_11_classes_base_overridable_FGSchematic_has_mSchematicDependencies & docs_json_ts_0_4_2_11_classes_base_overridable_FGSchematic_has_mSchematicIcon & docs_json_ts_0_5_2_1_classes_base_overridable_FGSchematic_version_specific & docs_json_ts_0_6_1_5_classes_base_overridable_FGSchematic_version_specific_mUnlocks & docs_json_ts_0_3_7_7_classes_base_FGSchematic_pre_1_0 & docs_json_ts_0_4_2_11_classes_base_FGSchematic_has_mMenuPriority & docs_json_ts_0_4_2_11_classes_base_FGSchematic_has_mTechTier & docs_json_ts_0_5_2_1_classes_base_FGSchematic_with_described_unlocks_version_specific & docs_json_ts_common_classes_FGSchematic & docs_json_ts_common_classes_base_isDescribed & FGSchematic_pre_update8 & FGSchematic_version_specific;

type FGSuitBase = docs_json_ts_0_3_7_7_classes_base_FGEquipment_has_mFilterDuration & docs_json_ts_0_3_7_7_classes_base_FGEquipment_has_effect_timer & docs_json_ts_0_3_7_7_classes_base_FGEquipment_negates_damage & docs_json_ts_0_3_7_7_classes_base_FGSuitBase_base & docs_json_ts_0_3_7_7_classes_base_overridable_FGSuitBase_pre_1_0 & docs_json_ts_common_classes_FGSuitBase & FGEquipment & FGSuitBase_version_specific;

type FGSuitBase_version_specific = {
	mEquipmentSlot: 'ES_BODY',
	mIsBurningFuel: docs_json_ts_common_types_bool_string,
};

type FGVehicleDescriptor_Desc_CyberWagon_C = docs_json_ts_0_4_2_11_classes_base_FGVehicleDescriptor_fueled_with_inventory_base & docs_json_ts_common_classes_FGVehicleDescriptor;

type FGVehicleDescriptor_Desc_DroneTransport_C = docs_json_ts_0_4_2_11_classes_base_FGDescriptor & docs_json_ts_0_4_2_11_classes_base_FGDescriptor_base & docs_json_ts_0_4_2_11_classes_base_has_mInventorySize & docs_json_ts_common_classes_FGVehicleDescriptor;

type FGVehicleDescriptor_Desc_Explorer_C = docs_json_ts_0_4_2_11_classes_base_FGVehicleDescriptor_fueled_with_inventory_base & docs_json_ts_common_classes_FGVehicleDescriptor;

type FGVehicleDescriptor_Desc_FreightWagon_C = docs_json_ts_0_4_2_11_classes_base_FGDescriptor & docs_json_ts_0_4_2_11_classes_base_FGDescriptor_base & docs_json_ts_0_4_2_11_classes_base_has_mInventorySize & docs_json_ts_common_classes_FGVehicleDescriptor;

type FGVehicleDescriptor_Desc_Locomotive_C = docs_json_ts_0_4_2_11_classes_base_FGDescriptor & docs_json_ts_0_4_2_11_classes_base_FGVehicleDescriptor_powered_base & docs_json_ts_common_classes_FGVehicleDescriptor;

type FGVehicleDescriptor_Desc_Tractor_C = docs_json_ts_0_4_2_11_classes_base_FGVehicleDescriptor_fueled_with_inventory_base & docs_json_ts_common_classes_FGVehicleDescriptor;

type FGVehicleDescriptor_Desc_Truck_C = docs_json_ts_0_4_2_11_classes_base_FGVehicleDescriptor_fueled_with_inventory_base & docs_json_ts_common_classes_FGVehicleDescriptor;

type FGWeapon_base = {
	mAttachMagazineToPlayer: docs_json_ts_common_types_bool_string,
	mMuzzleSocketName: 'muzzleSocket' | 'MuzzleSocket' | 'None',
	mCurrentMagazineBoneName: 'CurrentMagazine' | 'hand_rSocket',
	mEjectMagazineBoneName: 'EjectMagazine' | 'hand_rSocket',
	mDispersionOnNoMagazine: docs_json_ts_common_types_decimal_string,
	mReloadTime: docs_json_ts_common_types_decimal_string,
};

type FGWeapon_Equip_RebarGun_Projectile_C = docs_json_ts_0_5_2_1_classes_base_overridable_FGWeapon_version_specific & docs_json_ts_0_3_7_7_classes_base_FGEquipment_base & docs_json_ts_0_3_7_7_classes_base_FGEquipment_has_mRandomStingerAnim & docs_json_ts_0_3_7_7_classes_base_FGWeaponProjectile_has_mAttachSocket & docs_json_ts_0_3_7_7_classes_base_FGWeaponProjectileFire_has_mRandomReloadAnim & docs_json_ts_0_4_2_11_classes_base_FGWeaponProjectile_has_mBlockSprintWhenFiring & docs_json_ts_0_4_2_11_classes_base_FGWeaponProjectileFire_has_mMuteDryFire & docs_json_ts_0_5_2_1_classes_base_FGWeapon_pre_1_1 & docs_json_ts_0_5_2_1_classes_base_FGWeapon_version_specific & docs_json_ts_common_classes_FGWeapon_Equip_RebarGun_Projectile_C & FGEquipment & FGWeapon_base & FGWeapon_Equip_RebarGun_Projectile_C_version_specific;

type FGWeapon_Equip_RebarGun_Projectile_C_version_specific = {
	mRebarGunStingerID: docs_json_ts_common_types_integer_string,
	mRebarGunEquipID: docs_json_ts_common_types_integer_string,
};

type FGWeapon_Equip_Rifle_C = docs_json_ts_0_5_2_1_classes_base_overridable_FGWeapon_version_specific & docs_json_ts_0_3_7_7_classes_base_FGEquipment_base & docs_json_ts_0_3_7_7_classes_base_FGWeaponInstantFire_base_base_base & docs_json_ts_0_3_7_7_classes_base_FGWeaponProjectile_has_mAttachSocket & docs_json_ts_0_4_2_11_classes_base_FGWeaponProjectile_has_mBlockSprintWhenFiring & docs_json_ts_0_5_2_1_classes_base_FGWeapon_Equip_Rifle_C_base & docs_json_ts_0_5_2_1_classes_base_FGWeapon_pre_1_1 & docs_json_ts_0_5_2_1_classes_base_FGWeapon_version_specific & docs_json_ts_common_classes_FGWeapon_Equip_Rifle_C & FGEquipment & FGWeapon_base;

export type {
	has_mIsInverted,
	FGAmmoType_base,
	FGAmmoType_pre_update8,
	FGAmmoType_version_specific,
	FGAmmoTypeInstantHit_Desc_CartridgeChaos_C,
	FGAmmoTypeInstantHit_Desc_CartridgeChaos_C_version_specific,
	FGAmmoTypeInstantHit_Desc_CartridgeStandard_C,
	FGAmmoTypeInstantHit_version_specific,
	FGAmmoTypeProjectile,
	FGAmmoTypeProjectile_pre_update8,
	FGAmmoTypeProjectile_version_specific,
	FGAmmoTypeSpreadshot,
	FGAmmoTypeSpreadshot_version_specific,
	FGBuildable_base,
	FGBuildable_foundation_mDisableSnapOn,
	FGBuildable_occupied,
	FGBuildable_powered,
	FGBuildable_powered_base,
	FGBuildable_pre_1_2,
	FGBuildable_pre_update8,
	FGBuildable_tiered,
	FGBuildable_unoccupied_and_untiered,
	FGBuildable_version_specific,
	FGBuildable_with_depth,
	FGBuildableAttachmentMerger,
	FGBuildableAttachmentSplitter,
	FGBuildableBeam,
	FGBuildableCircuitSwitch,
	FGBuildableConveyorBelt,
	FGBuildableConveyorLift,
	FGBuildableCornerWall,
	FGBuildableCornerWall_base,
	FGBuildableDockingStation,
	FGBuildableDoor,
	FGBuildableDoor_automated,
	FGBuildableDoor_manual,
	FGBuildableDroneStation,
	FGBuildableFactory_jump_pad,
	FGBuildableFactory_landing_pad,
	FGBuildableFactory_not_pad,
	FGBuildableFactoryBuilding,
	FGBuildableFactorySimpleProducer,
	FGBuildableFloodlight,
	FGBuildableFoundation,
	FGBuildableFoundation_version_specific,
	FGBuildableFrackingActivator,
	FGBuildableFrackingExtractor,
	FGBuildableGeneratorFuel_biomass,
	FGBuildableGeneratorFuel_coal,
	FGBuildableGeneratorFuel_fuel,
	FGBuildableGeneratorGeoThermal,
	FGBuildableGeneratorNuclear,
	FGBuildableJumppad,
	FGBuildableLadder,
	FGBuildableLightsControlPanel,
	FGBuildableLightSource_Build_CeilingLight_C,
	FGBuildableLightSource_Build_StreetLight_C,
	FGBuildableMAM,
	FGBuildableManufacturer_Build_AssemblerMk1_C,
	FGBuildableManufacturer_Build_Blender_C,
	FGBuildableManufacturer_Build_ConstructorMk1_C,
	FGBuildableManufacturer_Build_FoundryMk1_C,
	FGBuildableManufacturer_Build_HadronCollider_C,
	FGBuildableManufacturer_Build_ManufacturerMk1_C,
	FGBuildableManufacturer_Build_OilRefinery_C,
	FGBuildableManufacturer_Build_Packager_C,
	FGBuildableManufacturer_Build_SmelterMk1_C,
	FGBuildableManufacturer_Build_SmelterMk1_C_base,
	FGBuildablePassthrough,
	FGBuildablePillar,
	FGBuildablePipeHyper,
	FGBuildablePipeline,
	FGBuildablePipeline_version_specific,
	FGBuildablePipelineJunction,
	FGBuildablePipelinePump_pump,
	FGBuildablePipelinePump_valve,
	FGBuildablePipelineSupport,
	FGBuildablePipeReservoir,
	FGBuildablePole,
	FGBuildablePowerPole,
	FGBuildablePowerStorage,
	FGBuildableRadarTower,
	FGBuildableRadarTower_version_specific,
	FGBuildableRailroadSignal_base,
	FGBuildableRailroadSignal_block,
	FGBuildableRailroadSignal_path,
	FGBuildableRailroadStation,
	FGBuildableRailroadTrack,
	FGBuildableRamp,
	FGBuildableRamp_version_specific,
	FGBuildableResourceExtractor_base,
	FGBuildableResourceExtractor_base_base,
	FGBuildableResourceExtractor_base_untimed,
	FGBuildableResourceExtractor_base_version_specific,
	FGBuildableResourceExtractor_base_version_specific_base,
	FGBuildableResourceExtractor_miner_mk1,
	FGBuildableResourceExtractor_miner_mk2,
	FGBuildableResourceExtractor_miner_mk3,
	FGBuildableResourceExtractor_oil,
	FGBuildableResourceExtractor_water,
	FGBuildableResourceSink,
	FGBuildableResourceSinkShop,
	FGBuildableSnowDispenser,
	FGBuildableSpaceElevator,
	FGBuildableSplitterSmart,
	FGBuildableStair,
	FGBuildableStorage,
	FGBuildableTradingPost,
	FGBuildableTrainPlatformCargo,
	FGBuildableTrainPlatformCargo_version_specific,
	FGBuildableTrainPlatformEmpty,
	FGBuildableWalkway,
	FGBuildableWall,
	FGBuildableWidgetSign,
	FGBuildableWire,
	FGChainsaw,
	FGChainsaw_pre_1_0,
	FGChainsaw_pre_update8,
	FGChainsaw_version_specific,
	FGConsumableEquipment,
	FGConveyorPoleStackable,
	FGDescriptor,
	FGEquipment,
	FGEquipment_noisy,
	FGEquipment_noisy_version_specific,
	FGEquipment_pre_1_0,
	FGEquipment_version_specific,
	FGEquipmentDescriptor,
	FGEquipmentStunSpear_base,
	FGEquipmentStunSpear_base_mDamageTypes,
	FGEquipmentStunSpear_base_version_specific,
	FGEquipmentStunSpear_xenobasher,
	FGEquipmentStunSpear_xenozapper,
	FGEquipmentZipline,
	FGGasMask,
	FGGasMask_version_specific,
	FGGolfCartDispenser,
	FGHoverPack,
	FGItemDescriptor,
	FGItemDescriptor_pre_1_0,
	FGItemDescriptor_version_specific,
	FGItemDescriptorBiomass,
	FGJetPack,
	FGJetPack_version_specific,
	FGJumpingStilts,
	FGJumpingStilts_version_specific,
	FGNobeliskDetonator,
	FGObjectScanner,
	FGObjectScanner_version_specific,
	FGParachute,
	FGPipeHyperStart,
	FGPortableMinerDispenser,
	FGRecipe_version_specific,
	FGResourceDescriptor,
	FGSchematic,
	FGSchematic_pre_update8,
	FGSchematic_version_specific,
	FGSchematic_with_described_unlocks,
	FGSuitBase,
	FGSuitBase_version_specific,
	FGVehicleDescriptor_Desc_CyberWagon_C,
	FGVehicleDescriptor_Desc_DroneTransport_C,
	FGVehicleDescriptor_Desc_Explorer_C,
	FGVehicleDescriptor_Desc_FreightWagon_C,
	FGVehicleDescriptor_Desc_Locomotive_C,
	FGVehicleDescriptor_Desc_Tractor_C,
	FGVehicleDescriptor_Desc_Truck_C,
	FGWeapon_base,
	FGWeapon_Equip_RebarGun_Projectile_C,
	FGWeapon_Equip_RebarGun_Projectile_C_version_specific,
	FGWeapon_Equip_Rifle_C,
};
