/* eslint-disable @stylistic/max-len */

import type {
	FGBuildingDescriptor as docs_json_ts_0_6_1_5_classes_base_overridable_FGBuildingDescriptor,
	FGConsumableDescriptor as docs_json_ts_0_6_1_5_classes_base_overridable_FGConsumableDescriptor,
	FGItemDescriptor_base as docs_json_ts_0_6_1_5_classes_base_overridable_FGItemDescriptor_base,
	FGPoleDescriptor as docs_json_ts_0_6_1_5_classes_base_overridable_FGPoleDescriptor,
	FGRecipe as docs_json_ts_0_6_1_5_classes_base_overridable_FGRecipe,
	FGVehicleDescriptor_Desc_CyberWagon_C as docs_json_ts_0_6_1_5_classes_base_overridable_FGVehicleDescriptor_Desc_CyberWagon_C,
	FGVehicleDescriptor_Desc_DroneTransport_C as docs_json_ts_0_6_1_5_classes_base_overridable_FGVehicleDescriptor_Desc_DroneTransport_C,
	FGVehicleDescriptor_Desc_Explorer_C as docs_json_ts_0_6_1_5_classes_base_overridable_FGVehicleDescriptor_Desc_Explorer_C,
	FGVehicleDescriptor_Desc_FreightWagon_C as docs_json_ts_0_6_1_5_classes_base_overridable_FGVehicleDescriptor_Desc_FreightWagon_C,
	FGVehicleDescriptor_Desc_Locomotive_C as docs_json_ts_0_6_1_5_classes_base_overridable_FGVehicleDescriptor_Desc_Locomotive_C,
	FGVehicleDescriptor_Desc_Tractor_C as docs_json_ts_0_6_1_5_classes_base_overridable_FGVehicleDescriptor_Desc_Tractor_C,
	FGVehicleDescriptor_Desc_Truck_C as docs_json_ts_0_6_1_5_classes_base_overridable_FGVehicleDescriptor_Desc_Truck_C,
} from './Base.1.0.1.4.ts';

type FGBuildingDescriptor = docs_json_ts_0_6_1_5_classes_base_overridable_FGBuildingDescriptor;

type FGConsumableDescriptor = docs_json_ts_0_6_1_5_classes_base_overridable_FGConsumableDescriptor;

type FGEquipmentDescriptor_Desc_GolfCartGold_C = docs_json_ts_0_6_1_5_classes_base_overridable_FGItemDescriptor_base;

type FGPoleDescriptor = docs_json_ts_0_6_1_5_classes_base_overridable_FGPoleDescriptor;

type FGRecipe = docs_json_ts_0_6_1_5_classes_base_overridable_FGRecipe;

type FGVehicleDescriptor_Desc_CyberWagon_C = docs_json_ts_0_6_1_5_classes_base_overridable_FGVehicleDescriptor_Desc_CyberWagon_C;

type FGVehicleDescriptor_Desc_DroneTransport_C = docs_json_ts_0_6_1_5_classes_base_overridable_FGVehicleDescriptor_Desc_DroneTransport_C;

type FGVehicleDescriptor_Desc_Explorer_C = docs_json_ts_0_6_1_5_classes_base_overridable_FGVehicleDescriptor_Desc_Explorer_C;

type FGVehicleDescriptor_Desc_FreightWagon_C = docs_json_ts_0_6_1_5_classes_base_overridable_FGVehicleDescriptor_Desc_FreightWagon_C;

type FGVehicleDescriptor_Desc_Locomotive_C = docs_json_ts_0_6_1_5_classes_base_overridable_FGVehicleDescriptor_Desc_Locomotive_C;

type FGVehicleDescriptor_Desc_Tractor_C = docs_json_ts_0_6_1_5_classes_base_overridable_FGVehicleDescriptor_Desc_Tractor_C;

type FGVehicleDescriptor_Desc_Truck_C = docs_json_ts_0_6_1_5_classes_base_overridable_FGVehicleDescriptor_Desc_Truck_C;

export type {
	FGBuildingDescriptor,
	FGConsumableDescriptor,
	FGEquipmentDescriptor_Desc_GolfCartGold_C,
	FGPoleDescriptor,
	FGRecipe,
	FGVehicleDescriptor_Desc_CyberWagon_C,
	FGVehicleDescriptor_Desc_DroneTransport_C,
	FGVehicleDescriptor_Desc_Explorer_C,
	FGVehicleDescriptor_Desc_FreightWagon_C,
	FGVehicleDescriptor_Desc_Locomotive_C,
	FGVehicleDescriptor_Desc_Tractor_C,
	FGVehicleDescriptor_Desc_Truck_C,
};
