/* eslint-disable @stylistic/max-len */

import type {
	BGRA as docs_json_ts_common_types_BGRA,
	bool_string as docs_json_ts_common_types_bool_string,
	decimal_string as docs_json_ts_common_types_decimal_string,
	empty_object as docs_json_ts_common_types_empty_object,
	integer_string as docs_json_ts_common_types_integer_string,
	RGBA as docs_json_ts_common_types_RGBA,
	XYZ_decimal_string as docs_json_ts_common_types_XYZ_decimal_string,
	XYZ_decimal_string_list as docs_json_ts_common_types_XYZ_decimal_string_list,
} from './../../common/types.ts';

import type {
	FGBuildable_base_pre_1_0 as docs_json_ts_0_3_7_7_classes_base_FGBuildable_base_pre_1_0,
	FGBuildable_base_pre_update5 as docs_json_ts_0_3_7_7_classes_base_FGBuildable_base_pre_update5,
	FGBuildable_base_version_specific as docs_json_ts_0_3_7_7_classes_base_FGBuildable_base_version_specific,
	FGBuildable_docking_station_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildable_docking_station_base_base_base,
	FGBuildable_docking_station_base_with_mMapText as docs_json_ts_0_3_7_7_classes_base_FGBuildable_docking_station_base_with_mMapText,
	FGBuildable_occupied as docs_json_ts_0_3_7_7_classes_base_FGBuildable_occupied,
	FGBuildable_powered_base_resources as docs_json_ts_0_3_7_7_classes_base_FGBuildable_powered_base_resources,
	FGBuildable_powered_base_resources_base as docs_json_ts_0_3_7_7_classes_base_FGBuildable_powered_base_resources_base,
	FGBuildable_powered_pre_1_0 as docs_json_ts_0_3_7_7_classes_base_FGBuildable_powered_pre_1_0,
	FGBuildable_powered_storage_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildable_powered_storage_base_base,
	FGBuildable_powered_version_specific as docs_json_ts_0_3_7_7_classes_base_FGBuildable_powered_version_specific,
	FGBuildable_tiered as docs_json_ts_0_3_7_7_classes_base_FGBuildable_tiered,
	FGBuildable_with_mLength as docs_json_ts_0_3_7_7_classes_base_FGBuildable_with_mLength,
	FGBuildableAttachment_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableAttachment_base,
	FGBuildableAttachment_has_mCurrentInventoryIndex as docs_json_ts_0_3_7_7_classes_base_FGBuildableAttachment_has_mCurrentInventoryIndex,
	FGBuildableAttachment_splitter_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableAttachment_splitter_base,
	FGBuildableAttachment_splitter_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableAttachment_splitter_base_base_base,
	FGBuildableAttachmentMerger_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableAttachmentMerger_base,
	FGBuildableConveyorBelt_pre_1_0 as docs_json_ts_0_3_7_7_classes_base_FGBuildableConveyorBelt_pre_1_0,
	FGBuildableConveyorBelt_pre_update8 as docs_json_ts_0_3_7_7_classes_base_FGBuildableConveyorBelt_pre_update8,
	FGBuildableConveyorLift_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableConveyorLift_base,
	FGBuildableDockingStation_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableDockingStation_base,
	FGBuildableFactory_jump_pad_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableFactory_jump_pad_base,
	FGBuildableFactory_landing_pad_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableFactory_landing_pad_base,
	FGBuildableFactorySimpleProducer_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableFactorySimpleProducer_base,
	FGBuildableGenerator_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableGenerator_base,
	FGBuildableGenerator_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableGenerator_base_base_base,
	FGBuildableGenerator_base_base_pre_1_0 as docs_json_ts_0_3_7_7_classes_base_FGBuildableGenerator_base_base_pre_1_0,
	FGBuildableGenerator_no_fuel_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableGenerator_no_fuel_base_base,
	FGBuildableGenerator_no_fuel_base_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableGenerator_no_fuel_base_base_base_base,
	FGBuildableGeneratorFuel_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableGeneratorFuel_base,
	FGBuildableGeneratorFuel_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableGeneratorFuel_base_base_base,
	FGBuildableGeneratorFuel_biomass_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableGeneratorFuel_biomass_base,
	FGBuildableGeneratorFuel_coal_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableGeneratorFuel_coal_base,
	FGBuildableGeneratorFuel_fuel_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableGeneratorFuel_fuel_base,
	FGBuildableGeneratorGeoThermal_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableGeneratorGeoThermal_base,
	FGBuildableGeneratorNuclear_version_specific as docs_json_ts_0_3_7_7_classes_base_FGBuildableGeneratorNuclear_version_specific,
	FGBuildableJumppad_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableJumppad_base,
	FGBuildableLadder_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableLadder_base,
	FGBuildableManufacturer_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base,
	FGBuildableManufacturer_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_base,
	FGBuildableManufacturer_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_base_base,
	FGBuildableManufacturer_base_IsPowered as docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_IsPowered,
	FGBuildableManufacturer_base_mProductionEffectsRunning as docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_mProductionEffectsRunning,
	FGBuildableManufacturer_base_packager as docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_packager,
	FGBuildablePipeline_base as docs_json_ts_0_3_7_7_classes_base_FGBuildablePipeline_base,
	FGBuildablePipeline_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildablePipeline_base_base,
	FGBuildablePipeline_base_no_indicator_base as docs_json_ts_0_3_7_7_classes_base_FGBuildablePipeline_base_no_indicator_base,
	FGBuildablePipeline_base_root_quantized as docs_json_ts_0_3_7_7_classes_base_FGBuildablePipeline_base_root_quantized,
	FGBuildablePipeline_base_spline as docs_json_ts_0_3_7_7_classes_base_FGBuildablePipeline_base_spline,
	FGBuildablePipelinePump_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildablePipelinePump_base_base,
	FGBuildablePipelinePump_powered_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildablePipelinePump_powered_base_base,
	FGBuildablePipelinePump_powered_version_specific as docs_json_ts_0_3_7_7_classes_base_FGBuildablePipelinePump_powered_version_specific,
	FGBuildablePipelinePump_pump_version_specific as docs_json_ts_0_3_7_7_classes_base_FGBuildablePipelinePump_pump_version_specific,
	FGBuildablePipelineSupport_base as docs_json_ts_0_3_7_7_classes_base_FGBuildablePipelineSupport_base,
	FGBuildablePipeReservoir_base as docs_json_ts_0_3_7_7_classes_base_FGBuildablePipeReservoir_base,
	FGBuildablePowerPole as docs_json_ts_0_3_7_7_classes_base_FGBuildablePowerPole,
	FGBuildableRadarTower_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableRadarTower_base,
	FGBuildableRailroadStation_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableRailroadStation_base,
	FGBuildableRailroadTrack as docs_json_ts_0_3_7_7_classes_base_FGBuildableRailroadTrack,
	FGBuildableRailroadTrack_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableRailroadTrack_base,
	FGBuildableResourceExtractor_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_base,
	FGBuildableResourceExtractor_miner as docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_miner,
	FGBuildableResourceExtractor_miner_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_miner_base,
	FGBuildableResourceExtractor_miner_mk2_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_miner_mk2_base,
	FGBuildableResourceExtractor_miner_mk3_version_specific as docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_miner_mk3_version_specific,
	FGBuildableResourceExtractor_oil_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_oil_base,
	FGBuildableResourceExtractor_piped as docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_piped,
	FGBuildableResourceExtractor_piped_pre_1_0 as docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_piped_pre_1_0,
	FGBuildableResourceExtractor_timed as docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_timed,
	FGBuildableResourceExtractor_water_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_water_base,
	FGBuildableResourceSink_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceSink_base,
	FGBuildableResourceSink_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceSink_base_base,
	FGBuildableResourceSink_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceSink_base_base_base,
	FGBuildableResourceSinkShop_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceSinkShop_base,
	FGBuildableSpaceElevator_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableSpaceElevator_base,
	FGBuildableSplitterSmart_version_specific as docs_json_ts_0_3_7_7_classes_base_FGBuildableSplitterSmart_version_specific,
	FGBuildableStorage_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableStorage_base,
	FGBuildableTradingPost_pre_1_0 as docs_json_ts_0_3_7_7_classes_base_FGBuildableTradingPost_pre_1_0,
	FGBuildableTradingPost_pre_update5 as docs_json_ts_0_3_7_7_classes_base_FGBuildableTradingPost_pre_update5,
	FGBuildableTradingPost_pre_update8 as docs_json_ts_0_3_7_7_classes_base_FGBuildableTradingPost_pre_update8,
	FGBuildableTradingPost_version_specific as docs_json_ts_0_3_7_7_classes_base_FGBuildableTradingPost_version_specific,
	FGBuildableTrainPlatform_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableTrainPlatform_base,
	FGBuildableTrainPlatform_with_storage_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableTrainPlatform_with_storage_base,
	FGBuildableTrainPlatformCargo_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableTrainPlatformCargo_base,
	FGBuildableWire as docs_json_ts_0_3_7_7_classes_base_FGBuildableWire,
	FGColorGun_base as docs_json_ts_0_3_7_7_classes_base_FGColorGun_base,
	FGConsumableDescriptor_base as docs_json_ts_0_3_7_7_classes_base_FGConsumableDescriptor_base,
	FGConsumableEquipment_pre_update8 as docs_json_ts_0_3_7_7_classes_base_FGConsumableEquipment_pre_update8,
	FGConsumableEquipment_version_specific as docs_json_ts_0_3_7_7_classes_base_FGConsumableEquipment_version_specific,
	FGDescriptor_base as docs_json_ts_0_3_7_7_classes_base_FGDescriptor_base,
	FGDescriptor_BuildMenu_base as docs_json_ts_0_3_7_7_classes_base_FGDescriptor_BuildMenu_base,
	FGEquipment as docs_json_ts_0_3_7_7_classes_base_FGEquipment,
	FGEquipment_base as docs_json_ts_0_3_7_7_classes_base_FGEquipment_base,
	FGEquipment_dispenser as docs_json_ts_0_3_7_7_classes_base_FGEquipment_dispenser,
	FGEquipment_has_mUseDefaultPrimaryFire as docs_json_ts_0_3_7_7_classes_base_FGEquipment_has_mUseDefaultPrimaryFire,
	FGEquipment_pre_1_0 as docs_json_ts_0_3_7_7_classes_base_FGEquipment_pre_1_0,
	FGNobeliskDetonator_base as docs_json_ts_0_3_7_7_classes_base_FGNobeliskDetonator_base,
	FGParachute_has_mIsDeployed as docs_json_ts_0_3_7_7_classes_base_FGParachute_has_mIsDeployed,
	FGParachute_has_mTerminalVelocityZ as docs_json_ts_0_3_7_7_classes_base_FGParachute_has_mTerminalVelocityZ,
	FGPipeHyperStart_base as docs_json_ts_0_3_7_7_classes_base_FGPipeHyperStart_base,
	FGPortableMinerDispenser_version_specific as docs_json_ts_0_3_7_7_classes_base_FGPortableMinerDispenser_version_specific,
	FGRecipe_pre_update5 as docs_json_ts_0_3_7_7_classes_base_FGRecipe_pre_update5,
	FGRecipe_version_specific as docs_json_ts_0_3_7_7_classes_base_FGRecipe_version_specific,
	FGResourceDescriptor_base as docs_json_ts_0_3_7_7_classes_base_FGResourceDescriptor_base,
	FGSnowballWeapon_version_specific as docs_json_ts_0_3_7_7_classes_base_FGSnowballWeapon_version_specific,
	FGWeaponInstantFire_base as docs_json_ts_0_3_7_7_classes_base_FGWeaponInstantFire_base,
	FGWeaponProjectile as docs_json_ts_0_3_7_7_classes_base_FGWeaponProjectile,
	FGWeaponProjectile_base as docs_json_ts_0_3_7_7_classes_base_FGWeaponProjectile_base,
	FGWeaponProjectile_has_mAttachSocket as docs_json_ts_0_3_7_7_classes_base_FGWeaponProjectile_has_mAttachSocket,
	FGWeaponProjectile_instant as docs_json_ts_0_3_7_7_classes_base_FGWeaponProjectile_instant,
	FGWeaponProjectile_thrown as docs_json_ts_0_3_7_7_classes_base_FGWeaponProjectile_thrown,
	FGWeaponProjectileFire_base_random as docs_json_ts_0_3_7_7_classes_base_FGWeaponProjectileFire_base_random,
	FGWeaponProjectileFire_base_version_specific as docs_json_ts_0_3_7_7_classes_base_FGWeaponProjectileFire_base_version_specific,
	has_mCanStack as docs_json_ts_0_3_7_7_classes_base_has_mCanStack,
	has_mDisableAttachmentSnapOn as docs_json_ts_0_3_7_7_classes_base_has_mDisableAttachmentSnapOn,
	has_mDisableSnapOn as docs_json_ts_0_3_7_7_classes_base_has_mDisableSnapOn,
	has_mElevation as docs_json_ts_0_3_7_7_classes_base_has_mElevation,
	has_mHeight as docs_json_ts_0_3_7_7_classes_base_has_mHeight,
	has_mMeshLength as docs_json_ts_0_3_7_7_classes_base_has_mMeshLength,
	has_mNumCyclesForProductivity as docs_json_ts_0_3_7_7_classes_base_has_mNumCyclesForProductivity,
	has_mResourceSinkPoints as docs_json_ts_0_3_7_7_classes_base_has_mResourceSinkPoints,
	has_mSize as docs_json_ts_0_3_7_7_classes_base_has_mSize,
	has_mSplineData as docs_json_ts_0_3_7_7_classes_base_has_mSplineData,
	has_mStackHeight as docs_json_ts_0_3_7_7_classes_base_has_mStackHeight,
	has_mUseStaticHeight as docs_json_ts_0_3_7_7_classes_base_has_mUseStaticHeight,
	has_mWidth as docs_json_ts_0_3_7_7_classes_base_has_mWidth,
} from './../../0.3.7.7/classes/Base.ts';

import type {
	FGRailroadTrackConnectionComponent_quoted as docs_json_ts_0_4_2_11_properties_FGRailroadTrackConnectionComponent_quoted,
	m_SFXSockets_item_exhaust as docs_json_ts_0_4_2_11_properties_m_SFXSockets_item_exhaust,
	m_SFXSockets_item_turbine as docs_json_ts_0_4_2_11_properties_m_SFXSockets_item_turbine,
	mAllowedResourceForms as docs_json_ts_0_4_2_11_properties_mAllowedResourceForms,
	mDefaultFuelClasses_item_nuclear as docs_json_ts_0_4_2_11_properties_mDefaultFuelClasses_item_nuclear,
	mFogPlaneTransforms_empty as docs_json_ts_0_4_2_11_properties_mFogPlaneTransforms_empty,
	mFogPlaneTransforms_list as docs_json_ts_0_4_2_11_properties_mFogPlaneTransforms_list,
	mForm as docs_json_ts_0_4_2_11_properties_mForm,
	mFuel as docs_json_ts_0_4_2_11_properties_mFuel,
	mMeshes_item as docs_json_ts_0_4_2_11_properties_mMeshes_item,
	mProducedIn as docs_json_ts_0_4_2_11_properties_mProducedIn,
	Texture2D as docs_json_ts_0_4_2_11_properties_Texture2D,
	Tier as docs_json_ts_0_4_2_11_properties_Tier,
} from './../types/properties.ts';

import type {
	FGBuildableResourceExtractor_miner_base as docs_json_ts_0_3_7_7_classes_base_overridable_FGBuildableResourceExtractor_miner_base,
	FGBuildableResourceExtractor_only_allow_certain_resources as docs_json_ts_0_3_7_7_classes_base_overridable_FGBuildableResourceExtractor_only_allow_certain_resources,
	FGEquipment_version_specific as docs_json_ts_0_3_7_7_classes_base_overridable_FGEquipment_version_specific,
} from './../../0.3.7.7/classes/Base.overridable.ts';

import type {
	FGBuildable_unoccupied_and_untiered as docs_json_ts_common_classes_FGBuildable_unoccupied_and_untiered,
	FGBuildableAttachmentMerger as docs_json_ts_common_classes_FGBuildableAttachmentMerger,
	FGBuildableAttachmentSplitter as docs_json_ts_common_classes_FGBuildableAttachmentSplitter,
	FGBuildableCircuitSwitch as docs_json_ts_common_classes_FGBuildableCircuitSwitch,
	FGBuildableConveyorBelt as docs_json_ts_common_classes_FGBuildableConveyorBelt,
	FGBuildableConveyorLift as docs_json_ts_common_classes_FGBuildableConveyorLift,
	FGBuildableDockingStation as docs_json_ts_common_classes_FGBuildableDockingStation,
	FGBuildableDroneStation as docs_json_ts_common_classes_FGBuildableDroneStation,
	FGBuildableFactory as docs_json_ts_common_classes_FGBuildableFactory,
	FGBuildableFactorySimpleProducer as docs_json_ts_common_classes_FGBuildableFactorySimpleProducer,
	FGBuildableFloodlight as docs_json_ts_common_classes_FGBuildableFloodlight,
	FGBuildableFoundation as docs_json_ts_common_classes_FGBuildableFoundation,
	FGBuildableFrackingActivator as docs_json_ts_common_classes_FGBuildableFrackingActivator,
	FGBuildableFrackingExtractor as docs_json_ts_common_classes_FGBuildableFrackingExtractor,
	FGBuildableGeneratorFuel as docs_json_ts_common_classes_FGBuildableGeneratorFuel,
	FGBuildableGeneratorGeoThermal as docs_json_ts_common_classes_FGBuildableGeneratorGeoThermal,
	FGBuildableGeneratorNuclear as docs_json_ts_common_classes_FGBuildableGeneratorNuclear,
	FGBuildableJumppad as docs_json_ts_common_classes_FGBuildableJumppad,
	FGBuildableLadder as docs_json_ts_common_classes_FGBuildableLadder,
	FGBuildableLightsControlPanel as docs_json_ts_common_classes_FGBuildableLightsControlPanel,
	FGBuildableLightSource as docs_json_ts_common_classes_FGBuildableLightSource,
	FGBuildableMAM as docs_json_ts_common_classes_FGBuildableMAM,
	FGBuildableManufacturer as docs_json_ts_common_classes_FGBuildableManufacturer,
	FGBuildableManufacturerVariablePower as docs_json_ts_common_classes_FGBuildableManufacturerVariablePower,
	FGBuildablePipeHyper as docs_json_ts_common_classes_FGBuildablePipeHyper,
	FGBuildablePipeline as docs_json_ts_common_classes_FGBuildablePipeline,
	FGBuildablePipelineJunction as docs_json_ts_common_classes_FGBuildablePipelineJunction,
	FGBuildablePipelinePump as docs_json_ts_common_classes_FGBuildablePipelinePump,
	FGBuildablePipelineSupport as docs_json_ts_common_classes_FGBuildablePipelineSupport,
	FGBuildablePipeReservoir as docs_json_ts_common_classes_FGBuildablePipeReservoir,
	FGBuildablePole as docs_json_ts_common_classes_FGBuildablePole,
	FGBuildablePowerStorage as docs_json_ts_common_classes_FGBuildablePowerStorage,
	FGBuildableRadarTower as docs_json_ts_common_classes_FGBuildableRadarTower,
	FGBuildableRailroadStation as docs_json_ts_common_classes_FGBuildableRailroadStation,
	FGBuildableRailroadTrack as docs_json_ts_common_classes_FGBuildableRailroadTrack,
	FGBuildableResourceExtractor as docs_json_ts_common_classes_FGBuildableResourceExtractor,
	FGBuildableResourceSink as docs_json_ts_common_classes_FGBuildableResourceSink,
	FGBuildableResourceSinkShop as docs_json_ts_common_classes_FGBuildableResourceSinkShop,
	FGBuildableSnowDispenser as docs_json_ts_common_classes_FGBuildableSnowDispenser,
	FGBuildableSpaceElevator as docs_json_ts_common_classes_FGBuildableSpaceElevator,
	FGBuildableSplitterSmart as docs_json_ts_common_classes_FGBuildableSplitterSmart,
	FGBuildableStair as docs_json_ts_common_classes_FGBuildableStair,
	FGBuildableTradingPost as docs_json_ts_common_classes_FGBuildableTradingPost,
	FGBuildableTrainPlatformCargo as docs_json_ts_common_classes_FGBuildableTrainPlatformCargo,
	FGBuildableTrainPlatformEmpty as docs_json_ts_common_classes_FGBuildableTrainPlatformEmpty,
	FGBuildableWalkway as docs_json_ts_common_classes_FGBuildableWalkway,
	FGBuildableWall as docs_json_ts_common_classes_FGBuildableWall,
	FGBuildingDescriptor as docs_json_ts_common_classes_FGBuildingDescriptor,
	FGColorGun as docs_json_ts_common_classes_FGColorGun,
	FGConsumableDescriptor as docs_json_ts_common_classes_FGConsumableDescriptor,
	FGConsumableEquipment as docs_json_ts_common_classes_FGConsumableEquipment,
	FGConveyorPoleStackable as docs_json_ts_common_classes_FGConveyorPoleStackable,
	FGEquipmentDescriptor as docs_json_ts_common_classes_FGEquipmentDescriptor,
	FGEquipmentZipline as docs_json_ts_common_classes_FGEquipmentZipline,
	FGHoverPack as docs_json_ts_common_classes_FGHoverPack,
	FGItemDescriptor as docs_json_ts_common_classes_FGItemDescriptor,
	FGItemDescriptorBiomass as docs_json_ts_common_classes_FGItemDescriptorBiomass,
	FGNobeliskDetonator as docs_json_ts_common_classes_FGNobeliskDetonator,
	FGParachute as docs_json_ts_common_classes_FGParachute,
	FGPipeHyperStart as docs_json_ts_common_classes_FGPipeHyperStart,
	FGPoleDescriptor as docs_json_ts_common_classes_FGPoleDescriptor,
	FGPortableMinerDispenser as docs_json_ts_common_classes_FGPortableMinerDispenser,
	FGRecipe as docs_json_ts_common_classes_FGRecipe,
	FGResourceDescriptor as docs_json_ts_common_classes_FGResourceDescriptor,
	FGSchematic as docs_json_ts_common_classes_FGSchematic,
	FGSnowballWeapon as docs_json_ts_common_classes_FGSnowballWeapon,
	FGVehicleDescriptor as docs_json_ts_common_classes_FGVehicleDescriptor,
	FGWeapon_Equip_RebarGun_Projectile_C as docs_json_ts_common_classes_FGWeapon_Equip_RebarGun_Projectile_C,
	FGWeapon_Equip_Rifle_C as docs_json_ts_common_classes_FGWeapon_Equip_Rifle_C,
} from './../../common/classes.ts';

import type {
	has_mBatteryClasses as docs_json_ts_0_4_2_11_overridable_has_mBatteryClasses,
} from './../types/overridable.ts';

import type {
	hasClassName as docs_json_ts_common_classes_base_hasClassName,
	isDescribed as docs_json_ts_common_classes_base_isDescribed,
} from './../../common/classes/Base.ts';

import type {
	FGSchematic_base as docs_json_ts_0_4_2_11_classes_base_overridable_FGSchematic_base,
	FGSchematic_version_specific as docs_json_ts_0_4_2_11_classes_base_overridable_FGSchematic_version_specific,
} from './Base.overridable.ts';

import type {
	mUnlocks_item_base as docs_json_ts_0_3_7_7_properties_mUnlocks_item_base,
	Texture2D_base as docs_json_ts_0_3_7_7_properties_Texture2D_base,
} from './../../0.3.7.7/types/properties.ts';

type has_mHasPower = {
	mHasPower: docs_json_ts_common_types_bool_string,
};

type has_mInventorySize = {
	mInventorySize: docs_json_ts_common_types_integer_string,
};

type has_mPowerConsumption = {
	mPowerConsumption: docs_json_ts_common_types_decimal_string,
};

type FGBuildable_base = docs_json_ts_0_3_7_7_classes_base_FGBuildable_base_pre_1_0 & docs_json_ts_0_3_7_7_classes_base_FGBuildable_base_pre_update5 & docs_json_ts_0_3_7_7_classes_base_FGBuildable_base_version_specific & FGBuildable_base_pre_update5 & FGBuildable_base_pre_update8 & FGBuildable_base_version_specific;

type FGBuildable_base_pre_update5 = {
	mFogPlaneTransforms: docs_json_ts_0_4_2_11_properties_mFogPlaneTransforms_empty | docs_json_ts_0_4_2_11_properties_mFogPlaneTransforms_list,
};

type FGBuildable_base_pre_update8 = {
	mToggleDormancyOnInteraction: docs_json_ts_common_types_bool_string,
	mShouldModifyWorldGrid: docs_json_ts_common_types_bool_string,
};

type FGBuildable_base_version_specific = {
	mToggleDormancyOnInteraction: docs_json_ts_common_types_bool_string,
	mShouldModifyWorldGrid: docs_json_ts_common_types_bool_string,
};

type FGBuildable_docking_station = docs_json_ts_0_3_7_7_classes_base_FGBuildable_docking_station_base_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildable_docking_station_base_with_mMapText & docs_json_ts_0_3_7_7_classes_base_FGBuildable_powered_storage_base_base & FGBuildable_powered_storage_base & FGBuildable_powered_storage;

type FGBuildable_has_mCachedSkeletalMeshes = {
	mCachedSkeletalMeshes: '',
};

type FGBuildable_light_related_thing_base = {
	mIsEnabled: docs_json_ts_common_types_bool_string,
	mLightControlData: {
		Intensity: docs_json_ts_common_types_decimal_string,
	},
};

type FGBuildable_mStopped_audio_stuff = {
	mStoppedProducingAnimationSounds: docs_json_ts_common_types_bool_string,
	mStoppedAkComponents: '',
	mSocketStoppedAkComponents: '',
};

type FGBuildable_occupied = docs_json_ts_0_3_7_7_classes_base_FGBuildable_occupied & FGBuildable_base;

type FGBuildable_powered = docs_json_ts_0_3_7_7_classes_base_FGBuildable_powered_pre_1_0 & docs_json_ts_0_3_7_7_classes_base_FGBuildable_powered_version_specific & docs_json_ts_0_3_7_7_classes_base_has_mNumCyclesForProductivity & FGBuildable_base & FGBuildable_has_mCachedSkeletalMeshes & FGBuildable_powered_version_specific;

type FGBuildable_powered_has_mAllowedResourceForms = FGBuildable_powered & FGBuildable_powered_has_mAllowedResourceForms_base;

type FGBuildable_powered_has_mAllowedResourceForms_base = {
	mAllowedResourceForms: docs_json_ts_0_4_2_11_properties_mAllowedResourceForms,
};

type FGBuildable_powered_has_mAllowedResourceForms_with_resources = docs_json_ts_0_3_7_7_classes_base_FGBuildable_powered_base_resources & FGBuildable_powered_has_mAllowedResourceForms & FGBuildable_powered_has_mAllowedResourceForms_with_resources_base;

type FGBuildable_powered_has_mAllowedResourceForms_with_resources_base = docs_json_ts_0_3_7_7_classes_base_FGBuildable_powered_base_resources_base & FGBuildable_powered_has_mAllowedResourceForms_with_resources_base_base;

type FGBuildable_powered_has_mAllowedResourceForms_with_resources_base_base = docs_json_ts_0_3_7_7_classes_base_overridable_FGBuildableResourceExtractor_only_allow_certain_resources & FGBuildable_powered_has_mAllowedResourceForms_base;

type FGBuildable_powered_version_specific = {
	mOnProductionStatusChanged: docs_json_ts_common_types_empty_object,
};

type FGBuildable_powered_storage = FGBuildable_powered & FGBuildable_powered_storage_base;

type FGBuildable_powered_storage_base = docs_json_ts_0_3_7_7_classes_base_FGBuildable_powered_storage_base_base & FGBuildable_has_mCachedSkeletalMeshes;

type FGBuildable_tiered = docs_json_ts_0_3_7_7_classes_base_FGBuildable_tiered & FGBuildable_base;

type FGBuildable_unoccupied_and_untiered = docs_json_ts_common_classes_FGBuildable_unoccupied_and_untiered & FGBuildable_base;

type FGBuildableAttachment = docs_json_ts_0_3_7_7_classes_base_FGBuildableAttachment_base & FGBuildable_powered;

type FGBuildableAttachmentMerger = docs_json_ts_0_3_7_7_classes_base_FGBuildableAttachmentMerger_base & docs_json_ts_common_classes_FGBuildableAttachmentMerger & FGBuildableAttachment;

type FGBuildableAttachmentSplitter = docs_json_ts_0_3_7_7_classes_base_FGBuildableAttachment_splitter_base & docs_json_ts_common_classes_FGBuildableAttachmentSplitter & FGBuildableAttachment;

type FGBuildableCircuitSwitch = docs_json_ts_common_classes_FGBuildableCircuitSwitch & FGBuildable_base & FGBuildableCircuitSwitch_base;

type FGBuildableCircuitSwitch_base = {
	mTextRenderers: '',
	bIsSignificant: docs_json_ts_common_types_bool_string,
	mMaxCharacters: docs_json_ts_common_types_integer_string,
	mOnIsSwitchOnChanged: docs_json_ts_common_types_empty_object,
	mOnIsConnectedChanged: docs_json_ts_common_types_empty_object,
	mIsSwitchOn: docs_json_ts_common_types_bool_string,
	mHasBuildingTag: docs_json_ts_common_types_bool_string,
	mBuildingTag: '',
	mIsBridgeConnected: docs_json_ts_common_types_bool_string,
	mConnections: '',
};

type FGBuildableConveyorBelt_spline = docs_json_ts_0_3_7_7_classes_base_FGBuildableConveyorBelt_pre_1_0 & docs_json_ts_0_3_7_7_classes_base_FGBuildableConveyorBelt_pre_update8 & docs_json_ts_0_3_7_7_classes_base_has_mMeshLength & docs_json_ts_0_3_7_7_classes_base_has_mSplineData & docs_json_ts_common_classes_FGBuildableConveyorBelt & FGBuildable_base;

type FGBuildableConveyorLift = docs_json_ts_0_3_7_7_classes_base_FGBuildableConveyorBelt_pre_1_0 & docs_json_ts_0_3_7_7_classes_base_FGBuildableConveyorBelt_pre_update8 & docs_json_ts_0_3_7_7_classes_base_FGBuildableConveyorLift_base & docs_json_ts_common_classes_FGBuildableConveyorLift & FGBuildable_base;

type FGBuildableDockingStation = docs_json_ts_0_3_7_7_classes_base_FGBuildableDockingStation_base & docs_json_ts_common_classes_FGBuildableDockingStation & FGBuildable_docking_station;

type FGBuildableDroneStation = docs_json_ts_0_4_2_11_overridable_has_mBatteryClasses & docs_json_ts_common_classes_FGBuildableDroneStation & FGBuildable_docking_station & docs_json_ts_0_3_7_7_classes_base_FGBuildable_docking_station_base_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildable_docking_station_base_with_mMapText & docs_json_ts_0_3_7_7_classes_base_FGBuildable_powered_storage_base_base & FGBuildable_powered_storage_base & FGBuildableDroneStation_pre_1_0 & FGBuildableDroneStation_pre_update5 & FGBuildableDroneStation_version_specific;

type FGBuildableDroneStation_pre_1_0 = {
	mBatteryStorageSizeX: docs_json_ts_common_types_integer_string,
	mBatteryStorageSizeY: docs_json_ts_common_types_integer_string,
};

type FGBuildableDroneStation_pre_update5 = {
	mMapText: 'Drone Port',
};

type FGBuildableDroneStation_version_specific = {
	mStoppedProducingAnimationSounds: docs_json_ts_common_types_bool_string,
	mStoppedAkComponents: '',
	mSocketStoppedAkComponents: '',
	m_DockingStates: 'DS_UNDOCKED',
	m_OffsetTime: docs_json_ts_common_types_decimal_string,
	mDroneDockingStartLocationLocal: docs_json_ts_common_types_XYZ_decimal_string,
	mDroneDockingLocationLocal: docs_json_ts_common_types_XYZ_decimal_string,
	mDroneDockingQueue: '',
	mStationHasDronesInQueue: docs_json_ts_common_types_bool_string,
	mItemTransferringStage: 'ITS_NONE',
	mTransferProgress: docs_json_ts_common_types_decimal_string,
	mDroneQueueRadius: docs_json_ts_common_types_decimal_string,
	mDroneQueueSeparationRadius: docs_json_ts_common_types_decimal_string,
	mDroneQueueVerticalSeparation: docs_json_ts_common_types_decimal_string,
	mTripPowerCost: docs_json_ts_common_types_decimal_string,
	mTripPowerPerMeterCost: docs_json_ts_common_types_decimal_string,
	mTripInformationSampleCount: docs_json_ts_common_types_integer_string,
};

type FGBuildableFactory_jump_pad = docs_json_ts_0_3_7_7_classes_base_FGBuildableFactory_jump_pad_base & docs_json_ts_common_classes_FGBuildableFactory & FGBuildable_powered;

type FGBuildableFactory_landing_pad = docs_json_ts_0_3_7_7_classes_base_FGBuildableFactory_landing_pad_base & docs_json_ts_common_classes_FGBuildableFactory & FGBuildable_powered;

type FGBuildableFactory_not_a_pad = docs_json_ts_common_classes_FGBuildableFactory & FGBuildable_powered;

type FGBuildableFactorySimpleProducer = docs_json_ts_0_3_7_7_classes_base_FGBuildableFactorySimpleProducer_base & docs_json_ts_common_classes_FGBuildableFactorySimpleProducer & FGBuildable_powered;

type FGBuildableFloodlight = docs_json_ts_common_classes_FGBuildableFloodlight & FGBuildable_base & FGBuildable_light_related_thing_base & FGBuildableFloodlight_version_specific & FGBuildableLightSource_version_specific & has_mHasPower & has_mPowerConsumption;

type FGBuildableFloodlight_version_specific = {
	mFixtureAngle: docs_json_ts_common_types_integer_string,
};

type FGBuildableFoundation = docs_json_ts_0_3_7_7_classes_base_has_mDisableAttachmentSnapOn & docs_json_ts_0_3_7_7_classes_base_has_mDisableSnapOn & docs_json_ts_0_3_7_7_classes_base_has_mElevation & docs_json_ts_0_3_7_7_classes_base_has_mHeight & docs_json_ts_0_3_7_7_classes_base_has_mSize & docs_json_ts_common_classes_FGBuildableFoundation & FGBuildable_base;

type FGBuildableFrackingActivator = docs_json_ts_common_classes_FGBuildableFrackingActivator & FGBuildable_powered_has_mAllowedResourceForms_with_resources & FGBuildableFrackingActivator_base;

type FGBuildableFrackingActivator_base = FGBuildable_powered_has_mAllowedResourceForms_with_resources_base & FGBuildableFrackingActivator_version_specific;

type FGBuildableFrackingActivator_version_specific = {
	CurrentPotentialChangedDelegate: docs_json_ts_common_types_empty_object,
	ConnectedExtractorCountChangedDelegate: docs_json_ts_common_types_empty_object,
	mActivationStartupTime: docs_json_ts_common_types_decimal_string,
	mActivationStartupTimer: docs_json_ts_common_types_decimal_string,
	mSatelliteActivationComplete: docs_json_ts_common_types_bool_string,
	mSatelliteNodeCount: docs_json_ts_common_types_integer_string,
	mConnectedExtractorCount: docs_json_ts_common_types_integer_string,
	mDefaultPotentialExtractionPerMinute: docs_json_ts_common_types_decimal_string,
};

type FGBuildableFrackingExtractor = docs_json_ts_common_classes_FGBuildableFrackingExtractor & FGBuildableResourceExtractor_base;

type FGBuildableGenerator = docs_json_ts_0_3_7_7_classes_base_FGBuildableGenerator_base & FGBuildableGenerator_no_fuel;

type FGBuildableGenerator_no_fuel = docs_json_ts_0_3_7_7_classes_base_FGBuildable_powered_pre_1_0 & docs_json_ts_0_3_7_7_classes_base_FGBuildable_powered_version_specific & docs_json_ts_0_3_7_7_classes_base_FGBuildableGenerator_no_fuel_base_base & docs_json_ts_0_3_7_7_classes_base_has_mNumCyclesForProductivity & FGBuildable_powered;

type FGBuildableGeneratorFuel_base = docs_json_ts_0_3_7_7_classes_base_FGBuildableGeneratorFuel_base & FGBuildableGeneratorFuel_base_base;

type FGBuildableGeneratorFuel_base_base = docs_json_ts_0_3_7_7_classes_base_FGBuildableGenerator_base_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableGenerator_base_base_pre_1_0 & docs_json_ts_0_3_7_7_classes_base_FGBuildableGenerator_no_fuel_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableGenerator_no_fuel_base_base_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableGeneratorFuel_base_base_base & FGBuildableGeneratorFuel_base_base_base;

type FGBuildableGeneratorFuel_base_base_base = {
	mFuel: docs_json_ts_0_4_2_11_properties_mFuel,
	mFuelLoadAmount: docs_json_ts_common_types_integer_string,
	mIsFullBlast: docs_json_ts_common_types_bool_string,
	m_SFXSockets?: [
		docs_json_ts_0_4_2_11_properties_m_SFXSockets_item_turbine,
		docs_json_ts_0_4_2_11_properties_m_SFXSockets_item_turbine,
		...docs_json_ts_0_4_2_11_properties_m_SFXSockets_item_turbine[],
	] | [
		docs_json_ts_0_4_2_11_properties_m_SFXSockets_item_exhaust,
		docs_json_ts_0_4_2_11_properties_m_SFXSockets_item_exhaust,
		...docs_json_ts_0_4_2_11_properties_m_SFXSockets_item_exhaust[],
	],
	m_CurrentPotential?: docs_json_ts_common_types_integer_string,
};

type FGBuildableGeneratorFuel_biomass = docs_json_ts_0_3_7_7_classes_base_FGBuildableGeneratorFuel_biomass_base & docs_json_ts_common_classes_FGBuildableGeneratorFuel & FGBuildableGenerator & FGBuildableGeneratorFuel_base;

type FGBuildableGeneratorFuel_coal = docs_json_ts_0_3_7_7_classes_base_FGBuildableGeneratorFuel_coal_base & docs_json_ts_common_classes_FGBuildableGeneratorFuel & FGBuildableGenerator & FGBuildableGeneratorFuel_base;

type FGBuildableGeneratorFuel_fuel = docs_json_ts_0_3_7_7_classes_base_FGBuildableGeneratorFuel_fuel_base & docs_json_ts_common_classes_FGBuildableGeneratorFuel & FGBuildableGenerator & FGBuildableGeneratorFuel_base;

type FGBuildableGeneratorGeoThermal = docs_json_ts_0_3_7_7_classes_base_FGBuildableGeneratorGeoThermal_base & docs_json_ts_common_classes_FGBuildableGeneratorGeoThermal & FGBuildableGenerator_no_fuel & FGBuildableGeneratorGeoThermal_base;

type FGBuildableGeneratorGeoThermal_base = {
	mVariablePowerProductionConstant: docs_json_ts_common_types_decimal_string,
	mVariablePowerProductionFactor: docs_json_ts_common_types_decimal_string,
	mVariablePowerProductionCycleLength: docs_json_ts_common_types_decimal_string,
	mMinPowerProduction: docs_json_ts_common_types_decimal_string,
	mMaxPowerProduction: docs_json_ts_common_types_decimal_string,
	mVariablePowerProductionCycleOffset: docs_json_ts_common_types_decimal_string,
};

type FGBuildableGeneratorNuclear = docs_json_ts_0_3_7_7_classes_base_FGBuildableGenerator_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableGenerator_no_fuel_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableGenerator_no_fuel_base_base_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableGeneratorNuclear_version_specific & docs_json_ts_common_classes_FGBuildableGeneratorNuclear & FGBuildableGenerator & FGBuildableGeneratorFuel_base & FGBuildableGeneratorNuclear_pre_1_0 & FGBuildableGeneratorNuclear_version_specific;

type FGBuildableGeneratorNuclear_pre_1_0 = {
	mDefaultFuelClasses: [
		docs_json_ts_0_4_2_11_properties_mDefaultFuelClasses_item_nuclear,
		...docs_json_ts_0_4_2_11_properties_mDefaultFuelClasses_item_nuclear[],
	],
};

type FGBuildableGeneratorNuclear_version_specific = {
	mCurrentGeneratorNuclearWarning: 'GNW_None',
};

type FGBuildableJumppad = docs_json_ts_0_3_7_7_classes_base_FGBuildableJumppad_base & docs_json_ts_common_classes_FGBuildableJumppad & FGBuildable_powered;

type FGBuildableLadder = docs_json_ts_0_3_7_7_classes_base_FGBuildableLadder_base & docs_json_ts_0_3_7_7_classes_base_has_mWidth & docs_json_ts_common_classes_FGBuildableLadder & FGBuildable_base;

type FGBuildableLightsControlPanel = docs_json_ts_common_classes_FGBuildableLightsControlPanel & FGBuildable_base & FGBuildable_light_related_thing_base & FGBuildableLightsControlPanel_version_specific;

type FGBuildableLightsControlPanel_version_specific = {
	mOnControlledBuildablesChanged: docs_json_ts_common_types_empty_object,
	mControlledBuildables: '',
	mIsBridgeConnected: docs_json_ts_common_types_bool_string,
	mConnections: '',
};

type FGBuildableLightSource = docs_json_ts_common_classes_FGBuildableLightSource & FGBuildable_base & FGBuildable_light_related_thing_base & FGBuildableLightSource_version_specific & has_mHasPower & has_mPowerConsumption;

type FGBuildableLightSource_version_specific = {
	mIsDay: docs_json_ts_common_types_bool_string,
};

type FGBuildableMAM = docs_json_ts_common_classes_FGBuildableMAM & FGBuildable_base & FGBuildable_occupied & FGBuildableMAM_version_specific;

type FGBuildableMAM_version_specific = {
	mSignificanceRange: docs_json_ts_common_types_decimal_string,
	mCurrentResearchState: 'ERS_NotResearching',
};

type FGBuildableManufacturer_base_blender = docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base & FGBuildableManufacturer_base_blender_base;

type FGBuildableManufacturer_base_blender_base = docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_base & FGBuildableManufacturer_base_blender_base_base;

type FGBuildableManufacturer_base_blender_base_base = docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_base_base & {
	mColor: '',
	mIsRadioActive: docs_json_ts_common_types_bool_string,
	mCurrentColorVFX: docs_json_ts_common_types_RGBA,
	m_NotifyNameREferences: [
		'Arm_04_ClawBase',
		'Arm_02_SFXSocket',
	],
};

type FGBuildableManufacturer_base_constructor = docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base & FGBuildableManufacturer_base_constructor_base;

type FGBuildableManufacturer_base_constructor_base = docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_base & FGBuildableManufacturer_base_constructor_base_base;

type FGBuildableManufacturer_base_constructor_base_base = docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_base_base & {
	mCurrentRecipeCheck: '',
	mPreviousRecipeCheck: '',
};

type FGBuildableManufacturer_Build_AssemblerMk1_C = docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_IsPowered & docs_json_ts_common_classes_FGBuildableManufacturer & FGBuildable_powered;

type FGBuildableManufacturer_Build_Blender_C = docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_IsPowered & docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_mProductionEffectsRunning & docs_json_ts_common_classes_FGBuildableManufacturer & FGBuildable_powered & FGBuildableManufacturer_base_blender;

type FGBuildableManufacturer_Build_ConstructorMk1_C = docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_IsPowered & docs_json_ts_common_classes_FGBuildableManufacturer & FGBuildable_powered & FGBuildableManufacturer_base_constructor;

type FGBuildableManufacturer_Build_FoundryMk1_C = docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_mProductionEffectsRunning & docs_json_ts_common_classes_FGBuildableManufacturer & FGBuildable_powered;

type FGBuildableManufacturer_Build_HadronCollider_C = docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_IsPowered & docs_json_ts_common_classes_FGBuildableManufacturerVariablePower & FGBuildable_powered & FGBuildableManufacturer_Build_HadronCollider_C_base & FGBuildableManufacturerVariablePower;

type FGBuildableManufacturer_Build_HadronCollider_C_base = {
	mSequenceDuration: docs_json_ts_common_types_decimal_string,
	mLightningTimer: docs_json_ts_common_types_empty_object,
	mGameTimeAtProducing: docs_json_ts_common_types_decimal_string,
	mCurrentProducingSeekTime: docs_json_ts_common_types_decimal_string,
	mStartVector_VFX_Small_Start: docs_json_ts_common_types_XYZ_decimal_string_list,
	mStartVector_VFX_Small_End: docs_json_ts_common_types_XYZ_decimal_string_list,
	mStartVector_VFX_Medium_Start: docs_json_ts_common_types_XYZ_decimal_string_list,
	mStartVector_VFX_Medium_End: docs_json_ts_common_types_XYZ_decimal_string_list,
	mStartVector_VFX_Large_Start: docs_json_ts_common_types_XYZ_decimal_string_list,
	mStartVector_VFX_Large_End: docs_json_ts_common_types_XYZ_decimal_string_list,
};

type FGBuildableManufacturer_Build_ManufacturerMk1_C = docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base & docs_json_ts_common_classes_FGBuildableManufacturer & FGBuildable_mStopped_audio_stuff & FGBuildable_powered;

type FGBuildableManufacturer_Build_OilRefinery_C = docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_IsPowered & docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_mProductionEffectsRunning & docs_json_ts_common_classes_FGBuildableManufacturer & FGBuildable_powered;

type FGBuildableManufacturer_Build_Packager_C = docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_IsPowered & docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_mProductionEffectsRunning & docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_packager & docs_json_ts_common_classes_FGBuildableManufacturer & FGBuildable_powered;

type FGBuildableManufacturer_Build_SmelterMk1_C = docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_mProductionEffectsRunning & docs_json_ts_common_classes_FGBuildableManufacturer & FGBuildable_powered;

type FGBuildableManufacturerVariablePower = {
	mEstimatedMininumPowerConsumption: docs_json_ts_common_types_decimal_string,
	mEstimatedMaximumPowerConsumption: docs_json_ts_common_types_decimal_string,
};

type FGBuildablePipeHyper = docs_json_ts_0_3_7_7_classes_base_has_mMeshLength & docs_json_ts_0_3_7_7_classes_base_has_mSplineData & docs_json_ts_common_classes_FGBuildablePipeHyper & FGBuildable_base;

type FGBuildablePipeline = docs_json_ts_0_3_7_7_classes_base_FGBuildablePipeline_base_root_quantized & docs_json_ts_0_3_7_7_classes_base_FGBuildablePipeline_base_spline & docs_json_ts_common_classes_FGBuildablePipeline & FGBuildable_base;

type FGBuildablePipeline_junction = FGBuildable_powered & FGBuildablePipeline_junction_base;

type FGBuildablePipeline_junction_base = docs_json_ts_0_3_7_7_classes_base_FGBuildable_powered_pre_1_0 & docs_json_ts_0_3_7_7_classes_base_FGBuildable_powered_version_specific & docs_json_ts_0_3_7_7_classes_base_FGBuildablePipeline_base_no_indicator_base & docs_json_ts_0_3_7_7_classes_base_has_mNumCyclesForProductivity & FGBuildablePipeline_junction_base_base;

type FGBuildablePipeline_junction_base_base = docs_json_ts_0_3_7_7_classes_base_FGBuildable_powered_pre_1_0 & docs_json_ts_0_3_7_7_classes_base_FGBuildable_powered_version_specific & docs_json_ts_0_3_7_7_classes_base_FGBuildablePipeline_base_no_indicator_base & docs_json_ts_0_3_7_7_classes_base_has_mNumCyclesForProductivity;

type FGBuildablePipelineJunction = docs_json_ts_common_classes_FGBuildablePipelineJunction & FGBuildablePipeline_junction & FGBuildablePipelineJunction_base;

type FGBuildablePipelineJunction_base = FGBuildablePipeline_junction_base & FGBuildablePipelineJunction_base_base;

type FGBuildablePipelineJunction_base_base = docs_json_ts_0_3_7_7_classes_base_FGBuildable_powered_pre_1_0 & docs_json_ts_0_3_7_7_classes_base_FGBuildable_powered_version_specific & docs_json_ts_0_3_7_7_classes_base_FGBuildablePipeline_base_no_indicator_base & FGBuildablePipeline_junction_base_base & FGBuildablePipelineJunction_base_base_base;

type FGBuildablePipelineJunction_base_base_base = {
	mFluidBoxVolume: docs_json_ts_common_types_decimal_string,
};

type FGBuildablePipelinePump_powered_base = docs_json_ts_0_3_7_7_classes_base_FGBuildablePipelinePump_powered_base_base & FGBuildable_powered;

type FGBuildablePipelinePump_pump = docs_json_ts_0_3_7_7_classes_base_FGBuildablePipeline_base & docs_json_ts_0_3_7_7_classes_base_FGBuildablePipeline_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildablePipelinePump_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildablePipelinePump_powered_version_specific & docs_json_ts_0_3_7_7_classes_base_FGBuildablePipelinePump_powered_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildablePipelinePump_pump_version_specific & docs_json_ts_common_classes_FGBuildablePipelinePump & FGBuildablePipelinePump_powered_base;

type FGBuildablePipelinePump_valve = docs_json_ts_0_3_7_7_classes_base_FGBuildablePipeline_base & docs_json_ts_0_3_7_7_classes_base_FGBuildablePipelinePump_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildablePipelinePump_powered_base_base & docs_json_ts_common_classes_FGBuildablePipelinePump & FGBuildable_powered;

type FGBuildablePipelineSupport = docs_json_ts_0_3_7_7_classes_base_FGBuildable_base_pre_update5 & docs_json_ts_0_3_7_7_classes_base_FGBuildable_with_mLength & docs_json_ts_0_3_7_7_classes_base_FGBuildablePipelineSupport_base & docs_json_ts_0_3_7_7_classes_base_has_mCanStack & docs_json_ts_0_3_7_7_classes_base_has_mStackHeight & docs_json_ts_0_3_7_7_classes_base_has_mUseStaticHeight & docs_json_ts_common_classes_FGBuildablePipelineSupport & FGBuildable_base;

type FGBuildablePipeReservoir = docs_json_ts_0_3_7_7_classes_base_FGBuildablePipeReservoir_base & docs_json_ts_common_classes_FGBuildablePipeReservoir & FGBuildable_powered;

type FGBuildablePole = docs_json_ts_0_3_7_7_classes_base_has_mCanStack & docs_json_ts_0_3_7_7_classes_base_has_mHeight & docs_json_ts_0_3_7_7_classes_base_has_mStackHeight & docs_json_ts_0_3_7_7_classes_base_has_mUseStaticHeight & docs_json_ts_common_classes_FGBuildablePole & FGBuildable_base;

type FGBuildablePowerPole = docs_json_ts_0_3_7_7_classes_base_FGBuildablePowerPole & FGBuildable_base & has_mHasPower;

type FGBuildablePowerStorage = docs_json_ts_common_classes_FGBuildablePowerStorage & FGBuildable_powered & FGBuildablePowerStorage_base;

type FGBuildablePowerStorage_base = {
	m_PreviousBatteryStatus: 'BS_Idle',
	mCurrentGameTimeSinceStateChange: docs_json_ts_common_types_decimal_string,
	mActivationEventID: docs_json_ts_common_types_integer_string,
	mBatteryStatus: 'BS_Idle',
	mPowerStore: docs_json_ts_common_types_decimal_string,
	mPowerStoreCapacity: docs_json_ts_common_types_decimal_string,
	mPowerInputCapacity: docs_json_ts_common_types_decimal_string,
	mIndicatorLevelMax: docs_json_ts_common_types_integer_string,
	mIndicatorLevel: docs_json_ts_common_types_integer_string,
};

type FGBuildableRadarTower = docs_json_ts_0_3_7_7_classes_base_FGBuildableRadarTower_base & docs_json_ts_common_classes_FGBuildableRadarTower & FGBuildable_powered;

type FGBuildableRailroadStation = docs_json_ts_0_3_7_7_classes_base_FGBuildableRailroadStation_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableTrainPlatform_base & docs_json_ts_common_classes_FGBuildableRailroadStation & FGBuildable_powered;

type FGBuildableRailroadTrack = docs_json_ts_common_classes_FGBuildableRailroadTrack & FGBuildable_base & FGBuildableRailroadTrack_base;

type FGBuildableRailroadTrack_base = docs_json_ts_0_3_7_7_classes_base_FGBuildableRailroadTrack & FGBuildableRailroadTrack_base_base;

type FGBuildableRailroadTrack_base_base = docs_json_ts_0_3_7_7_classes_base_FGBuildableRailroadTrack_base & {
	mConnections: [
		docs_json_ts_0_4_2_11_properties_FGRailroadTrackConnectionComponent_quoted,
		...docs_json_ts_0_4_2_11_properties_FGRailroadTrackConnectionComponent_quoted[],
	],
};

type FGBuildableResourceExtractor_base = docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_base & FGBuildable_powered_has_mAllowedResourceForms;

type FGBuildableResourceExtractor_miner_mk1 = docs_json_ts_common_classes_FGBuildableResourceExtractor & FGBuildableResourceExtractor_base & FGBuildableResourceExtractor_miner_mk1_base;

type FGBuildableResourceExtractor_miner_mk1_base = docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_miner & FGBuildableResourceExtractor_miner_mk1_base_base;

type FGBuildableResourceExtractor_miner_mk1_base_base = docs_json_ts_0_3_7_7_classes_base_FGBuildable_powered_base_resources_base & docs_json_ts_0_3_7_7_classes_base_overridable_FGBuildableResourceExtractor_miner_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_miner_base & docs_json_ts_0_3_7_7_classes_base_overridable_FGBuildableResourceExtractor_only_allow_certain_resources & docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_piped & docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_piped_pre_1_0 & docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_timed & FGBuildableResourceExtractor_miner_mk1_version_specific;

type FGBuildableResourceExtractor_miner_mk1_version_specific = {
	CanPlayAfterStartUpStopped: docs_json_ts_common_types_bool_string,
	mDisplayName: Exclude<string, ''>,
};

type FGBuildableResourceExtractor_miner_mk2 = docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_miner_mk2_base & docs_json_ts_common_classes_FGBuildableResourceExtractor & FGBuildable_powered;

type FGBuildableResourceExtractor_miner_mk3 = docs_json_ts_0_3_7_7_classes_base_FGBuildable_powered_base_resources_base & docs_json_ts_0_3_7_7_classes_base_FGBuildable_powered_pre_1_0 & docs_json_ts_0_3_7_7_classes_base_FGBuildable_powered_version_specific & docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_miner & docs_json_ts_0_3_7_7_classes_base_overridable_FGBuildableResourceExtractor_miner_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_miner_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_miner_mk3_version_specific & docs_json_ts_0_3_7_7_classes_base_overridable_FGBuildableResourceExtractor_only_allow_certain_resources & docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_piped & docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_piped_pre_1_0 & docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_timed & docs_json_ts_0_3_7_7_classes_base_has_mNumCyclesForProductivity & docs_json_ts_common_classes_FGBuildableResourceExtractor & FGBuildable_powered;

type FGBuildableResourceExtractor_oil = docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_oil_base & docs_json_ts_common_classes_FGBuildableResourceExtractor & FGBuildable_powered;

type FGBuildableResourceExtractor_water = docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_water_base & docs_json_ts_common_classes_FGBuildableResourceExtractor & FGBuildable_powered & FGBuildableResourceExtractor_water_base;

type FGBuildableResourceExtractor_water_base = {
	mMinimumDepthForPlacement: docs_json_ts_common_types_decimal_string,
	mDepthTraceOriginOffset: docs_json_ts_common_types_XYZ_decimal_string,
};

type FGBuildableResourceSink = docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceSink_base & docs_json_ts_common_classes_FGBuildableResourceSink & FGBuildable_powered & FGBuildableResourceSink_base;

type FGBuildableResourceSink_base = docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceSink_base_base & FGBuildableResourceSink_base_base;

type FGBuildableResourceSink_base_base = docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceSink_base_base_base & {
	IsAnimationProducing: docs_json_ts_common_types_bool_string,
	EnableTickGrinder: docs_json_ts_common_types_bool_string,
	EnableTickEngine: docs_json_ts_common_types_bool_string,
	mGrinderInterpDuration: docs_json_ts_common_types_decimal_string,
	mEngineInterpDuration: docs_json_ts_common_types_decimal_string,
	mProducingTimer: docs_json_ts_common_types_decimal_string,
};

type FGBuildableResourceSinkShop = docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceSinkShop_base & docs_json_ts_common_classes_FGBuildableResourceSinkShop & FGBuildable_powered;

type FGBuildableSnowDispenser = docs_json_ts_common_classes_FGBuildableSnowDispenser & FGBuildable_base;

type FGBuildableSpaceElevator = docs_json_ts_0_3_7_7_classes_base_FGBuildableSpaceElevator_base & docs_json_ts_common_classes_FGBuildableSpaceElevator & FGBuildable_powered;

type FGBuildableSplitterSmart = docs_json_ts_0_3_7_7_classes_base_FGBuildable_powered_pre_1_0 & docs_json_ts_0_3_7_7_classes_base_FGBuildable_powered_version_specific & docs_json_ts_0_3_7_7_classes_base_FGBuildableAttachment_has_mCurrentInventoryIndex & docs_json_ts_0_3_7_7_classes_base_FGBuildableAttachment_splitter_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableAttachment_splitter_base_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableSplitterSmart_version_specific & docs_json_ts_0_3_7_7_classes_base_has_mNumCyclesForProductivity & docs_json_ts_common_classes_FGBuildableSplitterSmart & FGBuildable_powered;

type FGBuildableStair = docs_json_ts_0_3_7_7_classes_base_has_mDisableAttachmentSnapOn & docs_json_ts_0_3_7_7_classes_base_has_mDisableSnapOn & docs_json_ts_0_3_7_7_classes_base_has_mElevation & docs_json_ts_0_3_7_7_classes_base_has_mHeight & docs_json_ts_0_3_7_7_classes_base_has_mSize & docs_json_ts_common_classes_FGBuildableStair & FGBuildable_base;

type FGBuildableStorage = docs_json_ts_0_3_7_7_classes_base_FGBuildableStorage_base & docs_json_ts_common_classes_FGBuildableResourceExtractor & FGBuildable_powered;

type FGBuildableTradingPost = docs_json_ts_0_3_7_7_classes_base_FGBuildable_powered_pre_1_0 & docs_json_ts_0_3_7_7_classes_base_FGBuildable_powered_version_specific & docs_json_ts_0_3_7_7_classes_base_FGBuildableTradingPost_pre_1_0 & docs_json_ts_0_3_7_7_classes_base_FGBuildableTradingPost_pre_update5 & docs_json_ts_0_3_7_7_classes_base_FGBuildableTradingPost_pre_update8 & docs_json_ts_0_3_7_7_classes_base_FGBuildableTradingPost_version_specific & docs_json_ts_0_3_7_7_classes_base_has_mNumCyclesForProductivity & docs_json_ts_common_classes_FGBuildableTradingPost & FGBuildable_powered & FGBuildableTradingPost_base & FGBuildableTradingPost_base_pre_1_0 & FGBuildableTradingPost_base_version_specific;

type FGBuildableTradingPost_base = {
	mMamFreeText: 'Use MAM',
	mMamOccupiedText: 'MAM is occupied',
};

type FGBuildableTradingPost_base_pre_1_0 = {
	mMeshes: [
		docs_json_ts_0_4_2_11_properties_mMeshes_item,
		docs_json_ts_0_4_2_11_properties_mMeshes_item,
		docs_json_ts_0_4_2_11_properties_mMeshes_item,
		docs_json_ts_0_4_2_11_properties_mMeshes_item,
		docs_json_ts_0_4_2_11_properties_mMeshes_item,
		docs_json_ts_0_4_2_11_properties_mMeshes_item,
		...docs_json_ts_0_4_2_11_properties_mMeshes_item[],
	],
};

type FGBuildableTradingPost_base_version_specific = {
	ABClass: '/Game/FactoryGame/Buildable/Factory/TradingPost/BPA_Tradingpost.BPA_Tradingpost_C',
	mSkeletalMeshSoftPtr: '/Game/FactoryGame/Buildable/Factory/TradingPost/Mesh/SK_Tradingpost.SK_Tradingpost',
};

type FGBuildableTrainPlatform_with_storage = docs_json_ts_0_3_7_7_classes_base_FGBuildableTrainPlatform_with_storage_base & FGBuildable_powered_storage;

type FGBuildableTrainPlatformCargo = docs_json_ts_0_3_7_7_classes_base_FGBuildableTrainPlatformCargo_base & docs_json_ts_common_classes_FGBuildableTrainPlatformCargo & FGBuildableTrainPlatform_with_storage;

type FGBuildableTrainPlatformEmpty = docs_json_ts_0_3_7_7_classes_base_FGBuildableTrainPlatform_base & docs_json_ts_common_classes_FGBuildableTrainPlatformEmpty & FGBuildable_powered;

type FGBuildableWalkway = docs_json_ts_0_3_7_7_classes_base_has_mDisableSnapOn & docs_json_ts_0_3_7_7_classes_base_has_mElevation & docs_json_ts_0_3_7_7_classes_base_has_mSize & docs_json_ts_common_classes_FGBuildableWalkway & FGBuildable_base;

type FGBuildableWall = docs_json_ts_0_3_7_7_classes_base_has_mHeight & docs_json_ts_0_3_7_7_classes_base_has_mWidth & docs_json_ts_common_classes_FGBuildableWall & FGBuildable_base;

type FGBuildableWire = docs_json_ts_0_3_7_7_classes_base_FGBuildableWire & FGBuildable_base;

type FGBuildingDescriptor = docs_json_ts_common_classes_FGBuildingDescriptor & FGDescriptor_BuildMenu;

type FGColorGun = docs_json_ts_0_3_7_7_classes_base_FGColorGun_base & docs_json_ts_0_3_7_7_classes_base_FGWeaponProjectile_instant & docs_json_ts_common_classes_FGColorGun & FGWeaponProjectile;

type FGConsumableDescriptor = docs_json_ts_0_3_7_7_classes_base_FGConsumableDescriptor_base & docs_json_ts_common_classes_FGConsumableDescriptor & FGDescriptor_sinkable;

type FGConsumableEquipment = docs_json_ts_0_3_7_7_classes_base_FGConsumableEquipment_pre_update8 & docs_json_ts_0_3_7_7_classes_base_FGConsumableEquipment_version_specific & docs_json_ts_0_3_7_7_classes_base_FGEquipment & docs_json_ts_0_3_7_7_classes_base_FGEquipment_base & docs_json_ts_common_classes_FGConsumableEquipment & FGConsumableEquipment_version_specific;

type FGConsumableEquipment_version_specific = {
	mArmAnimation: 'AE_Consumables' | 'AE_OneHandEquipment' | 'AE_Generic1Hand',
};

type FGConveyorPoleStackable = docs_json_ts_0_3_7_7_classes_base_has_mCanStack & docs_json_ts_0_3_7_7_classes_base_has_mHeight & docs_json_ts_0_3_7_7_classes_base_has_mStackHeight & docs_json_ts_0_3_7_7_classes_base_has_mUseStaticHeight & docs_json_ts_common_classes_FGBuildablePole & docs_json_ts_common_classes_FGConveyorPoleStackable & FGBuildable_base;

type FGDescriptor = FGDescriptor_base & {
	mPersistentBigIcon: docs_json_ts_0_4_2_11_properties_Texture2D | 'None',
	mSmallIcon: docs_json_ts_0_4_2_11_properties_Texture2D | 'None',
};

type FGDescriptor_base = docs_json_ts_0_3_7_7_classes_base_FGDescriptor_base & {
	mForm: docs_json_ts_0_4_2_11_properties_mForm,
	mGasColor: docs_json_ts_common_types_BGRA,
};

type FGDescriptor_BuildMenu = FGDescriptor & FGDescriptor_BuildMenu_base;

type FGDescriptor_BuildMenu_base = docs_json_ts_0_3_7_7_classes_base_FGDescriptor_BuildMenu_base & FGDescriptor_base;

type FGDescriptor_sinkable = docs_json_ts_0_3_7_7_classes_base_FGDescriptor_base & docs_json_ts_0_3_7_7_classes_base_has_mResourceSinkPoints & FGDescriptor;

type FGEquipment = docs_json_ts_0_3_7_7_classes_base_FGEquipment_base & FGEquipment_base;

type FGEquipment_base = docs_json_ts_0_3_7_7_classes_base_FGEquipment_has_mUseDefaultPrimaryFire & docs_json_ts_0_3_7_7_classes_base_FGEquipment_pre_1_0 & docs_json_ts_0_3_7_7_classes_base_overridable_FGEquipment_version_specific & docs_json_ts_common_classes_base_hasClassName & FGEquipment_version_specific;

type FGEquipment_version_specific = {
	mAttachSocket: 'None' | 'hand_rSocket' | 'hand_lSocket' | 'jumpingStilt_lSocket' | 'helmetSocket' | 'root',
};

type FGEquipmentDescriptor = docs_json_ts_common_classes_FGEquipmentDescriptor & FGDescriptor_sinkable;

type FGEquipmentZipline = docs_json_ts_common_classes_FGEquipmentZipline & FGEquipment & FGEquipmentZipline_pre_1_0 & FGEquipmentZipline_version_specific;

type FGEquipmentZipline_pre_1_0 = {
	mShouldPlayDeactivateSound: docs_json_ts_common_types_bool_string,
};

type FGEquipmentZipline_version_specific = {
	mZiplineJumpLaunchVelocity: docs_json_ts_common_types_decimal_string,
	mMaxZiplineAngle: docs_json_ts_common_types_decimal_string,
	mTraceDistance: docs_json_ts_common_types_decimal_string,
	mTraceStartOffset: docs_json_ts_common_types_decimal_string,
	mTraceRadius: docs_json_ts_common_types_decimal_string,
	mVisualizeTraceDistance: docs_json_ts_common_types_bool_string,
	mZiplineReattachCooldown: docs_json_ts_common_types_decimal_string,
	mEquipmentSlot: 'ES_ARMS',
	mAttachSocket: 'hand_rSocket',
	mArmAnimation: 'AE_Generic1Hand',
	mBackAnimation: 'BE_None',
};

type FGHoverPack = docs_json_ts_common_classes_FGHoverPack & FGEquipment & FGHoverPack_pre_1_0 & FGHoverPack_pre_update6 & FGHoverPack_version_specific;

type FGHoverPack_pre_1_0 = {
	mHoverPackActiveTimer: docs_json_ts_common_types_empty_object,
	mCurrentPlayerVelocity: docs_json_ts_common_types_decimal_string,
	mCurrentMouseDelta: docs_json_ts_common_types_decimal_string,
	mHoverpackJoystickTimer: docs_json_ts_common_types_empty_object,
	mCurrentBatteryPowerLevel: docs_json_ts_common_types_decimal_string,
	m_PreviousHoverMode: 'HPM_Inactive',
};

type FGHoverPack_pre_update6 = {
	mRailRoadSurfSpeed: docs_json_ts_common_types_decimal_string,
	mRailroadSurfSensitivity: docs_json_ts_common_types_decimal_string,
};

type FGHoverPack_version_specific = {
	ConnectionLocationUpdatedDelegate: docs_json_ts_common_types_empty_object,
	ConnectionStatusUpdatedDelegate: docs_json_ts_common_types_empty_object,
	HoverModeChangedDelegate: docs_json_ts_common_types_empty_object,
	RangeWarningToggleDelegate: docs_json_ts_common_types_empty_object,
	mHoverSpeed: docs_json_ts_common_types_decimal_string,
	mHoverAccelerationSpeed: docs_json_ts_common_types_decimal_string,
	mHoverSprintMultiplier: docs_json_ts_common_types_decimal_string,
	mHoverFriction: docs_json_ts_common_types_decimal_string,
	mJumpKeyHoldActivationTime: docs_json_ts_common_types_decimal_string,
	mFallSpeedLimitWhenPowered: docs_json_ts_common_types_decimal_string,
	mPowerConnectionSearchRadius: docs_json_ts_common_types_decimal_string,
	mPowerConnectionSearchTickRate: docs_json_ts_common_types_decimal_string,
	mPowerConnectionDisconnectionTime: docs_json_ts_common_types_decimal_string,
	mPowerCapacity: docs_json_ts_common_types_decimal_string,
	mPowerDrainRate: docs_json_ts_common_types_decimal_string,
	mPowerConsumption: docs_json_ts_common_types_decimal_string,
	mCurrentPowerLevel: docs_json_ts_common_types_decimal_string,
	mRangeWarningNormalizedDistanceThreshold: docs_json_ts_common_types_decimal_string,
	mCurrentHoverMode: 'HPM_Inactive',
	mHasConnection: docs_json_ts_common_types_bool_string,
	mShouldAutomaticallyHoverWhenConnected: docs_json_ts_common_types_bool_string,
	mCrouchHoverCancelTime: docs_json_ts_common_types_decimal_string,
	mCharacterUseDistanceWhenActive: docs_json_ts_common_types_decimal_string,
	mCurrentConnectionLocation: docs_json_ts_common_types_XYZ_decimal_string,
	mEquipmentSlot: 'ES_BACK',
	mAttachSocket: 'root',
	mArmAnimation: 'AE_None',
	mBackAnimation: 'BE_Jetpack',
};

type FGItemDescriptor = docs_json_ts_common_classes_FGItemDescriptor & FGDescriptor_sinkable;

type FGItemDescriptorBiomass = docs_json_ts_common_classes_FGItemDescriptorBiomass & FGDescriptor_sinkable;

type FGNobeliskDetonator = docs_json_ts_0_3_7_7_classes_base_FGNobeliskDetonator_base & docs_json_ts_0_3_7_7_classes_base_FGWeaponProjectile_thrown & docs_json_ts_common_classes_FGNobeliskDetonator & FGWeaponProjectile;

type FGParachute = docs_json_ts_0_3_7_7_classes_base_FGParachute_has_mIsDeployed & docs_json_ts_0_3_7_7_classes_base_FGParachute_has_mTerminalVelocityZ & docs_json_ts_common_classes_FGParachute & FGEquipment;

type FGPipeHyperStart = docs_json_ts_0_3_7_7_classes_base_FGBuildable_powered_pre_1_0 & docs_json_ts_0_3_7_7_classes_base_FGBuildable_powered_version_specific & docs_json_ts_0_3_7_7_classes_base_FGBuildable_with_mLength & docs_json_ts_0_3_7_7_classes_base_FGPipeHyperStart_base & docs_json_ts_0_3_7_7_classes_base_has_mCanStack & docs_json_ts_0_3_7_7_classes_base_has_mNumCyclesForProductivity & docs_json_ts_0_3_7_7_classes_base_has_mStackHeight & docs_json_ts_0_3_7_7_classes_base_has_mUseStaticHeight & docs_json_ts_common_classes_FGPipeHyperStart & FGBuildable_powered;

type FGPoleDescriptor = docs_json_ts_common_classes_FGPoleDescriptor & FGDescriptor_BuildMenu;

type FGPortableMinerDispenser = docs_json_ts_0_3_7_7_classes_base_FGEquipment_dispenser & docs_json_ts_0_3_7_7_classes_base_FGPortableMinerDispenser_version_specific & docs_json_ts_common_classes_FGPortableMinerDispenser & FGPortableMinerDispenser_version_specific;

type FGPortableMinerDispenser_version_specific = {
	mArmAnimation: 'AE_Generic2Hand',
};

type FGRecipe = docs_json_ts_0_3_7_7_classes_base_FGRecipe_pre_update5 & docs_json_ts_0_3_7_7_classes_base_FGRecipe_version_specific & docs_json_ts_common_classes_FGRecipe & FGRecipe_pre_update6 & FGRecipe_version_specific;

type FGRecipe_pre_update6 = {
	mProducedIn: docs_json_ts_0_4_2_11_properties_mProducedIn,
};

type FGRecipe_version_specific = {
	mManufacturingMenuPriority: docs_json_ts_common_types_decimal_string,
	mVariablePowerConsumptionConstant: docs_json_ts_common_types_decimal_string,
	mVariablePowerConsumptionFactor: docs_json_ts_common_types_decimal_string,
};

type FGResourceDescriptor = docs_json_ts_0_3_7_7_classes_base_FGResourceDescriptor_base & docs_json_ts_common_classes_FGResourceDescriptor & FGDescriptor_sinkable;

type FGSchematic = docs_json_ts_0_4_2_11_classes_base_overridable_FGSchematic_base & docs_json_ts_0_4_2_11_classes_base_overridable_FGSchematic_version_specific & docs_json_ts_common_classes_FGSchematic & docs_json_ts_common_classes_base_isDescribed & FGSchematic_has_mMenuPriority & FGSchematic_has_mSmallSchematicIcon & FGSchematic_has_mTechTier & FGSchematic_has_mUnlocks;

type FGSchematic_has_mMenuPriority = {
	mMenuPriority: docs_json_ts_common_types_decimal_string,
};

type FGSchematic_has_mSmallSchematicIcon = {
	mSmallSchematicIcon: 'None' | docs_json_ts_0_3_7_7_properties_Texture2D_base,
};

type FGSchematic_has_mTechTier = {
	mTechTier: docs_json_ts_0_4_2_11_properties_Tier,
};

type FGSchematic_has_mUnlocks = {
	mUnlocks: [
		...docs_json_ts_0_3_7_7_properties_mUnlocks_item_base[],
	],
};

type FGSnowballWeapon = docs_json_ts_0_3_7_7_classes_base_FGSnowballWeapon_version_specific & docs_json_ts_0_3_7_7_classes_base_FGWeaponProjectile_thrown & docs_json_ts_common_classes_FGSnowballWeapon & FGWeaponProjectile;

type FGVehicleDescriptor_Desc_CyberWagon_C = docs_json_ts_common_classes_FGVehicleDescriptor & FGVehicleDescriptor_fueled_with_inventory;

type FGVehicleDescriptor_Desc_DroneTransport_C = docs_json_ts_common_classes_FGVehicleDescriptor & FGVehicleDescriptor_with_inventory;

type FGVehicleDescriptor_Desc_Explorer_C = docs_json_ts_common_classes_FGVehicleDescriptor & FGVehicleDescriptor_fueled_with_inventory;

type FGVehicleDescriptor_Desc_FreightWagon_C = docs_json_ts_common_classes_FGVehicleDescriptor & FGVehicleDescriptor_with_inventory;

type FGVehicleDescriptor_Desc_Locomotive_C = docs_json_ts_common_classes_FGVehicleDescriptor & FGVehicleDescriptor_powered;

type FGVehicleDescriptor_Desc_Tractor_C = docs_json_ts_common_classes_FGVehicleDescriptor & FGVehicleDescriptor_fueled_with_inventory;

type FGVehicleDescriptor_Desc_Truck_C = docs_json_ts_common_classes_FGVehicleDescriptor & FGVehicleDescriptor_fueled_with_inventory;

type FGVehicleDescriptor_fueled = FGDescriptor_BuildMenu & FGVehicleDescriptor_fueled_base;

type FGVehicleDescriptor_fueled_with_inventory = FGVehicleDescriptor_fueled & FGVehicleDescriptor_with_inventory;

type FGVehicleDescriptor_fueled_with_inventory_base = FGVehicleDescriptor_fueled_base & has_mInventorySize;

type FGVehicleDescriptor_fueled_base = FGDescriptor & {
	mFuelConsumption: docs_json_ts_common_types_decimal_string,
};

type FGVehicleDescriptor_powered = FGDescriptor_BuildMenu & FGVehicleDescriptor_powered_base;

type FGVehicleDescriptor_powered_base = FGDescriptor & {
	mPowerConsumption: {
		Min: docs_json_ts_common_types_decimal_string,
		Max: docs_json_ts_common_types_decimal_string,
	},
};

type FGVehicleDescriptor_with_inventory = FGDescriptor_BuildMenu & has_mInventorySize;

type FGWeapon_Equip_RebarGun_Projectile_C = docs_json_ts_0_3_7_7_classes_base_FGWeaponProjectile_base & docs_json_ts_0_3_7_7_classes_base_FGWeaponProjectile_has_mAttachSocket & docs_json_ts_0_3_7_7_classes_base_FGWeaponProjectileFire_base_random & docs_json_ts_0_3_7_7_classes_base_FGWeaponProjectileFire_base_version_specific & docs_json_ts_common_classes_FGWeapon_Equip_RebarGun_Projectile_C & FGWeaponProjectile & FGWeaponProjectile_base & FGWeaponProjectileFire_has_mMuteDryFire;

type FGWeapon_Equip_Rifle_C = docs_json_ts_0_3_7_7_classes_base_FGWeaponInstantFire_base & docs_json_ts_0_3_7_7_classes_base_FGWeaponProjectile_instant & docs_json_ts_common_classes_FGWeapon_Equip_Rifle_C & FGWeaponProjectile;

type FGWeaponProjectile = docs_json_ts_0_3_7_7_classes_base_FGWeaponProjectile & FGWeaponProjectile_base;

type FGWeaponProjectile_base = docs_json_ts_0_3_7_7_classes_base_FGEquipment_base & docs_json_ts_0_3_7_7_classes_base_FGWeaponProjectile_base & FGWeaponProjectile_has_mBlockSprintWhenFiring;

type FGWeaponProjectile_has_mBlockSprintWhenFiring = {
	mBlockSprintWhenFiring: docs_json_ts_common_types_bool_string,
};

type FGWeaponProjectileFire_has_mMuteDryFire = {
	mMuteDryFire: docs_json_ts_common_types_bool_string,
};

export type {
	has_mHasPower,
	has_mInventorySize,
	has_mPowerConsumption,
	FGBuildable_base,
	FGBuildable_base_pre_update5,
	FGBuildable_base_pre_update8,
	FGBuildable_base_version_specific,
	FGBuildable_docking_station,
	FGBuildable_has_mCachedSkeletalMeshes,
	FGBuildable_light_related_thing_base,
	FGBuildable_mStopped_audio_stuff,
	FGBuildable_occupied,
	FGBuildable_powered,
	FGBuildable_powered_has_mAllowedResourceForms,
	FGBuildable_powered_has_mAllowedResourceForms_base,
	FGBuildable_powered_has_mAllowedResourceForms_with_resources,
	FGBuildable_powered_has_mAllowedResourceForms_with_resources_base,
	FGBuildable_powered_has_mAllowedResourceForms_with_resources_base_base,
	FGBuildable_powered_version_specific,
	FGBuildable_powered_storage,
	FGBuildable_powered_storage_base,
	FGBuildable_tiered,
	FGBuildable_unoccupied_and_untiered,
	FGBuildableAttachment,
	FGBuildableAttachmentMerger,
	FGBuildableAttachmentSplitter,
	FGBuildableCircuitSwitch,
	FGBuildableCircuitSwitch_base,
	FGBuildableConveyorBelt_spline,
	FGBuildableConveyorLift,
	FGBuildableDockingStation,
	FGBuildableDroneStation,
	FGBuildableDroneStation_pre_1_0,
	FGBuildableDroneStation_pre_update5,
	FGBuildableDroneStation_version_specific,
	FGBuildableFactory_jump_pad,
	FGBuildableFactory_landing_pad,
	FGBuildableFactory_not_a_pad,
	FGBuildableFactorySimpleProducer,
	FGBuildableFloodlight,
	FGBuildableFloodlight_version_specific,
	FGBuildableFoundation,
	FGBuildableFrackingActivator,
	FGBuildableFrackingActivator_base,
	FGBuildableFrackingActivator_version_specific,
	FGBuildableFrackingExtractor,
	FGBuildableGenerator,
	FGBuildableGenerator_no_fuel,
	FGBuildableGeneratorFuel_base,
	FGBuildableGeneratorFuel_base_base,
	FGBuildableGeneratorFuel_base_base_base,
	FGBuildableGeneratorFuel_biomass,
	FGBuildableGeneratorFuel_coal,
	FGBuildableGeneratorFuel_fuel,
	FGBuildableGeneratorGeoThermal,
	FGBuildableGeneratorGeoThermal_base,
	FGBuildableGeneratorNuclear,
	FGBuildableGeneratorNuclear_pre_1_0,
	FGBuildableGeneratorNuclear_version_specific,
	FGBuildableJumppad,
	FGBuildableLadder,
	FGBuildableLightsControlPanel,
	FGBuildableLightsControlPanel_version_specific,
	FGBuildableLightSource,
	FGBuildableLightSource_version_specific,
	FGBuildableMAM,
	FGBuildableMAM_version_specific,
	FGBuildableManufacturer_base_blender,
	FGBuildableManufacturer_base_blender_base,
	FGBuildableManufacturer_base_blender_base_base,
	FGBuildableManufacturer_base_constructor,
	FGBuildableManufacturer_base_constructor_base,
	FGBuildableManufacturer_base_constructor_base_base,
	FGBuildableManufacturer_Build_AssemblerMk1_C,
	FGBuildableManufacturer_Build_Blender_C,
	FGBuildableManufacturer_Build_ConstructorMk1_C,
	FGBuildableManufacturer_Build_FoundryMk1_C,
	FGBuildableManufacturer_Build_HadronCollider_C,
	FGBuildableManufacturer_Build_HadronCollider_C_base,
	FGBuildableManufacturer_Build_ManufacturerMk1_C,
	FGBuildableManufacturer_Build_OilRefinery_C,
	FGBuildableManufacturer_Build_Packager_C,
	FGBuildableManufacturer_Build_SmelterMk1_C,
	FGBuildableManufacturerVariablePower,
	FGBuildablePipeHyper,
	FGBuildablePipeline,
	FGBuildablePipeline_junction,
	FGBuildablePipeline_junction_base,
	FGBuildablePipeline_junction_base_base,
	FGBuildablePipelineJunction,
	FGBuildablePipelineJunction_base,
	FGBuildablePipelineJunction_base_base,
	FGBuildablePipelineJunction_base_base_base,
	FGBuildablePipelinePump_powered_base,
	FGBuildablePipelinePump_pump,
	FGBuildablePipelinePump_valve,
	FGBuildablePipelineSupport,
	FGBuildablePipeReservoir,
	FGBuildablePole,
	FGBuildablePowerPole,
	FGBuildablePowerStorage,
	FGBuildablePowerStorage_base,
	FGBuildableRadarTower,
	FGBuildableRailroadStation,
	FGBuildableRailroadTrack,
	FGBuildableRailroadTrack_base,
	FGBuildableRailroadTrack_base_base,
	FGBuildableResourceExtractor_base,
	FGBuildableResourceExtractor_miner_mk1,
	FGBuildableResourceExtractor_miner_mk1_base,
	FGBuildableResourceExtractor_miner_mk1_base_base,
	FGBuildableResourceExtractor_miner_mk1_version_specific,
	FGBuildableResourceExtractor_miner_mk2,
	FGBuildableResourceExtractor_miner_mk3,
	FGBuildableResourceExtractor_oil,
	FGBuildableResourceExtractor_water,
	FGBuildableResourceExtractor_water_base,
	FGBuildableResourceSink,
	FGBuildableResourceSink_base,
	FGBuildableResourceSink_base_base,
	FGBuildableResourceSinkShop,
	FGBuildableSnowDispenser,
	FGBuildableSpaceElevator,
	FGBuildableSplitterSmart,
	FGBuildableStair,
	FGBuildableStorage,
	FGBuildableTradingPost,
	FGBuildableTradingPost_base,
	FGBuildableTradingPost_base_pre_1_0,
	FGBuildableTradingPost_base_version_specific,
	FGBuildableTrainPlatform_with_storage,
	FGBuildableTrainPlatformCargo,
	FGBuildableTrainPlatformEmpty,
	FGBuildableWalkway,
	FGBuildableWall,
	FGBuildableWire,
	FGBuildingDescriptor,
	FGColorGun,
	FGConsumableDescriptor,
	FGConsumableEquipment,
	FGConsumableEquipment_version_specific,
	FGConveyorPoleStackable,
	FGDescriptor,
	FGDescriptor_base,
	FGDescriptor_BuildMenu,
	FGDescriptor_BuildMenu_base,
	FGDescriptor_sinkable,
	FGEquipment,
	FGEquipment_base,
	FGEquipment_version_specific,
	FGEquipmentDescriptor,
	FGEquipmentZipline,
	FGEquipmentZipline_pre_1_0,
	FGEquipmentZipline_version_specific,
	FGHoverPack,
	FGHoverPack_pre_1_0,
	FGHoverPack_pre_update6,
	FGHoverPack_version_specific,
	FGItemDescriptor,
	FGItemDescriptorBiomass,
	FGNobeliskDetonator,
	FGParachute,
	FGPipeHyperStart,
	FGPoleDescriptor,
	FGPortableMinerDispenser,
	FGPortableMinerDispenser_version_specific,
	FGRecipe,
	FGRecipe_pre_update6,
	FGRecipe_version_specific,
	FGResourceDescriptor,
	FGSchematic,
	FGSchematic_has_mMenuPriority,
	FGSchematic_has_mSmallSchematicIcon,
	FGSchematic_has_mTechTier,
	FGSchematic_has_mUnlocks,
	FGSnowballWeapon,
	FGVehicleDescriptor_Desc_CyberWagon_C,
	FGVehicleDescriptor_Desc_DroneTransport_C,
	FGVehicleDescriptor_Desc_Explorer_C,
	FGVehicleDescriptor_Desc_FreightWagon_C,
	FGVehicleDescriptor_Desc_Locomotive_C,
	FGVehicleDescriptor_Desc_Tractor_C,
	FGVehicleDescriptor_Desc_Truck_C,
	FGVehicleDescriptor_fueled,
	FGVehicleDescriptor_fueled_with_inventory,
	FGVehicleDescriptor_fueled_with_inventory_base,
	FGVehicleDescriptor_fueled_base,
	FGVehicleDescriptor_powered,
	FGVehicleDescriptor_powered_base,
	FGVehicleDescriptor_with_inventory,
	FGWeapon_Equip_RebarGun_Projectile_C,
	FGWeapon_Equip_Rifle_C,
	FGWeaponProjectile,
	FGWeaponProjectile_base,
	FGWeaponProjectile_has_mBlockSprintWhenFiring,
	FGWeaponProjectileFire_has_mMuteDryFire,
};
