/* eslint-disable @stylistic/max-len */

import type {
	bool_string as docs_json_ts_common_types_bool_string,
	decimal_string as docs_json_ts_common_types_decimal_string,
	decimal_string_signed as docs_json_ts_common_types_decimal_string_signed,
	empty_object as docs_json_ts_common_types_empty_object,
} from './../../common/types.ts';

import type {
	mClearanceData_item as docs_json_ts_1_0_1_4_properties_mClearanceData_item,
	Montages_item_AudioEvent as docs_json_ts_1_0_1_4_properties_Montages_item_AudioEvent,
	Montages_item_AudioEvent_bSeparate3PAudioEvent_AudioEvent3P as docs_json_ts_1_0_1_4_properties_Montages_item_AudioEvent_bSeparate3PAudioEvent_AudioEvent3P,
	Montages_item_Filter_Exclusive_Montage_1P_Montage_3P_Montage_Equipment_AudioEvent as docs_json_ts_1_0_1_4_properties_Montages_item_Filter_Exclusive_Montage_1P_Montage_3P_Montage_Equipment_AudioEvent,
	Montages_item_Filter_FilterMontageTag_EquipmentInHand_None_Exclusive_AudioEvent as docs_json_ts_1_0_1_4_properties_Montages_item_Filter_FilterMontageTag_EquipmentInHand_None_Exclusive_AudioEvent,
	Montages_item_Filter_FilterMontageTag_EquipmentInHand_None_Exclusive_Montage_1P_Montage_3P_AudioEvent_CameraAnim as docs_json_ts_1_0_1_4_properties_Montages_item_Filter_FilterMontageTag_EquipmentInHand_None_Exclusive_Montage_1P_Montage_3P_AudioEvent_CameraAnim,
	Montages_item_Filter_FilterMontageTag_EquipmentInHand_TwoHanded_Exclusive_Montage_3P_AudioEvent_CameraAnim as docs_json_ts_1_0_1_4_properties_Montages_item_Filter_FilterMontageTag_EquipmentInHand_TwoHanded_Exclusive_Montage_3P_AudioEvent_CameraAnim,
	Montages_item_Filter_FilterMontageTag_EquipmentInHand_TwoHanded_InvertFilter_Exclusive_Montage_1P_Montage_3P_AudioEvent as docs_json_ts_1_0_1_4_properties_Montages_item_Filter_FilterMontageTag_EquipmentInHand_TwoHanded_InvertFilter_Exclusive_Montage_1P_Montage_3P_AudioEvent,
	Montages_item_Filter_FilterMontageTag_FullyCharged_Exclusive_Montage_1P_Montage_3P_Montage_Equipment_AudioEvent_bSeparate3PAudioEvent_AudioEvent3P_CameraAnim as docs_json_ts_1_0_1_4_properties_Montages_item_Filter_FilterMontageTag_FullyCharged_Exclusive_Montage_1P_Montage_3P_Montage_Equipment_AudioEvent_bSeparate3PAudioEvent_AudioEvent3P_CameraAnim,
	Montages_item_Filter_FilterMontageTag_HasAmmunition_Exclusive_Montage_1P_Montage_3P_Montage_Equipment as docs_json_ts_1_0_1_4_properties_Montages_item_Filter_FilterMontageTag_HasAmmunition_Exclusive_Montage_1P_Montage_3P_Montage_Equipment,
	Montages_item_Filter_FilterMontageTag_HasAmmunition_InvertFilter_Exclusive_Montage_1P_Montage_3P_Montage_Equipment as docs_json_ts_1_0_1_4_properties_Montages_item_Filter_FilterMontageTag_HasAmmunition_InvertFilter_Exclusive_Montage_1P_Montage_3P_Montage_Equipment,
	Montages_item_Filter_FilterMontageTag_LowCharged_Exclusive_Montage_1P_Montage_3P_Montage_Equipment_AudioEvent_bSeparate3PAudioEvent_AudioEvent3P as docs_json_ts_1_0_1_4_properties_Montages_item_Filter_FilterMontageTag_LowCharged_Exclusive_Montage_1P_Montage_3P_Montage_Equipment_AudioEvent_bSeparate3PAudioEvent_AudioEvent3P,
	Montages_item_Filter_FilterMontageTag_MediumCharged_Exclusive_Montage_1P_Montage_3P_Montage_Equipment_AudioEvent_bSeparate3PAudioEvent_AudioEvent3P as docs_json_ts_1_0_1_4_properties_Montages_item_Filter_FilterMontageTag_MediumCharged_Exclusive_Montage_1P_Montage_3P_Montage_Equipment_AudioEvent_bSeparate3PAudioEvent_AudioEvent3P,
	Montages_item_Montage_1P as docs_json_ts_1_0_1_4_properties_Montages_item_Montage_1P,
	Montages_item_Montage_1P_AudioEvent as docs_json_ts_1_0_1_4_properties_Montages_item_Montage_1P_AudioEvent,
	Montages_item_Montage_1P_Montage_3P as docs_json_ts_1_0_1_4_properties_Montages_item_Montage_1P_Montage_3P,
	Montages_item_Montage_1P_Montage_3P_AudioEvent as docs_json_ts_1_0_1_4_properties_Montages_item_Montage_1P_Montage_3P_AudioEvent,
	Montages_item_Montage_1P_Montage_3P_AudioEvent_bSeparate3PAudioEvent_AudioEvent3P_CameraAnim as docs_json_ts_1_0_1_4_properties_Montages_item_Montage_1P_Montage_3P_AudioEvent_bSeparate3PAudioEvent_AudioEvent3P_CameraAnim,
	Montages_item_Montage_1P_Montage_3P_AudioEvent_bSeparate3PAudioEvent_CameraAnim as docs_json_ts_1_0_1_4_properties_Montages_item_Montage_1P_Montage_3P_AudioEvent_bSeparate3PAudioEvent_CameraAnim,
	Montages_item_Montage_1P_Montage_3P_AudioEvent_CameraAnim as docs_json_ts_1_0_1_4_properties_Montages_item_Montage_1P_Montage_3P_AudioEvent_CameraAnim,
	Montages_item_Montage_1P_Montage_3P_CameraAnim as docs_json_ts_1_0_1_4_properties_Montages_item_Montage_1P_Montage_3P_CameraAnim,
	Montages_item_Montage_1P_Montage_3P_Montage_Equipment as docs_json_ts_1_0_1_4_properties_Montages_item_Montage_1P_Montage_3P_Montage_Equipment,
	Montages_item_Montage_1P_Montage_3P_Montage_Equipment_AudioEvent as docs_json_ts_1_0_1_4_properties_Montages_item_Montage_1P_Montage_3P_Montage_Equipment_AudioEvent,
	Montages_item_Montage_1P_Montage_3P_Montage_Equipment_AudioEvent_bSeparate3PAudioEvent_AudioEvent3P as docs_json_ts_1_0_1_4_properties_Montages_item_Montage_1P_Montage_3P_Montage_Equipment_AudioEvent_bSeparate3PAudioEvent_AudioEvent3P,
	Montages_item_Montage_1P_Montage_3P_Montage_Equipment_AudioEvent_bSeparate3PAudioEvent_AudioEvent3P_CameraAnim as docs_json_ts_1_0_1_4_properties_Montages_item_Montage_1P_Montage_3P_Montage_Equipment_AudioEvent_bSeparate3PAudioEvent_AudioEvent3P_CameraAnim,
	Montages_item_Montage_1P_Montage_3P_Montage_Equipment_AudioEvent_CameraAnim as docs_json_ts_1_0_1_4_properties_Montages_item_Montage_1P_Montage_3P_Montage_Equipment_AudioEvent_CameraAnim,
	Montages_item_Montage_1P_Montage_3P_Montage_Equipment_CameraAnim as docs_json_ts_1_0_1_4_properties_Montages_item_Montage_1P_Montage_3P_Montage_Equipment_CameraAnim,
	Montages_item_Montage_1P_Montage_Equipment as docs_json_ts_1_0_1_4_properties_Montages_item_Montage_1P_Montage_Equipment,
	Montages_item_Montage_1P_Montage_Equipment_AudioEvent as docs_json_ts_1_0_1_4_properties_Montages_item_Montage_1P_Montage_Equipment_AudioEvent,
	Montages_item_Montage_1P_Montage_Equipment_AudioEvent_bSeparate3PAudioEvent_AudioEvent3P_CameraAnim as docs_json_ts_1_0_1_4_properties_Montages_item_Montage_1P_Montage_Equipment_AudioEvent_bSeparate3PAudioEvent_AudioEvent3P_CameraAnim,
	Montages_item_Montage_1P_Montage_Equipment_AudioEvent_CameraAnim as docs_json_ts_1_0_1_4_properties_Montages_item_Montage_1P_Montage_Equipment_AudioEvent_CameraAnim,
	Montages_item_Montage_3P_AudioEvent as docs_json_ts_1_0_1_4_properties_Montages_item_Montage_3P_AudioEvent,
	Montages_item_Weight_Montage_1P_Montage_3P_Montage_Equipment_AudioEvent_bSeparate3PAudioEvent_AudioEvent3P_CameraAnim as docs_json_ts_1_0_1_4_properties_Montages_item_Weight_Montage_1P_Montage_3P_Montage_Equipment_AudioEvent_bSeparate3PAudioEvent_AudioEvent3P_CameraAnim,
	Montages_item_Weight_Montage_1P_Montage_3P_Montage_Equipment_AudioEvent_CameraAnim as docs_json_ts_1_0_1_4_properties_Montages_item_Weight_Montage_1P_Montage_3P_Montage_Equipment_AudioEvent_CameraAnim,
	Montages_item_Weight_Montage_1P_Montage_3P_Montage_Equipment_CameraAnim as docs_json_ts_1_0_1_4_properties_Montages_item_Weight_Montage_1P_Montage_3P_Montage_Equipment_CameraAnim,
} from './../../1.0.1.4/types/properties.ts';

import type {
	DocsDotJson_AkAudioEvent_quoted_list_item as docs_json_ts_0_8_3_3_properties_overridable_DocsDotJson_AkAudioEvent_quoted_list_item,
} from './../../0.8.3.3/types/properties.1.1.2.2.ts';

import type {
	AnimMontage_quoted as docs_json_ts_0_3_7_7_overridable_AnimMontage_quoted,
} from './../../0.3.7.7/types/overridable--1.1.2.2.ts';

type mHologramOverrides_item = `/Script/FactoryGame.FGHologramOverride_ConveyorAttachment_FloorToLift'/Game/FactoryGame${Exclude<string, ''>}${'\''}`;

type mPoleVariations_item = {
	StaticMesh: `/Script/Engine.StaticMesh'/Game/FactoryGame${Exclude<string, ''>}${'\''}`,
	Height: docs_json_ts_common_types_decimal_string,
	Clearance: docs_json_ts_1_0_1_4_properties_mClearanceData_item,
};

type mSoftAudioEvents = {
	mSoftAudioEvents: [
		mSoftAudioEvents_item,
		...mSoftAudioEvents_item[],
	],
};

type mSoftAudioEvents_item = '/Game/WwiseAudio/Events/Equipment/Rifle/Play_E_Rifle_WorldImpact_Solids.Play_E_Rifle_WorldImpact_Solids';

type mStatisticGameplayTag = {
	TagName: `Stats.Gameplay.Schematics.Schematic${'_Tutorial1' | '_Tutorial1_5' | '_Tutorial2' | '_Tutorial3' | '_Tutorial4' | '_Tutorial5' | '1-1' | '1-2' | '1-3' | '2-1' | '2-2' | '2-3' | '2-5' | '3-1' | '3-2' | '3-3' | '3-4' | '4-1' | '4-2' | '4-3' | '4-4' | '4-5' | '5-1' | '5-2' | '5-3' | '5-4' | '5-5' | '6-1' | '6-2' | '6-3' | '6-4' | '6-5' | '6-6' | '6-7' | '7-1' | '7-2' | '7-3' | '7-4' | '7-5' | '8-1' | '8-2' | '8-3' | '8-4' | '8-5' | '9-1' | '9-2' | '9-3' | '9-4' | '9-5'}`,
};

type FalloffCurve_EditorCurveData = {
	EditorCurveData: FalloffCurve_EditorCurveData_with_ExternalCurve_EditorCurveData_without_keys,
};

type FalloffCurve_EditorCurveData_with_ExternalCurve = {
	EditorCurveData: FalloffCurve_EditorCurveData_with_ExternalCurve_EditorCurveData | FalloffCurve_EditorCurveData_with_ExternalCurve_EditorCurveData_without_keys,
	ExternalCurve: `/Script/Engine.CurveFloat'/Game/FactoryGame${Exclude<string, ''>}${'\''}`,
};

type FalloffCurve_EditorCurveData_with_ExternalCurve_EditorCurveData = {
	Keys: [
		{
			InterpMode: 'RCIM_Cubic',
			TangentMode: 'RCTM_User',
			Time: docs_json_ts_common_types_decimal_string_signed,
			Value: docs_json_ts_common_types_decimal_string,
			ArriveTangent: docs_json_ts_common_types_decimal_string_signed,
			LeaveTangent: docs_json_ts_common_types_decimal_string_signed,
		},
		{
			InterpMode: 'RCIM_Cubic',
			TangentMode: 'RCTM_User',
			Time: docs_json_ts_common_types_decimal_string_signed,
			Value: docs_json_ts_common_types_decimal_string,
			ArriveTangent: docs_json_ts_common_types_decimal_string_signed,
			LeaveTangent: docs_json_ts_common_types_decimal_string_signed,
		},
		...{
			InterpMode: 'RCIM_Cubic',
			TangentMode: 'RCTM_User',
			Time: docs_json_ts_common_types_decimal_string_signed,
			Value: docs_json_ts_common_types_decimal_string,
			ArriveTangent: docs_json_ts_common_types_decimal_string_signed,
			LeaveTangent: docs_json_ts_common_types_decimal_string_signed,
		}[],
	],
	DefaultValue: docs_json_ts_common_types_decimal_string,
	PreInfinityExtrap: 'RCCE_Constant',
	PostInfinityExtrap: 'RCCE_Constant',
};

type FalloffCurve_EditorCurveData_with_ExternalCurve_EditorCurveData_without_keys = {
	DefaultValue: docs_json_ts_common_types_decimal_string,
	PreInfinityExtrap: 'RCCE_Constant',
	PostInfinityExtrap: 'RCCE_Constant',
};

type Montages = docs_json_ts_common_types_empty_object | Montages_as_object;

type Montages_as_object = {
	Montages: [
		Montages_item,
		...Montages_item[],
	],
};

type Montages_item = docs_json_ts_1_0_1_4_properties_Montages_item_Montage_1P_Montage_Equipment | docs_json_ts_1_0_1_4_properties_Montages_item_Montage_1P_Montage_Equipment_AudioEvent | docs_json_ts_1_0_1_4_properties_Montages_item_Montage_1P_Montage_3P_Montage_Equipment_AudioEvent | docs_json_ts_1_0_1_4_properties_Montages_item_AudioEvent | docs_json_ts_1_0_1_4_properties_Montages_item_Weight_Montage_1P_Montage_3P_Montage_Equipment_CameraAnim | docs_json_ts_1_0_1_4_properties_Montages_item_Montage_1P_Montage_3P_Montage_Equipment_CameraAnim | docs_json_ts_1_0_1_4_properties_Montages_item_Montage_1P_Montage_3P_Montage_Equipment_AudioEvent_bSeparate3PAudioEvent_AudioEvent3P | docs_json_ts_1_0_1_4_properties_Montages_item_Montage_1P_Montage_3P_CameraAnim | docs_json_ts_1_0_1_4_properties_Montages_item_Montage_1P | docs_json_ts_1_0_1_4_properties_Montages_item_Montage_1P_Montage_3P | docs_json_ts_1_0_1_4_properties_Montages_item_Montage_1P_Montage_3P_AudioEvent_CameraAnim | docs_json_ts_1_0_1_4_properties_Montages_item_Montage_1P_AudioEvent | docs_json_ts_1_0_1_4_properties_Montages_item_Filter_FilterMontageTag_HasAmmunition_Exclusive_Montage_1P_Montage_3P_Montage_Equipment | docs_json_ts_1_0_1_4_properties_Montages_item_Filter_FilterMontageTag_HasAmmunition_InvertFilter_Exclusive_Montage_1P_Montage_3P_Montage_Equipment | docs_json_ts_1_0_1_4_properties_Montages_item_Filter_FilterMontageTag_LowCharged_Exclusive_Montage_1P_Montage_3P_Montage_Equipment_AudioEvent_bSeparate3PAudioEvent_AudioEvent3P | docs_json_ts_1_0_1_4_properties_Montages_item_Filter_FilterMontageTag_MediumCharged_Exclusive_Montage_1P_Montage_3P_Montage_Equipment_AudioEvent_bSeparate3PAudioEvent_AudioEvent3P | docs_json_ts_1_0_1_4_properties_Montages_item_Filter_FilterMontageTag_FullyCharged_Exclusive_Montage_1P_Montage_3P_Montage_Equipment_AudioEvent_bSeparate3PAudioEvent_AudioEvent3P_CameraAnim | docs_json_ts_1_0_1_4_properties_Montages_item_Montage_1P_Montage_3P_Montage_Equipment_AudioEvent_bSeparate3PAudioEvent_AudioEvent3P_CameraAnim | docs_json_ts_1_0_1_4_properties_Montages_item_Weight_Montage_1P_Montage_3P_Montage_Equipment_AudioEvent_bSeparate3PAudioEvent_AudioEvent3P_CameraAnim | docs_json_ts_1_0_1_4_properties_Montages_item_Filter_Exclusive_Montage_1P_Montage_3P_Montage_Equipment_AudioEvent | docs_json_ts_1_0_1_4_properties_Montages_item_Weight_Montage_1P_Montage_3P_Montage_Equipment_AudioEvent_CameraAnim | docs_json_ts_1_0_1_4_properties_Montages_item_Montage_1P_Montage_3P_Montage_Equipment_AudioEvent_CameraAnim | docs_json_ts_1_0_1_4_properties_Montages_item_Montage_1P_Montage_3P_AudioEvent | docs_json_ts_1_0_1_4_properties_Montages_item_Filter_FilterMontageTag_EquipmentInHand_None_Exclusive_AudioEvent | docs_json_ts_1_0_1_4_properties_Montages_item_Montage_1P_Montage_3P_Montage_Equipment | docs_json_ts_1_0_1_4_properties_Montages_item_AudioEvent_bSeparate3PAudioEvent_AudioEvent3P | docs_json_ts_1_0_1_4_properties_Montages_item_Montage_1P_Montage_Equipment_AudioEvent_CameraAnim | docs_json_ts_1_0_1_4_properties_Montages_item_Montage_1P_Montage_Equipment_AudioEvent_bSeparate3PAudioEvent_AudioEvent3P_CameraAnim | docs_json_ts_1_0_1_4_properties_Montages_item_Montage_1P_Montage_3P_AudioEvent_bSeparate3PAudioEvent_CameraAnim | docs_json_ts_1_0_1_4_properties_Montages_item_Montage_1P_Montage_3P_AudioEvent_bSeparate3PAudioEvent_AudioEvent3P_CameraAnim | docs_json_ts_1_0_1_4_properties_Montages_item_Filter_FilterMontageTag_EquipmentInHand_None_Exclusive_Montage_1P_Montage_3P_AudioEvent_CameraAnim | docs_json_ts_1_0_1_4_properties_Montages_item_Filter_FilterMontageTag_EquipmentInHand_TwoHanded_Exclusive_Montage_3P_AudioEvent_CameraAnim | docs_json_ts_1_0_1_4_properties_Montages_item_Filter_FilterMontageTag_EquipmentInHand_TwoHanded_InvertFilter_Exclusive_Montage_1P_Montage_3P_AudioEvent | docs_json_ts_1_0_1_4_properties_Montages_item_Montage_3P_AudioEvent | Montages_item_AudioEvent_bSeparate3PAudioEvent | Montages_item_Filter_Exclusive_Montage_1P_Montage_3P_Montage_Equipment_AudioEvent_bSeparate3PAudioEvent_AudioEvent3P | Montages_item_Weight_Montage_1P_Montage_3P_Montage_Equipment_AudioEvent;

type Montages_item_AudioEvent_bSeparate3PAudioEvent = {
	AudioEvent: docs_json_ts_0_8_3_3_properties_overridable_DocsDotJson_AkAudioEvent_quoted_list_item,
	bSeparate3PAudioEvent: docs_json_ts_common_types_bool_string,
};

type Montages_item_Filter_Exclusive_Montage_1P_Montage_3P_Montage_Equipment_AudioEvent_bSeparate3PAudioEvent_AudioEvent3P = {
	Filter: docs_json_ts_common_types_bool_string,
	Exclusive: docs_json_ts_common_types_bool_string,
	Montage_1P: docs_json_ts_0_3_7_7_overridable_AnimMontage_quoted,
	Montage_3P: docs_json_ts_0_3_7_7_overridable_AnimMontage_quoted,
	Montage_Equipment: docs_json_ts_0_3_7_7_overridable_AnimMontage_quoted,
	AudioEvent: docs_json_ts_0_8_3_3_properties_overridable_DocsDotJson_AkAudioEvent_quoted_list_item,
	bSeparate3PAudioEvent: docs_json_ts_common_types_bool_string,
	AudioEvent3P: docs_json_ts_0_8_3_3_properties_overridable_DocsDotJson_AkAudioEvent_quoted_list_item,
};

type Montages_item_Weight_Montage_1P_Montage_3P_Montage_Equipment_AudioEvent = {
	Weight: docs_json_ts_common_types_decimal_string,
	Montage_1P: docs_json_ts_0_3_7_7_overridable_AnimMontage_quoted,
	Montage_3P: docs_json_ts_0_3_7_7_overridable_AnimMontage_quoted,
	Montage_Equipment: docs_json_ts_0_3_7_7_overridable_AnimMontage_quoted,
	AudioEvent: docs_json_ts_0_8_3_3_properties_overridable_DocsDotJson_AkAudioEvent_quoted_list_item,
};

type WidgetClass = 'None' | `/Game/FactoryGame/${'Buildable' | 'Interface'}${'/'}${Exclude<string, ''>}${'/Widget_'}${Exclude<string, ''>}${'.Widget_'}${Exclude<string, ''>}${'_C'}` | `/Game/FactoryGame/${'Buildable' | 'Interface'}${'/'}${Exclude<string, ''>}${'/BPW_'}${Exclude<string, ''>}${'.BPW_'}${Exclude<string, ''>}${'_C'}`;

export type {
	mHologramOverrides_item,
	mPoleVariations_item,
	mSoftAudioEvents,
	mSoftAudioEvents_item,
	mStatisticGameplayTag,
	FalloffCurve_EditorCurveData,
	FalloffCurve_EditorCurveData_with_ExternalCurve,
	FalloffCurve_EditorCurveData_with_ExternalCurve_EditorCurveData,
	FalloffCurve_EditorCurveData_with_ExternalCurve_EditorCurveData_without_keys,
	Montages,
	Montages_as_object,
	Montages_item,
	Montages_item_AudioEvent_bSeparate3PAudioEvent,
	Montages_item_Filter_Exclusive_Montage_1P_Montage_3P_Montage_Equipment_AudioEvent_bSeparate3PAudioEvent_AudioEvent3P,
	Montages_item_Weight_Montage_1P_Montage_3P_Montage_Equipment_AudioEvent,
	WidgetClass,
};
