/* eslint-disable @stylistic/max-len */

import type {
	bool_string as docs_json_ts_common_types_bool_string,
	decimal_string as docs_json_ts_common_types_decimal_string,
	empty_object as docs_json_ts_common_types_empty_object,
} from './../../common/types.ts';

import type {
	AnimMontage_quoted as docs_json_ts_0_3_7_7_overridable_AnimMontage_quoted,
	DocsDotJson_BlueprintGeneratedClass_quoted_list as docs_json_ts_0_3_7_7_overridable_DocsDotJson_BlueprintGeneratedClass_quoted_list,
	mUnlocks_item_mItemsToGive as docs_json_ts_0_3_7_7_overridable_mUnlocks_item_mItemsToGive,
	mUnlocks_item_mRecipes as docs_json_ts_0_3_7_7_overridable_mUnlocks_item_mRecipes,
	mUnlocks_item_mSchematics as docs_json_ts_0_3_7_7_overridable_mUnlocks_item_mSchematics,
} from './../../0.3.7.7/types/overridable--1.2.0.0.ts';

import type {
	mUnlocks_item_mResourcePairsToAddToScanner as docs_json_ts_0_4_2_11_overridable_mUnlocks_item_mResourcePairsToAddToScanner,
} from './../../0.4.2.11/types/overridable--1.2.0.0.ts';

import type {
	mUnlocks_item_mEmotes as docs_json_ts_0_5_2_1_overridable_mUnlocks_item_mEmotes,
} from './../../0.5.2.1/types/overridable--1.2.0.0.ts';

import type {
	mUnlocks_item_mNumArmEquipmentSlotsToUnlock as docs_json_ts_0_4_2_11_properties_mUnlocks_item_mNumArmEquipmentSlotsToUnlock,
} from './../../0.4.2.11/types/properties.ts';

import type {
	mUnlocks_item_base as docs_json_ts_0_3_7_7_properties_mUnlocks_item_base,
	mUnlocks_item_mNumInventorySlotsToUnlock as docs_json_ts_0_3_7_7_properties_mUnlocks_item_mNumInventorySlotsToUnlock,
} from './../../0.3.7.7/types/properties.ts';

import type {
	mUnlocks_item_mTapeUnlocks as docs_json_ts_0_6_1_5_overridable_mUnlocks_item_mTapeUnlocks,
} from './../../0.6.1.5/types/overridable--1.2.0.0.ts';

import type {
	CameraAnimationSequence_quoted as docs_json_ts_0_8_3_3_properties_overridable_CameraAnimationSequence_quoted,
	DocsDotJson_AkAudioEvent_quoted_list_item as docs_json_ts_0_8_3_3_properties_overridable_DocsDotJson_AkAudioEvent_quoted_list_item,
	mUnlocks_item_mScannableObjects as docs_json_ts_0_8_3_3_properties_overridable_mUnlocks_item_mScannableObjects,
} from './../../0.8.3.3/types/properties.1.2.0.0.ts';

import type {
	Montages_item_Filter_FilterMontageTag_LowCharged_Exclusive_Montage_1P_Montage_3P_Montage_Equipment_AudioEvent_bSeparate3PAudioEvent_AudioEvent3P as docs_json_ts_1_0_1_4_properties_Montages_item_Filter_FilterMontageTag_LowCharged_Exclusive_Montage_1P_Montage_3P_Montage_Equipment_AudioEvent_bSeparate3PAudioEvent_AudioEvent3P,
	Montages_item_Filter_FilterMontageTag_MediumCharged_Exclusive_Montage_1P_Montage_3P_Montage_Equipment_AudioEvent_bSeparate3PAudioEvent_AudioEvent3P as docs_json_ts_1_0_1_4_properties_Montages_item_Filter_FilterMontageTag_MediumCharged_Exclusive_Montage_1P_Montage_3P_Montage_Equipment_AudioEvent_bSeparate3PAudioEvent_AudioEvent3P,
	Montages_item_Montage_1P_Montage_3P as docs_json_ts_1_0_1_4_properties_Montages_item_Montage_1P_Montage_3P,
	Montages_item_Montage_1P_Montage_3P_AudioEvent_bSeparate3PAudioEvent_AudioEvent3P_CameraAnim as docs_json_ts_1_0_1_4_properties_Montages_item_Montage_1P_Montage_3P_AudioEvent_bSeparate3PAudioEvent_AudioEvent3P_CameraAnim,
	Montages_item_Montage_1P_Montage_3P_Montage_Equipment_AudioEvent_bSeparate3PAudioEvent_AudioEvent3P as docs_json_ts_1_0_1_4_properties_Montages_item_Montage_1P_Montage_3P_Montage_Equipment_AudioEvent_bSeparate3PAudioEvent_AudioEvent3P,
	mUnlocks_item_mCustomizationUnlocks as docs_json_ts_1_0_1_4_properties_mUnlocks_item_mCustomizationUnlocks,
	mUnlocks_item_mItemStackLimitIncrease as docs_json_ts_1_0_1_4_properties_mUnlocks_item_mItemStackLimitIncrease,
	mUnlocks_item_mNumSlotsToUnlock as docs_json_ts_1_0_1_4_properties_mUnlocks_item_mNumSlotsToUnlock,
	mUnlocks_item_mUploadSpeedPercentageDecrease as docs_json_ts_1_0_1_4_properties_mUnlocks_item_mUploadSpeedPercentageDecrease,
} from './../../1.0.1.4/types/properties.ts';

import type {
	Montages_item_Filter_Exclusive_Montage_1P_Montage_3P_Montage_Equipment_AudioEvent_bSeparate3PAudioEvent_AudioEvent3P as docs_json_ts_1_1_2_2_properties_Montages_item_Filter_Exclusive_Montage_1P_Montage_3P_Montage_Equipment_AudioEvent_bSeparate3PAudioEvent_AudioEvent3P,
	Montages_item_Weight_Montage_1P_Montage_3P_Montage_Equipment_AudioEvent as docs_json_ts_1_1_2_2_properties_Montages_item_Weight_Montage_1P_Montage_3P_Montage_Equipment_AudioEvent,
} from './../../1.1.2.2/types/properties.ts';

type mAllowedResourceForms_item = 'RF_SOLID' | 'RF_LIQUID' | 'RF_GAS' | '(INVALID)';

type mGameplayTags = docs_json_ts_common_types_empty_object | mGameplayTags_non_empty;

type mGameplayTags_non_empty = {
	GameplayTags: [
		mGameplayTags_tag_array_item,
		...mGameplayTags_tag_array_item[],
	],
};

type mGameplayTags_tag_array_item = {
	TagName: 'Resource.Basic' | 'Resource.FossilFuel' | 'Resource.Advanced' | 'Recipe.Part' | 'Recipe.SpacePart',
};

type mUnlocks_item = docs_json_ts_0_3_7_7_overridable_mUnlocks_item_mRecipes | docs_json_ts_0_4_2_11_overridable_mUnlocks_item_mResourcePairsToAddToScanner | docs_json_ts_0_5_2_1_overridable_mUnlocks_item_mEmotes | docs_json_ts_0_4_2_11_properties_mUnlocks_item_mNumArmEquipmentSlotsToUnlock | docs_json_ts_0_3_7_7_properties_mUnlocks_item_mNumInventorySlotsToUnlock | mUnlocks_item_mItemDescriptors | docs_json_ts_0_6_1_5_overridable_mUnlocks_item_mTapeUnlocks | docs_json_ts_0_3_7_7_properties_mUnlocks_item_base | docs_json_ts_0_3_7_7_overridable_mUnlocks_item_mSchematics | docs_json_ts_0_8_3_3_properties_overridable_mUnlocks_item_mScannableObjects | docs_json_ts_0_3_7_7_overridable_mUnlocks_item_mItemsToGive | docs_json_ts_1_0_1_4_properties_mUnlocks_item_mCustomizationUnlocks | docs_json_ts_1_0_1_4_properties_mUnlocks_item_mUploadSpeedPercentageDecrease | docs_json_ts_1_0_1_4_properties_mUnlocks_item_mItemStackLimitIncrease | docs_json_ts_1_0_1_4_properties_mUnlocks_item_mNumSlotsToUnlock;

type mUnlocks_item_mItemDescriptors = docs_json_ts_0_3_7_7_properties_mUnlocks_item_base & {
	Class?: `BP_${string}${'_C'}`,
	mItemDescriptors: docs_json_ts_0_3_7_7_overridable_DocsDotJson_BlueprintGeneratedClass_quoted_list,
};

type FGVehiclePathSegment_item = '/Script/FactoryGame.FGVehiclePathPreset\'/Game/FactoryGame/Buildable/Vehicle/Tractor/VehiclePathPreset_Tractor.VehiclePathPreset_Tractor\'' | '/Script/FactoryGame.FGVehiclePathPreset\'/Game/FactoryGame/Buildable/Vehicle/Truck/VehiclePathPreset_Truck.VehiclePathPreset_Truck\'' | '/Script/FactoryGame.FGVehiclePathPreset\'/Game/FactoryGame/Buildable/Vehicle/Explorer/VehiclePathPreset_Explorer.VehiclePathPreset_Explorer\'' | '/Script/FactoryGame.FGVehiclePathPreset\'/Game/FactoryGame/Buildable/Vehicle/Golfcart/VehiclePathPreset_FactoryCart.VehiclePathPreset_FactoryCart\'';

type Montages = docs_json_ts_common_types_empty_object | Montages_as_object;

type Montages_as_object = {
	Montages: [
		Montages_item,
		...Montages_item[],
	],
};

type Montages_FGNobeliskDetonator = {
	Montages: [
		Montages_FGNobeliskDetonator_item,
		...Montages_FGNobeliskDetonator_item[],
	],
};

type Montages_FGNobeliskDetonator_item = docs_json_ts_1_0_1_4_properties_Montages_item_Filter_FilterMontageTag_LowCharged_Exclusive_Montage_1P_Montage_3P_Montage_Equipment_AudioEvent_bSeparate3PAudioEvent_AudioEvent3P | docs_json_ts_1_0_1_4_properties_Montages_item_Filter_FilterMontageTag_MediumCharged_Exclusive_Montage_1P_Montage_3P_Montage_Equipment_AudioEvent_bSeparate3PAudioEvent_AudioEvent3P | Montages_item_Filter_FilterMontageTag_FullyCharged_Exclusive_Montage_1P_Montage_3P_Montage_Equipment_AudioEvent_bSeparate3PAudioEvent_AudioEvent3P;

type Montages_FGParachute = {
	Montages: [
		Montages_FGParachute_item,
		...Montages_FGParachute_item[],
	],
};

type Montages_FGParachute_item = Montages_item_Filter_FilterMontageTag_EquipmentInHand_None_Exclusive_Montage_1P_Montage_3P_AudioEvent_bSeparate3PAudioEvent_AudioEvent3P_CameraAnim | Montages_item_Filter_FilterMontageTag_EquipmentInHand_TwoHanded_Exclusive_Montage_3P_AudioEvent_bSeparate3PAudioEvent_AudioEvent3P_CameraAnim | docs_json_ts_1_0_1_4_properties_Montages_item_Montage_1P_Montage_3P_AudioEvent_bSeparate3PAudioEvent_AudioEvent3P_CameraAnim | Montages_item_Filter_FilterMontageTag_EquipmentInHand_TwoHanded_InvertFilter_Exclusive_Montage_1P_Montage_3P_AudioEvent_bSeparate3PAudioEvent_AudioEvent3P | Montages_item_Montage_3P_AudioEvent_bSeparate3PAudioEvent_AudioEvent3P;

type Montages_item = docs_json_ts_1_0_1_4_properties_Montages_item_Montage_1P_Montage_3P | Montages_item_Montage_1P_AudioEvent_bSeparate3PAudioEvent_AudioEvent3P | docs_json_ts_1_1_2_2_properties_Montages_item_Filter_Exclusive_Montage_1P_Montage_3P_Montage_Equipment_AudioEvent_bSeparate3PAudioEvent_AudioEvent3P | Montages_item_Weight_Montage_1P_Montage_3P_Montage_Equipment_AudioEvent_bSeparate3PAudioEvent_AudioEvent3P | docs_json_ts_1_0_1_4_properties_Montages_item_Montage_1P_Montage_3P_Montage_Equipment_AudioEvent_bSeparate3PAudioEvent_AudioEvent3P | docs_json_ts_1_1_2_2_properties_Montages_item_Weight_Montage_1P_Montage_3P_Montage_Equipment_AudioEvent | Montages_item_Montage_1P_Montage_Equipment_AudioEvent_bSeparate3PAudioEvent_AudioEvent3P;

type Montages_item_Filter_FilterMontageTag_EquipmentInHand_None_Exclusive_Montage_1P_Montage_3P_AudioEvent_bSeparate3PAudioEvent_AudioEvent3P_CameraAnim = {
	Filter: docs_json_ts_common_types_bool_string,
	FilterMontageTag: 'EquipmentInHand_None',
	Exclusive: docs_json_ts_common_types_bool_string,
	Montage_1P: docs_json_ts_0_3_7_7_overridable_AnimMontage_quoted,
	Montage_3P: docs_json_ts_0_3_7_7_overridable_AnimMontage_quoted,
	AudioEvent: docs_json_ts_0_8_3_3_properties_overridable_DocsDotJson_AkAudioEvent_quoted_list_item,
	bSeparate3PAudioEvent: docs_json_ts_common_types_bool_string,
	AudioEvent3P: docs_json_ts_0_8_3_3_properties_overridable_DocsDotJson_AkAudioEvent_quoted_list_item,
	CameraAnim: docs_json_ts_0_8_3_3_properties_overridable_CameraAnimationSequence_quoted,
};

type Montages_item_Filter_FilterMontageTag_EquipmentInHand_TwoHanded_Exclusive_Montage_3P_AudioEvent_bSeparate3PAudioEvent_AudioEvent3P_CameraAnim = {
	Filter: docs_json_ts_common_types_bool_string,
	FilterMontageTag: 'EquipmentInHand_TwoHanded',
	Exclusive: docs_json_ts_common_types_bool_string,
	Montage_3P: docs_json_ts_0_3_7_7_overridable_AnimMontage_quoted,
	AudioEvent: docs_json_ts_0_8_3_3_properties_overridable_DocsDotJson_AkAudioEvent_quoted_list_item,
	bSeparate3PAudioEvent: docs_json_ts_common_types_bool_string,
	AudioEvent3P: docs_json_ts_0_8_3_3_properties_overridable_DocsDotJson_AkAudioEvent_quoted_list_item,
	CameraAnim: docs_json_ts_0_8_3_3_properties_overridable_CameraAnimationSequence_quoted,
};

type Montages_item_Filter_FilterMontageTag_EquipmentInHand_TwoHanded_InvertFilter_Exclusive_Montage_1P_Montage_3P_AudioEvent_bSeparate3PAudioEvent_AudioEvent3P = {
	Filter: docs_json_ts_common_types_bool_string,
	FilterMontageTag: 'EquipmentInHand_TwoHanded',
	InvertFilter: docs_json_ts_common_types_bool_string,
	Exclusive: docs_json_ts_common_types_bool_string,
	Montage_1P: docs_json_ts_0_3_7_7_overridable_AnimMontage_quoted,
	Montage_3P: docs_json_ts_0_3_7_7_overridable_AnimMontage_quoted,
	AudioEvent: docs_json_ts_0_8_3_3_properties_overridable_DocsDotJson_AkAudioEvent_quoted_list_item,
	bSeparate3PAudioEvent: docs_json_ts_common_types_bool_string,
	AudioEvent3P: docs_json_ts_0_8_3_3_properties_overridable_DocsDotJson_AkAudioEvent_quoted_list_item,
};

type Montages_item_Filter_FilterMontageTag_FullyCharged_Exclusive_Montage_1P_Montage_3P_Montage_Equipment_AudioEvent_bSeparate3PAudioEvent_AudioEvent3P = {
	Filter: docs_json_ts_common_types_bool_string,
	FilterMontageTag: 'FullyCharged',
	Exclusive: docs_json_ts_common_types_bool_string,
	Montage_1P: docs_json_ts_0_3_7_7_overridable_AnimMontage_quoted,
	Montage_3P: docs_json_ts_0_3_7_7_overridable_AnimMontage_quoted,
	Montage_Equipment: docs_json_ts_0_3_7_7_overridable_AnimMontage_quoted,
	AudioEvent: docs_json_ts_0_8_3_3_properties_overridable_DocsDotJson_AkAudioEvent_quoted_list_item,
	bSeparate3PAudioEvent: docs_json_ts_common_types_bool_string,
	AudioEvent3P: docs_json_ts_0_8_3_3_properties_overridable_DocsDotJson_AkAudioEvent_quoted_list_item,
};

type Montages_item_Montage_1P_AudioEvent_bSeparate3PAudioEvent_AudioEvent3P = {
	Montage_1P: docs_json_ts_0_3_7_7_overridable_AnimMontage_quoted,
	AudioEvent: docs_json_ts_0_8_3_3_properties_overridable_DocsDotJson_AkAudioEvent_quoted_list_item,
	bSeparate3PAudioEvent: docs_json_ts_common_types_bool_string,
	AudioEvent3P: docs_json_ts_0_8_3_3_properties_overridable_DocsDotJson_AkAudioEvent_quoted_list_item,
};

type Montages_item_Montage_1P_Montage_Equipment_AudioEvent_bSeparate3PAudioEvent_AudioEvent3P = {
	Montage_1P: docs_json_ts_0_3_7_7_overridable_AnimMontage_quoted,
	Montage_Equipment: docs_json_ts_0_3_7_7_overridable_AnimMontage_quoted,
	AudioEvent: docs_json_ts_0_8_3_3_properties_overridable_DocsDotJson_AkAudioEvent_quoted_list_item,
	bSeparate3PAudioEvent: docs_json_ts_common_types_bool_string,
	AudioEvent3P: docs_json_ts_0_8_3_3_properties_overridable_DocsDotJson_AkAudioEvent_quoted_list_item,
};

type Montages_item_Montage_3P_AudioEvent_bSeparate3PAudioEvent_AudioEvent3P = {
	Montage_3P: docs_json_ts_0_3_7_7_overridable_AnimMontage_quoted,
	AudioEvent: docs_json_ts_0_8_3_3_properties_overridable_DocsDotJson_AkAudioEvent_quoted_list_item,
	bSeparate3PAudioEvent: docs_json_ts_common_types_bool_string,
	AudioEvent3P: docs_json_ts_0_8_3_3_properties_overridable_DocsDotJson_AkAudioEvent_quoted_list_item,
};

type Montages_item_Weight_Montage_1P_Montage_3P_Montage_Equipment_AudioEvent_bSeparate3PAudioEvent_AudioEvent3P = {
	Weight: docs_json_ts_common_types_decimal_string,
	Montage_1P: docs_json_ts_0_3_7_7_overridable_AnimMontage_quoted,
	Montage_3P: docs_json_ts_0_3_7_7_overridable_AnimMontage_quoted,
	Montage_Equipment: docs_json_ts_0_3_7_7_overridable_AnimMontage_quoted,
	AudioEvent: docs_json_ts_0_8_3_3_properties_overridable_DocsDotJson_AkAudioEvent_quoted_list_item,
	bSeparate3PAudioEvent: docs_json_ts_common_types_bool_string,
	AudioEvent3P: docs_json_ts_0_8_3_3_properties_overridable_DocsDotJson_AkAudioEvent_quoted_list_item,
};

export type {
	mAllowedResourceForms_item,
	mGameplayTags,
	mGameplayTags_non_empty,
	mGameplayTags_tag_array_item,
	mUnlocks_item,
	mUnlocks_item_mItemDescriptors,
	FGVehiclePathSegment_item,
	Montages,
	Montages_as_object,
	Montages_FGNobeliskDetonator,
	Montages_FGNobeliskDetonator_item,
	Montages_FGParachute,
	Montages_FGParachute_item,
	Montages_item,
	Montages_item_Filter_FilterMontageTag_EquipmentInHand_None_Exclusive_Montage_1P_Montage_3P_AudioEvent_bSeparate3PAudioEvent_AudioEvent3P_CameraAnim,
	Montages_item_Filter_FilterMontageTag_EquipmentInHand_TwoHanded_Exclusive_Montage_3P_AudioEvent_bSeparate3PAudioEvent_AudioEvent3P_CameraAnim,
	Montages_item_Filter_FilterMontageTag_EquipmentInHand_TwoHanded_InvertFilter_Exclusive_Montage_1P_Montage_3P_AudioEvent_bSeparate3PAudioEvent_AudioEvent3P,
	Montages_item_Filter_FilterMontageTag_FullyCharged_Exclusive_Montage_1P_Montage_3P_Montage_Equipment_AudioEvent_bSeparate3PAudioEvent_AudioEvent3P,
	Montages_item_Montage_1P_AudioEvent_bSeparate3PAudioEvent_AudioEvent3P,
	Montages_item_Montage_1P_Montage_Equipment_AudioEvent_bSeparate3PAudioEvent_AudioEvent3P,
	Montages_item_Montage_3P_AudioEvent_bSeparate3PAudioEvent_AudioEvent3P,
	Montages_item_Weight_Montage_1P_Montage_3P_Montage_Equipment_AudioEvent_bSeparate3PAudioEvent_AudioEvent3P,
};
