/* eslint-disable @stylistic/max-len */

import type {
	FGBuildable_base as docs_json_ts_0_6_1_5_classes_base_FGBuildable_base,
	FGBuildableBeam as docs_json_ts_0_6_1_5_classes_base_FGBuildableBeam,
	FGBuildableCornerWall as docs_json_ts_0_6_1_5_classes_base_FGBuildableCornerWall,
	FGBuildableDoor as docs_json_ts_0_6_1_5_classes_base_FGBuildableDoor,
	FGBuildableFoundation as docs_json_ts_0_6_1_5_classes_base_FGBuildableFoundation,
	FGBuildableManufacturer_Build_SmelterMk1_C_base as docs_json_ts_0_6_1_5_classes_base_FGBuildableManufacturer_Build_SmelterMk1_C_base,
	FGBuildablePillar as docs_json_ts_0_6_1_5_classes_base_FGBuildablePillar,
	FGBuildablePipeline as docs_json_ts_0_6_1_5_classes_base_FGBuildablePipeline,
	FGBuildablePole as docs_json_ts_0_6_1_5_classes_base_FGBuildablePole,
	FGBuildableRadarTower_base as docs_json_ts_0_6_1_5_classes_base_FGBuildableRadarTower_base,
	FGBuildableRailroadTrack as docs_json_ts_0_6_1_5_classes_base_FGBuildableRailroadTrack,
	FGBuildableRamp as docs_json_ts_0_6_1_5_classes_base_FGBuildableRamp,
	FGBuildableResourceExtractor_base_version_specific_base as docs_json_ts_0_6_1_5_classes_base_FGBuildableResourceExtractor_base_version_specific_base,
	FGBuildableTrainPlatformCargo_version_specific as docs_json_ts_0_6_1_5_classes_base_FGBuildableTrainPlatformCargo_version_specific,
	FGBuildableWall as docs_json_ts_0_6_1_5_classes_base_FGBuildableWall,
	FGEquipment as docs_json_ts_0_6_1_5_classes_base_FGEquipment,
} from './../../0.6.1.5/classes/Base.ts';

import type {
	bool_string as docs_json_ts_common_types_bool_string,
	decimal_string as docs_json_ts_common_types_decimal_string,
	empty_object as docs_json_ts_common_types_empty_object,
	integer_string as docs_json_ts_common_types_integer_string,
	integer_string_signed as docs_json_ts_common_types_integer_string_signed,
	RGBA as docs_json_ts_common_types_RGBA,
	XYZ_decimal_string as docs_json_ts_common_types_XYZ_decimal_string,
	XYZ_integer_string as docs_json_ts_common_types_XYZ_integer_string,
} from './../../common/types.ts';

import type {
	FGBuildable_docking_station_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildable_docking_station_base_base_base,
	FGBuildable_docking_station_base_with_mMapText as docs_json_ts_0_3_7_7_classes_base_FGBuildable_docking_station_base_with_mMapText,
	FGBuildable_pole_with_length_and_power_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildable_pole_with_length_and_power_base_base,
	FGBuildable_powered_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildable_powered_base_base_base,
	FGBuildable_powered_base_resources_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildable_powered_base_resources_base_base,
	FGBuildable_powered_storage_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildable_powered_storage_base_base_base,
	FGBuildableAttachment_splitter_pre_update7 as docs_json_ts_0_3_7_7_classes_base_FGBuildableAttachment_splitter_pre_update7,
	FGBuildableAttachmentMerger_pre_update7 as docs_json_ts_0_3_7_7_classes_base_FGBuildableAttachmentMerger_pre_update7,
	FGBuildableDockingStation_with_mFuelTransferSpeed_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableDockingStation_with_mFuelTransferSpeed_base,
	FGBuildableFactory_jump_pad_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableFactory_jump_pad_base_base_base,
	FGBuildableFactory_landing_pad_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableFactory_landing_pad_base_base_base,
	FGBuildableFactorySimpleProducer_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableFactorySimpleProducer_base_base,
	FGBuildableGenerator_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableGenerator_base_base_base,
	FGBuildableGenerator_no_fuel_base_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableGenerator_no_fuel_base_base_base_base,
	FGBuildableGeneratorFuel_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableGeneratorFuel_base_base_base,
	FGBuildableGeneratorFuel_biomass_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableGeneratorFuel_biomass_base_base,
	FGBuildableGeneratorFuel_coal_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableGeneratorFuel_coal_base_base,
	FGBuildableGeneratorFuel_fuel_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableGeneratorFuel_fuel_base_base,
	FGBuildableGeneratorGeoThermal_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableGeneratorGeoThermal_base_base_base,
	FGBuildableGeneratorNuclear_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableGeneratorNuclear_base_base_base,
	FGBuildableJumppad_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableJumppad_base_base_base,
	FGBuildableManufacturer_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_base_base,
	FGBuildableManufacturer_base_IsPowered_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_IsPowered_base_base,
	FGBuildableManufacturer_base_mProductionEffectsRunning_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_mProductionEffectsRunning_base_base,
	FGBuildableManufacturer_base_packager_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_packager_base_base,
	FGBuildablePipelinePump_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildablePipelinePump_base_base_base,
	FGBuildablePipelinePump_powered_base_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildablePipelinePump_powered_base_base_base_base,
	FGBuildablePipelinePump_pump_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildablePipelinePump_pump_base_base_base,
	FGBuildablePipeReservoir_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildablePipeReservoir_base_base_base,
	FGBuildableRailroadStation_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableRailroadStation_base_base,
	FGBuildableResourceExtractor_base_base_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_base_base_base_base_base,
	FGBuildableResourceExtractor_base_base_base_piped_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_base_base_base_piped_base,
	FGBuildableResourceExtractor_base_base_timed_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_base_base_timed_base,
	FGBuildableResourceExtractor_miner_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_miner_base_base_base,
	FGBuildableResourceExtractor_miner_mk2_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_miner_mk2_base_base_base,
	FGBuildableResourceExtractor_miner_mk3_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_miner_mk3_base_base_base,
	FGBuildableResourceExtractor_oil_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_oil_base_base_base,
	FGBuildableResourceExtractor_water_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_water_base_base_base,
	FGBuildableResourceSinkShop_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceSinkShop_base_base_base,
	FGBuildableSplitterSmart_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableSplitterSmart_base_base_base,
	FGBuildableStorage_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableStorage_base_base_base,
	FGBuildableTradingPost_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableTradingPost_base_base,
	FGBuildableTrainPlatformCargo_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableTrainPlatformCargo_base_base,
	FGJetPack_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGJetPack_base_base_base,
	FGPipeHyperStart_base_base as docs_json_ts_0_3_7_7_classes_base_FGPipeHyperStart_base_base,
} from './../../0.3.7.7/classes/Base.ts';

import type {
	FGBuildable_occupied as docs_json_ts_0_5_2_1_classes_base_FGBuildable_occupied,
	FGBuildable_powered_base_base as docs_json_ts_0_5_2_1_classes_base_FGBuildable_powered_base_base,
	FGBuildable_tiered as docs_json_ts_0_5_2_1_classes_base_FGBuildable_tiered,
	FGBuildable_with_size_and_elevation as docs_json_ts_0_5_2_1_classes_base_FGBuildable_with_size_and_elevation,
	FGBuildableCircuitSwitch as docs_json_ts_0_5_2_1_classes_base_FGBuildableCircuitSwitch,
	FGBuildableConveyorBelt_spline as docs_json_ts_0_5_2_1_classes_base_FGBuildableConveyorBelt_spline,
	FGBuildableConveyorLift as docs_json_ts_0_5_2_1_classes_base_FGBuildableConveyorLift,
	FGBuildableDockingStation_base as docs_json_ts_0_5_2_1_classes_base_FGBuildableDockingStation_base,
	FGBuildableFloodlight as docs_json_ts_0_5_2_1_classes_base_FGBuildableFloodlight,
	FGBuildableLadder as docs_json_ts_0_5_2_1_classes_base_FGBuildableLadder,
	FGBuildableLightsControlPanel as docs_json_ts_0_5_2_1_classes_base_FGBuildableLightsControlPanel,
	FGBuildableLightSource as docs_json_ts_0_5_2_1_classes_base_FGBuildableLightSource,
	FGBuildableLightSource_Build_StreetLight_C as docs_json_ts_0_5_2_1_classes_base_FGBuildableLightSource_Build_StreetLight_C,
	FGBuildableMAM as docs_json_ts_0_5_2_1_classes_base_FGBuildableMAM,
	FGBuildableManufacturer_Build_ConstructorMk1_C_base as docs_json_ts_0_5_2_1_classes_base_FGBuildableManufacturer_Build_ConstructorMk1_C_base,
	FGBuildableManufacturer_Build_FoundryMk1_C_base as docs_json_ts_0_5_2_1_classes_base_FGBuildableManufacturer_Build_FoundryMk1_C_base,
	FGBuildablePassthrough as docs_json_ts_0_5_2_1_classes_base_FGBuildablePassthrough,
	FGBuildablePipeHyper as docs_json_ts_0_5_2_1_classes_base_FGBuildablePipeHyper,
	FGBuildablePipelineSupport as docs_json_ts_0_5_2_1_classes_base_FGBuildablePipelineSupport,
	FGBuildablePowerPole as docs_json_ts_0_5_2_1_classes_base_FGBuildablePowerPole,
	FGBuildableRailroadSignal_base as docs_json_ts_0_5_2_1_classes_base_FGBuildableRailroadSignal_base,
	FGBuildableRailroadSignal_block as docs_json_ts_0_5_2_1_classes_base_FGBuildableRailroadSignal_block,
	FGBuildableRailroadStation_base as docs_json_ts_0_5_2_1_classes_base_FGBuildableRailroadStation_base,
	FGBuildableStair as docs_json_ts_0_5_2_1_classes_base_FGBuildableStair,
	FGBuildableTradingPost_base as docs_json_ts_0_5_2_1_classes_base_FGBuildableTradingPost_base,
	FGBuildableTrainPlatform_base as docs_json_ts_0_5_2_1_classes_base_FGBuildableTrainPlatform_base,
	FGBuildableTrainPlatform_non_empty as docs_json_ts_0_5_2_1_classes_base_FGBuildableTrainPlatform_non_empty,
	FGBuildableTrainPlatformCargo_version_specific as docs_json_ts_0_5_2_1_classes_base_FGBuildableTrainPlatformCargo_version_specific,
	FGBuildableWidgetSign as docs_json_ts_0_5_2_1_classes_base_FGBuildableWidgetSign,
	FGBuildableWire as docs_json_ts_0_5_2_1_classes_base_FGBuildableWire,
} from './../../0.5.2.1/classes/Base.ts';

import type {
	FGBuildable_mStopped_audio_stuff_base as docs_json_ts_0_4_2_11_classes_base_FGBuildable_mStopped_audio_stuff_base,
	FGBuildable_powered_base_base as docs_json_ts_0_4_2_11_classes_base_FGBuildable_powered_base_base,
	FGBuildableDroneStation_base_base_base as docs_json_ts_0_4_2_11_classes_base_FGBuildableDroneStation_base_base_base,
	FGBuildableFrackingActivator_base_base as docs_json_ts_0_4_2_11_classes_base_FGBuildableFrackingActivator_base_base,
	FGBuildableGeneratorFuel_base_base_base as docs_json_ts_0_4_2_11_classes_base_FGBuildableGeneratorFuel_base_base_base,
	FGBuildableGeneratorGeoThermal_base as docs_json_ts_0_4_2_11_classes_base_FGBuildableGeneratorGeoThermal_base,
	FGBuildableGeneratorNuclear_base as docs_json_ts_0_4_2_11_classes_base_FGBuildableGeneratorNuclear_base,
	FGBuildableManufacturer_base_blender_base_base as docs_json_ts_0_4_2_11_classes_base_FGBuildableManufacturer_base_blender_base_base,
	FGBuildableManufacturer_base_constructor_base_base as docs_json_ts_0_4_2_11_classes_base_FGBuildableManufacturer_base_constructor_base_base,
	FGBuildableManufacturer_Build_HadronCollider_C_base as docs_json_ts_0_4_2_11_classes_base_FGBuildableManufacturer_Build_HadronCollider_C_base,
	FGBuildablePipelineJunction_base_base_base as docs_json_ts_0_4_2_11_classes_base_FGBuildablePipelineJunction_base_base_base,
	FGBuildablePowerStorage_base as docs_json_ts_0_4_2_11_classes_base_FGBuildablePowerStorage_base,
	FGBuildableResourceExtractor_miner_mk1_base_base_base as docs_json_ts_0_4_2_11_classes_base_FGBuildableResourceExtractor_miner_mk1_base_base_base,
	FGBuildableResourceExtractor_water_base as docs_json_ts_0_4_2_11_classes_base_FGBuildableResourceExtractor_water_base,
	FGBuildableResourceSink_base_base as docs_json_ts_0_4_2_11_classes_base_FGBuildableResourceSink_base_base,
} from './../../0.4.2.11/classes/Base.ts';

import type {
	DocsDotJson_BlueprintGeneratedClass_quoted_list as docs_json_ts_0_3_7_7_properties_DocsDotJson_BlueprintGeneratedClass_quoted_list,
} from './../../0.3.7.7/types/properties.ts';

type FGBuildable_base = FGBuildable_base_pre_update8 & docs_json_ts_0_6_1_5_classes_base_FGBuildable_base;

type FGBuildable_base_pre_update8 = {
	mContainsComponents: docs_json_ts_common_types_bool_string,
	mIsMultiSpawnedBuildable: docs_json_ts_common_types_bool_string,
	mCanContainLightweightInstances: docs_json_ts_common_types_bool_string,
	mBlueprintBuildEffectID: docs_json_ts_common_types_integer_string_signed,
};

type FGBuildable_docking_station = docs_json_ts_0_3_7_7_classes_base_FGBuildable_docking_station_base_with_mMapText & FGBuildable_powered_storage;

type FGBuildable_occupied = docs_json_ts_0_5_2_1_classes_base_FGBuildable_occupied & FGBuildable_base;

type FGBuildable_powered = FGBuildable_powered_pre_update8 & FGBuildable_powered_base;

type FGBuildable_powered_base = docs_json_ts_0_3_7_7_classes_base_FGBuildable_powered_base_base_base & docs_json_ts_0_5_2_1_classes_base_FGBuildable_powered_base_base & docs_json_ts_0_4_2_11_classes_base_FGBuildable_powered_base_base & FGBuildable_base;

type FGBuildable_powered_pre_update8 = {
	mCanEverMonitorProductivity: docs_json_ts_common_types_bool_string,
	mDefaultProductivityMeasurementDuration: docs_json_ts_common_types_decimal_string,
	mLastProductivityMeasurementProduceDuration: docs_json_ts_common_types_decimal_string,
	mLastProductivityMeasurementDuration: docs_json_ts_common_types_decimal_string,
	mCurrentProductivityMeasurementProduceDuration: docs_json_ts_common_types_decimal_string,
	mCurrentProductivityMeasurementDuration: docs_json_ts_common_types_decimal_string,
	mProductivityMonitorEnabled: docs_json_ts_common_types_bool_string,
};

type FGBuildable_powered_storage = docs_json_ts_0_3_7_7_classes_base_FGBuildable_powered_storage_base_base_base & docs_json_ts_0_4_2_11_classes_base_FGBuildable_powered_base_base & FGBuildable_powered;

type FGBuildable_tiered = docs_json_ts_0_5_2_1_classes_base_FGBuildable_tiered & FGBuildable_base;

type FGBuildableAttachmentMerger = docs_json_ts_0_3_7_7_classes_base_FGBuildableAttachmentMerger_pre_update7 & FGBuildable_base;

type FGBuildableAttachmentSplitter = docs_json_ts_0_3_7_7_classes_base_FGBuildableAttachment_splitter_pre_update7 & FGBuildable_base;

type FGBuildableBeamLightweight = docs_json_ts_0_6_1_5_classes_base_FGBuildableBeam & FGBuildable_base;

type FGBuildableBlueprintDesigner = FGBuildableBlueprintDesigner_pre_update8 & FGBuildable_base;

type FGBuildableBlueprintDesigner_pre_update8 = {
	mTerminalDistanceFromEdge: docs_json_ts_common_types_decimal_string,
	mTerminalHalfDepth: docs_json_ts_common_types_decimal_string,
	mDimensions: docs_json_ts_common_types_XYZ_integer_string,
	OnRecordDataChanged: docs_json_ts_common_types_empty_object,
	OnBlueprintCostChanged: docs_json_ts_common_types_empty_object,
	mCurrentCost: '',
	mBuildables: '',
	mIntersectComponents: '',
	mCurrentRecordData: {
		IconID: docs_json_ts_common_types_integer_string_signed,
		Color: docs_json_ts_common_types_RGBA,
	},
};

type FGBuildableCircuitSwitch = docs_json_ts_0_5_2_1_classes_base_FGBuildableCircuitSwitch & FGBuildableCircuitSwitch_version_specific & FGBuildable_base;

type FGBuildableCircuitSwitch_version_specific = {
	mOnBuildingTagChanged: docs_json_ts_common_types_empty_object,
};

type FGBuildableConveyorBelt = docs_json_ts_0_5_2_1_classes_base_FGBuildableConveyorBelt_spline & FGBuildable_base;

type FGBuildableConveyorLift = docs_json_ts_0_5_2_1_classes_base_FGBuildableConveyorLift & FGBuildable_base;

type FGBuildableCornerWall = docs_json_ts_0_6_1_5_classes_base_FGBuildableCornerWall & FGBuildable_base;

type FGBuildableDockingStation = docs_json_ts_0_5_2_1_classes_base_FGBuildableDockingStation_base & docs_json_ts_0_3_7_7_classes_base_FGBuildable_docking_station_base_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableDockingStation_with_mFuelTransferSpeed_base & FGBuildable_powered;

type FGBuildableDoor = docs_json_ts_0_6_1_5_classes_base_FGBuildableDoor & FGBuildable_base;

type FGBuildableDroneStation = docs_json_ts_0_4_2_11_classes_base_FGBuildableDroneStation_base_base_base & FGBuildable_docking_station & docs_json_ts_0_6_1_5_classes_base_FGBuildable_base;

type FGBuildableFactory_jump_pad = FGBuildable_powered & docs_json_ts_0_3_7_7_classes_base_FGBuildableFactory_jump_pad_base_base_base;

type FGBuildableFactory_landing_pad = FGBuildable_powered & docs_json_ts_0_3_7_7_classes_base_FGBuildableFactory_landing_pad_base_base_base;

type FGBuildableFactorySimpleProducer = FGBuildable_powered & docs_json_ts_0_3_7_7_classes_base_FGBuildableFactorySimpleProducer_base_base;

type FGBuildableFloodlight = docs_json_ts_0_5_2_1_classes_base_FGBuildableFloodlight & FGBuildable_base;

type FGBuildableFoundation = docs_json_ts_0_6_1_5_classes_base_FGBuildableFoundation & FGBuildable_base;

type FGBuildableFrackingActivator = docs_json_ts_0_4_2_11_classes_base_FGBuildableFrackingActivator_base_base & docs_json_ts_0_6_1_5_classes_base_FGBuildableResourceExtractor_base_version_specific_base & FGBuildable_powered;

type FGBuildableFrackingExtractor = docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_base_base_timed_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_base_base_base_piped_base & docs_json_ts_0_6_1_5_classes_base_FGBuildableResourceExtractor_base_version_specific_base & FGBuildable_powered;

type FGBuildableGenerator = FGBuildableGenerator_no_fuel & docs_json_ts_0_3_7_7_classes_base_FGBuildableGenerator_base_base_base;

type FGBuildableGenerator_no_fuel = docs_json_ts_0_3_7_7_classes_base_FGBuildableGenerator_no_fuel_base_base_base_base & FGBuildable_powered;

type FGBuildableGeneratorFuel_biomass = FGBuildableGenerator & docs_json_ts_0_4_2_11_classes_base_FGBuildableGeneratorFuel_base_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableGeneratorFuel_biomass_base_base;

type FGBuildableGeneratorFuel_coal = FGBuildableGenerator & docs_json_ts_0_4_2_11_classes_base_FGBuildableGeneratorFuel_base_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableGeneratorFuel_coal_base_base;

type FGBuildableGeneratorFuel_fuel = FGBuildableGenerator & docs_json_ts_0_4_2_11_classes_base_FGBuildableGeneratorFuel_base_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableGeneratorFuel_base_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableGeneratorFuel_fuel_base_base;

type FGBuildableGeneratorGeoThermal = FGBuildableGenerator_no_fuel & docs_json_ts_0_3_7_7_classes_base_FGBuildableGeneratorGeoThermal_base_base_base & docs_json_ts_0_4_2_11_classes_base_FGBuildableGeneratorGeoThermal_base;

type FGBuildableGeneratorNuclear = FGBuildableGenerator & docs_json_ts_0_4_2_11_classes_base_FGBuildableGeneratorFuel_base_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableGeneratorNuclear_base_base_base & docs_json_ts_0_4_2_11_classes_base_FGBuildableGeneratorNuclear_base;

type FGBuildableJumppad = docs_json_ts_0_3_7_7_classes_base_FGBuildableJumppad_base_base_base & FGBuildable_powered;

type FGBuildableLadder = docs_json_ts_0_5_2_1_classes_base_FGBuildableLadder & FGBuildable_base;

type FGBuildableLightsControlPanel = docs_json_ts_0_5_2_1_classes_base_FGBuildableLightsControlPanel & FGBuildable_base;

type FGBuildableLightSource_Build_CeilingLight_C = docs_json_ts_0_5_2_1_classes_base_FGBuildableLightSource & FGBuildable_base;

type FGBuildableLightSource_Build_StreetLight_C = docs_json_ts_0_5_2_1_classes_base_FGBuildableLightSource_Build_StreetLight_C & FGBuildable_base;

type FGBuildableMAM = docs_json_ts_0_5_2_1_classes_base_FGBuildableMAM & FGBuildable_base;

type FGBuildableManufacturer_Build_AssemblerMk1_C = docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_IsPowered_base_base & FGBuildable_powered;

type FGBuildableManufacturer_Build_Blender_C = docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_base_base & docs_json_ts_0_4_2_11_classes_base_FGBuildableManufacturer_base_blender_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_IsPowered_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_mProductionEffectsRunning_base_base & FGBuildable_powered;

type FGBuildableManufacturer_Build_ConstructorMk1_C = docs_json_ts_0_4_2_11_classes_base_FGBuildableManufacturer_base_constructor_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_IsPowered_base_base & FGBuildable_powered & docs_json_ts_0_5_2_1_classes_base_FGBuildableManufacturer_Build_ConstructorMk1_C_base;

type FGBuildableManufacturer_Build_FoundryMk1_C = docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_mProductionEffectsRunning_base_base & FGBuildable_powered & docs_json_ts_0_5_2_1_classes_base_FGBuildableManufacturer_Build_FoundryMk1_C_base;

type FGBuildableManufacturer_Build_HadronCollider_C = docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_IsPowered_base_base & FGBuildable_powered & docs_json_ts_0_4_2_11_classes_base_FGBuildableManufacturer_Build_HadronCollider_C_base;

type FGBuildableManufacturer_Build_ManufacturerMk1_C = docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_base_base & docs_json_ts_0_4_2_11_classes_base_FGBuildable_mStopped_audio_stuff_base & FGBuildable_powered;

type FGBuildableManufacturer_Build_OilRefinery_C = docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_IsPowered_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_mProductionEffectsRunning_base_base & FGBuildable_powered;

type FGBuildableManufacturer_Build_Packager_C = docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_IsPowered_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_mProductionEffectsRunning_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_packager_base_base & FGBuildable_powered;

type FGBuildableManufacturer_Build_SmelterMk1_C = docs_json_ts_0_6_1_5_classes_base_FGBuildableManufacturer_Build_SmelterMk1_C_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_mProductionEffectsRunning_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_base_base & FGBuildable_powered;

type FGBuildablePassthrough = docs_json_ts_0_5_2_1_classes_base_FGBuildablePassthrough & FGBuildable_base;

type FGBuildablePillarLightweight = docs_json_ts_0_6_1_5_classes_base_FGBuildablePillar & FGBuildable_base;

type FGBuildablePipeHyper = docs_json_ts_0_5_2_1_classes_base_FGBuildablePipeHyper & FGBuildable_base;

type FGBuildablePipeline = docs_json_ts_0_6_1_5_classes_base_FGBuildablePipeline & FGBuildable_base;

type FGBuildablePipelineJunction = docs_json_ts_0_4_2_11_classes_base_FGBuildablePipelineJunction_base_base_base & FGBuildable_powered;

type FGBuildablePipelinePump_pump = docs_json_ts_0_3_7_7_classes_base_FGBuildablePipelinePump_pump_base_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildablePipelinePump_powered_base_base_base_base & FGBuildable_powered;

type FGBuildablePipelinePump_valve = docs_json_ts_0_3_7_7_classes_base_FGBuildablePipelinePump_base_base_base & FGBuildable_powered;

type FGBuildablePipelineSupport = docs_json_ts_0_5_2_1_classes_base_FGBuildablePipelineSupport & FGBuildable_base;

type FGBuildablePipeReservoir = FGBuildable_powered & docs_json_ts_0_3_7_7_classes_base_FGBuildablePipeReservoir_base_base_base;

type FGBuildablePole = FGBuildablePole_version_specific & FGBuildablePole_base;

type FGBuildablePole_base = docs_json_ts_0_6_1_5_classes_base_FGBuildablePole & FGBuildable_base;

type FGBuildablePole_version_specific = {
	mSelectedPoleVersion: docs_json_ts_common_types_integer_string_signed,
};

type FGBuildablePowerPole = docs_json_ts_0_5_2_1_classes_base_FGBuildablePowerPole & FGBuildable_base;

type FGBuildablePowerStorage = FGBuildable_powered & docs_json_ts_0_4_2_11_classes_base_FGBuildablePowerStorage_base;

type FGBuildableRadarTower = FGBuildable_powered & docs_json_ts_0_6_1_5_classes_base_FGBuildableRadarTower_base;

type FGBuildableRailroadSignal_base = docs_json_ts_0_5_2_1_classes_base_FGBuildableRailroadSignal_base & FGBuildable_base;

type FGBuildableRailroadSignal_block = docs_json_ts_0_5_2_1_classes_base_FGBuildableRailroadSignal_block & FGBuildable_base;

type FGBuildableRailroadStation = docs_json_ts_0_5_2_1_classes_base_FGBuildableRailroadStation_base & docs_json_ts_0_5_2_1_classes_base_FGBuildableTrainPlatform_base & docs_json_ts_0_5_2_1_classes_base_FGBuildableTrainPlatform_non_empty & docs_json_ts_0_3_7_7_classes_base_FGBuildableRailroadStation_base_base & FGBuildable_powered;

type FGBuildableRailroadTrack = docs_json_ts_0_6_1_5_classes_base_FGBuildableRailroadTrack & FGBuildable_base;

type FGBuildableRamp = docs_json_ts_0_6_1_5_classes_base_FGBuildableRamp & FGBuildable_base;

type FGBuildableResourceExtractor_base = docs_json_ts_0_6_1_5_classes_base_FGBuildableResourceExtractor_base_version_specific_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_base_base_base_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_base_base_base_piped_base & docs_json_ts_0_3_7_7_classes_base_FGBuildable_powered_base_resources_base_base & FGBuildable_powered;

type FGBuildableResourceExtractor_miner_mk1 = docs_json_ts_0_4_2_11_classes_base_FGBuildableResourceExtractor_miner_mk1_base_base_base & FGBuildableResourceExtractor_base;

type FGBuildableResourceExtractor_miner_mk2 = docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_miner_mk2_base_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_miner_base_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_base_base_timed_base & FGBuildableResourceExtractor_base;

type FGBuildableResourceExtractor_miner_mk3 = docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_miner_mk3_base_base_base & FGBuildableResourceExtractor_base;

type FGBuildableResourceExtractor_oil = docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_oil_base_base_base & FGBuildableResourceExtractor_base;

type FGBuildableResourceExtractor_water = docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_water_base_base_base & docs_json_ts_0_4_2_11_classes_base_FGBuildableResourceExtractor_water_base & FGBuildableResourceExtractor_base;

type FGBuildableResourceSink = FGBuildable_powered & docs_json_ts_0_4_2_11_classes_base_FGBuildableResourceSink_base_base;

type FGBuildableResourceSinkShop = FGBuildable_powered & docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceSinkShop_base_base_base;

type FGBuildableSplitterSmart = docs_json_ts_0_3_7_7_classes_base_FGBuildableSplitterSmart_base_base_base & FGBuildable_base;

type FGBuildableStair = docs_json_ts_0_5_2_1_classes_base_FGBuildableStair & FGBuildable_base;

type FGBuildableStorage = docs_json_ts_0_3_7_7_classes_base_FGBuildableStorage_base_base_base & FGBuildable_powered;

type FGBuildableTradingPost = docs_json_ts_0_3_7_7_classes_base_FGBuildableTradingPost_base_base & docs_json_ts_0_5_2_1_classes_base_FGBuildableTradingPost_base & FGBuildable_powered;

type FGBuildableTrainPlatformCargo = docs_json_ts_0_6_1_5_classes_base_FGBuildableTrainPlatformCargo_version_specific & docs_json_ts_0_5_2_1_classes_base_FGBuildableTrainPlatformCargo_version_specific & FGBuildable_powered_storage & docs_json_ts_0_5_2_1_classes_base_FGBuildableTrainPlatform_non_empty & docs_json_ts_0_3_7_7_classes_base_FGBuildableTrainPlatformCargo_base_base;

type FGBuildableTrainPlatformEmpty = docs_json_ts_0_5_2_1_classes_base_FGBuildableTrainPlatform_base & FGBuildable_powered;

type FGBuildableWalkway = docs_json_ts_0_5_2_1_classes_base_FGBuildable_with_size_and_elevation & FGBuildable_base;

type FGBuildableWall = docs_json_ts_0_6_1_5_classes_base_FGBuildableWall & FGBuildable_base;

type FGBuildableWidgetSign = docs_json_ts_0_5_2_1_classes_base_FGBuildableWidgetSign & FGBuildable_base;

type FGBuildableWire = FGBuildableWire_version_specific & FGBuildableWire_base;

type FGBuildableWire_base = docs_json_ts_0_5_2_1_classes_base_FGBuildableWire & FGBuildable_base;

type FGBuildableWire_version_specific = {
	mCachedRelativeLocations: docs_json_ts_common_types_XYZ_decimal_string,
};

type FGJetPack = docs_json_ts_0_3_7_7_classes_base_FGJetPack_base_base_base & docs_json_ts_0_6_1_5_classes_base_FGEquipment & FGJetPack_version_specific;

type FGJetPack_version_specific = {
	mFuelTypes: docs_json_ts_0_3_7_7_properties_DocsDotJson_BlueprintGeneratedClass_quoted_list,
	mSelectedFuelType: docs_json_ts_common_types_integer_string,
	mCurrentFuelType: docs_json_ts_common_types_integer_string,
};

type FGPipeHyperStart = docs_json_ts_0_3_7_7_classes_base_FGPipeHyperStart_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildable_pole_with_length_and_power_base_base & FGBuildable_powered;

export type {
	FGBuildable_base,
	FGBuildable_base_pre_update8,
	FGBuildable_docking_station,
	FGBuildable_occupied,
	FGBuildable_powered,
	FGBuildable_powered_base,
	FGBuildable_powered_pre_update8,
	FGBuildable_powered_storage,
	FGBuildable_tiered,
	FGBuildableAttachmentMerger,
	FGBuildableAttachmentSplitter,
	FGBuildableBeamLightweight,
	FGBuildableBlueprintDesigner,
	FGBuildableBlueprintDesigner_pre_update8,
	FGBuildableCircuitSwitch,
	FGBuildableCircuitSwitch_version_specific,
	FGBuildableConveyorBelt,
	FGBuildableConveyorLift,
	FGBuildableCornerWall,
	FGBuildableDockingStation,
	FGBuildableDoor,
	FGBuildableDroneStation,
	FGBuildableFactory_jump_pad,
	FGBuildableFactory_landing_pad,
	FGBuildableFactorySimpleProducer,
	FGBuildableFloodlight,
	FGBuildableFoundation,
	FGBuildableFrackingActivator,
	FGBuildableFrackingExtractor,
	FGBuildableGenerator,
	FGBuildableGenerator_no_fuel,
	FGBuildableGeneratorFuel_biomass,
	FGBuildableGeneratorFuel_coal,
	FGBuildableGeneratorFuel_fuel,
	FGBuildableGeneratorGeoThermal,
	FGBuildableGeneratorNuclear,
	FGBuildableJumppad,
	FGBuildableLadder,
	FGBuildableLightsControlPanel,
	FGBuildableLightSource_Build_CeilingLight_C,
	FGBuildableLightSource_Build_StreetLight_C,
	FGBuildableMAM,
	FGBuildableManufacturer_Build_AssemblerMk1_C,
	FGBuildableManufacturer_Build_Blender_C,
	FGBuildableManufacturer_Build_ConstructorMk1_C,
	FGBuildableManufacturer_Build_FoundryMk1_C,
	FGBuildableManufacturer_Build_HadronCollider_C,
	FGBuildableManufacturer_Build_ManufacturerMk1_C,
	FGBuildableManufacturer_Build_OilRefinery_C,
	FGBuildableManufacturer_Build_Packager_C,
	FGBuildableManufacturer_Build_SmelterMk1_C,
	FGBuildablePassthrough,
	FGBuildablePillarLightweight,
	FGBuildablePipeHyper,
	FGBuildablePipeline,
	FGBuildablePipelineJunction,
	FGBuildablePipelinePump_pump,
	FGBuildablePipelinePump_valve,
	FGBuildablePipelineSupport,
	FGBuildablePipeReservoir,
	FGBuildablePole,
	FGBuildablePole_base,
	FGBuildablePole_version_specific,
	FGBuildablePowerPole,
	FGBuildablePowerStorage,
	FGBuildableRadarTower,
	FGBuildableRailroadSignal_base,
	FGBuildableRailroadSignal_block,
	FGBuildableRailroadStation,
	FGBuildableRailroadTrack,
	FGBuildableRamp,
	FGBuildableResourceExtractor_base,
	FGBuildableResourceExtractor_miner_mk1,
	FGBuildableResourceExtractor_miner_mk2,
	FGBuildableResourceExtractor_miner_mk3,
	FGBuildableResourceExtractor_oil,
	FGBuildableResourceExtractor_water,
	FGBuildableResourceSink,
	FGBuildableResourceSinkShop,
	FGBuildableSplitterSmart,
	FGBuildableStair,
	FGBuildableStorage,
	FGBuildableTradingPost,
	FGBuildableTrainPlatformCargo,
	FGBuildableTrainPlatformEmpty,
	FGBuildableWalkway,
	FGBuildableWall,
	FGBuildableWidgetSign,
	FGBuildableWire,
	FGBuildableWire_base,
	FGBuildableWire_version_specific,
	FGJetPack,
	FGJetPack_version_specific,
	FGPipeHyperStart,
};
