/* eslint-disable @stylistic/max-len */

import type {
	FGBuildable_base_version_specific as docs_json_ts_0_6_1_5_classes_base_overridable_FGBuildable_base_version_specific,
	FGBuildableRadarTower_version_specific as docs_json_ts_0_6_1_5_classes_base_overridable_FGBuildableRadarTower_version_specific,
} from './../../0.6.1.5/classes/Base.overridable.ts';

import type {
	FGBuildable_base_pre_1_0 as docs_json_ts_0_3_7_7_classes_base_FGBuildable_base_pre_1_0,
	FGBuildable_base_version_specific as docs_json_ts_0_3_7_7_classes_base_FGBuildable_base_version_specific,
	FGBuildable_docking_station_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildable_docking_station_base_base_base,
	FGBuildable_docking_station_base_with_mMapText as docs_json_ts_0_3_7_7_classes_base_FGBuildable_docking_station_base_with_mMapText,
	FGBuildable_occupied_base as docs_json_ts_0_3_7_7_classes_base_FGBuildable_occupied_base,
	FGBuildable_powered_pre_1_0 as docs_json_ts_0_3_7_7_classes_base_FGBuildable_powered_pre_1_0,
	FGBuildable_powered_storage_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildable_powered_storage_base_base_base,
	FGBuildable_powered_version_specific as docs_json_ts_0_3_7_7_classes_base_FGBuildable_powered_version_specific,
	FGBuildable_tiered_base as docs_json_ts_0_3_7_7_classes_base_FGBuildable_tiered_base,
	FGBuildable_with_mLength as docs_json_ts_0_3_7_7_classes_base_FGBuildable_with_mLength,
	FGBuildableAttachment_has_mCurrentOutputIndex as docs_json_ts_0_3_7_7_classes_base_FGBuildableAttachment_has_mCurrentOutputIndex,
	FGBuildableAttachment_splitter_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableAttachment_splitter_base_base_base,
	FGBuildableAttachmentMerger_version_specific as docs_json_ts_0_3_7_7_classes_base_FGBuildableAttachmentMerger_version_specific,
	FGBuildableConveyorBelt_pre_1_0 as docs_json_ts_0_3_7_7_classes_base_FGBuildableConveyorBelt_pre_1_0,
	FGBuildableConveyorBelt_pre_update8 as docs_json_ts_0_3_7_7_classes_base_FGBuildableConveyorBelt_pre_update8,
	FGBuildableConveyorLift_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableConveyorLift_base,
	FGBuildableDockingStation_with_mFuelTransferSpeed_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableDockingStation_with_mFuelTransferSpeed_base,
	FGBuildableFactory_jump_pad_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableFactory_jump_pad_base_base_base,
	FGBuildableFactory_landing_pad_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableFactory_landing_pad_base_base_base,
	FGBuildableFactorySimpleProducer_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableFactorySimpleProducer_base_base,
	FGBuildableGenerator_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableGenerator_base_base_base,
	FGBuildableGenerator_base_base_pre_1_0 as docs_json_ts_0_3_7_7_classes_base_FGBuildableGenerator_base_base_pre_1_0,
	FGBuildableGenerator_no_fuel_base_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableGenerator_no_fuel_base_base_base_base,
	FGBuildableGeneratorFuel_biomass_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableGeneratorFuel_biomass_base_base,
	FGBuildableGeneratorFuel_coal_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableGeneratorFuel_coal_base_base,
	FGBuildableGeneratorFuel_fuel_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableGeneratorFuel_fuel_base_base,
	FGBuildableGeneratorGeoThermal_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableGeneratorGeoThermal_base_base_base,
	FGBuildableGeneratorNuclear_version_specific as docs_json_ts_0_3_7_7_classes_base_FGBuildableGeneratorNuclear_version_specific,
	FGBuildableJumppad_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableJumppad_base_base_base,
	FGBuildableLadder_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableLadder_base,
	FGBuildableManufacturer_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_base_base,
	FGBuildableManufacturer_base_IsPowered_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_IsPowered_base_base,
	FGBuildableManufacturer_base_mProductionEffectsRunning_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_mProductionEffectsRunning_base_base,
	FGBuildableManufacturer_base_packager_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_packager_base_base,
	FGBuildablePipeline_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildablePipeline_base_base,
	FGBuildablePipeline_base_no_indicator_base as docs_json_ts_0_3_7_7_classes_base_FGBuildablePipeline_base_no_indicator_base,
	FGBuildablePipeline_base_root as docs_json_ts_0_3_7_7_classes_base_FGBuildablePipeline_base_root,
	FGBuildablePipelinePump_powered_version_specific as docs_json_ts_0_3_7_7_classes_base_FGBuildablePipelinePump_powered_version_specific,
	FGBuildablePipelinePump_pump_version_specific as docs_json_ts_0_3_7_7_classes_base_FGBuildablePipelinePump_pump_version_specific,
	FGBuildablePipelineSupport_base as docs_json_ts_0_3_7_7_classes_base_FGBuildablePipelineSupport_base,
	FGBuildablePipeReservoir_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildablePipeReservoir_base_base_base,
	FGBuildablePowerPole_base as docs_json_ts_0_3_7_7_classes_base_FGBuildablePowerPole_base,
	FGBuildableRailroadStation_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableRailroadStation_base_base,
	FGBuildableResourceExtractor_miner_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_miner_base,
	FGBuildableResourceExtractor_miner_mk2_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_miner_mk2_base_base_base,
	FGBuildableResourceExtractor_miner_mk3_version_specific as docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_miner_mk3_version_specific,
	FGBuildableResourceExtractor_oil_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_oil_base_base_base,
	FGBuildableResourceExtractor_only_allow_certain_resources as docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_only_allow_certain_resources,
	FGBuildableResourceExtractor_piped as docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_piped,
	FGBuildableResourceExtractor_piped_pre_1_0 as docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_piped_pre_1_0,
	FGBuildableResourceExtractor_timed as docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_timed,
	FGBuildableResourceExtractor_water_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_water_base_base_base,
	FGBuildableResourceSinkShop_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceSinkShop_base_base_base,
	FGBuildableSplitterSmart_version_specific as docs_json_ts_0_3_7_7_classes_base_FGBuildableSplitterSmart_version_specific,
	FGBuildableStorage_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableStorage_base_base_base,
	FGBuildableTradingPost_pre_1_0 as docs_json_ts_0_3_7_7_classes_base_FGBuildableTradingPost_pre_1_0,
	FGBuildableTradingPost_pre_update8 as docs_json_ts_0_3_7_7_classes_base_FGBuildableTradingPost_pre_update8,
	FGBuildableTradingPost_version_specific as docs_json_ts_0_3_7_7_classes_base_FGBuildableTradingPost_version_specific,
	FGBuildableTrainPlatform_with_storage_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableTrainPlatform_with_storage_base_base_base,
	FGBuildableTrainPlatformCargo_pre_update8 as docs_json_ts_0_3_7_7_classes_base_FGBuildableTrainPlatformCargo_pre_update8,
	FGBuildableTrainPlatformCargo_version_specific as docs_json_ts_0_3_7_7_classes_base_FGBuildableTrainPlatformCargo_version_specific,
	FGBuildableWire_base as docs_json_ts_0_3_7_7_classes_base_FGBuildableWire_base,
	FGJetPack_pre_1_0 as docs_json_ts_0_3_7_7_classes_base_FGJetPack_pre_1_0,
	FGJetPack_version_specific as docs_json_ts_0_3_7_7_classes_base_FGJetPack_version_specific,
	FGPipeHyperStart_base_base_base as docs_json_ts_0_3_7_7_classes_base_FGPipeHyperStart_base_base_base,
	FGPipeHyperStart_pre_update8 as docs_json_ts_0_3_7_7_classes_base_FGPipeHyperStart_pre_update8,
	has_mCanStack as docs_json_ts_0_3_7_7_classes_base_has_mCanStack,
	has_mDisableSnapOn as docs_json_ts_0_3_7_7_classes_base_has_mDisableSnapOn,
	has_mElevation as docs_json_ts_0_3_7_7_classes_base_has_mElevation,
	has_mHeight as docs_json_ts_0_3_7_7_classes_base_has_mHeight,
	has_mMeshLength as docs_json_ts_0_3_7_7_classes_base_has_mMeshLength,
	has_mRTPCInterval as docs_json_ts_0_3_7_7_classes_base_has_mRTPCInterval,
	has_mSize as docs_json_ts_0_3_7_7_classes_base_has_mSize,
	has_mSplineData as docs_json_ts_0_3_7_7_classes_base_has_mSplineData,
	has_mStackHeight as docs_json_ts_0_3_7_7_classes_base_has_mStackHeight,
	has_mUseStaticHeight as docs_json_ts_0_3_7_7_classes_base_has_mUseStaticHeight,
	has_mWidth as docs_json_ts_0_3_7_7_classes_base_has_mWidth,
} from './../../0.3.7.7/classes/Base.ts';

import type {
	FGBuildable_base_version_specific as docs_json_ts_0_4_2_11_classes_base_FGBuildable_base_version_specific,
	FGBuildable_has_mCachedSkeletalMeshes as docs_json_ts_0_4_2_11_classes_base_FGBuildable_has_mCachedSkeletalMeshes,
	FGBuildable_light_related_thing_base as docs_json_ts_0_4_2_11_classes_base_FGBuildable_light_related_thing_base,
	FGBuildable_mStopped_audio_stuff as docs_json_ts_0_4_2_11_classes_base_FGBuildable_mStopped_audio_stuff,
	FGBuildableCircuitSwitch_base as docs_json_ts_0_4_2_11_classes_base_FGBuildableCircuitSwitch_base,
	FGBuildableDroneStation_pre_1_0 as docs_json_ts_0_4_2_11_classes_base_FGBuildableDroneStation_pre_1_0,
	FGBuildableDroneStation_version_specific as docs_json_ts_0_4_2_11_classes_base_FGBuildableDroneStation_version_specific,
	FGBuildableFloodlight_version_specific as docs_json_ts_0_4_2_11_classes_base_FGBuildableFloodlight_version_specific,
	FGBuildableFrackingActivator_version_specific as docs_json_ts_0_4_2_11_classes_base_FGBuildableFrackingActivator_version_specific,
	FGBuildableGeneratorFuel_base_base_base as docs_json_ts_0_4_2_11_classes_base_FGBuildableGeneratorFuel_base_base_base,
	FGBuildableGeneratorGeoThermal_base as docs_json_ts_0_4_2_11_classes_base_FGBuildableGeneratorGeoThermal_base,
	FGBuildableGeneratorNuclear_pre_1_0 as docs_json_ts_0_4_2_11_classes_base_FGBuildableGeneratorNuclear_pre_1_0,
	FGBuildableGeneratorNuclear_version_specific as docs_json_ts_0_4_2_11_classes_base_FGBuildableGeneratorNuclear_version_specific,
	FGBuildableLightsControlPanel_version_specific as docs_json_ts_0_4_2_11_classes_base_FGBuildableLightsControlPanel_version_specific,
	FGBuildableLightSource_version_specific as docs_json_ts_0_4_2_11_classes_base_FGBuildableLightSource_version_specific,
	FGBuildableMAM_version_specific as docs_json_ts_0_4_2_11_classes_base_FGBuildableMAM_version_specific,
	FGBuildableManufacturer_base_blender_base_base as docs_json_ts_0_4_2_11_classes_base_FGBuildableManufacturer_base_blender_base_base,
	FGBuildableManufacturer_base_constructor_base_base as docs_json_ts_0_4_2_11_classes_base_FGBuildableManufacturer_base_constructor_base_base,
	FGBuildableManufacturer_Build_HadronCollider_C_base as docs_json_ts_0_4_2_11_classes_base_FGBuildableManufacturer_Build_HadronCollider_C_base,
	FGBuildableManufacturerVariablePower as docs_json_ts_0_4_2_11_classes_base_FGBuildableManufacturerVariablePower,
	FGBuildablePipelineJunction_base_base_base as docs_json_ts_0_4_2_11_classes_base_FGBuildablePipelineJunction_base_base_base,
	FGBuildablePowerStorage_base as docs_json_ts_0_4_2_11_classes_base_FGBuildablePowerStorage_base,
	FGBuildableResourceExtractor_miner_mk1_version_specific as docs_json_ts_0_4_2_11_classes_base_FGBuildableResourceExtractor_miner_mk1_version_specific,
	FGBuildableResourceExtractor_water_base as docs_json_ts_0_4_2_11_classes_base_FGBuildableResourceExtractor_water_base,
	FGBuildableResourceSink_base_base as docs_json_ts_0_4_2_11_classes_base_FGBuildableResourceSink_base_base,
	FGBuildableTradingPost_base_pre_1_0 as docs_json_ts_0_4_2_11_classes_base_FGBuildableTradingPost_base_pre_1_0,
	FGBuildableTradingPost_base_version_specific as docs_json_ts_0_4_2_11_classes_base_FGBuildableTradingPost_base_version_specific,
	has_mHasPower as docs_json_ts_0_4_2_11_classes_base_has_mHasPower,
	has_mPowerConsumption as docs_json_ts_0_4_2_11_classes_base_has_mPowerConsumption,
} from './../../0.4.2.11/classes/Base.ts';

import type {
	FGBuildable_base_pre_1_0 as docs_json_ts_0_5_2_1_classes_base_FGBuildable_base_pre_1_0,
	FGBuildable_base_version_specific as docs_json_ts_0_5_2_1_classes_base_FGBuildable_base_version_specific,
	FGBuildable_isFrame as docs_json_ts_0_5_2_1_classes_base_FGBuildable_isFrame,
	FGBuildable_mSnappedPassthroughs as docs_json_ts_0_5_2_1_classes_base_FGBuildable_mSnappedPassthroughs,
	FGBuildable_powered_version_specific as docs_json_ts_0_5_2_1_classes_base_FGBuildable_powered_version_specific,
	FGBuildableBeam_version_specific as docs_json_ts_0_5_2_1_classes_base_FGBuildableBeam_version_specific,
	FGBuildableConveyorBelt_version_specific as docs_json_ts_0_5_2_1_classes_base_FGBuildableConveyorBelt_version_specific,
	FGBuildableDockingStation_base as docs_json_ts_0_5_2_1_classes_base_FGBuildableDockingStation_base,
	FGBuildableDoor_automated_version_specific as docs_json_ts_0_5_2_1_classes_base_FGBuildableDoor_automated_version_specific,
	FGBuildableDoor_base as docs_json_ts_0_5_2_1_classes_base_FGBuildableDoor_base,
	FGBuildableDoor_manual_version_specific as docs_json_ts_0_5_2_1_classes_base_FGBuildableDoor_manual_version_specific,
	FGBuildableLightsControlPanel_version_specific as docs_json_ts_0_5_2_1_classes_base_FGBuildableLightsControlPanel_version_specific,
	FGBuildableLightSource_base as docs_json_ts_0_5_2_1_classes_base_FGBuildableLightSource_base,
	FGBuildableLightSource_Build_StreetLight_C as docs_json_ts_0_5_2_1_classes_base_FGBuildableLightSource_Build_StreetLight_C,
	FGBuildableManufacturer_Build_ConstructorMk1_C_base as docs_json_ts_0_5_2_1_classes_base_FGBuildableManufacturer_Build_ConstructorMk1_C_base,
	FGBuildableManufacturer_Build_FoundryMk1_C_base as docs_json_ts_0_5_2_1_classes_base_FGBuildableManufacturer_Build_FoundryMk1_C_base,
	FGBuildablePassthrough_base as docs_json_ts_0_5_2_1_classes_base_FGBuildablePassthrough_base,
	FGBuildablePassthrough_pre_update8 as docs_json_ts_0_5_2_1_classes_base_FGBuildablePassthrough_pre_update8,
	FGBuildablePipeHyper_version_specific as docs_json_ts_0_5_2_1_classes_base_FGBuildablePipeHyper_version_specific,
	FGBuildablePipeline_base_spline as docs_json_ts_0_5_2_1_classes_base_FGBuildablePipeline_base_spline,
	FGBuildableRailroadSignal_base as docs_json_ts_0_5_2_1_classes_base_FGBuildableRailroadSignal_base,
	FGBuildableRailroadSignal_block_version_specific as docs_json_ts_0_5_2_1_classes_base_FGBuildableRailroadSignal_block_version_specific,
	FGBuildableRailroadStation_base as docs_json_ts_0_5_2_1_classes_base_FGBuildableRailroadStation_base,
	FGBuildableRailroadTrack_base as docs_json_ts_0_5_2_1_classes_base_FGBuildableRailroadTrack_base,
	FGBuildableRailroadTrack_base_version_specific as docs_json_ts_0_5_2_1_classes_base_FGBuildableRailroadTrack_base_version_specific,
	FGBuildableRamp_base as docs_json_ts_0_5_2_1_classes_base_FGBuildableRamp_base,
	FGBuildableStair_has_mStairDirection as docs_json_ts_0_5_2_1_classes_base_FGBuildableStair_has_mStairDirection,
	FGBuildableTradingPost_version_specific as docs_json_ts_0_5_2_1_classes_base_FGBuildableTradingPost_version_specific,
	FGBuildableTrainPlatform_base as docs_json_ts_0_5_2_1_classes_base_FGBuildableTrainPlatform_base,
	FGBuildableTrainPlatform_non_empty as docs_json_ts_0_5_2_1_classes_base_FGBuildableTrainPlatform_non_empty,
	FGBuildableTrainPlatformCargo_version_specific as docs_json_ts_0_5_2_1_classes_base_FGBuildableTrainPlatformCargo_version_specific,
	FGBuildableWidgetSign_base as docs_json_ts_0_5_2_1_classes_base_FGBuildableWidgetSign_base,
	has_mIsSupport as docs_json_ts_0_5_2_1_classes_base_has_mIsSupport,
	has_mSize_vector as docs_json_ts_0_5_2_1_classes_base_has_mSize_vector,
	has_mSplineData as docs_json_ts_0_5_2_1_classes_base_has_mSplineData,
} from './../../0.5.2.1/classes/Base.ts';

import type {
	FGBuildable_foundation_mDisableSnapOn as docs_json_ts_0_6_1_5_classes_base_FGBuildable_foundation_mDisableSnapOn,
	FGBuildable_pre_1_2 as docs_json_ts_0_6_1_5_classes_base_FGBuildable_pre_1_2,
	FGBuildable_pre_update8 as docs_json_ts_0_6_1_5_classes_base_FGBuildable_pre_update8,
	FGBuildable_version_specific as docs_json_ts_0_6_1_5_classes_base_FGBuildable_version_specific,
	FGBuildable_with_depth as docs_json_ts_0_6_1_5_classes_base_FGBuildable_with_depth,
	FGBuildableCornerWall_base as docs_json_ts_0_6_1_5_classes_base_FGBuildableCornerWall_base,
	FGBuildableFoundation_version_specific as docs_json_ts_0_6_1_5_classes_base_FGBuildableFoundation_version_specific,
	FGBuildableManufacturer_Build_SmelterMk1_C_base as docs_json_ts_0_6_1_5_classes_base_FGBuildableManufacturer_Build_SmelterMk1_C_base,
	FGBuildablePipeline_version_specific as docs_json_ts_0_6_1_5_classes_base_FGBuildablePipeline_version_specific,
	FGBuildableRadarTower_version_specific as docs_json_ts_0_6_1_5_classes_base_FGBuildableRadarTower_version_specific,
	FGBuildableResourceExtractor_base_version_specific_base as docs_json_ts_0_6_1_5_classes_base_FGBuildableResourceExtractor_base_version_specific_base,
	FGBuildableTrainPlatformCargo_version_specific as docs_json_ts_0_6_1_5_classes_base_FGBuildableTrainPlatformCargo_version_specific,
	FGEquipment as docs_json_ts_0_6_1_5_classes_base_FGEquipment,
	has_mIsInverted as docs_json_ts_0_6_1_5_classes_base_has_mIsInverted,
} from './../../0.6.1.5/classes/Base.ts';

import type {
	bool_string as docs_json_ts_common_types_bool_string,
	decimal_string as docs_json_ts_common_types_decimal_string,
	empty_object as docs_json_ts_common_types_empty_object,
	integer_string_signed as docs_json_ts_common_types_integer_string_signed,
	RGBA as docs_json_ts_common_types_RGBA,
	XYZ_decimal_string as docs_json_ts_common_types_XYZ_decimal_string,
	XYZ_integer_string as docs_json_ts_common_types_XYZ_integer_string,
} from './../../common/types.ts';

import type {
	FGBuildable_occupied as docs_json_ts_common_classes_FGBuildable_occupied,
	FGBuildable_tiered as docs_json_ts_common_classes_FGBuildable_tiered,
	FGBuildable_unoccupied_and_untiered as docs_json_ts_common_classes_FGBuildable_unoccupied_and_untiered,
	FGBuildableAttachmentMerger as docs_json_ts_common_classes_FGBuildableAttachmentMerger,
	FGBuildableAttachmentSplitter as docs_json_ts_common_classes_FGBuildableAttachmentSplitter,
	FGBuildableBeam as docs_json_ts_common_classes_FGBuildableBeam,
	FGBuildableBlueprintDesigner as docs_json_ts_common_classes_FGBuildableBlueprintDesigner,
	FGBuildableCircuitSwitch as docs_json_ts_common_classes_FGBuildableCircuitSwitch,
	FGBuildableConveyorBelt as docs_json_ts_common_classes_FGBuildableConveyorBelt,
	FGBuildableConveyorLift as docs_json_ts_common_classes_FGBuildableConveyorLift,
	FGBuildableCornerWall as docs_json_ts_common_classes_FGBuildableCornerWall,
	FGBuildableDockingStation as docs_json_ts_common_classes_FGBuildableDockingStation,
	FGBuildableDoor as docs_json_ts_common_classes_FGBuildableDoor,
	FGBuildableDroneStation as docs_json_ts_common_classes_FGBuildableDroneStation,
	FGBuildableFactory as docs_json_ts_common_classes_FGBuildableFactory,
	FGBuildableFactoryBuilding as docs_json_ts_common_classes_FGBuildableFactoryBuilding,
	FGBuildableFactorySimpleProducer as docs_json_ts_common_classes_FGBuildableFactorySimpleProducer,
	FGBuildableFloodlight as docs_json_ts_common_classes_FGBuildableFloodlight,
	FGBuildableFoundation as docs_json_ts_common_classes_FGBuildableFoundation,
	FGBuildableFrackingActivator as docs_json_ts_common_classes_FGBuildableFrackingActivator,
	FGBuildableFrackingExtractor as docs_json_ts_common_classes_FGBuildableFrackingExtractor,
	FGBuildableGeneratorFuel as docs_json_ts_common_classes_FGBuildableGeneratorFuel,
	FGBuildableGeneratorGeoThermal as docs_json_ts_common_classes_FGBuildableGeneratorGeoThermal,
	FGBuildableGeneratorNuclear as docs_json_ts_common_classes_FGBuildableGeneratorNuclear,
	FGBuildableJumppad as docs_json_ts_common_classes_FGBuildableJumppad,
	FGBuildableLadder as docs_json_ts_common_classes_FGBuildableLadder,
	FGBuildableLightsControlPanel as docs_json_ts_common_classes_FGBuildableLightsControlPanel,
	FGBuildableLightSource as docs_json_ts_common_classes_FGBuildableLightSource,
	FGBuildableMAM as docs_json_ts_common_classes_FGBuildableMAM,
	FGBuildableManufacturer as docs_json_ts_common_classes_FGBuildableManufacturer,
	FGBuildableManufacturerVariablePower as docs_json_ts_common_classes_FGBuildableManufacturerVariablePower,
	FGBuildablePassthrough as docs_json_ts_common_classes_FGBuildablePassthrough,
	FGBuildablePillar as docs_json_ts_common_classes_FGBuildablePillar,
	FGBuildablePipeHyper as docs_json_ts_common_classes_FGBuildablePipeHyper,
	FGBuildablePipeline as docs_json_ts_common_classes_FGBuildablePipeline,
	FGBuildablePipelineJunction as docs_json_ts_common_classes_FGBuildablePipelineJunction,
	FGBuildablePipelinePump as docs_json_ts_common_classes_FGBuildablePipelinePump,
	FGBuildablePipelineSupport as docs_json_ts_common_classes_FGBuildablePipelineSupport,
	FGBuildablePipeReservoir as docs_json_ts_common_classes_FGBuildablePipeReservoir,
	FGBuildablePole as docs_json_ts_common_classes_FGBuildablePole,
	FGBuildablePowerPole as docs_json_ts_common_classes_FGBuildablePowerPole,
	FGBuildablePowerStorage as docs_json_ts_common_classes_FGBuildablePowerStorage,
	FGBuildableRadarTower as docs_json_ts_common_classes_FGBuildableRadarTower,
	FGBuildableRailroadSignal_block as docs_json_ts_common_classes_FGBuildableRailroadSignal_block,
	FGBuildableRailroadSignal_path as docs_json_ts_common_classes_FGBuildableRailroadSignal_path,
	FGBuildableRailroadStation as docs_json_ts_common_classes_FGBuildableRailroadStation,
	FGBuildableRailroadTrack as docs_json_ts_common_classes_FGBuildableRailroadTrack,
	FGBuildableRamp as docs_json_ts_common_classes_FGBuildableRamp,
	FGBuildableResourceExtractor as docs_json_ts_common_classes_FGBuildableResourceExtractor,
	FGBuildableResourceSink as docs_json_ts_common_classes_FGBuildableResourceSink,
	FGBuildableResourceSinkShop as docs_json_ts_common_classes_FGBuildableResourceSinkShop,
	FGBuildableSnowDispenser as docs_json_ts_common_classes_FGBuildableSnowDispenser,
	FGBuildableSpaceElevator as docs_json_ts_common_classes_FGBuildableSpaceElevator,
	FGBuildableSplitterSmart as docs_json_ts_common_classes_FGBuildableSplitterSmart,
	FGBuildableStair as docs_json_ts_common_classes_FGBuildableStair,
	FGBuildableStorage as docs_json_ts_common_classes_FGBuildableStorage,
	FGBuildableTradingPost as docs_json_ts_common_classes_FGBuildableTradingPost,
	FGBuildableTrainPlatformCargo as docs_json_ts_common_classes_FGBuildableTrainPlatformCargo,
	FGBuildableTrainPlatformEmpty as docs_json_ts_common_classes_FGBuildableTrainPlatformEmpty,
	FGBuildableWalkway as docs_json_ts_common_classes_FGBuildableWalkway,
	FGBuildableWall as docs_json_ts_common_classes_FGBuildableWall,
	FGBuildableWidgetSign as docs_json_ts_common_classes_FGBuildableWidgetSign,
	FGBuildableWire as docs_json_ts_common_classes_FGBuildableWire,
	FGConveyorPoleStackable as docs_json_ts_common_classes_FGConveyorPoleStackable,
	FGJetPack as docs_json_ts_common_classes_FGJetPack,
	FGPipeHyperStart as docs_json_ts_common_classes_FGPipeHyperStart,
} from './../../common/classes.ts';

import type {
	FGBuildable_is_wallish as docs_json_ts_0_5_2_1_classes_base_overridable_FGBuildable_is_wallish,
} from './../../0.5.2.1/classes/Base.overridable.ts';

import type {
	has_mBatteryClasses as docs_json_ts_0_4_2_11_overridable_has_mBatteryClasses,
} from './../../0.4.2.11/types/overridable.ts';

import type {
	FGBuildableResourceExtractor_miner_base as docs_json_ts_0_3_7_7_classes_base_overridable_FGBuildableResourceExtractor_miner_base,
	FGBuildableResourceExtractor_only_allow_certain_resources as docs_json_ts_0_3_7_7_classes_base_overridable_FGBuildableResourceExtractor_only_allow_certain_resources,
} from './../../0.3.7.7/classes/Base.overridable.ts';

import type {
	FGJetPack_pre_1_0 as docs_json_ts_0_7_1_1_classes_base_overridable_FGJetPack_pre_1_0,
	FGJetPack_version_specific as docs_json_ts_0_7_1_1_classes_base_overridable_FGJetPack_version_specific,
} from './Base.overridable.ts';

type FGBuildable_base = docs_json_ts_0_6_1_5_classes_base_overridable_FGBuildable_base_version_specific & docs_json_ts_0_3_7_7_classes_base_FGBuildable_base_pre_1_0 & docs_json_ts_0_3_7_7_classes_base_FGBuildable_base_version_specific & docs_json_ts_0_4_2_11_classes_base_FGBuildable_base_version_specific & docs_json_ts_0_5_2_1_classes_base_FGBuildable_base_pre_1_0 & docs_json_ts_0_5_2_1_classes_base_FGBuildable_base_version_specific & docs_json_ts_0_6_1_5_classes_base_FGBuildable_pre_1_2 & docs_json_ts_0_6_1_5_classes_base_FGBuildable_pre_update8 & docs_json_ts_0_6_1_5_classes_base_FGBuildable_version_specific & FGBuildable_base_pre_1_2 & FGBuildable_base_version_specific;

type FGBuildable_base_pre_1_2 = {
	mIsMultiSpawnedBuildable: docs_json_ts_common_types_bool_string,
};

type FGBuildable_base_version_specific = {
	mContainsComponents: docs_json_ts_common_types_bool_string,
	mCanContainLightweightInstances: docs_json_ts_common_types_bool_string,
	mBlueprintBuildEffectID: docs_json_ts_common_types_integer_string_signed,
};

type FGBuildable_docking_station = docs_json_ts_0_3_7_7_classes_base_FGBuildable_docking_station_base_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildable_docking_station_base_with_mMapText & FGBuildable_powered_storage;

type FGBuildable_occupied = docs_json_ts_0_3_7_7_classes_base_FGBuildable_occupied_base & docs_json_ts_common_classes_FGBuildable_occupied & FGBuildable_base;

type FGBuildable_powered = docs_json_ts_0_3_7_7_classes_base_FGBuildable_powered_pre_1_0 & docs_json_ts_0_3_7_7_classes_base_FGBuildable_powered_version_specific & docs_json_ts_0_4_2_11_classes_base_FGBuildable_has_mCachedSkeletalMeshes & docs_json_ts_0_5_2_1_classes_base_FGBuildable_powered_version_specific & FGBuildable_base & FGBuildable_powered_version_specific;

type FGBuildable_powered_version_specific = {
	mCanEverMonitorProductivity: docs_json_ts_common_types_bool_string,
	mDefaultProductivityMeasurementDuration: docs_json_ts_common_types_decimal_string,
	mLastProductivityMeasurementProduceDuration: docs_json_ts_common_types_decimal_string,
	mLastProductivityMeasurementDuration: docs_json_ts_common_types_decimal_string,
	mCurrentProductivityMeasurementProduceDuration: docs_json_ts_common_types_decimal_string,
	mCurrentProductivityMeasurementDuration: docs_json_ts_common_types_decimal_string,
	mProductivityMonitorEnabled: docs_json_ts_common_types_bool_string,
};

type FGBuildable_powered_storage = docs_json_ts_0_3_7_7_classes_base_FGBuildable_powered_storage_base_base_base & docs_json_ts_0_4_2_11_classes_base_FGBuildable_has_mCachedSkeletalMeshes & FGBuildable_powered;

type FGBuildable_tiered = docs_json_ts_0_3_7_7_classes_base_FGBuildable_tiered_base & docs_json_ts_common_classes_FGBuildable_tiered & FGBuildable_base;

type FGBuildable_unoccupied_and_untiered = docs_json_ts_common_classes_FGBuildable_unoccupied_and_untiered & FGBuildable_base;

type FGBuildableAttachmentMerger = docs_json_ts_0_3_7_7_classes_base_FGBuildableAttachmentMerger_version_specific & docs_json_ts_common_classes_FGBuildableAttachmentMerger & FGBuildable_base;

type FGBuildableAttachmentSplitter = docs_json_ts_0_3_7_7_classes_base_FGBuildableAttachment_has_mCurrentOutputIndex & docs_json_ts_common_classes_FGBuildableAttachmentSplitter & FGBuildable_base;

type FGBuildableBeamLightweight = docs_json_ts_0_3_7_7_classes_base_has_mSize & docs_json_ts_0_5_2_1_classes_base_FGBuildableBeam_version_specific & docs_json_ts_common_classes_FGBuildableBeam & FGBuildable_base;

type FGBuildableBlueprintDesigner = docs_json_ts_common_classes_FGBuildableBlueprintDesigner & FGBuildable_base & FGBuildableBlueprintDesigner_pre_1_0 & FGBuildableBlueprintDesigner_version_specific;

type FGBuildableBlueprintDesigner_pre_1_0 = {
	mIntersectComponents: '',
	mCurrentRecordData: {
		IconID: docs_json_ts_common_types_integer_string_signed,
		Color: docs_json_ts_common_types_RGBA,
	},
};

type FGBuildableBlueprintDesigner_version_specific = {
	mTerminalDistanceFromEdge: docs_json_ts_common_types_decimal_string,
	mTerminalHalfDepth: docs_json_ts_common_types_decimal_string,
	mDimensions: docs_json_ts_common_types_XYZ_integer_string,
	OnRecordDataChanged: docs_json_ts_common_types_empty_object,
	OnBlueprintCostChanged: docs_json_ts_common_types_empty_object,
	mCurrentCost: '',
	mBuildables: '',
};

type FGBuildableCircuitSwitch = docs_json_ts_0_4_2_11_classes_base_FGBuildableCircuitSwitch_base & docs_json_ts_common_classes_FGBuildableCircuitSwitch & FGBuildable_base & FGBuildableCircuitSwitch_version_specific;

type FGBuildableCircuitSwitch_version_specific = {
	mOnBuildingTagChanged: docs_json_ts_common_types_empty_object,
};

type FGBuildableConveyorBelt = docs_json_ts_0_3_7_7_classes_base_FGBuildableConveyorBelt_pre_1_0 & docs_json_ts_0_3_7_7_classes_base_FGBuildableConveyorBelt_pre_update8 & docs_json_ts_0_3_7_7_classes_base_has_mMeshLength & docs_json_ts_0_3_7_7_classes_base_has_mSplineData & docs_json_ts_0_5_2_1_classes_base_FGBuildableConveyorBelt_version_specific & docs_json_ts_common_classes_FGBuildableConveyorBelt & FGBuildable_base;

type FGBuildableConveyorLift = docs_json_ts_0_3_7_7_classes_base_FGBuildableConveyorBelt_pre_1_0 & docs_json_ts_0_3_7_7_classes_base_FGBuildableConveyorBelt_pre_update8 & docs_json_ts_0_3_7_7_classes_base_FGBuildableConveyorLift_base & docs_json_ts_0_5_2_1_classes_base_FGBuildable_mSnappedPassthroughs & docs_json_ts_common_classes_FGBuildableConveyorLift & FGBuildable_base;

type FGBuildableCornerWall = docs_json_ts_0_6_1_5_classes_base_FGBuildableCornerWall_base & docs_json_ts_0_6_1_5_classes_base_has_mIsInverted & docs_json_ts_common_classes_FGBuildableCornerWall & FGBuildable_base;

type FGBuildableDockingStation = docs_json_ts_0_3_7_7_classes_base_FGBuildable_docking_station_base_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildable_powered_storage_base_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableDockingStation_with_mFuelTransferSpeed_base & docs_json_ts_0_5_2_1_classes_base_FGBuildableDockingStation_base & docs_json_ts_common_classes_FGBuildableDockingStation & FGBuildable_powered;

type FGBuildableDoor = FGBuildableDoor_manual | FGBuildableDoor_automated;

type FGBuildableDoor_automated = docs_json_ts_0_5_2_1_classes_base_overridable_FGBuildable_is_wallish & docs_json_ts_0_3_7_7_classes_base_has_mElevation & docs_json_ts_0_3_7_7_classes_base_has_mHeight & docs_json_ts_0_3_7_7_classes_base_has_mWidth & docs_json_ts_0_5_2_1_classes_base_FGBuildableDoor_automated_version_specific & docs_json_ts_0_5_2_1_classes_base_FGBuildableDoor_base & docs_json_ts_common_classes_FGBuildableDoor & FGBuildable_base;

type FGBuildableDoor_manual = docs_json_ts_0_5_2_1_classes_base_overridable_FGBuildable_is_wallish & docs_json_ts_0_3_7_7_classes_base_has_mElevation & docs_json_ts_0_3_7_7_classes_base_has_mHeight & docs_json_ts_0_3_7_7_classes_base_has_mWidth & docs_json_ts_0_5_2_1_classes_base_FGBuildableDoor_base & docs_json_ts_0_5_2_1_classes_base_FGBuildableDoor_manual_version_specific & docs_json_ts_common_classes_FGBuildableDoor & FGBuildable_base;

type FGBuildableDroneStation = docs_json_ts_0_4_2_11_classes_base_FGBuildableDroneStation_pre_1_0 & docs_json_ts_0_4_2_11_classes_base_FGBuildableDroneStation_version_specific & docs_json_ts_0_4_2_11_overridable_has_mBatteryClasses & docs_json_ts_common_classes_FGBuildableDroneStation & FGBuildable_base & FGBuildable_docking_station;

type FGBuildableFactory_jump_pad = docs_json_ts_0_3_7_7_classes_base_FGBuildableFactory_jump_pad_base_base_base & docs_json_ts_common_classes_FGBuildableFactory & FGBuildable_powered;

type FGBuildableFactory_landing_pad = docs_json_ts_0_3_7_7_classes_base_FGBuildableFactory_landing_pad_base_base_base & docs_json_ts_common_classes_FGBuildableFactory & FGBuildable_powered;

type FGBuildableFactory_not_pad = docs_json_ts_common_classes_FGBuildableFactory & FGBuildable_powered;

type FGBuildableFactoryBuilding = docs_json_ts_common_classes_FGBuildableFactoryBuilding & FGBuildable_base;

type FGBuildableFactorySimpleProducer = docs_json_ts_0_3_7_7_classes_base_FGBuildableFactorySimpleProducer_base_base & docs_json_ts_common_classes_FGBuildableFactorySimpleProducer & FGBuildable_powered;

type FGBuildableFloodlight = docs_json_ts_0_4_2_11_classes_base_FGBuildable_light_related_thing_base & docs_json_ts_0_4_2_11_classes_base_FGBuildableFloodlight_version_specific & docs_json_ts_0_4_2_11_classes_base_FGBuildableLightSource_version_specific & docs_json_ts_0_4_2_11_classes_base_has_mHasPower & docs_json_ts_0_4_2_11_classes_base_has_mPowerConsumption & docs_json_ts_0_5_2_1_classes_base_FGBuildableLightSource_base & docs_json_ts_common_classes_FGBuildableFloodlight & FGBuildable_base;

type FGBuildableFoundation = docs_json_ts_0_3_7_7_classes_base_has_mElevation & docs_json_ts_0_3_7_7_classes_base_has_mHeight & docs_json_ts_0_3_7_7_classes_base_has_mWidth & docs_json_ts_0_5_2_1_classes_base_FGBuildable_isFrame & docs_json_ts_0_6_1_5_classes_base_FGBuildable_foundation_mDisableSnapOn & docs_json_ts_0_6_1_5_classes_base_FGBuildable_with_depth & docs_json_ts_0_6_1_5_classes_base_FGBuildableFoundation_version_specific & docs_json_ts_common_classes_FGBuildableFoundation & FGBuildable_base;

type FGBuildableFoundationLightweight = docs_json_ts_0_3_7_7_classes_base_has_mElevation & docs_json_ts_0_3_7_7_classes_base_has_mHeight & docs_json_ts_0_3_7_7_classes_base_has_mWidth & docs_json_ts_0_5_2_1_classes_base_FGBuildable_isFrame & docs_json_ts_0_6_1_5_classes_base_FGBuildable_foundation_mDisableSnapOn & docs_json_ts_0_6_1_5_classes_base_FGBuildable_with_depth & docs_json_ts_0_6_1_5_classes_base_FGBuildableFoundation_version_specific & docs_json_ts_common_classes_FGBuildableFoundation & FGBuildable_base;

type FGBuildableFrackingActivator = docs_json_ts_0_3_7_7_classes_base_overridable_FGBuildableResourceExtractor_only_allow_certain_resources & docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_only_allow_certain_resources & docs_json_ts_0_4_2_11_classes_base_FGBuildableFrackingActivator_version_specific & docs_json_ts_0_6_1_5_classes_base_FGBuildableResourceExtractor_base_version_specific_base & docs_json_ts_common_classes_FGBuildableFrackingActivator & FGBuildable_powered;

type FGBuildableFrackingExtractor = docs_json_ts_0_3_7_7_classes_base_overridable_FGBuildableResourceExtractor_only_allow_certain_resources & docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_piped & docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_piped_pre_1_0 & docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_timed & docs_json_ts_0_6_1_5_classes_base_FGBuildableResourceExtractor_base_version_specific_base & docs_json_ts_common_classes_FGBuildableFrackingExtractor & FGBuildable_powered;

type FGBuildableGenerator = docs_json_ts_0_3_7_7_classes_base_FGBuildable_powered_version_specific & docs_json_ts_0_3_7_7_classes_base_FGBuildableGenerator_base_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableGenerator_base_base_pre_1_0 & docs_json_ts_0_3_7_7_classes_base_FGBuildableGenerator_no_fuel_base_base_base_base & FGBuildableGenerator_no_fuel;

type FGBuildableGenerator_no_fuel = docs_json_ts_0_3_7_7_classes_base_FGBuildableGenerator_no_fuel_base_base_base_base & FGBuildable_powered;

type FGBuildableGeneratorFuel_biomass = docs_json_ts_0_3_7_7_classes_base_FGBuildableGenerator_base_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableGeneratorFuel_biomass_base_base & docs_json_ts_0_4_2_11_classes_base_FGBuildableGeneratorFuel_base_base_base & docs_json_ts_common_classes_FGBuildableGeneratorFuel & FGBuildableGenerator;

type FGBuildableGeneratorFuel_coal = docs_json_ts_0_3_7_7_classes_base_FGBuildableGenerator_base_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableGeneratorFuel_coal_base_base & docs_json_ts_0_4_2_11_classes_base_FGBuildableGeneratorFuel_base_base_base & docs_json_ts_common_classes_FGBuildableGeneratorFuel & FGBuildableGenerator;

type FGBuildableGeneratorFuel_fuel = docs_json_ts_0_3_7_7_classes_base_FGBuildableGenerator_base_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableGeneratorFuel_fuel_base_base & docs_json_ts_0_3_7_7_classes_base_has_mRTPCInterval & docs_json_ts_0_4_2_11_classes_base_FGBuildableGeneratorFuel_base_base_base & docs_json_ts_common_classes_FGBuildableGeneratorFuel & FGBuildableGenerator;

type FGBuildableGeneratorGeoThermal = docs_json_ts_0_3_7_7_classes_base_FGBuildableGenerator_no_fuel_base_base_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableGeneratorGeoThermal_base_base_base & docs_json_ts_0_4_2_11_classes_base_FGBuildableGeneratorGeoThermal_base & docs_json_ts_common_classes_FGBuildableGeneratorGeoThermal & FGBuildableGenerator_no_fuel;

type FGBuildableGeneratorNuclear = docs_json_ts_0_3_7_7_classes_base_FGBuildableGenerator_base_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableGeneratorNuclear_version_specific & docs_json_ts_0_4_2_11_classes_base_FGBuildableGeneratorFuel_base_base_base & docs_json_ts_0_4_2_11_classes_base_FGBuildableGeneratorNuclear_pre_1_0 & docs_json_ts_0_4_2_11_classes_base_FGBuildableGeneratorNuclear_version_specific & docs_json_ts_common_classes_FGBuildableGeneratorNuclear & FGBuildableGenerator;

type FGBuildableJumppad = docs_json_ts_0_3_7_7_classes_base_FGBuildableJumppad_base_base_base & docs_json_ts_common_classes_FGBuildableJumppad & FGBuildable_powered;

type FGBuildableLadder = docs_json_ts_0_3_7_7_classes_base_FGBuildableLadder_base & docs_json_ts_0_3_7_7_classes_base_has_mWidth & docs_json_ts_common_classes_FGBuildableLadder & FGBuildable_base;

type FGBuildableLightsControlPanel = docs_json_ts_0_4_2_11_classes_base_FGBuildable_light_related_thing_base & docs_json_ts_0_4_2_11_classes_base_FGBuildableLightsControlPanel_version_specific & docs_json_ts_0_5_2_1_classes_base_FGBuildableLightsControlPanel_version_specific & docs_json_ts_common_classes_FGBuildableLightsControlPanel & FGBuildable_base;

type FGBuildableLightSource_Build_CeilingLight_C = docs_json_ts_0_4_2_11_classes_base_FGBuildable_light_related_thing_base & docs_json_ts_0_4_2_11_classes_base_FGBuildableLightSource_version_specific & docs_json_ts_0_4_2_11_classes_base_has_mHasPower & docs_json_ts_0_4_2_11_classes_base_has_mPowerConsumption & docs_json_ts_0_5_2_1_classes_base_FGBuildableLightSource_base & docs_json_ts_common_classes_FGBuildableLightSource & FGBuildable_base;

type FGBuildableLightSource_Build_StreetLight_C = docs_json_ts_0_5_2_1_classes_base_FGBuildableLightSource_Build_StreetLight_C & docs_json_ts_common_classes_FGBuildableLightSource & FGBuildable_base;

type FGBuildableMAM = docs_json_ts_0_4_2_11_classes_base_FGBuildableMAM_version_specific & docs_json_ts_common_classes_FGBuildableMAM & FGBuildable_base & FGBuildable_occupied;

type FGBuildableManufacturer_Build_AssemblerMk1_C = docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_IsPowered_base_base & docs_json_ts_common_classes_FGBuildableManufacturer & FGBuildable_powered;

type FGBuildableManufacturer_Build_Blender_C = docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_IsPowered_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_mProductionEffectsRunning_base_base & docs_json_ts_0_4_2_11_classes_base_FGBuildableManufacturer_base_blender_base_base & docs_json_ts_common_classes_FGBuildableManufacturer & FGBuildable_powered;

type FGBuildableManufacturer_Build_ConstructorMk1_C = docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_IsPowered_base_base & docs_json_ts_0_4_2_11_classes_base_FGBuildableManufacturer_base_constructor_base_base & docs_json_ts_0_5_2_1_classes_base_FGBuildableManufacturer_Build_ConstructorMk1_C_base & docs_json_ts_common_classes_FGBuildableManufacturer & FGBuildable_powered;

type FGBuildableManufacturer_Build_FoundryMk1_C = docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_mProductionEffectsRunning_base_base & docs_json_ts_0_5_2_1_classes_base_FGBuildableManufacturer_Build_FoundryMk1_C_base & docs_json_ts_common_classes_FGBuildableManufacturer & FGBuildable_powered;

type FGBuildableManufacturer_Build_HadronCollider_C = docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_IsPowered_base_base & docs_json_ts_0_4_2_11_classes_base_FGBuildableManufacturer_Build_HadronCollider_C_base & docs_json_ts_0_4_2_11_classes_base_FGBuildableManufacturerVariablePower & docs_json_ts_common_classes_FGBuildableManufacturerVariablePower & FGBuildable_powered;

type FGBuildableManufacturer_Build_ManufacturerMk1_C = docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_base_base & docs_json_ts_0_4_2_11_classes_base_FGBuildable_mStopped_audio_stuff & docs_json_ts_common_classes_FGBuildableManufacturer & FGBuildable_powered;

type FGBuildableManufacturer_Build_OilRefinery_C = docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_IsPowered_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_mProductionEffectsRunning_base_base & docs_json_ts_common_classes_FGBuildableManufacturer & FGBuildable_powered;

type FGBuildableManufacturer_Build_Packager_C = docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_IsPowered_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_mProductionEffectsRunning_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_packager_base_base & docs_json_ts_common_classes_FGBuildableManufacturer & FGBuildable_powered;

type FGBuildableManufacturer_Build_SmelterMk1_C = docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableManufacturer_base_mProductionEffectsRunning_base_base & docs_json_ts_0_6_1_5_classes_base_FGBuildableManufacturer_Build_SmelterMk1_C_base & docs_json_ts_common_classes_FGBuildableManufacturer & FGBuildable_powered;

type FGBuildablePassthrough = docs_json_ts_0_5_2_1_classes_base_FGBuildablePassthrough_base & docs_json_ts_0_5_2_1_classes_base_FGBuildablePassthrough_pre_update8 & docs_json_ts_common_classes_FGBuildablePassthrough & FGBuildable_base;

type FGBuildablePillarLightweight = docs_json_ts_0_5_2_1_classes_base_has_mIsSupport & docs_json_ts_0_5_2_1_classes_base_has_mSize_vector & docs_json_ts_common_classes_FGBuildablePillar & FGBuildable_base;

type FGBuildablePipeHyper = docs_json_ts_0_5_2_1_classes_base_FGBuildablePipeHyper_version_specific & docs_json_ts_0_5_2_1_classes_base_has_mSplineData & docs_json_ts_common_classes_FGBuildablePipeHyper & FGBuildable_base;

type FGBuildablePipeline = docs_json_ts_0_3_7_7_classes_base_FGBuildablePipeline_base_root & docs_json_ts_0_5_2_1_classes_base_FGBuildablePipeline_base_spline & docs_json_ts_0_6_1_5_classes_base_FGBuildablePipeline_version_specific & docs_json_ts_common_classes_FGBuildablePipeline & FGBuildable_base;

type FGBuildablePipelineJunction = docs_json_ts_0_3_7_7_classes_base_FGBuildable_powered_pre_1_0 & docs_json_ts_0_3_7_7_classes_base_FGBuildable_powered_version_specific & docs_json_ts_0_3_7_7_classes_base_FGBuildablePipeline_base_no_indicator_base & docs_json_ts_0_4_2_11_classes_base_FGBuildablePipelineJunction_base_base_base & docs_json_ts_common_classes_FGBuildablePipelineJunction & FGBuildable_powered;

type FGBuildablePipelinePump_pump = docs_json_ts_0_3_7_7_classes_base_FGBuildablePipeline_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildablePipeline_base_no_indicator_base & docs_json_ts_0_3_7_7_classes_base_FGBuildablePipelinePump_powered_version_specific & docs_json_ts_0_3_7_7_classes_base_FGBuildablePipelinePump_pump_version_specific & docs_json_ts_common_classes_FGBuildablePipelinePump & FGBuildable_powered;

type FGBuildablePipelinePump_valve = docs_json_ts_0_3_7_7_classes_base_FGBuildablePipeline_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildablePipeline_base_no_indicator_base & docs_json_ts_0_3_7_7_classes_base_FGBuildablePipelinePump_powered_version_specific & docs_json_ts_common_classes_FGBuildablePipelinePump & FGBuildable_powered;

type FGBuildablePipelineSupport = docs_json_ts_0_3_7_7_classes_base_FGBuildable_with_mLength & docs_json_ts_0_3_7_7_classes_base_FGBuildablePipelineSupport_base & docs_json_ts_0_3_7_7_classes_base_has_mCanStack & docs_json_ts_0_3_7_7_classes_base_has_mStackHeight & docs_json_ts_0_3_7_7_classes_base_has_mUseStaticHeight & docs_json_ts_common_classes_FGBuildablePipelineSupport & FGBuildable_base;

type FGBuildablePipeReservoir = docs_json_ts_0_3_7_7_classes_base_FGBuildablePipeReservoir_base_base_base & docs_json_ts_common_classes_FGBuildablePipeReservoir & FGBuildable_powered;

type FGBuildablePole = docs_json_ts_0_3_7_7_classes_base_has_mCanStack & docs_json_ts_0_3_7_7_classes_base_has_mHeight & docs_json_ts_0_3_7_7_classes_base_has_mStackHeight & docs_json_ts_0_3_7_7_classes_base_has_mUseStaticHeight & docs_json_ts_common_classes_FGBuildablePole & FGBuildable_base & FGBuildablePole_version_specific;

type FGBuildablePole_version_specific = {
	mSelectedPoleVersion: docs_json_ts_common_types_integer_string_signed,
};

type FGBuildablePoleLightweight = docs_json_ts_0_3_7_7_classes_base_has_mCanStack & docs_json_ts_0_3_7_7_classes_base_has_mHeight & docs_json_ts_0_3_7_7_classes_base_has_mStackHeight & docs_json_ts_0_3_7_7_classes_base_has_mUseStaticHeight & docs_json_ts_common_classes_FGBuildablePole & FGBuildable_base & FGBuildablePole_version_specific;

type FGBuildablePowerPole = docs_json_ts_0_3_7_7_classes_base_FGBuildablePowerPole_base & docs_json_ts_0_4_2_11_classes_base_has_mHasPower & docs_json_ts_common_classes_FGBuildablePowerPole & FGBuildable_base;

type FGBuildablePowerStorage = docs_json_ts_0_4_2_11_classes_base_FGBuildablePowerStorage_base & docs_json_ts_common_classes_FGBuildablePowerStorage & FGBuildable_powered;

type FGBuildableRadarTower = docs_json_ts_0_6_1_5_classes_base_FGBuildableRadarTower_version_specific & docs_json_ts_0_6_1_5_classes_base_overridable_FGBuildableRadarTower_version_specific & docs_json_ts_common_classes_FGBuildableRadarTower & FGBuildable_powered;

type FGBuildableRailroadSignal_base = docs_json_ts_0_5_2_1_classes_base_FGBuildableRailroadSignal_base & FGBuildable_base;

type FGBuildableRailroadSignal_block = docs_json_ts_0_5_2_1_classes_base_FGBuildableRailroadSignal_block_version_specific & docs_json_ts_common_classes_FGBuildableRailroadSignal_block & FGBuildable_base & FGBuildableRailroadSignal_base;

type FGBuildableRailroadSignal_path = docs_json_ts_common_classes_FGBuildableRailroadSignal_path & FGBuildableRailroadSignal_base;

type FGBuildableRailroadStation = docs_json_ts_0_3_7_7_classes_base_FGBuildableRailroadStation_base_base & docs_json_ts_0_5_2_1_classes_base_FGBuildableRailroadStation_base & docs_json_ts_0_5_2_1_classes_base_FGBuildableTrainPlatform_base & docs_json_ts_0_5_2_1_classes_base_FGBuildableTrainPlatform_non_empty & docs_json_ts_common_classes_FGBuildableRailroadStation & FGBuildable_powered;

type FGBuildableRailroadTrack = docs_json_ts_0_3_7_7_classes_base_has_mMeshLength & docs_json_ts_0_5_2_1_classes_base_FGBuildableRailroadTrack_base & docs_json_ts_0_5_2_1_classes_base_FGBuildableRailroadTrack_base_version_specific & docs_json_ts_common_classes_FGBuildableRailroadTrack & FGBuildable_base;

type FGBuildableRamp = docs_json_ts_0_3_7_7_classes_base_has_mElevation & docs_json_ts_0_3_7_7_classes_base_has_mHeight & docs_json_ts_0_3_7_7_classes_base_has_mWidth & docs_json_ts_0_5_2_1_classes_base_FGBuildable_isFrame & docs_json_ts_0_5_2_1_classes_base_FGBuildableRamp_base & docs_json_ts_0_6_1_5_classes_base_FGBuildable_foundation_mDisableSnapOn & docs_json_ts_0_6_1_5_classes_base_FGBuildable_with_depth & docs_json_ts_0_6_1_5_classes_base_FGBuildableFoundation_version_specific & docs_json_ts_common_classes_FGBuildableRamp & FGBuildable_base;

type FGBuildableResourceExtractor_base = docs_json_ts_0_3_7_7_classes_base_overridable_FGBuildableResourceExtractor_only_allow_certain_resources & docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_piped & docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_piped_pre_1_0 & docs_json_ts_0_6_1_5_classes_base_FGBuildableResourceExtractor_base_version_specific_base & FGBuildable_powered;

type FGBuildableResourceExtractor_miner_mk1 = docs_json_ts_0_3_7_7_classes_base_overridable_FGBuildableResourceExtractor_miner_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_miner_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_timed & docs_json_ts_0_4_2_11_classes_base_FGBuildableResourceExtractor_miner_mk1_version_specific & docs_json_ts_common_classes_FGBuildableResourceExtractor & FGBuildableResourceExtractor_base;

type FGBuildableResourceExtractor_miner_mk2 = docs_json_ts_0_3_7_7_classes_base_overridable_FGBuildableResourceExtractor_miner_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_miner_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_miner_mk2_base_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_timed & docs_json_ts_common_classes_FGBuildableResourceExtractor & FGBuildableResourceExtractor_base;

type FGBuildableResourceExtractor_miner_mk3 = docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_miner_base & docs_json_ts_0_3_7_7_classes_base_overridable_FGBuildableResourceExtractor_miner_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_miner_mk3_version_specific & docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_timed & docs_json_ts_common_classes_FGBuildableResourceExtractor & FGBuildableResourceExtractor_base;

type FGBuildableResourceExtractor_oil = docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_oil_base_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_timed & docs_json_ts_common_classes_FGBuildableResourceExtractor & FGBuildableResourceExtractor_base;

type FGBuildableResourceExtractor_water = docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_timed & docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceExtractor_water_base_base_base & docs_json_ts_0_4_2_11_classes_base_FGBuildableResourceExtractor_water_base & docs_json_ts_common_classes_FGBuildableResourceExtractor & FGBuildableResourceExtractor_base;

type FGBuildableResourceSink = docs_json_ts_0_4_2_11_classes_base_FGBuildableResourceSink_base_base & docs_json_ts_common_classes_FGBuildableResourceSink & FGBuildable_powered;

type FGBuildableResourceSinkShop = docs_json_ts_0_3_7_7_classes_base_FGBuildableResourceSinkShop_base_base_base & docs_json_ts_common_classes_FGBuildableResourceSinkShop & FGBuildable_powered;

type FGBuildableSnowDispenser = docs_json_ts_common_classes_FGBuildableSnowDispenser & FGBuildable_base;

type FGBuildableSpaceElevator = docs_json_ts_common_classes_FGBuildableSpaceElevator & FGBuildable_powered;

type FGBuildableSplitterSmart = docs_json_ts_0_3_7_7_classes_base_FGBuildableAttachment_splitter_base_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableSplitterSmart_version_specific & docs_json_ts_common_classes_FGBuildableSplitterSmart & FGBuildable_base;

type FGBuildableStair = docs_json_ts_0_3_7_7_classes_base_has_mHeight & docs_json_ts_0_3_7_7_classes_base_has_mSize & docs_json_ts_0_5_2_1_classes_base_FGBuildableStair_has_mStairDirection & docs_json_ts_common_classes_FGBuildableStair & FGBuildable_base;

type FGBuildableStorage = docs_json_ts_0_3_7_7_classes_base_FGBuildableStorage_base_base_base & docs_json_ts_common_classes_FGBuildableStorage & FGBuildable_powered;

type FGBuildableTradingPost = docs_json_ts_0_3_7_7_classes_base_FGBuildableTradingPost_pre_1_0 & docs_json_ts_0_3_7_7_classes_base_FGBuildableTradingPost_pre_update8 & docs_json_ts_0_3_7_7_classes_base_FGBuildableTradingPost_version_specific & docs_json_ts_0_4_2_11_classes_base_FGBuildableTradingPost_base_pre_1_0 & docs_json_ts_0_4_2_11_classes_base_FGBuildableTradingPost_base_version_specific & docs_json_ts_0_5_2_1_classes_base_FGBuildableTradingPost_version_specific & docs_json_ts_common_classes_FGBuildableTradingPost & FGBuildable_powered;

type FGBuildableTrainPlatformCargo = docs_json_ts_0_3_7_7_classes_base_FGBuildableTrainPlatform_with_storage_base_base_base & docs_json_ts_0_3_7_7_classes_base_FGBuildableTrainPlatformCargo_pre_update8 & docs_json_ts_0_3_7_7_classes_base_FGBuildableTrainPlatformCargo_version_specific & docs_json_ts_0_5_2_1_classes_base_FGBuildableTrainPlatform_non_empty & docs_json_ts_0_5_2_1_classes_base_FGBuildableTrainPlatformCargo_version_specific & docs_json_ts_0_6_1_5_classes_base_FGBuildableTrainPlatformCargo_version_specific & docs_json_ts_common_classes_FGBuildableTrainPlatformCargo & FGBuildable_powered_storage;

type FGBuildableTrainPlatformEmpty = docs_json_ts_0_5_2_1_classes_base_FGBuildableTrainPlatform_base & docs_json_ts_common_classes_FGBuildableTrainPlatformEmpty & FGBuildable_powered;

type FGBuildableWalkway = docs_json_ts_0_3_7_7_classes_base_has_mDisableSnapOn & docs_json_ts_0_3_7_7_classes_base_has_mElevation & docs_json_ts_0_3_7_7_classes_base_has_mSize & docs_json_ts_common_classes_FGBuildableWalkway & FGBuildable_base;

type FGBuildableWalkwayLightweight = docs_json_ts_0_3_7_7_classes_base_has_mDisableSnapOn & docs_json_ts_0_3_7_7_classes_base_has_mElevation & docs_json_ts_0_3_7_7_classes_base_has_mSize & docs_json_ts_common_classes_FGBuildableWalkway & FGBuildable_base;

type FGBuildableWall = docs_json_ts_0_5_2_1_classes_base_overridable_FGBuildable_is_wallish & docs_json_ts_0_3_7_7_classes_base_has_mElevation & docs_json_ts_0_3_7_7_classes_base_has_mHeight & docs_json_ts_0_3_7_7_classes_base_has_mWidth & docs_json_ts_common_classes_FGBuildableWall & FGBuildable_base;

type FGBuildableWallLightweight = docs_json_ts_0_5_2_1_classes_base_overridable_FGBuildable_is_wallish & docs_json_ts_0_3_7_7_classes_base_has_mElevation & docs_json_ts_0_3_7_7_classes_base_has_mHeight & docs_json_ts_0_3_7_7_classes_base_has_mWidth & docs_json_ts_common_classes_FGBuildableWall & FGBuildable_base;

type FGBuildableWidgetSign = docs_json_ts_0_5_2_1_classes_base_FGBuildableWidgetSign_base & docs_json_ts_common_classes_FGBuildableWidgetSign & FGBuildable_base;

type FGBuildableWire = docs_json_ts_0_3_7_7_classes_base_FGBuildableWire_base & docs_json_ts_common_classes_FGBuildableWire & FGBuildable_base & FGBuildableWire_version_specific;

type FGBuildableWire_version_specific = {
	mCachedRelativeLocations: docs_json_ts_common_types_XYZ_decimal_string,
};

type FGConveyorPoleStackable = docs_json_ts_0_3_7_7_classes_base_has_mCanStack & docs_json_ts_0_3_7_7_classes_base_has_mHeight & docs_json_ts_0_3_7_7_classes_base_has_mStackHeight & docs_json_ts_0_3_7_7_classes_base_has_mUseStaticHeight & docs_json_ts_common_classes_FGConveyorPoleStackable & FGBuildable_base & FGBuildablePole_version_specific;

type FGJetPack = docs_json_ts_0_7_1_1_classes_base_overridable_FGJetPack_pre_1_0 & docs_json_ts_0_7_1_1_classes_base_overridable_FGJetPack_version_specific & docs_json_ts_0_3_7_7_classes_base_FGJetPack_pre_1_0 & docs_json_ts_0_3_7_7_classes_base_FGJetPack_version_specific & docs_json_ts_0_3_7_7_classes_base_has_mRTPCInterval & docs_json_ts_0_6_1_5_classes_base_FGEquipment & docs_json_ts_common_classes_FGJetPack;

type FGPipeHyperStart = docs_json_ts_0_3_7_7_classes_base_FGBuildable_powered_pre_1_0 & docs_json_ts_0_3_7_7_classes_base_FGBuildable_powered_version_specific & docs_json_ts_0_3_7_7_classes_base_FGBuildable_with_mLength & docs_json_ts_0_3_7_7_classes_base_FGPipeHyperStart_base_base_base & docs_json_ts_0_3_7_7_classes_base_FGPipeHyperStart_pre_update8 & docs_json_ts_0_3_7_7_classes_base_has_mCanStack & docs_json_ts_0_3_7_7_classes_base_has_mStackHeight & docs_json_ts_0_3_7_7_classes_base_has_mUseStaticHeight & docs_json_ts_common_classes_FGPipeHyperStart & FGBuildable_powered;

export type {
	FGBuildable_base,
	FGBuildable_base_pre_1_2,
	FGBuildable_base_version_specific,
	FGBuildable_docking_station,
	FGBuildable_occupied,
	FGBuildable_powered,
	FGBuildable_powered_version_specific,
	FGBuildable_powered_storage,
	FGBuildable_tiered,
	FGBuildable_unoccupied_and_untiered,
	FGBuildableAttachmentMerger,
	FGBuildableAttachmentSplitter,
	FGBuildableBeamLightweight,
	FGBuildableBlueprintDesigner,
	FGBuildableBlueprintDesigner_pre_1_0,
	FGBuildableBlueprintDesigner_version_specific,
	FGBuildableCircuitSwitch,
	FGBuildableCircuitSwitch_version_specific,
	FGBuildableConveyorBelt,
	FGBuildableConveyorLift,
	FGBuildableCornerWall,
	FGBuildableDockingStation,
	FGBuildableDoor,
	FGBuildableDoor_automated,
	FGBuildableDoor_manual,
	FGBuildableDroneStation,
	FGBuildableFactory_jump_pad,
	FGBuildableFactory_landing_pad,
	FGBuildableFactory_not_pad,
	FGBuildableFactoryBuilding,
	FGBuildableFactorySimpleProducer,
	FGBuildableFloodlight,
	FGBuildableFoundation,
	FGBuildableFoundationLightweight,
	FGBuildableFrackingActivator,
	FGBuildableFrackingExtractor,
	FGBuildableGenerator,
	FGBuildableGenerator_no_fuel,
	FGBuildableGeneratorFuel_biomass,
	FGBuildableGeneratorFuel_coal,
	FGBuildableGeneratorFuel_fuel,
	FGBuildableGeneratorGeoThermal,
	FGBuildableGeneratorNuclear,
	FGBuildableJumppad,
	FGBuildableLadder,
	FGBuildableLightsControlPanel,
	FGBuildableLightSource_Build_CeilingLight_C,
	FGBuildableLightSource_Build_StreetLight_C,
	FGBuildableMAM,
	FGBuildableManufacturer_Build_AssemblerMk1_C,
	FGBuildableManufacturer_Build_Blender_C,
	FGBuildableManufacturer_Build_ConstructorMk1_C,
	FGBuildableManufacturer_Build_FoundryMk1_C,
	FGBuildableManufacturer_Build_HadronCollider_C,
	FGBuildableManufacturer_Build_ManufacturerMk1_C,
	FGBuildableManufacturer_Build_OilRefinery_C,
	FGBuildableManufacturer_Build_Packager_C,
	FGBuildableManufacturer_Build_SmelterMk1_C,
	FGBuildablePassthrough,
	FGBuildablePillarLightweight,
	FGBuildablePipeHyper,
	FGBuildablePipeline,
	FGBuildablePipelineJunction,
	FGBuildablePipelinePump_pump,
	FGBuildablePipelinePump_valve,
	FGBuildablePipelineSupport,
	FGBuildablePipeReservoir,
	FGBuildablePole,
	FGBuildablePole_version_specific,
	FGBuildablePoleLightweight,
	FGBuildablePowerPole,
	FGBuildablePowerStorage,
	FGBuildableRadarTower,
	FGBuildableRailroadSignal_base,
	FGBuildableRailroadSignal_block,
	FGBuildableRailroadSignal_path,
	FGBuildableRailroadStation,
	FGBuildableRailroadTrack,
	FGBuildableRamp,
	FGBuildableResourceExtractor_base,
	FGBuildableResourceExtractor_miner_mk1,
	FGBuildableResourceExtractor_miner_mk2,
	FGBuildableResourceExtractor_miner_mk3,
	FGBuildableResourceExtractor_oil,
	FGBuildableResourceExtractor_water,
	FGBuildableResourceSink,
	FGBuildableResourceSinkShop,
	FGBuildableSnowDispenser,
	FGBuildableSpaceElevator,
	FGBuildableSplitterSmart,
	FGBuildableStair,
	FGBuildableStorage,
	FGBuildableTradingPost,
	FGBuildableTrainPlatformCargo,
	FGBuildableTrainPlatformEmpty,
	FGBuildableWalkway,
	FGBuildableWalkwayLightweight,
	FGBuildableWall,
	FGBuildableWallLightweight,
	FGBuildableWidgetSign,
	FGBuildableWire,
	FGBuildableWire_version_specific,
	FGConveyorPoleStackable,
	FGJetPack,
	FGPipeHyperStart,
};
