import {
	common_base__FGAmmoTypeInstantHit__base__pre_1_1__type,
	common_base__FGAmmoTypeInstantHit__chaos__pre_1_1__type,
	common_base__FGAmmoTypeInstantHit__standard__pre_1_1__type,
} from '../../common/unassigned';

import {common_base__FGAmmoTypeProjectile__base__type} from './FGAmmoTypeProjectile';

export type common_base__FGAmmoTypeInstantHit__base__type =
	common_base__FGAmmoTypeProjectile__base__type &
		common_base__FGAmmoTypeInstantHit__base__pre_1_1__type;

export type common_base__FGAmmoTypeInstantHit__chaos__type =
	common_base__FGAmmoTypeInstantHit__base__type &
		common_base__FGAmmoTypeInstantHit__chaos__pre_1_1__type;

export type common_base__FGAmmoTypeInstantHit__standard__type =
	common_base__FGAmmoTypeInstantHit__base__type &
		common_base__FGAmmoTypeInstantHit__standard__pre_1_1__type;
