import {common_base__FGItemDescriptor__FGResourceDescriptor__type} from './FGItemDescriptor.ts';

export type common_base__FGItemDescriptorBiomass__type =
	common_base__FGItemDescriptor__FGResourceDescriptor__type;
